import SymmetricSubgroupAsymptotics.GeneratedNormal8.Registry8T6
import SymmetricSubgroupAsymptotics.GeneratedNormal8.Registry8T7
import SymmetricSubgroupAsymptotics.GeneratedNormal8.Registry8T8
import SymmetricSubgroupAsymptotics.GeneratedNormal8.Registry8T11
import SymmetricSubgroupAsymptotics.GeneratedNormal8.Registry8T15
import SymmetricSubgroupAsymptotics.GeneratedNormal8.Registry8T16
import SymmetricSubgroupAsymptotics.GeneratedNormal8.Registry8T17
import SymmetricSubgroupAsymptotics.GeneratedNormal8.Registry8T19
import SymmetricSubgroupAsymptotics.GeneratedNormal8.Registry8T20
import SymmetricSubgroupAsymptotics.GeneratedNormal8.Registry8T21
import SymmetricSubgroupAsymptotics.GeneratedNormal8.Registry8T22

/-! Kernel-checked exclusions used by the degree-sixteen split classifier.
Generated by export_lean_elementary_top_exclusions.py. -/
set_option autoImplicit false
set_option maxHeartbeats 0
set_option maxRecDepth 100000
noncomputable section

namespace SymmetricSubgroupAsymptotics.BinaryNormal8T6
local instance : Group Source := BinaryMenuCayley8T6.group

/-- No registered normal of this literal action is both index two
and elementary abelian.  Every negative row carries a checked witness. -/
theorem no_elementary_index_two (j : Fin 7) :
    (states j).quotientCount≠2 ∨
      ∃ x : (states j).kernel,x^2≠1 := by
  fin_cases j
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · right
    refine ⟨⟨(⟨(2 : Fin 16)⟩ : Source),?_⟩,?_⟩
    · have hm := N3.row_mem (1 : Fin 8)
      change (⟨(2 : Fin 16)⟩ : Source)∈N3.kernel at hm
      exact hm
    · intro hsquare
      have hne : ((⟨(2 : Fin 16)⟩ : Source))^2≠(1 : Source) := by decide +kernel
      exact hne (congrArg Subtype.val hsquare)
  · right
    refine ⟨⟨(⟨(2 : Fin 16)⟩ : Source),?_⟩,?_⟩
    · have hm := N4.row_mem (0 : Fin 8)
      change (⟨(2 : Fin 16)⟩ : Source)∈N4.kernel at hm
      exact hm
    · intro hsquare
      have hne : ((⟨(2 : Fin 16)⟩ : Source))^2≠(1 : Source) := by decide +kernel
      exact hne (congrArg Subtype.val hsquare)
  · right
    refine ⟨⟨(⟨(1 : Fin 16)⟩ : Source),?_⟩,?_⟩
    · have hm := N5.row_mem (0 : Fin 8)
      change (⟨(1 : Fin 16)⟩ : Source)∈N5.kernel at hm
      exact hm
    · intro hsquare
      have hne : ((⟨(1 : Fin 16)⟩ : Source))^2≠(1 : Source) := by decide +kernel
      exact hne (congrArg Subtype.val hsquare)
  · left
    decide +kernel

end SymmetricSubgroupAsymptotics.BinaryNormal8T6

namespace SymmetricSubgroupAsymptotics.BinaryNormal8T7
local instance : Group Source := BinaryMenuCayley8T7.group

/-- No registered normal of this literal action is both index two
and elementary abelian.  Every negative row carries a checked witness. -/
theorem no_elementary_index_two (j : Fin 9) :
    (states j).quotientCount≠2 ∨
      ∃ x : (states j).kernel,x^2≠1 := by
  fin_cases j
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · right
    refine ⟨⟨(⟨(0 : Fin 16)⟩ : Source),?_⟩,?_⟩
    · have hm := N5.row_mem (0 : Fin 8)
      change (⟨(0 : Fin 16)⟩ : Source)∈N5.kernel at hm
      exact hm
    · intro hsquare
      have hne : ((⟨(0 : Fin 16)⟩ : Source))^2≠(1 : Source) := by decide +kernel
      exact hne (congrArg Subtype.val hsquare)
  · right
    refine ⟨⟨(⟨(2 : Fin 16)⟩ : Source),?_⟩,?_⟩
    · have hm := N6.row_mem (0 : Fin 8)
      change (⟨(2 : Fin 16)⟩ : Source)∈N6.kernel at hm
      exact hm
    · intro hsquare
      have hne : ((⟨(2 : Fin 16)⟩ : Source))^2≠(1 : Source) := by decide +kernel
      exact hne (congrArg Subtype.val hsquare)
  · right
    refine ⟨⟨(⟨(1 : Fin 16)⟩ : Source),?_⟩,?_⟩
    · have hm := N7.row_mem (0 : Fin 8)
      change (⟨(1 : Fin 16)⟩ : Source)∈N7.kernel at hm
      exact hm
    · intro hsquare
      have hne : ((⟨(1 : Fin 16)⟩ : Source))^2≠(1 : Source) := by decide +kernel
      exact hne (congrArg Subtype.val hsquare)
  · left
    decide +kernel

end SymmetricSubgroupAsymptotics.BinaryNormal8T7

namespace SymmetricSubgroupAsymptotics.BinaryNormal8T8
local instance : Group Source := BinaryMenuCayley8T8.group

/-- No registered normal of this literal action is both index two
and elementary abelian.  Every negative row carries a checked witness. -/
theorem no_elementary_index_two (j : Fin 7) :
    (states j).quotientCount≠2 ∨
      ∃ x : (states j).kernel,x^2≠1 := by
  fin_cases j
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · right
    refine ⟨⟨(⟨(0 : Fin 16)⟩ : Source),?_⟩,?_⟩
    · have hm := N3.row_mem (0 : Fin 8)
      change (⟨(0 : Fin 16)⟩ : Source)∈N3.kernel at hm
      exact hm
    · intro hsquare
      have hne : ((⟨(0 : Fin 16)⟩ : Source))^2≠(1 : Source) := by decide +kernel
      exact hne (congrArg Subtype.val hsquare)
  · right
    refine ⟨⟨(⟨(2 : Fin 16)⟩ : Source),?_⟩,?_⟩
    · have hm := N4.row_mem (0 : Fin 8)
      change (⟨(2 : Fin 16)⟩ : Source)∈N4.kernel at hm
      exact hm
    · intro hsquare
      have hne : ((⟨(2 : Fin 16)⟩ : Source))^2≠(1 : Source) := by decide +kernel
      exact hne (congrArg Subtype.val hsquare)
  · right
    refine ⟨⟨(⟨(1 : Fin 16)⟩ : Source),?_⟩,?_⟩
    · have hm := N5.row_mem (0 : Fin 8)
      change (⟨(1 : Fin 16)⟩ : Source)∈N5.kernel at hm
      exact hm
    · intro hsquare
      have hne : ((⟨(1 : Fin 16)⟩ : Source))^2≠(1 : Source) := by decide +kernel
      exact hne (congrArg Subtype.val hsquare)
  · left
    decide +kernel

end SymmetricSubgroupAsymptotics.BinaryNormal8T8

namespace SymmetricSubgroupAsymptotics.BinaryNormal8T11
local instance : Group Source := BinaryMenuCayley8T11.group

/-- No registered normal of this literal action is both index two
and elementary abelian.  Every negative row carries a checked witness. -/
theorem no_elementary_index_two (j : Fin 17) :
    (states j).quotientCount≠2 ∨
      ∃ x : (states j).kernel,x^2≠1 := by
  fin_cases j
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · right
    refine ⟨⟨(⟨(3 : Fin 16)⟩ : Source),?_⟩,?_⟩
    · have hm := N8.row_mem (1 : Fin 8)
      change (⟨(3 : Fin 16)⟩ : Source)∈N8.kernel at hm
      exact hm
    · intro hsquare
      have hne : ((⟨(3 : Fin 16)⟩ : Source))^2≠(1 : Source) := by decide +kernel
      exact hne (congrArg Subtype.val hsquare)
  · right
    refine ⟨⟨(⟨(2 : Fin 16)⟩ : Source),?_⟩,?_⟩
    · have hm := N9.row_mem (1 : Fin 8)
      change (⟨(2 : Fin 16)⟩ : Source)∈N9.kernel at hm
      exact hm
    · intro hsquare
      have hne : ((⟨(2 : Fin 16)⟩ : Source))^2≠(1 : Source) := by decide +kernel
      exact hne (congrArg Subtype.val hsquare)
  · right
    refine ⟨⟨(⟨(0 : Fin 16)⟩ : Source),?_⟩,?_⟩
    · have hm := N10.row_mem (0 : Fin 8)
      change (⟨(0 : Fin 16)⟩ : Source)∈N10.kernel at hm
      exact hm
    · intro hsquare
      have hne : ((⟨(0 : Fin 16)⟩ : Source))^2≠(1 : Source) := by decide +kernel
      exact hne (congrArg Subtype.val hsquare)
  · right
    refine ⟨⟨(⟨(0 : Fin 16)⟩ : Source),?_⟩,?_⟩
    · have hm := N11.row_mem (0 : Fin 8)
      change (⟨(0 : Fin 16)⟩ : Source)∈N11.kernel at hm
      exact hm
    · intro hsquare
      have hne : ((⟨(0 : Fin 16)⟩ : Source))^2≠(1 : Source) := by decide +kernel
      exact hne (congrArg Subtype.val hsquare)
  · left
    decide +kernel
  · right
    refine ⟨⟨(⟨(5 : Fin 16)⟩ : Source),?_⟩,?_⟩
    · have hm := N13.row_mem (1 : Fin 8)
      change (⟨(5 : Fin 16)⟩ : Source)∈N13.kernel at hm
      exact hm
    · intro hsquare
      have hne : ((⟨(5 : Fin 16)⟩ : Source))^2≠(1 : Source) := by decide +kernel
      exact hne (congrArg Subtype.val hsquare)
  · right
    refine ⟨⟨(⟨(0 : Fin 16)⟩ : Source),?_⟩,?_⟩
    · have hm := N14.row_mem (0 : Fin 8)
      change (⟨(0 : Fin 16)⟩ : Source)∈N14.kernel at hm
      exact hm
    · intro hsquare
      have hne : ((⟨(0 : Fin 16)⟩ : Source))^2≠(1 : Source) := by decide +kernel
      exact hne (congrArg Subtype.val hsquare)
  · right
    refine ⟨⟨(⟨(2 : Fin 16)⟩ : Source),?_⟩,?_⟩
    · have hm := N15.row_mem (0 : Fin 8)
      change (⟨(2 : Fin 16)⟩ : Source)∈N15.kernel at hm
      exact hm
    · intro hsquare
      have hne : ((⟨(2 : Fin 16)⟩ : Source))^2≠(1 : Source) := by decide +kernel
      exact hne (congrArg Subtype.val hsquare)
  · left
    decide +kernel

end SymmetricSubgroupAsymptotics.BinaryNormal8T11

namespace SymmetricSubgroupAsymptotics.BinaryNormal8T15
local instance : Group Source := BinaryMenuCayley8T15.group

/-- No registered normal of this literal action is both index two
and elementary abelian.  Every negative row carries a checked witness. -/
theorem no_elementary_index_two (j : Fin 20) :
    (states j).quotientCount≠2 ∨
      ∃ x : (states j).kernel,x^2≠1 := by
  fin_cases j
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · right
    refine ⟨⟨(⟨(1 : Fin 32)⟩ : Source),?_⟩,?_⟩
    · have hm := N11.row_mem (1 : Fin 16)
      change (⟨(1 : Fin 32)⟩ : Source)∈N11.kernel at hm
      exact hm
    · intro hsquare
      have hne : ((⟨(1 : Fin 32)⟩ : Source))^2≠(1 : Source) := by decide +kernel
      exact hne (congrArg Subtype.val hsquare)
  · right
    refine ⟨⟨(⟨(2 : Fin 32)⟩ : Source),?_⟩,?_⟩
    · have hm := N12.row_mem (1 : Fin 16)
      change (⟨(2 : Fin 32)⟩ : Source)∈N12.kernel at hm
      exact hm
    · intro hsquare
      have hne : ((⟨(2 : Fin 32)⟩ : Source))^2≠(1 : Source) := by decide +kernel
      exact hne (congrArg Subtype.val hsquare)
  · right
    refine ⟨⟨(⟨(1 : Fin 32)⟩ : Source),?_⟩,?_⟩
    · have hm := N13.row_mem (0 : Fin 16)
      change (⟨(1 : Fin 32)⟩ : Source)∈N13.kernel at hm
      exact hm
    · intro hsquare
      have hne : ((⟨(1 : Fin 32)⟩ : Source))^2≠(1 : Source) := by decide +kernel
      exact hne (congrArg Subtype.val hsquare)
  · right
    refine ⟨⟨(⟨(4 : Fin 32)⟩ : Source),?_⟩,?_⟩
    · have hm := N14.row_mem (0 : Fin 16)
      change (⟨(4 : Fin 32)⟩ : Source)∈N14.kernel at hm
      exact hm
    · intro hsquare
      have hne : ((⟨(4 : Fin 32)⟩ : Source))^2≠(1 : Source) := by decide +kernel
      exact hne (congrArg Subtype.val hsquare)
  · left
    decide +kernel
  · right
    refine ⟨⟨(⟨(2 : Fin 32)⟩ : Source),?_⟩,?_⟩
    · have hm := N16.row_mem (0 : Fin 16)
      change (⟨(2 : Fin 32)⟩ : Source)∈N16.kernel at hm
      exact hm
    · intro hsquare
      have hne : ((⟨(2 : Fin 32)⟩ : Source))^2≠(1 : Source) := by decide +kernel
      exact hne (congrArg Subtype.val hsquare)
  · right
    refine ⟨⟨(⟨(3 : Fin 32)⟩ : Source),?_⟩,?_⟩
    · have hm := N17.row_mem (1 : Fin 16)
      change (⟨(3 : Fin 32)⟩ : Source)∈N17.kernel at hm
      exact hm
    · intro hsquare
      have hne : ((⟨(3 : Fin 32)⟩ : Source))^2≠(1 : Source) := by decide +kernel
      exact hne (congrArg Subtype.val hsquare)
  · right
    refine ⟨⟨(⟨(1 : Fin 32)⟩ : Source),?_⟩,?_⟩
    · have hm := N18.row_mem (0 : Fin 16)
      change (⟨(1 : Fin 32)⟩ : Source)∈N18.kernel at hm
      exact hm
    · intro hsquare
      have hne : ((⟨(1 : Fin 32)⟩ : Source))^2≠(1 : Source) := by decide +kernel
      exact hne (congrArg Subtype.val hsquare)
  · left
    decide +kernel

end SymmetricSubgroupAsymptotics.BinaryNormal8T15

namespace SymmetricSubgroupAsymptotics.BinaryNormal8T16
local instance : Group Source := BinaryMenuCayley8T16.group

/-- No registered normal of this literal action is both index two
and elementary abelian.  Every negative row carries a checked witness. -/
theorem no_elementary_index_two (j : Fin 12) :
    (states j).quotientCount≠2 ∨
      ∃ x : (states j).kernel,x^2≠1 := by
  fin_cases j
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · right
    refine ⟨⟨(⟨(0 : Fin 32)⟩ : Source),?_⟩,?_⟩
    · have hm := N7.row_mem (0 : Fin 16)
      change (⟨(0 : Fin 32)⟩ : Source)∈N7.kernel at hm
      exact hm
    · intro hsquare
      have hne : ((⟨(0 : Fin 32)⟩ : Source))^2≠(1 : Source) := by decide +kernel
      exact hne (congrArg Subtype.val hsquare)
  · right
    refine ⟨⟨(⟨(1 : Fin 32)⟩ : Source),?_⟩,?_⟩
    · have hm := N8.row_mem (0 : Fin 16)
      change (⟨(1 : Fin 32)⟩ : Source)∈N8.kernel at hm
      exact hm
    · intro hsquare
      have hne : ((⟨(1 : Fin 32)⟩ : Source))^2≠(1 : Source) := by decide +kernel
      exact hne (congrArg Subtype.val hsquare)
  · left
    decide +kernel
  · right
    refine ⟨⟨(⟨(5 : Fin 32)⟩ : Source),?_⟩,?_⟩
    · have hm := N10.row_mem (1 : Fin 16)
      change (⟨(5 : Fin 32)⟩ : Source)∈N10.kernel at hm
      exact hm
    · intro hsquare
      have hne : ((⟨(5 : Fin 32)⟩ : Source))^2≠(1 : Source) := by decide +kernel
      exact hne (congrArg Subtype.val hsquare)
  · left
    decide +kernel

end SymmetricSubgroupAsymptotics.BinaryNormal8T16

namespace SymmetricSubgroupAsymptotics.BinaryNormal8T17
local instance : Group Source := BinaryMenuCayley8T17.group

/-- No registered normal of this literal action is both index two
and elementary abelian.  Every negative row carries a checked witness. -/
theorem no_elementary_index_two (j : Fin 12) :
    (states j).quotientCount≠2 ∨
      ∃ x : (states j).kernel,x^2≠1 := by
  fin_cases j
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · right
    refine ⟨⟨(⟨(0 : Fin 32)⟩ : Source),?_⟩,?_⟩
    · have hm := N8.row_mem (0 : Fin 16)
      change (⟨(0 : Fin 32)⟩ : Source)∈N8.kernel at hm
      exact hm
    · intro hsquare
      have hne : ((⟨(0 : Fin 32)⟩ : Source))^2≠(1 : Source) := by decide +kernel
      exact hne (congrArg Subtype.val hsquare)
  · right
    refine ⟨⟨(⟨(0 : Fin 32)⟩ : Source),?_⟩,?_⟩
    · have hm := N9.row_mem (0 : Fin 16)
      change (⟨(0 : Fin 32)⟩ : Source)∈N9.kernel at hm
      exact hm
    · intro hsquare
      have hne : ((⟨(0 : Fin 32)⟩ : Source))^2≠(1 : Source) := by decide +kernel
      exact hne (congrArg Subtype.val hsquare)
  · right
    refine ⟨⟨(⟨(0 : Fin 32)⟩ : Source),?_⟩,?_⟩
    · have hm := N10.row_mem (0 : Fin 16)
      change (⟨(0 : Fin 32)⟩ : Source)∈N10.kernel at hm
      exact hm
    · intro hsquare
      have hne : ((⟨(0 : Fin 32)⟩ : Source))^2≠(1 : Source) := by decide +kernel
      exact hne (congrArg Subtype.val hsquare)
  · left
    decide +kernel

end SymmetricSubgroupAsymptotics.BinaryNormal8T17

namespace SymmetricSubgroupAsymptotics.BinaryNormal8T19
local instance : Group Source := BinaryMenuCayley8T19.group

/-- No registered normal of this literal action is both index two
and elementary abelian.  Every negative row carries a checked witness. -/
theorem no_elementary_index_two (j : Fin 12) :
    (states j).quotientCount≠2 ∨
      ∃ x : (states j).kernel,x^2≠1 := by
  fin_cases j
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · right
    refine ⟨⟨(⟨(13 : Fin 32)⟩ : Source),?_⟩,?_⟩
    · have hm := N7.row_mem (6 : Fin 16)
      change (⟨(13 : Fin 32)⟩ : Source)∈N7.kernel at hm
      exact hm
    · intro hsquare
      have hne : ((⟨(13 : Fin 32)⟩ : Source))^2≠(1 : Source) := by decide +kernel
      exact hne (congrArg Subtype.val hsquare)
  · right
    refine ⟨⟨(⟨(1 : Fin 32)⟩ : Source),?_⟩,?_⟩
    · have hm := N8.row_mem (1 : Fin 16)
      change (⟨(1 : Fin 32)⟩ : Source)∈N8.kernel at hm
      exact hm
    · intro hsquare
      have hne : ((⟨(1 : Fin 32)⟩ : Source))^2≠(1 : Source) := by decide +kernel
      exact hne (congrArg Subtype.val hsquare)
  · left
    decide +kernel
  · right
    refine ⟨⟨(⟨(12 : Fin 32)⟩ : Source),?_⟩,?_⟩
    · have hm := N10.row_mem (6 : Fin 16)
      change (⟨(12 : Fin 32)⟩ : Source)∈N10.kernel at hm
      exact hm
    · intro hsquare
      have hne : ((⟨(12 : Fin 32)⟩ : Source))^2≠(1 : Source) := by decide +kernel
      exact hne (congrArg Subtype.val hsquare)
  · left
    decide +kernel

end SymmetricSubgroupAsymptotics.BinaryNormal8T19

namespace SymmetricSubgroupAsymptotics.BinaryNormal8T20
local instance : Group Source := BinaryMenuCayley8T20.group

/-- No registered normal of this literal action is both index two
and elementary abelian.  Every negative row carries a checked witness. -/
theorem no_elementary_index_two (j : Fin 12) :
    (states j).quotientCount≠2 ∨
      ∃ x : (states j).kernel,x^2≠1 := by
  fin_cases j
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · right
    refine ⟨⟨(⟨(0 : Fin 32)⟩ : Source),?_⟩,?_⟩
    · have hm := N7.row_mem (0 : Fin 16)
      change (⟨(0 : Fin 32)⟩ : Source)∈N7.kernel at hm
      exact hm
    · intro hsquare
      have hne : ((⟨(0 : Fin 32)⟩ : Source))^2≠(1 : Source) := by decide +kernel
      exact hne (congrArg Subtype.val hsquare)
  · right
    refine ⟨⟨(⟨(1 : Fin 32)⟩ : Source),?_⟩,?_⟩
    · have hm := N8.row_mem (0 : Fin 16)
      change (⟨(1 : Fin 32)⟩ : Source)∈N8.kernel at hm
      exact hm
    · intro hsquare
      have hne : ((⟨(1 : Fin 32)⟩ : Source))^2≠(1 : Source) := by decide +kernel
      exact hne (congrArg Subtype.val hsquare)
  · left
    decide +kernel
  · right
    refine ⟨⟨(⟨(5 : Fin 32)⟩ : Source),?_⟩,?_⟩
    · have hm := N10.row_mem (1 : Fin 16)
      change (⟨(5 : Fin 32)⟩ : Source)∈N10.kernel at hm
      exact hm
    · intro hsquare
      have hne : ((⟨(5 : Fin 32)⟩ : Source))^2≠(1 : Source) := by decide +kernel
      exact hne (congrArg Subtype.val hsquare)
  · left
    decide +kernel

end SymmetricSubgroupAsymptotics.BinaryNormal8T20

namespace SymmetricSubgroupAsymptotics.BinaryNormal8T21
local instance : Group Source := BinaryMenuCayley8T21.group

/-- No registered normal of this literal action is both index two
and elementary abelian.  Every negative row carries a checked witness. -/
theorem no_elementary_index_two (j : Fin 12) :
    (states j).quotientCount≠2 ∨
      ∃ x : (states j).kernel,x^2≠1 := by
  fin_cases j
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · right
    refine ⟨⟨(⟨(8 : Fin 32)⟩ : Source),?_⟩,?_⟩
    · have hm := N8.row_mem (0 : Fin 16)
      change (⟨(8 : Fin 32)⟩ : Source)∈N8.kernel at hm
      exact hm
    · intro hsquare
      have hne : ((⟨(8 : Fin 32)⟩ : Source))^2≠(1 : Source) := by decide +kernel
      exact hne (congrArg Subtype.val hsquare)
  · right
    refine ⟨⟨(⟨(5 : Fin 32)⟩ : Source),?_⟩,?_⟩
    · have hm := N9.row_mem (1 : Fin 16)
      change (⟨(5 : Fin 32)⟩ : Source)∈N9.kernel at hm
      exact hm
    · intro hsquare
      have hne : ((⟨(5 : Fin 32)⟩ : Source))^2≠(1 : Source) := by decide +kernel
      exact hne (congrArg Subtype.val hsquare)
  · right
    refine ⟨⟨(⟨(0 : Fin 32)⟩ : Source),?_⟩,?_⟩
    · have hm := N10.row_mem (0 : Fin 16)
      change (⟨(0 : Fin 32)⟩ : Source)∈N10.kernel at hm
      exact hm
    · intro hsquare
      have hne : ((⟨(0 : Fin 32)⟩ : Source))^2≠(1 : Source) := by decide +kernel
      exact hne (congrArg Subtype.val hsquare)
  · left
    decide +kernel

end SymmetricSubgroupAsymptotics.BinaryNormal8T21

namespace SymmetricSubgroupAsymptotics.BinaryNormal8T22
local instance : Group Source := BinaryMenuCayley8T22.group

/-- No registered normal of this literal action is both index two
and elementary abelian.  Every negative row carries a checked witness. -/
theorem no_elementary_index_two (j : Fin 68) :
    (states j).quotientCount≠2 ∨
      ∃ x : (states j).kernel,x^2≠1 := by
  fin_cases j
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · left
    decide +kernel
  · right
    refine ⟨⟨(⟨(5 : Fin 32)⟩ : Source),?_⟩,?_⟩
    · have hm := N52.row_mem (5 : Fin 16)
      change (⟨(5 : Fin 32)⟩ : Source)∈N52.kernel at hm
      exact hm
    · intro hsquare
      have hne : ((⟨(5 : Fin 32)⟩ : Source))^2≠(1 : Source) := by decide +kernel
      exact hne (congrArg Subtype.val hsquare)
  · right
    refine ⟨⟨(⟨(13 : Fin 32)⟩ : Source),?_⟩,?_⟩
    · have hm := N53.row_mem (5 : Fin 16)
      change (⟨(13 : Fin 32)⟩ : Source)∈N53.kernel at hm
      exact hm
    · intro hsquare
      have hne : ((⟨(13 : Fin 32)⟩ : Source))^2≠(1 : Source) := by decide +kernel
      exact hne (congrArg Subtype.val hsquare)
  · right
    refine ⟨⟨(⟨(22 : Fin 32)⟩ : Source),?_⟩,?_⟩
    · have hm := N54.row_mem (6 : Fin 16)
      change (⟨(22 : Fin 32)⟩ : Source)∈N54.kernel at hm
      exact hm
    · intro hsquare
      have hne : ((⟨(22 : Fin 32)⟩ : Source))^2≠(1 : Source) := by decide +kernel
      exact hne (congrArg Subtype.val hsquare)
  · right
    refine ⟨⟨(⟨(15 : Fin 32)⟩ : Source),?_⟩,?_⟩
    · have hm := N55.row_mem (7 : Fin 16)
      change (⟨(15 : Fin 32)⟩ : Source)∈N55.kernel at hm
      exact hm
    · intro hsquare
      have hne : ((⟨(15 : Fin 32)⟩ : Source))^2≠(1 : Source) := by decide +kernel
      exact hne (congrArg Subtype.val hsquare)
  · right
    refine ⟨⟨(⟨(13 : Fin 32)⟩ : Source),?_⟩,?_⟩
    · have hm := N56.row_mem (6 : Fin 16)
      change (⟨(13 : Fin 32)⟩ : Source)∈N56.kernel at hm
      exact hm
    · intro hsquare
      have hne : ((⟨(13 : Fin 32)⟩ : Source))^2≠(1 : Source) := by decide +kernel
      exact hne (congrArg Subtype.val hsquare)
  · right
    refine ⟨⟨(⟨(5 : Fin 32)⟩ : Source),?_⟩,?_⟩
    · have hm := N57.row_mem (2 : Fin 16)
      change (⟨(5 : Fin 32)⟩ : Source)∈N57.kernel at hm
      exact hm
    · intro hsquare
      have hne : ((⟨(5 : Fin 32)⟩ : Source))^2≠(1 : Source) := by decide +kernel
      exact hne (congrArg Subtype.val hsquare)
  · right
    refine ⟨⟨(⟨(5 : Fin 32)⟩ : Source),?_⟩,?_⟩
    · have hm := N58.row_mem (2 : Fin 16)
      change (⟨(5 : Fin 32)⟩ : Source)∈N58.kernel at hm
      exact hm
    · intro hsquare
      have hne : ((⟨(5 : Fin 32)⟩ : Source))^2≠(1 : Source) := by decide +kernel
      exact hne (congrArg Subtype.val hsquare)
  · right
    refine ⟨⟨(⟨(6 : Fin 32)⟩ : Source),?_⟩,?_⟩
    · have hm := N59.row_mem (3 : Fin 16)
      change (⟨(6 : Fin 32)⟩ : Source)∈N59.kernel at hm
      exact hm
    · intro hsquare
      have hne : ((⟨(6 : Fin 32)⟩ : Source))^2≠(1 : Source) := by decide +kernel
      exact hne (congrArg Subtype.val hsquare)
  · right
    refine ⟨⟨(⟨(6 : Fin 32)⟩ : Source),?_⟩,?_⟩
    · have hm := N60.row_mem (3 : Fin 16)
      change (⟨(6 : Fin 32)⟩ : Source)∈N60.kernel at hm
      exact hm
    · intro hsquare
      have hne : ((⟨(6 : Fin 32)⟩ : Source))^2≠(1 : Source) := by decide +kernel
      exact hne (congrArg Subtype.val hsquare)
  · right
    refine ⟨⟨(⟨(5 : Fin 32)⟩ : Source),?_⟩,?_⟩
    · have hm := N61.row_mem (2 : Fin 16)
      change (⟨(5 : Fin 32)⟩ : Source)∈N61.kernel at hm
      exact hm
    · intro hsquare
      have hne : ((⟨(5 : Fin 32)⟩ : Source))^2≠(1 : Source) := by decide +kernel
      exact hne (congrArg Subtype.val hsquare)
  · right
    refine ⟨⟨(⟨(5 : Fin 32)⟩ : Source),?_⟩,?_⟩
    · have hm := N62.row_mem (2 : Fin 16)
      change (⟨(5 : Fin 32)⟩ : Source)∈N62.kernel at hm
      exact hm
    · intro hsquare
      have hne : ((⟨(5 : Fin 32)⟩ : Source))^2≠(1 : Source) := by decide +kernel
      exact hne (congrArg Subtype.val hsquare)
  · right
    refine ⟨⟨(⟨(5 : Fin 32)⟩ : Source),?_⟩,?_⟩
    · have hm := N63.row_mem (3 : Fin 16)
      change (⟨(5 : Fin 32)⟩ : Source)∈N63.kernel at hm
      exact hm
    · intro hsquare
      have hne : ((⟨(5 : Fin 32)⟩ : Source))^2≠(1 : Source) := by decide +kernel
      exact hne (congrArg Subtype.val hsquare)
  · right
    refine ⟨⟨(⟨(5 : Fin 32)⟩ : Source),?_⟩,?_⟩
    · have hm := N64.row_mem (3 : Fin 16)
      change (⟨(5 : Fin 32)⟩ : Source)∈N64.kernel at hm
      exact hm
    · intro hsquare
      have hne : ((⟨(5 : Fin 32)⟩ : Source))^2≠(1 : Source) := by decide +kernel
      exact hne (congrArg Subtype.val hsquare)
  · right
    refine ⟨⟨(⟨(6 : Fin 32)⟩ : Source),?_⟩,?_⟩
    · have hm := N65.row_mem (2 : Fin 16)
      change (⟨(6 : Fin 32)⟩ : Source)∈N65.kernel at hm
      exact hm
    · intro hsquare
      have hne : ((⟨(6 : Fin 32)⟩ : Source))^2≠(1 : Source) := by decide +kernel
      exact hne (congrArg Subtype.val hsquare)
  · right
    refine ⟨⟨(⟨(6 : Fin 32)⟩ : Source),?_⟩,?_⟩
    · have hm := N66.row_mem (2 : Fin 16)
      change (⟨(6 : Fin 32)⟩ : Source)∈N66.kernel at hm
      exact hm
    · intro hsquare
      have hne : ((⟨(6 : Fin 32)⟩ : Source))^2≠(1 : Source) := by decide +kernel
      exact hne (congrArg Subtype.val hsquare)
  · left
    decide +kernel

end SymmetricSubgroupAsymptotics.BinaryNormal8T22
