import SymmetricSubgroupAsymptotics.ActualWreathAffineCapacity
import SymmetricSubgroupAsymptotics.BinaryPairResidualTop
import SymmetricSubgroupAsymptotics.DualGeneratorInvariantCapacity
import SymmetricSubgroupAsymptotics.PrimeCentralJointElementaryEnvelope

/-!
# Prime-cut capacity on an actual affine wreath layer

The common refined primal/dual tuple controls both pieces of the invariant
cut: the literal fixed radical and the Schur capacity of the quotient by that
radical.  This module builds the joint capacity used by the same-source prime
moment without replacing the correlated wreath kernel by a full product.
-/

set_option autoImplicit false
set_option backward.isDefEq.respectTransparency false
set_option linter.unusedSectionVars false
set_option maxHeartbeats 2000000
noncomputable section
open scoped BigOperators Classical MonoidAlgebra

namespace SymmetricSubgroupAsymptotics
namespace ActualWreathAffineCapacity

attribute [-instance] originalNormalFintype

variable {Q I : Type} [Group Q] [Fintype I] [Nonempty I]
  [MulAction Q I] [FaithfulSMul Q I]

variable (S : ActualWreathCompressionState Q I)
  {D' : Type} [Group D'] [Finite D']
  (phi : S.D →* D') (hphi : Function.Surjective phi)
  (C : ElementaryMinimalNormalChart phi.ker)

section NormalSection

variable (N : Subgroup S.A) [N.Normal]
variable (i₀ : I) (D : RefinedCapacityData S phi C i₀)

private abbrev sectionRep :=
  (originalChart S phi C).sectionRepresentation
    (pi S phi) (E S phi C).quotientRepresentation N

private abbrev invariantCut :
    {W : Submodule (ZMod C.p) (sectionRep S phi C N) //
      W ≤ (sectionRep S phi C N).ρ.invariants} :=
  ⟨(sectionRep S phi C N).ρ.invariants, le_rfl⟩

/-- The dual of every inflated literal normal section is generated by the
common refined tuple. -/
theorem inflatedSectionDual_generated_refined :
    RepresentationGeneratedBy
      (inflatedSectionRepresentation S phi C N).dual D.H := by
  letI : FiniteDimensional (ZMod C.p)
      (PermutationalWreathProduct.Compression.ElementarySubmodule (p := C.p)
        S.rho phi C.equiv.symm) := inferInstance
  letI : FiniteDimensional (ZMod (E S phi C).p) (E S phi C).V :=
    (E S phi C).finiteDimensional
  letI : FiniteDimensional (ZMod C.p)
      ((originalChart S phi C).sectionRepresentation
        (pi S phi) (E S phi C).quotientRepresentation N) := by
    change FiniteDimensional (ZMod (E S phi C).p)
      ((E S phi C).V ⧸
        (originalChart S phi C).normalSpace
          (pi S phi) (E S phi C).quotientRepresentation N)
    infer_instance
  exact representationDual_generated_of_subquotient
    D.dual
    (inducedIntertwiner S phi C i₀)
    (inducedIntertwiner_injective S phi C i₀)
    (sectionQuotientIntertwiner S phi C N)
    (sectionQuotientIntertwiner_surjective S phi C N)

/-- The fixed radical of every literal section has dimension bounded by the
same common tuple length. -/
theorem section_invariants_finrank_le_refined :
    Module.finrank (ZMod C.p) (sectionRep S phi C N).ρ.invariants ≤ D.H := by
  letI : FiniteDimensional (ZMod C.p)
      (PermutationalWreathProduct.Compression.ElementarySubmodule (p := C.p)
        S.rho phi C.equiv.symm) := inferInstance
  letI : FiniteDimensional (ZMod (E S phi C).p) (E S phi C).V :=
    (E S phi C).finiteDimensional
  letI : FiniteDimensional (ZMod C.p) (sectionRep S phi C N) := by
    change FiniteDimensional (ZMod (E S phi C).p)
      ((E S phi C).V ⧸
        (originalChart S phi C).normalSpace
          (pi S phi) (E S phi C).quotientRepresentation N)
    infer_instance
  let gamma : S.A →* S.A ⧸ ((pi S phi).ker ⊔ N) :=
    QuotientGroup.mk' ((pi S phi).ker ⊔ N)
  have hfixed := invariants_finrank_le_of_dual_generated
    (inflatedSectionRepresentation S phi C N) D.H
    (inflatedSectionDual_generated_refined S phi C N i₀ D)
  have heq := representation_invariants_comp_onto
    (sectionRep S phi C N).ρ gamma
    (QuotientGroup.mk'_surjective ((pi S phi).ker ⊔ N))
  change Module.finrank (ZMod C.p)
    (Representation.invariants ((sectionRep S phi C N).ρ.comp gamma)) ≤ D.H at hfixed
  rw [heq] at hfixed
  exact hfixed

private def quotientIntertwiner :
    (inflatedSectionRepresentation S phi C N).IntertwiningMap
      ((OriginalCentralCutExtension.quotientModule
        (sectionRep S phi C N) (invariantCut S phi C N)).ρ.comp
          (QuotientGroup.mk' ((pi S phi).ker ⊔ N))) where
  toLinearMap := (sectionRep S phi C N).ρ.invariants.mkQ
  isIntertwining' _ := rfl

private theorem quotientIntertwiner_surjective :
    Function.Surjective (quotientIntertwiner S phi C N) :=
  (sectionRep S phi C N).ρ.invariants.mkQ_surjective

/-- Quotienting by the whole invariant radical leaves Schur capacity at most
the same refined tuple length. -/
theorem invariantQuotient_schurCapacity_le_refined :
    representationSchurCapacity
      (OriginalCentralCutExtension.quotientModule
        (sectionRep S phi C N) (invariantCut S phi C N)).ρ ≤ D.H := by
  let M := sectionRep S phi C N
  let W := OriginalCentralCutExtension.quotientModule M
    (invariantCut S phi C N)
  letI : FiniteDimensional (ZMod C.p)
      (PermutationalWreathProduct.Compression.ElementarySubmodule (p := C.p)
        S.rho phi C.equiv.symm) := inferInstance
  letI : FiniteDimensional (ZMod (E S phi C).p) (E S phi C).V :=
    (E S phi C).finiteDimensional
  letI : FiniteDimensional (ZMod (E S phi C).p) M := by
    change FiniteDimensional (ZMod (E S phi C).p)
      ((E S phi C).V ⧸
        (originalChart S phi C).normalSpace
          (pi S phi) (E S phi C).quotientRepresentation N)
    infer_instance
  letI : FiniteDimensional (ZMod (E S phi C).p) W := by
    change FiniteDimensional (ZMod (E S phi C).p)
      (M ⧸ (invariantCut S phi C N).1)
    infer_instance
  let gamma : S.A →* S.A ⧸ ((pi S phi).ker ⊔ N) :=
    QuotientGroup.mk' ((pi S phi).ker ⊔ N)
  let tau : Representation (ZMod (E S phi C).p) S.A W := W.ρ.comp gamma
  have hgen : RepresentationGeneratedBy tau.dual D.H :=
    representationDual_generated_of_subquotient
      D.dual
      (inducedIntertwiner S phi C i₀)
      (inducedIntertwiner_injective S phi C i₀)
      ((quotientIntertwiner S phi C N).comp
        (sectionQuotientIntertwiner S phi C N))
      ((quotientIntertwiner_surjective S phi C N).comp
        (sectionQuotientIntertwiner_surjective S phi C N))
  have hcap := representationSchurCapacity_le_of_dual_generated
    tau D.H hgen
  change representationSchurCapacity (W.ρ.comp gamma) ≤ D.H at hcap
  rw [representationSchurCapacity_comp gamma
    (QuotientGroup.mk'_surjective ((pi S phi).ker ⊔ N)) W.ρ] at hcap
  simpa only [W] using hcap

end NormalSection

/-- The lift coefficient after the invariant cut is no larger than the
standard generator-power fibre used by the ordinary affine joint capacity.
This is the quantitative reason the prime-marked refinement has no extra
menu-mass cost. -/
private theorem primeCutCoefficient_le_generatorPower
    (i₀ : I) (D : RefinedCapacityData S phi C i₀)
    (N : {N : Subgroup S.A // N.Normal}) :
    elementaryLayerPrimeCutCoefficient C.p
        (pi S phi) (E S phi C).quotientRepresentation
        (E S phi C).originalKernelChart N ≤
      (Nat.card (E S phi C).quotientRepresentation : ℝ) ^
        (S.generatorCount + 1) := by
  let M := (originalChart S phi C).sectionRepresentation
    (pi S phi) (E S phi C).quotientRepresentation N.1
  let cut : {W : Submodule (ZMod C.p) M // W ≤ M.ρ.invariants} :=
    ⟨M.ρ.invariants, le_rfl⟩
  let W := OriginalCentralCutExtension.quotientModule M cut
  letI : N.1.Normal := N.2
  let normalSpace := (originalChart S phi C).normalSpace
    (pi S phi) (E S phi C).quotientRepresentation N.1
  letI : Finite C.V := Module.finite_of_finite (ZMod C.p)
  letI : Finite (E S phi C).V := Finite.of_injective
    (PermutationalWreathProduct.Compression.ElementarySubmodule
      (p := C.p) S.rho phi C.equiv.symm).subtype
    (PermutationalWreathProduct.Compression.ElementarySubmodule
      (p := C.p) S.rho phi C.equiv.symm).subtype_injective
  letI : Finite (E S phi C).quotientRepresentation :=
    inferInstanceAs (Finite (E S phi C).V)
  letI : Finite M := Finite.of_surjective
    normalSpace.mkQ normalSpace.mkQ_surjective
  letI : Finite W := Finite.of_surjective cut.1.mkQ cut.1.mkQ_surjective
  obtain ⟨generators, hgenerators⟩ :=
    (jointCapacityInputRefined S phi C i₀ D).sectionGenerators N
  have hH1 : Nat.card (groupCohomology.H1 W) ≤
      Nat.card W ^ S.generatorCount :=
    firstCohomology_card_le_generator_power W S.generatorCount
      generators hgenerators
  have hWM : Nat.card W ≤ Nat.card M :=
    Nat.card_le_card_of_surjective cut.1.mkQ cut.1.mkQ_surjective
  have hMA : Nat.card M ≤
      Nat.card (E S phi C).quotientRepresentation :=
    Nat.card_le_card_of_surjective normalSpace.mkQ normalSpace.mkQ_surjective
  unfold elementaryLayerPrimeCutCoefficient
    OriginalPrimeCentralCutFusion.liftConstant
  calc
    (Nat.card W * Nat.card (groupCohomology.H1 W) : ℝ) ≤
        (Nat.card W : ℝ) * (Nat.card W : ℝ) ^ S.generatorCount := by
      gcongr
      exact_mod_cast hH1
    _ = (Nat.card W : ℝ) ^ (S.generatorCount + 1) := by
      rw [pow_succ']
    _ ≤ (Nat.card (E S phi C).quotientRepresentation : ℝ) ^
        (S.generatorCount + 1) := by
      apply pow_le_pow_left₀ (by positivity)
      exact_mod_cast hWM.trans hMA

/-- Actual refined affine capacity after the full invariant prime cut.  Both
the fixed columns and the quotient Schur exponent use the same retained
tuple `D.H`. -/
noncomputable def primeCutJointCapacityRefined
    (i₀ : I) (D : RefinedCapacityData S phi C i₀) :
    PrimeCentralLayerJointCapacityBound C.p
      (pi S phi) (QuotientGroup.mk'_surjective (K S phi))
      (E S phi C).quotientRepresentation
      (E S phi C).originalKernelChart := by
  letI : Finite C.V := Module.finite_of_finite (ZMod C.p)
  letI : Finite (E S phi C).V := Finite.of_injective
    (PermutationalWreathProduct.Compression.ElementarySubmodule
      (p := C.p) S.rho phi C.equiv.symm).subtype
    (PermutationalWreathProduct.Compression.ElementarySubmodule
      (p := C.p) S.rho phi C.equiv.symm).subtype_injective
  letI : Finite (E S phi C).quotientRepresentation :=
    inferInstanceAs (Finite (E S phi C).V)
  let input := jointCapacityInputRefined S phi C i₀ D
  let ordinary := input.toJointCapacity
    (hpi := QuotientGroup.mk'_surjective (K S phi))
  let B : ℝ :=
    (Nat.card (E S phi C).quotientRepresentation : ℝ) ^
      (S.generatorCount + 1)
  refine
    { fixedCapacity := D.H
      quotientCapacity := D.H
      quotientCapacity_nonneg := by positivity
      fixed_le := ?_
      quotient_capacity_le := ?_
      coefficient := ordinary.coefficient
      coefficient_nonneg := ordinary.coefficient_nonneg
      fixed_top_fibre := ?_ }
  · intro N
    letI : N.1.Normal := N.2
    exact section_invariants_finrank_le_refined S phi C N.1 i₀ D
  · intro N
    letI : N.1.Normal := N.2
    exact_mod_cast invariantQuotient_schurCapacity_le_refined
      S phi C N.1 i₀ D
  · intro top
    calc
      (∑ N : {N : {N : Subgroup S.A // N.Normal} //
          elementaryLayerTopAxis (pi S phi)
            (QuotientGroup.mk'_surjective (K S phi)) N = top},
          elementaryLayerPrimeCutCoefficient C.p
            (pi S phi) (E S phi C).quotientRepresentation
            (E S phi C).originalKernelChart N.1) ≤
        ∑ _N : {N : {N : Subgroup S.A // N.Normal} //
          elementaryLayerTopAxis (pi S phi)
            (QuotientGroup.mk'_surjective (K S phi)) N = top}, B := by
          apply Finset.sum_le_sum
          intro N _
          exact primeCutCoefficient_le_generatorPower S phi C i₀ D N.1
      _ = (Nat.card {N : {N : Subgroup S.A // N.Normal} //
          elementaryLayerTopAxis (pi S phi)
            (QuotientGroup.mk'_surjective (K S phi)) N = top} : ℝ) * B := by
          simp only [Finset.sum_const, Finset.card_univ, nsmul_eq_mul,
            Fintype.card_eq_nat_card]
      _ ≤ ((Nat.card (E S phi C).quotientRepresentation : ℝ) ^ input.H *
            (C.p : ℝ) ^ (input.H * (input.v / C.p))) * B := by
          apply mul_le_mul_of_nonneg_right _ (by positivity)
          exact_mod_cast AffineJointElementaryCapacityInput.fixedTop_card_le
            C.p (pi S phi) (QuotientGroup.mk'_surjective (K S phi))
              (E S phi C).quotientRepresentation
              (E S phi C).originalKernelChart input top
      _ = ordinary.coefficient := by
          rfl

end ActualWreathAffineCapacity
end SymmetricSubgroupAsymptotics

end
