import SymmetricSubgroupAsymptotics.BinaryCoverage

/-! Normal-registry edges can be checked by generator membership and exact
orders, without storing every element of every enlarged normal subgroup. -/
set_option autoImplicit false
noncomputable section

namespace SymmetricSubgroupAsymptotics

variable {G : Type*} [Group G] (N : Subgroup G) [N.Normal]

/-- The quotient-cyclic step is generated by the original normal subgroup
and one actual lift. The extension need not split. -/
theorem normal_step_generated (x : G) :
    (Subgroup.zpowers (QuotientGroup.mk' N x)).comap (QuotientGroup.mk' N) =
      N ⊔ Subgroup.zpowers x := by
  rw [← MonoidHom.map_zpowers, Subgroup.comap_map_eq, QuotientGroup.ker_mk', sup_comm]

/-- The cardinality multiplier is the order in the actual quotient, not
the order of the selected lift in the original group. -/
theorem normal_step_card [Finite G] (x : G) :
    Nat.card ((Subgroup.zpowers (QuotientGroup.mk' N x)).comap (QuotientGroup.mk' N)) =
      Nat.card N * orderOf (QuotientGroup.mk' N x) := by
  let L := (Subgroup.zpowers (QuotientGroup.mk' N x)).comap (QuotientGroup.mk' N)
  have hNL : N ≤ L := by rw [show L = _ from normal_step_generated N x]; exact le_sup_left
  have hi : N.relIndex L = orderOf (QuotientGroup.mk' N x) := by
    have h := Subgroup.relIndex_ker L (QuotientGroup.mk' N)
    rw [QuotientGroup.ker_mk'] at h
    rw [h]
    dsimp [L]
    rw [Subgroup.map_comap_eq_self_of_surjective (QuotientGroup.mk'_surjective N),
      Nat.card_zpowers]
  have hc := (N.subgroupOf L).card_mul_index
  rw [Nat.card_congr (Subgroup.subgroupOfEquivOfLe hNL).toEquiv] at hc
  change Nat.card N * N.relIndex L = Nat.card L at hc
  rw [hi] at hc
  exact hc.symm

/-- A local normal-registry target is identified by short generator
membership checks and its checked order. No full element correspondence is
needed, and the selected lift may have larger order than its quotient. -/
theorem normal_step_eq_of_generators_card [Finite G] {ι : Type*}
    (generators : ι → G) (hgen : Subgroup.closure (Set.range generators) = N)
    (x : G) (M : Subgroup G)
    (hmem : ∀ i, generators i ∈ M) (hx : x ∈ M)
    (hcard : Nat.card M = Nat.card N * orderOf (QuotientGroup.mk' N x)) :
    (Subgroup.zpowers (QuotientGroup.mk' N x)).comap (QuotientGroup.mk' N) = M := by
  apply Subgroup.eq_of_le_of_card_ge
  · rw [normal_step_generated]
    apply sup_le
    · rw [← hgen]
      exact (Subgroup.closure_le M).mpr (by rintro _ ⟨i,rfl⟩; exact hmem i)
    · exact Subgroup.zpowers_le.mpr hx
  · rw [normal_step_card, hcard]

end SymmetricSubgroupAsymptotics
