import SymmetricSubgroupAsymptotics.CentralizingHomCount
import SymmetricSubgroupAsymptotics.CentralizerCosetCode

/-! A fixed actual normal-kernel fibre of epimorphisms has the target-center
slope. The short source tuple is fixed, but its image is only required to
generate the target. No restriction to the normal commutator is prescribed.
The proof counts quotient-center maps on actual centralizer cosets and then
counts their central differences on the original source group.
-/
set_option autoImplicit false
noncomputable section

namespace SymmetricSubgroupAsymptotics

local instance structuredHomFinite {G Q : Type*} [Group G] [Group Q]
    [Finite G] [Finite Q] : Finite (G →* Q) :=
  Finite.of_injective (fun f : G →* Q => (f : G → Q)) DFunLike.coe_injective

section Generating
variable {G Q : Type*} [Group G] [Group Q] {ι : Type*}
    (x : ι → G) (f : G →* Q)

theorem tuple_image_generating_surjective
    (hf : Subgroup.closure (Set.range (f ∘ x)) = ⊤) : Function.Surjective f := by
  apply MonoidHom.range_eq_top.mp
  apply top_unique
  rw [← hf]
  apply (Subgroup.closure_le _).mpr
  rintro _ ⟨i,rfl⟩
  exact ⟨x i,rfl⟩

/-- The original normal commutator maps onto the whole target derived
subgroup when the displayed tuple maps to generators. -/
theorem generatorNormalCommutator_map_of_generating
    (hf : Subgroup.closure (Set.range (f ∘ x)) = ⊤) :
    (generatorNormalCommutator x).map f = commutator Q := by
  rw [generatorNormalCommutator_map x f (tuple_image_generating_surjective x f hf)]
  have hn : Subgroup.normalClosure (Set.range (f ∘ x)) = ⊤ := by
    apply top_unique
    rw [← hf]
    exact Subgroup.closure_le_normalClosure
  simp only [generatorNormalCommutator,hn,commutator_def]
end Generating

namespace BinaryStructuredEpiFibre

variable {G Q : Type*} [Group G] [Group Q] {ι : Type*}
    (x : ι → G) (H : Subgroup G) [H.Normal]

/-- This is the preimage of the literal tuple centralizer in G/H. It is
independent of the selected epimorphism and need not be normal. -/
def centralizerPreimage : Subgroup G :=
  (Subgroup.centralizer (Set.range ((QuotientGroup.mk' H) ∘ x))).comap
    (QuotientGroup.mk' H)

theorem centralizerPreimage_index_le [Finite G] [Finite ι] :
    (centralizerPreimage x H).index ≤
      (Nat.card ((generatorNormalCommutator x).map (QuotientGroup.mk' H)))^
        (Nat.card ι) := by
  unfold centralizerPreimage
  rw [Subgroup.index_comap_of_surjective _ (QuotientGroup.mk'_surjective H)]
  rw [generatorNormalCommutator_map x (QuotientGroup.mk' H)
    (QuotientGroup.mk'_surjective H)]
  exact centralizer_index_le_normalCommutator_card ((QuotientGroup.mk' H) ∘ x)

/-- Every map killing H and generated by the displayed tuple sends the
same actual centralizer preimage into the target center. -/
theorem centralizerPreimage_maps_to_center (f : G →* Q)
    (hkill : H ≤ f.ker)
    (hgen : Subgroup.closure (Set.range (f ∘ x)) = ⊤) :
    ∀ c ∈ centralizerPreimage x H, f c ∈ Subgroup.center Q := by
  intro c hc
  have he : f c ∈ Subgroup.centralizer (Set.range (f ∘ x)) := by
    apply Subgroup.mem_centralizer_iff.mpr
    rintro _ ⟨i,rfl⟩
    have hi := (Subgroup.mem_centralizer_iff.mp hc)
      ((QuotientGroup.mk' H) (x i)) (Set.mem_range_self i)
    have hi' := congrArg (QuotientGroup.lift H f hkill) hi
    simpa only [map_mul,QuotientGroup.lift_mk] using hi'
  rw [← Subgroup.centralizer_closure,hgen,Subgroup.coe_top,
    Subgroup.centralizer_univ] at he
  exact he

theorem selected_card_le [Finite G] [Finite Q] [Finite ι]
    (hQ : IsPGroup 2 Q) :
    Nat.card {f : G →* Q // H ≤ f.ker ∧
      Subgroup.closure (Set.range (f ∘ x)) = ⊤} ≤
      (Nat.card Q)^((Nat.card ((generatorNormalCommutator x).map
        (QuotientGroup.mk' H)))^(Nat.card ι)) *
      (Nat.card (Subgroup.center Q))^(binaryCharacterRank G) := by
  have hb := CentralizingHomCount.selected_binary_card_le (centralizerPreimage x H)
    (fun f : G →* Q => H ≤ f.ker ∧ Subgroup.closure (Set.range (f ∘ x)) = ⊤)
    (fun f hf => centralizerPreimage_maps_to_center x H f hf.1 hf.2) hQ
  exact hb.trans (Nat.mul_le_mul_right _
    (Nat.pow_le_pow_right (Nat.card_pos : 0 < Nat.card Q)
      (centralizerPreimage_index_le x H)))

/-- The quotient-normal order is exactly |Q'| on every nonempty kernel
fibre. This is an index identity, not a source-order or kernel-order premise. -/
theorem normalCommutator_quotient_card (f : G →* Q)
    (hgen : Subgroup.closure (Set.range (f ∘ x)) = ⊤)
    (hH : generatorNormalCommutator x ⊓ f.ker = H) :
    Nat.card ((generatorNormalCommutator x).map (QuotientGroup.mk' H)) =
      Nat.card (commutator Q) := by
  calc
    _ = H.relIndex (generatorNormalCommutator x) := by
      simpa only [QuotientGroup.ker_mk'] using
        ((generatorNormalCommutator x).relIndex_ker (QuotientGroup.mk' H)).symm
    _ = f.ker.relIndex (generatorNormalCommutator x) := by
      rw [← hH,Subgroup.inf_relIndex_left]
    _ = Nat.card ((generatorNormalCommutator x).map f) :=
      (generatorNormalCommutator x).relIndex_ker f
    _ = _ := by rw [generatorNormalCommutator_map_of_generating x f hgen]

/-- Count a literal H-fibre, including the empty case, by the exact target
derived order and center slope. There is no selected representative premise. -/
theorem kernel_fibre_card_le [Finite G] [Finite Q] [Finite ι]
    (hQ : IsPGroup 2 Q) :
    Nat.card {f : G →* Q //
      Subgroup.closure (Set.range (f ∘ x)) = ⊤ ∧
      generatorNormalCommutator x ⊓ f.ker = H} ≤
      (Nat.card Q)^((Nat.card (commutator Q))^(Nat.card ι)) *
      (Nat.card (Subgroup.center Q))^(binaryCharacterRank G) := by
  let F := {f : G →* Q // Subgroup.closure (Set.range (f ∘ x)) = ⊤ ∧
    generatorNormalCommutator x ⊓ f.ker = H}
  by_cases hn : Nonempty F
  · obtain ⟨f₀⟩ := hn
    let j : F → {f : G →* Q // H ≤ f.ker ∧
        Subgroup.closure (Set.range (f ∘ x)) = ⊤} := fun f =>
      ⟨f.1,f.2.2.symm.le.trans inf_le_right,f.2.1⟩
    have hj : Function.Injective j := by
      intro f g he
      apply Subtype.ext
      exact congrArg (fun t : {f : G →* Q // H ≤ f.ker ∧
        Subgroup.closure (Set.range (f ∘ x)) = ⊤} => t.1) he
    have hb := (Nat.card_le_card_of_injective j hj).trans (selected_card_le x H hQ)
    rwa [normalCommutator_quotient_card x H f₀.1 f₀.2.1 f₀.2.2] at hb
  · letI := not_nonempty_iff.mp hn
    change Nat.card F ≤ _
    simp

end BinaryStructuredEpiFibre
end SymmetricSubgroupAsymptotics
