import SymmetricSubgroupAsymptotics.IndexTwoSchreier
import SymmetricSubgroupAsymptotics.BinarySylowCoverage
import SymmetricSubgroupAsymptotics.BinaryGeneratorWords
import Mathlib.Algebra.BigOperators.Fin
import Mathlib.Tactic.FinCases

/-!
# Word-sized original action registry certificates

An actual index-two subgroup is generated by two Schreier words per
original generator. Literal two-way generator words then certify accepted
conjugacy edges; relations and preserved point colourings reject the other
assignments. No source-element table or declared group order is needed.
-/

set_option autoImplicit false
noncomputable section
open scoped Pointwise
namespace SymmetricSubgroupAsymptotics

variable {G ι κ : Type*} [Group G]

/-- Exhaustive finite enumeration of original-generator membership bits. -/
def schreierAssignment {d : ℕ} (c : Fin (2^d)) (j : Fin d) : Bool :=
  finTwoEquiv (finFunctionFinEquiv.symm c j)

theorem schreierAssignment_surjective (d : ℕ) :
    Function.Surjective (@schreierAssignment d) := by
  intro bits
  refine ⟨finFunctionFinEquiv (fun j => finTwoEquiv.symm (bits j)), ?_⟩
  funext j
  simp only [schreierAssignment, Equiv.symm_apply_apply, Equiv.apply_symm_apply]

def binaryWordBit (bits : ι → Bool) : List ι → Bool
  | [] => true
  | j :: w => bits j == binaryWordBit bits w

private theorem binary_bool_eq_iff (a b : Bool) :
    a=b ↔ (a=true ↔ b=true) := by
  cases a <;> cases b <;> decide

theorem binaryWordBit_membership (generators : ι → G)
    (K : Subgroup G)
    (hi : K.relIndex (Subgroup.closure (Set.range generators))=2)
    (bits : ι → Bool) (hb : ∀ j,bits j=true ↔ generators j∈K)
    (w : List ι) : binaryWordBit bits w=true ↔ (w.map generators).prod∈K := by
  let U := Subgroup.closure (Set.range generators)
  have hword (v : List ι) : (v.map generators).prod∈U := by
    apply Subgroup.list_prod_mem
    intro x hx
    obtain ⟨j,_,rfl⟩ := List.mem_map.mp hx
    exact Subgroup.subset_closure ⟨j,rfl⟩
  induction w with
  | nil => simp [binaryWordBit]
  | cons j w ih =>
    have hm := (K.subgroupOf U).mul_mem_iff_of_index_two hi
      (a := ⟨generators j,Subgroup.subset_closure ⟨j,rfl⟩⟩)
      (b := ⟨(w.map generators).prod,hword w⟩)
    change generators j*(w.map generators).prod∈K ↔
      (generators j∈K ↔ (w.map generators).prod∈K) at hm
    change (bits j == binaryWordBit bits w)=true ↔
      generators j*(w.map generators).prod∈K
    rw [beq_iff_eq,binary_bool_eq_iff (bits j) (binaryWordBit bits w)]
    exact (iff_congr (hb j) ih).trans hm.symm

/-- Every actual index-two membership assignment respects every checked
literal relation between positive original-generator words. -/
theorem binaryWordBit_relation (generators : ι → G) (K : Subgroup G)
    (hi : K.relIndex (Subgroup.closure (Set.range generators))=2)
    (bits : ι → Bool) (hb : ∀ j,bits j=true ↔ generators j∈K)
    (u v : List ι) (he : (u.map generators).prod=(v.map generators).prod) :
    binaryWordBit bits u=binaryWordBit bits v := by
  rw [binary_bool_eq_iff,binaryWordBit_membership generators K hi bits hb,
    binaryWordBit_membership generators K hi bits hb,he]

/-- Short generator words certify equality after the same literal ambient
conjugator, without a cardinality premise. -/
theorem generatorWords_conjugacy (source : ι → G) (target : κ → G) (g : G)
    (forward : BinaryNormalGeneratorWords (fun j => MulAut.conj g (source j)) target)
    (backward : BinaryNormalGeneratorWords target (fun j => MulAut.conj g (source j))) :
    MulAut.conj g • Subgroup.closure (Set.range source)=
      Subgroup.closure (Set.range target) := by
  rw [Subgroup.pointwise_smul_def,MonoidHom.map_closure]
  change Subgroup.closure ((MulAut.conj g).toMonoidHom '' Set.range source)=
    Subgroup.closure (Set.range target)
  have hr : (MulAut.conj g).toMonoidHom '' Set.range source=
      Set.range (fun j => MulAut.conj g (source j)) := by
    ext x
    simp only [Set.mem_image,Set.mem_range,exists_exists_eq_and]
    rfl
  rw [hr]
  exact le_antisymm forward.closure_le backward.closure_le

variable {w : ℕ}

/-- A nonconstant point colouring preserved by all original generators
is preserved by their full generated subgroup. -/
theorem generated_not_transitive_of_coloring
    (generators : ι → Equiv.Perm (Fin w)) (color : Fin w → Bool)
    (x y : Fin w) (hxy : color x≠color y)
    (hcolor : ∀ j z,color (generators j z)=color z) :
    ¬PermutationSubgroupTransitive (Subgroup.closure (Set.range generators)) := by
  let V : Subgroup (Equiv.Perm (Fin w)) := {
    carrier := {g | ∀ z,color (g z)=color z}
    one_mem' := by intro z; rfl
    mul_mem' := by
      intro g h hg hh z
      exact (hg (h z)).trans (hh z)
    inv_mem' := by
      intro g hg z
      have he := hg (g⁻¹ z)
      simpa only [Equiv.Perm.inv_def,Equiv.apply_symm_apply] using he.symm }
  have hle : Subgroup.closure (Set.range generators)≤V := by
    apply (Subgroup.closure_le _).mpr
    rintro _ ⟨j,rfl⟩
    exact hcolor j
  intro ht
  obtain ⟨g,hg,hgxy⟩ := ht x y
  have he := hle hg x
  rw [hgxy] at he
  exact hxy he.symm

/-- Complete actual child coverage from relations, point colourings and
literal two-way Schreier generator words. The finite checker has no source
order, target order, or source-element-table hypothesis. -/
theorem binary_schreier_registry_children {I : Type*}
    (generators : ι → Equiv.Perm (Fin w))
    (actions : I → Subgroup (Equiv.Perm (Fin w)))
    (checked : ∀ bits : ι → Bool,
      (∃ j,bits j=false) →
      (∀ u v : List ι,(u.map generators).prod=(v.map generators).prod →
        binaryWordBit bits u=binaryWordBit bits v) →
      ∃ j,bits j=false ∧
        (¬PermutationSubgroupTransitive (Subgroup.closure
          (Set.range (binarySchreierWords generators bits (generators j)))) ∨
        ActionRegistryCovered actions (Subgroup.closure
          (Set.range (binarySchreierWords generators bits (generators j))))))
    (K : Subgroup (Equiv.Perm (Fin w)))
    (hK : K≤Subgroup.closure (Set.range generators))
    (hi : K.relIndex (Subgroup.closure (Set.range generators))=2)
    (ht : PermutationSubgroupTransitive K) : ActionRegistryCovered actions K := by
  classical
  let bits : ι → Bool := fun j => decide (generators j∈K)
  have hb : ∀ j,bits j=true ↔ generators j∈K := fun _ => decide_eq_true_iff
  have hn : ∃ j,bits j=false := by
    by_contra h
    have hle : Subgroup.closure (Set.range generators)≤K := by
      apply (Subgroup.closure_le _).mpr
      rintro _ ⟨j,rfl⟩
      apply (hb j).mp
      cases hj : bits j
      · exact (h ⟨j,hj⟩).elim
      · rfl
    have he := Subgroup.relIndex_eq_one.mpr hle
    rw [hi] at he
    omega
  obtain ⟨j,hj,hout⟩ := checked bits hn (binaryWordBit_relation generators K hi bits hb)
  have hx : generators j∉K := by
    intro h
    have hh := (hb j).mpr h
    rw [hj] at hh
    contradiction
  have he := relative_indexTwo_schreier_generated generators K hK hi bits hb
    (generators j) (Subgroup.subset_closure ⟨j,rfl⟩) hx
  rw [← he] at hout
  exact hout.resolve_left (fun h => h ht)

end SymmetricSubgroupAsymptotics
