import SymmetricSubgroupAsymptotics.BinaryCoordinateSpaces
import SymmetricSubgroupAsymptotics.OutsideOrbitDegreeThree

/-!
# Cyclic binary modules on three coordinates

The regular three-coordinate permutation module over `F₂` is
multiplicity-free for a transitive group of order three.  Consequently every
invariant submodule is generated by the orbit of one vector.  This is the
small, reusable local algebra statement needed by the structural degree-six
binary-block owner; it classifies submodules of one fixed natural module,
not permutation groups or transitive actions.
-/

set_option autoImplicit false
noncomputable section
open scoped BigOperators

namespace SymmetricSubgroupAsymptotics

private abbrev NaturalC3 : Subgroup (Equiv.Perm (Fin 3)) :=
  alternatingGroup (Fin 3)

private abbrev naturalC3BinaryRepresentation :
    Representation (ZMod 2) NaturalC3 (Fin 3 → ZMod 2) :=
  (binaryPermutationRepresentation 3).comp NaturalC3.subtype

private def binaryUnit : Fin 3 → ZMod 2 :=
  fun i => if i = 0 then 1 else 0

private def binaryPair : Fin 3 → ZMod 2 :=
  fun i => if i = 2 then 0 else 1

private def binaryDiagonal : Fin 3 → ZMod 2 := fun _ => 1

private def naturalC3OrbitSum (v : Fin 3 → ZMod 2) (s : Finset NaturalC3) :
    Fin 3 → ZMod 2 :=
  ∑ g ∈ s, naturalC3BinaryRepresentation g v

private theorem orderThree_subgroup_eq_naturalC3
    (T : Subgroup (Equiv.Perm (Fin 3)))
    (hT : Nat.card T = 3) : T = NaturalC3 := by
  have hle : T ≤ NaturalC3 := by
    intro g hg
    rw [Equiv.Perm.mem_alternatingGroup]
    have hpowT := pow_card_eq_one' (x := (⟨g, hg⟩ : T))
    rw [hT] at hpowT
    have hpow : g ^ 3 = 1 := congrArg Subtype.val hpowT
    have hsignpow : Equiv.Perm.sign g ^ 3 = 1 := by
      rw [← map_pow, hpow, map_one]
    rcases Int.units_eq_one_or (Equiv.Perm.sign g) with hsign | hsign
    · exact hsign
    · rw [hsign] at hsignpow
      norm_num at hsignpow
  apply Subgroup.eq_of_le_of_card_ge hle
  rw [nat_card_alternatingGroup, hT]
  norm_num [Nat.card_eq_fintype_card]

private theorem binaryUnit_orbit_spans :
    ∀ x : Fin 3 → ZMod 2, ∃ s : Finset NaturalC3,
      naturalC3OrbitSum binaryUnit s = x := by
  decide +kernel

private theorem binaryPair_orbit_or_unit :
    ∀ x : Fin 3 → ZMod 2,
      (∃ s : Finset NaturalC3, naturalC3OrbitSum binaryPair s = x) ∨
      ∃ s : Finset NaturalC3, x + naturalC3OrbitSum binaryPair s = binaryUnit := by
  decide +kernel

private theorem binaryDiagonal_orbit_or_pair_or_unit :
    ∀ x : Fin 3 → ZMod 2,
      (∃ s : Finset NaturalC3, naturalC3OrbitSum binaryDiagonal s = x) ∨
      (∃ (g : NaturalC3) (s : Finset NaturalC3),
        x + naturalC3OrbitSum binaryDiagonal s =
          naturalC3BinaryRepresentation g binaryPair) ∨
      ∃ (g : NaturalC3) (s : Finset NaturalC3),
        x + naturalC3OrbitSum binaryDiagonal s =
          naturalC3BinaryRepresentation g binaryUnit := by
  decide +kernel

private theorem binaryThree_vector_cases :
    ∀ x : Fin 3 → ZMod 2,
      x = 0 ∨ x = binaryDiagonal ∨
      (∃ g : NaturalC3, x = naturalC3BinaryRepresentation g binaryPair) ∨
      ∃ g : NaturalC3, x = naturalC3BinaryRepresentation g binaryUnit := by
  decide +kernel

private theorem orbitSum_mem
    (M : Subrepresentation naturalC3BinaryRepresentation)
    (v : Fin 3 → ZMod 2) (hv : v ∈ M.toSubmodule)
    (s : Finset NaturalC3) : naturalC3OrbitSum v s ∈ M.toSubmodule := by
  rw [naturalC3OrbitSum]
  apply M.toSubmodule.sum_mem
  intro g hg
  exact M.apply_mem_toSubmodule g hv

private theorem mem_of_representation_mem
    (M : Subrepresentation naturalC3BinaryRepresentation)
    (g : NaturalC3) (v : Fin 3 → ZMod 2)
    (hv : naturalC3BinaryRepresentation g v ∈ M.toSubmodule) :
    v ∈ M.toSubmodule := by
  have h := M.apply_mem_toSubmodule g⁻¹ hv
  simpa using h

private theorem coe_orbitListSum
    (M : Subrepresentation naturalC3BinaryRepresentation)
    (v : M.toSubmodule) (l : List NaturalC3) :
    (((l.map fun g => M.toRepresentation g v).sum : M.toSubmodule) :
        Fin 3 → ZMod 2) =
      (l.map fun g => naturalC3BinaryRepresentation g v.1).sum := by
  induction l with
  | nil => rfl
  | cons g l ih =>
      simp only [List.map_cons, List.sum_cons]
      exact congrArg₂ (· + ·) rfl ih

private theorem orbitSum_toList
    (v : Fin 3 → ZMod 2) (s : Finset NaturalC3) :
    (s.toList.map fun g => naturalC3BinaryRepresentation g v).sum =
      naturalC3OrbitSum v s := by
  let f := fun g : NaturalC3 => naturalC3BinaryRepresentation g v
  calc
    (s.toList.map f).sum = ((s.toList.map f : List (Fin 3 → ZMod 2)) :
        Multiset (Fin 3 → ZMod 2)).sum :=
      (Multiset.sum_coe (s.toList.map f)).symm
    _ = (((s.toList : List NaturalC3) : Multiset NaturalC3).map f).sum := by
      rw [Multiset.map_coe]
    _ = (s.1.map f).sum := by rw [Finset.coe_toList]
    _ = naturalC3OrbitSum v s := rfl

/-- Every invariant submodule of the natural binary permutation module on
three points for a top of order three is generated additively by one orbit. -/
theorem binaryThree_subrepresentation_cyclic
    (T : Subgroup (Equiv.Perm (Fin 3)))
    (hT : Nat.card T = 3)
    (M : Subrepresentation
      ((binaryPermutationRepresentation 3).comp T.subtype)) :
    ∃ v : M.toSubmodule, ∀ x : M.toSubmodule, ∃ l : List T,
      (l.map fun g => M.toRepresentation g v).sum = x := by
  have hT' : T = NaturalC3 := orderThree_subgroup_eq_naturalC3 T hT
  subst T
  by_cases he : binaryUnit ∈ M.toSubmodule
  · refine ⟨⟨binaryUnit, he⟩, ?_⟩
    intro x
    obtain ⟨s, hs⟩ := binaryUnit_orbit_spans x.1
    refine ⟨s.toList, ?_⟩
    apply Subtype.ext
    rw [coe_orbitListSum]
    rw [orbitSum_toList]
    exact hs
  · by_cases ha : binaryPair ∈ M.toSubmodule
    · refine ⟨⟨binaryPair, ha⟩, ?_⟩
      intro x
      rcases binaryPair_orbit_or_unit x.1 with ⟨s, hs⟩ | ⟨s, hs⟩
      · refine ⟨s.toList, ?_⟩
        apply Subtype.ext
        rw [coe_orbitListSum]
        rw [orbitSum_toList]
        exact hs
      · exfalso
        apply he
        rw [← hs]
        exact M.toSubmodule.add_mem x.2 (orbitSum_mem M binaryPair ha s)
    · by_cases hd : binaryDiagonal ∈ M.toSubmodule
      · refine ⟨⟨binaryDiagonal, hd⟩, ?_⟩
        intro x
        rcases binaryDiagonal_orbit_or_pair_or_unit x.1 with
          ⟨s, hs⟩ | ⟨g, s, hs⟩ | ⟨g, s, hs⟩
        · refine ⟨s.toList, ?_⟩
          apply Subtype.ext
          rw [coe_orbitListSum]
          rw [orbitSum_toList]
          exact hs
        · exfalso
          apply ha
          apply mem_of_representation_mem M g binaryPair
          rw [← hs]
          exact M.toSubmodule.add_mem x.2
            (orbitSum_mem M binaryDiagonal hd s)
        · exfalso
          apply he
          apply mem_of_representation_mem M g binaryUnit
          rw [← hs]
          exact M.toSubmodule.add_mem x.2
            (orbitSum_mem M binaryDiagonal hd s)
      · refine ⟨0, ?_⟩
        intro x
        have hx : x.1 = 0 := by
          rcases binaryThree_vector_cases x.1 with
            hx | hx | ⟨g, hx⟩ | ⟨g, hx⟩
          · exact hx
          · exact False.elim (hd (hx ▸ x.2))
          · apply False.elim (ha (mem_of_representation_mem M g binaryPair ?_))
            rw [← hx]
            exact x.2
          · apply False.elim (he (mem_of_representation_mem M g binaryUnit ?_))
            rw [← hx]
            exact x.2
        refine ⟨[], ?_⟩
        apply Subtype.ext
        simpa only [List.map_nil, List.sum_nil] using hx.symm

end SymmetricSubgroupAsymptotics

end
