import SymmetricSubgroupAsymptotics.NormalSubgroupSaturationCommutators
import SymmetricSubgroupAsymptotics.BinaryCarrierDerivedRadical16T1332

/-! Selected saturation by actual iterated commutators in the original
16T1332 action. Every original derived row outside its relative radical
recovers every displayed radical generator. No normal-subgroup list or
intrinsic-only conjugation action is substituted. Generated by the bounded
selected export_lean_carrier_saturation.py producer. -/
set_option autoImplicit false
set_option Elab.async false
noncomputable section
open scoped commutatorElement

namespace SymmetricSubgroupAsymptotics.BinaryCarrierRadicalSaturation16T1332

abbrev Original := BinaryCarrierDerivedOrder16T1332.Original
private abbrev D := commutator Original
private abbrev R := primeRelativeRadical 2 D
private abbrev g := BinaryActionData16.node1332Generators
private abbrev ambient := closureGenerators g
private abbrev basisWords := BinaryCarrierDerivedOrder16T1332.basisWords
private abbrev basis := derivedWordGenerators g basisWords
private abbrev rows := BinaryCarrierDerivedOrder16T1332.certificate.cayley.elements
private abbrev ambientRows := BinaryCarrierDerivedOrder16T1332.ambientRows

private def ambientBasis (j : Fin 6) : Equiv.Perm (Fin 16) := (basisWords j).eval g
private def seed : Fin 2 → Fin 6 ⊕ (Fin 6 × Fin 5) :=
  ![.inl 4,.inr (1,3)]
private def candidate (j : Fin 2) : Original :=
  primeRelativeFiniteGenerators 2 ambient basis (seed j)
private def ambientCandidate (j : Fin 2) : Equiv.Perm (Fin 16) :=
  primeRelativeFiniteGenerators 2 g ambientBasis (seed j)
private def radicalWords : Fin 4 → List (Fin 2) :=
  ![[],[0],[1],[0,1]]
private def radicalRows (i : Fin 4) : Original :=
  ((radicalWords i).map candidate).prod
private def ambientRadicalRows (i : Fin 4) : Equiv.Perm (Fin 16) :=
  ((radicalWords i).map ambientCandidate).prod
private def inside : Fin 64 → Bool := ![true,true,false,true,false,false,false,false,
    true,false,false,false,false,false,false,false,
    false,false,false,false,false,false,false,false,
    false,false,false,false,false,false,false,false,
    false,false,false,false,false,false,false,false,
    false,false,false,false,false,false,false,false,
    false,false,false,false,false,false,false,false,
    false,false,false,false,false,false,false,false]
private def insideCode : Fin 64 → Fin 4 := ![0,3,0,2,0,0,0,0,
    1,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0,
    0,0,0,0,0,0,0,0]
private def saturationWords (i : Fin 64) (j : Fin 2) : List (List (Fin 5)) :=
  ![![[],[]],![[],[]],
    ![[[2]],[[3]]],![[],[]],
    ![[[2,4]],[[2]]],![[[2]],[[1]]],
    ![[[4]],[[1]]],![[[2]],[[3]]],
    ![[],[]],![[[2,4]],[[2]]],
    ![[[2]],[[1]]],![[[0,4]],[[1]]],
    ![[[2]],[[3]]],![[[4]],[[2],[4]]],
    ![[[3]],[[1]]],![[[0,4]],[[1]]],
    ![[[2,4]],[[2]]],![[[2]],[[1]]],
    ![[[0,4]],[[1]]],![[[3]],[[1]]],
    ![[[2]],[[1]]],![[[3]],[[1]]],
    ![[[0,4]],[[2]]],![[[0,4]],[[1]]],
    ![[[2]],[[1]]],![[[0,4]],[[2]]],
    ![[[2]],[[3]]],![[[2,4]],[[2],[2,4]]],
    ![[[3]],[[1]]],![[[0,4]],[[1]]],
    ![[[2,4]],[[2]]],![[[2]],[[1]]],
    ![[[4]],[[1]]],![[[3]],[[1]]],
    ![[[2]],[[1]]],![[[3]],[[1]]],
    ![[[4]],[[2]]],![[[0,4]],[[1]]],
    ![[[2]],[[1]]],![[[4]],[[2]]],
    ![[[2,4]],[[2],[2,4]]],![[[3]],[[1]]],
    ![[[1,4]],[[1]]],![[[0,4]],[[1]]],
    ![[[1,4]],[[1]]],![[[3]],[[0],[3]]],
    ![[[0,4]],[[1]]],![[[3]],[[0],[3]]],
    ![[[3]],[[4]]],![[[3]],[[4]]],
    ![[[4]],[[2],[4]]],![[[3]],[[1]]],
    ![[[4]],[[1]]],![[[4]],[[1]]],
    ![[[4]],[[1]]],![[[3]],[[4]]],
    ![[[4]],[[1]]],![[[3]],[[4]]],
    ![[[3]],[[0],[3]]],![[[3]],[[0],[3]]],
    ![[[2]],[[0],[2]]],![[[2]],[[0],[2]]],
    ![[[2]],[[0],[2]]],![[[2]],[[0],[2]]]] i j

private theorem candidate_coe (j : Fin 2) :
    (candidate j : Equiv.Perm (Fin 16)) = ambientCandidate j := by
  cases hs : seed j with
  | inl k =>
    change ((primeRelativeFiniteGenerators 2 ambient basis (seed j) : Original) : Equiv.Perm (Fin 16)) = _
    simp only [hs, primeRelativeFiniteGenerators, Sum.elim_inl, ambientCandidate]
    change (basis k : Equiv.Perm (Fin 16)) ^ 2 = ambientBasis k ^ 2
    rw [show (basis k : Equiv.Perm (Fin 16)) = ambientBasis k from
      closureGenerators_eval_coe g (basisWords k)]
  | inr ki =>
    change ((primeRelativeFiniteGenerators 2 ambient basis (seed j) : Original) : Equiv.Perm (Fin 16)) = _
    simp only [hs, primeRelativeFiniteGenerators, Sum.elim_inr, ambientCandidate]
    change ⁅(basis ki.1 : Equiv.Perm (Fin 16)), g ki.2⁆ = ⁅ambientBasis ki.1, g ki.2⁆
    rw [show (basis ki.1 : Equiv.Perm (Fin 16)) = ambientBasis ki.1 from
      closureGenerators_eval_coe g (basisWords ki.1)]

private theorem radicalRows_coe (i : Fin 4) :
    (radicalRows i : Equiv.Perm (Fin 16)) = ambientRadicalRows i := by
  change Original.subtype (((radicalWords i).map candidate).prod) = _
  have hf : Original.subtype ∘ candidate = ambientCandidate := funext candidate_coe
  rw [map_list_prod, List.map_map, hf]
  rfl

private theorem rows_coe (i : Fin 64) :
    (rows i : Equiv.Perm (Fin 16)) = ambientRows i :=
  BinaryCarrierDerivedOrder16T1332.certificate_elements_coe i

private theorem radicalRows_injective_pointwise : ∀ i j : Fin 4,
    (∀ x : Fin 16, ambientRadicalRows i x = ambientRadicalRows j x) → i = j := by
  decide +kernel

private theorem inside_pointwise_000 : ∀ i : Fin 8,
    inside (Fin.castAdd 32 (Fin.castAdd 16 (Fin.castAdd 8 i))) = true → ∀ x : Fin 16,
      ambientRows (Fin.castAdd 32 (Fin.castAdd 16 (Fin.castAdd 8 i))) x = ambientRadicalRows (insideCode (Fin.castAdd 32 (Fin.castAdd 16 (Fin.castAdd 8 i)))) x := by
  decide +kernel

private theorem inside_pointwise_001 : ∀ i : Fin 8,
    inside (Fin.castAdd 32 (Fin.castAdd 16 (Fin.natAdd 8 i))) = true → ∀ x : Fin 16,
      ambientRows (Fin.castAdd 32 (Fin.castAdd 16 (Fin.natAdd 8 i))) x = ambientRadicalRows (insideCode (Fin.castAdd 32 (Fin.castAdd 16 (Fin.natAdd 8 i)))) x := by
  decide +kernel

private theorem inside_pointwise_002 : ∀ i : Fin 8,
    inside (Fin.castAdd 32 (Fin.natAdd 16 (Fin.castAdd 8 i))) = true → ∀ x : Fin 16,
      ambientRows (Fin.castAdd 32 (Fin.natAdd 16 (Fin.castAdd 8 i))) x = ambientRadicalRows (insideCode (Fin.castAdd 32 (Fin.natAdd 16 (Fin.castAdd 8 i)))) x := by
  decide +kernel

private theorem inside_pointwise_003 : ∀ i : Fin 8,
    inside (Fin.castAdd 32 (Fin.natAdd 16 (Fin.natAdd 8 i))) = true → ∀ x : Fin 16,
      ambientRows (Fin.castAdd 32 (Fin.natAdd 16 (Fin.natAdd 8 i))) x = ambientRadicalRows (insideCode (Fin.castAdd 32 (Fin.natAdd 16 (Fin.natAdd 8 i)))) x := by
  decide +kernel

private theorem inside_pointwise_004 : ∀ i : Fin 8,
    inside (Fin.natAdd 32 (Fin.castAdd 16 (Fin.castAdd 8 i))) = true → ∀ x : Fin 16,
      ambientRows (Fin.natAdd 32 (Fin.castAdd 16 (Fin.castAdd 8 i))) x = ambientRadicalRows (insideCode (Fin.natAdd 32 (Fin.castAdd 16 (Fin.castAdd 8 i)))) x := by
  decide +kernel

private theorem inside_pointwise_005 : ∀ i : Fin 8,
    inside (Fin.natAdd 32 (Fin.castAdd 16 (Fin.natAdd 8 i))) = true → ∀ x : Fin 16,
      ambientRows (Fin.natAdd 32 (Fin.castAdd 16 (Fin.natAdd 8 i))) x = ambientRadicalRows (insideCode (Fin.natAdd 32 (Fin.castAdd 16 (Fin.natAdd 8 i)))) x := by
  decide +kernel

private theorem inside_pointwise_006 : ∀ i : Fin 8,
    inside (Fin.natAdd 32 (Fin.natAdd 16 (Fin.castAdd 8 i))) = true → ∀ x : Fin 16,
      ambientRows (Fin.natAdd 32 (Fin.natAdd 16 (Fin.castAdd 8 i))) x = ambientRadicalRows (insideCode (Fin.natAdd 32 (Fin.natAdd 16 (Fin.castAdd 8 i)))) x := by
  decide +kernel

private theorem inside_pointwise_007 : ∀ i : Fin 8,
    inside (Fin.natAdd 32 (Fin.natAdd 16 (Fin.natAdd 8 i))) = true → ∀ x : Fin 16,
      ambientRows (Fin.natAdd 32 (Fin.natAdd 16 (Fin.natAdd 8 i))) x = ambientRadicalRows (insideCode (Fin.natAdd 32 (Fin.natAdd 16 (Fin.natAdd 8 i)))) x := by
  decide +kernel

private theorem inside_pointwise : ∀ i : Fin 64,
    inside i = true → ∀ x : Fin 16,
      ambientRows i x = ambientRadicalRows (insideCode i) x :=
  (Fin.addCases (m := 32) (n := 32) (Fin.addCases (m := 16) (n := 16) (Fin.addCases (m := 8) (n := 8) inside_pointwise_000 inside_pointwise_001) (Fin.addCases (m := 8) (n := 8) inside_pointwise_002 inside_pointwise_003)) (Fin.addCases (m := 16) (n := 16) (Fin.addCases (m := 8) (n := 8) inside_pointwise_004 inside_pointwise_005) (Fin.addCases (m := 8) (n := 8) inside_pointwise_006 inside_pointwise_007)))


private theorem words_pointwise_000 : ∀ i : Fin 8,
    inside (Fin.castAdd 32 (Fin.castAdd 16 (Fin.castAdd 8 i))) = false → ∀ (j : Fin 2) (x : Fin 16),
      originalCommutatorProduct g (ambientRows (Fin.castAdd 32 (Fin.castAdd 16 (Fin.castAdd 8 i)))) (saturationWords (Fin.castAdd 32 (Fin.castAdd 16 (Fin.castAdd 8 i))) j) x =
        ambientCandidate j x := by
  decide +kernel

private theorem words_pointwise_001 : ∀ i : Fin 8,
    inside (Fin.castAdd 32 (Fin.castAdd 16 (Fin.natAdd 8 i))) = false → ∀ (j : Fin 2) (x : Fin 16),
      originalCommutatorProduct g (ambientRows (Fin.castAdd 32 (Fin.castAdd 16 (Fin.natAdd 8 i)))) (saturationWords (Fin.castAdd 32 (Fin.castAdd 16 (Fin.natAdd 8 i))) j) x =
        ambientCandidate j x := by
  decide +kernel

private theorem words_pointwise_002 : ∀ i : Fin 8,
    inside (Fin.castAdd 32 (Fin.natAdd 16 (Fin.castAdd 8 i))) = false → ∀ (j : Fin 2) (x : Fin 16),
      originalCommutatorProduct g (ambientRows (Fin.castAdd 32 (Fin.natAdd 16 (Fin.castAdd 8 i)))) (saturationWords (Fin.castAdd 32 (Fin.natAdd 16 (Fin.castAdd 8 i))) j) x =
        ambientCandidate j x := by
  decide +kernel

private theorem words_pointwise_003 : ∀ i : Fin 8,
    inside (Fin.castAdd 32 (Fin.natAdd 16 (Fin.natAdd 8 i))) = false → ∀ (j : Fin 2) (x : Fin 16),
      originalCommutatorProduct g (ambientRows (Fin.castAdd 32 (Fin.natAdd 16 (Fin.natAdd 8 i)))) (saturationWords (Fin.castAdd 32 (Fin.natAdd 16 (Fin.natAdd 8 i))) j) x =
        ambientCandidate j x := by
  decide +kernel

private theorem words_pointwise_004 : ∀ i : Fin 8,
    inside (Fin.natAdd 32 (Fin.castAdd 16 (Fin.castAdd 8 i))) = false → ∀ (j : Fin 2) (x : Fin 16),
      originalCommutatorProduct g (ambientRows (Fin.natAdd 32 (Fin.castAdd 16 (Fin.castAdd 8 i)))) (saturationWords (Fin.natAdd 32 (Fin.castAdd 16 (Fin.castAdd 8 i))) j) x =
        ambientCandidate j x := by
  decide +kernel

private theorem words_pointwise_005 : ∀ i : Fin 8,
    inside (Fin.natAdd 32 (Fin.castAdd 16 (Fin.natAdd 8 i))) = false → ∀ (j : Fin 2) (x : Fin 16),
      originalCommutatorProduct g (ambientRows (Fin.natAdd 32 (Fin.castAdd 16 (Fin.natAdd 8 i)))) (saturationWords (Fin.natAdd 32 (Fin.castAdd 16 (Fin.natAdd 8 i))) j) x =
        ambientCandidate j x := by
  decide +kernel

private theorem words_pointwise_006 : ∀ i : Fin 8,
    inside (Fin.natAdd 32 (Fin.natAdd 16 (Fin.castAdd 8 i))) = false → ∀ (j : Fin 2) (x : Fin 16),
      originalCommutatorProduct g (ambientRows (Fin.natAdd 32 (Fin.natAdd 16 (Fin.castAdd 8 i)))) (saturationWords (Fin.natAdd 32 (Fin.natAdd 16 (Fin.castAdd 8 i))) j) x =
        ambientCandidate j x := by
  decide +kernel

private theorem words_pointwise_007 : ∀ i : Fin 8,
    inside (Fin.natAdd 32 (Fin.natAdd 16 (Fin.natAdd 8 i))) = false → ∀ (j : Fin 2) (x : Fin 16),
      originalCommutatorProduct g (ambientRows (Fin.natAdd 32 (Fin.natAdd 16 (Fin.natAdd 8 i)))) (saturationWords (Fin.natAdd 32 (Fin.natAdd 16 (Fin.natAdd 8 i))) j) x =
        ambientCandidate j x := by
  decide +kernel

private theorem words_pointwise : ∀ i : Fin 64,
    inside i = false → ∀ (j : Fin 2) (x : Fin 16),
      originalCommutatorProduct g (ambientRows i) (saturationWords i j) x =
        ambientCandidate j x :=
  (Fin.addCases (m := 32) (n := 32) (Fin.addCases (m := 16) (n := 16) (Fin.addCases (m := 8) (n := 8) words_pointwise_000 words_pointwise_001) (Fin.addCases (m := 8) (n := 8) words_pointwise_002 words_pointwise_003)) (Fin.addCases (m := 16) (n := 16) (Fin.addCases (m := 8) (n := 8) words_pointwise_004 words_pointwise_005) (Fin.addCases (m := 8) (n := 8) words_pointwise_006 words_pointwise_007)))


private theorem candidate_mem (j : Fin 2) : candidate j ∈ R :=
  primeRelativeFiniteGenerators_mem 2 D ambient basis
    BinaryCarrierDerivedOrder16T1332.certificate.subgroup_eq_commutator (seed j)

private theorem radicalRows_mem_closure (i : Fin 4) :
    radicalRows i ∈ Subgroup.closure (Set.range candidate) := by
  apply (Subgroup.closure (Set.range candidate)).list_prod_mem
  intro x hx
  obtain ⟨j, _, rfl⟩ := List.mem_map.mp hx
  exact Subgroup.subset_closure (Set.mem_range_self j)

private theorem radicalRows_injective : Function.Injective radicalRows := by
  intro i j h
  apply radicalRows_injective_pointwise i j
  intro x
  have he := congrArg (fun z : Original => (z : Equiv.Perm (Fin 16)) x) h
  simpa only [radicalRows_coe] using he

/-- Actual relative-radical equality uses its checked cardinality and
distinct original rows, rather than assuming the candidate is normal. -/
private theorem candidate_full : Subgroup.closure (Set.range candidate) = R := by
  have hle : Subgroup.closure (Set.range candidate) ≤ R := by
    apply (Subgroup.closure_le R).mpr
    rintro _ ⟨j, rfl⟩
    exact candidate_mem j
  apply Subgroup.eq_of_le_of_card_ge hle
  let f : Fin 4 → Subgroup.closure (Set.range candidate) :=
    fun i => ⟨radicalRows i, radicalRows_mem_closure i⟩
  have hf : Function.Injective f := by
    intro i j h
    exact radicalRows_injective (congrArg Subtype.val h)
  have hc := Nat.card_le_card_of_injective f hf
  rw [BinaryCarrierDerivedRadical16T1332.card_relative_radical]
  simpa only [Nat.card_fin] using hc

def certificate : NormalSubgroupSaturationCertificate D R ambient candidate 64 where
  radical_le := primeRelativeRadical_le 2 D
  radical_full := candidate_full
  rows := rows
  rows_mem := by
    intro i
    have hd := BinaryCarrierDerivedOrder16T1332.certificate.subgroup_eq_commutator
    change Subgroup.closure (Set.range basis) = D at hd
    have hm : rows i ∈ Subgroup.closure (Set.range basis) :=
      (BinaryCarrierDerivedOrder16T1332.certificate.cayley.mem_closure_iff _).mpr ⟨i, rfl⟩
    exact hd ▸ hm
  rows_cover := by
    intro x hx
    have hd := BinaryCarrierDerivedOrder16T1332.certificate.subgroup_eq_commutator
    change Subgroup.closure (Set.range basis) = D at hd
    rw [← hd] at hx
    exact (BinaryCarrierDerivedOrder16T1332.certificate.cayley.mem_closure_iff x).mp hx
  inside := inside
  inside_mem := by
    intro i hi
    have he : rows i = radicalRows (insideCode i) := by
      apply Subtype.ext
      rw [rows_coe, radicalRows_coe]
      exact Equiv.ext (inside_pointwise i hi)
    rw [he, ← candidate_full]
    exact radicalRows_mem_closure _
  words := saturationWords
  words_eq := by
    intro i hi j
    apply Subtype.ext
    change Original.subtype (originalCommutatorProduct ambient (rows i) (saturationWords i j)) =
      (candidate j : Equiv.Perm (Fin 16))
    rw [map_originalCommutatorProduct]
    change originalCommutatorProduct g (rows i : Equiv.Perm (Fin 16)) (saturationWords i j) = _
    rw [rows_coe, candidate_coe]
    exact Equiv.ext (words_pointwise i hi j)

/-- Every selected path begins with a genuine original commutator. -/
theorem nonempty_words : certificate.NonemptyWords := by
  change ∀ i : Fin 64, inside i = false → ∀ j : Fin 2,
    ∀ w ∈ saturationWords i j, w ≠ []
  decide +kernel

/-- All normals use conjugation by the whole literal original action. -/
theorem normal_comparable (B : Subgroup Original) [B.Normal] (hBD : B ≤ commutator Original) :
    B ≤ primeRelativeRadical 2 (commutator Original) ∨
      primeRelativeRadical 2 (commutator Original) ≤ B :=
  certificate.comparable B hBD

end SymmetricSubgroupAsymptotics.BinaryCarrierRadicalSaturation16T1332
