import SymmetricSubgroupAsymptotics.BinaryGeneratorWords
import SymmetricSubgroupAsymptotics.FiniteGeneratorNormality
import SymmetricSubgroupAsymptotics.FiniteGroupCertificates

/-!
# Sparse original-action semidirect certificates for bounded c=1 owners

The large degree-twelve owners should not be certified by an ambient
multiplication table.  This interface enumerates only the retained base and
complement.  Literal positive words prove their inclusion in the original
source, factor every original source generator, and prove that every source
generator normalizes the base.  The resulting theorems concern the actual
subgroups generated by the original permutations.
-/

set_option autoImplicit false
noncomputable section

namespace SymmetricSubgroupAsymptotics

variable {G : Type*} [Group G] [Finite G]

structure C1SparseSemidirectCertificate (G : Type*) [Group G] [Finite G] where
  sourceCount : ℕ
  baseGeneratorCount : ℕ
  complementGeneratorCount : ℕ
  sourceGenerators : Fin sourceCount → G
  baseGenerators : Fin baseGeneratorCount → G
  complementGenerators : Fin complementGeneratorCount → G
  baseOrder : ℕ
  complementOrder : ℕ
  baseCayley : FiniteCayleyCertificate baseGenerators baseOrder
  complementCayley : FiniteCayleyCertificate complementGenerators complementOrder
  baseRowsInjective : Function.Injective baseCayley.elements
  complementRowsInjective : Function.Injective complementCayley.elements
  baseInSource : BinaryNormalGeneratorWords baseGenerators sourceGenerators
  complementInSource : BinaryNormalGeneratorWords complementGenerators sourceGenerators
  sourceBaseWords : Fin sourceCount → List (Fin baseGeneratorCount)
  sourceComplementWords : Fin sourceCount → List (Fin complementGeneratorCount)
  sourceFactorization : ∀ i,
    ((sourceBaseWords i).map baseGenerators).prod *
      ((sourceComplementWords i).map complementGenerators).prod = sourceGenerators i
  conjugateWords : BinaryNormalGeneratorWords
    (fun ij : Fin sourceCount × Fin baseGeneratorCount =>
      sourceGenerators ij.1 * baseGenerators ij.2 * (sourceGenerators ij.1)⁻¹)
    baseGenerators

namespace C1SparseSemidirectCertificate

variable (C : C1SparseSemidirectCertificate G)

def action : Subgroup G :=
  Subgroup.closure (Set.range C.sourceGenerators)

def base : Subgroup G :=
  Subgroup.closure (Set.range C.baseGenerators)

def complement : Subgroup G :=
  Subgroup.closure (Set.range C.complementGenerators)

theorem base_card : Nat.card C.base = C.baseOrder :=
  C.baseCayley.card_closure C.baseRowsInjective

theorem complement_card : Nat.card C.complement = C.complementOrder :=
  C.complementCayley.card_closure C.complementRowsInjective

theorem base_le_action : C.base ≤ C.action :=
  C.baseInSource.closure_le

theorem complement_le_action : C.complement ≤ C.action :=
  C.complementInSource.closure_le

omit [Finite G] in
private theorem word_mem_closure {n : ℕ} (generators : Fin n → G)
    (word : List (Fin n)) :
    ((word.map generators).prod) ∈ Subgroup.closure (Set.range generators) := by
  apply Subgroup.list_prod_mem
  intro x hx
  obtain ⟨i, _, rfl⟩ := List.mem_map.mp hx
  exact Subgroup.subset_closure (Set.mem_range_self i)

theorem action_le_sup : C.action ≤ C.base ⊔ C.complement := by
  apply (Subgroup.closure_le _).mpr
  rintro _ ⟨i, rfl⟩
  rw [← C.sourceFactorization i]
  exact Subgroup.mul_mem _
    ((show C.base ≤ C.base ⊔ C.complement from le_sup_left)
      (word_mem_closure C.baseGenerators (C.sourceBaseWords i)))
    ((show C.complement ≤ C.base ⊔ C.complement from le_sup_right)
      (word_mem_closure C.complementGenerators (C.sourceComplementWords i)))

theorem sup_le_action : C.base ⊔ C.complement ≤ C.action :=
  sup_le C.base_le_action C.complement_le_action

theorem sup_eq_action : C.base ⊔ C.complement = C.action :=
  le_antisymm C.sup_le_action C.action_le_sup

theorem base_normal_in_action : (C.base.subgroupOf C.action).Normal :=
  generated_subgroupOf_normal_of_word_certificates
    C.baseGenerators C.sourceGenerators C.baseInSource C.conjugateWords

def actionBase : Subgroup C.action :=
  C.base.subgroupOf C.action

def actionComplement : Subgroup C.action :=
  C.complement.subgroupOf C.action

theorem action_join : C.actionBase ⊔ C.actionComplement = ⊤ := by
  change C.base.subgroupOf C.action ⊔ C.complement.subgroupOf C.action = ⊤
  rw [← Subgroup.subgroupOf_sup C.base_le_action C.complement_le_action,
    C.sup_eq_action, Subgroup.subgroupOf_self]

end C1SparseSemidirectCertificate

end SymmetricSubgroupAsymptotics
