import SymmetricSubgroupAsymptotics.EpimorphismKernelLabels
import SymmetricSubgroupAsymptotics.PermutationThreeGroupRank
import Mathlib.GroupTheory.Sylow

/-!
# One coprime character labels every epimorphism kernel

Let `A` be a normal abelian subgroup of a finite target `Q` with `Q/A` a
`q`-group, and fix one `p`-character `ℓ` of `A`, where `p ≠ q`.  Its average
`ℓ₀` over the conjugation action of `Q/A` is again a character.  If `ℓ`
detects the identity in the sense below, then an epimorphism `f : J → Q` is
determined up to its kernel by the single character `ℓ ∘ f` of the literal
subgroup of `J` generated by commutators and `q`-th powers.

Averaging the label over one fixed Sylow `q`-subgroup of `J` recovers
`ℓ₀ ∘ f` without knowing which elements of that Sylow subgroup act
nontrivially; this is where the coprimality is used.  The resulting count
uses one `p`-character space of the source, which is the joint module budget
for a central and a twisted component.  No classification of the target is
used.
-/

set_option autoImplicit false
noncomputable section
open scoped BigOperators Classical commutatorElement

namespace SymmetricSubgroupAsymptotics

/-- The literal subgroup generated by all commutators and `q`-th powers. -/
def commPowSubgroup (J : Type*) [Group J] (q : ℕ) : Subgroup J :=
  Subgroup.normalClosure ({z | ∃ x y : J, z = ⁅x, y⁆} ∪ {z | ∃ x : J, z = x ^ q})

instance commPowSubgroup_normal (J : Type*) [Group J] (q : ℕ) :
    (commPowSubgroup J q).Normal :=
  Subgroup.normalClosure_normal

theorem commutator_mem_commPowSubgroup {J : Type*} [Group J] (q : ℕ) (x y : J) :
    ⁅x, y⁆ ∈ commPowSubgroup J q :=
  Subgroup.subset_normalClosure (Or.inl ⟨x, y, rfl⟩)

theorem pow_mem_commPowSubgroup {J : Type*} [Group J] (q : ℕ) (x : J) :
    x ^ q ∈ commPowSubgroup J q :=
  Subgroup.subset_normalClosure (Or.inr ⟨x, rfl⟩)

section Fibres

variable {T C : Type*} [Group T] [Group C] [Fintype T] [Fintype C]

/-- Summing along a surjective homomorphism counts each value once for
every element of the kernel. -/
theorem sum_comp_surjective_hom {M : Type*} [AddCommMonoid M]
    (φ : T →* C) (hφ : Function.Surjective φ) (G : C → M) :
    ∑ t : T, G (φ t) = Nat.card φ.ker • ∑ c : C, G c := by
  rw [← Finset.sum_fiberwise Finset.univ φ (fun t => G (φ t)), Finset.smul_sum]
  apply Finset.sum_congr rfl
  intro c _
  have hfib : (Finset.univ.filter fun t => φ t = c).card = Nat.card φ.ker := by
    have h := MonoidHom.card_fiber_eq_of_mem_range φ (hφ c) ⟨1, map_one φ⟩
    rw [h, Nat.card_congr (Equiv.subtypeEquivRight (fun t => MonoidHom.mem_ker (f := φ))),
      Nat.card_eq_fintype_card, Fintype.card_subtype]
  rw [Finset.sum_congr rfl (fun t ht => by rw [(Finset.mem_filter.mp ht).2]),
    Finset.sum_const, hfib]

end Fibres

/-- A Sylow subgroup of a finite `q`-group is the whole group. -/
theorem sylow_eq_top_of_isPGroup {q : ℕ} [Fact q.Prime] {H : Type*} [Group H]
    [Finite H] (hH : IsPGroup q H) (S : Sylow q H) : (S : Subgroup H) = ⊤ := by
  obtain ⟨k, hk⟩ := IsPGroup.iff_card.mp hH
  have hdvd : (S : Subgroup H).index ∣ q ^ k := by
    rw [← hk]
    exact Subgroup.index_dvd_card _
  obtain ⟨m, _, hm⟩ := (Nat.dvd_prime_pow (Fact.out : q.Prime)).mp hdvd
  have hnot := S.not_dvd_index
  have hm0 : m = 0 := by
    by_contra h
    apply hnot
    rw [hm]
    exact dvd_pow_self q h
  rw [hm0, pow_zero] at hm
  exact Subgroup.index_eq_one.mp hm

variable {J Q : Type*} [Group J] [Group Q]

/-- The restriction of an epimorphism to the commutator/power subgroup lands
in any normal subgroup containing all commutators and `q`-th powers. -/
def commPowRestrict (q : ℕ) (A : Subgroup Q) [A.Normal]
    (hcomm : ∀ x y : Q, ⁅x, y⁆ ∈ A) (hpow : ∀ x : Q, x ^ q ∈ A)
    (f : J →* Q) : commPowSubgroup J q →* A :=
  (f.comp (commPowSubgroup J q).subtype).codRestrict A (by
    intro y
    have hle : commPowSubgroup J q ≤ A.comap f := by
      apply Subgroup.normalClosure_le_normal
      rintro z (⟨x, y, rfl⟩ | ⟨x, rfl⟩)
      · change f ⁅x, y⁆ ∈ A
        rw [map_commutatorElement]
        exact hcomm _ _
      · change f (x ^ q) ∈ A
        rw [map_pow]
        exact hpow _
    exact hle y.2)

@[simp] theorem commPowRestrict_coe (q : ℕ) (A : Subgroup Q) [A.Normal]
    (hcomm : ∀ x y : Q, ⁅x, y⁆ ∈ A) (hpow : ∀ x : Q, x ^ q ∈ A)
    (f : J →* Q) (y : commPowSubgroup J q) :
    (commPowRestrict q A hcomm hpow f y : Q) = f y := rfl

/-- Conjugation on an abelian normal subgroup depends only on the class
modulo that subgroup. -/
theorem conjNormal_eq_of_mem (A : Subgroup Q) [A.Normal]
    (hA : ∀ a b : A, a * b = b * a) {u u' : Q} (h : u⁻¹ * u' ∈ A) (v : A) :
    MulAut.conjNormal u' v = MulAut.conjNormal u v := by
  apply Subtype.ext
  simp only [MulAut.conjNormal_apply]
  obtain ⟨a, ha, rfl⟩ : ∃ a ∈ A, u' = u * a := ⟨u⁻¹ * u', h, by group⟩
  have hc := congrArg Subtype.val (hA ⟨a, ha⟩ v)
  simp only [Subgroup.coe_mul] at hc
  calc
    u * a * (v : Q) * (u * a)⁻¹ = u * (a * (v : Q)) * a⁻¹ * u⁻¹ := by group
    _ = u * ((v : Q) * a) * a⁻¹ * u⁻¹ := by rw [hc]
    _ = u * (v : Q) * u⁻¹ := by group

variable (p q : ℕ) [Fact p.Prime] [Fact q.Prime]

/-- Epimorphisms onto a target with an abelian normal `p`-section and a
`q`-group top are counted by one `p`-character of the source's literal
commutator/power subgroup, provided the chosen character detects. -/
theorem groupEpimorphism_card_le_coprimeSplitLabel
    (hpq : p ≠ q) [Finite J] [Finite Q]
    (A : Subgroup Q) [A.Normal] [Fintype (Q ⧸ A)] (hA : ∀ a b : A, a * b = b * a)
    (hcomm : ∀ x y : Q, ⁅x, y⁆ ∈ A) (hpow : ∀ x : Q, x ^ q ∈ A)
    (ℓ ℓ0 : A →* Multiplicative (ZMod p))
    (havg : ∀ v : A,
      ∑ c : Q ⧸ A, (ℓ (MulAut.conjNormal (Quotient.out c : Q) v)).toAdd =
        (Nat.card (Q ⧸ A) : ZMod p) * (ℓ0 v).toAdd)
    (hdet : ∀ w : Q, (∀ a : Q, ℓ ⟨⁅w, a⁆, hcomm w a⟩ = 1) →
      ℓ0 ⟨w ^ q, hpow w⟩ = 1 → w = 1) :
    Nat.card (GroupEpimorphism J Q) ≤
      Nat.card (PrimeCharacters p (commPowSubgroup J q)) * Nat.card (Q ≃* Q) := by
  letI : Fintype J := Fintype.ofFinite J
  letI : Fintype Q := Fintype.ofFinite Q
  let Φ := commPowSubgroup J q
  let fΦ : GroupEpimorphism J Q → Φ →* A :=
    fun f => commPowRestrict q A hcomm hpow f.1
  let label : GroupEpimorphism J Q → PrimeCharacters p Φ :=
    fun f => AddMonoidHom.toMultiplicativeRight.symm (ℓ.comp (fΦ f))
  have hlabel_apply (f : GroupEpimorphism J Q) (y : Φ) :
      label f (Additive.ofMul y) = (ℓ (fΦ f y)).toAdd := rfl
  -- The top quotient is a q-group, so a Sylow subgroup of J maps onto it.
  have hQA : IsPGroup q (Q ⧸ A) := by
    intro c
    obtain ⟨x, rfl⟩ := QuotientGroup.mk_surjective c
    refine ⟨1, ?_⟩
    rw [pow_one, ← QuotientGroup.mk_pow, QuotientGroup.eq_one_iff]
    exact hpow x
  let T : Sylow q J := Classical.choice inferInstance
  have htop (f : GroupEpimorphism J Q) :
      Function.Surjective ((QuotientGroup.mk' A).comp (f.1.comp (T : Subgroup J).subtype)) := by
    have hψ : Function.Surjective ((QuotientGroup.mk' A).comp f.1) :=
      (QuotientGroup.mk'_surjective A).comp f.2
    let S := T.mapSurjective hψ
    have hS : (S : Subgroup (Q ⧸ A)) = ⊤ := sylow_eq_top_of_isPGroup hQA S
    intro c
    have hc : c ∈ (S : Subgroup (Q ⧸ A)) := by rw [hS]; exact Subgroup.mem_top c
    rw [Sylow.coe_mapSurjective, Subgroup.mem_map] at hc
    obtain ⟨t, ht, htc⟩ := hc
    exact ⟨⟨t, ht⟩, htc⟩
  -- Averaging the label over T recovers the averaged character.
  have hTcard : (Nat.card T : ZMod p) ≠ 0 := by
    obtain ⟨k, hk⟩ := IsPGroup.iff_card.mp T.isPGroup'
    rw [hk, Nat.cast_pow]
    apply pow_ne_zero
    intro hzero
    rw [ZMod.natCast_eq_zero_iff] at hzero
    exact hpq ((Nat.prime_dvd_prime_iff_eq (Fact.out) (Fact.out)).mp hzero)
  have havgLabel (f : GroupEpimorphism J Q) (y : Φ) :
      ∑ t : T, label f (Additive.ofMul (MulAut.conjNormal (t : J) y)) =
        (Nat.card T : ZMod p) * (ℓ0 (fΦ f y)).toAdd := by
    let φ := (QuotientGroup.mk' A).comp (f.1.comp (T : Subgroup J).subtype)
    let v := fΦ f y
    let G : Q ⧸ A → ZMod p :=
      fun c => (ℓ (MulAut.conjNormal (Quotient.out c : Q) v)).toAdd
    have hterm (t : T) : label f (Additive.ofMul (MulAut.conjNormal (t : J) y)) = G (φ t) := by
      rw [hlabel_apply]
      have hconj : fΦ f (MulAut.conjNormal (t : J) y) = MulAut.conjNormal (f.1 t) v := by
        apply Subtype.ext
        change f.1 (((MulAut.conjNormal (t : J) y : Φ)) : J) =
          f.1 t * f.1 (y : J) * (f.1 t)⁻¹
        simp only [MulAut.conjNormal_apply, map_mul, map_inv]
      rw [hconj]
      change (ℓ (MulAut.conjNormal (f.1 t) v)).toAdd =
        (ℓ (MulAut.conjNormal (Quotient.out (QuotientGroup.mk (f.1 t) : Q ⧸ A) : Q) v)).toAdd
      congr 2
      apply conjNormal_eq_of_mem A hA
      have h := QuotientGroup.mk_out_eq_mul A (f.1 t)
      obtain ⟨a, ha⟩ := h
      rw [ha]
      simp [a.2]
    simp only [hterm]
    rw [sum_comp_surjective_hom φ (htop f) G, havg v]
    have hcard : Nat.card T = Nat.card φ.ker * Nat.card (Q ⧸ A) := by
      rw [← Nat.card_congr (QuotientGroup.quotientKerEquivOfSurjective φ (htop f)).toEquiv]
      exact (Subgroup.card_eq_card_quotient_mul_card_subgroup φ.ker).trans (mul_comm _ _)
    rw [hcard, nsmul_eq_mul, Nat.cast_mul]
    ring
  have hℓ0 (f g : GroupEpimorphism J Q) (h : label f = label g) (y : Φ) :
      ℓ0 (fΦ f y) = ℓ0 (fΦ g y) := by
    have hf := havgLabel f y
    have hg := havgLabel g y
    rw [h] at hf
    have hmul := hf.symm.trans hg
    have hcancel := mul_left_cancel₀ hTcard hmul
    exact Multiplicative.toAdd.injective hcancel
  have hkernel (f g : GroupEpimorphism J Q) (h : label f = label g) :
      f.1.ker ≤ g.1.ker := by
    intro x hx
    have hfx : f.1 x = 1 := hx
    change g.1 x = 1
    apply hdet
    · intro a
      obtain ⟨y, rfl⟩ := g.2 a
      let z : Φ := ⟨⁅x, y⁆, commutator_mem_commPowSubgroup q x y⟩
      have hz := DFunLike.congr_fun h (Additive.ofMul z)
      rw [hlabel_apply, hlabel_apply] at hz
      have hfz : fΦ f z = 1 := by
        apply Subtype.ext
        change f.1 ⁅x, y⁆ = 1
        rw [map_commutatorElement, hfx, commutatorElement_one_left]
      have hgz : fΦ g z = ⟨⁅g.1 x, g.1 y⁆, hcomm _ _⟩ := by
        apply Subtype.ext
        change g.1 ⁅x, y⁆ = ⁅g.1 x, g.1 y⁆
        exact map_commutatorElement _ _ _
      rw [hfz, map_one, hgz] at hz
      exact Multiplicative.toAdd.injective hz.symm
    · let z : Φ := ⟨x ^ q, pow_mem_commPowSubgroup q x⟩
      have h0 := hℓ0 f g h z
      have hfz : fΦ f z = 1 := by
        apply Subtype.ext
        change f.1 (x ^ q) = 1
        rw [map_pow, hfx, one_pow]
      have hgz : fΦ g z = ⟨(g.1 x) ^ q, hpow _⟩ := by
        apply Subtype.ext
        change g.1 (x ^ q) = (g.1 x) ^ q
        exact map_pow _ _ _
      rw [hfz, map_one, hgz] at h0
      exact h0.symm
  exact groupEpimorphism_card_le_kernel_labels label
    (fun f g h => le_antisymm (hkernel f g h) (hkernel g f h.symm))

/-- The source label space has the permutation rank bound. -/
theorem primeCharacters_commPow_card_le (p q : ℕ) [Fact p.Prime] (b : ℕ)
    (J : Subgroup (Equiv.Perm (Fin b))) (r : ℕ)
    (hrank : ∀ (G X : Type) [Group G] [Finite G] [Finite X] [MulAction G X]
      [FaithfulSMul G X], Module.finrank (ZMod p) (PrimeCharacters p G) ≤ Nat.card X / r) :
    Nat.card (PrimeCharacters p (commPowSubgroup J q)) ≤ p ^ (b / r) := by
  have h := hrank (commPowSubgroup J q) (Fin b)
  rw [Module.natCard_eq_pow_finrank (K := ZMod p), Nat.card_zmod]
  simpa only [Nat.card_fin] using
    Nat.pow_le_pow_right (Fact.out : p.Prime).pos h

end SymmetricSubgroupAsymptotics

end
