import SymmetricSubgroupAsymptotics.PrimeEvaluationKernelGenerators
import SymmetricSubgroupAsymptotics.BinaryGeneratorWords
import Mathlib.Algebra.Group.End

/-! Small original-generator expressions certified to lie in the actual
derived subgroup. Literal ambient equations transfer to the subgroup
generated by the same tuple; no Cayley table, order or abstract group
identification is used. -/
set_option autoImplicit false
open scoped commutatorElement

namespace SymmetricSubgroupAsymptotics

/-- A word assembled from basic commutators of the displayed original
generators, with multiplication, inversion and generator conjugation. -/
inductive DerivedGeneratorWord (ι : Type*) where
  | one : DerivedGeneratorWord ι
  | comm : ι → ι → DerivedGeneratorWord ι
  | mul : DerivedGeneratorWord ι → DerivedGeneratorWord ι → DerivedGeneratorWord ι
  | inv : DerivedGeneratorWord ι → DerivedGeneratorWord ι
  | conj : ι → DerivedGeneratorWord ι → DerivedGeneratorWord ι
  | conjInv : ι → DerivedGeneratorWord ι → DerivedGeneratorWord ι

namespace DerivedGeneratorWord

variable {ι G H : Type*} [Group G] [Group H]

/-- Mathlib's basic commutator is a*b*a⁻¹*b⁻¹; this orientation is part
of the literal certificate. Both conjugation directions are explicit. -/
def eval : DerivedGeneratorWord ι → (ι → G) → G
  | .one, _ => 1
  | .comm i j, g => ⁅g i, g j⁆
  | .mul u v, g => u.eval g * v.eval g
  | .inv u, g => (u.eval g)⁻¹
  | .conj i u, g => g i * u.eval g * (g i)⁻¹
  | .conjInv i u, g => (g i)⁻¹ * u.eval g * g i

/-- Every expression belongs to the derived subgroup of this exact G. -/
theorem eval_mem_commutator (w : DerivedGeneratorWord ι) (g : ι → G) :
    w.eval g ∈ commutator G := by
  induction w with
  | one => exact (commutator G).one_mem
  | comm i j =>
      exact Subgroup.commutator_mem_commutator (Subgroup.mem_top (g i))
        (Subgroup.mem_top (g j))
  | mul u v hu hv => exact (commutator G).mul_mem hu hv
  | inv u hu => exact (commutator G).inv_mem hu
  | conj i u hu =>
      exact Subgroup.Normal.conj_mem inferInstance _ hu (g i)
  | conjInv i u hu =>
      simpa only [eval, inv_inv] using
        (Subgroup.Normal.conj_mem (inferInstance : (commutator G).Normal)
          (u.eval g) hu (g i)⁻¹)

/-- Evaluation commutes with the literal homomorphism on every original
generator, including all inverse and conjugation operations. -/
theorem map_eval (f : G →* H) (w : DerivedGeneratorWord ι) (g : ι → G) :
    f (w.eval g) = w.eval (fun i => f (g i)) := by
  induction w <;>
    simp_all only [eval, map_one, map_mul, map_inv, map_commutatorElement]

end DerivedGeneratorWord

noncomputable section

variable {G ι : Type*} [Group G]

/-- The lifted tuple uses exactly the original ambient generator values. -/
def closureGenerators (g : ι → G) : ι → Subgroup.closure (Set.range g) :=
  fun i => ⟨g i, Subgroup.subset_closure (Set.mem_range_self i)⟩

theorem closureGenerators_full (g : ι → G) :
    Subgroup.closure (Set.range (closureGenerators g)) = ⊤ :=
  binaryNormal_full_generators_of_equiv g (closureGenerators g)
    (MulEquiv.refl _) (fun _ => rfl)

/-- The inclusion into the original ambient group evaluates each word
pointwise, so checked permutation equalities are sufficient. -/
theorem closureGenerators_eval_coe (g : ι → G) (w : DerivedGeneratorWord ι) :
    (w.eval (G := Subgroup.closure (Set.range g)) (closureGenerators g) : G) =
      w.eval g :=
  DerivedGeneratorWord.map_eval (Subgroup.closure (Set.range g)).subtype
    w (closureGenerators g)

/-- A finite producer needs only original ambient equations for the
generator powers. Derived membership and exact kernel identification are
proved generically on the literal subgroup generated by that same tuple. -/
theorem primeEvaluationKernel_closure_eq_commutator_of_words
    (p : ℕ) [Fact p.Prime] (g : ι → G) (words : ι → DerivedGeneratorWord ι)
    (hwords : ∀ i, (g i)^p = (words i).eval g) :
    (primeAbelianizationGroupMap p (Subgroup.closure (Set.range g))).ker =
      commutator (Subgroup.closure (Set.range g)) := by
  apply primeAbelianizationGroupMap_ker_eq_commutator_of_generator_powers
    p (closureGenerators g) (closureGenerators_full g)
  intro i
  have he : (closureGenerators g i)^p = (words i).eval (closureGenerators g) := by
    apply Subtype.ext
    change (g i)^p =
      ((words i).eval (G := Subgroup.closure (Set.range g)) (closureGenerators g) : G)
    rw [closureGenerators_eval_coe]
    exact hwords i
  rw [he]
  exact DerivedGeneratorWord.eval_mem_commutator (words i) (closureGenerators g)

variable {X : Type*}

/-- A finite certificate checks only values of the original permutations.
On Fin n the hypothesis is a closed decidable proposition; equality of
permutation structures and their inverse-law proofs is unnecessary. -/
theorem permutation_square_eq_derivedWord_of_pointwise
    (g : ι → Equiv.Perm X) (i : ι) (w : DerivedGeneratorWord ι)
    (h : ∀ x, g i (g i x) = w.eval g x) :
    (g i)^2 = w.eval g := by
  apply Equiv.ext
  intro x
  simpa only [pow_two, Equiv.Perm.mul_apply] using h x

/-- The selected finite-permutation producer can use one pointwise
kernel-decidable check per original generator, with no source table. -/
theorem binaryEvaluationKernel_permClosure_eq_commutator_of_pointwise
    (g : ι → Equiv.Perm X) (words : ι → DerivedGeneratorWord ι)
    (hwords : ∀ i x, g i (g i x) = (words i).eval g x) :
    (primeAbelianizationGroupMap 2 (Subgroup.closure (Set.range g))).ker =
      commutator (Subgroup.closure (Set.range g)) := by
  apply primeEvaluationKernel_closure_eq_commutator_of_words 2 g words
  intro i
  exact permutation_square_eq_derivedWord_of_pointwise g i (words i) (hwords i)

end
end SymmetricSubgroupAsymptotics
