import SymmetricSubgroupAsymptotics.InducedSubrepresentationCount
import SymmetricSubgroupAsymptotics.RepresentationCoordinateHeads
import SymmetricSubgroupAsymptotics.RepresentationHeadExact
import SymmetricSubgroupAsymptotics.SchurRepresentation

/-!
# Schur capacity from generators of the contragredient

Dualising an intertwiner embeds every simple-source Hom space into a Hom
space whose source is the contragredient target.  Consequently a generating
tuple for that contragredient bounds the Schur capacity.  This is the
algebraic step used by the affine normal-graph incidence.
-/

set_option autoImplicit false
set_option linter.unusedSectionVars false
set_option backward.isDefEq.respectTransparency false
noncomputable section
open scoped Classical MonoidAlgebra

namespace SymmetricSubgroupAsymptotics

variable {k G V W : Type} [Field k] [Group G]
  [AddCommGroup V] [Module k V] [AddCommGroup W] [Module k W]

/-- A generated representation admits at most `H * dim W` intertwining maps
to a finite-dimensional target `W`. -/
theorem intertwiningMap_finrank_le_of_generated_source
    (rho : Representation k G V) (sigma : Representation k G W)
    [FiniteDimensional k W] (H : ℕ)
    (hgen : RepresentationGeneratedBy rho H) :
    Module.finrank k (rho.IntertwiningMap sigma) ≤
      H * Module.finrank k W := by
  obtain ⟨v, hv⟩ := hgen
  let ev : (rho.IntertwiningMap sigma) →ₗ[k] (Fin H → W) :=
    { toFun := fun f i ↦ f (v i)
      map_add' := by intro f g; funext i; rfl
      map_smul' := by intro a f; funext i; rfl }
  have hev : Function.Injective ev := by
    intro f g hfg
    apply Representation.IntertwiningMap.ext
    apply LinearMap.ext
    intro x
    let f' : rho.asModule →ₗ[k[G]] sigma.asModule :=
      Representation.IntertwiningMap.equivLinearMapAsModule rho sigma f
    let g' : rho.asModule →ₗ[k[G]] sigma.asModule :=
      Representation.IntertwiningMap.equivLinearMapAsModule rho sigma g
    have heq : f' = g' := LinearMap.ext_on_range hv (fun i ↦ congrFun hfg i)
    exact DFunLike.congr_fun heq x
  have h := ev.finrank_le_finrank_of_injective hev
  simpa only [Module.finrank_pi_fintype, Finset.sum_const,
    Finset.card_univ, Fintype.card_fin, Nat.nsmul_eq_mul] using h

/-- Dualisation is injective on the finite-dimensional intertwining-map
space. -/
private theorem dualIntertwiner_injective
    (rho : Representation k G V) (sigma : Representation k G W)
    [FiniteDimensional k W] :
    Function.Injective
      (fun f : rho.IntertwiningMap sigma ↦
        RepresentationHeadExact.dualMap f) := by
  intro f g hfg
  apply Representation.IntertwiningMap.ext
  have hdual : f.toLinearMap.dualMap = g.toLinearMap.dualMap :=
    congrArg Representation.IntertwiningMap.toLinearMap hfg
  apply LinearMap.ext
  intro x
  apply (Module.bijective_dual_eval k W).1
  ext l
  exact DFunLike.congr_fun (DFunLike.congr_fun hdual l) x

/-- If the contragredient is generated by `H` elements, the original
representation has Schur capacity at most `H`. -/
theorem representationSchurCapacity_le_of_dual_generated
    (sigma : Representation k G W) [FiniteDimensional k W]
    (H : ℕ) (hgen : RepresentationGeneratedBy sigma.dual H) :
    representationSchurCapacity sigma ≤ H := by
  unfold representationSchurCapacity schurCapacity
  apply csSup_le (Set.insert_nonempty _ _)
  rintro x (rfl | ⟨S, hS, rfl⟩)
  · positivity
  · letI : Module k[G] sigma.asModule :=
      Representation.instModuleMonoidAlgebraAsModule sigma
    letI : IsScalarTower k k[G] sigma.asModule :=
      inferInstanceAs (IsScalarTower k k[G] (Representation.asModule sigma))
    letI : IsSimpleModule k[G] S := hS
    haveI : Nontrivial S := IsSimpleModule.nontrivial k[G] S
    let tau : Representation k G
        (Subrepresentation.ofSubmodule' S).toSubmodule :=
      (Subrepresentation.ofSubmodule' S).toRepresentation
    letI : FiniteDimensional k S := FiniteDimensional.of_injective
      (S.subtype.restrictScalars k) S.subtype_injective
    letI : FiniteDimensional k
        (Subrepresentation.ofSubmodule' S).toSubmodule :=
      FiniteDimensional.of_injective
        (Subrepresentation.ofSubmodule' S).toSubmodule.subtype
        (Subrepresentation.ofSubmodule' S).toSubmodule.injective_subtype
    have hdual : Module.finrank k (tau.IntertwiningMap sigma) ≤
        Module.finrank k (sigma.dual.IntertwiningMap tau.dual) := by
      let d : (tau.IntertwiningMap sigma) →ₗ[k]
          (sigma.dual.IntertwiningMap tau.dual) :=
        { toFun := fun f ↦ RepresentationHeadExact.dualMap f
          map_add' := by
            intro f g
            apply Representation.IntertwiningMap.ext
            ext l v
            simp [RepresentationHeadExact.dualMap, LinearMap.dualMap_apply]
          map_smul' := by
            intro a f
            apply Representation.IntertwiningMap.ext
            ext l v
            simp [RepresentationHeadExact.dualMap, LinearMap.dualMap_apply] }
      exact d.finrank_le_finrank_of_injective
        (dualIntertwiner_injective tau sigma)
    have htarget : Module.finrank k (sigma.dual.IntertwiningMap tau.dual) ≤
        H * Module.finrank k S := by
      have h := intertwiningMap_finrank_le_of_generated_source
        sigma.dual tau.dual H hgen
      rw [Subspace.dual_finrank_eq] at h
      have hfin : Module.finrank k
          (Subrepresentation.ofSubmodule' S).toSubmodule =
          Module.finrank k S := by
        rw [← tau.asModuleEquiv.finrank_eq]
        exact ((submoduleRepresentationModuleEquiv sigma S).restrictScalars k).finrank_eq.symm
      simpa only [tau, hfin] using h
    have hhom : Module.finrank k (S →ₗ[k[G]] sigma.asModule) ≤
        H * Module.finrank k S := by
      have h := hdual.trans htarget
      rw [(Representation.IntertwiningMap.equivLinearMapAsModule tau sigma).finrank_eq]
        at h
      rw [(moduleHomDomainEquiv (k := k) (A := sigma.asModule)
        (submoduleRepresentationModuleEquiv sigma S)).finrank_eq]
      exact h
    have hpos : (0 : ℝ) < Module.finrank k S := by
      exact_mod_cast (Module.finrank_pos (R := k) (M := S))
    apply (div_le_iff₀ hpos).mpr
    exact_mod_cast hhom

end SymmetricSubgroupAsymptotics

end
