import SymmetricSubgroupAsymptotics.DualGeneratorSchurCapacity

/-!
# Fixed-space capacity from dual module generators

A generating tuple for the contragredient controls the trivial head of that
contragredient, hence the fixed space of the original representation.  This
is the fixed-radical half of the affine prime-cut argument.
-/

set_option autoImplicit false
set_option backward.isDefEq.respectTransparency false
noncomputable section
open scoped Classical MonoidAlgebra

namespace SymmetricSubgroupAsymptotics

variable {k G V W : Type} [Field k] [Group G]
  [AddCommGroup V] [Module k V]
  [AddCommGroup W] [Module k W]

private def trivialIntertwiningInvariants
    (sigma : Representation k G V) :
    (Representation.trivial k G k).IntertwiningMap sigma ≃ₗ[k]
      sigma.invariants where
  toFun f := ⟨f 1, fun g ↦ by
    simpa using
      (Representation.IntertwiningMap.isIntertwining _ _ f g 1).symm⟩
  invFun a :=
    (LinearMap.toSpanSingleton k V a.1).intertwiningMap_of_isIntertwiningMap
      _ _ (by
        intro g t
        change t • a.1 = sigma g (t • a.1)
        rw [map_smul, a.2 g])
  left_inv f := by
    apply Representation.IntertwiningMap.ext
    apply LinearMap.ext
    intro t
    change t • f 1 = f t
    simpa using (f.toLinearMap.map_smul t (1 : k)).symm
  right_inv a := by apply Subtype.ext; simp
  map_add' f g := by apply Subtype.ext; rfl
  map_smul' t f := by apply Subtype.ext; rfl

private def dualizationLinearMap
    (rho : Representation k G V) (sigma : Representation k G W) :
    (rho.IntertwiningMap sigma) →ₗ[k]
      (sigma.dual.IntertwiningMap rho.dual) where
  toFun := RepresentationHeadExact.dualMap
  map_add' f g := by
    apply Representation.IntertwiningMap.ext
    ext l v
    simp [RepresentationHeadExact.dualMap, LinearMap.dualMap_apply]
  map_smul' a f := by
    apply Representation.IntertwiningMap.ext
    ext l v
    simp [RepresentationHeadExact.dualMap, LinearMap.dualMap_apply]

private theorem dualizationLinearMap_injective
    (rho : Representation k G V) (sigma : Representation k G W)
    [FiniteDimensional k W] :
    Function.Injective (dualizationLinearMap rho sigma) := by
  intro f g hfg
  apply Representation.IntertwiningMap.ext
  have hdual : f.toLinearMap.dualMap = g.toLinearMap.dualMap :=
    congrArg Representation.IntertwiningMap.toLinearMap hfg
  apply LinearMap.ext
  intro x
  apply (Module.bijective_dual_eval k W).1
  ext l
  exact DFunLike.congr_fun (DFunLike.congr_fun hdual l) x

/-- If the contragredient is generated by `H` elements, the original fixed
space has dimension at most `H`. -/
theorem invariants_finrank_le_of_dual_generated
    (sigma : Representation k G W) [FiniteDimensional k W]
    (H : ℕ) (hgen : RepresentationGeneratedBy sigma.dual H) :
    Module.finrank k sigma.invariants ≤ H := by
  let triv := Representation.trivial k G k
  have hinj : Module.finrank k (triv.IntertwiningMap sigma) ≤
      Module.finrank k (sigma.dual.IntertwiningMap triv.dual) :=
    (dualizationLinearMap triv sigma).finrank_le_finrank_of_injective
      (dualizationLinearMap_injective triv sigma)
  have htarget := intertwiningMap_finrank_le_of_generated_source
    sigma.dual triv.dual H hgen
  have hdim : Module.finrank k (Module.Dual k k) = 1 := by
    rw [Subspace.dual_finrank_eq, Module.finrank_self]
  have htarget' :
      Module.finrank k (sigma.dual.IntertwiningMap triv.dual) ≤ H := by
    simpa only [hdim, mul_one] using htarget
  rw [← (trivialIntertwiningInvariants sigma).finrank_eq]
  exact hinj.trans htarget'

end SymmetricSubgroupAsymptotics

end
