import SymmetricSubgroupAsymptotics.BinaryTransport
import Mathlib.GroupTheory.OrderOfElement

/-!
# Finite Cayley and homomorphism certificates

Finite tables are certificates, not axioms. Right-generator transitions and
words for every row prove equality with the literal generated subgroup. A
graph table whose first-coordinate kernel is trivial then gives an actual
homomorphism with exactly the listed generator images.
-/

set_option autoImplicit false
noncomputable section
open scoped Pointwise

namespace SymmetricSubgroupAsymptotics

variable {G Q ι : Type*} [Group G] [Group Q]

/-- A finite enumeration with checked generator transitions and a word
certificate for every row. Duplicate rows are permitted. -/
structure FiniteCayleyCertificate (generators : ι → G) (n : ℕ) where
  elements : Fin n → G
  identity : Fin n
  identity_eq : elements identity = 1
  next : Fin n → ι → Fin n
  next_eq : ∀ i j, elements (next i j) = elements i * generators j
  words : Fin n → List ι
  words_eq : ∀ i, elements i = ((words i).map generators).prod

namespace FiniteCayleyCertificate

variable {generators : ι → G} {n : ℕ} (C : FiniteCayleyCertificate generators n)

theorem mul_word_mem (w : List ι) {x : G} (hx : x ∈ Set.range C.elements) :
    x * (w.map generators).prod ∈ Set.range C.elements := by
  induction w generalizing x with
  | nil => simpa using hx
  | cons j w ih =>
    rcases hx with ⟨i, rfl⟩
    simpa only [List.map_cons, List.prod_cons, ← mul_assoc] using
      ih (show C.elements i * generators j ∈ Set.range C.elements from
        ⟨C.next i j, C.next_eq i j⟩)

/-- The listed rows are the exact literal group generated by the inputs. -/
theorem range_eq_closure [Finite G] :
    Set.range C.elements = (Subgroup.closure (Set.range generators) : Set G) := by
  let S := Set.range C.elements
  have h1 : (1 : G) ∈ S := ⟨C.identity, C.identity_eq⟩
  have hmul : ∀ x ∈ S, ∀ y ∈ S, x*y ∈ S := by
    intro x hx y hy
    obtain ⟨j, rfl⟩ := hy
    rw [C.words_eq j]
    exact C.mul_word_mem _ hx
  have hSS : S*S = S := by
    apply le_antisymm
    · rintro _ ⟨x,hx,y,hy,rfl⟩
      exact hmul x hx y hy
    · intro x hx
      exact ⟨1,h1,x,hx,one_mul x⟩
  let H := subgroupOfIdempotent S ⟨1,h1⟩ hSS
  have hgen : Subgroup.closure (Set.range generators) ≤ H := by
    apply (Subgroup.closure_le _).mpr
    rintro x ⟨j,rfl⟩
    exact ⟨C.next C.identity j, by rw [C.next_eq, C.identity_eq, one_mul]⟩
  apply Set.Subset.antisymm
  · rintro x ⟨i,rfl⟩
    rw [C.words_eq i]
    apply Subgroup.list_prod_mem
    intro y hy
    obtain ⟨j, _, rfl⟩ := List.mem_map.mp hy
    exact Subgroup.subset_closure (Set.mem_range_self j)
  · exact hgen

theorem mem_closure_iff [Finite G] (x : G) :
    x ∈ Subgroup.closure (Set.range generators) ↔ ∃ i, C.elements i = x := by
  exact Set.ext_iff.mp C.range_eq_closure x |>.symm

/-- An injective row table determines the actual group cardinality. -/
theorem card_closure [Finite G] (hinj : Function.Injective C.elements) :
    Nat.card (Subgroup.closure (Set.range generators)) = n := by
  let f : Fin n → Subgroup.closure (Set.range generators) :=
    fun i => ⟨C.elements i, (C.mem_closure_iff _).mpr ⟨i,rfl⟩⟩
  have hf : Function.Bijective f := by
    constructor
    · intro i j he
      exact hinj (congrArg Subtype.val he)
    · rintro ⟨x,hx⟩
      obtain ⟨i,hi⟩ := (C.mem_closure_iff _).mp hx
      exact ⟨i,Subtype.ext hi⟩
  exact (Nat.card_congr (Equiv.ofBijective f hf)).symm.trans (Nat.card_fin n)

end FiniteCayleyCertificate

/-- A checked finite graph of generator images. The last condition is
tested on actual rows and rules out a hidden relation in the source. -/
structure FiniteHomCertificate (generators : ι → G) (images : ι → Q) (n : ℕ) where
  cayley : FiniteCayleyCertificate (fun j => (generators j, images j)) n
  first_kernel : ∀ i, (cayley.elements i).1 = 1 → (cayley.elements i).2 = 1

namespace FiniteHomCertificate

variable [Finite G] [Finite Q] {generators : ι → G} {images : ι → Q} {n : ℕ}
    (C : FiniteHomCertificate generators images n)

def graph (_C : FiniteHomCertificate generators images n) : Subgroup (G × Q) :=
  Subgroup.closure (Set.range (fun j => (generators j, images j)))

omit [Finite G] [Finite Q] in
theorem first_image : C.graph.map (MonoidHom.fst G Q) =
    Subgroup.closure (Set.range generators) := by
  rw [graph, MonoidHom.map_closure]
  congr 1
  ext x
  simp

omit [Finite G] [Finite Q] in
theorem second_image : C.graph.map (MonoidHom.snd G Q) =
    Subgroup.closure (Set.range images) := by
  rw [graph, MonoidHom.map_closure]
  congr 1
  ext x
  simp

def first : C.graph →* Subgroup.closure (Set.range generators) :=
  ((MonoidHom.fst G Q).comp C.graph.subtype).codRestrict _ (fun x => by
    rw [← C.first_image]
    exact ⟨x, x.property, rfl⟩)

omit [Finite G] [Finite Q] in
theorem first_surjective : Function.Surjective C.first := by
  rintro ⟨x,hx⟩
  rw [← C.first_image] at hx
  obtain ⟨y,hy,he⟩ := hx
  exact ⟨⟨y,hy⟩, Subtype.ext he⟩

theorem first_injective : Function.Injective C.first := by
  apply (MonoidHom.ker_eq_bot_iff C.first).mp
  apply le_antisymm _ bot_le
  intro x hx
  have hx1 : (x : G × Q).1 = 1 := congrArg Subtype.val hx
  have hmem : (x : G × Q) ∈ Subgroup.closure
      (Set.range (fun j => (generators j, images j))) := x.property
  obtain ⟨i,hi⟩ := (C.cayley.mem_closure_iff _).mp hmem
  have hx2 : (x : G × Q).2 = 1 := by
    rw [← hi]
    exact C.first_kernel i (by simpa only [hi] using hx1)
  exact Subtype.ext (Prod.ext hx1 hx2)

def firstEquiv : C.graph ≃* Subgroup.closure (Set.range generators) :=
  MulEquiv.ofBijective C.first ⟨C.first_injective,C.first_surjective⟩

/-- The actual homomorphism certified by the finite graph. -/
def hom : Subgroup.closure (Set.range generators) →* Q :=
  ((MonoidHom.snd G Q).comp C.graph.subtype).comp C.firstEquiv.symm.toMonoidHom

theorem hom_graph (x : Subgroup.closure (Set.range generators)) :
    ((x : G), C.hom x) ∈ C.graph := by
  have hx := (C.firstEquiv.symm x).property
  have hfirst : (C.firstEquiv.symm x : G × Q).1 = x :=
    congrArg Subtype.val (C.firstEquiv.apply_symm_apply x)
  simpa only [← hfirst] using hx

theorem hom_eq_of_graph (x : Subgroup.closure (Set.range generators)) (y : Q)
    (hxy : ((x : G),y) ∈ C.graph) : C.hom x = y := by
  have he : C.firstEquiv.symm x = ⟨((x : G),y),hxy⟩ := by
    apply C.firstEquiv.injective
    exact C.firstEquiv.apply_symm_apply x
  exact congrArg (fun z : C.graph => (z : G × Q).2) he

@[simp] theorem hom_generator (j : ι) :
    C.hom ⟨generators j,Subgroup.subset_closure (Set.mem_range_self j)⟩ = images j :=
  C.hom_eq_of_graph _ _ (Subgroup.subset_closure (Set.mem_range_self j))

theorem hom_range : C.hom.range = Subgroup.closure (Set.range images) := by
  apply le_antisymm
  · rintro y ⟨x,rfl⟩
    rw [← C.second_image]
    exact ⟨((x:G),C.hom x),C.hom_graph x,rfl⟩
  · apply (Subgroup.closure_le _).mpr
    rintro y ⟨j,rfl⟩
    exact ⟨⟨generators j,Subgroup.subset_closure (Set.mem_range_self j)⟩,
      C.hom_generator j⟩

theorem source_mem (i : Fin n) : (C.cayley.elements i).1 ∈
    Subgroup.closure (Set.range generators) := by
  rw [← C.first_image]
  exact ⟨C.cayley.elements i, (C.cayley.mem_closure_iff _).mpr ⟨i,rfl⟩,rfl⟩

theorem source_mem_iff (x : G) :
    x ∈ Subgroup.closure (Set.range generators) ↔
      ∃ i, (C.cayley.elements i).1 = x := by
  rw [← C.first_image]
  constructor
  · rintro ⟨z,hz,hzx⟩
    obtain ⟨i,hi⟩ := (C.cayley.mem_closure_iff _).mp hz
    exact ⟨i,(congrArg Prod.fst hi).trans hzx⟩
  · rintro ⟨i,rfl⟩
    exact ⟨C.cayley.elements i,
      (C.cayley.mem_closure_iff _).mpr ⟨i,rfl⟩,rfl⟩

theorem hom_element (i : Fin n) :
    C.hom ⟨(C.cayley.elements i).1,C.source_mem i⟩ = (C.cayley.elements i).2 :=
  C.hom_eq_of_graph _ _ ((C.cayley.mem_closure_iff _).mpr ⟨i,rfl⟩)

theorem hom_range_mem_iff (y : Q) : y ∈ C.hom.range ↔
    ∃ i, (C.cayley.elements i).2 = y := by
  constructor
  · rintro ⟨x,rfl⟩
    obtain ⟨i,hi⟩ := (C.cayley.mem_closure_iff _).mp (C.hom_graph x)
    have he := congrArg (fun z : G × Q => z.2) hi
    exact ⟨i,he⟩
  · rintro ⟨i,rfl⟩
    exact ⟨⟨(C.cayley.elements i).1,C.source_mem i⟩,C.hom_element i⟩

theorem kernel_image_mem_iff (x : G) :
    x ∈ C.hom.ker.map (Subgroup.closure (Set.range generators)).subtype ↔
      ∃ i, (C.cayley.elements i).1 = x ∧ (C.cayley.elements i).2 = 1 := by
  constructor
  · rintro ⟨y,hy,rfl⟩
    obtain ⟨i,hi⟩ := (C.cayley.mem_closure_iff _).mp (C.hom_graph y)
    exact ⟨i,congrArg Prod.fst hi,(congrArg Prod.snd hi).trans hy⟩
  · rintro ⟨i,rfl,hi⟩
    exact ⟨⟨(C.cayley.elements i).1,C.source_mem i⟩,
      (C.hom_element i).trans hi,rfl⟩

/-- A table equality with a separately certified quotient installs the
literal image group, without an abstract group identifier. -/
theorem hom_range_eq_of_rows {κ : Type*} {qgenerators : κ → Q} {m : ℕ}
    (D : FiniteCayleyCertificate qgenerators m)
    (forward : Fin n → Fin m) (backward : Fin m → Fin n)
    (hf : ∀ i, (C.cayley.elements i).2 = D.elements (forward i))
    (hb : ∀ j, D.elements j = (C.cayley.elements (backward j)).2) :
    C.hom.range = Subgroup.closure (Set.range qgenerators) := by
  ext y
  rw [C.hom_range_mem_iff,D.mem_closure_iff]
  exact ⟨fun ⟨i,hi⟩ => ⟨forward i,(hf i).symm.trans hi⟩,
    fun ⟨j,hj⟩ => ⟨backward j,(hb j).symm.trans hj⟩⟩

/-- Exact kernel identification from the original generator rows and a
separate checked enumeration of the original kernel. -/
theorem kernel_image_eq_of_rows {κ : Type*} {kgenerators : κ → G} {m : ℕ}
    (D : FiniteCayleyCertificate kgenerators m)
    (forward : Fin n → Fin m) (backward : Fin m → Fin n)
    (hf : ∀ i, (C.cayley.elements i).2 = 1 →
      (C.cayley.elements i).1 = D.elements (forward i))
    (hb : ∀ j, (C.cayley.elements (backward j)).1 = D.elements j ∧
      (C.cayley.elements (backward j)).2 = 1) :
    C.hom.ker.map (Subgroup.closure (Set.range generators)).subtype =
      Subgroup.closure (Set.range kgenerators) := by
  ext x
  rw [C.kernel_image_mem_iff,D.mem_closure_iff]
  exact ⟨fun ⟨i,hi,h1⟩ => ⟨forward i,(hf i h1).symm.trans hi⟩,
    fun ⟨j,hj⟩ => ⟨backward j,(hb j).1.trans hj,(hb j).2⟩⟩

end FiniteHomCertificate

end SymmetricSubgroupAsymptotics
