import SymmetricSubgroupAsymptotics.Non2PreE7B6RankTailSource

/-!
# Padded generators for a finite group

If `|R| ≤ 2^l`, every subgroup of `R` is the closure of an `l`-tuple.
Consequently `R` has at most `|R|^l ≤ 2^(l^2)` subgroups, and the same
bound holds for its literal normal-subgroup axes.  This is the elementary
finite-group input used by the SNS complete quotient envelope.
-/

set_option autoImplicit false
noncomputable section
open scoped Classical

namespace SymmetricSubgroupAsymptotics

variable {R : Type*} [Group R]

/-- The subgroup generated by a padded tuple. -/
def paddedTupleClosure (l : ℕ) (f : Fin l → R) : Subgroup R :=
  Subgroup.closure (Set.range f)

/-- A generating finset of cardinality at most `l` can be padded by the
identity to an `l`-tuple without changing its closure. -/
theorem exists_paddedTupleClosure_eq (l : ℕ) (H : Subgroup R)
    (S : Finset H) (hS : Subgroup.closure (S : Set H) = ⊤)
    (hcard : S.card ≤ l) :
    ∃ f : Fin l → R, paddedTupleClosure l f = H := by
  classical
  let e := Fintype.equivFin S
  have hcard' : Fintype.card S ≤ l := by simpa using hcard
  let f : Fin l → R := fun j =>
    if h : j.val < Fintype.card S then
      (((e.symm ⟨j.val, h⟩ : S) : H) : R)
    else 1
  refine ⟨f, le_antisymm ?_ ?_⟩
  · rw [paddedTupleClosure, Subgroup.closure_le]
    rintro x ⟨j, rfl⟩
    dsimp [f]
    split
    · exact (e.symm _ : S).1.2
    · exact H.one_mem
  · intro x hx
    let xH : H := ⟨x, hx⟩
    let K := paddedTupleClosure l f
    have hgenerators : (S : Set H) ⊆ K.comap H.subtype := by
      intro y hy
      let k := e ⟨y, hy⟩
      let j : Fin l := ⟨k.val, lt_of_lt_of_le k.isLt hcard'⟩
      apply Subgroup.subset_closure
      refine ⟨j, ?_⟩
      dsimp [f, j]
      rw [if_pos k.isLt]
      exact congrArg (fun z : S => (((z : H) : R)))
        (e.symm_apply_apply ⟨y, hy⟩)
    have htop : (⊤ : Subgroup H) ≤ K.comap H.subtype := by
      rw [← hS]
      exact (Subgroup.closure_le (K.comap H.subtype)).mpr hgenerators
    have hxK : xH ∈ K.comap H.subtype := htop (by trivial)
    exact hxK

/-- The tuple-closure map is onto all subgroups when the ambient order is
at most `2^l`. -/
theorem paddedTupleClosure_surjective (l : ℕ)
    [Finite R]
    (horder : Nat.card R ≤ 2 ^ l) :
    Function.Surjective (paddedTupleClosure (R := R) l) := by
  intro H
  obtain ⟨S, hS, hpow⟩ := exists_generating_finset_two_pow_le H
  have hsub : Nat.card H ≤ Nat.card R :=
    Nat.card_le_card_of_injective (Subtype.val : H → R) Subtype.val_injective
  have hcard : S.card ≤ l :=
    (Nat.pow_le_pow_iff_right (by decide : 1 < (2 : ℕ))).mp
      (hpow.trans (hsub.trans horder))
  exact exists_paddedTupleClosure_eq l H S hS hcard

/-- A finite group of order at most `2^l` has at most `2^(l^2)` subgroups. -/
theorem subgroup_card_le_two_pow_sq (l : ℕ)
    [Finite R]
    (horder : Nat.card R ≤ 2 ^ l) :
    Nat.card (Subgroup R) ≤ 2 ^ (l * l) := by
  have hsurj := paddedTupleClosure_surjective (R := R) l horder
  calc
    Nat.card (Subgroup R) ≤ Nat.card (Fin l → R) :=
      Nat.card_le_card_of_surjective _ hsurj
    _ = Nat.card R ^ l := by rw [Nat.card_fun, Nat.card_fin]
    _ ≤ (2 ^ l) ^ l := Nat.pow_le_pow_left horder l
    _ = 2 ^ (l * l) := by rw [pow_mul]

/-- The same bound for the literal normal axes used in complete quotient
counts. -/
theorem normalSubgroup_card_le_two_pow_sq (l : ℕ)
    [Finite R]
    (horder : Nat.card R ≤ 2 ^ l) :
    Nat.card {N : Subgroup R // N.Normal} ≤ 2 ^ (l * l) := by
  exact (Nat.card_le_card_of_injective Subtype.val Subtype.val_injective).trans
    (subgroup_card_le_two_pow_sq l horder)

end SymmetricSubgroupAsymptotics

end
