import SymmetricSubgroupAsymptotics.SchreierKernelGenerators
import Mathlib.Tactic.NormNum

/-! The complete original index-two subgroup is generated by two checked
Schreier words per original generator. True bits mean membership in the
actual subgroup. No source or child cardinality is assumed. -/
set_option autoImplicit false
noncomputable section
namespace SymmetricSubgroupAsymptotics
variable {G ι : Type*} [Group G]

def indexTwoCharacter (K : Subgroup G) (hi : K.index=2) : G →* Multiplicative (ZMod 2) := by
  classical
  exact {
  toFun g := Multiplicative.ofAdd (if g∈K then 0 else 1)
  map_one' := by simp
  map_mul' a b := by
    change (if a*b∈K then 0 else 1 : ZMod 2) =
      (if a∈K then 0 else 1)+(if b∈K then 0 else 1)
    have hm := K.mul_mem_iff_of_index_two hi (a := a) (b := b)
    have htwo : (1+1 : ZMod 2)=0 := by decide
    by_cases ha : a∈K <;> by_cases hb : b∈K <;> simp_all }

@[simp] theorem indexTwoCharacter_ker (K : Subgroup G) (hi : K.index=2) :
    (indexTwoCharacter K hi).ker = K := by
  classical
  ext g
  change (if g∈K then 0 else 1 : ZMod 2)=0 ↔ g∈K
  by_cases h : g∈K <;> simp [h]

def binarySchreierWords (g : ι → G) (bits : ι → Bool) (x : G) : Bool × ι → G :=
  fun bj => (if bj.1 then 1 else x)*g bj.2*(if bj.1 == bits bj.2 then 1 else x)⁻¹

theorem indexTwo_schreier_generated (g : ι → G)
    (hg : Subgroup.closure (Set.range g)=⊤)
    (K : Subgroup G) (hi : K.index=2) (bits : ι → Bool)
    (hbits : ∀j,bits j=true ↔ g j∈K) (x : G) (hx : x∉K) :
    K=Subgroup.closure (Set.range (binarySchreierWords g bits x)) := by
  classical
  let χ := indexTwoCharacter K hi
  let r : Multiplicative (ZMod 2) → G := fun q => if q.toAdd=0 then 1 else x
  have htwo (q : Multiplicative (ZMod 2)) :
      q=Multiplicative.ofAdd 0 ∨ q=Multiplicative.ofAdd 1 := by
    have h : ∀ q : Multiplicative (ZMod 2),
        q=Multiplicative.ofAdd 0 ∨ q=Multiplicative.ofAdd 1 := by
      intro q
      have h : q.toAdd=0 ∨ q.toAdd=1 := by
        exact (show ∀ a : ZMod 2, a=0 ∨ a=1 from by decide) q.toAdd
      exact h
    exact h q
  have hr : ∀q,χ (r q)=q := by
    intro q
    rcases htwo q with rfl|rfl <;> simp [χ,r,indexTwoCharacter,hx]
  have hr1 : r 1=1 := by simp [r]
  have hword (b : Bool) (j : ι) :
      schreierWords g χ r (Multiplicative.ofAdd (if b then 0 else 1),j)=
        binarySchreierWords g bits x (b,j) := by
    have hb := hbits j
    have hd : (Multiplicative.ofAdd (1 : ZMod 2))*Multiplicative.ofAdd 1=1 := by
      change (1+1 : ZMod 2)=0
      decide
    cases b <;> cases hj : bits j <;>
      simp_all [schreierWords,binarySchreierWords,χ,r,indexTwoCharacter,hd]
  have he : Set.range (schreierWords g χ r) = Set.range (binarySchreierWords g bits x) := by
    ext y
    constructor
    · rintro ⟨⟨q,j⟩,rfl⟩
      rcases htwo q with rfl|rfl
      · exact ⟨(true,j),(hword true j).symm⟩
      · exact ⟨(false,j),(hword false j).symm⟩
    · rintro ⟨⟨b,j⟩,rfl⟩
      exact ⟨(Multiplicative.ofAdd (if b then 0 else 1),j),hword b j⟩
  have h := schreier_kernel_generated g hg χ r hr hr1
  simpa only [χ,indexTwoCharacter_ker,he] using h


/-- The same original generators, regarded in their literal generated group. -/
def originalGeneratedGenerators (g : ι → G) :
    ι → Subgroup.closure (Set.range g) :=
  fun i => ⟨g i,Subgroup.subset_closure ⟨i,rfl⟩⟩

theorem originalGeneratedGenerators_generate (g : ι → G) :
    Subgroup.closure (Set.range (originalGeneratedGenerators g))=⊤ := by
  let U := Subgroup.closure (Set.range g)
  apply Subgroup.map_injective U.subtype_injective
  rw [MonoidHom.map_closure,← Set.range_comp]
  have he : U.subtype ∘ originalGeneratedGenerators g = g := rfl
  rw [he]
  simp only [← MonoidHom.range_eq_map,Subgroup.range_subtype]
  rfl

/-- Every relative-index-two subgroup of the original generated group is
exactly the closure of the two original Schreier words per generator. -/
theorem relative_indexTwo_schreier_generated (g : ι → G)
    (K : Subgroup G) (hK : K≤Subgroup.closure (Set.range g))
    (hi : K.relIndex (Subgroup.closure (Set.range g))=2)
    (bits : ι → Bool) (hbits : ∀j,bits j=true ↔ g j∈K)
    (x : G) (hxU : x∈Subgroup.closure (Set.range g)) (hx : x∉K) :
    K=Subgroup.closure (Set.range (binarySchreierWords g bits x)) := by
  let U := Subgroup.closure (Set.range g)
  have h := indexTwo_schreier_generated (originalGeneratedGenerators g)
    (originalGeneratedGenerators_generate g) (K.subgroupOf U) hi bits hbits (⟨x,hxU⟩:U) hx
  have hm := congrArg (Subgroup.map U.subtype) h
  rw [Subgroup.map_subgroupOf_eq_of_le hK,MonoidHom.map_closure,← Set.range_comp] at hm
  have he : U.subtype ∘ binarySchreierWords (originalGeneratedGenerators g) bits (⟨x,hxU⟩:U) =
      binarySchreierWords g bits x := by
    funext ⟨b,j⟩
    cases b <;> cases hj : bits j <;> simp [binarySchreierWords,hj,originalGeneratedGenerators]
  rwa [he] at hm

end SymmetricSubgroupAsymptotics
