import SymmetricSubgroupAsymptotics.MarkedC4WeightedEncoding
import SymmetricSubgroupAsymptotics.MarkedC4MomentGraphs
import Mathlib.GroupTheory.Solvable

/-!
# The marked one-generator reduction to soluble sources

Roney-Dougal--Tracey, Theorem 7 together with Theorem 8.4, says that every
finite group is generated by a soluble subgroup and at most one additional
element.  This file retains that literal subgroup and element.  The same code
is injective because their closure recovers the source, and the marked cost is
exactly `4^r` by restriction of characters.

Consequently the passage from all subgroups of `S_b` to soluble subgroups is
proved here, rather than included in a marked-moment hypothesis.
-/

set_option autoImplicit false
noncomputable section
open scoped BigOperators Classical

namespace SymmetricSubgroupAsymptotics
namespace MarkedC4

abbrev PermutationGroup (b : ℕ) := Equiv.Perm (Fin b)

/-- Soluble subgroups of the literal symmetric group. -/
abbrev SolublePermutationSubgroup (b : ℕ) :=
  {J : Subgroup (PermutationGroup b) // IsSolvable J}

/-- The marked moment restricted to soluble sources. -/
def solubleMarkedC4Moment (b r : ℕ) : ℝ :=
  ∑ J : SolublePermutationSubgroup b,
    (Nat.card (J.1 →* Multiplicative (ZMod 4)) : ℝ) ^ r

/-- Precomposition by a group equivalence is an equivalence of literal
homomorphism spaces. -/
def homPrecompEquiv {G H A : Type*} [Group G] [Group H] [Group A]
    (e : G ≃* H) : (H →* A) ≃ (G →* A) where
  toFun f := f.comp e.toMonoidHom
  invFun f := f.comp e.symm.toMonoidHom
  left_inv f := by
    ext x
    simp
  right_inv f := by
    ext x
    simp

/-- Literal one-generator witness supplied by RDT Theorem 7 / Theorem 8.4.
The ambient recovery equality is retained because it is what makes the
encoding of subgroups injective; `generates` is what bounds extensions of
the marked characters. -/
structure OneGeneratorSolubleWitness {b : ℕ}
    (J : Subgroup (PermutationGroup b)) where
  K : Subgroup J
  K_solvable : IsSolvable K
  x : J
  generates : Subgroup.closure (({x} : Set J) ∪ K) = ⊤
  recover : Subgroup.closure
    (({(x : PermutationGroup b)} : Set (PermutationGroup b)) ∪
      K.map J.subtype) = J

/-- Named published input: every finite group has the preceding literal
one-generator soluble witness.  This is the exact part of RDT used at the
last reduction step. -/
def RDTOneGeneratorSolubleInput : Prop :=
  ∀ b (J : Subgroup (PermutationGroup b)),
    Nonempty (OneGeneratorSolubleWitness J)

namespace OneGeneratorSolubleWitness

variable {b : ℕ} {J : Subgroup (PermutationGroup b)}
  (W : OneGeneratorSolubleWitness J)

def ambientCore : Subgroup (PermutationGroup b) :=
  W.K.map J.subtype

theorem ambientCore_solvable : IsSolvable W.ambientCore := by
  letI : IsSolvable W.K := W.K_solvable
  let e : W.K ≃* W.ambientCore :=
    W.K.equivMapOfInjective J.subtype J.subtype_injective
  exact solvable_of_solvable_injective
    (f := e.symm.toMonoidHom) e.symm.injective

theorem ambientCore_hom_card :
    Nat.card (W.ambientCore →* Multiplicative (ZMod 4)) =
      Nat.card (W.K →* Multiplicative (ZMod 4)) := by
  let e : W.K ≃* W.ambientCore :=
    W.K.equivMapOfInjective J.subtype J.subtype_injective
  exact Nat.card_congr (homPrecompEquiv e)

end OneGeneratorSolubleWitness

/-- The global marked moment is at most `b! 4^r` times the soluble marked
moment.  All multiplicity is visible: `b!` chooses the extra permutation and
`4^r` chooses its value under the `r` characters. -/
theorem markedC4Moment_le_factorial_mul_solubleMoment
    (hRDT : RDTOneGeneratorSolubleInput) (b r : ℕ) :
    Non2UnipotentPrefixFiniteMenu.markedC4Moment b r ≤
      (Nat.factorial b : ℝ) * (2 : ℝ) ^ (2 * r) *
        solubleMarkedC4Moment b r := by
  let W : ∀ J : Subgroup (PermutationGroup b),
      OneGeneratorSolubleWitness J :=
    fun J => Classical.choice (hRDT b J)
  let code : Subgroup (PermutationGroup b) →
      SolublePermutationSubgroup b × PermutationGroup b :=
    fun J => (⟨(W J).ambientCore, (W J).ambientCore_solvable⟩,
      ((W J).x : PermutationGroup b))
  have hcode : Function.Injective code := by
    intro J₁ J₂ h
    have hcore : (W J₁).ambientCore = (W J₂).ambientCore := by
      exact congrArg (fun z => z.1.1) h
    have hx : ((W J₁).x : PermutationGroup b) =
        ((W J₂).x : PermutationGroup b) := by
      exact congrArg Prod.snd h
    calc
      J₁ = Subgroup.closure
          (({((W J₁).x : PermutationGroup b)} : Set (PermutationGroup b)) ∪
            (W J₁).ambientCore) := (W J₁).recover.symm
      _ = Subgroup.closure
          (({((W J₂).x : PermutationGroup b)} : Set (PermutationGroup b)) ∪
            (W J₂).ambientCore) := by rw [hx, hcore]
      _ = J₂ := (W J₂).recover
  have hfibre : ∀ z : SolublePermutationSubgroup b × PermutationGroup b,
      Nat.card {J : Subgroup (PermutationGroup b) // code J = z} ≤ 1 := by
    intro z
    rw [Finite.card_le_one_iff_subsingleton]
    exact ⟨fun x y =>
      Subtype.ext (hcode (x.property.trans y.property.symm))⟩
  have hsum := sum_le_uniformFiber_mul_twoPow_mul_sum
    code
    (fun J : Subgroup (PermutationGroup b) =>
      (Nat.card (J →* Multiplicative (ZMod 4)) : ℝ) ^ r)
    (fun z : SolublePermutationSubgroup b × PermutationGroup b =>
      (Nat.card (z.1.1 →* Multiplicative (ZMod 4)) : ℝ) ^ r)
    1 (2 * r) (fun J => by
      have hmark := card_hom_cyclicFour_pow_le_real
        (W J).K ({(W J).x} : Finset J) (by
          simpa only [Finset.coe_singleton] using (W J).generates) r
      calc
        (Nat.card (J →* Multiplicative (ZMod 4)) : ℝ) ^ r ≤
            (Nat.card ((W J).K →* Multiplicative (ZMod 4)) : ℝ) ^ r *
              (2 : ℝ) ^ (2 * r * ({(W J).x} : Finset J).card) := hmark
        _ = (2 : ℝ) ^ (2 * r) *
            (Nat.card ((W J).ambientCore →*
              Multiplicative (ZMod 4)) : ℝ) ^ r := by
          rw [← (W J).ambientCore_hom_card]
          simp only [Finset.card_singleton, mul_one]
          ring
        _ = (2 : ℝ) ^ (2 * r) *
            (Nat.card ((code J).1.1 →*
              Multiplicative (ZMod 4)) : ℝ) ^ r := by
          rfl)
    (fun _ => by positivity) hfibre
  have hproduct :
      (∑ z : SolublePermutationSubgroup b × PermutationGroup b,
          (Nat.card (z.1.1 →* Multiplicative (ZMod 4)) : ℝ) ^ r) =
        (Nat.factorial b : ℝ) * solubleMarkedC4Moment b r := by
    rw [Fintype.sum_prod_type]
    unfold solubleMarkedC4Moment
    calc
      (∑ x : SolublePermutationSubgroup b,
          ∑ _y : PermutationGroup b,
            (Nat.card (x.1 →* Multiplicative (ZMod 4)) : ℝ) ^ r) =
          ∑ x : SolublePermutationSubgroup b,
            (Fintype.card (PermutationGroup b) : ℝ) *
              (Nat.card (x.1 →* Multiplicative (ZMod 4)) : ℝ) ^ r := by
        apply Finset.sum_congr rfl
        intro x hx
        simp
      _ = (Nat.factorial b : ℝ) *
          ∑ x : SolublePermutationSubgroup b,
            (Nat.card (x.1 →* Multiplicative (ZMod 4)) : ℝ) ^ r := by
        rw [← Finset.mul_sum]
        rw [show Fintype.card (PermutationGroup b) = Nat.factorial b by
          rw [Fintype.card_perm, Fintype.card_fin]]
  unfold Non2UnipotentPrefixFiniteMenu.markedC4Moment at hsum ⊢
  calc
    ∑ J : Subgroup (PermutationGroup b),
        (Nat.card (J →* Multiplicative (ZMod 4)) : ℝ) ^ r
        ≤ (1 : ℝ) * (2 : ℝ) ^ (2 * r) *
          ∑ z : SolublePermutationSubgroup b × PermutationGroup b,
            (Nat.card (z.1.1 →* Multiplicative (ZMod 4)) : ℝ) ^ r := by
      simpa only [Nat.cast_one] using hsum
    _ = (Nat.factorial b : ℝ) * (2 : ℝ) ^ (2 * r) *
          solubleMarkedC4Moment b r := by
      rw [one_mul, hproduct]
      ring

end MarkedC4
end SymmetricSubgroupAsymptotics

end
