import SymmetricSubgroupAsymptotics.MarkedC4Filtration
import Mathlib.GroupTheory.Nilpotent
import Mathlib.Order.Atoms.Finite

/-!
# Generator numbers and normal generator numbers

`d_G(N)` (`normalGen N`) is the least size of a subset of the normal subgroup
`N` whose normal closure is `N`; `d(G)` (`genRank G`) is the least size of a
generating set.  This file proves the bookkeeping used by the joint `C4`
tableau and the peeling argument:

* normal generation is subadditive along a normal chain whose layers are
  normally generated modulo the previous term;
* a layer mapping onto a normal subgroup `U` of a quotient with kernel the
  previous term needs only `d(U)` lifted generators;
* `d(G) ≤ d(K) + d(G/K)`;
* for finite `2`-groups, `d(G) ≤ d_G(G) ≤ col₀(G^ab)`, and an abelian
  `2`-group is generated by `col₀` elements.
-/

set_option autoImplicit false
noncomputable section
open scoped Classical commutatorElement

namespace SymmetricSubgroupAsymptotics
namespace MarkedC4

universe u

/-! ## Definitions -/

/-- The normal generator number `d_G(N)`. -/
def normalGen {G : Type*} [Group G] (N : Subgroup G) : ℕ :=
  sInf {k | ∃ s : Finset G, s.card = k ∧ (s : Set G) ⊆ N ∧
    Subgroup.normalClosure (s : Set G) = N}

/-- The generator number `d(G)`. -/
def genRank (G : Type*) [Group G] : ℕ :=
  sInf {k | ∃ s : Finset G, s.card = k ∧ Subgroup.closure (s : Set G) = ⊤}

section Basic

variable {G : Type*} [Group G]

theorem normalGen_le {N : Subgroup G} {s : Finset G} (hs : (s : Set G) ⊆ N)
    (h : Subgroup.normalClosure (s : Set G) = N) : normalGen N ≤ s.card :=
  Nat.sInf_le ⟨s, rfl, hs, h⟩

theorem normalGen_spec [Finite G] (N : Subgroup G) [N.Normal] :
    ∃ s : Finset G, s.card = normalGen N ∧ (s : Set G) ⊆ N ∧
      Subgroup.normalClosure (s : Set G) = N := by
  have hne : {k | ∃ s : Finset G, s.card = k ∧ (s : Set G) ⊆ N ∧
      Subgroup.normalClosure (s : Set G) = N}.Nonempty := by
    letI := Fintype.ofFinite G
    refine ⟨_, Finset.univ.filter (· ∈ N), rfl, ?_, ?_⟩
    · intro x hx
      simpa using hx
    · have : ((Finset.univ.filter (· ∈ N) : Finset G) : Set G) = N := by
        ext x
        simp
      rw [this]
      exact Subgroup.normalClosure_eq_self N
  exact Nat.sInf_mem hne

theorem genRank_le {s : Finset G} (h : Subgroup.closure (s : Set G) = ⊤) :
    genRank G ≤ s.card :=
  Nat.sInf_le ⟨s, rfl, h⟩

theorem genRank_spec [Finite G] :
    ∃ s : Finset G, s.card = genRank G ∧ Subgroup.closure (s : Set G) = ⊤ := by
  have hne : {k | ∃ s : Finset G, s.card = k ∧ Subgroup.closure (s : Set G) = ⊤}.Nonempty := by
    obtain ⟨s, hs, -⟩ := exists_generating_finset_card_le G
    exact ⟨_, s, rfl, hs⟩
  exact Nat.sInf_mem hne

theorem normalGen_bot : normalGen (⊥ : Subgroup G) = 0 := by
  apply Nat.eq_zero_of_le_zero
  have := normalGen_le (N := (⊥ : Subgroup G)) (s := ∅) (by simp) (by simp)
  simpa using this

/-- Normal generators of the image under an onto map. -/
theorem normalGen_map_le {H : Type*} [Group H] [Finite G] (f : G →* H)
    (hf : Function.Surjective f) (N : Subgroup G) [N.Normal] :
    normalGen (N.map f) ≤ normalGen N := by
  obtain ⟨s, hcard, hsN, hcl⟩ := normalGen_spec N
  rw [← hcard]
  refine le_trans (normalGen_le (s := s.image f) ?_ ?_) Finset.card_image_le
  · rw [Finset.coe_image]
    exact Set.image_mono hsN |>.trans (fun x ⟨y, hy, hyx⟩ => ⟨y, hy, hyx⟩)
  · rw [Finset.coe_image, ← Subgroup.map_normalClosure _ f hf, hcl]

end Basic

/-! ## Chains -/

section Chain

variable {A : Type*} [Group A] [Finite A]

/-- **Normal generation along a chain.** -/
theorem normalGen_le_sum_of_chain (H : Subgroup A) [H.Normal] (t : ℕ) (C : ℕ → Subgroup A)
    (h0 : C 0 = ⊥) (ht : C t = H) (S : ℕ → Finset A)
    (hS : ∀ m < t, (S m : Set A) ⊆ C (m + 1))
    (hstep : ∀ m < t, C (m + 1) ≤ Subgroup.normalClosure (S m : Set A) ⊔ C m)
    (hCH : ∀ m ≤ t, C m ≤ H) :
    normalGen H ≤ ∑ m ∈ Finset.range t, (S m).card := by
  let T : Finset A := (Finset.range t).biUnion S
  have hT : (T : Set A) ⊆ H := by
    intro x hx
    simp only [T, Finset.coe_biUnion, Finset.coe_range, Set.mem_iUnion, Set.mem_Iio] at hx
    obtain ⟨m, hm, hx⟩ := hx
    exact hCH (m + 1) (by omega) (hS m hm hx)
  have hcl : Subgroup.normalClosure (T : Set A) = H := by
    apply le_antisymm
    · exact Subgroup.normalClosure_le_normal hT
    · have : ∀ m ≤ t, C m ≤ Subgroup.normalClosure (T : Set A) := by
        intro m
        induction m with
        | zero => intro _; rw [h0]; exact bot_le
        | succ m ih =>
          intro hm
          refine le_trans (hstep m (by omega)) (sup_le ?_ (ih (by omega)))
          apply Subgroup.normalClosure_mono
          intro x hx
          simp only [T, Finset.coe_biUnion, Finset.coe_range, Set.mem_iUnion, Set.mem_Iio]
          exact ⟨m, by omega, hx⟩
      rw [← ht]
      exact this t le_rfl
  calc normalGen H ≤ T.card := normalGen_le hT hcl
    _ ≤ ∑ m ∈ Finset.range t, (S m).card := Finset.card_biUnion_le

/-- **Lifting a layer.**  If `π : A → Q` is onto, `C ≤ C'` are normal, the
kernel of `π` on `C'` lies in `C`, and `U = π(C')` is the normal closure of
`s`, then `C'` is the normal closure of at most `|s|` lifted elements modulo
`C`. -/
theorem exists_layer_lift {Q : Type*} [Group Q] (π : A →* Q) (hπ : Function.Surjective π)
    (C C' : Subgroup A) [C'.Normal] (hker : ∀ x ∈ C', π x = 1 → x ∈ C)
    (s : Finset Q) (hsU : (s : Set Q) ⊆ C'.map π)
    (hcl : Subgroup.normalClosure (s : Set Q) = C'.map π) :
    ∃ t : Finset A, t.card ≤ s.card ∧ (t : Set A) ⊆ C' ∧
      C' ≤ Subgroup.normalClosure (t : Set A) ⊔ C := by
  have hlift : ∀ q ∈ s, ∃ a ∈ C', π a = q := fun q hq => hsU hq
  let lift : Q → A := fun q => if h : q ∈ s then Classical.choose (hlift q h) else 1
  have hliftC : ∀ q ∈ s, lift q ∈ C' ∧ π (lift q) = q := by
    intro q hq
    simp only [lift, dif_pos hq]
    exact Classical.choose_spec (hlift q hq)
  refine ⟨s.image lift, Finset.card_image_le, ?_, ?_⟩
  · intro x hx
    simp only [Finset.coe_image, Set.mem_image] at hx
    obtain ⟨q, hq, rfl⟩ := hx
    exact (hliftC q hq).1
  · intro x hx
    have hxU : π x ∈ C'.map π := ⟨x, hx, rfl⟩
    rw [← hcl] at hxU
    have himg : (s : Set Q) = π '' ((s.image lift : Finset A) : Set A) := by
      ext q
      simp only [Finset.coe_image, Set.mem_image]
      constructor
      · intro hq
        exact ⟨lift q, ⟨q, hq, rfl⟩, (hliftC q hq).2⟩
      · rintro ⟨_, ⟨q, hq, rfl⟩, rfl⟩
        rw [(hliftC q hq).2]
        exact hq
    rw [himg, ← Subgroup.map_normalClosure _ π hπ] at hxU
    obtain ⟨y, hy, hyx⟩ := hxU
    have hyC' : y ∈ C' := by
      have hle : Subgroup.normalClosure ((s.image lift : Finset A) : Set A) ≤ C' :=
        Subgroup.normalClosure_le_normal (fun z hz => by
          simp only [Finset.coe_image, Set.mem_image] at hz
          obtain ⟨q, hq, rfl⟩ := hz
          exact (hliftC q hq).1)
      exact hle hy
    have hmem : y⁻¹ * x ∈ C := by
      apply hker _ (C'.mul_mem (C'.inv_mem hyC') hx)
      rw [map_mul, map_inv, hyx, inv_mul_cancel]
    have : x = y * (y⁻¹ * x) := by group
    rw [this]
    exact Subgroup.mul_mem _ (Subgroup.mem_sup_left hy) (Subgroup.mem_sup_right hmem)

end Chain

/-! ## Ranks -/

section Rank

variable {G : Type*} [Group G] [Finite G]

/-- `d(G) ≤ d(K) + d(G/K)`. -/
theorem genRank_le_of_normal (K : Subgroup G) [K.Normal] :
    genRank G ≤ genRank K + genRank (G ⧸ K) := by
  obtain ⟨s, hs, hscl⟩ := genRank_spec (G := K)
  obtain ⟨t, ht, htcl⟩ := genRank_spec (G := G ⧸ K)
  let lift : G ⧸ K → G := fun q => Quotient.out q
  let T : Finset G := s.image (K.subtype) ∪ t.image lift
  have hT : Subgroup.closure (T : Set G) = ⊤ := by
    rw [eq_top_iff]
    intro x _
    set H := Subgroup.closure (T : Set G)
    -- `K ≤ H`
    have hK : K ≤ H := by
      intro k hk
      have hk' : (⟨k, hk⟩ : K) ∈ Subgroup.closure (s : Set K) := by rw [hscl]; trivial
      have := Subgroup.mem_map_of_mem K.subtype hk'
      rw [MonoidHom.map_closure] at this
      refine (Subgroup.closure_mono ?_) this
      intro y hy
      simp only [T, Finset.coe_union, Finset.coe_image]
      exact Or.inl hy
    -- the image of `H` is everything
    have hmap : H.map (QuotientGroup.mk' K) = ⊤ := by
      rw [eq_top_iff, ← htcl, Subgroup.closure_le]
      intro q hq
      refine ⟨lift q, Subgroup.subset_closure ?_, QuotientGroup.out_eq' q⟩
      simp only [T, Finset.coe_union, Finset.coe_image]
      exact Or.inr ⟨q, hq, rfl⟩
    obtain ⟨h, hh, hhx⟩ : (x : G ⧸ K) ∈ H.map (QuotientGroup.mk' K) := by rw [hmap]; trivial
    have : h⁻¹ * x ∈ K := by
      rw [← QuotientGroup.eq]
      exact hhx
    have hx : x = h * (h⁻¹ * x) := by group
    rw [hx]
    exact H.mul_mem hh (hK this)
  calc genRank G ≤ T.card := genRank_le hT
    _ ≤ (s.image K.subtype).card + (t.image lift).card := Finset.card_union_le _ _
    _ ≤ s.card + t.card := Nat.add_le_add Finset.card_image_le Finset.card_image_le
    _ = genRank K + genRank (G ⧸ K) := by rw [hs, ht]

/-- For nilpotent groups `d(G) ≤ d_G(G)`: a proper subgroup lies in a normal
maximal subgroup. -/
theorem genRank_le_normalGen_top [Group.IsNilpotent G] : genRank G ≤ normalGen (⊤ : Subgroup G) := by
  obtain ⟨s, hs, -, hcl⟩ := normalGen_spec (⊤ : Subgroup G)
  rw [← hs]
  apply genRank_le
  rcases IsCoatomic.eq_top_or_exists_le_coatom (α := Subgroup G) (Subgroup.closure (s : Set G))
    with h | ⟨M, hM, hle⟩
  · exact h
  · exfalso
    have hMn : M.Normal :=
      Subgroup.NormalizerCondition.normal_of_coatom (H := M) Group.normalizerCondition_of_isNilpotent hM
    have hle' : Subgroup.normalClosure (s : Set G) ≤ M :=
      Subgroup.normalClosure_le_normal (Subgroup.subset_closure.trans hle)
    rw [hcl] at hle'
    exact hM.1 (eq_top_iff.mpr hle')

/-- A maximal subgroup of a finite `2`-group is normal of index two: it
contains every square and every commutator. -/
theorem coatom_contains_squares_commutators (h2 : IsPGroup 2 G) {M : Subgroup G}
    (hM : IsCoatom M) : M.Normal ∧ (∀ g : G, g ^ 2 ∈ M) ∧ commutator G ≤ M := by
  haveI : Fact (Nat.Prime 2) := ⟨Nat.prime_two⟩
  haveI : Group.IsNilpotent G := h2.isNilpotent
  have hMn : M.Normal :=
    Subgroup.NormalizerCondition.normal_of_coatom (H := M) Group.normalizerCondition_of_isNilpotent hM
  have hX2 : IsPGroup 2 (G ⧸ M) := h2.to_quotient M
  have hnt : Nontrivial (G ⧸ M) := QuotientGroup.nontrivial_iff.mpr hM.1
  obtain ⟨k, hk⟩ := (IsPGroup.iff_card).mp hX2
  have hk0 : k ≠ 0 := by
    intro h0
    rw [h0, pow_zero] at hk
    exact (Finite.one_lt_card_iff_nontrivial.mpr hnt).ne' hk
  obtain ⟨x, hx⟩ := exists_prime_orderOf_dvd_card' (G := G ⧸ M) 2
    (by rw [hk]; exact dvd_pow_self 2 hk0)
  -- the preimage of `⟨x⟩` is everything
  have hall : ∀ y : G ⧸ M, y ∈ Subgroup.zpowers x := by
    have hlt : M < (Subgroup.zpowers x).comap (QuotientGroup.mk' M) := by
      refine lt_of_le_of_ne (fun g hg => ?_) ?_
      · show (g : G ⧸ M) ∈ Subgroup.zpowers x
        rw [(QuotientGroup.eq_one_iff g).mpr hg]
        exact Subgroup.one_mem _
      · intro heq
        obtain ⟨g, hg⟩ := QuotientGroup.mk_surjective x
        have hgm : g ∈ (Subgroup.zpowers x).comap (QuotientGroup.mk' M) := by
          show (g : G ⧸ M) ∈ Subgroup.zpowers x
          rw [hg]
          exact Subgroup.mem_zpowers x
        rw [← heq] at hgm
        have : x = 1 := by rw [← hg]; exact (QuotientGroup.eq_one_iff g).mpr hgm
        rw [this, orderOf_one] at hx
        exact absurd hx (by norm_num)
    have htop := hM.2 _ hlt
    intro y
    obtain ⟨g, rfl⟩ := QuotientGroup.mk_surjective y
    have : g ∈ (Subgroup.zpowers x).comap (QuotientGroup.mk' M) := by rw [htop]; trivial
    exact this
  refine ⟨hMn, fun g => ?_, ?_⟩
  · obtain ⟨n, hn⟩ := hall (g : G ⧸ M)
    rw [← QuotientGroup.eq_one_iff, QuotientGroup.mk_pow, ← hn, ← zpow_natCast,
      ← zpow_mul, mul_comm, zpow_mul, zpow_natCast, ← hx, pow_orderOf_eq_one, one_zpow]
  · rw [commutator_def, Subgroup.commutator_le]
    intro a _ b _
    rw [← QuotientGroup.eq_one_iff]
    obtain ⟨i, hi⟩ := hall (a : G ⧸ M)
    obtain ⟨j, hj⟩ := hall (b : G ⧸ M)
    show (QuotientGroup.mk' M) ⁅a, b⁆ = 1
    rw [map_commutatorElement, commutatorElement_eq_one_iff_mul_comm,
      QuotientGroup.mk'_apply, QuotientGroup.mk'_apply]
    rw [show ((a : G ⧸ M)) = x ^ i from hi.symm, show ((b : G ⧸ M)) = x ^ j from hj.symm]
    exact (Commute.zpow_zpow_self x i j).eq

/-- A subgroup which together with a subgroup contained in every maximal
subgroup generates everything is everything. -/
theorem eq_top_of_sup_le_coatoms (H K : Subgroup G) (hK : ∀ M : Subgroup G, IsCoatom M → K ≤ M)
    (h : H ⊔ K = ⊤) : H = ⊤ := by
  rcases IsCoatomic.eq_top_or_exists_le_coatom (α := Subgroup G) H with h' | ⟨M, hM, hle⟩
  · exact h'
  · exfalso
    have : H ⊔ K ≤ M := sup_le hle (hK M hM)
    rw [h] at this
    exact hM.1 (eq_top_iff.mpr this)

/-- An abelian `2`-group is generated by `col₀` elements. -/
theorem genRank_le_col_zero {B : Type u} [CommGroup B] [Finite B] (h2 : IsPGroup 2 B) :
    genRank B ≤ col B 0 := by
  obtain ⟨S, hS, hcard⟩ := exists_generating_finset_card_le (B ⧸ sqs B)
  have hq : Nat.card (B ⧸ sqs B) = 2 ^ col B 0 := card_quotient_powSub_two B
  have hScard : S.card ≤ col B 0 := by
    rw [hq] at hcard
    exact (Nat.pow_le_pow_iff_right (by norm_num)).mp hcard
  let T : Finset B := S.image Quotient.out
  have hT : Subgroup.closure (T : Set B) = ⊤ := by
    apply eq_top_of_sup_le_coatoms _ (sqs B)
    · intro M hM
      rintro _ ⟨g, rfl⟩
      exact (coatom_contains_squares_commutators h2 hM).2.1 g
    · have hmap : (Subgroup.closure (T : Set B)).map (QuotientGroup.mk' (sqs B)) = ⊤ := by
        rw [MonoidHom.map_closure, eq_top_iff, ← hS, Subgroup.closure_le]
        intro q hq
        apply Subgroup.subset_closure
        refine ⟨Quotient.out q, ?_, QuotientGroup.out_eq' q⟩
        simp only [T, Finset.coe_image]
        exact ⟨q, hq, rfl⟩
      have := congrArg (Subgroup.comap (QuotientGroup.mk' (sqs B))) hmap
      rwa [Subgroup.comap_map_eq, QuotientGroup.ker_mk', Subgroup.comap_top] at this
  calc genRank B ≤ T.card := genRank_le hT
    _ ≤ S.card := Finset.card_image_le
    _ ≤ col B 0 := hScard

/-- A finite `2`-group is generated by `col₀(G^ab)` elements. -/
theorem genRank_le_col_abelianization (h2 : IsPGroup 2 G) :
    genRank G ≤ col (Abelianization G) 0 := by
  have hE : IsPGroup 2 (Abelianization G) := h2.to_quotient _
  obtain ⟨S, hS, hScl⟩ := genRank_spec (G := Abelianization G)
  have hSle := genRank_le_col_zero hE
  let T : Finset G := S.image Quotient.out
  have hT : Subgroup.closure (T : Set G) = ⊤ := by
    apply eq_top_of_sup_le_coatoms _ (commutator G)
    · intro M hM
      exact (coatom_contains_squares_commutators h2 hM).2.2
    · have hmap : (Subgroup.closure (T : Set G)).map (Abelianization.of) = ⊤ := by
        rw [MonoidHom.map_closure, eq_top_iff, ← hScl, Subgroup.closure_le]
        intro q hq
        apply Subgroup.subset_closure
        refine ⟨Quotient.out q, ?_, QuotientGroup.out_eq' q⟩
        simp only [T, Finset.coe_image]
        exact ⟨q, hq, rfl⟩
      have := congrArg (Subgroup.comap (Abelianization.of (G := G))) hmap
      rwa [Subgroup.comap_map_eq, Abelianization.ker_of, Subgroup.comap_top] at this
  calc genRank G ≤ T.card := genRank_le hT
    _ ≤ S.card := Finset.card_image_le
    _ = genRank (Abelianization G) := hS
    _ ≤ col (Abelianization G) 0 := hSle

/-- The first column of a subgroup of an abelian group is at most that of
the group. -/
theorem col_zero_subgroup_le {A : Type u} [CommGroup A] [Finite A] (B : Subgroup A) :
    col B 0 ≤ col A 0 := by
  have h : Nat.card (tors2 B) ≤ Nat.card (tors2 A) := by
    refine Nat.card_le_card_of_injective
      (fun x : tors2 B => (⟨((x : B) : A), by
        have := x.2
        rw [mem_tors2] at this ⊢
        exact congrArg Subtype.val this⟩ : tors2 A)) ?_
    intro x y hxy
    apply Subtype.ext
    apply Subtype.ext
    exact congrArg (fun z : tors2 A => (z : A)) hxy
  rw [card_tors2, card_tors2] at h
  exact (Nat.pow_le_pow_iff_right (by norm_num)).mp h

end Rank

end MarkedC4
end SymmetricSubgroupAsymptotics
