import SymmetricSubgroupAsymptotics.MarkedC4AbelianColumns
import Mathlib.Data.Real.Basic

/-!
# Extending marked characters across relative generators

If a finite group `G` is generated by a subgroup `K` and `l` further
elements, a homomorphism from `G` is determined by its restriction to `K`
and its values on those `l` elements.  For the cyclic target of order four
this costs at most `4^l` per mark.  This is the elementary marked version of
the generation step used in the Roney-Dougal--Tracey reductions.
-/

set_option autoImplicit false
noncomputable section
open scoped Classical

namespace SymmetricSubgroupAsymptotics
namespace MarkedC4

/-- Restrict a homomorphism to a subgroup. -/
def restrictHom {G H : Type*} [Group G] [Group H] (K : Subgroup G) :
    (G →* H) → (K →* H) := fun f => f.comp K.subtype

/-- A homomorphism is determined by its restriction to `K` and its values on
any finite set which generates `G` together with `K`. -/
theorem restrictHom_values_injective {G H : Type*} [Group G] [Group H]
    (K : Subgroup G) (S : Finset G)
    (hgen : Subgroup.closure ((S : Set G) ∪ K) = ⊤) :
    Function.Injective
      (fun f : G →* H => (restrictHom K f, fun s : S => f s)) := by
  intro f g hfg
  apply MonoidHom.eq_of_eqOn_dense hgen
  intro x hx
  rcases hx with hxS | hxK
  · have hv := congrArg Prod.snd hfg
    exact congrFun hv ⟨x, hxS⟩
  · have hr := congrArg Prod.fst hfg
    have hv := congrArg (fun q : K →* H => q ⟨x, hxK⟩) hr
    exact hv

/-- The relative-generator cardinal bound for homomorphisms to a finite
target. -/
theorem card_hom_le_card_restriction_mul_pow {G H : Type*} [Group G] [Group H]
    [Finite G] [Finite H] (K : Subgroup G) (S : Finset G)
    (hgen : Subgroup.closure ((S : Set G) ∪ K) = ⊤) :
    Nat.card (G →* H) ≤ Nat.card (K →* H) * Nat.card H ^ S.card := by
  letI : Finite (K →* H) :=
    Finite.of_injective (fun f : K →* H => (f : K → H)) DFunLike.coe_injective
  calc
    Nat.card (G →* H) ≤ Nat.card ((K →* H) × (S → H)) :=
      Nat.card_le_card_of_injective _ (restrictHom_values_injective K S hgen)
    _ = Nat.card (K →* H) * Nat.card H ^ S.card := by
      rw [Nat.card_prod, Nat.card_fun, Nat.card_eq_fintype_card (α := S),
        Fintype.card_coe]

/-- For a cyclic-four target, each relative generator has four possible
values. -/
theorem card_hom_cyclicFour_le_restriction_mul_four_pow {G : Type*} [Group G]
    [Finite G] (K : Subgroup G) (S : Finset G)
    (hgen : Subgroup.closure ((S : Set G) ∪ K) = ⊤) :
    Nat.card (G →* Multiplicative (ZMod 4)) ≤
      Nat.card (K →* Multiplicative (ZMod 4)) * 4 ^ S.card := by
  simpa using
    (card_hom_le_card_restriction_mul_pow
      (H := Multiplicative (ZMod 4)) K S hgen)

/-- The same bound after taking `r` independent marked characters. -/
theorem card_hom_cyclicFour_pow_le {G : Type*} [Group G] [Finite G]
    (K : Subgroup G) (S : Finset G)
    (hgen : Subgroup.closure ((S : Set G) ∪ K) = ⊤) (r : ℕ) :
    Nat.card (G →* Multiplicative (ZMod 4)) ^ r ≤
      Nat.card (K →* Multiplicative (ZMod 4)) ^ r * 4 ^ (r * S.card) := by
  calc
    Nat.card (G →* Multiplicative (ZMod 4)) ^ r ≤
        (Nat.card (K →* Multiplicative (ZMod 4)) * 4 ^ S.card) ^ r :=
      Nat.pow_le_pow_left
        (card_hom_cyclicFour_le_restriction_mul_four_pow K S hgen) r
    _ = Nat.card (K →* Multiplicative (ZMod 4)) ^ r * 4 ^ (r * S.card) := by
      rw [mul_pow, ← pow_mul]
      rw [Nat.mul_comm S.card r]

/-- Real-valued form used by the global moment sum. -/
theorem card_hom_cyclicFour_pow_le_real {G : Type*} [Group G] [Finite G]
    (K : Subgroup G) (S : Finset G)
    (hgen : Subgroup.closure ((S : Set G) ∪ K) = ⊤) (r : ℕ) :
    (Nat.card (G →* Multiplicative (ZMod 4)) : ℝ) ^ r ≤
      (Nat.card (K →* Multiplicative (ZMod 4)) : ℝ) ^ r *
        (2 : ℝ) ^ (2 * r * S.card) := by
  have h : (Nat.card (G →* Multiplicative (ZMod 4)) : ℝ) ^ r ≤
      (Nat.card (K →* Multiplicative (ZMod 4)) : ℝ) ^ r *
        (4 : ℝ) ^ (r * S.card) := by
    exact_mod_cast card_hom_cyclicFour_pow_le K S hgen r
  calc
    _ ≤ _ := h
    _ = _ := by
      have hexp : (2 * r * S.card : ℕ) = 2 * (r * S.card) :=
        Nat.mul_assoc 2 r S.card
      have hpow : (2 : ℝ) ^ (2 * (r * S.card)) = (4 : ℝ) ^ (r * S.card) := by
        rw [pow_mul]
        norm_num
      rw [hexp, hpow]

end MarkedC4
end SymmetricSubgroupAsymptotics
