import SymmetricSubgroupAsymptotics.MarkedC4PsiAnalysis

/-!
# Binary columns of an abelianization along a normal filtration

Let `1 = L₀ ≤ L₁ ≤ ⋯ ≤ L_t = L` be normal subgroups of a finite group and
suppose each `L_{m+1}` is the normal closure of a set `S_m` of size `d_m`
modulo `L_m`.  Then the abelianization `E = L^ab` satisfies

* `col₀ E ≤ ∑ d_m`,
* `col₀ E + col₁ E ≤ ∑ log₂ min(4^{d_m}, |L_{m+1} : L_m|)`.

These are the two simultaneous column capacities of the joint `C4` tableau
estimate.  The proof works in `E / E^k` for `k = 2, 4`: every layer of the
image filtration is generated by `d_m` elements of exponent dividing `k`,
and is a quotient of the original layer.
-/

set_option autoImplicit false
noncomputable section
open scoped Classical

namespace SymmetricSubgroupAsymptotics
namespace MarkedC4

universe u

/-! ## Powers and small closures -/

/-- The subgroup of `k`-th powers. -/
def powSub (E : Type*) [CommGroup E] (k : ℕ) : Subgroup E := (powMonoidHom k : E →* E).range

theorem mem_powSub {E : Type*} [CommGroup E] (k : ℕ) (x : E) :
    x ∈ powSub E k ↔ ∃ y : E, y ^ k = x := Iff.rfl

/-- In a commutative group, a set of elements of exponent dividing `k`
generates at most `k^|S|` elements. -/
theorem card_closure_le_pow {E : Type*} [CommGroup E] [Finite E] (k : ℕ) (hk : 0 < k)
    (S : Finset E) (hS : ∀ s ∈ S, s ^ k = 1) :
    Nat.card (Subgroup.closure (S : Set E)) ≤ k ^ S.card := by
  -- products of powers with exponents below `k`
  let f : (S → Fin k) → E := fun e => ∏ s : S, (s : E) ^ (e s : ℕ)
  let M : Subgroup E :=
    { carrier := Set.range f
      one_mem' := ⟨fun _ => ⟨0, hk⟩, by simp [f]⟩
      mul_mem' := by
        rintro _ _ ⟨e₁, rfl⟩ ⟨e₂, rfl⟩
        refine ⟨fun s => ⟨((e₁ s : ℕ) + e₂ s) % k, Nat.mod_lt _ hk⟩, ?_⟩
        simp only [f, ← Finset.prod_mul_distrib]
        apply Finset.prod_congr rfl
        intro s _
        rw [← pow_add]
        conv_rhs => rw [← Nat.mod_add_div ((e₁ s : ℕ) + e₂ s) k]
        rw [pow_add, pow_mul, hS s s.2, one_pow, mul_one]
      inv_mem' := by
        rintro _ ⟨e, rfl⟩
        refine ⟨fun s => ⟨(k - e s) % k, Nat.mod_lt _ hk⟩, ?_⟩
        simp only [f, ← Finset.prod_inv_distrib]
        apply Finset.prod_congr rfl
        intro s _
        rw [eq_inv_iff_mul_eq_one, ← pow_add]
        have hlt := (e s).2
        have h1 : (k - (e s : ℕ)) % k + (e s : ℕ) = k * (((k - (e s : ℕ)) % k + e s) / k) := by
          rcases Nat.eq_zero_or_pos (e s : ℕ) with h0 | hpos
          · rw [h0, Nat.sub_zero, Nat.mod_self, zero_add, Nat.zero_div, mul_zero]
          · rw [Nat.mod_eq_of_lt (by omega), Nat.sub_add_cancel hlt.le, Nat.div_self hk,
              mul_one]
        rw [h1, pow_mul, hS s s.2, one_pow] }
  have hle : Subgroup.closure (S : Set E) ≤ M := by
    rw [Subgroup.closure_le]
    intro s hs
    refine ⟨fun x => if (x : E) = s then ⟨1 % k, Nat.mod_lt _ hk⟩ else ⟨0, hk⟩, ?_⟩
    simp only [f]
    rw [Finset.prod_eq_single ⟨s, hs⟩]
    · simp only [if_true]
      rcases Nat.lt_or_ge 1 k with h1 | h1
      · rw [Nat.mod_eq_of_lt h1, pow_one]
      · have : k = 1 := by omega
        subst this
        have := hS s hs
        rw [pow_one] at this
        simp [this]
    · intro x _ hx
      rw [if_neg (fun h => hx (Subtype.ext h))]
      simp
    · simp
  calc Nat.card (Subgroup.closure (S : Set E)) ≤ Nat.card M := Subgroup.card_le_of_le hle
    _ ≤ Nat.card (S → Fin k) := by
        change Nat.card (Set.range f) ≤ _
        exact Nat.card_le_card_of_surjective (fun e => (⟨f e, e, rfl⟩ : Set.range f))
          (fun ⟨_, e, he⟩ => ⟨e, Subtype.ext he⟩)
    _ = k ^ S.card := by rw [Nat.card_fun, Nat.card_fin, Nat.card_eq_fintype_card,
          Fintype.card_coe]

/-- `|A ⊔ B| ≤ |A| |B|` in a finite commutative group. -/
theorem card_sup_le {G : Type*} [CommGroup G] [Finite G] (A B : Subgroup G) :
    Nat.card (A ⊔ B : Subgroup G) ≤ Nat.card A * Nat.card B := by
  have h := card_sup_mul_card_inf A B
  have hpos : 0 < Nat.card (A ⊓ B : Subgroup G) := Nat.card_pos
  calc Nat.card (A ⊔ B : Subgroup G) ≤ Nat.card (A ⊔ B : Subgroup G) *
        Nat.card (A ⊓ B : Subgroup G) := Nat.le_mul_of_pos_right _ hpos
    _ = Nat.card A * Nat.card B := h

/-- The image of a subgroup in a quotient: `|X.map mk| |X ⊓ P| = |X|`. -/
theorem card_map_mk_mul_inf {G : Type*} [CommGroup G] [Finite G] (P X : Subgroup G) :
    Nat.card (X.map (QuotientGroup.mk' P)) * Nat.card (X ⊓ P : Subgroup G) = Nat.card X := by
  have h1 := card_map_mk_mul P (X ⊔ P) le_sup_right
  have hmap : (X ⊔ P).map (QuotientGroup.mk' P) = X.map (QuotientGroup.mk' P) := by
    rw [Subgroup.map_sup, QuotientGroup.map_mk'_self, sup_bot_eq]
  rw [hmap] at h1
  have h2 := card_sup_mul_card_inf X P
  have hpos : 0 < Nat.card P := Nat.card_pos
  apply Nat.eq_of_mul_eq_mul_right hpos
  calc Nat.card (X.map (QuotientGroup.mk' P)) * Nat.card (X ⊓ P : Subgroup G) * Nat.card P
      = (Nat.card (X.map (QuotientGroup.mk' P)) * Nat.card P) *
          Nat.card (X ⊓ P : Subgroup G) := by ring
    _ = Nat.card X * Nat.card P := by rw [h1, h2]

/-! ## Chains in a quotient by powers -/

/-- **Filtration bound.**  Let `C₀ = ⊥ ≤ C₁ ≤ ⋯ ≤ C_t = ⊤` in a finite
commutative group `E`, with `C_{m+1} ≤ ⟨S_m⟩ ⊔ C_m` and
`|C_{m+1}| ≤ u_m |C_m|`.  Then
`|E / E^k| ≤ ∏_{m<t} min(k^{|S_m|}, u_m)`. -/
theorem card_quotient_pow_le_of_chain {E : Type*} [CommGroup E] [Finite E] (k : ℕ) (hk : 0 < k)
    (t : ℕ) (C : ℕ → Subgroup E) (h0 : C 0 = ⊥) (ht : C t = ⊤)
    (hmono : ∀ m, C m ≤ C (m + 1)) (S : ℕ → Finset E) (u : ℕ → ℕ)
    (hstep : ∀ m < t, C (m + 1) ≤ Subgroup.closure (S m : Set E) ⊔ C m)
    (hu : ∀ m < t, Nat.card (C (m + 1)) ≤ u m * Nat.card (C m)) :
    Nat.card (E ⧸ powSub E k) ≤ ∏ m ∈ Finset.range t, min (k ^ (S m).card) (u m) := by
  set P := powSub E k
  let π : E →* E ⧸ P := QuotientGroup.mk' P
  let Cb : ℕ → Subgroup (E ⧸ P) := fun m => (C m).map π
  have hexp : ∀ z : E ⧸ P, z ^ k = 1 := by
    intro z
    obtain ⟨x, rfl⟩ := QuotientGroup.mk_surjective z
    rw [← QuotientGroup.mk_pow, QuotientGroup.eq_one_iff]
    exact ⟨x, rfl⟩
  have hstep' : ∀ m < t, Nat.card (Cb (m + 1)) ≤
      min (k ^ (S m).card) (u m) * Nat.card (Cb m) := by
    intro m hm
    -- the generator bound
    have ha : Nat.card (Cb (m + 1)) ≤ k ^ (S m).card * Nat.card (Cb m) := by
      have hle : Cb (m + 1) ≤ Subgroup.closure ((S m).image π : Set (E ⧸ P)) ⊔ Cb m := by
        have := Subgroup.map_mono (f := π) (hstep m hm)
        rw [Subgroup.map_sup, MonoidHom.map_closure] at this
        simpa [Cb, Finset.coe_image] using this
      calc Nat.card (Cb (m + 1))
          ≤ Nat.card (Subgroup.closure ((S m).image π : Set (E ⧸ P)) ⊔ Cb m :
              Subgroup (E ⧸ P)) := Subgroup.card_le_of_le hle
        _ ≤ Nat.card (Subgroup.closure ((S m).image π : Set (E ⧸ P))) * Nat.card (Cb m) :=
            card_sup_le _ _
        _ ≤ k ^ ((S m).image π).card * Nat.card (Cb m) :=
            Nat.mul_le_mul_right _ (card_closure_le_pow k hk _ (fun z _ => hexp z))
        _ ≤ k ^ (S m).card * Nat.card (Cb m) :=
            Nat.mul_le_mul_right _ (Nat.pow_le_pow_right hk Finset.card_image_le)
    -- the layer bound
    have hb : Nat.card (Cb (m + 1)) ≤ u m * Nat.card (Cb m) := by
      have e1 := card_map_mk_mul_inf P (C (m + 1))
      have e2 := card_map_mk_mul_inf P (C m)
      have hinf : Nat.card (C m ⊓ P : Subgroup E) ≤ Nat.card (C (m + 1) ⊓ P : Subgroup E) :=
        Subgroup.card_le_of_le (inf_le_inf_right _ (hmono m))
      have hpos : 0 < Nat.card (C (m + 1) ⊓ P : Subgroup E) := Nat.card_pos
      apply Nat.le_of_mul_le_mul_right _ hpos
      calc Nat.card (Cb (m + 1)) * Nat.card (C (m + 1) ⊓ P : Subgroup E)
          = Nat.card (C (m + 1)) := e1
        _ ≤ u m * Nat.card (C m) := hu m hm
        _ = u m * (Nat.card (Cb m) * Nat.card (C m ⊓ P : Subgroup E)) := by rw [e2]
        _ ≤ u m * (Nat.card (Cb m) * Nat.card (C (m + 1) ⊓ P : Subgroup E)) :=
            Nat.mul_le_mul_left _ (Nat.mul_le_mul_left _ hinf)
        _ = u m * Nat.card (Cb m) * Nat.card (C (m + 1) ⊓ P : Subgroup E) := by ring
    rcases le_total (k ^ (S m).card) (u m) with h | h
    · rw [min_eq_left h]
      exact ha
    · rw [min_eq_right h]
      exact hb
  have hind : ∀ m ≤ t, Nat.card (Cb m) ≤
      ∏ j ∈ Finset.range m, min (k ^ (S j).card) (u j) := by
    intro m
    induction m with
    | zero =>
      intro _
      simp only [Cb, h0, Subgroup.map_bot, Subgroup.card_bot, Finset.range_zero,
        Finset.prod_empty, le_refl]
    | succ m ih =>
      intro hm
      rw [Finset.prod_range_succ]
      calc Nat.card (Cb (m + 1)) ≤ min (k ^ (S m).card) (u m) * Nat.card (Cb m) :=
            hstep' m (by omega)
        _ ≤ min (k ^ (S m).card) (u m) *
              ∏ j ∈ Finset.range m, min (k ^ (S j).card) (u j) :=
            Nat.mul_le_mul_left _ (ih (by omega))
        _ = _ := mul_comm _ _
  have htop : Nat.card (Cb t) = Nat.card (E ⧸ P) := by
    simp only [Cb, ht, Subgroup.map_top_of_surjective π (QuotientGroup.mk'_surjective P),
      Subgroup.card_top]
  rw [← htop]
  exact hind t le_rfl

/-! ## Columns as quotient orders -/

theorem card_quotient_powSub_two (E : Type u) [CommGroup E] [Finite E] :
    Nat.card (E ⧸ powSub E 2) = 2 ^ col E 0 := by
  change Nat.card (E ⧸ sqs E) = _
  have h1 := card_eq_two_pow_col_mul E
  have h2 := Subgroup.card_eq_card_quotient_mul_card_subgroup (sqs E)
  have hpos : 0 < Nat.card (sqs E) := Nat.card_pos
  exact Nat.eq_of_mul_eq_mul_right hpos (h2.symm.trans h1)

theorem powSub_four_eq (E : Type u) [CommGroup E] :
    powSub E 4 = (sqs (sqs E)).map (sqs E).subtype := by
  ext x
  constructor
  · rintro ⟨y, rfl⟩
    refine ⟨⟨y ^ 2, y, rfl⟩ ^ 2, ⟨⟨y ^ 2, y, rfl⟩, rfl⟩, ?_⟩
    change (y ^ 2) ^ 2 = y ^ 4
    rw [← pow_mul]
  · rintro ⟨_, ⟨z, rfl⟩, rfl⟩
    obtain ⟨y, hy⟩ := z.2
    refine ⟨y, ?_⟩
    change y ^ 4 = ((z : E)) ^ 2
    rw [← hy]
    change y ^ 4 = (y ^ 2) ^ 2
    rw [← pow_mul]

theorem card_quotient_powSub_four (E : Type u) [CommGroup E] [Finite E] :
    Nat.card (E ⧸ powSub E 4) = 2 ^ (col E 0 + col E 1) := by
  have h1 := card_eq_two_pow_col_mul E
  have h2 := card_eq_two_pow_col_mul (sqs E)
  have h3 := Subgroup.card_eq_card_quotient_mul_card_subgroup (powSub E 4)
  have h4 : Nat.card (powSub E 4) = Nat.card (sqs (sqs E)) := by
    rw [powSub_four_eq]
    exact Nat.card_congr ((Subgroup.equivMapOfInjective _ _ Subtype.val_injective).symm.toEquiv)
  rw [h4] at h3
  rw [h2] at h1
  have hpos : 0 < Nat.card (sqs (sqs E)) := Nat.card_pos
  rw [col_succ, pow_add]
  apply Nat.eq_of_mul_eq_mul_right hpos
  rw [← h3, h1, mul_assoc]

end MarkedC4
end SymmetricSubgroupAsymptotics
