import SymmetricSubgroupAsymptotics.ChiefSeriesTransport
import Mathlib.GroupTheory.Perm.Closure
import Mathlib.GroupTheory.Perm.Fin

/-! Zero-weight chief chains for the original two-generator symmetric
actions. A full cycle and an adjacent swap generate the complete symmetric
group by the symbolic Mathlib theorem; no elements or subgroups are listed. -/
set_option autoImplicit false
noncomputable section
namespace SymmetricSubgroupAsymptotics

/-- The subgroup generated by the literal cycle and adjacent swap is
transported through its proved equality with the full symmetric group. -/
theorem cycleAdjacentSwapChiefSeries_zero (n:ℕ) (hn:5≤n)
    (σ:Equiv.Perm (Fin n)) (hcycle:σ.IsCycle)
    (hsupport:σ.support=Finset.univ) (x:Fin n) :
    ∃s:ActualChiefSeries
      (Subgroup.closure ({σ,Equiv.swap x (σ x)}:Set (Equiv.Perm (Fin n)))),
      actualChiefSeriesTernaryWeight s=0 := by
  let e := (MulEquiv.subgroupCongr
    (Equiv.Perm.closure_cycle_adjacent_swap hcycle hsupport x)).trans
      (Subgroup.topEquiv)
  exact symmetricChiefSeries_zero_of_equiv n hn e

/-- The canonical original generators used by the natural symmetric
rows: rotation by one and the transposition of the first two points. -/
theorem naturalSymmetricChiefSeries_zero (n:ℕ) :
    ∃s:ActualChiefSeries
      (Subgroup.closure ({finRotate (n+5),Equiv.swap 0 1}:
        Set (Equiv.Perm (Fin (n+5))))),actualChiefSeriesTernaryWeight s=0 := by
  simpa only [finRotate_apply_zero] using
    cycleAdjacentSwapChiefSeries_zero (n+5) (by omega) (finRotate (n+5))
      (isCycle_finRotate_of_le (by omega))
      (support_finRotate_of_le (by omega)) 0

end SymmetricSubgroupAsymptotics
