import SymmetricSubgroupAsymptotics.Non2PreE7Y1RankTailSource
import SymmetricSubgroupAsymptotics.BinaryMarkedInvariantsCongr
import SymmetricSubgroupAsymptotics.BinaryRankTailFiftyOne
import SymmetricSubgroupAsymptotics.NaturalA4ScalarFourHead
import SymmetricSubgroupAsymptotics.NaturalA4ComparatorAction

/-!
# Y1: the summed-source rank-tail certificate

The Y1 source is hot when some index-three kernel `F` of the complete source
has `d₂(F) > 51b/200`.  Hot sources are counted through a hot kernel and one
further permutation, and hot kernels by the untilted rank tail at
`a = 51/200` and tilt `r = ⌈b/100⌉`:

`∑_{J ≤ S_b} Z_J(U) ≤ C_U (1+b) 2^(153b/200) s_b
    + ν(U) (b!)^16 · b! · 2^(-51 r b / 200) s_{b+2r}`.

The square completion `(b+2r)²/16 - 51rb/200 ≤ b²/16 - b²/40000 + 1/4`
leaves a quadratic deficit for the factors `(b!)^17`.  The cold slope
`153/200` meets the width-eight gap at `ρ = 1/8192`.

The certificate keeps the hot/cold split until after the sum over sources;
it is meant for the summed-source physical transfer.
-/

set_option autoImplicit false
noncomputable section
open scoped BigOperators Classical

namespace SymmetricSubgroupAsymptotics
namespace Non2UnipotentPrefixFiniteMenu

/-- A group with an index-three top is generated by the image of its kernel
and one element over the generator. -/
theorem eq_closure_of_indexThree {b : ℕ} (J : Subgroup (Equiv.Perm (Fin b)))
    (θ : J →* CyclicThree) (x : J) (hx : θ x = Multiplicative.ofAdd 1) :
    J = Subgroup.closure
      ((θ.ker.map J.subtype : Set (Equiv.Perm (Fin b))) ∪ {(x : Equiv.Perm (Fin b))}) := by
  apply le_antisymm
  · intro g hg
    let m := (Multiplicative.toAdd (θ ⟨g, hg⟩)).val
    have hmem : (x ^ m)⁻¹ * ⟨g, hg⟩ ∈ θ.ker := by
      rw [MonoidHom.mem_ker, map_mul, map_inv, map_pow, hx]
      have hm : (Multiplicative.ofAdd (1 : ZMod 3)) ^ m = θ ⟨g, hg⟩ := by
        rw [← ofAdd_nsmul, nsmul_eq_mul, mul_one]
        simp [m]
      rw [hm, inv_mul_cancel]
    have hy : (((x ^ m)⁻¹ * ⟨g, hg⟩ : J) : Equiv.Perm (Fin b)) ∈
        Subgroup.closure ((θ.ker.map J.subtype : Set (Equiv.Perm (Fin b))) ∪
          {(x : Equiv.Perm (Fin b))}) :=
      Subgroup.subset_closure (Or.inl ⟨_, hmem, rfl⟩)
    have hxmem : (x : Equiv.Perm (Fin b)) ∈
        Subgroup.closure ((θ.ker.map J.subtype : Set (Equiv.Perm (Fin b))) ∪
          {(x : Equiv.Perm (Fin b))}) :=
      Subgroup.subset_closure (Or.inr rfl)
    have hg' : g = (x : Equiv.Perm (Fin b)) ^ m *
        (((x ^ m)⁻¹ * ⟨g, hg⟩ : J) : Equiv.Perm (Fin b)) := by simp
    rw [hg']
    exact Subgroup.mul_mem _ (Subgroup.pow_mem _ hxmem m) hy
  · rw [Subgroup.closure_le]
    rintro y (⟨z, _, rfl⟩ | hy)
    · exact z.2
    · rw [Set.mem_singleton_iff] at hy
      rw [hy]
      exact x.2

/-- Hot complete sources are counted by a hot index-three kernel and one
further permutation: `#hot ≤ b! · #{F : d₂(F) > a b}`. -/
theorem indexThreeRankHot_card_le (a : ℝ) (b : ℕ) :
    ((Finset.univ.filter
        (fun J : Subgroup (Equiv.Perm (Fin b)) => IndexThreeRankHot a J)).card : ℝ) ≤
      (Nat.factorial b : ℝ) *
        ((Finset.univ.filter
          (fun F : Subgroup (Equiv.Perm (Fin b)) => BinaryRankHot a F)).card : ℝ) := by
  let HJ := {J : Subgroup (Equiv.Perm (Fin b)) // IndexThreeRankHot a J}
  let HF := {F : Subgroup (Equiv.Perm (Fin b)) // BinaryRankHot a F}
  have hwit : ∀ J : HJ, ∃ θ : J.1 →* CyclicThree, ∃ x : J.1,
      Function.Surjective θ ∧ a * b < binaryCharacterRank θ.ker ∧
        θ x = Multiplicative.ofAdd 1 := by
    intro J
    obtain ⟨θ, hθ, hhot⟩ := J.2
    obtain ⟨x, hx⟩ := hθ (Multiplicative.ofAdd 1)
    exact ⟨θ, x, hθ, hhot, hx⟩
  choose θ x hθ hhot hx using hwit
  let Ψ : HJ → HF × Equiv.Perm (Fin b) := fun J =>
    (⟨(θ J).ker.map J.1.subtype, by
      unfold BinaryRankHot
      rw [← binaryCharacterRank_congr (Subgroup.equivMapOfInjective (θ J).ker
        J.1.subtype Subtype.val_injective)]
      exact hhot J⟩, (x J : Equiv.Perm (Fin b)))
  have hΨ : Function.Injective Ψ := by
    intro J J' hJJ'
    have h1 : (θ J).ker.map J.1.subtype = (θ J').ker.map J'.1.subtype :=
      congrArg (fun z : HF × Equiv.Perm (Fin b) => z.1.1) hJJ'
    have h2 : (x J : Equiv.Perm (Fin b)) = (x J' : Equiv.Perm (Fin b)) :=
      congrArg (fun z : HF × Equiv.Perm (Fin b) => z.2) hJJ'
    apply Subtype.ext
    rw [eq_closure_of_indexThree J.1 (θ J) (x J) (hx J),
      eq_closure_of_indexThree J'.1 (θ J') (x J') (hx J'), h1, h2]
  have hcard := Nat.card_le_card_of_injective Ψ hΨ
  rw [Nat.card_prod, Nat.card_perm, Nat.card_fin] at hcard
  have hJc : (Finset.univ.filter
      (fun J : Subgroup (Equiv.Perm (Fin b)) => IndexThreeRankHot a J)).card =
      Nat.card HJ := by rw [Nat.card_eq_fintype_card, Fintype.card_subtype]
  have hFc : (Finset.univ.filter
      (fun F : Subgroup (Equiv.Perm (Fin b)) => BinaryRankHot a F)).card =
      Nat.card HF := by rw [Nat.card_eq_fintype_card, Fintype.card_subtype]
  rw [hJc, hFc]
  have : Nat.card HJ ≤ Nat.factorial b * Nat.card HF := by
    rw [mul_comm]
    exact hcard
  exact_mod_cast this

/-- The square completion for the Y1 kernel tail (`ℓ = 0`). -/
theorem y1RankTail_squareCompletion (b : ℕ) :
    ((b : ℝ) + 2 * rankTail51Tilt b) ^ 2 / 16 -
        (rankTail51Tilt b : ℝ) * (51 / 200) * b ≤
      (b : ℝ) ^ 2 / 16 - (b : ℝ) ^ 2 / 40000 + 1 / 4 := by
  simpa using rankTail51_squareCompletion b 0

/-- The cold slope `153/200` meets the width-eight cold gap at the global
`ρ = 1/8192`. -/
theorem y1RankTail_coldGap :
    (153 / 200 : ℝ) ≤
      (halfDegree 8 : ℝ) / 4 - preE7CharacterRho * (8 : ℕ) / 4 := by
  unfold preE7CharacterRho halfDegree
  norm_num

namespace PreE7Y1ActionCertificate

variable {w : ℕ} {U : Subgroup (Equiv.Perm (Fin w))}
  (C : PreE7Y1ActionCertificate U)

/-- The summed complete source, with the cold envelope on cold sources and
the full fibre only on hot sources, counted through their hot index-three
kernels. -/
theorem summedSource_le (lit : PreE7CharacterLiterature) (b : ℕ)
    (P : Subgroup (U × Equiv.Perm (Fin b)) → Prop) :
    (∑ J : Subgroup (Equiv.Perm (Fin b)), fusionCompleteSourceSum U P J) ≤
      C.constant * (1 + b) * (2 : ℝ) ^ ((153 / 200 : ℝ) * b) *
          (subgroupCount b : ℝ) +
        (PreE7B6ActionCertificate.normalCount U : ℝ) *
            ((Nat.factorial b : ℕ) : ℝ) ^ 16 *
          ((Nat.factorial b : ℝ) *
            ((2 : ℝ) ^ (-((rankTail51Tilt b : ℝ) * (51 / 200) * b)) *
              (subgroupCount (b + 2 * rankTail51Tilt b) : ℝ))) := by
  set K₁ : ℝ := C.constant * (1 + b) * (2 : ℝ) ^ ((153 / 200 : ℝ) * b)
  set K₂ : ℝ := (PreE7B6ActionCertificate.normalCount U : ℝ) *
    ((Nat.factorial b : ℕ) : ℝ) ^ 16
  have hK₁ : 0 ≤ K₁ := by
    have := C.constant_nonneg
    positivity
  have hK₂ : 0 ≤ K₂ := by positivity
  let hot : Subgroup (Equiv.Perm (Fin b)) → Prop := IndexThreeRankHot (51 / 200)
  rw [← Finset.sum_filter_add_sum_filter_not Finset.univ hot]
  refine (add_comm _ _).le.trans (add_le_add ?_ ?_)
  · calc (∑ J ∈ Finset.univ.filter (fun J => ¬ hot J),
          fusionCompleteSourceSum U P J)
        ≤ ∑ J ∈ Finset.univ.filter (fun J => ¬ hot J), K₁ := by
          apply Finset.sum_le_sum
          intro J hJ
          exact C.completeSource_cold lit P J (Finset.mem_filter.mp hJ).2
      _ = K₁ * ((Finset.univ.filter (fun J => ¬ hot J)).card : ℝ) := by
          rw [Finset.sum_const, nsmul_eq_mul, mul_comm]
      _ ≤ K₁ * (subgroupCount b : ℝ) := by
          apply mul_le_mul_of_nonneg_left _ hK₁
          have hle := Finset.card_filter_le
            (Finset.univ : Finset (Subgroup (Equiv.Perm (Fin b)))) (fun J => ¬ hot J)
          rw [Finset.card_univ, Fintype.card_eq_nat_card] at hle
          exact_mod_cast hle
  · calc (∑ J ∈ Finset.univ.filter hot, fusionCompleteSourceSum U P J)
        ≤ ∑ J ∈ Finset.univ.filter hot, K₂ :=
          Finset.sum_le_sum (fun J _ => C.completeSource_full P J)
      _ = K₂ * ((Finset.univ.filter hot).card : ℝ) := by
          rw [Finset.sum_const, nsmul_eq_mul, mul_comm]
      _ ≤ K₂ * ((Nat.factorial b : ℝ) *
            ((2 : ℝ) ^ (-((rankTail51Tilt b : ℝ) * (51 / 200) * b)) *
              (subgroupCount (b + 2 * rankTail51Tilt b) : ℝ))) := by
          apply mul_le_mul_of_nonneg_left _ hK₂
          exact (indexThreeRankHot_card_le (51 / 200) b).trans
            (mul_le_mul_of_nonneg_left (binaryRankHot51_card_le b)
              (Nat.cast_nonneg _))

end PreE7Y1ActionCertificate

/-! ## The family-specific certificate and its dispatcher -/

/-- The width-eight repeated-`A₄` rank-tail certificate on one retained
action class.  It keeps the per-source cold and full envelopes and their sum
over all complementary sources with the hot sources counted through their
hot index-three kernels, together with the two numerical facts at
`ρ = 1/8192`. -/
structure PreE7Y1RankTailCertificate (w : ℕ) (i : PreE7NonPairActionClass w) :
    Type where
  coldConstant : ℝ
  normalCount : ℝ
  coldConstant_nonneg : 0 ≤ coldConstant
  normalCount_nonneg : 0 ≤ normalCount
  width_eq : w = 8
  cold : ∀ (b : ℕ)
      (P : Subgroup (preE7NonPairAction w i × Equiv.Perm (Fin b)) → Prop)
      (J : Subgroup (Equiv.Perm (Fin b))), ¬ IndexThreeRankHot (51 / 200) J →
    fusionCompleteSourceSum (preE7NonPairAction w i) P J ≤
      coldConstant * (1 + b) * (2 : ℝ) ^ ((153 / 200 : ℝ) * b)
  full : ∀ (b : ℕ)
      (P : Subgroup (preE7NonPairAction w i × Equiv.Perm (Fin b)) → Prop)
      (J : Subgroup (Equiv.Perm (Fin b))),
    fusionCompleteSourceSum (preE7NonPairAction w i) P J ≤
      normalCount * ((Nat.factorial b : ℕ) : ℝ) ^ 16
  summed : ∀ (b : ℕ)
      (P : Subgroup (preE7NonPairAction w i × Equiv.Perm (Fin b)) → Prop),
    (∑ J : Subgroup (Equiv.Perm (Fin b)),
        fusionCompleteSourceSum (preE7NonPairAction w i) P J) ≤
      coldConstant * (1 + b) * (2 : ℝ) ^ ((153 / 200 : ℝ) * b) *
          (subgroupCount b : ℝ) +
        normalCount * ((Nat.factorial b : ℕ) : ℝ) ^ 16 *
          ((Nat.factorial b : ℝ) *
            ((2 : ℝ) ^ (-((rankTail51Tilt b : ℝ) * (51 / 200) * b)) *
              (subgroupCount (b + 2 * rankTail51Tilt b) : ℝ)))
  cold_gap : (153 / 200 : ℝ) ≤
    (halfDegree w : ℝ) / 4 - preE7CharacterRho * w / 4
  square_completion : ∀ b : ℕ,
    ((b : ℝ) + 2 * rankTail51Tilt b) ^ 2 / 16 -
        (rankTail51Tilt b : ℝ) * (51 / 200) * b ≤
      (b : ℝ) ^ 2 / 16 - (b : ℝ) ^ 2 / 40000 + 1 / 4

/-- The Y1 source on one retained action class.  The family predicate is
existence of this datum. -/
abbrev PreE7Y1SourceData (w : ℕ) (i : PreE7NonPairActionClass w) : Type 1 :=
  PreE7Y1ActionCertificate (preE7NonPairAction w i)

/-- The Y1 rank-tail certificate of one certified action. -/
def preE7_y1RankTailCertificate (lit : PreE7CharacterLiterature) {w : ℕ}
    {i : PreE7NonPairActionClass w} (S : PreE7Y1SourceData w i) :
    PreE7Y1RankTailCertificate w i where
  coldConstant := S.constant
  normalCount := PreE7B6ActionCertificate.normalCount (preE7NonPairAction w i)
  coldConstant_nonneg := S.constant_nonneg
  normalCount_nonneg := Nat.cast_nonneg _
  width_eq := S.width_eq
  cold b P J hJ := S.completeSource_cold lit P J hJ
  full b P J := S.completeSource_full P J
  summed b P := S.summedSource_le lit b P
  cold_gap := by
    have hw := S.width_eq
    subst hw
    exact y1RankTail_coldGap
  square_completion := y1RankTail_squareCompletion

/-- The family dispatcher for the Y1 branch of the binary rank-tail
moment. -/
def preE7_rankTailCertificate_y1
    (family : PreE7NoPairNoC3EarlierOwnerFamily) (_hfamily : family = .y1)
    (w : ℕ) (i : PreE7NonPairActionClass w) (hsource : PreE7Y1SourceData w i)
    (lit : PreE7CharacterLiterature) : PreE7Y1RankTailCertificate w i :=
  preE7_y1RankTailCertificate lit hsource

/-! ## The natural width-four `A4` rank-tail row -/

namespace NaturalA4RankTail

abbrev A4 := NaturalA4ScalarFourHead.G

private def quotientTopEquiv (G H : Type*) [Group G] [Group H] :
    (G ⧸ (⊤ : Subgroup G)) ≃* (H ⧸ (⊤ : Subgroup H)) := by
  letI : Subsingleton (G ⧸ (⊤ : Subgroup G)) := ⟨by
    intro x y
    exact Quotient.inductionOn₂ x y (fun a b =>
      QuotientGroup.eq_iff_div_mem.mpr (Subgroup.mem_top _))⟩
  letI : Subsingleton (H ⧸ (⊤ : Subgroup H)) := ⟨by
    intro x y
    exact Quotient.inductionOn₂ x y (fun a b =>
      QuotientGroup.eq_iff_div_mem.mpr (Subgroup.mem_top _))⟩
  exact MulEquiv.ofBijective (1 : (G ⧸ (⊤ : Subgroup G)) →*
      (H ⧸ (⊤ : Subgroup H)))
    ⟨fun _ _ _ => Subsingleton.elim _ _,
      fun y => ⟨1, Subsingleton.elim _ y⟩⟩

private theorem epi_le_completeWeight_of_equiv
    {Q R : Type*} [Group Q] [Group R] [Finite R]
    {b : ℕ} (J : Subgroup (Equiv.Perm (Fin b)))
    (M : {M : Subgroup R // M.Normal}) (e : Q ≃* R ⧸ M.1) :
    (Nat.card (GroupEpimorphism J Q) : ℝ) ≤
      completeQuotientWeight (R := R) J := by
  have htransport : Nat.card (GroupEpimorphism J Q) =
      Nat.card (GroupEpimorphism J (R ⧸ M.1)) :=
    fusionGroupEpimorphism_card_congr (MulEquiv.refl J) e
  have haxis : Nat.card (GroupEpimorphism J (R ⧸ M.1)) ≤
      completeQuotientCount (R := R) J := by
    unfold completeQuotientCount
    exact Finset.single_le_sum
      (fun L _ => Nat.zero_le (Nat.card (GroupEpimorphism J (R ⧸ L.1))))
      (Finset.mem_univ M)
  unfold completeQuotientWeight
  exact_mod_cast htransport.le.trans haxis

/-- Every nonbottom normal quotient of natural `A4` is a literal quotient
of the regular `C3` comparator. -/
theorem nonbottom_epi_le_weight
    (N : {N : Subgroup A4 // N.Normal}) (hN : N.1 ≠ ⊥)
    {b : ℕ} (J : Subgroup (Equiv.Perm (Fin b))) :
    (Nat.card (GroupEpimorphism J (A4 ⧸ N.1)) : ℝ) ≤
      completeQuotientWeight (R := CyclicThree) J := by
  letI : N.1.Normal := N.2
  rcases NaturalA4ScalarFourHead.normal_subgroup_trichotomy N.1 N.2 with
      hbot | hK | htop
  · exact absurd hbot hN
  · letI : (alternatingGroup.kleinFour (Fin 4)).Normal := hK ▸ N.2
    let eN : (A4 ⧸ N.1) ≃*
        (A4 ⧸ alternatingGroup.kleinFour (Fin 4)) :=
      QuotientGroup.congr N.1 (alternatingGroup.kleinFour (Fin 4))
        (MulEquiv.refl A4) (by simpa using hK)
    let eK : (A4 ⧸ alternatingGroup.kleinFour (Fin 4)) ≃*
        (A4 ⧸ NaturalA4ScalarFourHead.top.ker) :=
      QuotientGroup.congr (alternatingGroup.kleinFour (Fin 4))
        NaturalA4ScalarFourHead.top.ker (MulEquiv.refl A4)
          (by rw [NaturalA4ScalarFourHead.top_ker]; simp)
    let M : {M : Subgroup CyclicThree // M.Normal} := ⟨⊥, inferInstance⟩
    have e : (A4 ⧸ alternatingGroup.kleinFour (Fin 4)) ≃*
        (CyclicThree ⧸ M.1) := by
      simpa only [M] using eK.trans
        ((QuotientGroup.quotientKerEquivOfSurjective
          NaturalA4ScalarFourHead.top NaturalA4ScalarFourHead.top_surjective).trans
            QuotientGroup.quotientBot.symm)
    exact epi_le_completeWeight_of_equiv J M (eN.trans e)
  · let eN : (A4 ⧸ N.1) ≃* (A4 ⧸ (⊤ : Subgroup A4)) :=
      QuotientGroup.congr N.1 ⊤ (MulEquiv.refl A4) (by simpa using htop)
    let M : {M : Subgroup CyclicThree // M.Normal} := ⟨⊤, inferInstance⟩
    exact epi_le_completeWeight_of_equiv J M
      (eN.trans (quotientTopEquiv A4 CyclicThree))

/-- A linear factor is absorbed by the exponent gap
`1/3 - 51/200`. -/
theorem scalarFour_polynomial_absorption (b : ℕ) :
    ((b : ℝ) + 1) * (2 : ℝ) ^ ((51 / 200 : ℝ) * b) ≤
      13 * (2 : ℝ) ^ ((1 / 3 : ℝ) * b) := by
  let q := b / 13
  have hqpow : q + 1 ≤ 2 ^ q := Nat.add_one_le_iff.mpr q.lt_two_pow_self
  have hbq : b + 1 ≤ 13 * (q + 1) := by dsimp only [q]; omega
  have hpolyNat : b + 1 ≤ 13 * 2 ^ q :=
    hbq.trans (Nat.mul_le_mul_left 13 hqpow)
  have hqNat : 13 * q ≤ b := by
    dsimp only [q]
    simpa only [mul_comm] using Nat.div_mul_le_self b 13
  have hqR : (q : ℝ) ≤ ((1 : ℝ) / 13) * b := by
    have h : (13 : ℝ) * q ≤ b := by exact_mod_cast hqNat
    linarith
  have hpoly : (b : ℝ) + 1 ≤
      13 * (2 : ℝ) ^ (((1 : ℝ) / 13) * b) := by
    calc
      (b : ℝ) + 1 ≤ 13 * (2 : ℝ) ^ q := by exact_mod_cast hpolyNat
      _ = 13 * (2 : ℝ) ^ (q : ℝ) := by rw [Real.rpow_natCast]
      _ ≤ 13 * (2 : ℝ) ^ (((1 : ℝ) / 13) * b) :=
        mul_le_mul_of_nonneg_left
          (Real.rpow_le_rpow_of_exponent_le (by norm_num) hqR) (by norm_num)
  calc
    ((b : ℝ) + 1) * (2 : ℝ) ^ ((51 / 200 : ℝ) * b) ≤
        (13 * (2 : ℝ) ^ (((1 : ℝ) / 13) * b)) *
          (2 : ℝ) ^ ((51 / 200 : ℝ) * b) :=
      mul_le_mul_of_nonneg_right hpoly (by positivity)
    _ = 13 * (2 : ℝ) ^
        ((((1 : ℝ) / 13) + 51 / 200) * b) := by
      rw [mul_assoc, ← Real.rpow_add (by norm_num : (0 : ℝ) < 2)]
      congr 2
      ring
    _ ≤ 13 * (2 : ℝ) ^ ((1 / 3 : ℝ) * b) := by
      apply mul_le_mul_of_nonneg_left _ (by norm_num)
      apply Real.rpow_le_rpow_of_exponent_le (by norm_num)
      have hb0 : (0 : ℝ) ≤ b := by positivity
      nlinarith

/-- On a cold source the full natural `A4` target has slope `1/3`. -/
theorem bottom_epi_cold {b : ℕ} (J : Subgroup (Equiv.Perm (Fin b)))
    (hJ : ¬ IndexThreeRankHot (51 / 200) J) :
    (Nat.card (GroupEpimorphism J A4) : ℝ) ≤
      156 * (2 : ℝ) ^ ((1 / 3 : ℝ) * b) := by
  have hepi := NaturalA4ScalarFourHead.headed.epi_card_le (J := J)
    ((51 / 200 : ℝ) * b)
    (fun theta htheta => indexThreeRank_le_of_not_hot hJ theta htheta)
  have hrank := commutator_binaryCharacterRank_le_half J
  have hcard : (Nat.card A4 : ℝ) = 12 := by
    exact_mod_cast (alternatingGroup.card_of_card_eq_four (by simp))
  have hraw : (Nat.card (GroupEpimorphism J A4) : ℝ) ≤
      12 * ((b : ℝ) + 1) * (2 : ℝ) ^ ((51 / 200 : ℝ) * b) := by
    rw [NaturalA4ScalarFourHead.headed_weight, Nat.cast_one, one_mul,
      hcard] at hepi
    calc
      _ ≤ binaryCharacterRank (commutator J) * 12 *
          (2 : ℝ) ^ ((51 / 200 : ℝ) * b) := hepi
      _ ≤ 12 * ((b : ℝ) + 1) *
          (2 : ℝ) ^ ((51 / 200 : ℝ) * b) := by
        apply mul_le_mul_of_nonneg_right _ (by positivity)
        nlinarith [show (0 : ℝ) ≤ b by positivity]
  calc
    _ ≤ 12 * (((b : ℝ) + 1) *
        (2 : ℝ) ^ ((51 / 200 : ℝ) * b)) := by simpa [mul_assoc] using hraw
    _ ≤ 12 * (13 * (2 : ℝ) ^ ((1 / 3 : ℝ) * b)) :=
      mul_le_mul_of_nonneg_left (scalarFour_polynomial_absorption b) (by norm_num)
    _ = _ := by ring

end NaturalA4RankTail

/-- The literal natural `A4` action at width four. -/
structure PreE7NaturalA4Source (w : ℕ) (i : PreE7NonPairActionClass w) : Prop where
  degree : w = 4
  alternating : preE7NonPairAction w i = alternatingGroup (Fin w)

/-- Source-summed certificate for the natural `A4` action. -/
structure PreE7NaturalA4RankTailCertificate
    (w : ℕ) (i : PreE7NonPairActionClass w) : Type where
  normalCount : ℝ
  normalCount_nonneg : 0 ≤ normalCount
  width_eq : w = 4
  summed : ∀ (b : ℕ)
      (P : Subgroup (preE7NonPairAction w i × Equiv.Perm (Fin b)) → Prop),
    (∑ J : Subgroup (Equiv.Perm (Fin b)),
        fusionCompleteSourceSum (preE7NonPairAction w i) P J) ≤
      (∑ J : Subgroup (Equiv.Perm (Fin b)),
        (normalCount * completeQuotientWeight (R := CyclicThree) J +
          (156 * normalCount) * (2 : ℝ) ^ ((1 / 3 : ℝ) * b))) +
        normalCount * ((Nat.factorial b : ℕ) : ℝ) ^ 16 *
          ((Nat.factorial b : ℝ) *
            ((2 : ℝ) ^ (-((rankTail51Tilt b : ℝ) * (51 / 200) * b)) *
              (subgroupCount (b + 2 * rankTail51Tilt b) : ℝ)))

namespace PreE7NaturalA4Source

variable {w : ℕ} {i : PreE7NonPairActionClass w}
  (S : PreE7NaturalA4Source w i)

include S

private theorem axis_cold {b : ℕ}
    (P : Subgroup (preE7NonPairAction w i × Equiv.Perm (Fin b)) → Prop)
    (N : {N : Subgroup (preE7NonPairAction w i) // N.Normal})
    (J : Subgroup (Equiv.Perm (Fin b)))
    (hJ : ¬ IndexThreeRankHot (51 / 200) J) :
    fusionSurvivingEpiCount (preE7NonPairAction w i) P N J ≤
      completeQuotientWeight (R := CyclicThree) J +
        156 * (2 : ℝ) ^ ((1 / 3 : ℝ) * b) := by
  have hw := S.degree
  subst w
  let actionEquiv : preE7NonPairAction 4 i ≃* NaturalA4RankTail.A4 :=
    MulEquiv.subgroupCongr S.alternating
  refine (fusionSurvivingEpiCount_le_groupEpimorphism_card _ _ N J).trans ?_
  haveI : N.1.Normal := N.2
  by_cases hN : N.1 = ⊥
  · let e : (preE7NonPairAction 4 i ⧸ N.1) ≃* NaturalA4RankTail.A4 :=
      (QuotientGroup.quotientMulEquivOfEq hN).trans
        ((QuotientGroup.quotientBot).trans actionEquiv)
    rw [fusionGroupEpimorphism_card_congr (MulEquiv.refl J) e]
    exact (NaturalA4RankTail.bottom_epi_cold J hJ).trans
      (le_add_of_nonneg_left (completeQuotientWeight_nonneg J))
  · let N' : Subgroup NaturalA4RankTail.A4 :=
      N.1.map actionEquiv.toMonoidHom
    haveI hN'normal : N'.Normal := N.2.map _ actionEquiv.surjective
    have hN' : N' ≠ ⊥ := by
      intro hb
      apply hN
      rw [eq_bot_iff]
      intro x hx
      have hx' : actionEquiv x ∈ N' := ⟨x, hx, rfl⟩
      rw [hb] at hx'
      exact (Subgroup.mem_bot).mpr
        (actionEquiv.injective ((Subgroup.mem_bot.mp hx').trans (map_one _).symm))
    let e : (preE7NonPairAction 4 i ⧸ N.1) ≃*
        (NaturalA4RankTail.A4 ⧸ N') :=
      QuotientGroup.congr N.1 N' actionEquiv rfl
    rw [fusionGroupEpimorphism_card_congr (MulEquiv.refl J) e]
    exact (NaturalA4RankTail.nonbottom_epi_le_weight
      ⟨N', hN'normal⟩ hN' J).trans (le_add_of_nonneg_right (by positivity))

private theorem completeSource_cold {b : ℕ}
    (P : Subgroup (preE7NonPairAction w i × Equiv.Perm (Fin b)) → Prop)
    (J : Subgroup (Equiv.Perm (Fin b)))
    (hJ : ¬ IndexThreeRankHot (51 / 200) J) :
    fusionCompleteSourceSum (preE7NonPairAction w i) P J ≤
      (PreE7B6ActionCertificate.normalCount (preE7NonPairAction w i) : ℝ) *
        completeQuotientWeight (R := CyclicThree) J +
      (156 * (PreE7B6ActionCertificate.normalCount
        (preE7NonPairAction w i) : ℝ)) *
          (2 : ℝ) ^ ((1 / 3 : ℝ) * b) := by
  unfold fusionCompleteSourceSum PreE7B6ActionCertificate.normalCount
  calc
    _ ≤ ∑ _N : {N : Subgroup (preE7NonPairAction w i) // N.Normal},
        (completeQuotientWeight (R := CyclicThree) J +
          156 * (2 : ℝ) ^ ((1 / 3 : ℝ) * b)) :=
      Finset.sum_le_sum (fun N _ => S.axis_cold P N J hJ)
    _ = _ := by
      rw [Finset.sum_const, Finset.card_univ, nsmul_eq_mul,
        Fintype.card_eq_nat_card]
      ring

private theorem completeSource_full {b : ℕ}
    (P : Subgroup (preE7NonPairAction w i × Equiv.Perm (Fin b)) → Prop)
    (J : Subgroup (Equiv.Perm (Fin b))) :
    fusionCompleteSourceSum (preE7NonPairAction w i) P J ≤
      (PreE7B6ActionCertificate.normalCount (preE7NonPairAction w i) : ℝ) *
        ((Nat.factorial b : ℕ) : ℝ) ^ 16 := by
  have hw := S.degree
  subst w
  unfold fusionCompleteSourceSum PreE7B6ActionCertificate.normalCount
  calc
    _ ≤ ∑ _N : {N : Subgroup (preE7NonPairAction 4 i) // N.Normal},
        ((Nat.factorial b : ℕ) : ℝ) ^ 16 := by
      apply Finset.sum_le_sum
      intro N _
      refine (fusionSurvivingEpiCount_le_groupEpimorphism_card _ _ N J).trans ?_
      have hU : Nat.card (preE7NonPairAction 4 i) ≤ 2 ^ 16 := by
        have h := Nat.card_le_card_of_injective
          (Subtype.val : preE7NonPairAction 4 i → Equiv.Perm (Fin 4))
          Subtype.val_injective
        rw [Nat.card_perm, Nat.card_fin] at h
        exact h.trans (by norm_num)
      have hQ : Nat.card (preE7NonPairAction 4 i ⧸ N.1) ≤ 2 ^ 16 :=
        (Nat.card_le_card_of_surjective _
          (QuotientGroup.mk_surjective (s := N.1))).trans hU
      exact_mod_cast groupEpimorphism_card_le_factorial_pow J hQ
    _ = _ := by
      rw [Finset.sum_const, Finset.card_univ, nsmul_eq_mul,
        Fintype.card_eq_nat_card]

/-- The actual natural `A4` action produces the complete correlated
rank-tail certificate. -/
def rankTailCertificate : PreE7NaturalA4RankTailCertificate w i where
  normalCount := PreE7B6ActionCertificate.normalCount (preE7NonPairAction w i)
  normalCount_nonneg := Nat.cast_nonneg _
  width_eq := S.degree
  summed := by
    intro b P
    let hot : Subgroup (Equiv.Perm (Fin b)) → Prop :=
      IndexThreeRankHot (51 / 200)
    let D : ℝ := PreE7B6ActionCertificate.normalCount
      (preE7NonPairAction w i)
    let tail : ℝ := (156 * D) * (2 : ℝ) ^ ((1 / 3 : ℝ) * b)
    let full : ℝ := D * ((Nat.factorial b : ℕ) : ℝ) ^ 16
    have hD : 0 ≤ D := by dsimp [D]; positivity
    have htail : 0 ≤ tail := by dsimp [tail]; positivity
    have hfull : 0 ≤ full := by dsimp [full]; positivity
    rw [← Finset.sum_filter_add_sum_filter_not Finset.univ hot]
    calc
      (∑ J ∈ Finset.univ.filter hot,
          fusionCompleteSourceSum (preE7NonPairAction w i) P J) +
          ∑ J ∈ Finset.univ.filter (fun J => ¬ hot J),
            fusionCompleteSourceSum (preE7NonPairAction w i) P J ≤
        full * ((Finset.univ.filter hot).card : ℝ) +
          ∑ J ∈ Finset.univ.filter (fun J => ¬ hot J),
            (D * completeQuotientWeight (R := CyclicThree) J + tail) := by
        apply add_le_add
        · calc
            _ ≤ ∑ _J ∈ Finset.univ.filter hot, full :=
              Finset.sum_le_sum (fun J _ => S.completeSource_full P J)
            _ = _ := by rw [Finset.sum_const, nsmul_eq_mul, mul_comm]
        · apply Finset.sum_le_sum
          intro J hJ
          exact S.completeSource_cold P J (Finset.mem_filter.mp hJ).2
      _ ≤ full * ((Finset.univ.filter hot).card : ℝ) +
          ∑ J : Subgroup (Equiv.Perm (Fin b)),
            (D * completeQuotientWeight (R := CyclicThree) J + tail) := by
        exact add_le_add (le_refl _)
          (Finset.sum_le_sum_of_subset_of_nonneg (Finset.filter_subset _ _)
            (fun _ _ _ => add_nonneg
              (mul_nonneg hD (completeQuotientWeight_nonneg _)) htail))
      _ ≤ full *
            ((Nat.factorial b : ℝ) *
              ((2 : ℝ) ^ (-((rankTail51Tilt b : ℝ) * (51 / 200) * b)) *
                (subgroupCount (b + 2 * rankTail51Tilt b) : ℝ))) +
          ∑ J : Subgroup (Equiv.Perm (Fin b)),
            (D * completeQuotientWeight (R := CyclicThree) J + tail) := by
        exact add_le_add
          (mul_le_mul_of_nonneg_left
            ((indexThreeRankHot_card_le (51 / 200) b).trans
              (mul_le_mul_of_nonneg_left (binaryRankHot51_card_le b)
                (Nat.cast_nonneg _))) hfull) (le_refl _)
      _ = _ := by
        rw [Finset.sum_add_distrib, Finset.sum_const, Finset.card_univ,
          nsmul_eq_mul, Fintype.card_eq_nat_card]
        dsimp only [D, tail, full, subgroupCount]
        ring

end PreE7NaturalA4Source

theorem preE7_y1_specialMoment :
    PreE7NoPairNoC3EarlierOwnerFamily.y1.specialMoment = .binaryRankTail :=
  rfl

end Non2UnipotentPrefixFiniteMenu
end SymmetricSubgroupAsymptotics
