import SymmetricSubgroupAsymptotics.Non2PreE7CharacterCertificateTemplate
import SymmetricSubgroupAsymptotics.BinaryTargetOrderEnvelope

/-!
# B6: the cold and full-fibre package for one six-pair-block action

The historical family B6 consists of the faithful transitive actions on
twelve points with a system of six two-point blocks (exact local `C2`).
For the complete source `J ≤ S_b` put `r = d₂(J)`, the binary character rank.
The source is cold when `r ≤ 13b/50`.

Each literal normal quotient `Q = U/N` carries one of three fixed
certificates:

* A: a jointly faithful character tuple of slope at most `4/3`, giving
  `Epi(J,Q) ≤ |Aut Q| 2^(4b/3)` (historically one irreducible, or one linear
  and one irreducible, or two linear characters: slope at most `log₂ 15 / 3`);
* B: `Q` is a `2`-group of order at most `32`, so every map factors through
  the maximal binary quotient and `Hom(J,Q) ≤ |Q|^r ≤ 2^(5r)`;
* C: an independently proved full-source envelope
  `Epi(J,Q) ≤ K (1+b) 2^(s b)` with `s ≤ 4/3` (historically the MULT bound
  for `C₂^e × (F₄²:C₃)`).

Summing the literal normal menu gives, on every cold source,

`Z_J(U) ≤ C_U (1+b) 2^(4b/3)`.

Without any temperature, every map to a quotient of order at most `2^16` is
determined by a generating set of size at most `log₂ |J|`, whence

`Z_J(U) ≤ ν(U) (b!)^16`.

The order bound `|U| ≤ 2^6 · 6! = 46080 < 2^16` is proved from the literal
block chart.  The 182-class census of the historical source is not checked
Lean data here; the certificate below is generic in its A/B/C partition.
-/

set_option autoImplicit false
noncomputable section
open scoped Classical

namespace SymmetricSubgroupAsymptotics

/-! ## Generating sets and the unrestricted fibre -/

/-- Every finite group is generated by a finite set `S` with `2^|S| ≤ |G|`:
an element outside the span of the previous ones at least doubles it. -/
theorem exists_generating_finset_two_pow_le (G : Type*) [Group G] [Finite G] :
    ∃ S : Finset G, Subgroup.closure (S : Set G) = ⊤ ∧
      2 ^ S.card ≤ Nat.card G := by
  suffices h : ∀ m : ℕ, ∀ S : Finset G,
      2 ^ S.card ≤ Nat.card (Subgroup.closure (S : Set G)) →
      Nat.card G - Nat.card (Subgroup.closure (S : Set G)) ≤ m →
      ∃ T : Finset G, Subgroup.closure (T : Set G) = ⊤ ∧
        2 ^ T.card ≤ Nat.card G by
    refine h (Nat.card G) ∅ ?_ (Nat.sub_le _ _)
    simp
  intro m
  induction m with
  | zero =>
    intro S hS hm
    have hcard : Nat.card (Subgroup.closure (S : Set G)) = Nat.card G :=
      le_antisymm (Subgroup.card_le_card_group _) (by omega)
    have htop := Subgroup.eq_top_of_card_eq _ hcard
    exact ⟨S, htop, hS.trans hcard.le⟩
  | succ m ih =>
    intro S hS hm
    by_cases htop : Subgroup.closure (S : Set G) = ⊤
    · refine ⟨S, htop, hS.trans ?_⟩
      exact Subgroup.card_le_card_group _
    · obtain ⟨g, hg⟩ : ∃ g, g ∉ Subgroup.closure (S : Set G) := by
        by_contra hall
        push Not at hall
        exact htop (eq_top_iff.mpr fun g _ => hall g)
      have hgS : g ∉ S := fun h => hg (Subgroup.subset_closure h)
      let S' := insert g S
      have hle : Subgroup.closure (S : Set G) ≤ Subgroup.closure (S' : Set G) :=
        Subgroup.closure_mono (by simp [S'])
      have hgS' : g ∈ Subgroup.closure (S' : Set G) :=
        Subgroup.subset_closure (by simp [S'])
      have hdvd := Subgroup.card_dvd_of_le hle
      have hlt : Nat.card (Subgroup.closure (S : Set G)) <
          Nat.card (Subgroup.closure (S' : Set G)) := by
        refine lt_of_le_of_ne (Subgroup.card_le_of_le hle) ?_
        intro heq
        have := Subgroup.eq_of_le_of_card_ge hle heq.ge
        exact hg (this ▸ hgS')
      have hdouble : 2 * Nat.card (Subgroup.closure (S : Set G)) ≤
          Nat.card (Subgroup.closure (S' : Set G)) := by
        obtain ⟨k, hk⟩ := hdvd
        have hpos : 0 < Nat.card (Subgroup.closure (S : Set G)) := Nat.card_pos
        rcases k with _ | _ | k
        · omega
        · omega
        · rw [hk]
          nlinarith
      have hcardS' : S'.card = S.card + 1 := Finset.card_insert_of_notMem hgS
      apply ih S'
      · rw [hcardS', pow_succ]
        omega
      · have := Subgroup.card_le_card_group (Subgroup.closure (S' : Set G))
        omega

/-- A homomorphism is determined by its values on a generating set. -/
theorem monoidHom_card_le_pow_of_closure {G Q : Type*} [Group G] [Group Q]
    [Finite Q] (S : Finset G) (hS : Subgroup.closure (S : Set G) = ⊤) :
    Nat.card (G →* Q) ≤ Nat.card Q ^ S.card := by
  let e : (G →* Q) → (S → Q) := fun f s => f s
  have he : Function.Injective e := by
    intro f g h
    apply MonoidHom.eq_of_eqOn_dense hS
    intro s hs
    exact congrFun h ⟨s, hs⟩
  calc Nat.card (G →* Q) ≤ Nat.card (S → Q) :=
        Nat.card_le_card_of_injective e he
    _ = Nat.card Q ^ S.card := by
        rw [Nat.card_fun, Nat.card_eq_fintype_card (α := S), Fintype.card_coe]

/-- The unrestricted fibre bound: maps from an actual `J ≤ S_b` onto a
target of order at most `2^m` number at most `(b!)^m`. -/
theorem groupEpimorphism_card_le_factorial_pow {b m : ℕ}
    (J : Subgroup (Equiv.Perm (Fin b))) {Q : Type*} [Group Q] [Finite Q]
    (hQ : Nat.card Q ≤ 2 ^ m) :
    Nat.card (GroupEpimorphism J Q) ≤ (Nat.factorial b) ^ m := by
  obtain ⟨S, hS, hcard⟩ := exists_generating_finset_two_pow_le J
  have hepi : Nat.card (GroupEpimorphism J Q) ≤ Nat.card (J →* Q) := by
    letI : Finite (J →* Q) := Finite.of_injective (fun f : J →* Q => (f : J → Q))
      DFunLike.coe_injective
    exact Nat.card_le_card_of_injective Subtype.val Subtype.val_injective
  have hJ : Nat.card J ≤ Nat.factorial b := by
    have := Nat.card_le_card_of_injective (Subtype.val : J → Equiv.Perm (Fin b))
      Subtype.val_injective
    rwa [Nat.card_perm, Nat.card_fin] at this
  calc Nat.card (GroupEpimorphism J Q) ≤ Nat.card (J →* Q) := hepi
    _ ≤ Nat.card Q ^ S.card := monoidHom_card_le_pow_of_closure S hS
    _ ≤ (2 ^ m) ^ S.card := Nat.pow_le_pow_left hQ _
    _ = (2 ^ S.card) ^ m := by rw [← pow_mul, ← pow_mul, mul_comm]
    _ ≤ (Nat.card J) ^ m := Nat.pow_le_pow_left hcard _
    _ ≤ (Nat.factorial b) ^ m := Nat.pow_le_pow_left hJ _

/-- The surviving count on one literal axis is at most the full count of
onto maps to that axis quotient. -/
theorem fusionSurvivingEpiCount_le_groupEpimorphism_card {w b : ℕ}
    (U : Subgroup (Equiv.Perm (Fin w)))
    (P : Subgroup (U × Equiv.Perm (Fin b)) → Prop)
    (N : {N : Subgroup U // N.Normal}) (J : Subgroup (Equiv.Perm (Fin b))) :
    fusionSurvivingEpiCount U P N J ≤
      Nat.card (GroupEpimorphism J (U ⧸ N.1)) := by
  letI := groupEpimorphism_finite (J := J) (Q := U ⧸ N.1)
  unfold fusionSurvivingEpiCount
  exact_mod_cast Nat.card_le_card_of_injective Subtype.val
    Subtype.val_injective

/-! ## The six-pair-block order bound -/

/-- A permutation group preserving a literal system of six two-point blocks
has order at most `2^6 · 6! = 46080`: an element is determined by the images
of one point from each block, and those images lie in distinct blocks. -/
theorem sixPairBlock_card_le (e : Fin 12 ≃ Fin 6 × Fin 2)
    (U : Subgroup (Equiv.Perm (Fin 12)))
    (hU : ∀ u ∈ U, ∀ x y : Fin 12, (e x).1 = (e y).1 →
      (e (u x)).1 = (e (u y)).1) :
    Nat.card U ≤ 46080 := by
  let p : Fin 6 → Fin 12 := fun k => e.symm (k, 0)
  let T := {g : Fin 6 → Fin 6 × Fin 2 // Function.Injective (Prod.fst ∘ g)}
  let Φ : U → T := fun u => ⟨fun k => e ((u : Equiv.Perm (Fin 12)) (p k)), by
    intro k l hkl
    have hinv := hU (u⁻¹ : U) (u⁻¹ : U).2 _ _ hkl
    simpa [p] using hinv⟩
  have hΦ : Function.Injective Φ := by
    intro u v huv
    have hp : ∀ k, (u : Equiv.Perm (Fin 12)) (p k) =
        (v : Equiv.Perm (Fin 12)) (p k) := by
      intro k
      have := congrFun (congrArg Subtype.val huv) k
      exact e.injective this
    have hq : ∀ k, (u : Equiv.Perm (Fin 12)) (e.symm (k, 1)) =
        (v : Equiv.Perm (Fin 12)) (e.symm (k, 1)) := by
      intro k
      let q := e.symm (k, 1)
      have hpq : (e q).1 = (e (p k)).1 := by simp [q, p]
      have hbu := hU u u.2 q (p k) hpq
      have hbv := hU v v.2 q (p k) hpq
      have hne : ∀ w : U, (e ((w : Equiv.Perm (Fin 12)) q)).2 ≠
          (e ((w : Equiv.Perm (Fin 12)) (p k))).2 := by
        intro w h2
        have hb := hU w w.2 q (p k) hpq
        have heq : e ((w : Equiv.Perm (Fin 12)) q) =
            e ((w : Equiv.Perm (Fin 12)) (p k)) := Prod.ext hb h2
        have := (w : Equiv.Perm (Fin 12)).injective (e.injective heq)
        have h' := congrArg e this
        simp [q, p] at h'
      have hsnd : (e ((u : Equiv.Perm (Fin 12)) q)).2 =
          (e ((v : Equiv.Perm (Fin 12)) q)).2 := by
        have h1 := hne u
        have h2 := hne v
        rw [← hp k] at h2
        apply Fin.ext
        have a1 := (e ((u : Equiv.Perm (Fin 12)) q)).2.isLt
        have a2 := (e ((v : Equiv.Perm (Fin 12)) q)).2.isLt
        have a3 := (e ((u : Equiv.Perm (Fin 12)) (p k))).2.isLt
        have n1 := Fin.val_ne_of_ne h1
        have n2 := Fin.val_ne_of_ne h2
        omega
      have hfst : (e ((u : Equiv.Perm (Fin 12)) q)).1 =
          (e ((v : Equiv.Perm (Fin 12)) q)).1 := by
        rw [hbu, hbv, hp k]
      exact e.injective (Prod.ext hfst hsnd)
    apply Subtype.ext
    apply Equiv.ext
    intro x
    have hx : x = e.symm ((e x).1, (e x).2) := by simp
    rcases Fin.exists_fin_two.mp ⟨(e x).2, rfl⟩ with h0 | h1
    · rw [hx, h0]
      exact hp _
    · rw [hx, h1]
      exact hq _
  let Ψ : T → Equiv.Perm (Fin 6) × (Fin 6 → Fin 2) := fun g =>
    (Equiv.ofBijective (Prod.fst ∘ g.1) (Finite.injective_iff_bijective.mp g.2),
      Prod.snd ∘ g.1)
  have hΨ : Function.Injective Ψ := by
    intro g h hgh
    apply Subtype.ext
    funext k
    have h1 := congrArg (fun z => (z.1 : Fin 6 → Fin 6) k) hgh
    have h2 := congrFun (congrArg Prod.snd hgh) k
    exact Prod.ext h1 h2
  have hcard := Nat.card_le_card_of_injective (Ψ ∘ Φ) (hΨ.comp hΦ)
  rw [Nat.card_prod, Nat.card_perm, Nat.card_fun, Nat.card_fin,
    Nat.card_fin] at hcard
  simpa [Nat.factorial] using hcard

/-! ## The three quotient certificates -/

/-- The historical A-profiles `(l,t)`, one linear and one general, two
linear, or one general position, have `3^l 5^t ≤ 15 < 16`, hence slope at
most `4/3`. -/
theorem CharacterQuotientCertificate.slope_le_four_thirds_of_mixed
    {Q : Type} [Group Q] (c : CharacterQuotientCertificate Q)
    (hmode : c.mode = .mixed) (hbinary : c.tuple.binaryCount = 0)
    (hprofile : 3 ^ c.tuple.linearCount * 5 ^ c.tuple.generalCount ≤ 15) :
    c.slope ≤ 4 / 3 := by
  have hlog : (c.tuple.linearCount : ℝ) * Real.logb 2 3 +
      (c.tuple.generalCount : ℝ) * Real.logb 2 5 =
        Real.logb 2 ((3 : ℝ) ^ c.tuple.linearCount *
          (5 : ℝ) ^ c.tuple.generalCount) := by
    rw [Real.logb_mul (by positivity) (by positivity), Real.logb_pow,
      Real.logb_pow]
  have hle : Real.logb 2 ((3 : ℝ) ^ c.tuple.linearCount *
      (5 : ℝ) ^ c.tuple.generalCount) ≤ Real.logb 2 16 := by
    apply Real.logb_le_logb_of_le (by norm_num) (by positivity)
    have : 3 ^ c.tuple.linearCount * 5 ^ c.tuple.generalCount ≤ 16 :=
      hprofile.trans (by norm_num)
    exact_mod_cast this
  have h16 : Real.logb 2 16 = 4 := by
    rw [show (16 : ℝ) = 2 ^ (4 : ℕ) by norm_num, Real.logb_pow,
      Real.logb_self_eq_one (by norm_num)]
    norm_num
  unfold CharacterQuotientCertificate.slope
  rw [hmode, hbinary]
  simp only [CharacterQuotientMode.generalSlope, Nat.cast_zero, zero_mul,
    zero_add]
  nlinarith


/-- The historical cold test on the complete source. -/
def PreE7B6Cold {b : ℕ} (J : Subgroup (Equiv.Perm (Fin b))) : Prop :=
  (binaryCharacterRank J : ℝ) ≤ 13 * b / 50

/-- One fixed certificate on a literal normal quotient, in the historical
first-available order A, B, C. -/
inductive PreE7B6QuotientCertificate (Q : Type) [Group Q] : Type 1
  /-- A: a jointly faithful character tuple of slope at most `4/3`. -/
  | character (c : CharacterQuotientCertificate Q) (slope_le : c.slope ≤ 4 / 3)
  /-- B: a binary target of order at most `32`. -/
  | binary (twoGroup : IsPGroup 2 Q) (card_le : Nat.card Q ≤ 32)
  /-- C: an independently proved full-source envelope. -/
  | fullSource (constant slope : ℝ) (constant_nonneg : 0 ≤ constant)
      (slope_le : slope ≤ 4 / 3)
      (bound : ∀ (b : ℕ) (J : Subgroup (Equiv.Perm (Fin b))),
        (Nat.card (GroupEpimorphism J Q) : ℝ) ≤
          constant * (1 + b) * (2 : ℝ) ^ (slope * b))

namespace PreE7B6QuotientCertificate

variable {Q : Type} [Group Q]

/-- The fixed constant of one quotient certificate. -/
def constant : PreE7B6QuotientCertificate Q → ℝ
  | .character _ _ => Nat.card (Q ≃* Q)
  | .binary _ _ => 1
  | .fullSource K _ _ _ _ => K

theorem constant_nonneg (c : PreE7B6QuotientCertificate Q) :
    0 ≤ c.constant := by
  cases c with
  | character => exact Nat.cast_nonneg _
  | binary => exact zero_le_one
  | fullSource _ _ hK _ _ => exact hK

private theorem two_rpow_le_of_le {x y : ℝ} (h : x ≤ y) :
    (2 : ℝ) ^ x ≤ (2 : ℝ) ^ y :=
  Real.rpow_le_rpow_of_exponent_le (by norm_num) h

/-- The cold envelope on one literal quotient. -/
theorem cold_envelope (lit : PreE7CharacterLiterature) [Finite Q]
    (c : PreE7B6QuotientCertificate Q) {b : ℕ}
    (J : Subgroup (Equiv.Perm (Fin b))) (hJ : PreE7B6Cold J) :
    (Nat.card (GroupEpimorphism J Q) : ℝ) ≤
      c.constant * (1 + b) * (2 : ℝ) ^ ((4 / 3 : ℝ) * b) := by
  have hb : (0 : ℝ) ≤ b := Nat.cast_nonneg b
  have hone : (1 : ℝ) ≤ 1 + b := by linarith
  cases c with
  | character c hslope =>
    have h := c.envelope lit b J
    calc (Nat.card (GroupEpimorphism J Q) : ℝ)
        ≤ (Nat.card (Q ≃* Q) : ℝ) * (2 : ℝ) ^ (c.slope * b) := h
      _ ≤ (Nat.card (Q ≃* Q) : ℝ) * (2 : ℝ) ^ ((4 / 3 : ℝ) * b) :=
          mul_le_mul_of_nonneg_left
            (two_rpow_le_of_le (mul_le_mul_of_nonneg_right hslope hb))
            (Nat.cast_nonneg _)
      _ ≤ (Nat.card (Q ≃* Q) : ℝ) * (1 + b) * (2 : ℝ) ^ ((4 / 3 : ℝ) * b) := by
          rw [mul_assoc]
          apply mul_le_mul_of_nonneg_left _ (Nat.cast_nonneg _)
          exact le_mul_of_one_le_left (by positivity) hone
  | binary hQ hcard =>
    letI : Finite (Q ≃* Q) := inferInstance
    have hhom := binaryTargetOrder_hom_card_le (J := J) hQ
    have hlog : Nat.log 2 (Nat.card Q) ≤ 5 := by
      calc Nat.log 2 (Nat.card Q) ≤ Nat.log 2 32 := Nat.log_mono_right hcard
        _ = 5 := by decide
    have hepi : Nat.card (GroupEpimorphism J Q) ≤ Nat.card (J →* Q) := by
      letI : Finite (J →* Q) := Finite.of_injective
        (fun f : J →* Q => (f : J → Q)) DFunLike.coe_injective
      exact Nat.card_le_card_of_injective Subtype.val Subtype.val_injective
    have hnat : Nat.card (GroupEpimorphism J Q) ≤
        2 ^ (5 * binaryCharacterRank J) :=
      hepi.trans (hhom.trans (Nat.pow_le_pow_right (by norm_num)
        (Nat.mul_le_mul_right _ hlog)))
    have hreal : (Nat.card (GroupEpimorphism J Q) : ℝ) ≤
        (2 : ℝ) ^ ((5 * binaryCharacterRank J : ℕ) : ℝ) := by
      rw [Real.rpow_natCast]
      exact_mod_cast hnat
    have hexp : ((5 * binaryCharacterRank J : ℕ) : ℝ) ≤ (4 / 3 : ℝ) * b := by
      push_cast
      unfold PreE7B6Cold at hJ
      nlinarith
    calc (Nat.card (GroupEpimorphism J Q) : ℝ)
        ≤ (2 : ℝ) ^ ((4 / 3 : ℝ) * b) := hreal.trans (two_rpow_le_of_le hexp)
      _ ≤ 1 * (1 + b) * (2 : ℝ) ^ ((4 / 3 : ℝ) * b) := by
          rw [one_mul]
          exact le_mul_of_one_le_left (by positivity) hone
  | fullSource K s hK hs hbound =>
    calc (Nat.card (GroupEpimorphism J Q) : ℝ)
        ≤ K * (1 + b) * (2 : ℝ) ^ (s * b) := hbound b J
      _ ≤ K * (1 + b) * (2 : ℝ) ^ ((4 / 3 : ℝ) * b) :=
          mul_le_mul_of_nonneg_left
            (two_rpow_le_of_le (mul_le_mul_of_nonneg_right hs hb))
            (mul_nonneg hK (by linarith))

end PreE7B6QuotientCertificate

/-! ## The action certificate -/

namespace Non2UnipotentPrefixFiniteMenu

/-- A literal width-twelve action with a fixed system of six two-point
blocks and one fixed A/B/C certificate on every literal normal quotient.
The block chart is part of the certificate; alternative block systems do
not create further certificates. -/
structure PreE7B6ActionCertificate (U : Subgroup (Equiv.Perm (Fin 12))) :
    Type 1 where
  blockChart : Fin 12 ≃ Fin 6 × Fin 2
  preserves : ∀ u ∈ U, ∀ x y : Fin 12,
    (blockChart x).1 = (blockChart y).1 →
      (blockChart (u x)).1 = (blockChart (u y)).1
  quotient : ∀ N : {N : Subgroup U // N.Normal},
    PreE7B6QuotientCertificate (U ⧸ N.1)

namespace PreE7B6ActionCertificate

variable {U : Subgroup (Equiv.Perm (Fin 12))} (C : PreE7B6ActionCertificate U)

/-- The fixed constant `C_U`, summed over the literal normal partition. -/
def constant : ℝ := ∑ N, (C.quotient N).constant

theorem constant_nonneg : 0 ≤ C.constant :=
  Finset.sum_nonneg (fun N _ => (C.quotient N).constant_nonneg)

/-- The number `ν(U)` of literal normal subgroups. -/
def normalCount (U : Subgroup (Equiv.Perm (Fin 12))) : ℕ :=
  Nat.card {N : Subgroup U // N.Normal}

include C in
theorem card_le : Nat.card U ≤ 46080 :=
  sixPairBlock_card_le C.blockChart U C.preserves

include C in
theorem card_le_two_pow : Nat.card U ≤ 2 ^ 16 :=
  C.card_le.trans (by norm_num)

/-- The cold envelope on one literal normal axis of the same complete
source. -/
theorem axis_cold (lit : PreE7CharacterLiterature) {b : ℕ}
    (P : Subgroup (U × Equiv.Perm (Fin b)) → Prop)
    (N : {N : Subgroup U // N.Normal}) (J : Subgroup (Equiv.Perm (Fin b)))
    (hJ : PreE7B6Cold J) :
    fusionSurvivingEpiCount U P N J ≤
      (C.quotient N).constant * (1 + b) * (2 : ℝ) ^ ((4 / 3 : ℝ) * b) :=
  (fusionSurvivingEpiCount_le_groupEpimorphism_card U P N J).trans
    ((C.quotient N).cold_envelope lit J hJ)

/-- The complete cold source: `d₂(J) ≤ 13b/50` implies
`Z_J(U) ≤ C_U (1+b) 2^(4b/3)`. -/
theorem completeSource_cold (lit : PreE7CharacterLiterature) {b : ℕ}
    (P : Subgroup (U × Equiv.Perm (Fin b)) → Prop)
    (J : Subgroup (Equiv.Perm (Fin b))) (hJ : PreE7B6Cold J) :
    fusionCompleteSourceSum U P J ≤
      C.constant * (1 + b) * (2 : ℝ) ^ ((4 / 3 : ℝ) * b) := by
  unfold fusionCompleteSourceSum constant
  rw [Finset.sum_mul, Finset.sum_mul]
  exact Finset.sum_le_sum (fun N _ => C.axis_cold lit P N J hJ)

include C in
/-- The unrestricted fibre on one literal normal axis. -/
theorem axis_full {b : ℕ} (P : Subgroup (U × Equiv.Perm (Fin b)) → Prop)
    (N : {N : Subgroup U // N.Normal}) (J : Subgroup (Equiv.Perm (Fin b))) :
    fusionSurvivingEpiCount U P N J ≤ ((Nat.factorial b : ℕ) : ℝ) ^ 16 := by
  refine (fusionSurvivingEpiCount_le_groupEpimorphism_card U P N J).trans ?_
  have hQ : Nat.card (U ⧸ N.1) ≤ 2 ^ 16 :=
    (Nat.card_le_card_of_surjective _ (QuotientGroup.mk_surjective (s := N.1))).trans
      C.card_le_two_pow
  exact_mod_cast groupEpimorphism_card_le_factorial_pow J hQ

include C in
/-- The unrestricted complete fibre: `Z_J(U) ≤ ν(U) (b!)^16` on every
source, hot or cold. -/
theorem completeSource_full {b : ℕ}
    (P : Subgroup (U × Equiv.Perm (Fin b)) → Prop)
    (J : Subgroup (Equiv.Perm (Fin b))) :
    fusionCompleteSourceSum U P J ≤
      (normalCount U : ℝ) * ((Nat.factorial b : ℕ) : ℝ) ^ 16 := by
  unfold fusionCompleteSourceSum normalCount
  calc (∑ N : {N : Subgroup U // N.Normal}, fusionSurvivingEpiCount U P N J)
      ≤ ∑ _N : {N : Subgroup U // N.Normal},
          ((Nat.factorial b : ℕ) : ℝ) ^ 16 :=
        Finset.sum_le_sum (fun N _ => C.axis_full P N J)
    _ = _ := by
        rw [Finset.sum_const, Finset.card_univ, nsmul_eq_mul,
          Fintype.card_eq_nat_card]

end PreE7B6ActionCertificate

end Non2UnipotentPrefixFiniteMenu

end SymmetricSubgroupAsymptotics
