import SymmetricSubgroupAsymptotics.ScalarFourHeadCount
import SymmetricSubgroupAsymptotics.Non2PreE7B6RankTailSource
import SymmetricSubgroupAsymptotics.BinaryMarkedInvariantsCongr
import SymmetricSubgroupAsymptotics.PermutationThreeGroupRank
import SymmetricSubgroupAsymptotics.BinaryRankTailFiftyOne

/-!
# Y1: the cold and full-fibre package for repeated natural-`A₄` heads

The historical family Y1 is the degree-eight class `A:A₄`.  Its normal
quotients are `Y1`, `F₄²:C₃`, five copies of `A₄`, `C₃` and `1`.  Each
quotient above `C₃` is an index-three extension of a central binary layer by
natural `F₄` layers on which the top acts by `ω`.  The source is hot when
some index-three kernel `F` of the complete source has `200 d₂(F) > 51 b`.

On a cold source every such quotient has at most
`d₂(J') |Q| 2^(weight · 51b/200)` onto maps (`ScalarFourHeadCount`), with
weight at most `3` and `d₂(J') ≤ b/2`.  The remaining quotients carry a
character certificate of slope at most `153/200`; `C₃` needs one linear
character.  Summing gives, on every cold source,

`Z_J(U) ≤ C_U (1+b) 2^(153b/200)`.

Every source satisfies `Z_J(U) ≤ ν(U) (b!)^16`, since `|U| ≤ 8! < 2^16`.
Hot sources are counted through a hot index-three kernel and one further
permutation, which costs the overgroup factor `b!`.

The certificate is generic in its quotient partition; the single
historical class is not assumed as census data.
-/

set_option autoImplicit false
noncomputable section
open scoped BigOperators Classical

namespace SymmetricSubgroupAsymptotics

/-! ## The index-three hot test and its overgroup count -/

/-- Some index-three kernel of the complete source has `d₂ > a b`. -/
def IndexThreeRankHot (a : ℝ) {b : ℕ} (J : Subgroup (Equiv.Perm (Fin b))) :
    Prop :=
  ∃ θ : J →* CyclicThree, Function.Surjective θ ∧
    a * b < binaryCharacterRank θ.ker

theorem indexThreeRank_le_of_not_hot {a : ℝ} {b : ℕ}
    {J : Subgroup (Equiv.Perm (Fin b))} (hJ : ¬ IndexThreeRankHot a J)
    (θ : J →* CyclicThree) (hθ : Function.Surjective θ) :
    (binaryCharacterRank θ.ker : ℝ) ≤ a * b := by
  by_contra hlt
  exact hJ ⟨θ, hθ, lt_of_not_ge hlt⟩

/-- A group with an index-three top is generated by the image of its kernel
and one element over the generator. -/
theorem eq_closure_of_indexThree {b : ℕ} (J : Subgroup (Equiv.Perm (Fin b)))
    (θ : J →* CyclicThree) (x : J) (hx : θ x = Multiplicative.ofAdd 1) :
    J = Subgroup.closure
      ((θ.ker.map J.subtype : Set (Equiv.Perm (Fin b))) ∪ {(x : Equiv.Perm (Fin b))}) := by
  apply le_antisymm
  · intro g hg
    let m := (Multiplicative.toAdd (θ ⟨g, hg⟩)).val
    have hmem : (x ^ m)⁻¹ * ⟨g, hg⟩ ∈ θ.ker := by
      rw [MonoidHom.mem_ker, map_mul, map_inv, map_pow, hx]
      have hm : (Multiplicative.ofAdd (1 : ZMod 3)) ^ m = θ ⟨g, hg⟩ := by
        rw [← ofAdd_nsmul, nsmul_eq_mul, mul_one]
        simp [m]
      rw [hm, inv_mul_cancel]
    have hy : (((x ^ m)⁻¹ * ⟨g, hg⟩ : J) : Equiv.Perm (Fin b)) ∈
        Subgroup.closure ((θ.ker.map J.subtype : Set (Equiv.Perm (Fin b))) ∪
          {(x : Equiv.Perm (Fin b))}) :=
      Subgroup.subset_closure (Or.inl ⟨_, hmem, rfl⟩)
    have hxmem : (x : Equiv.Perm (Fin b)) ∈
        Subgroup.closure ((θ.ker.map J.subtype : Set (Equiv.Perm (Fin b))) ∪
          {(x : Equiv.Perm (Fin b))}) :=
      Subgroup.subset_closure (Or.inr rfl)
    have hg' : g = (x : Equiv.Perm (Fin b)) ^ m *
        (((x ^ m)⁻¹ * ⟨g, hg⟩ : J) : Equiv.Perm (Fin b)) := by
      simp
    rw [hg']
    exact Subgroup.mul_mem _ (Subgroup.pow_mem _ hxmem m) hy
  · rw [Subgroup.closure_le]
    rintro y (⟨z, _, rfl⟩ | hy)
    · exact z.2
    · rw [Set.mem_singleton_iff] at hy
      rw [hy]
      exact x.2

/-- Hot complete sources are counted by a hot index-three kernel and one
further permutation: `#hot ≤ b! · #{F : d₂(F) > a b}`. -/
theorem indexThreeRankHot_card_le (a : ℝ) (b : ℕ) :
    ((Finset.univ.filter
        (fun J : Subgroup (Equiv.Perm (Fin b)) => IndexThreeRankHot a J)).card : ℝ) ≤
      (Nat.factorial b : ℝ) *
        ((Finset.univ.filter
          (fun F : Subgroup (Equiv.Perm (Fin b)) => BinaryRankHot a F)).card : ℝ) := by
  let HJ := {J : Subgroup (Equiv.Perm (Fin b)) // IndexThreeRankHot a J}
  let HF := {F : Subgroup (Equiv.Perm (Fin b)) // BinaryRankHot a F}
  have hwit : ∀ J : HJ, ∃ θ : J.1 →* CyclicThree, ∃ x : J.1,
      Function.Surjective θ ∧ a * b < binaryCharacterRank θ.ker ∧
        θ x = Multiplicative.ofAdd 1 := by
    intro J
    obtain ⟨θ, hθ, hhot⟩ := J.2
    obtain ⟨x, hx⟩ := hθ (Multiplicative.ofAdd 1)
    exact ⟨θ, x, hθ, hhot, hx⟩
  choose θ x hθ hhot hx using hwit
  let Ψ : HJ → HF × Equiv.Perm (Fin b) := fun J =>
    (⟨(θ J).ker.map J.1.subtype, by
      unfold BinaryRankHot
      rw [← binaryCharacterRank_congr (Subgroup.equivMapOfInjective (θ J).ker
        J.1.subtype Subtype.val_injective)]
      exact hhot J⟩, (x J : Equiv.Perm (Fin b)))
  have hΨ : Function.Injective Ψ := by
    intro J J' hJJ'
    have h1 : (θ J).ker.map J.1.subtype = (θ J').ker.map J'.1.subtype :=
      congrArg (fun z : HF × Equiv.Perm (Fin b) => z.1.1) hJJ'
    have h2 : (x J : Equiv.Perm (Fin b)) = (x J' : Equiv.Perm (Fin b)) :=
      congrArg (fun z : HF × Equiv.Perm (Fin b) => z.2) hJJ'
    apply Subtype.ext
    rw [eq_closure_of_indexThree J.1 (θ J) (x J) (hx J),
      eq_closure_of_indexThree J'.1 (θ J') (x J') (hx J'), h1, h2]
  have hcard := Nat.card_le_card_of_injective Ψ hΨ
  rw [Nat.card_prod, Nat.card_perm, Nat.card_fin] at hcard
  have hJc : (Finset.univ.filter
      (fun J : Subgroup (Equiv.Perm (Fin b)) => IndexThreeRankHot a J)).card =
      Nat.card HJ := by
    rw [Nat.card_eq_fintype_card, Fintype.card_subtype]
  have hFc : (Finset.univ.filter
      (fun F : Subgroup (Equiv.Perm (Fin b)) => BinaryRankHot a F)).card =
      Nat.card HF := by
    rw [Nat.card_eq_fintype_card, Fintype.card_subtype]
  rw [hJc, hFc]
  have : Nat.card HJ ≤ Nat.factorial b * Nat.card HF := by
    rw [mul_comm]
    exact hcard
  exact_mod_cast this

/-- The derived subgroup of an actual `J ≤ S_b` has `d₂ ≤ b/2`. -/
theorem commutator_binaryCharacterRank_le_half {b : ℕ}
    (J : Subgroup (Equiv.Perm (Fin b))) :
    (binaryCharacterRank (commutator J) : ℝ) ≤ b / 2 := by
  have h := permutation_binaryCharacterRank_le_half (commutator J) (Fin b)
  rw [Nat.card_fin] at h
  have h' : binaryCharacterRank (commutator J) ≤ b / 2 := h
  calc (binaryCharacterRank (commutator J) : ℝ) ≤ ((b / 2 : ℕ) : ℝ) := by
        exact_mod_cast h'
    _ ≤ b / 2 := Nat.cast_div_le

/-! ## The quotient certificates -/

namespace Non2UnipotentPrefixFiniteMenu

/-- One fixed certificate on a literal Y1 quotient. -/
inductive PreE7Y1QuotientCertificate (Q : Type) [Group Q] : Type 1
  /-- A character tuple of slope at most `153/200` (for `C₃` and `1`). -/
  | character (c : CharacterQuotientCertificate Q) (slope_le : c.slope ≤ 153 / 200)
  /-- An index-three extension of a central binary layer by natural `F₄`
  layers, of weight at most three. -/
  | headed (h : ScalarFourHeadedQuotient Q) (weight_le : h.weight ≤ 3)

namespace PreE7Y1QuotientCertificate

variable {Q : Type} [Group Q]

/-- The fixed constant of one quotient certificate. -/
def constant : PreE7Y1QuotientCertificate Q → ℝ
  | .character _ _ => Nat.card (Q ≃* Q)
  | .headed _ _ => Nat.card Q

theorem constant_nonneg (c : PreE7Y1QuotientCertificate Q) : 0 ≤ c.constant := by
  cases c <;> exact Nat.cast_nonneg _

/-- The cold envelope on one literal quotient. -/
theorem cold_envelope (lit : PreE7CharacterLiterature) [Finite Q]
    (c : PreE7Y1QuotientCertificate Q) {b : ℕ}
    (J : Subgroup (Equiv.Perm (Fin b)))
    (hJ : ¬ IndexThreeRankHot (51 / 200) J) :
    (Nat.card (GroupEpimorphism J Q) : ℝ) ≤
      c.constant * (1 + b) * (2 : ℝ) ^ ((153 / 200 : ℝ) * b) := by
  have hb : (0 : ℝ) ≤ b := Nat.cast_nonneg b
  have hone : (1 : ℝ) ≤ 1 + b := by linarith
  cases c with
  | character c hslope =>
    calc (Nat.card (GroupEpimorphism J Q) : ℝ)
        ≤ (Nat.card (Q ≃* Q) : ℝ) * (2 : ℝ) ^ (c.slope * b) := c.envelope lit b J
      _ ≤ (Nat.card (Q ≃* Q) : ℝ) * (2 : ℝ) ^ ((153 / 200 : ℝ) * b) :=
          mul_le_mul_of_nonneg_left
            (Real.rpow_le_rpow_of_exponent_le (by norm_num)
              (mul_le_mul_of_nonneg_right hslope hb))
            (Nat.cast_nonneg _)
      _ ≤ (Nat.card (Q ≃* Q) : ℝ) * (1 + b) * (2 : ℝ) ^ ((153 / 200 : ℝ) * b) := by
          rw [mul_assoc]
          apply mul_le_mul_of_nonneg_left _ (Nat.cast_nonneg _)
          exact le_mul_of_one_le_left (by positivity) hone
  | headed h hweight =>
    have hepi := h.epi_card_le (J := J) ((51 / 200) * b)
      (fun θ hθ => indexThreeRank_le_of_not_hot hJ θ hθ)
    have hrank := commutator_binaryCharacterRank_le_half J
    have hw : (h.weight : ℝ) ≤ 3 := by exact_mod_cast hweight
    calc (Nat.card (GroupEpimorphism J Q) : ℝ)
        ≤ binaryCharacterRank (commutator J) * Nat.card Q *
            (2 : ℝ) ^ ((h.weight : ℝ) * ((51 / 200) * b)) := hepi
      _ ≤ (1 + b) * Nat.card Q * (2 : ℝ) ^ ((153 / 200 : ℝ) * b) := by
          apply mul_le_mul _ _ (by positivity) (by positivity)
          · exact mul_le_mul_of_nonneg_right (by linarith) (Nat.cast_nonneg _)
          · apply Real.rpow_le_rpow_of_exponent_le (by norm_num)
            nlinarith
      _ = (Nat.card Q : ℝ) * (1 + b) * (2 : ℝ) ^ ((153 / 200 : ℝ) * b) := by
          ring

end PreE7Y1QuotientCertificate

/-! ## The action certificate -/

/-- A literal width-eight action with one fixed Y1 certificate on every
literal normal quotient. -/
structure PreE7Y1ActionCertificate {w : ℕ} (U : Subgroup (Equiv.Perm (Fin w))) :
    Type 1 where
  width_eq : w = 8
  quotient : ∀ N : {N : Subgroup U // N.Normal},
    PreE7Y1QuotientCertificate (U ⧸ N.1)

namespace PreE7Y1ActionCertificate

variable {w : ℕ} {U : Subgroup (Equiv.Perm (Fin w))}
  (C : PreE7Y1ActionCertificate U)

/-- The fixed constant `C_U`, summed over the literal normal partition. -/
def constant : ℝ := ∑ N, (C.quotient N).constant

theorem constant_nonneg : 0 ≤ C.constant :=
  Finset.sum_nonneg (fun N _ => (C.quotient N).constant_nonneg)

include C in
theorem card_le_two_pow : Nat.card U ≤ 2 ^ 16 := by
  have hw := C.width_eq
  subst hw
  have h := Nat.card_le_card_of_injective (Subtype.val : U → Equiv.Perm (Fin 8))
    Subtype.val_injective
  rw [Nat.card_perm, Nat.card_fin] at h
  exact h.trans (by decide)

/-- The cold envelope on one literal normal axis. -/
theorem axis_cold (lit : PreE7CharacterLiterature) {b : ℕ}
    (P : Subgroup (U × Equiv.Perm (Fin b)) → Prop)
    (N : {N : Subgroup U // N.Normal}) (J : Subgroup (Equiv.Perm (Fin b)))
    (hJ : ¬ IndexThreeRankHot (51 / 200) J) :
    fusionSurvivingEpiCount U P N J ≤
      (C.quotient N).constant * (1 + b) * (2 : ℝ) ^ ((153 / 200 : ℝ) * b) :=
  (fusionSurvivingEpiCount_le_groupEpimorphism_card U P N J).trans
    ((C.quotient N).cold_envelope lit J hJ)

/-- The complete cold source: no index-three kernel with `d₂ > 51b/200`
implies `Z_J(U) ≤ C_U (1+b) 2^(153b/200)`. -/
theorem completeSource_cold (lit : PreE7CharacterLiterature) {b : ℕ}
    (P : Subgroup (U × Equiv.Perm (Fin b)) → Prop)
    (J : Subgroup (Equiv.Perm (Fin b)))
    (hJ : ¬ IndexThreeRankHot (51 / 200) J) :
    fusionCompleteSourceSum U P J ≤
      C.constant * (1 + b) * (2 : ℝ) ^ ((153 / 200 : ℝ) * b) := by
  unfold fusionCompleteSourceSum constant
  rw [Finset.sum_mul, Finset.sum_mul]
  exact Finset.sum_le_sum (fun N _ => C.axis_cold lit P N J hJ)

include C in
/-- The unrestricted complete fibre: `Z_J(U) ≤ ν(U) (b!)^16`. -/
theorem completeSource_full {b : ℕ}
    (P : Subgroup (U × Equiv.Perm (Fin b)) → Prop)
    (J : Subgroup (Equiv.Perm (Fin b))) :
    fusionCompleteSourceSum U P J ≤
      (PreE7B6ActionCertificate.normalCount U : ℝ) *
        ((Nat.factorial b : ℕ) : ℝ) ^ 16 := by
  unfold fusionCompleteSourceSum PreE7B6ActionCertificate.normalCount
  calc (∑ N : {N : Subgroup U // N.Normal}, fusionSurvivingEpiCount U P N J)
      ≤ ∑ _N : {N : Subgroup U // N.Normal},
          ((Nat.factorial b : ℕ) : ℝ) ^ 16 := by
        apply Finset.sum_le_sum
        intro N _
        refine (fusionSurvivingEpiCount_le_groupEpimorphism_card U P N J).trans ?_
        have hQ : Nat.card (U ⧸ N.1) ≤ 2 ^ 16 :=
          (Nat.card_le_card_of_surjective _
            (QuotientGroup.mk_surjective (s := N.1))).trans C.card_le_two_pow
        exact_mod_cast groupEpimorphism_card_le_factorial_pow J hQ
    _ = _ := by
        rw [Finset.sum_const, Finset.card_univ, nsmul_eq_mul,
          Fintype.card_eq_nat_card]

end PreE7Y1ActionCertificate

end Non2UnipotentPrefixFiniteMenu

end SymmetricSubgroupAsymptotics
