import SymmetricSubgroupAsymptotics.PrimitiveCompositionBoundedRow

/-! Generated bounded primitive receipt, degrees 28--36.

Source: `certificates/data/primitive_rank.jsonl.gz`, compressed SHA256
`9460b4ec81ac8108c4a41478fe94b4e81fb6b394bb21362205547a97fe882217`.  This chunk contains 79 published PrimGrp locators.
Lean checks every exact 3-adic valuation and every applicable integer bound.
-/

set_option autoImplicit false

namespace SymmetricSubgroupAsymptotics

def primitiveCompositionBoundRows28To36 : Array PrimitiveCompositionBoundRow := #[
  { degree := 28, catalogueIndex := 1,
    groupOrder := 336, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 28, catalogueIndex := 2,
    groupOrder := 504, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 28, catalogueIndex := 3,
    groupOrder := 1512, ternaryValuation := 3,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 28, catalogueIndex := 4,
    groupOrder := 6048, ternaryValuation := 3,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 28, catalogueIndex := 5,
    groupOrder := 12096, ternaryValuation := 3,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 28, catalogueIndex := 6,
    groupOrder := 1451520, ternaryValuation := 4,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 28, catalogueIndex := 7,
    groupOrder := 20160, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 28, catalogueIndex := 8,
    groupOrder := 40320, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 28, catalogueIndex := 9,
    groupOrder := 9828, ternaryValuation := 3,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 28, catalogueIndex := 10,
    groupOrder := 19656, ternaryValuation := 3,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 28, catalogueIndex := 11,
    groupOrder := 29484, ternaryValuation := 4,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 28, catalogueIndex := 12,
    groupOrder := 58968, ternaryValuation := 4,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 28, catalogueIndex := 13,
    groupOrder := 152444172305856930250752000000, ternaryValuation := 13,
    kind := .naturalAlternating, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 28, catalogueIndex := 14,
    groupOrder := 304888344611713860501504000000, ternaryValuation := 13,
    kind := .naturalSymmetric, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 29, catalogueIndex := 1,
    groupOrder := 29, ternaryValuation := 0,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 29, catalogueIndex := 2,
    groupOrder := 58, ternaryValuation := 0,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 29, catalogueIndex := 3,
    groupOrder := 116, ternaryValuation := 0,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 29, catalogueIndex := 4,
    groupOrder := 203, ternaryValuation := 0,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 29, catalogueIndex := 5,
    groupOrder := 406, ternaryValuation := 0,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 29, catalogueIndex := 6,
    groupOrder := 812, ternaryValuation := 0,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 29, catalogueIndex := 7,
    groupOrder := 4420880996869850977271808000000, ternaryValuation := 13,
    kind := .naturalAlternating, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 29, catalogueIndex := 8,
    groupOrder := 8841761993739701954543616000000, ternaryValuation := 13,
    kind := .naturalSymmetric, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 30, catalogueIndex := 1,
    groupOrder := 12180, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 30, catalogueIndex := 2,
    groupOrder := 24360, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 30, catalogueIndex := 3,
    groupOrder := 132626429906095529318154240000000, ternaryValuation := 14,
    kind := .naturalAlternating, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 30, catalogueIndex := 4,
    groupOrder := 265252859812191058636308480000000, ternaryValuation := 14,
    kind := .naturalSymmetric, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 31, catalogueIndex := 1,
    groupOrder := 31, ternaryValuation := 0,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 31, catalogueIndex := 2,
    groupOrder := 62, ternaryValuation := 0,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 31, catalogueIndex := 3,
    groupOrder := 93, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 31, catalogueIndex := 4,
    groupOrder := 155, ternaryValuation := 0,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 31, catalogueIndex := 5,
    groupOrder := 186, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 31, catalogueIndex := 6,
    groupOrder := 310, ternaryValuation := 0,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 31, catalogueIndex := 7,
    groupOrder := 465, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 31, catalogueIndex := 8,
    groupOrder := 930, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 31, catalogueIndex := 9,
    groupOrder := 372000, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 31, catalogueIndex := 10,
    groupOrder := 9999360, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 31, catalogueIndex := 11,
    groupOrder := 4111419327088961408862781440000000, ternaryValuation := 14,
    kind := .naturalAlternating, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 31, catalogueIndex := 12,
    groupOrder := 8222838654177922817725562880000000, ternaryValuation := 14,
    kind := .naturalSymmetric, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 32, catalogueIndex := 1,
    groupOrder := 992, ternaryValuation := 0,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 32, catalogueIndex := 2,
    groupOrder := 4960, ternaryValuation := 0,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 32, catalogueIndex := 3,
    groupOrder := 319979520, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 32, catalogueIndex := 4,
    groupOrder := 14880, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 32, catalogueIndex := 5,
    groupOrder := 29760, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 32, catalogueIndex := 6,
    groupOrder := 131565418466846765083609006080000000, ternaryValuation := 14,
    kind := .naturalAlternating, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 32, catalogueIndex := 7,
    groupOrder := 263130836933693530167218012160000000, ternaryValuation := 14,
    kind := .naturalSymmetric, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 33, catalogueIndex := 1,
    groupOrder := 32736, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 33, catalogueIndex := 2,
    groupOrder := 163680, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 33, catalogueIndex := 3,
    groupOrder := 4341658809405943247759097200640000000, ternaryValuation := 15,
    kind := .naturalAlternating, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 33, catalogueIndex := 4,
    groupOrder := 8683317618811886495518194401280000000, ternaryValuation := 15,
    kind := .naturalSymmetric, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 34, catalogueIndex := 1,
    groupOrder := 147616399519802070423809304821760000000, ternaryValuation := 15,
    kind := .naturalAlternating, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 34, catalogueIndex := 2,
    groupOrder := 295232799039604140847618609643520000000, ternaryValuation := 15,
    kind := .naturalSymmetric, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 35, catalogueIndex := 1,
    groupOrder := 20160, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 35, catalogueIndex := 2,
    groupOrder := 40320, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 35, catalogueIndex := 3,
    groupOrder := 2520, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 35, catalogueIndex := 4,
    groupOrder := 5040, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 35, catalogueIndex := 5,
    groupOrder := 5166573983193072464833325668761600000000, ternaryValuation := 15,
    kind := .naturalAlternating, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 35, catalogueIndex := 6,
    groupOrder := 10333147966386144929666651337523200000000, ternaryValuation := 15,
    kind := .naturalSymmetric, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 36, catalogueIndex := 1,
    groupOrder := 504, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 36, catalogueIndex := 2,
    groupOrder := 1512, ternaryValuation := 3,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 36, catalogueIndex := 3,
    groupOrder := 720, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 36, catalogueIndex := 4,
    groupOrder := 720, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 36, catalogueIndex := 5,
    groupOrder := 1440, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 36, catalogueIndex := 6,
    groupOrder := 6048, ternaryValuation := 3,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 36, catalogueIndex := 7,
    groupOrder := 12096, ternaryValuation := 3,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 36, catalogueIndex := 8,
    groupOrder := 25920, ternaryValuation := 4,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 36, catalogueIndex := 9,
    groupOrder := 51840, ternaryValuation := 4,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 36, catalogueIndex := 10,
    groupOrder := 1451520, ternaryValuation := 4,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 36, catalogueIndex := 11,
    groupOrder := 181440, ternaryValuation := 4,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 36, catalogueIndex := 12,
    groupOrder := 362880, ternaryValuation := 4,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 36, catalogueIndex := 13,
    groupOrder := 259200, ternaryValuation := 4,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 36, catalogueIndex := 14,
    groupOrder := 518400, ternaryValuation := 4,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 36, catalogueIndex := 15,
    groupOrder := 518400, ternaryValuation := 4,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 36, catalogueIndex := 16,
    groupOrder := 1036800, ternaryValuation := 4,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 36, catalogueIndex := 17,
    groupOrder := 7200, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 36, catalogueIndex := 18,
    groupOrder := 14400, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 36, catalogueIndex := 19,
    groupOrder := 14400, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 36, catalogueIndex := 20,
    groupOrder := 28800, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 36, catalogueIndex := 21,
    groupOrder := 185996663394950608733999724075417600000000, ternaryValuation := 17,
    kind := .naturalAlternating, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 36, catalogueIndex := 22,
    groupOrder := 371993326789901217467999448150835200000000, ternaryValuation := 17,
    kind := .naturalSymmetric, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },]

theorem primitiveCompositionBoundRows28To36_size :
    primitiveCompositionBoundRows28To36.size = 79 := by
  decide +kernel

theorem primitiveCompositionBoundRows28To36_locators_nodup :
    (primitiveCompositionBoundRows28To36.toList.map
      PrimitiveCompositionBoundRow.locator).Nodup := by
  decide +kernel

theorem primitiveCompositionBoundRows28To36_degree_range :
    ∀ r ∈ primitiveCompositionBoundRows28To36.toList,
      28 ≤ r.degree ∧ r.degree ≤ 36 := by
  decide +kernel

end SymmetricSubgroupAsymptotics
