import SymmetricSubgroupAsymptotics.PrimitiveBoundedIndexRow

/-!
# Bounded primitive quotient-index rows in degrees 25--29

Generated by `computations/python/export_lean_primitive_bounded_index.py`
from `certificates/data/primitive_rank.jsonl.gz` (compressed SHA256
`9460b4ec81ac8108c4a41478fe94b4e81fb6b394bb21362205547a97fe882217`).  This chunk contains every simple-nonabelian-socle primitive row
in its displayed degree interval.  Lean checks the exact order factorization,
the quotient-index inequality, locator uniqueness, and the degree range.
-/

set_option autoImplicit false

namespace SymmetricSubgroupAsymptotics

/-- The checked rows in degrees 25 through 29. -/
def primitiveBoundedIndexRows25To29 : Array PrimitiveBoundedIndexRow := #[
  { degree := 25, catalogueIndex := 27, groupOrder := 7755605021665492992000000,
    socleOrder := 7755605021665492992000000, outerOrder := 1,
    order_factorization := by norm_num, index_bound := by omega },
  { degree := 25, catalogueIndex := 28, groupOrder := 15511210043330985984000000,
    socleOrder := 7755605021665492992000000, outerOrder := 2,
    order_factorization := by norm_num, index_bound := by omega },
  { degree := 26, catalogueIndex := 1, groupOrder := 7800,
    socleOrder := 7800, outerOrder := 1,
    order_factorization := by norm_num, index_bound := by omega },
  { degree := 26, catalogueIndex := 2, groupOrder := 15600,
    socleOrder := 7800, outerOrder := 2,
    order_factorization := by norm_num, index_bound := by omega },
  { degree := 26, catalogueIndex := 3, groupOrder := 15600,
    socleOrder := 7800, outerOrder := 2,
    order_factorization := by norm_num, index_bound := by omega },
  { degree := 26, catalogueIndex := 4, groupOrder := 15600,
    socleOrder := 7800, outerOrder := 2,
    order_factorization := by norm_num, index_bound := by omega },
  { degree := 26, catalogueIndex := 5, groupOrder := 31200,
    socleOrder := 7800, outerOrder := 4,
    order_factorization := by norm_num, index_bound := by omega },
  { degree := 26, catalogueIndex := 6, groupOrder := 201645730563302817792000000,
    socleOrder := 201645730563302817792000000, outerOrder := 1,
    order_factorization := by norm_num, index_bound := by omega },
  { degree := 26, catalogueIndex := 7, groupOrder := 403291461126605635584000000,
    socleOrder := 201645730563302817792000000, outerOrder := 2,
    order_factorization := by norm_num, index_bound := by omega },
  { degree := 27, catalogueIndex := 12, groupOrder := 25920,
    socleOrder := 25920, outerOrder := 1,
    order_factorization := by norm_num, index_bound := by omega },
  { degree := 27, catalogueIndex := 13, groupOrder := 51840,
    socleOrder := 25920, outerOrder := 2,
    order_factorization := by norm_num, index_bound := by omega },
  { degree := 27, catalogueIndex := 14, groupOrder := 5444434725209176080384000000,
    socleOrder := 5444434725209176080384000000, outerOrder := 1,
    order_factorization := by norm_num, index_bound := by omega },
  { degree := 27, catalogueIndex := 15, groupOrder := 10888869450418352160768000000,
    socleOrder := 5444434725209176080384000000, outerOrder := 2,
    order_factorization := by norm_num, index_bound := by omega },
  { degree := 28, catalogueIndex := 1, groupOrder := 336,
    socleOrder := 168, outerOrder := 2,
    order_factorization := by norm_num, index_bound := by omega },
  { degree := 28, catalogueIndex := 2, groupOrder := 504,
    socleOrder := 504, outerOrder := 1,
    order_factorization := by norm_num, index_bound := by omega },
  { degree := 28, catalogueIndex := 3, groupOrder := 1512,
    socleOrder := 504, outerOrder := 3,
    order_factorization := by norm_num, index_bound := by omega },
  { degree := 28, catalogueIndex := 4, groupOrder := 6048,
    socleOrder := 6048, outerOrder := 1,
    order_factorization := by norm_num, index_bound := by omega },
  { degree := 28, catalogueIndex := 5, groupOrder := 12096,
    socleOrder := 6048, outerOrder := 2,
    order_factorization := by norm_num, index_bound := by omega },
  { degree := 28, catalogueIndex := 6, groupOrder := 1451520,
    socleOrder := 1451520, outerOrder := 1,
    order_factorization := by norm_num, index_bound := by omega },
  { degree := 28, catalogueIndex := 7, groupOrder := 20160,
    socleOrder := 20160, outerOrder := 1,
    order_factorization := by norm_num, index_bound := by omega },
  { degree := 28, catalogueIndex := 8, groupOrder := 40320,
    socleOrder := 20160, outerOrder := 2,
    order_factorization := by norm_num, index_bound := by omega },
  { degree := 28, catalogueIndex := 9, groupOrder := 9828,
    socleOrder := 9828, outerOrder := 1,
    order_factorization := by norm_num, index_bound := by omega },
  { degree := 28, catalogueIndex := 10, groupOrder := 19656,
    socleOrder := 9828, outerOrder := 2,
    order_factorization := by norm_num, index_bound := by omega },
  { degree := 28, catalogueIndex := 11, groupOrder := 29484,
    socleOrder := 9828, outerOrder := 3,
    order_factorization := by norm_num, index_bound := by omega },
  { degree := 28, catalogueIndex := 12, groupOrder := 58968,
    socleOrder := 9828, outerOrder := 6,
    order_factorization := by norm_num, index_bound := by omega },
  { degree := 28, catalogueIndex := 13, groupOrder := 152444172305856930250752000000,
    socleOrder := 152444172305856930250752000000, outerOrder := 1,
    order_factorization := by norm_num, index_bound := by omega },
  { degree := 28, catalogueIndex := 14, groupOrder := 304888344611713860501504000000,
    socleOrder := 152444172305856930250752000000, outerOrder := 2,
    order_factorization := by norm_num, index_bound := by omega },
  { degree := 29, catalogueIndex := 7, groupOrder := 4420880996869850977271808000000,
    socleOrder := 4420880996869850977271808000000, outerOrder := 1,
    order_factorization := by norm_num, index_bound := by omega },
  { degree := 29, catalogueIndex := 8, groupOrder := 8841761993739701954543616000000,
    socleOrder := 4420880996869850977271808000000, outerOrder := 2,
    order_factorization := by norm_num, index_bound := by omega },]

theorem primitiveBoundedIndexRows25To29_size :
    primitiveBoundedIndexRows25To29.size = 29 := by
  decide +kernel

theorem primitiveBoundedIndexRows25To29_locators_nodup :
    (primitiveBoundedIndexRows25To29.toList.map
      PrimitiveBoundedIndexRow.locator).Nodup := by
  decide +kernel

theorem primitiveBoundedIndexRows25To29_degree_range
    (row : PrimitiveBoundedIndexRow)
    (hrow : row ∈ primitiveBoundedIndexRows25To29.toList) :
    25 ≤ row.degree ∧ row.degree ≤ 29 := by
  revert row
  decide +kernel

end SymmetricSubgroupAsymptotics
