import SymmetricSubgroupAsymptotics.PrimeRelativeRadicalGenerators

/-! Original generator tests for the absolute prime-evaluation kernel.
The top relative radical is the same literal subgroup of G as that kernel.
Consequently generator p-th powers in G' make the evaluation kernel equal
to G', without finiteness, a p-group hypothesis, or a Cayley enumeration. -/
set_option autoImplicit false
noncomputable section

namespace SymmetricSubgroupAsymptotics

variable (p : ℕ) [Fact p.Prime] {G ι : Type*} [Group G]

/-- Pullback through the actual top-subgroup equivalence retains every
relative character, so no additional character vanishing is assumed. -/
theorem primeAbelianizationGroupMap_ker_eq_relativeRadical_top :
    (primeAbelianizationGroupMap p G).ker =
      primeRelativeRadical p (⊤ : Subgroup G) := by
  apply le_antisymm
  · intro x hx
    apply (mem_primeRelativeRadical_iff p (⊤ : Subgroup G) x).mpr
    refine ⟨Subgroup.mem_top x, ?_⟩
    intro χ
    let ψ : PrimeCharacters p G := χ.1.comp
      (Subgroup.topEquiv : (⊤ : Subgroup G) ≃* G).symm.toMonoidHom.toAdditive
    have heval : primeAbelianizationMap p G (Additive.ofMul x) = 0 := hx
    exact congrArg (fun z : PrimeAbelianization p G => z ψ) heval
  · exact primeRelativeRadical_le_ambient_evaluation_ker p (⊤ : Subgroup G)

/-- The absolute kernel is generated by the displayed original p-th
powers and the full original derived subgroup. -/
theorem primeAbelianizationGroupMap_ker_eq_generated_powers_sup_commutator
    (generators : ι → G)
    (hgen : Subgroup.closure (Set.range generators) = ⊤) :
    (primeAbelianizationGroupMap p G).ker =
      Subgroup.closure (Set.range (fun i => (generators i)^p)) ⊔ commutator G := by
  rw [primeAbelianizationGroupMap_ker_eq_relativeRadical_top]
  exact primeRelativeRadical_eq_ambient_generator_pow_commutator
    p (⊤ : Subgroup G) generators hgen

/-- Tiny word certificates placing each original generator power in G'
identify the whole evaluation kernel, rather than merely its order. -/
theorem primeAbelianizationGroupMap_ker_eq_commutator_of_generator_powers
    (generators : ι → G)
    (hgen : Subgroup.closure (Set.range generators) = ⊤)
    (hpowers : ∀ i, (generators i)^p ∈ commutator G) :
    (primeAbelianizationGroupMap p G).ker = commutator G := by
  rw [primeAbelianizationGroupMap_ker_eq_generated_powers_sup_commutator p generators hgen]
  apply sup_eq_right.mpr
  apply (Subgroup.closure_le _).mpr
  rintro _ ⟨i, rfl⟩
  exact hpowers i

/-- Involutory generators are the p=2 instance of this original-source
criterion. Only their displayed powers must be checked. -/
theorem primeAbelianizationGroupMap_ker_eq_commutator_of_generator_orders
    (generators : ι → G)
    (hgen : Subgroup.closure (Set.range generators) = ⊤)
    (hpowers : ∀ i, (generators i)^p = 1) :
    (primeAbelianizationGroupMap p G).ker = commutator G := by
  apply primeAbelianizationGroupMap_ker_eq_commutator_of_generator_powers
    p generators hgen
  intro i
  rw [hpowers i]
  exact (commutator G).one_mem

end SymmetricSubgroupAsymptotics
