import SymmetricSubgroupAsymptotics.PrimitiveCompositionBoundedRow

/-! Generated bounded primitive receipt, degrees 37--44.

Source: `certificates/data/primitive_rank.jsonl.gz`, compressed SHA256
`9460b4ec81ac8108c4a41478fe94b4e81fb6b394bb21362205547a97fe882217`.  This chunk contains 53 published PrimGrp locators.
Lean checks every exact 3-adic valuation and every applicable integer bound.
-/

set_option autoImplicit false

namespace SymmetricSubgroupAsymptotics

def primitiveCompositionBoundRows37To44 : Array PrimitiveCompositionBoundRow := #[
  { degree := 37, catalogueIndex := 1,
    groupOrder := 37, ternaryValuation := 0,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 37, catalogueIndex := 2,
    groupOrder := 74, ternaryValuation := 0,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 37, catalogueIndex := 3,
    groupOrder := 111, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 37, catalogueIndex := 4,
    groupOrder := 148, ternaryValuation := 0,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 37, catalogueIndex := 5,
    groupOrder := 222, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 37, catalogueIndex := 6,
    groupOrder := 333, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 37, catalogueIndex := 7,
    groupOrder := 444, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 37, catalogueIndex := 8,
    groupOrder := 666, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 37, catalogueIndex := 9,
    groupOrder := 1332, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 37, catalogueIndex := 10,
    groupOrder := 6881876545613172523157989790790451200000000, ternaryValuation := 17,
    kind := .naturalAlternating, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 37, catalogueIndex := 11,
    groupOrder := 13763753091226345046315979581580902400000000, ternaryValuation := 17,
    kind := .naturalSymmetric, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 38, catalogueIndex := 1,
    groupOrder := 25308, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 38, catalogueIndex := 2,
    groupOrder := 50616, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 38, catalogueIndex := 3,
    groupOrder := 261511308733300555880003612050037145600000000, ternaryValuation := 17,
    kind := .naturalAlternating, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 38, catalogueIndex := 4,
    groupOrder := 523022617466601111760007224100074291200000000, ternaryValuation := 17,
    kind := .naturalSymmetric, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 39, catalogueIndex := 1,
    groupOrder := 10198941040598721679320140869951448678400000000, ternaryValuation := 18,
    kind := .naturalAlternating, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 39, catalogueIndex := 2,
    groupOrder := 20397882081197443358640281739902897356800000000, ternaryValuation := 18,
    kind := .naturalSymmetric, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 40, catalogueIndex := 1,
    groupOrder := 25920, ternaryValuation := 4,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 40, catalogueIndex := 2,
    groupOrder := 51840, ternaryValuation := 4,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 40, catalogueIndex := 3,
    groupOrder := 25920, ternaryValuation := 4,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 40, catalogueIndex := 4,
    groupOrder := 51840, ternaryValuation := 4,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 40, catalogueIndex := 5,
    groupOrder := 6065280, ternaryValuation := 6,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 40, catalogueIndex := 6,
    groupOrder := 12130560, ternaryValuation := 6,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 40, catalogueIndex := 7,
    groupOrder := 407957641623948867172805634798057947136000000000, ternaryValuation := 18,
    kind := .naturalAlternating, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 40, catalogueIndex := 8,
    groupOrder := 815915283247897734345611269596115894272000000000, ternaryValuation := 18,
    kind := .naturalSymmetric, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 41, catalogueIndex := 1,
    groupOrder := 41, ternaryValuation := 0,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 41, catalogueIndex := 2,
    groupOrder := 82, ternaryValuation := 0,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 41, catalogueIndex := 3,
    groupOrder := 164, ternaryValuation := 0,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 41, catalogueIndex := 4,
    groupOrder := 205, ternaryValuation := 0,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 41, catalogueIndex := 5,
    groupOrder := 328, ternaryValuation := 0,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 41, catalogueIndex := 6,
    groupOrder := 410, ternaryValuation := 0,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 41, catalogueIndex := 7,
    groupOrder := 820, ternaryValuation := 0,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 41, catalogueIndex := 8,
    groupOrder := 1640, ternaryValuation := 0,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 41, catalogueIndex := 9,
    groupOrder := 16726263306581903554085031026720375832576000000000, ternaryValuation := 18,
    kind := .naturalAlternating, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 41, catalogueIndex := 10,
    groupOrder := 33452526613163807108170062053440751665152000000000, ternaryValuation := 18,
    kind := .naturalSymmetric, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 42, catalogueIndex := 1,
    groupOrder := 34440, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 42, catalogueIndex := 2,
    groupOrder := 68880, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 42, catalogueIndex := 3,
    groupOrder := 702503058876439949271571303122255784968192000000000, ternaryValuation := 19,
    kind := .naturalAlternating, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 42, catalogueIndex := 4,
    groupOrder := 1405006117752879898543142606244511569936384000000000, ternaryValuation := 19,
    kind := .naturalSymmetric, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 43, catalogueIndex := 1,
    groupOrder := 43, ternaryValuation := 0,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 43, catalogueIndex := 2,
    groupOrder := 86, ternaryValuation := 0,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 43, catalogueIndex := 3,
    groupOrder := 129, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 43, catalogueIndex := 4,
    groupOrder := 258, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 43, catalogueIndex := 5,
    groupOrder := 301, ternaryValuation := 0,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 43, catalogueIndex := 6,
    groupOrder := 602, ternaryValuation := 0,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 43, catalogueIndex := 7,
    groupOrder := 903, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 43, catalogueIndex := 8,
    groupOrder := 1806, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 43, catalogueIndex := 9,
    groupOrder := 30207631531686917818677566034256998753632256000000000, ternaryValuation := 19,
    kind := .naturalAlternating, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 43, catalogueIndex := 10,
    groupOrder := 60415263063373835637355132068513997507264512000000000, ternaryValuation := 19,
    kind := .naturalSymmetric, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 44, catalogueIndex := 1,
    groupOrder := 39732, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 44, catalogueIndex := 2,
    groupOrder := 79464, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 44, catalogueIndex := 3,
    groupOrder := 1329135787394224384021812905507307945159819264000000000, ternaryValuation := 19,
    kind := .naturalAlternating, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 44, catalogueIndex := 4,
    groupOrder := 2658271574788448768043625811014615890319638528000000000, ternaryValuation := 19,
    kind := .naturalSymmetric, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },]

theorem primitiveCompositionBoundRows37To44_size :
    primitiveCompositionBoundRows37To44.size = 53 := by
  decide +kernel

theorem primitiveCompositionBoundRows37To44_locators_nodup :
    (primitiveCompositionBoundRows37To44.toList.map
      PrimitiveCompositionBoundRow.locator).Nodup := by
  decide +kernel

theorem primitiveCompositionBoundRows37To44_degree_range :
    ∀ r ∈ primitiveCompositionBoundRows37To44.toList,
      37 ≤ r.degree ∧ r.degree ≤ 44 := by
  decide +kernel

end SymmetricSubgroupAsymptotics
