import SymmetricSubgroupAsymptotics.PrimitiveCompositionBoundedRow

/-! Generated bounded primitive receipt, degrees 2--11.

Source: `certificates/data/primitive_rank.jsonl.gz`, compressed SHA256
`9460b4ec81ac8108c4a41478fe94b4e81fb6b394bb21362205547a97fe882217`.  This chunk contains 56 published PrimGrp locators.
Lean checks every exact 3-adic valuation and every applicable integer bound.
-/

set_option autoImplicit false

namespace SymmetricSubgroupAsymptotics

def primitiveCompositionBoundRows2To11 : Array PrimitiveCompositionBoundRow := #[
  { degree := 2, catalogueIndex := 1,
    groupOrder := 2, ternaryValuation := 0,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 3, catalogueIndex := 1,
    groupOrder := 3, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 3, catalogueIndex := 2,
    groupOrder := 6, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 4, catalogueIndex := 1,
    groupOrder := 12, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 4, catalogueIndex := 2,
    groupOrder := 24, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 5, catalogueIndex := 1,
    groupOrder := 5, ternaryValuation := 0,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 5, catalogueIndex := 2,
    groupOrder := 10, ternaryValuation := 0,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 5, catalogueIndex := 3,
    groupOrder := 20, ternaryValuation := 0,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 5, catalogueIndex := 4,
    groupOrder := 60, ternaryValuation := 1,
    kind := .naturalAlternating, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 5, catalogueIndex := 5,
    groupOrder := 120, ternaryValuation := 1,
    kind := .naturalSymmetric, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 6, catalogueIndex := 1,
    groupOrder := 60, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 6, catalogueIndex := 2,
    groupOrder := 120, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 6, catalogueIndex := 3,
    groupOrder := 360, ternaryValuation := 2,
    kind := .naturalAlternating, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 6, catalogueIndex := 4,
    groupOrder := 720, ternaryValuation := 2,
    kind := .naturalSymmetric, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 7, catalogueIndex := 1,
    groupOrder := 7, ternaryValuation := 0,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 7, catalogueIndex := 2,
    groupOrder := 14, ternaryValuation := 0,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 7, catalogueIndex := 3,
    groupOrder := 21, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 7, catalogueIndex := 4,
    groupOrder := 42, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 7, catalogueIndex := 5,
    groupOrder := 168, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 7, catalogueIndex := 6,
    groupOrder := 2520, ternaryValuation := 2,
    kind := .naturalAlternating, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 7, catalogueIndex := 7,
    groupOrder := 5040, ternaryValuation := 2,
    kind := .naturalSymmetric, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 8, catalogueIndex := 1,
    groupOrder := 56, ternaryValuation := 0,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 8, catalogueIndex := 2,
    groupOrder := 168, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 8, catalogueIndex := 3,
    groupOrder := 1344, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 8, catalogueIndex := 4,
    groupOrder := 168, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 8, catalogueIndex := 5,
    groupOrder := 336, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 8, catalogueIndex := 6,
    groupOrder := 20160, ternaryValuation := 2,
    kind := .naturalAlternating, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 8, catalogueIndex := 7,
    groupOrder := 40320, ternaryValuation := 2,
    kind := .naturalSymmetric, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 9, catalogueIndex := 1,
    groupOrder := 36, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 9, catalogueIndex := 2,
    groupOrder := 72, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 9, catalogueIndex := 3,
    groupOrder := 72, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 9, catalogueIndex := 4,
    groupOrder := 72, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 9, catalogueIndex := 5,
    groupOrder := 144, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 9, catalogueIndex := 6,
    groupOrder := 216, ternaryValuation := 3,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 9, catalogueIndex := 7,
    groupOrder := 432, ternaryValuation := 3,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 9, catalogueIndex := 8,
    groupOrder := 504, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 9, catalogueIndex := 9,
    groupOrder := 1512, ternaryValuation := 3,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 9, catalogueIndex := 10,
    groupOrder := 181440, ternaryValuation := 4,
    kind := .naturalAlternating, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 9, catalogueIndex := 11,
    groupOrder := 362880, ternaryValuation := 4,
    kind := .naturalSymmetric, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 10, catalogueIndex := 1,
    groupOrder := 60, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 10, catalogueIndex := 2,
    groupOrder := 120, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 10, catalogueIndex := 3,
    groupOrder := 360, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 10, catalogueIndex := 4,
    groupOrder := 720, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 10, catalogueIndex := 5,
    groupOrder := 720, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 10, catalogueIndex := 6,
    groupOrder := 720, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 10, catalogueIndex := 7,
    groupOrder := 1440, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 10, catalogueIndex := 8,
    groupOrder := 1814400, ternaryValuation := 4,
    kind := .naturalAlternating, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 10, catalogueIndex := 9,
    groupOrder := 3628800, ternaryValuation := 4,
    kind := .naturalSymmetric, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 11, catalogueIndex := 1,
    groupOrder := 11, ternaryValuation := 0,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 11, catalogueIndex := 2,
    groupOrder := 22, ternaryValuation := 0,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 11, catalogueIndex := 3,
    groupOrder := 55, ternaryValuation := 0,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 11, catalogueIndex := 4,
    groupOrder := 110, ternaryValuation := 0,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 11, catalogueIndex := 5,
    groupOrder := 660, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 11, catalogueIndex := 6,
    groupOrder := 7920, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 11, catalogueIndex := 7,
    groupOrder := 19958400, ternaryValuation := 4,
    kind := .naturalAlternating, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 11, catalogueIndex := 8,
    groupOrder := 39916800, ternaryValuation := 4,
    kind := .naturalSymmetric, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },]

theorem primitiveCompositionBoundRows2To11_size :
    primitiveCompositionBoundRows2To11.size = 56 := by
  decide +kernel

theorem primitiveCompositionBoundRows2To11_locators_nodup :
    (primitiveCompositionBoundRows2To11.toList.map
      PrimitiveCompositionBoundRow.locator).Nodup := by
  decide +kernel

theorem primitiveCompositionBoundRows2To11_degree_range :
    ∀ r ∈ primitiveCompositionBoundRows2To11.toList,
      2 ≤ r.degree ∧ r.degree ≤ 11 := by
  decide +kernel

end SymmetricSubgroupAsymptotics
