import SymmetricSubgroupAsymptotics.PrimeDerivedCrossingCharacters
import SymmetricSubgroupAsymptotics.PrimeRelativeCharacterDetection

/-! Actual mixed commutators of crossing original normal subgroups.
Pair separation bounds the complete character space vanishing on [N,G].
When the relative radical lies in [N,G], complete detection recovers the
exact equality [N,G]=N∩G'. A separate corollary obtains that containment
from whole-original-group normal-subgroup comparability and at least two
dimensions of actual invariant derived characters. -/
set_option autoImplicit false
noncomputable section
open scoped commutatorElement

namespace SymmetricSubgroupAsymptotics

variable (p : ℕ) [Fact p.Prime] {G : Type*} [Group G] [Finite G]
    (hker : (primeAbelianizationGroupMap p G).ker = commutator G)

/-- Vanishing on the actual subgroup generated by the original mixed
commutators annihilates every direction in the actual image of N. -/
theorem derivedCharactersVanishingOn_mixedCommutator_le_joint
    (N : Subgroup G) :
    derivedCharactersVanishingOn p ⁅N, (⊤ : Subgroup G)⁆ ≤
      linearJointAnnihilator (derivedEvaluationBilinearMap p hker)
        (primeDerivedImage p N) := by
  intro χ hχ v hv
  obtain ⟨n, rfl⟩ := (mem_primeDerivedImage_iff p N v).mp hv
  change derivedEvaluationBilinear p hker χ
    (primeAbelianizationMap p G (Additive.ofMul (n : G))) = 0
  apply LinearMap.ext
  intro w
  obtain ⟨g, rfl⟩ := primeAbelianizationMap_surjective p G w
  change derivedEvaluationBilinear p hker χ
    (primeAbelianizationMap p G (Additive.ofMul (n : G)))
    (primeAbelianizationMap p G (Additive.ofMul g.toMul)) = 0
  rw [derivedEvaluationBilinear_eval]
  exact hχ (derivedCommutatorElement (n : G) g.toMul)
    (Subgroup.commutator_mem_commutator n.2 (Subgroup.mem_top g.toMul))

variable (hpair : ∀ v : Fin 2 → primeRelativeCharacters p (commutator G),
    LinearIndependent (ZMod p) v →
      (derivedEvaluationBilinearMap p hker (v 0)).ker ⊓
        (derivedEvaluationBilinearMap p hker (v 1)).ker = ⊥)
include hker hpair

theorem derivedCharactersVanishingOn_mixedCommutator_finrank_le_one
    (N : Subgroup G) (hnotND : ¬N ≤ commutator G) :
    Module.finrank (ZMod p)
      (derivedCharactersVanishingOn p ⁅N, (⊤ : Subgroup G)⁆) ≤ 1 := by
  have hW : primeDerivedImage p N ≠ ⊥ := by
    intro hz
    exact hnotND ((primeDerivedImage_eq_bot_iff_le_commutator p hker N).mp hz)
  exact (Submodule.finrank_mono
    (derivedCharactersVanishingOn_mixedCommutator_le_joint p hker N)).trans
      (linearJointAnnihilator_finrank_le_one
        (derivedEvaluationBilinearMap p hker) (primeDerivedImage p N) hpair hW)

/-- With at least two original invariant derived characters, the mixed
commutator subgroup of any N not contained in G' cannot lie in R_D. -/
theorem mixedCommutator_not_le_primeRelativeRadical
    (hE : 2 ≤ Module.finrank (ZMod p) (primeRelativeCharacters p (commutator G)))
    (N : Subgroup G) (hnotND : ¬N ≤ commutator G) :
    ¬⁅N, (⊤ : Subgroup G)⁆ ≤ primeRelativeRadical p (commutator G) := by
  intro hMR
  have hle := derivedCharactersVanishingOn_mixedCommutator_finrank_le_one
    p hker hpair N hnotND
  rw [derivedCharactersVanishingOn_eq_top_of_le_radical p _ hMR, finrank_top] at hle
  exact (Nat.not_succ_le_self 1) (hE.trans hle)

/-- Once the actual relative radical is contained in [N,G], crossing
forces [N,G] to be the entire actual derived intersection. -/
theorem derivedCrossing_mixedCommutator_eq_of_radical_le
    (hG : IsPGroup p G) (N : Subgroup G) [N.Normal]
    (hnotND : ¬N ≤ commutator G) (hnotDN : ¬commutator G ≤ N)
    (hRM : primeRelativeRadical p (commutator G) ≤ ⁅N, (⊤ : Subgroup G)⁆) :
    ⁅N, (⊤ : Subgroup G)⁆ = N ⊓ commutator G := by
  have hMB : ⁅N, (⊤ : Subgroup G)⁆ ≤ N ⊓ commutator G :=
    le_inf (Subgroup.commutator_le_left N ⊤)
      (Subgroup.commutator_mono le_top le_rfl)
  have hMD : ⁅N, (⊤ : Subgroup G)⁆ ≤ commutator G := hMB.trans inf_le_right
  have hspaces_le : derivedCharactersVanishingOn p (N ⊓ commutator G) ≤
      derivedCharactersVanishingOn p ⁅N, (⊤ : Subgroup G)⁆ := by
    intro χ hχ d hd
    exact hχ d (hMB hd)
  have hdimB := derivedCharactersVanishingOn_finrank_eq_one_of_crossing
    p hker hG hpair N hnotND hnotDN
  have hdimM : Module.finrank (ZMod p)
      (derivedCharactersVanishingOn p ⁅N, (⊤ : Subgroup G)⁆) = 1 := by
    apply le_antisymm
      (derivedCharactersVanishingOn_mixedCommutator_finrank_le_one p hker hpair N hnotND)
    rw [← hdimB]
    exact Submodule.finrank_mono hspaces_le
  have hspaces : derivedCharactersVanishingOn p (N ⊓ commutator G) =
      derivedCharactersVanishingOn p ⁅N, (⊤ : Subgroup G)⁆ :=
    Submodule.eq_of_le_of_finrank_eq hspaces_le (hdimB.trans hdimM.symm)
  apply le_antisymm hMB
  intro b hb
  have hj : b ∈ ⁅N, (⊤ : Subgroup G)⁆ ⊔ primeRelativeRadical p (commutator G) := by
    apply (mem_sup_primeRelativeRadical_iff p (commutator G)
      ⁅N, (⊤ : Subgroup G)⁆ hMD ⟨b, hb.2⟩).mpr
    intro χ hχ
    change χ ∈ derivedCharactersVanishingOn p ⁅N, (⊤ : Subgroup G)⁆ at hχ
    rw [← hspaces] at hχ
    exact hχ ⟨b, hb.2⟩ hb
  simpa only [sup_eq_left.mpr hRM] using hj

/-- Whole-G normal comparability inside the original derived subgroup
supplies the required radical containment. It is an explicit genuine input,
and may be installed by a finite original-commutator saturation certificate. -/
theorem derivedCrossing_mixedCommutator_eq_of_normal_comparability
    (hG : IsPGroup p G)
    (hE : 2 ≤ Module.finrank (ZMod p) (primeRelativeCharacters p (commutator G)))
    (hcompare : ∀ (M : Subgroup G) [M.Normal], M ≤ commutator G →
      M ≤ primeRelativeRadical p (commutator G) ∨ primeRelativeRadical p (commutator G) ≤ M)
    (N : Subgroup G) [N.Normal]
    (hnotND : ¬N ≤ commutator G) (hnotDN : ¬commutator G ≤ N) :
    ⁅N, (⊤ : Subgroup G)⁆ = N ⊓ commutator G := by
  have hMD : ⁅N, (⊤ : Subgroup G)⁆ ≤ commutator G :=
    Subgroup.commutator_mono le_top le_rfl
  rcases hcompare ⁅N, (⊤ : Subgroup G)⁆ hMD with hMR | hRM
  · exact False.elim
      (mixedCommutator_not_le_primeRelativeRadical p hker hpair hE N hnotND hMR)
  · exact derivedCrossing_mixedCommutator_eq_of_radical_le
      p hker hpair hG N hnotND hnotDN hRM

end SymmetricSubgroupAsymptotics
