import SymmetricSubgroupAsymptotics.PrimitiveCompositionBoundedRow

/-! Generated bounded primitive receipt, degrees 21--27.

Source: `certificates/data/primitive_rank.jsonl.gz`, compressed SHA256
`9460b4ec81ac8108c4a41478fe94b4e81fb6b394bb21362205547a97fe882217`.  This chunk contains 75 published PrimGrp locators.
Lean checks every exact 3-adic valuation and every applicable integer bound.
-/

set_option autoImplicit false

namespace SymmetricSubgroupAsymptotics

def primitiveCompositionBoundRows21To27 : Array PrimitiveCompositionBoundRow := #[
  { degree := 21, catalogueIndex := 1,
    groupOrder := 336, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 21, catalogueIndex := 2,
    groupOrder := 2520, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 21, catalogueIndex := 3,
    groupOrder := 5040, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 21, catalogueIndex := 4,
    groupOrder := 20160, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 21, catalogueIndex := 5,
    groupOrder := 40320, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 21, catalogueIndex := 6,
    groupOrder := 60480, ternaryValuation := 3,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 21, catalogueIndex := 7,
    groupOrder := 120960, ternaryValuation := 3,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 21, catalogueIndex := 8,
    groupOrder := 25545471085854720000, ternaryValuation := 9,
    kind := .naturalAlternating, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 21, catalogueIndex := 9,
    groupOrder := 51090942171709440000, ternaryValuation := 9,
    kind := .naturalSymmetric, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 22, catalogueIndex := 1,
    groupOrder := 443520, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 22, catalogueIndex := 2,
    groupOrder := 887040, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 22, catalogueIndex := 3,
    groupOrder := 562000363888803840000, ternaryValuation := 9,
    kind := .naturalAlternating, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 22, catalogueIndex := 4,
    groupOrder := 1124000727777607680000, ternaryValuation := 9,
    kind := .naturalSymmetric, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 23, catalogueIndex := 1,
    groupOrder := 23, ternaryValuation := 0,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 23, catalogueIndex := 2,
    groupOrder := 46, ternaryValuation := 0,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 23, catalogueIndex := 3,
    groupOrder := 253, ternaryValuation := 0,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 23, catalogueIndex := 4,
    groupOrder := 506, ternaryValuation := 0,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 23, catalogueIndex := 5,
    groupOrder := 10200960, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 23, catalogueIndex := 6,
    groupOrder := 12926008369442488320000, ternaryValuation := 9,
    kind := .naturalAlternating, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 23, catalogueIndex := 7,
    groupOrder := 25852016738884976640000, ternaryValuation := 9,
    kind := .naturalSymmetric, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 24, catalogueIndex := 1,
    groupOrder := 244823040, ternaryValuation := 3,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 24, catalogueIndex := 2,
    groupOrder := 6072, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 24, catalogueIndex := 3,
    groupOrder := 12144, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 24, catalogueIndex := 4,
    groupOrder := 310224200866619719680000, ternaryValuation := 10,
    kind := .naturalAlternating, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 24, catalogueIndex := 5,
    groupOrder := 620448401733239439360000, ternaryValuation := 10,
    kind := .naturalSymmetric, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 25, catalogueIndex := 1,
    groupOrder := 75, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 25, catalogueIndex := 2,
    groupOrder := 150, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 25, catalogueIndex := 3,
    groupOrder := 150, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 25, catalogueIndex := 4,
    groupOrder := 200, ternaryValuation := 0,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 25, catalogueIndex := 5,
    groupOrder := 200, ternaryValuation := 0,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 25, catalogueIndex := 6,
    groupOrder := 200, ternaryValuation := 0,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 25, catalogueIndex := 7,
    groupOrder := 300, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 25, catalogueIndex := 8,
    groupOrder := 300, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 25, catalogueIndex := 9,
    groupOrder := 300, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 25, catalogueIndex := 10,
    groupOrder := 400, ternaryValuation := 0,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 25, catalogueIndex := 11,
    groupOrder := 400, ternaryValuation := 0,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 25, catalogueIndex := 12,
    groupOrder := 600, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 25, catalogueIndex := 13,
    groupOrder := 600, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 25, catalogueIndex := 14,
    groupOrder := 600, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 25, catalogueIndex := 15,
    groupOrder := 600, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 25, catalogueIndex := 16,
    groupOrder := 800, ternaryValuation := 0,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 25, catalogueIndex := 17,
    groupOrder := 1200, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 25, catalogueIndex := 18,
    groupOrder := 1200, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 25, catalogueIndex := 19,
    groupOrder := 2400, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 25, catalogueIndex := 20,
    groupOrder := 3000, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 25, catalogueIndex := 21,
    groupOrder := 6000, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 25, catalogueIndex := 22,
    groupOrder := 12000, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 25, catalogueIndex := 23,
    groupOrder := 7200, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 25, catalogueIndex := 24,
    groupOrder := 14400, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 25, catalogueIndex := 25,
    groupOrder := 14400, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 25, catalogueIndex := 26,
    groupOrder := 28800, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 25, catalogueIndex := 27,
    groupOrder := 7755605021665492992000000, ternaryValuation := 10,
    kind := .naturalAlternating, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 25, catalogueIndex := 28,
    groupOrder := 15511210043330985984000000, ternaryValuation := 10,
    kind := .naturalSymmetric, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 26, catalogueIndex := 1,
    groupOrder := 7800, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 26, catalogueIndex := 2,
    groupOrder := 15600, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 26, catalogueIndex := 3,
    groupOrder := 15600, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 26, catalogueIndex := 4,
    groupOrder := 15600, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 26, catalogueIndex := 5,
    groupOrder := 31200, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 26, catalogueIndex := 6,
    groupOrder := 201645730563302817792000000, ternaryValuation := 10,
    kind := .naturalAlternating, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 26, catalogueIndex := 7,
    groupOrder := 403291461126605635584000000, ternaryValuation := 10,
    kind := .naturalSymmetric, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 27, catalogueIndex := 1,
    groupOrder := 324, ternaryValuation := 4,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 27, catalogueIndex := 2,
    groupOrder := 351, ternaryValuation := 3,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 27, catalogueIndex := 3,
    groupOrder := 648, ternaryValuation := 4,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 27, catalogueIndex := 4,
    groupOrder := 648, ternaryValuation := 4,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 27, catalogueIndex := 5,
    groupOrder := 648, ternaryValuation := 4,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 27, catalogueIndex := 6,
    groupOrder := 702, ternaryValuation := 3,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 27, catalogueIndex := 7,
    groupOrder := 1053, ternaryValuation := 4,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 27, catalogueIndex := 8,
    groupOrder := 1296, ternaryValuation := 4,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 27, catalogueIndex := 9,
    groupOrder := 2106, ternaryValuation := 4,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 27, catalogueIndex := 10,
    groupOrder := 151632, ternaryValuation := 6,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 27, catalogueIndex := 11,
    groupOrder := 303264, ternaryValuation := 6,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 27, catalogueIndex := 12,
    groupOrder := 25920, ternaryValuation := 4,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 27, catalogueIndex := 13,
    groupOrder := 51840, ternaryValuation := 4,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 27, catalogueIndex := 14,
    groupOrder := 5444434725209176080384000000, ternaryValuation := 13,
    kind := .naturalAlternating, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 27, catalogueIndex := 15,
    groupOrder := 10888869450418352160768000000, ternaryValuation := 13,
    kind := .naturalSymmetric, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },]

theorem primitiveCompositionBoundRows21To27_size :
    primitiveCompositionBoundRows21To27.size = 75 := by
  decide +kernel

theorem primitiveCompositionBoundRows21To27_locators_nodup :
    (primitiveCompositionBoundRows21To27.toList.map
      PrimitiveCompositionBoundRow.locator).Nodup := by
  decide +kernel

theorem primitiveCompositionBoundRows21To27_degree_range :
    ∀ r ∈ primitiveCompositionBoundRows21To27.toList,
      21 ≤ r.degree ∧ r.degree ≤ 27 := by
  decide +kernel

end SymmetricSubgroupAsymptotics
