import SymmetricSubgroupAsymptotics.PrimitiveCompositionBoundedRow

/-! Generated bounded primitive receipt, degrees 12--20.

Source: `certificates/data/primitive_rank.jsonl.gz`, compressed SHA256
`9460b4ec81ac8108c4a41478fe94b4e81fb6b394bb21362205547a97fe882217`.  This chunk contains 73 published PrimGrp locators.
Lean checks every exact 3-adic valuation and every applicable integer bound.
-/

set_option autoImplicit false

namespace SymmetricSubgroupAsymptotics

def primitiveCompositionBoundRows12To20 : Array PrimitiveCompositionBoundRow := #[
  { degree := 12, catalogueIndex := 1,
    groupOrder := 7920, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 12, catalogueIndex := 2,
    groupOrder := 95040, ternaryValuation := 3,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 12, catalogueIndex := 3,
    groupOrder := 660, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 12, catalogueIndex := 4,
    groupOrder := 1320, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 12, catalogueIndex := 5,
    groupOrder := 239500800, ternaryValuation := 5,
    kind := .naturalAlternating, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 12, catalogueIndex := 6,
    groupOrder := 479001600, ternaryValuation := 5,
    kind := .naturalSymmetric, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 13, catalogueIndex := 1,
    groupOrder := 13, ternaryValuation := 0,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 13, catalogueIndex := 2,
    groupOrder := 26, ternaryValuation := 0,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 13, catalogueIndex := 3,
    groupOrder := 39, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 13, catalogueIndex := 4,
    groupOrder := 52, ternaryValuation := 0,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 13, catalogueIndex := 5,
    groupOrder := 78, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 13, catalogueIndex := 6,
    groupOrder := 156, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 13, catalogueIndex := 7,
    groupOrder := 5616, ternaryValuation := 3,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 13, catalogueIndex := 8,
    groupOrder := 3113510400, ternaryValuation := 5,
    kind := .naturalAlternating, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 13, catalogueIndex := 9,
    groupOrder := 6227020800, ternaryValuation := 5,
    kind := .naturalSymmetric, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 14, catalogueIndex := 1,
    groupOrder := 1092, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 14, catalogueIndex := 2,
    groupOrder := 2184, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 14, catalogueIndex := 3,
    groupOrder := 43589145600, ternaryValuation := 5,
    kind := .naturalAlternating, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 14, catalogueIndex := 4,
    groupOrder := 87178291200, ternaryValuation := 5,
    kind := .naturalSymmetric, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 15, catalogueIndex := 1,
    groupOrder := 2520, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 15, catalogueIndex := 2,
    groupOrder := 360, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 15, catalogueIndex := 3,
    groupOrder := 720, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 15, catalogueIndex := 4,
    groupOrder := 20160, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 15, catalogueIndex := 5,
    groupOrder := 653837184000, ternaryValuation := 6,
    kind := .naturalAlternating, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 15, catalogueIndex := 6,
    groupOrder := 1307674368000, ternaryValuation := 6,
    kind := .naturalSymmetric, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 16, catalogueIndex := 1,
    groupOrder := 80, ternaryValuation := 0,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 16, catalogueIndex := 2,
    groupOrder := 160, ternaryValuation := 0,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 16, catalogueIndex := 3,
    groupOrder := 240, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 16, catalogueIndex := 4,
    groupOrder := 288, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 16, catalogueIndex := 5,
    groupOrder := 320, ternaryValuation := 0,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 16, catalogueIndex := 6,
    groupOrder := 480, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 16, catalogueIndex := 7,
    groupOrder := 576, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 16, catalogueIndex := 8,
    groupOrder := 576, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 16, catalogueIndex := 9,
    groupOrder := 960, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 16, catalogueIndex := 10,
    groupOrder := 1152, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 16, catalogueIndex := 11,
    groupOrder := 322560, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 16, catalogueIndex := 12,
    groupOrder := 5760, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 16, catalogueIndex := 13,
    groupOrder := 1920, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 16, catalogueIndex := 14,
    groupOrder := 2880, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 16, catalogueIndex := 15,
    groupOrder := 960, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 16, catalogueIndex := 16,
    groupOrder := 11520, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 16, catalogueIndex := 17,
    groupOrder := 5760, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 16, catalogueIndex := 18,
    groupOrder := 1920, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 16, catalogueIndex := 19,
    groupOrder := 960, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 16, catalogueIndex := 20,
    groupOrder := 40320, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 16, catalogueIndex := 21,
    groupOrder := 10461394944000, ternaryValuation := 6,
    kind := .naturalAlternating, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 16, catalogueIndex := 22,
    groupOrder := 20922789888000, ternaryValuation := 6,
    kind := .naturalSymmetric, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 17, catalogueIndex := 1,
    groupOrder := 17, ternaryValuation := 0,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 17, catalogueIndex := 2,
    groupOrder := 34, ternaryValuation := 0,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 17, catalogueIndex := 3,
    groupOrder := 68, ternaryValuation := 0,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 17, catalogueIndex := 4,
    groupOrder := 136, ternaryValuation := 0,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 17, catalogueIndex := 5,
    groupOrder := 272, ternaryValuation := 0,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 17, catalogueIndex := 6,
    groupOrder := 4080, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 17, catalogueIndex := 7,
    groupOrder := 8160, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 17, catalogueIndex := 8,
    groupOrder := 16320, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 17, catalogueIndex := 9,
    groupOrder := 177843714048000, ternaryValuation := 6,
    kind := .naturalAlternating, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 17, catalogueIndex := 10,
    groupOrder := 355687428096000, ternaryValuation := 6,
    kind := .naturalSymmetric, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 18, catalogueIndex := 1,
    groupOrder := 2448, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 18, catalogueIndex := 2,
    groupOrder := 4896, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 18, catalogueIndex := 3,
    groupOrder := 3201186852864000, ternaryValuation := 8,
    kind := .naturalAlternating, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 18, catalogueIndex := 4,
    groupOrder := 6402373705728000, ternaryValuation := 8,
    kind := .naturalSymmetric, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 19, catalogueIndex := 1,
    groupOrder := 19, ternaryValuation := 0,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 19, catalogueIndex := 2,
    groupOrder := 38, ternaryValuation := 0,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 19, catalogueIndex := 3,
    groupOrder := 57, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 19, catalogueIndex := 4,
    groupOrder := 114, ternaryValuation := 1,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 19, catalogueIndex := 5,
    groupOrder := 171, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 19, catalogueIndex := 6,
    groupOrder := 342, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 19, catalogueIndex := 7,
    groupOrder := 60822550204416000, ternaryValuation := 8,
    kind := .naturalAlternating, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 19, catalogueIndex := 8,
    groupOrder := 121645100408832000, ternaryValuation := 8,
    kind := .naturalSymmetric, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 20, catalogueIndex := 1,
    groupOrder := 3420, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 20, catalogueIndex := 2,
    groupOrder := 6840, ternaryValuation := 2,
    kind := .orderBound, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by simp,
    order_bound := by intro _ _ _; omega },
  { degree := 20, catalogueIndex := 3,
    groupOrder := 1216451004088320000, ternaryValuation := 8,
    kind := .naturalAlternating, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },
  { degree := 20, catalogueIndex := 4,
    groupOrder := 2432902008176640000, ternaryValuation := 8,
    kind := .naturalSymmetric, valuation_eq := by decide +kernel,
    degree_lower := by omega, degree_upper := by omega,
    index_pos := by omega, natural_degree := by intro _; omega,
    order_bound := by simp },]

theorem primitiveCompositionBoundRows12To20_size :
    primitiveCompositionBoundRows12To20.size = 73 := by
  decide +kernel

theorem primitiveCompositionBoundRows12To20_locators_nodup :
    (primitiveCompositionBoundRows12To20.toList.map
      PrimitiveCompositionBoundRow.locator).Nodup := by
  decide +kernel

theorem primitiveCompositionBoundRows12To20_degree_range :
    ∀ r ∈ primitiveCompositionBoundRows12To20.toList,
      12 ≤ r.degree ∧ r.degree ≤ 20 := by
  decide +kernel

end SymmetricSubgroupAsymptotics
