import SymmetricSubgroupAsymptotics.InducedSubrepresentationCount
import SymmetricSubgroupAsymptotics.RepresentationHeadExact

/-!
# Generator bounds through injected quotients

This file isolates the linear pullback used by the affine induced-module
argument.  A uniform generator theorem on the dual ambient representation
passes to the dual of every quotient of an injected representation.
-/

set_option autoImplicit false
set_option backward.isDefEq.respectTransparency false
set_option maxHeartbeats 5000000
noncomputable section
open scoped Classical MonoidAlgebra

namespace SymmetricSubgroupAsymptotics

variable {k G V W Z : Type} [Field k] [Group G]
  [AddCommGroup V] [Module k V] [AddCommGroup W] [Module k W]

private def dualSubquotientInclusion
    (rho : Representation k G V) (M : Subrepresentation rho) :
    M.toRepresentation.IntertwiningMap rho where
  toLinearMap := M.toSubmodule.subtype
  isIntertwining' _ := rfl

/-- A surjective intertwiner carries a module-generating tuple to a
module-generating tuple of the same length. -/
theorem representationGeneratedBy_of_surjective
    (rho : Representation k G V) (sigma : Representation k G W)
    (f : rho.IntertwiningMap sigma) (hf : Function.Surjective f)
    {n : ℕ} (hgen : RepresentationGeneratedBy rho n) :
    RepresentationGeneratedBy sigma n := by
  obtain ⟨v, hv⟩ := hgen
  let F : rho.asModule →ₗ[k[G]] sigma.asModule :=
    Representation.IntertwiningMap.equivLinearMapAsModule rho sigma f
  let w : Fin n → sigma.asModule := fun i ↦ F (v i)
  refine ⟨w, ?_⟩
  have hFsurj : Function.Surjective F := by
    intro y
    obtain ⟨x, hx⟩ := hf y
    exact ⟨x, hx⟩
  have hmap := congrArg (Submodule.map F) hv
  rw [Submodule.map_top, LinearMap.range_eq_top.mpr hFsurj,
    Submodule.map_span] at hmap
  rw [← Set.range_comp] at hmap
  simpa only [w, Function.comp_def] using hmap

/-- A representation injected into an ambient representation with a uniform
subrepresentation-generator bound is itself generated by the same number of
elements. -/
theorem representationGeneratedBy_of_injective_of_uniform
    {rho : Representation k G V} {sigma : Representation k G W}
    {H : ℕ} (hgen : UniformSubrepresentationGeneratorBound rho H)
    (f : sigma.IntertwiningMap rho) (hf : Function.Injective f) :
    RepresentationGeneratedBy sigma H := by
  let q : sigma.IntertwiningMap f.range.toRepresentation :=
    RepresentationHeadExact.rangeProjection f
  have hqsurj : Function.Surjective q :=
    RepresentationHeadExact.rangeProjection_surjective f
  have hqinj : Function.Injective q := by
    intro x y hxy
    exact hf (congrArg Subtype.val hxy)
  have hrange := hgen f.range
  exact representationGeneratedBy_of_surjective
    f.range.toRepresentation sigma
    (q.ofBijective ⟨hqinj, hqsurj⟩).symm.toIntertwiningMap
    (Representation.Equiv.symm
      (q.ofBijective ⟨hqinj, hqsurj⟩)).surjective
    hrange

/-- Uniform subrepresentation generation descends through any injected
representation. -/
theorem UniformSubrepresentationGeneratorBound.of_injective
    {rho : Representation k G V} {sigma : Representation k G W}
    {H : ℕ} (hgen : UniformSubrepresentationGeneratorBound rho H)
    (f : sigma.IntertwiningMap rho) (hf : Function.Injective f) :
    UniformSubrepresentationGeneratorBound sigma H := by
  intro N
  exact representationGeneratedBy_of_injective_of_uniform hgen
    (f.comp (dualSubquotientInclusion sigma N)) fun _ _ hxy ↦
      Subtype.ext (hf hxy)

/-- A uniform generator bound descends through a surjective intertwiner. -/
theorem UniformSubrepresentationGeneratorBound.of_surjective
    {rho : Representation k G V} {sigma : Representation k G W}
    {H : ℕ} (hgen : UniformSubrepresentationGeneratorBound rho H)
    (f : rho.IntertwiningMap sigma) (hf : Function.Surjective f) :
    UniformSubrepresentationGeneratorBound sigma H := by
  intro N
  let P : Subrepresentation rho :=
    { toSubmodule := N.toSubmodule.comap f.toLinearMap
      apply_mem_toSubmodule := by
        intro g x hx
        change f (rho g x) ∈ N
        rw [Representation.IntertwiningMap.isIntertwining]
        exact N.apply_mem_toSubmodule g hx }
  let q : P.toRepresentation.IntertwiningMap N.toRepresentation :=
    { toLinearMap := (f.toLinearMap.domRestrict P.toSubmodule).codRestrict
          N.toSubmodule (fun x ↦ x.2)
      isIntertwining' g := by
        apply LinearMap.ext
        intro x
        apply Subtype.ext
        exact LinearMap.congr_fun (f.isIntertwining' g) x.1 }
  have hq : Function.Surjective q := by
    intro y
    obtain ⟨x, hx⟩ := hf y.1
    have hxP : x ∈ P := by
      change f x ∈ N
      simpa [hx] using y.2
    exact ⟨⟨x, hxP⟩, Subtype.ext hx⟩
  exact representationGeneratedBy_of_surjective
    P.toRepresentation N.toRepresentation q hq (hgen P)

/-- Abstract pullback form of the subquotient argument. -/
theorem representationDual_generated_of_subquotient
    [AddCommGroup Z] [Module k Z]
    {rho : Representation k G V} {sigma : Representation k G W}
    {tau : Representation k G Z} {H : ℕ}
    (huniform : UniformSubrepresentationGeneratorBound rho.dual H)
    (i : sigma.IntertwiningMap rho) (hi : Function.Injective i)
    (q : sigma.IntertwiningMap tau) (hq : Function.Surjective q) :
    RepresentationGeneratedBy tau.dual H := by
  let r : rho.dual.IntertwiningMap sigma.dual :=
    RepresentationHeadExact.dualMap i
  have hr : Function.Surjective r :=
    LinearMap.dualMap_surjective_of_injective hi
  let d : tau.dual.IntertwiningMap sigma.dual :=
    RepresentationHeadExact.dualMap q
  have hd : Function.Injective d :=
    LinearMap.dualMap_injective_of_surjective hq
  have hsigma : UniformSubrepresentationGeneratorBound sigma.dual H :=
    huniform.of_surjective r hr
  exact representationGeneratedBy_of_injective_of_uniform hsigma d hd

end SymmetricSubgroupAsymptotics

end
