import SymmetricSubgroupAsymptotics.Non2PreE7Sns2MenuMass
import SymmetricSubgroupAsymptotics.Non2PreE7B6RankTailSource

/-!
# The semisimple outer factor from the primitive generator theorem

Holt--Roney-Dougal, *Minimal and random generation of permutation and
matrix groups*, J. Algebra 387 (2013), Theorem 1.1, proves that a subnormal
subgroup of a primitive permutation group of degree `w` is generated by at
most `log₂ w` elements, apart from the natural degree-three `S₃` exception.
A centerless simple permutation group is not that exception.  Passing from
one of its nontrivial orbits to a maximal overgroup of a point stabilizer
gives the following faithful-simple corollary.

This file takes precisely that published corollary as input and proves the
previously exposed `SemisimpleOuterFactorPermutationBound`.  The rest is
elementary: automorphisms are determined by generator images, the orders of
the simple factors multiply to `|E| ≤ w!`, and two base-two logarithmic
estimates pay the factor involving the source degree.
-/

set_option autoImplicit false
noncomputable section
open scoped BigOperators Classical

namespace SymmetricSubgroupAsymptotics

/-- **Published input LIT-PRIM-GEN, faithful-simple corollary.**

Every finite centerless simple group with a faithful permutation action of
degree `w` has a generating set of size at most `⌊log₂ w⌋`.  This is the
direct corollary of Holt--Roney-Dougal, Theorem 1.1, obtained by choosing a
nontrivial orbit and enlarging its point stabilizer to a maximal subgroup.
The exceptional group in degree three is `S₃`, hence is not simple. -/
def FaithfulSimplePermutationGeneratorBound : Prop :=
  ∀ (w : ℕ) (G : Type) [Group G] [Finite G],
    IsSimpleGroup G → IsCenterless G →
    ∀ ρ : G →* Equiv.Perm (Fin w), Function.Injective ρ →
      ∃ S : Finset G, Subgroup.closure (S : Set G) = ⊤ ∧
        S.card ≤ Nat.log2 w

namespace SemisimpleNormalChart

variable {w : ℕ} {U : Subgroup (Equiv.Perm (Fin w))}
  {E : Subgroup U} (C : SemisimpleNormalChart E)

/-- The literal embedding of one displayed simple factor in the ambient
permutation group. -/
def factorPermutationHom (i : C.ι) :
    C.factor i →* Equiv.Perm (Fin w) :=
  U.subtype.comp <| E.subtype.comp <|
    C.equiv.symm.toMonoidHom.comp (MonoidHom.mulSingle C.factor i)

theorem factorPermutationHom_injective (i : C.ι) :
    Function.Injective (C.factorPermutationHom i) :=
  U.subtype_injective.comp <| E.subtype_injective.comp <|
    C.equiv.symm.injective.comp (Pi.mulSingle_injective i)

/-- The published generator bound makes an automorphism of a simple factor
cost at most `|S|^(log₂ w)`. -/
theorem factor_aut_card_le
    (hgen : FaithfulSimplePermutationGeneratorBound) (i : C.ι) :
    Nat.card (C.factor i ≃* C.factor i) ≤
      Nat.card (C.factor i) ^ Nat.log2 w := by
  obtain ⟨S, hS, hScard⟩ := hgen w (C.factor i) (C.simple i)
    (C.centerless i) (C.factorPermutationHom i)
    (C.factorPermutationHom_injective i)
  letI : Finite (C.factor i →* C.factor i) := Finite.of_injective
    (fun f : C.factor i →* C.factor i => (f : C.factor i → C.factor i))
      DFunLike.coe_injective
  calc
    Nat.card (C.factor i ≃* C.factor i) ≤
        Nat.card (C.factor i →* C.factor i) :=
      Nat.card_le_card_of_injective (fun e => e.toMonoidHom)
        (fun _ _ h => MulEquiv.ext (fun x => DFunLike.congr_fun h x))
    _ ≤ Nat.card (C.factor i) ^ S.card :=
      monoidHom_card_le_pow_of_closure S hS
    _ ≤ Nat.card (C.factor i) ^ Nat.log2 w :=
      Nat.pow_le_pow_right Nat.card_pos hScard

end SemisimpleNormalChart

namespace Non2UnipotentPrefixFiniteMenu

private theorem logb_two_prod_nat
    {ι : Type*} (s : Finset ι) (f : ι → ℕ)
    (hf : ∀ i ∈ s, 0 < f i) :
    Real.logb 2 ((∏ i ∈ s, f i : ℕ) : ℝ) =
      ∑ i ∈ s, Real.logb 2 (f i : ℝ) := by
  induction s using Finset.induction_on with
  | empty => simp
  | @insert a s ha ih =>
      have hfa : (f a : ℝ) ≠ 0 := by exact_mod_cast (hf a (Finset.mem_insert_self _ _)).ne'
      have hfs : (((∏ i ∈ s, f i : ℕ) : ℝ)) ≠ 0 := by
        exact_mod_cast
          (Finset.prod_pos fun i hi => hf i (Finset.mem_insert_of_mem hi)).ne'
      rw [Finset.prod_insert ha, Finset.sum_insert ha, Nat.cast_mul,
        Real.logb_mul hfa hfs]
      rw [ih (fun i hi => hf i (Finset.mem_insert_of_mem hi))]

private theorem factorial_le_two_pow_sq (n : ℕ) :
    n.factorial ≤ 2 ^ (n * n) := by
  calc
    n.factorial ≤ n ^ n := n.factorial_le_pow
    _ ≤ (2 ^ n) ^ n :=
      Nat.pow_le_pow_left (Nat.le_of_lt n.lt_two_pow_self) n
    _ = 2 ^ (n * n) := by rw [pow_mul]

private theorem factorial_logb_le_sq (n : ℕ) :
    Real.logb 2 (Nat.factorial n : ℝ) ≤ (n : ℝ) ^ 2 := by
  have hcast : (Nat.factorial n : ℝ) ≤ (((2 ^ (n * n) : ℕ) : ℝ)) := by
    exact_mod_cast factorial_le_two_pow_sq n
  have h := Real.logb_le_logb_of_le (by norm_num : (1 : ℝ) < 2)
    (by positivity : (0 : ℝ) < Nat.factorial n)
    hcast
  calc
    Real.logb 2 (Nat.factorial n : ℝ) ≤
        Real.logb 2 (((2 ^ (n * n) : ℕ) : ℝ)) := h
    _ = (n : ℝ) ^ 2 := by
      rw [Nat.cast_pow, Nat.cast_ofNat, Real.logb_pow,
        Real.logb_self_eq_one (by norm_num : (1 : ℝ) < 2), mul_one,
        Nat.cast_mul]
      norm_num [pow_two]

private theorem log2_nat_le_logb_sum (w b : ℕ) :
    (Nat.log2 w : ℝ) ≤ Real.logb 2 ((w + b + 2 : ℕ) : ℝ) := by
  by_cases hw : w = 0
  · subst w
    simp only [Nat.log2_zero, Nat.cast_zero, Nat.zero_add]
    exact Real.logb_nonneg (by norm_num)
      (by exact_mod_cast (show 1 ≤ b + 2 by omega))
  · calc
      (Nat.log2 w : ℝ) ≤ Real.logb 2 (w : ℝ) := Real.log2_le_logb w
      _ ≤ Real.logb 2 ((w + b + 2 : ℕ) : ℝ) := by
        apply Real.logb_le_logb_of_le (by norm_num)
          (by exact_mod_cast (Nat.pos_of_ne_zero hw))
        exact_mod_cast (show w ≤ w + b + 2 by omega)

private theorem factorial_logb_add_one_le_rpow
    (w b : ℕ) :
    Real.logb 2 (Nat.factorial b : ℝ) + 1 ≤
      (2 : ℝ) ^
        (2 * Real.logb 2 ((w + b + 2 : ℕ) : ℝ)) := by
  let X : ℝ := Real.logb 2 ((w + b + 2 : ℕ) : ℝ)
  have hL := factorial_logb_le_sq b
  have hb : (b : ℝ) + 1 ≤ (w + b + 2 : ℕ) := by
    exact_mod_cast (show b + 1 ≤ w + b + 2 by omega)
  have hsq : (b : ℝ) ^ 2 + 1 ≤ ((w + b + 2 : ℕ) : ℝ) ^ 2 := by
    nlinarith
  have hN : (0 : ℝ) < (w + b + 2 : ℕ) := by positivity
  have hrepr : (2 : ℝ) ^ X = ((w + b + 2 : ℕ) : ℝ) := by
    dsimp [X]
    exact Real.rpow_logb (by norm_num) (by norm_num) hN
  calc
    Real.logb 2 (Nat.factorial b : ℝ) + 1 ≤ (b : ℝ) ^ 2 + 1 :=
      by linarith
    _ ≤ ((w + b + 2 : ℕ) : ℝ) ^ 2 := hsq
    _ = ((2 : ℝ) ^ X) ^ (2 : ℕ) := by rw [hrepr]
    _ = ((2 : ℝ) ^ X) ^ (2 : ℝ) := (Real.rpow_two _).symm
    _ = (2 : ℝ) ^ (X * 2) := by rw [← Real.rpow_mul (by norm_num : (0 : ℝ) ≤ 2)]
    _ = (2 : ℝ) ^ (2 * X) := by ring_nf

/-- The semisimple outer-factor hypothesis is a theorem from the published
primitive generator input. -/
theorem semisimpleOuterFactorPermutationBound_of_primitiveGenerator
    (hgen : FaithfulSimplePermutationGeneratorBound) :
    SemisimpleOuterFactorPermutationBound := by
  intro w U E _ C b
  let L : ℝ := Real.logb 2 (Nat.factorial b : ℝ)
  let X : ℝ := Real.logb 2 ((w + b + 2 : ℕ) : ℝ)
  have hL : 0 ≤ L := Real.logb_nonneg (by norm_num)
    (by exact_mod_cast Nat.factorial_pos b)
  have hX : 1 ≤ X := by
    dsimp [X]
    calc
      (1 : ℝ) = Real.logb 2 2 := by
        rw [Real.logb_self_eq_one (by norm_num : (1 : ℝ) < 2)]
      _ ≤ Real.logb 2 ((w + b + 2 : ℕ) : ℝ) :=
        Real.logb_le_logb_of_le (by norm_num)
          (by norm_num) (by exact_mod_cast (show 2 ≤ w + b + 2 by omega))
  have hlogw : (Nat.log2 w : ℝ) ≤ X := by
    exact log2_nat_le_logb_sum w b
  have hLone : L + 1 ≤ (2 : ℝ) ^ (2 * X) := by
    exact factorial_logb_add_one_le_rpow w b
  have hfactor : ∀ i : C.ι,
      1 + C.factorWeight L i ≤
        (2 : ℝ) ^
          (3 * Real.logb 2 (Nat.card (C.factor i) : ℝ) * X) := by
    intro i
    let a : ℝ := Real.logb 2 (Nat.card (C.factor i) : ℝ)
    have ha : 1 ≤ a := by
      letI : IsSimpleGroup (C.factor i) := C.simple i
      dsimp [a]
      rw [Real.le_logb_iff_rpow_le (by norm_num)
        (by exact_mod_cast (Nat.card_pos (α := C.factor i)))]
      norm_num
      exact_mod_cast Finite.one_lt_card (α := C.factor i)
    have ha0 : 0 ≤ a := le_trans (by norm_num) ha
    have hautNat := C.factor_aut_card_le hgen i
    have haut : (Nat.card (C.factor i ≃* C.factor i) : ℝ) ≤
        (Nat.card (C.factor i) : ℝ) ^ Nat.log2 w := by
      exact_mod_cast hautNat
    have hden : L / a ≤ L := div_le_self hL ha
    have hweight : C.factorWeight L i ≤
        (Nat.card (C.factor i ≃* C.factor i) : ℝ) * L := by
      unfold SemisimpleNormalChart.factorWeight
      exact mul_le_mul_of_nonneg_left hden (Nat.cast_nonneg _)
    have hautone : (1 : ℝ) ≤ Nat.card (C.factor i ≃* C.factor i) := by
      exact_mod_cast Nat.card_pos
    have hcardpos : (0 : ℝ) < Nat.card (C.factor i) := by
      exact_mod_cast Nat.card_pos (α := C.factor i)
    have hcardrepr : (2 : ℝ) ^ a = (Nat.card (C.factor i) : ℝ) := by
      dsimp [a]
      exact Real.rpow_logb (by norm_num) (by norm_num) hcardpos
    have hautExp : (Nat.card (C.factor i ≃* C.factor i) : ℝ) ≤
        (2 : ℝ) ^ (a * X) := by
      calc
        (Nat.card (C.factor i ≃* C.factor i) : ℝ) ≤
            (Nat.card (C.factor i) : ℝ) ^ Nat.log2 w := haut
        _ = ((2 : ℝ) ^ a) ^ (Nat.log2 w : ℕ) := by rw [hcardrepr]
        _ = ((2 : ℝ) ^ a) ^ (Nat.log2 w : ℝ) := by
          rw [Real.rpow_natCast]
        _ = (2 : ℝ) ^ (a * (Nat.log2 w : ℝ)) := by
          rw [← Real.rpow_mul (by norm_num : (0 : ℝ) ≤ 2)]
        _ ≤ (2 : ℝ) ^ (a * X) :=
          Real.rpow_le_rpow_of_exponent_le (by norm_num)
            (mul_le_mul_of_nonneg_left hlogw ha0)
    calc
      1 + C.factorWeight L i ≤
          1 + (Nat.card (C.factor i ≃* C.factor i) : ℝ) * L :=
        by simpa [add_comm] using add_le_add_right hweight 1
      _ ≤ (Nat.card (C.factor i ≃* C.factor i) : ℝ) * (L + 1) := by
        nlinarith
      _ ≤ (2 : ℝ) ^ (a * X) * (2 : ℝ) ^ (2 * X) :=
        mul_le_mul hautExp hLone (by positivity) (by positivity)
      _ = (2 : ℝ) ^ (a * X + 2 * X) := by
        rw [← Real.rpow_add (by norm_num : (0 : ℝ) < 2)]
      _ ≤ (2 : ℝ) ^ (3 * a * X) := by
        apply Real.rpow_le_rpow_of_exponent_le (by norm_num)
        nlinarith
      _ = (2 : ℝ) ^
          (3 * Real.logb 2 (Nat.card (C.factor i) : ℝ) * X) := rfl
  have hcardE : Nat.card E = ∏ i : C.ι, Nat.card (C.factor i) := by
    calc
      Nat.card E = Nat.card ((i : C.ι) → C.factor i) :=
        Nat.card_congr C.equiv.toEquiv
      _ = ∏ i : C.ι, Nat.card (C.factor i) := Nat.card_pi
  have hsumEq :
      (∑ i : C.ι, Real.logb 2 (Nat.card (C.factor i) : ℝ)) =
        Real.logb 2 (Nat.card E : ℝ) := by
    symm
    rw [hcardE]
    exact logb_two_prod_nat Finset.univ (fun i => Nat.card (C.factor i))
      (fun i _ => Nat.card_pos)
  have hcardEfac : Nat.card E ≤ Nat.factorial w := by
    calc
      Nat.card E ≤ Nat.card U := Subgroup.card_le_card_group E
      _ ≤ Nat.card (Equiv.Perm (Fin w)) := Subgroup.card_le_card_group U
      _ = Nat.factorial w := by
        rw [Nat.card_eq_fintype_card, Fintype.card_perm, Fintype.card_fin]
  have hsum :
      (∑ i : C.ι, Real.logb 2 (Nat.card (C.factor i) : ℝ)) ≤
        (w : ℝ) * X := by
    rw [hsumEq]
    have h1 := Real.logb_le_logb_of_le (by norm_num : (1 : ℝ) < 2)
      (by exact_mod_cast (Nat.card_pos (α := E)) : (0 : ℝ) < Nat.card E)
      (by
        have hcast : (Nat.card E : ℝ) ≤ (Nat.factorial w : ℝ) := by
          exact_mod_cast hcardEfac
        exact hcast)
    by_cases hw : w = 0
    · subst w
      norm_num at hcardEfac
      have hEpos : 0 < Fintype.card E := Fintype.card_pos
      have hE : Fintype.card E = 1 := by omega
      rw [Nat.card_eq_fintype_card, hE]
      simp
    · have hfac : Nat.factorial w ≤ w ^ w := w.factorial_le_pow
      have hfacCast : (Nat.factorial w : ℝ) ≤ (((w ^ w : ℕ) : ℝ)) := by
        exact_mod_cast hfac
      have h2 := Real.logb_le_logb_of_le (by norm_num : (1 : ℝ) < 2)
        (by positivity : (0 : ℝ) < Nat.factorial w)
        hfacCast
      calc
        Real.logb 2 (Nat.card E : ℝ) ≤
            Real.logb 2 (Nat.factorial w : ℝ) := h1
        _ ≤ Real.logb 2 (((w ^ w : ℕ) : ℝ)) := h2
        _ = (w : ℝ) * Real.logb 2 (w : ℝ) := by
          rw [Nat.cast_pow, Real.logb_pow]
        _ ≤ (w : ℝ) * X := by
          apply mul_le_mul_of_nonneg_left _ (Nat.cast_nonneg _)
          apply Real.logb_le_logb_of_le (by norm_num : (1 : ℝ) < 2)
            (by exact_mod_cast (Nat.pos_of_ne_zero hw))
          exact_mod_cast (show w ≤ w + b + 2 by omega)
  unfold SemisimpleNormalChart.outerFactor
  calc
    (∏ i : C.ι, (1 + C.factorWeight L i)) ≤
        ∏ i : C.ι,
          (2 : ℝ) ^
            (3 * Real.logb 2 (Nat.card (C.factor i) : ℝ) * X) :=
      Finset.prod_le_prod
        (fun i _ => add_nonneg zero_le_one (C.factorWeight_nonneg hL i))
        (fun i _ => hfactor i)
    _ = (2 : ℝ) ^
        (∑ i : C.ι,
          (3 * Real.logb 2 (Nat.card (C.factor i) : ℝ) * X)) := by
      exact (Real.rpow_sum_of_pos (by norm_num) _ Finset.univ).symm
    _ = (2 : ℝ) ^
        (3 * X *
          (∑ i : C.ι, Real.logb 2 (Nat.card (C.factor i) : ℝ))) := by
      congr 1
      rw [Finset.mul_sum]
      apply Finset.sum_congr rfl
      intro i _
      ring
    _ ≤ (2 : ℝ) ^ (3 * X * ((w : ℝ) * X)) := by
      apply Real.rpow_le_rpow_of_exponent_le (by norm_num)
      exact mul_le_mul_of_nonneg_left hsum
        (mul_nonneg (by norm_num) (le_trans (by norm_num) hX))
    _ = (2 : ℝ) ^
        (3 * (w : ℝ) *
          (Real.logb 2 ((w + b + 2 : ℕ) : ℝ)) ^ 2) := by
      dsimp [X]
      ring

end Non2UnipotentPrefixFiniteMenu
end SymmetricSubgroupAsymptotics

end
