import SymmetricSubgroupAsymptotics.C1SparseSemidirectCertificate
import SymmetricSubgroupAsymptotics.FiniteCayleyGroup
import SymmetricSubgroupAsymptotics.FinitePermutationEncoding
import Mathlib.Order.Fin.Basic

/-!
# Sparse V4-block semidirect certificate for 12T228

Generated by export_lean_c1_v4_semidirect.py from selected transitive row
402 (raw-line SHA256 39946b47d6fc5e6061ecf01162bd245c314d83c18306177cdc710fd0cfae6314).  Only the 64-row binary base and
the 27-row ternary complement are enumerated.  Literal
source words prove inclusion, generation and normality; no ambient Cayley
table or catalogue group identifier is used as a theorem premise.
-/

set_option autoImplicit false
set_option maxRecDepth 100000
set_option maxHeartbeats 0
noncomputable section

namespace SymmetricSubgroupAsymptotics.TernaryV4Semidirect12T228

private def sourceGenerator0 : Equiv.Perm (Fin 12) where
  toFun x := (#[0,1,11,3,4,8,6,7,5,9,10,2] : Array (Fin 12))[x.val]!
  invFun x := (#[0,1,11,3,4,8,6,7,5,9,10,2] : Array (Fin 12))[x.val]!
  left_inv := by decide +kernel
  right_inv := by decide +kernel

private def sourceGenerator1 : Equiv.Perm (Fin 12) where
  toFun x := (#[0,1,8,3,4,11,6,7,2,9,10,5] : Array (Fin 12))[x.val]!
  invFun x := (#[0,1,8,3,4,11,6,7,2,9,10,5] : Array (Fin 12))[x.val]!
  left_inv := by decide +kernel
  right_inv := by decide +kernel

private def sourceGenerator2 : Equiv.Perm (Fin 12) where
  toFun x := (#[0,1,5,9,4,11,3,7,8,6,10,2] : Array (Fin 12))[x.val]!
  invFun x := (#[0,1,11,6,4,2,9,7,8,3,10,5] : Array (Fin 12))[x.val]!
  left_inv := by decide +kernel
  right_inv := by decide +kernel

private def sourceGenerator3 : Equiv.Perm (Fin 12) where
  toFun x := (#[4,5,9,7,8,3,10,11,0,1,2,6] : Array (Fin 12))[x.val]!
  invFun x := (#[8,9,10,5,0,1,11,3,4,2,6,7] : Array (Fin 12))[x.val]!
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def sourceGenerators (j : Fin 4) : Equiv.Perm (Fin 12) :=
  (if j.val < 2 then (if j.val < 1 then sourceGenerator0 else sourceGenerator1) else (if j.val < 3 then sourceGenerator2 else sourceGenerator3))

private def baseGenerator0 : Equiv.Perm (Fin 12) where
  toFun x := (#[0,1,5,3,4,2,6,7,11,9,10,8] : Array (Fin 12))[x.val]!
  invFun x := (#[0,1,5,3,4,2,6,7,11,9,10,8] : Array (Fin 12))[x.val]!
  left_inv := by decide +kernel
  right_inv := by decide +kernel

private def baseGenerator1 : Equiv.Perm (Fin 12) where
  toFun x := (#[0,1,11,3,4,8,6,7,5,9,10,2] : Array (Fin 12))[x.val]!
  invFun x := (#[0,1,11,3,4,8,6,7,5,9,10,2] : Array (Fin 12))[x.val]!
  left_inv := by decide +kernel
  right_inv := by decide +kernel

private def baseGenerator2 : Equiv.Perm (Fin 12) where
  toFun x := (#[0,7,2,3,10,5,6,1,8,9,4,11] : Array (Fin 12))[x.val]!
  invFun x := (#[0,7,2,3,10,5,6,1,8,9,4,11] : Array (Fin 12))[x.val]!
  left_inv := by decide +kernel
  right_inv := by decide +kernel

private def baseGenerator3 : Equiv.Perm (Fin 12) where
  toFun x := (#[0,4,2,3,1,5,6,10,8,9,7,11] : Array (Fin 12))[x.val]!
  invFun x := (#[0,4,2,3,1,5,6,10,8,9,7,11] : Array (Fin 12))[x.val]!
  left_inv := by decide +kernel
  right_inv := by decide +kernel

private def baseGenerator4 : Equiv.Perm (Fin 12) where
  toFun x := (#[6,1,2,9,4,5,0,7,8,3,10,11] : Array (Fin 12))[x.val]!
  invFun x := (#[6,1,2,9,4,5,0,7,8,3,10,11] : Array (Fin 12))[x.val]!
  left_inv := by decide +kernel
  right_inv := by decide +kernel

private def baseGenerator5 : Equiv.Perm (Fin 12) where
  toFun x := (#[9,1,2,6,4,5,3,7,8,0,10,11] : Array (Fin 12))[x.val]!
  invFun x := (#[9,1,2,6,4,5,3,7,8,0,10,11] : Array (Fin 12))[x.val]!
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def baseGenerators (j : Fin 6) : Equiv.Perm (Fin 12) :=
  (if j.val < 3 then (if j.val < 1 then baseGenerator0 else (if j.val < 2 then baseGenerator1 else baseGenerator2)) else (if j.val < 4 then baseGenerator3 else (if j.val < 5 then baseGenerator4 else baseGenerator5)))

private def complementGenerator0 : Equiv.Perm (Fin 12) where
  toFun x := (#[4,5,9,7,8,3,10,11,0,1,2,6] : Array (Fin 12))[x.val]!
  invFun x := (#[8,9,10,5,0,1,11,3,4,2,6,7] : Array (Fin 12))[x.val]!
  left_inv := by decide +kernel
  right_inv := by decide +kernel

private def complementGenerator1 : Equiv.Perm (Fin 12) where
  toFun x := (#[0,1,5,9,4,11,3,7,8,6,10,2] : Array (Fin 12))[x.val]!
  invFun x := (#[0,1,11,6,4,2,9,7,8,3,10,5] : Array (Fin 12))[x.val]!
  left_inv := by decide +kernel
  right_inv := by decide +kernel

private def complementGenerator2 : Equiv.Perm (Fin 12) where
  toFun x := (#[0,7,5,6,4,11,9,10,8,3,1,2] : Array (Fin 12))[x.val]!
  invFun x := (#[0,10,11,9,4,2,3,1,8,6,7,5] : Array (Fin 12))[x.val]!
  left_inv := by decide +kernel
  right_inv := by decide +kernel

def complementGenerators (j : Fin 3) : Equiv.Perm (Fin 12) :=
  (if j.val < 1 then complementGenerator0 else (if j.val < 2 then complementGenerator1 else complementGenerator2))

private def baseCodes (i : Fin 64) : Fin (12^12) :=
  Fin.ofNat 8916100448256 (((if (i.val) / 32 < 1 then 1764270427859482822717083408535441793862065342070416849080527536828894168491371394414358715581120436513233455430743749064754503475004665131384989447603855931508966124605951832569847410571622257428177747189641743767621611234399264372303344858630358295631053313791100888342011346967831684179971536363065169029904368560026484922870736264346634388300477758423049031043891734040015952763839803543217541822686392661382523158885937 else 3560286225044666218587112496156636626901207822459748919404973000595904206038861912106348939977266672212355639275088975476693438815277703597211768095893618573779151177212984112620937719669353404410797599343483754101764443373729347697203950511387450979635456707129985404020108188905993957626211023857936137980061871520117614779542264817370360638459642195011326069392132062935152397319326954688227868950126673124413297133136593) : ℕ) / 2 ^ (44 * ((i.val) % 32)) % 2 ^ 44)
private def baseRanks (i : Fin 64) : ℕ :=
  (((if (i.val) / 32 < 1 then 759169472170960356697928572118589710316103274760507747637 else 32304404595517882478359013324668165372743520128758176817) : ℕ) / 2 ^ (6 * ((i.val) % 32)) % 2 ^ 6)
private def baseParents (i : Fin 64) : Fin 64 :=
  Fin.ofNat 64 (((if (i.val) / 32 < 1 then 4654943042163253299226555004258950873621151430875729891523 else 6274036743751087623231818149094330113977722055293887453411) : ℕ) / 2 ^ (6 * ((i.val) % 32)) % 2 ^ 6)
private def baseLetters (i : Fin 64) : Fin 6 :=
  Fin.ofNat 6 (((if (i.val) / 32 < 1 then 16817845628391366025463355237 else 6914325314108288641898272613) : ℕ) / 2 ^ (3 * ((i.val) % 32)) % 2 ^ 3)
private def baseNext (i : Fin 64) (j : Fin 6) : Fin 64 :=
  Fin.ofNat 64 (((if (i.val * 6 + j.val) / 32 < 6 then (if (i.val * 6 + j.val) / 32 < 3 then (if (i.val * 6 + j.val) / 32 < 1 then 5230577143712364949416360343950819152309577996842061302800 else (if (i.val * 6 + j.val) / 32 < 2 then 1377579607019820369388452454401425286513554527828552740941 else 1197145405247177001140242131860653662492278085519802217032)) else (if (i.val * 6 + j.val) / 32 < 4 then 3637170986382182831499485083090617369081144381611843880960 else (if (i.val * 6 + j.val) / 32 < 5 then 2970985954345215343087501313013513389776059710598905689181 else 2791329782969216402840173784447222305277852345145135773272))) else (if (i.val * 6 + j.val) / 32 < 9 then (if (i.val * 6 + j.val) / 32 < 7 then 2141844543668844848210270761036528101115728595378416813104 else (if (i.val * 6 + j.val) / 32 < 8 then 4564416246913436694749105752909489704101861528581416056941 else 4385514166537262353948787701580002834833705729925550422632)) else (if (i.val * 6 + j.val) / 32 < 10 then 548438386338662730293395500176326317887294980148199391264 else (if (i.val * 6 + j.val) / 32 < 11 then 6157822594238831668448154611521577807364366711351769005181 else 5979698544259301755648719354166571477619279989550883978872)))) : ℕ) / 2 ^ (6 * ((i.val * 6 + j.val) % 32)) % 2 ^ 6)

private theorem base_parent_lt : ∀ i : Fin 64,
    i ≠ 63 → baseRanks (baseParents i) < baseRanks i := (Fin.addCases (m := 32) (n := 32) (Fin.addCases (m := 16) (n := 16) (by decide +kernel) (by decide +kernel)) (Fin.addCases (m := 16) (n := 16) (by decide +kernel) (by decide +kernel)))
private theorem base_parent_next : ∀ i : Fin 64,
    i ≠ 63 →
      baseNext (baseParents i) (baseLetters i) = i := (Fin.addCases (m := 32) (n := 32) (Fin.addCases (m := 16) (n := 16) (by decide +kernel) (by decide +kernel)) (Fin.addCases (m := 16) (n := 16) (by decide +kernel) (by decide +kernel)))

def baseEncoded : EncodedCayleyCertificate
    (permutationGeneratorEncoding baseGenerators) 64 where
  rows := baseCodes
  identity := 63
  identity_eq := by decide +kernel
  next := baseNext
  next_eq := (Fin.addCases (m := 32) (n := 32) (Fin.addCases (m := 16) (n := 16) (by decide +kernel) (by decide +kernel)) (Fin.addCases (m := 16) (n := 16) (by decide +kernel) (by decide +kernel)))
  rank := baseRanks
  parent i _ := baseParents i
  letter i _ := baseLetters i
  parent_lt := base_parent_lt
  parent_next := base_parent_next

private theorem base_codes_strict : StrictMono baseCodes :=
  Fin.strictMono_iff_lt_succ.mpr (Fin.addCases (m := 31) (n := 32) (Fin.addCases (m := 15) (n := 16) (by decide +kernel) (by decide +kernel)) (Fin.addCases (m := 16) (n := 16) (by decide +kernel) (by decide +kernel)))

theorem baseRowsInjective : Function.Injective baseEncoded.toCayley.elements :=
  baseEncoded.elements_injective base_codes_strict.injective

private def complementCodes (i : Fin 27) : Fin (12^12) :=
  Fin.ofNat 8916100448256 ((2112933690262937560252700430581803714476522782887755194089212433669378116743764421316556624611019098869756995260549285805345169895257088406441912415896344526252305620119134560097737492220366419458199078792731630572291973427820543718417048586598558692965076037642340386174546104339998812085795778480030386633069658936548346584207277224305330706095253134940608 : ℕ) / 2 ^ (44 * ((i.val) % 32)) % 2 ^ 44)
private def complementRanks (i : Fin 27) : ℕ :=
  ((920013693655845007276085745202537541420 : ℕ) / 2 ^ (5 * ((i.val) % 32)) % 2 ^ 5)
private def complementParents (i : Fin 27) : Fin 27 :=
  Fin.ofNat 27 ((35787313500441958853033317373044329372887 : ℕ) / 2 ^ (5 * ((i.val) % 32)) % 2 ^ 5)
private def complementLetters (i : Fin 27) : Fin 3 :=
  Fin.ofNat 3 ((2819792669644434 : ℕ) / 2 ^ (2 * ((i.val) % 32)) % 2 ^ 2)
private def complementNext (i : Fin 27) (j : Fin 3) : Fin 27 :=
  Fin.ofNat 27 (((if (i.val * 3 + j.val) / 32 < 1 then 1154365250821056157153253054735807640338325193194 else (if (i.val * 3 + j.val) / 32 < 2 then 1105076153792286688994716374721333504606125976218 else 3830028949868136196252704)) : ℕ) / 2 ^ (5 * ((i.val * 3 + j.val) % 32)) % 2 ^ 5)

private theorem complement_parent_lt : ∀ i : Fin 27,
    i ≠ 26 → complementRanks (complementParents i) < complementRanks i := (Fin.addCases (m := 13) (n := 14) (by decide +kernel) (by decide +kernel))
private theorem complement_parent_next : ∀ i : Fin 27,
    i ≠ 26 →
      complementNext (complementParents i) (complementLetters i) = i := (Fin.addCases (m := 13) (n := 14) (by decide +kernel) (by decide +kernel))

def complementEncoded : EncodedCayleyCertificate
    (permutationGeneratorEncoding complementGenerators) 27 where
  rows := complementCodes
  identity := 26
  identity_eq := by decide +kernel
  next := complementNext
  next_eq := (Fin.addCases (m := 13) (n := 14) (by decide +kernel) (by decide +kernel))
  rank := complementRanks
  parent i _ := complementParents i
  letter i _ := complementLetters i
  parent_lt := complement_parent_lt
  parent_next := complement_parent_next

private theorem complement_codes_strict : StrictMono complementCodes :=
  Fin.strictMono_iff_lt_succ.mpr (Fin.addCases (m := 13) (n := 13) (by decide +kernel) (by decide +kernel))

theorem complementRowsInjective : Function.Injective complementEncoded.toCayley.elements :=
  complementEncoded.elements_injective complement_codes_strict.injective

private def baseInSourceWord (i : Fin 6) : List (Fin 4) :=
  (if i.val < 3 then (if i.val < 1 then [0,1] else (if i.val < 2 then [0] else [2,2,3,2,3,1,3])) else (if i.val < 4 then [2,2,3,2,3,0,3] else (if i.val < 5 then [2,2,3,0,2,3,3] else [2,2,3,2,0,3,3])))

private def complementInSourceWord (i : Fin 3) : List (Fin 4) :=
  (if i.val < 1 then [3] else (if i.val < 2 then [2] else [3,3,3]))

private def sourceBaseWord (i : Fin 4) : List (Fin 6) :=
  (if i.val < 2 then (if i.val < 1 then [1] else [0,1]) else (if i.val < 3 then [] else []))

private def sourceComplementWord (i : Fin 4) : List (Fin 3) :=
  (if i.val < 2 then (if i.val < 1 then [] else []) else (if i.val < 3 then [1] else [0]))

private def conjugateWord (i : Fin 4 × Fin 6) : List (Fin 6) :=
  (if i.1.val * 6 + i.2.val < 12 then (if i.1.val * 6 + i.2.val < 6 then (if i.1.val * 6 + i.2.val < 3 then (if i.1.val * 6 + i.2.val < 1 then [0] else (if i.1.val * 6 + i.2.val < 2 then [1] else [2])) else (if i.1.val * 6 + i.2.val < 4 then [3] else (if i.1.val * 6 + i.2.val < 5 then [4] else [5]))) else (if i.1.val * 6 + i.2.val < 9 then (if i.1.val * 6 + i.2.val < 7 then [0] else (if i.1.val * 6 + i.2.val < 8 then [1] else [2])) else (if i.1.val * 6 + i.2.val < 10 then [3] else (if i.1.val * 6 + i.2.val < 11 then [4] else [5])))) else (if i.1.val * 6 + i.2.val < 18 then (if i.1.val * 6 + i.2.val < 15 then (if i.1.val * 6 + i.2.val < 13 then [0,1] else (if i.1.val * 6 + i.2.val < 14 then [0] else [2])) else (if i.1.val * 6 + i.2.val < 16 then [3] else (if i.1.val * 6 + i.2.val < 17 then [4,5] else [4]))) else (if i.1.val * 6 + i.2.val < 21 then (if i.1.val * 6 + i.2.val < 19 then [4] else (if i.1.val * 6 + i.2.val < 20 then [4,5] else [0,1])) else (if i.1.val * 6 + i.2.val < 22 then [1] else (if i.1.val * 6 + i.2.val < 23 then [2] else [3])))))

private def baseInSource : BinaryNormalGeneratorWords
    baseGenerators sourceGenerators where
  words := baseInSourceWord
  equations := by decide +kernel

private def complementInSource : BinaryNormalGeneratorWords
    complementGenerators sourceGenerators where
  words := complementInSourceWord
  equations := by decide +kernel

private def conjugates : BinaryNormalGeneratorWords
    (fun ij : Fin 4 × Fin 6 =>
      sourceGenerators ij.1 * baseGenerators ij.2 * (sourceGenerators ij.1)⁻¹)
    baseGenerators where
  words := conjugateWord
  equations := by decide +kernel

def certificate : C1SparseSemidirectCertificate (Equiv.Perm (Fin 12)) where
  sourceCount := 4
  baseGeneratorCount := 6
  complementGeneratorCount := 3
  sourceGenerators := sourceGenerators
  baseGenerators := baseGenerators
  complementGenerators := complementGenerators
  baseOrder := 64
  complementOrder := 27
  baseCayley := baseEncoded.toCayley
  complementCayley := complementEncoded.toCayley
  baseRowsInjective := baseRowsInjective
  complementRowsInjective := complementRowsInjective
  baseInSource := baseInSource
  complementInSource := complementInSource
  sourceBaseWords := sourceBaseWord
  sourceComplementWords := sourceComplementWord
  sourceFactorization := by decide +kernel
  conjugateWords := conjugates

theorem base_card : Nat.card certificate.base = 64 :=
  certificate.base_card

theorem complement_card : Nat.card certificate.complement = 27 :=
  certificate.complement_card

theorem base_normal_in_action :
    (certificate.base.subgroupOf certificate.action).Normal :=
  certificate.base_normal_in_action

theorem action_join :
    certificate.actionBase ⊔ certificate.actionComplement = ⊤ :=
  certificate.action_join

end SymmetricSubgroupAsymptotics.TernaryV4Semidirect12T228
