import SymmetricSubgroupAsymptotics.InducedDualEquivalence
import SymmetricSubgroupAsymptotics.RepresentationDualSubquotientGenerators
import SymmetricSubgroupAsymptotics.TraceyAffineInducedModuleInput

/-!
# Refined published induced-module capacities

This is the exact numerical specialization of Tracey's induced-module
generator theorem used by the affine block argument.  Besides the uniform
half and logarithmic bounds, it retains the prime-to-characteristic,
primary square-root and prime-power soluble-transitive bounds.  The latter
is available for a transitive action of prime-power degree by applying the
soluble alternative to a transitive Sylow subgroup.

The record contains only numerical consequences of the published theorem.
All identifications of an actual wreath kernel with an induced subquotient,
all dual transport, and all subsequent margin arithmetic are proved in the
project.
-/

set_option autoImplicit false
noncomputable section
open scoped Classical MonoidAlgebra

namespace SymmetricSubgroupAsymptotics

universe u

/-- A uniform generating bound survives padding every retained
subrepresentation to a common longer tuple. -/
theorem uniformSubrepresentationGeneratorBound_mono
    {k G V : Type u} [Field k] [Group G]
    [AddCommGroup V] [Module k V]
    (rho : Representation k G V) {n H : ℕ}
    (h : UniformSubrepresentationGeneratorBound rho n)
    (hnH : n ≤ H) :
    UniformSubrepresentationGeneratorBound rho H := by
  intro M
  exact representationGeneratedBy_mono M.toRepresentation hnH (h M)

/-- Simultaneous numerical ceilings for one induced representation.  The
prime-to-characteristic field may use any displayed prime-power divisor;
the published largest-prime-power denominator is at least that large. -/
structure TraceyRefinedInducedCapacityBounds
    (p a s : ℕ) (H : ℝ) : Prop where
  half : H ≤ (a : ℝ) * s / 2
  logarithmic : H ≤ traceyInducedGeneratorCeiling a s
  primeTo : ∀ (q e : ℕ), q.Prime → q ≠ p → 1 ≤ e → q ^ e ∣ s →
    (H : ℝ) ≤ (a : ℝ) * s / q ^ e
  primary : ∀ (e : ℕ), 1 ≤ e → p ^ e ∣ s → ¬ p ^ (e + 1) ∣ s →
    (H : ℝ) ≤ (a : ℝ) * s *
      Real.sqrt (2 / (3 * ((p : ℝ) - 1) * e))
  primePower : ∀ (q e : ℕ), q.Prime → 1 ≤ e → s = q ^ e →
    let k := e * (q - 1)
    (H : ℝ) ≤ (a : ℝ) * s * Nat.choose k (k / 2) / 2 ^ k

namespace TraceyRefinedInducedCapacityBounds

/-- Two bounds with the same local parameters can be padded to their common
maximum without losing any retained numerical inequality. -/
theorem max
    {p a s H K : ℕ}
    (hH : TraceyRefinedInducedCapacityBounds p a s H)
    (hK : TraceyRefinedInducedCapacityBounds p a s K) :
    TraceyRefinedInducedCapacityBounds p a s (max H K) where
  half := by
    exact max_le hH.half hK.half
  logarithmic := by
    exact max_le hH.logarithmic hK.logarithmic
  primeTo q e hq hqp he hdiv := by
    exact max_le (hH.primeTo q e hq hqp he hdiv)
      (hK.primeTo q e hq hqp he hdiv)
  primary e he hdiv hmax := by
    exact max_le (hH.primary e he hdiv hmax)
      (hK.primary e he hdiv hmax)
  primePower q e hq he hs := by
    exact max_le (hH.primePower q e hq he hs)
      (hK.primePower q e hq he hs)

end TraceyRefinedInducedCapacityBounds

/-- Published Tracey input in the exact common form needed here.  Every
subrepresentation of the literal induced representation is generated by
one tuple length satisfying all numerical ceilings simultaneously. -/
def TraceyRefinedInducedModuleInput : Prop :=
  ∀ (p : ℕ) [Fact p.Prime]
    (G : Type) [Group G] [Finite G]
    (Hsub : Subgroup G), 2 ≤ Hsub.index →
    ∀ (V : Type) [AddCommGroup V] [Module (ZMod p) V]
      [FiniteDimensional (ZMod p) V]
      (rho : Representation (ZMod p) Hsub V),
      ∃ H : ℕ,
        TraceyRefinedInducedCapacityBounds p
          (Module.finrank (ZMod p) V) Hsub.index (H : ℝ) ∧
        UniformSubrepresentationGeneratorBound
          (Representation.ind Hsub.subtype rho) H

namespace TraceyRefinedInducedModuleInput

/-- The published bound applied to the dual local representation and
transported through finite-index induced duality. -/
theorem dual
    (hTracey : TraceyRefinedInducedModuleInput)
    {p : ℕ} [Fact p.Prime]
    (G : Type) [Group G] [Finite G]
    (Hsub : Subgroup G) (hindex : 2 ≤ Hsub.index)
    (V : Type) [AddCommGroup V] [Module (ZMod p) V]
      [FiniteDimensional (ZMod p) V]
    (rho : Representation (ZMod p) Hsub V) :
    ∃ H : ℕ,
      TraceyRefinedInducedCapacityBounds p
        (Module.finrank (ZMod p) V) Hsub.index (H : ℝ) ∧
      UniformSubrepresentationGeneratorBound
        (Representation.ind Hsub.subtype rho).dual H := by
  obtain ⟨H, hbounds, hlocal⟩ := hTracey p G Hsub hindex
    (Module.Dual (ZMod p) V) rho.dual
  let e := InducedDualEquivalence.inducedDualEquiv Hsub rho
  have htransport := UniformSubrepresentationGeneratorBound.of_injective
    hlocal e.symm.toIntertwiningMap e.symm.injective
  refine ⟨H, ?_, ?_⟩
  · simpa only [Subspace.dual_finrank_eq] using hbounds
  · simpa only [Subspace.dual_finrank_eq] using htransport

end TraceyRefinedInducedModuleInput
end SymmetricSubgroupAsymptotics

end
