#!/usr/bin/env python3
"""Check recorded centres and central involution subgroups in actual quotients.

The dimension and strict integer criterion are finite menu facts. The
faithful irreducible tuple and source character-count bounds are separate
analytic obligations, not conclusions of these certificates.
"""
from pathlib import Path
import argparse,gzip,json
from export_lean_normal_registry import ROOT,action_data,perm,inv,finfun
from export_lean_menu_cayley import compose,lookup,checks
OUT=ROOT/'formal/SymmetricSubgroupAsymptotics/GeneratedCharacter8'

def emit(node,record):
 label=node['id'][1:].replace('_','T');gs,st,source,si,normals=action_data(node,record);n=len(source)
 records=[(i,x) for i,x in enumerate(record['normals']) if x['kind']=='character']
 s=f'''import SymmetricSubgroupAsymptotics.BinaryNormalCharacterCriterion
import Mathlib.Algebra.Group.TransferInstance
import SymmetricSubgroupAsymptotics.GeneratedNormal8.Registry{label}

/-! Exact recorded centres and central involution subgroups of the
original quotients for {label}. Analytic character counting is separate. -/
set_option autoImplicit false
set_option maxHeartbeats 0
set_option maxRecDepth 100000
noncomputable section
namespace SymmetricSubgroupAsymptotics.BinaryNormalCharacters{label}
local instance : Group BinaryNormal{label}.Source := BinaryMenuCayley{label}.group
'''
 for i,nr in records:
  nd=normals[i];q=len(nd['reps']);qi={nd['keys'][p]:j for j,p in enumerate(nd['reps'])};qindex=lambda p:qi[nd['keys'][p]]
  cg=perm(nr['centre_lift_generators'][0]);og=perm(nr['omega_lift_generators'][0]);cr=qindex(cg);orr=qindex(og)
  centre=[0];x=cg
  while qindex(x):centre.append(qindex(x));x=compose(x,cg)
  c=len(centre);omega=[0,orr];z=nr['z'];assert z==1 and len(nr['centre_lift_generators'])==1 and len(nr['omega_lift_generators'])==1
  swc=nd['ni'][compose(nd['reps'][cr],inv(cg))];swo=nd['ni'][compose(nd['reps'][orr],inv(og))];nk=len(nd['ns'])
  s+=f'''\nnamespace N{i}
abbrev state := BinaryNormal{label}.N{i}.state
structure Row where
  index : Fin {q}
  deriving DecidableEq,Fintype
private def rowEquiv : Row ≃ state.Row where
  toFun x := ⟨x.index⟩
  invFun x := ⟨x.index⟩
  left_inv _ := rfl
  right_inv _ := rfl
def originalRowEquiv := state.quotientEquiv BinaryNormal{label}.generators_full
def centreLift : BinaryNormal{label}.Source := ⟨({si[cg]} : Fin {n})⟩
def omegaLift : BinaryNormal{label}.Source := ⟨({si[og]} : Fin {n})⟩
def centreClass := QuotientGroup.mk' BinaryNormal{label}.N{i}.kernel centreLift
def omegaClass := QuotientGroup.mk' BinaryNormal{label}.N{i}.kernel omegaLift
private theorem centreLift_mem : state.cosets.representatives {cr}/centreLift∈state.kernel := by
  have he : state.cosets.representatives {cr}/centreLift=
      (⟨BinaryNormal{label}.N{i}.normalCertificate.rows {swc}⟩ : BinaryNormal{label}.Source) := by
    decide +kernel
  rw [he]
  exact binaryNormalRow_mem BinaryNormal{label}.N{i}.normalCertificate {swc}
private theorem omegaLift_mem : state.cosets.representatives {orr}/omegaLift∈state.kernel := by
  have he : state.cosets.representatives {orr}/omegaLift=
      (⟨BinaryNormal{label}.N{i}.normalCertificate.rows {swo}⟩ : BinaryNormal{label}.Source) := by
    decide +kernel
  rw [he]
  exact binaryNormalRow_mem BinaryNormal{label}.N{i}.normalCertificate {swo}
section Rows
local instance : Group Row := by
  letI : Group state.Row := state.group BinaryNormal{label}.generators_full
  exact rowEquiv.group

def centreGenerator : Row := ⟨({cr} : Fin {q})⟩
def omegaGenerator : Row := ⟨({orr} : Fin {q})⟩
private def centreRows (j : Fin {c}) : Row := ⟨{finfun(centre,q,'j.val')}⟩
private def omegaRows (j : Fin 2) : Row := ⟨{finfun(omega,q,'j.val')}⟩

def centreCertificate : FiniteCayleyCertificate (fun _ : Fin 1 => centreGenerator) {c} where
  elements := centreRows
  identity := 0
  identity_eq := by decide +kernel
  next j _ := Fin.ofNat {c} (j.val+1)
  next_eq := by decide +kernel
  words j := List.replicate j.val 0
  words_eq := by decide +kernel

def omegaCertificate : FiniteCayleyCertificate (fun _ : Fin 1 => omegaGenerator) 2 where
  elements := omegaRows
  identity := 0
  identity_eq := by decide +kernel
  next j _ := Fin.ofNat 2 (j.val+1)
  next_eq := by decide +kernel
  words j := List.replicate j.val 0
  words_eq := by decide +kernel

/-- The whole original quotient centre, not a selected central subgroup. -/
theorem centre_complete : Subgroup.center Row=
    Subgroup.closure (Set.range (fun _ : Fin 1 => centreGenerator)) := by
  ext x
  rw [Subgroup.mem_center_iff,centreCertificate.mem_closure_iff]
  have hc : ∀ x : Row, (∀ y, y*x=x*y) ↔ ∃ j, centreCertificate.elements j=x := by
    decide +kernel
  exact hc x

/-- The complete central involution subgroup is generated by the retained
original omega lift; a proper subspace would fail this equality. -/
theorem omega_complete (x : Row) :
    (x∈Subgroup.center Row ∧ x^2=1) ↔ ∃ j, omegaCertificate.elements j=x := by
  rw [Subgroup.mem_center_iff]
  exact (by decide +kernel : ∀ x : Row, ((∀ y, y*x=x*y) ∧ x^2=1) ↔
    ∃ j, omegaCertificate.elements j=x) x

theorem omega_card : Nat.card (binaryCentralOmega Row)=2 := by
  rw [Nat.card_congr (binaryCentralOmegaEquiv Row)]
  letI : DecidablePred (fun x : Row => x∈Subgroup.center Row ∧ x^2=1) :=
    fun x => inferInstance
  rw [Nat.card_eq_fintype_card]
  decide +kernel

theorem centreGenerator_original : originalRowEquiv
    (rowEquiv centreGenerator)=centreClass := by
  rw [originalRowEquiv,BinaryNormalState.quotientEquiv,BinaryNormalCosetCertificate.rowQuotientEquiv_apply]
  exact QuotientGroup.eq_iff_div_mem.mpr centreLift_mem

theorem omegaGenerator_original : originalRowEquiv
    (rowEquiv omegaGenerator)=omegaClass := by
  rw [originalRowEquiv,BinaryNormalState.quotientEquiv,BinaryNormalCosetCertificate.rowQuotientEquiv_apply]
  exact QuotientGroup.eq_iff_div_mem.mpr omegaLift_mem

def criterion : BinaryNormalCharacterCriterion Row 8 where
  dimension := 1
  cardinal := by simpa using omega_card
  gap := by decide +kernel

def originalEquiv : Row ≃* (BinaryNormal{label}.Source ⧸ BinaryNormal{label}.N{i}.kernel) := by
  letI : Group state.Row := state.group BinaryNormal{label}.generators_full
  exact rowEquiv.mulEquiv.trans originalRowEquiv

/-- The criterion transfers to the actual original quotient U/N. -/
def originalQuotientCriterion : BinaryNormalCharacterCriterion
    (BinaryNormal{label}.Source ⧸ BinaryNormal{label}.N{i}.kernel) 8 :=
  criterion.transport originalEquiv

end Rows

abbrev Original := Subgroup.closure (Set.range BinaryMenuCayley{label}.generators)
def physicalNormal : Subgroup Original :=
  BinaryNormal{label}.N{i}.kernel.map BinaryMenuCayley{label}.originalEquiv.toMonoidHom
instance physicalNormal_normal : physicalNormal.Normal :=
  Subgroup.Normal.map inferInstance _ BinaryMenuCayley{label}.originalEquiv.surjective

def physicalCriterion : BinaryNormalCharacterCriterion (Original ⧸ physicalNormal) 8 :=
  originalQuotientCriterion.transport (QuotientGroup.congr BinaryNormal{label}.N{i}.kernel
    physicalNormal BinaryMenuCayley{label}.originalEquiv rfl)

theorem physical_dimension :
    Module.finrank (ZMod 2) (Additive (binaryCentralOmega (Original ⧸ physicalNormal)))=1 :=
  physicalCriterion.exact_dimension

end N{i}
'''
 s+=f'end SymmetricSubgroupAsymptotics.BinaryNormalCharacters{label}\n'
 return OUT/f'Characters{label}.lean',s

def main():
 ap=argparse.ArgumentParser(description=__doc__);ap.add_argument('--node',action='append');ap.add_argument('--check',action='store_true');args=ap.parse_args()
 with gzip.open(ROOT/'certificates/data/binary_menu.jsonl.gz','rt') as f:
  meta=json.loads(next(f));records={x['id']:x for line in f if (x:=json.loads(line)).get('kind')=='action'}
 nodes={n['id']:n for n in meta['nodes']};selected=args.node or [k for k,n in nodes.items() if n['degree']==8 and any(r['kind']=='character' for r in records[k]['normals'])]
 OUT.mkdir(exist_ok=True)
 for name in selected:
  path,s=emit(nodes[name],records[name]);b=s.encode()
  if args.check:
   if not path.exists() or path.read_bytes()!=b:raise SystemExit(f'Stale generated file {path}')
  elif not path.exists() or path.read_bytes()!=b:path.write_bytes(b)
  print(path.relative_to(ROOT),flush=True)
if __name__=='__main__':main()
