#!/usr/bin/env python3
"""Export literal quotient-row normal registries (the original width-8 menu).

The generated Lean checks every normal Cayley edge, original-generator
conjugation, quotient coset edge, and central-involution child. Python and
input orders are not trusted proof premises. Acceptance of each registered
pair/character/transport record is a separate semantic certificate.
"""
from pathlib import Path
import argparse, gzip, json
from export_lean_menu_cayley import table, packed, lookup, checks, compose
ROOT=Path(__file__).resolve().parents[2]
OUT=ROOT/'formal/SymmetricSubgroupAsymptotics/GeneratedNormal8'

def inv(p): return tuple(p.index(x) for x in range(len(p)))
def unpack(c,w): return tuple((c//w**i)%w for i in range(w))
def perm(p): return tuple(x-1 for x in p)
def arr(a): return '#['+','.join(map(str,a))+']'
def fun(v,t,index='i.val'): return f'({lookup(v,index)} : {t})'
def mat(a,t='ℕ'): return f'({lookup([arr(r) for r in a])} : Array ({t}))[j.val]!'
def finfun(v,n,index='i.val'): return fun(v,f'Fin {n}',index)

def action_data(node, record):
    w=node['degree']; gs=list(map(perm,node['generators'])); st=table(gs,w)
    source=[unpack(c,w) for c in st['codes']]; si={p:i for i,p in enumerate(source)}
    normals=[]
    for nr in record['normals']:
        ng=list(map(perm,nr['normal_generators'])); nt=table(ng,w)
        ns=[unpack(c,w) for c in nt['codes']]; ni={p:i for i,p in enumerate(ns)}
        keys={p:min(si[compose(x,p)] for x in ns) for p in source}
        reps=[tuple(range(w))]; qi={keys[reps[0]]:0}; parents=[0];letters=[0];nxt=[]
        for i,p in enumerate(reps):
            row=[]
            for j,g in enumerate(gs):
                x=compose(p,g);k=keys[x]
                if k not in qi:
                    qi[k]=len(reps);reps.append(x);parents.append(i);letters.append(j)
                row.append(qi[k])
            nxt.append(row)
        prev=[[0]*len(gs) for _ in reps]
        for i,row in enumerate(nxt):
            for j,k in enumerate(row):prev[k][j]=i
        pos=[[ni[compose(compose(g,x),inv(g))] for x in ng] for g in gs]
        neg=[[ni[compose(compose(inv(g),x),g)] for x in ng] for g in gs]
        sw=[[ni[compose(reps[nxt[i][j]], inv(compose(p,g))) ] for j,g in enumerate(gs)] for i,p in enumerate(reps)]
        normals.append(dict(record=nr,ng=ng,nt=nt,ns=ns,ni=ni,source_indices=[si[p] for p in ns],
            gen_indices=[si[p] for p in ng],reps=reps,rep_indices=[si[p] for p in reps],
            parents=parents,letters=letters,next=nxt,prev=prev,pos=pos,neg=neg,sw=sw,keys=keys))
    return gs,st,source,si,normals

def emit(node,record):
    w=node['degree'];label=node['id'][1:].replace('_','T');assert w==8
    gs,st,source,si,normals=action_data(node,record);n=len(source);d=len(gs)
    s=f'''import SymmetricSubgroupAsymptotics.BinaryNormalGeneratorChecks
import SymmetricSubgroupAsymptotics.BinaryMenuCayley{label}

/-! Exact original normal states and quotient rows for {label}.
Generated by export_lean_normal_registry.py; all finite facts are checked
in Lean's kernel. This file certifies normal-state coverage, not the later
pair/character/transport acceptance of those states. -/

set_option autoImplicit false
set_option maxRecDepth 100000
set_option maxHeartbeats 0
set_option linter.unusedVariables false
noncomputable section
namespace SymmetricSubgroupAsymptotics.BinaryNormal{label}

abbrev Source := FiniteGroupRow {n}
local instance : Group Source := BinaryMenuCayley{label}.group

def generators (j : Fin {d}) : Source :=
  ⟨BinaryMenuCayley{label}.certificate.next BinaryMenuCayley{label}.certificate.identity j⟩

theorem generators_full : Subgroup.closure (Set.range generators)=⊤ := by
  apply binaryNormal_full_generators_of_equiv BinaryMenuCayley{label}.generators
    generators BinaryMenuCayley{label}.originalEquiv
  intro j
  change BinaryMenuCayley{label}.certificate.toCayley.elements
    (BinaryMenuCayley{label}.certificate.toCayley.next
      BinaryMenuCayley{label}.certificate.toCayley.identity j)=_
  rw [FiniteCayleyCertificate.next_eq,FiniteCayleyCertificate.identity_eq,one_mul]

theorem source_card : Nat.card Source={n} := by
  rw [Nat.card_eq_fintype_card]
  rfl

'''
    for idx,nd in enumerate(normals):
        nt=nd['nt'];k=len(nd['ns']);r=len(nd['ng']);q=len(nd['reps']);ident=nt['identity']
        ng_expr=f'⟨{finfun(nd["gen_indices"],n,"j.val")}⟩' if r else 'Fin.elim0 j'
        next_expr=mat(nt['next'],f'Fin {k}') if r else 'Fin.elim0 j'
        letters=finfun(nt['letter'],r) if r else None
        letter_def='letters i' if r else f'False.elim (hi (Subsingleton.elim i ({ident} : Fin {k})))'
        s+=f'''namespace N{idx}
def normalGenerators (j : Fin {r}) : Source := {ng_expr}
def kernel : Subgroup Source := Subgroup.closure (Set.range normalGenerators)
private def rows (i : Fin {k}) : Fin {n} := {finfun(nd['source_indices'],n)}
private def next (i : Fin {k}) (j : Fin {r}) : Fin {k} := {next_expr}
private def rank (i : Fin {k}) : ℕ := {lookup(nt['rank'])}
private def parents (i : Fin {k}) : Fin {k} := {finfun(nt['parent'],k)}
'''
        if r:s+=f'private def letters (i : Fin {k}) : Fin {r} := {letters}\n'
        s+=f'''
def normalCertificate : EncodedCayleyCertificate (binaryNormalRowEncoding normalGenerators) {k} where
  rows := rows
  identity := {ident}
  identity_eq := by decide +kernel
  next := next
  next_eq := {checks(k)}
  rank := rank
  parent i _ := parents i
  letter i hi := {letter_def}
  parent_lt := {checks(k)}
  parent_next := {checks(k)}

theorem normalRows_injective : Function.Injective normalCertificate.rows := by decide +kernel

theorem kernel_card : Nat.card kernel={k} := normalCertificate.card_closure normalRows_injective

theorem row_mem (i : Fin {k}) : (⟨rows i⟩ : Source)∈kernel :=
  binaryNormalRow_mem normalCertificate i

'''
        if r:
            s+=f'''private def posWitness (i : Fin {d}) (j : Fin {r}) : Fin {k} := {mat(nd['pos'],f'Fin {k}')}
private def negWitness (i : Fin {d}) (j : Fin {r}) : Fin {k} := {mat(nd['neg'],f'Fin {k}')}
private theorem pos_checked : ∀ i j, generators i*normalGenerators j*(generators i)⁻¹=
    (⟨rows (posWitness i j)⟩ : Source) := by decide +kernel
private theorem neg_checked : ∀ i j, (generators i)⁻¹*normalGenerators j*generators i=
    (⟨rows (negWitness i j)⟩ : Source) := by decide +kernel

instance normal : kernel.Normal := binaryNormal_of_generator_conjugates generators generators_full
  normalGenerators (fun i j => (pos_checked i j) ▸ row_mem (posWitness i j))
  (fun i j => (neg_checked i j) ▸ row_mem (negWitness i j))
'''
        else:
            s+='''instance normal : kernel.Normal := binaryNormal_of_generator_conjugates generators generators_full
  normalGenerators (fun _ j => Fin.elim0 j) (fun _ j => Fin.elim0 j)
'''
        s+=f'''
private def representatives (i : Fin {q}) : Source := ⟨{finfun(nd['rep_indices'],n)}⟩
private def quotientNext (i : Fin {q}) (j : Fin {d}) : Fin {q} := {mat(nd['next'],f'Fin {q}')}
private def quotientPrev (i : Fin {q}) (j : Fin {d}) : Fin {q} := {mat(nd['prev'],f'Fin {q}')}
private def quotientParents (i : Fin {q}) : Fin {q} := {finfun(nd['parents'],q)}
private def quotientLetters (i : Fin {q}) : Fin {d} := {finfun(nd['letters'],d)}
private def stepWitness (i : Fin {q}) (j : Fin {d}) : Fin {k} := {mat(nd['sw'],f'Fin {k}')}
private theorem quotientStep_checked : ∀ i j,
    representatives (quotientNext i j)/(representatives i*generators j)=
      (⟨rows (stepWitness i j)⟩ : Source) := {checks(q)}

def cosets : BinaryNormalCosetCertificate generators kernel {q} where
  representatives := representatives
  identity := 0
  identity_mem := by
    have he : representatives 0=(⟨rows {ident}⟩ : Source) := by decide +kernel
    exact he ▸ row_mem {ident}
  next := quotientNext
  step_mem := fun i j => (quotientStep_checked i j) ▸ row_mem (stepWitness i j)
  rank i := i.val
  parent i _ := quotientParents i
  letter i _ := quotientLetters i
  parent_lt := {checks(q)}
  parent_next := {checks(q)}

@[reducible] def state : BinaryNormalState generators where
  kernel := kernel
  normal := normal
  generatorCount := {r}
  normalGenerators := normalGenerators
  generated := rfl
  quotientCount := {q}
  cardinal := by rw [kernel_card,source_card]
  cosets := cosets
  prev := quotientPrev
  prev_next := {checks(q)}

end N{idx}

'''
    s+=f'''@[reducible] def states (i : Fin {len(normals)}) : BinaryNormalState generators :=
  {lookup([f'N{i}.state' for i in range(len(normals))])}

end SymmetricSubgroupAsymptotics.BinaryNormal{label}
'''
    return OUT/f'States{label}.lean',s

def emit_registry(node,record):
    label=node['id'][1:].replace('_','T');gs,st,source,si,normals=action_data(node,record)
    n=len(source);d=len(gs);m=len(normals)
    normal_lookup={frozenset(nd['ns']):i for i,nd in enumerate(normals)}
    bottom=normal_lookup[frozenset([tuple(range(node['degree']))])]
    s=f'''import SymmetricSubgroupAsymptotics.GeneratedNormal8.States{label}

/-! All original normal subgroups of {label}, by checked central-involution
closure in the complete literal quotient rows. Acceptance is separate. -/
set_option autoImplicit false
set_option maxRecDepth 100000
set_option maxHeartbeats 0
set_option linter.unusedVariables false
noncomputable section
namespace SymmetricSubgroupAsymptotics.BinaryNormal{label}
local instance : Group Source := BinaryMenuCayley{label}.group

'''
    for i,nd in enumerate(normals):
        q=len(nd['reps']);r=len(nd['ng']);nsset=set(nd['ns']);children=[];iscentral=[]
        for p in nd['reps']:
            central=p not in nsset and compose(p,p) in nsset and all(compose(compose(p,g),inv(compose(g,p))) in nsset for g in gs)
            iscentral.append(central)
            if central:
                enlarged=table(nd['ng']+[p],node['degree']);elems=frozenset(unpack(c,node['degree']) for c in enlarged['codes'])
                child=normal_lookup[elems]
                assert child+1 in nd['record']['children']
            else:child=bottom
            children.append(child)
        s+=f'''private def child{i} (z : N{i}.state.Row) : Fin {m} :=
  {finfun(children,m,'z.index.val')}

private theorem child{i}_generator_mem (z : N{i}.state.Row)
    (hz : N{i}.state.CentralInvolution generators_full z) :
    ∀ j, N{i}.normalGenerators j ∈ (states (child{i} z)).kernel := by
  have ht := N{i}.state.centralInvolution_rowTests generators_full z hz
  rcases z with ⟨z⟩
  fin_cases z
'''
        for z,(central,child) in enumerate(zip(iscentral,children)):
            if not central:
                s+=f'''  · have hf : ¬N{i}.state.centralRowTests generators_full ⟨({z} : Fin {q})⟩ := by unfold BinaryNormalState.centralRowTests; decide +kernel
    exact False.elim (hf ht)
'''
            elif not r:
                s+='''  · intro j
    exact Fin.elim0 j
'''
            else:
                nw=[normals[child]['ni'][g] for g in nd['ng']];nk=len(normals[child]['ns'])
                s+=f'''  · change ∀ j, N{i}.normalGenerators j ∈ N{child}.kernel
    intro j
    have he : ∀ j : Fin {r}, N{i}.normalGenerators j=
        (⟨N{child}.normalCertificate.rows ({finfun(nw,nk,'j.val')})⟩ : Source) := by decide +kernel
    rw [he]
    exact binaryNormalRow_mem N{child}.normalCertificate _
'''
        s+=f'''
private theorem child{i}_lift_mem (z : N{i}.state.Row)
    (hz : N{i}.state.CentralInvolution generators_full z) :
    N{i}.cosets.representatives z.index ∈ (states (child{i} z)).kernel := by
  have ht := N{i}.state.centralInvolution_rowTests generators_full z hz
  rcases z with ⟨z⟩
  fin_cases z
'''
        for z,(central,child) in enumerate(zip(iscentral,children)):
            if not central:
                s+=f'''  · have hf : ¬N{i}.state.centralRowTests generators_full ⟨({z} : Fin {q})⟩ := by unfold BinaryNormalState.centralRowTests; decide +kernel
    exact False.elim (hf ht)
'''
            else:
                witness=normals[child]['ni'][nd['reps'][z]]
                s+=f'''  · change N{i}.cosets.representatives {z} ∈ N{child}.kernel
    have he : N{i}.cosets.representatives {z}=
        (⟨N{child}.normalCertificate.rows {witness}⟩ : Source) := by decide +kernel
    rw [he]
    exact binaryNormalRow_mem N{child}.normalCertificate _
'''
        s+=f'''
private theorem child{i}_card (z : N{i}.state.Row)
    (hz : N{i}.state.CentralInvolution generators_full z) :
    Nat.card (states (child{i} z)).kernel=Nat.card N{i}.kernel*2 := by
  have ht := N{i}.state.centralInvolution_rowTests generators_full z hz
  rcases z with ⟨z⟩
  fin_cases z
'''
        for z,(central,child) in enumerate(zip(iscentral,children)):
            if not central:
                s+=f'''  · have hf : ¬N{i}.state.centralRowTests generators_full ⟨({z} : Fin {q})⟩ := by unfold BinaryNormalState.centralRowTests; decide +kernel
    exact False.elim (hf ht)
'''
            else:s+=f'''  · change Nat.card N{child}.kernel=Nat.card N{i}.kernel*2
    rw [N{child}.kernel_card,N{i}.kernel_card]
'''
        s+='\n'
    child_expr='(fun i => Fin.elim0 i)'
    for i in reversed(range(m)):child_expr=f'(Fin.cases child{i} {child_expr})'
    s+=f'''private def child : (i : Fin {m}) → (states i).Row → Fin {m} :=
  {child_expr}
'''
    s+=f'''
def registry : BinaryNormalRegistry generators generators_full states where
  bottom := {bottom}
  bottom_kernel := by
    change Subgroup.closure (Set.range N{bottom}.normalGenerators)=⊥
    rw [show Set.range N{bottom}.normalGenerators=∅ by ext x; simp]
    exact Subgroup.closure_empty
  child := child
  generator_mem := by
    intro i
    fin_cases i
'''
    for i in range(m):s+=f'    · exact child{i}_generator_mem\n'
    s+='''  lift_mem := by
    intro i
    fin_cases i
'''
    for i in range(m):s+=f'    · exact child{i}_lift_mem\n'
    s+='''  child_card := by
    intro i
    fin_cases i
'''
    for i in range(m):s+=f'    · exact child{i}_card\n'
    s+=f'''
theorem source_isPGroup : IsPGroup 2 Source :=
  IsPGroup.of_card (n := {n.bit_length()-1}) (by rw [source_card]; rfl)

/-- Every literal normal subgroup of the original faithful source appears.
There is no finite classification or producer-order assumption. -/
theorem complete (N : Subgroup Source) [N.Normal] :
    ∃ i, (states i).kernel=N := registry.complete source_isPGroup N

/-- Any semantic acceptance proved at all listed original normal states
holds for every actual normal subgroup of this source. -/
theorem all_normal_accepted (Accept : Subgroup Source → Prop)
    (haccept : ∀ i, Accept (states i).kernel)
    (N : Subgroup Source) [N.Normal] : Accept N :=
  registry.all_normal_accepted source_isPGroup Accept haccept N

end SymmetricSubgroupAsymptotics.BinaryNormal{label}
'''
    return OUT/f'Registry{label}.lean',s

def main():
    ap=argparse.ArgumentParser(description=__doc__);ap.add_argument('--node',action='append');ap.add_argument('--check',action='store_true');args=ap.parse_args()
    with gzip.open(ROOT/'certificates/data/binary_menu.jsonl.gz','rt') as f:
        meta=json.loads(next(f));records={x['id']:x for line in f if (x:=json.loads(line)).get('kind')=='action'}
    nodes={n['id']:n for n in meta['nodes']}; selected=args.node or [k for k,n in nodes.items() if n['degree']==8 and records[k]['normals']]
    OUT.mkdir(exist_ok=True)
    for name in selected:
        for path,s in [emit(nodes[name],records[name]),emit_registry(nodes[name],records[name])]:
            b=s.encode()
            if args.check:
                if not path.exists() or path.read_bytes()!=b:raise SystemExit(f'Stale generated file {path}')
            elif not path.exists() or path.read_bytes()!=b:path.write_bytes(b)
            print(path.relative_to(ROOT))
if __name__=='__main__':main()
