#!/usr/bin/env python3
"""Export the bounded almost-simple primitive index receipt to Lean.

The source is the committed primitive/rank JSONL stream.  This exporter keeps
only the 116 primitive rows of degrees 5 through 29 whose recorded socle is
simple and nonabelian.  It emits the catalogue locator and the actual quotient
order `|G:S|`; every inequality `2 |G:S| <= degree` is then proved by Lean's
kernel.  Catalogue completeness and identification of an arbitrary action
with a locator are deliberately outside this numerical receipt.
"""

from __future__ import annotations

import argparse
import gzip
import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
DATA = ROOT / "certificates/data/primitive_rank.jsonl.gz"
OUTPUT = (
    ROOT
    / "formal/SymmetricSubgroupAsymptotics/PrimitiveBoundedIndexReceipt.lean"
)


def selected_rows() -> list[tuple[int, int, int]]:
    rows: list[tuple[int, int, int]] = []
    with gzip.open(DATA, "rt", encoding="utf-8") as source:
        for line in source:
            record = json.loads(line)
            if (
                record.get("catalogue") == "primitive"
                and 5 <= record["degree"] <= 29
                and record.get("socle_simple") is True
                and record.get("socle_abelian") is False
            ):
                rows.append(
                    (
                        record["degree"],
                        record["index"],
                        record["socle_cover_degree"],
                    )
                )
    if len(rows) != 116:
        raise RuntimeError(f"expected 116 bounded simple-socle rows, got {len(rows)}")
    if len({(degree, index) for degree, index, _ in rows}) != len(rows):
        raise RuntimeError("duplicate primitive catalogue locator")
    bad = [row for row in rows if 2 * row[2] > row[0]]
    if bad:
        raise RuntimeError(f"bounded quotient-index inequality failed: {bad}")
    return rows


def render(rows: list[tuple[int, int, int]]) -> str:
    digest = hashlib.sha256(DATA.read_bytes()).hexdigest()
    entries = "\n".join(
        "  { degree := %d, catalogueIndex := %d, outerOrder := %d,\n"
        "    index_bound := by omega },"
        % (degree, index, outer_order)
        for degree, index, outer_order in rows
    )
    return f"""import SymmetricSubgroupAsymptotics.PrimitiveSemisimpleBoundedIndexExhaustion

/-!
# Kernel-checked bounded primitive quotient-index receipt

Generated by `computations/python/export_lean_primitive_bounded_index.py`
from `certificates/data/primitive_rank.jsonl.gz` (compressed SHA256
`{digest}`).  The 116 entries are precisely the primitive catalogue rows of
degrees 5 through 29 with a recorded simple nonabelian socle.

This file proves only the finite numerical inequality.  The published
primitive classification and the correspondence between an arbitrary literal
action and one of these catalogue locators remain separate obligations.
-/

set_option autoImplicit false

namespace SymmetricSubgroupAsymptotics

/-- One checked bounded almost-simple primitive catalogue row. -/
structure PrimitiveBoundedIndexRow where
  degree : ℕ
  catalogueIndex : ℕ
  outerOrder : ℕ
  index_bound : 2 * outerOrder ≤ degree

/-- All simple-nonabelian-socle primitive rows in degrees 5 through 29. -/
def primitiveBoundedIndexRows : Array PrimitiveBoundedIndexRow := #[
{entries}]

theorem primitiveBoundedIndexRows_size :
    primitiveBoundedIndexRows.size = 116 := by
  decide +kernel

/-- Typed access to the complete numerical receipt. -/
def primitiveBoundedIndexRow (i : Fin 116) : PrimitiveBoundedIndexRow :=
  primitiveBoundedIndexRows[i.val]'(by
    rw [primitiveBoundedIndexRows_size]
    exact i.isLt)

theorem primitiveBoundedIndexRow_bound (i : Fin 116) :
    2 * (primitiveBoundedIndexRow i).outerOrder ≤
      (primitiveBoundedIndexRow i).degree :=
  (primitiveBoundedIndexRow i).index_bound

end SymmetricSubgroupAsymptotics
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify that the committed Lean receipt is current without writing it",
    )
    args = parser.parse_args()
    expected = render(selected_rows())
    if args.check:
        actual = OUTPUT.read_text(encoding="utf-8")
        if actual != expected:
            raise SystemExit(f"stale generated receipt: {OUTPUT}")
        print(f"PASS {OUTPUT.relative_to(ROOT)}")
    else:
        OUTPUT.write_text(expected, encoding="utf-8")


if __name__ == "__main__":
    main()
