#!/usr/bin/env python3
"""Export the bounded almost-simple primitive index receipt to Lean.

The source is the committed primitive/rank JSONL stream.  This exporter keeps
only the 116 primitive rows of degrees 5 through 29 whose recorded socle is
simple and nonabelian.  It emits the catalogue locator, the exact group and
socle orders, and the quotient order `|G:S|`.  Lean's kernel checks both the
order factorization and every inequality `2 |G:S| <= degree`.  Catalogue
completeness and identification of an arbitrary action with a locator are
deliberately outside this numerical receipt.
"""

from __future__ import annotations

import argparse
import gzip
import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
DATA = ROOT / "certificates/data/primitive_rank.jsonl.gz"
SPANS = ((5, 11), (12, 18), (19, 24), (25, 29))
NAMES = ("5To11", "12To18", "19To24", "25To29")


def selected_rows() -> list[tuple[int, int, int, int, int]]:
    rows: list[tuple[int, int, int, int, int]] = []
    with gzip.open(DATA, "rt", encoding="utf-8") as source:
        for line in source:
            record = json.loads(line)
            if (
                record.get("catalogue") == "primitive"
                and 5 <= record["degree"] <= 29
                and record.get("socle_simple") is True
                and record.get("socle_abelian") is False
            ):
                quotient_order = record["socle_cover_degree"]
                group_order = record["order"]
                if quotient_order <= 0 or group_order % quotient_order != 0:
                    raise RuntimeError(
                        "invalid simple-socle order factorization at "
                        f"{record['degree']}T{record['index']}"
                    )
                rows.append(
                    (
                        record["degree"],
                        record["index"],
                        group_order,
                        group_order // quotient_order,
                        quotient_order,
                    )
                )
    if len(rows) != 116:
        raise RuntimeError(f"expected 116 bounded simple-socle rows, got {len(rows)}")
    if len({(degree, index) for degree, index, _, _, _ in rows}) != len(rows):
        raise RuntimeError("duplicate primitive catalogue locator")
    bad = [row for row in rows if 2 * row[4] > row[0]]
    if bad:
        raise RuntimeError(f"bounded quotient-index inequality failed: {bad}")
    return rows


def render(
    rows: list[tuple[int, int, int, int, int]], chunk: int
) -> str:
    digest = hashlib.sha256(DATA.read_bytes()).hexdigest()
    lo, hi = SPANS[chunk]
    name = NAMES[chunk]
    chunk_rows = [row for row in rows if lo <= row[0] <= hi]
    entries = "\n".join(
        "  { degree := %d, catalogueIndex := %d, groupOrder := %d,\n"
        "    socleOrder := %d, outerOrder := %d,\n"
        "    order_factorization := by norm_num, index_bound := by omega },"
        % (degree, index, group_order, socle_order, outer_order)
        for degree, index, group_order, socle_order, outer_order in chunk_rows
    )
    return f"""import SymmetricSubgroupAsymptotics.PrimitiveBoundedIndexRow

/-!
# Bounded primitive quotient-index rows in degrees {lo}--{hi}

Generated by `computations/python/export_lean_primitive_bounded_index.py`
from `certificates/data/primitive_rank.jsonl.gz` (compressed SHA256
`{digest}`).  This chunk contains every simple-nonabelian-socle primitive row
in its displayed degree interval.  Lean checks the exact order factorization,
the quotient-index inequality, locator uniqueness, and the degree range.
-/

set_option autoImplicit false

namespace SymmetricSubgroupAsymptotics

/-- The checked rows in degrees {lo} through {hi}. -/
def primitiveBoundedIndexRows{name} : Array PrimitiveBoundedIndexRow := #[
{entries}]

theorem primitiveBoundedIndexRows{name}_size :
    primitiveBoundedIndexRows{name}.size = {len(chunk_rows)} := by
  decide +kernel

theorem primitiveBoundedIndexRows{name}_locators_nodup :
    (primitiveBoundedIndexRows{name}.toList.map
      PrimitiveBoundedIndexRow.locator).Nodup := by
  decide +kernel

theorem primitiveBoundedIndexRows{name}_degree_range
    (row : PrimitiveBoundedIndexRow)
    (hrow : row ∈ primitiveBoundedIndexRows{name}.toList) :
    {lo} ≤ row.degree ∧ row.degree ≤ {hi} := by
  revert row
  decide +kernel

end SymmetricSubgroupAsymptotics
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--chunk", type=int, choices=range(len(SPANS)), required=True)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify that the committed Lean receipt is current without writing it",
    )
    args = parser.parse_args()
    expected = render(selected_rows(), args.chunk)
    output = ROOT / (
        "formal/SymmetricSubgroupAsymptotics/PrimitiveBoundedIndexRows"
        f"{NAMES[args.chunk]}.lean"
    )
    if args.check:
        actual = output.read_text(encoding="utf-8")
        if actual != expected:
            raise SystemExit(f"stale generated receipt: {output}")
        print(f"PASS {output.relative_to(ROOT)}")
    else:
        output.write_text(expected, encoding="utf-8")


if __name__ == "__main__":
    main()
