#!/usr/bin/env python3
"""Export the finite elementary-index-two exclusions for the split frontier.

Only transitive degree-eight tops of order 16 or 32 are relevant.  The three
surviving actions 8T9, 8T10 and 8T18 are omitted.  For every normal state of
the other actions this producer emits either its checked quotient count or a
literal word in its retained normal generators whose square is nontrivial.
Lean checks every assertion; the Python search only chooses short witnesses.
"""

from pathlib import Path
import argparse
import gzip
import json
import sys

sys.dont_write_bytecode = True

from export_lean_menu_cayley import compose
from export_lean_normal_registry import action_data
from export_lean_split_top_normal_registry import complete_record


ROOT = Path(__file__).resolve().parents[2]
OUT = (
    ROOT
    / "formal/SymmetricSubgroupAsymptotics/GeneratedSplitTopNormals"
    / "ElementaryIndexTwoExclusions.lean"
)
NODES = ("b8_6", "b8_7", "b8_8", "b8_11", "b8_15", "b8_16",
         "b8_17", "b8_19", "b8_20", "b8_21", "b8_22")


def inverse(p):
    return tuple(p.index(i) for i in range(len(p)))


def generator_words(generators, width):
    identity = tuple(range(width))
    result = {identity: []}
    todo = [identity]
    for x in todo:
        for j, g in enumerate(generators):
            y = compose(x, g)
            if y not in result:
                result[y] = result[x] + [j]
                todo.append(y)
    return result


def product_expression(namespace, word):
    terms = [f"{namespace}.normalGenerators {j}" for j in word]
    return "*".join(f"({term})" for term in terms)


def membership_expression(word):
    leaves = [f"Subgroup.subset_closure ⟨{j},rfl⟩" for j in word]
    result = leaves[0]
    for leaf in leaves[1:]:
        result = f"mul_mem ({result}) ({leaf})"
    return result


def emit_node(node, record):
    label = node["id"][1:].replace("_", "T")
    _, _, source, _, normals = action_data(node, record)
    lines = [
        f"namespace SymmetricSubgroupAsymptotics.BinaryNormal{label}",
        f"local instance : Group Source := BinaryMenuCayley{label}.group",
        "",
        "/-- No registered normal of this literal action is both index two",
        "and elementary abelian.  Every negative row carries a checked witness. -/",
        f"theorem no_elementary_index_two (j : Fin {len(normals)}) :",
        "    (states j).quotientCount≠2 ∨",
        "      ∃ x : (states j).kernel,x^2≠1 := by",
        "  fin_cases j",
    ]
    identity = tuple(range(node["degree"]))
    for idx, normal in enumerate(normals):
        quotient_count = len(normal["reps"])
        if quotient_count != 2:
            lines.extend(("  · left", "    decide +kernel"))
            continue
        witness = next(
            (x for x in normal["ns"] if compose(x, x) != identity), None
        )
        if witness is None:
            raise ValueError(f"Unexpected elementary index-two row {label}/N{idx}")
        local_index = normal["ns"].index(witness)
        source_index = normal["source_indices"][local_index]
        raw = f"(⟨({source_index} : Fin {len(source)})⟩ : Source)"
        lines.extend(
            (
                "  · right",
                f"    refine ⟨⟨{raw},?_⟩,?_⟩",
                f"    · have hm := N{idx}.row_mem ({local_index} : Fin {len(normal['ns'])})",
                f"      change {raw}∈N{idx}.kernel at hm",
                "      exact hm",
                "    · intro hsquare",
                f"      have hne : ({raw})^2≠(1 : Source) := by decide +kernel",
                "      exact hne (congrArg Subtype.val hsquare)",
            )
        )
    lines.extend(("", f"end SymmetricSubgroupAsymptotics.BinaryNormal{label}", ""))
    return "\n".join(lines)


def render():
    with gzip.open(ROOT / "certificates/data/binary_menu.jsonl.gz", "rt") as stream:
        metadata = json.loads(next(stream))
        records = {
            row["id"]: row
            for line in stream
            if (row := json.loads(line)).get("kind") == "action"
        }
    nodes = {node["id"]: node for node in metadata["nodes"]}
    records["b8_22"] = complete_record(nodes["b8_22"])
    imports = "\n".join(
        f"import SymmetricSubgroupAsymptotics.GeneratedNormal8.Registry{name[1:].replace('_', 'T')}"
        for name in NODES
    )
    header = f"""{imports}

/-! Kernel-checked exclusions used by the degree-sixteen split classifier.
Generated by export_lean_elementary_top_exclusions.py. -/
set_option autoImplicit false
set_option maxHeartbeats 0
set_option maxRecDepth 100000
noncomputable section

"""
    return header + "\n".join(emit_node(nodes[name], records[name]) for name in NODES)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    payload = render().encode()
    if args.check:
        if not OUT.exists() or OUT.read_bytes() != payload:
            raise SystemExit(f"Stale generated file {OUT}")
    else:
        OUT.parent.mkdir(exist_ok=True)
        if not OUT.exists() or OUT.read_bytes() != payload:
            OUT.write_bytes(payload)
    print(OUT.relative_to(ROOT))


if __name__ == "__main__":
    main()
