#!/usr/bin/env python3
"""Selected sparse conjugacy cover for one original eight-point action.

Requires one explicit --source and exactly one of --write/--check. Reads only
that pinned original Cayley source, never a catalogue or normal registry. It
decodes at most 128 rows and traverses at most 384 conjugation edges under
the original generators. There is no all-sources or bulk invocation. No group-closure search, dense
multiplication table, compiler, subprocess, imported exporter, or bulk mode.

Immutable ceilings: 128 rows, 25 representatives, 384 edges, 100000 charged
operations, 5 cooperative seconds, and 64 KiB combined input/output each.
Time checks are cooperative, not a hard process/RSS guarantee. A separate
Lean check of the generated pointwise witnesses and public pilot is required.
"""
from __future__ import annotations

import sys
sys.dont_write_bytecode = True

import argparse
from collections import deque
import hashlib
import json
import math
import os
from pathlib import Path
import re
import tempfile
import time


ROOT = Path(__file__).resolve().parents[2]
SELF = Path(__file__).resolve()
FORMAL = ROOT / "formal/SymmetricSubgroupAsymptotics"
SOURCES = {
    "8T15": (32, 3, "0ea89d9b923038471a1f6dfbe6af310db59b8c381cc1d32a66ae15fab3151d9e"),
    "8T16": (32, 2, "481610531f086adb4d5c6ff477af7d2c8e71d931f3751b413d85496ac5c29dde"),
    "8T17": (32, 2, "2e38d74a3433af3cdb9d62429d731d0e6bc1ae10c94e014c164e6fd94dc80a2d"),
    "8T18": (32, 5, "2d673111c57de3d0a97b69e9487886808805db816574625b6d026ba9ab9a6c40"),
    "8T19": (32, 4, "f7f8d4d7dd6c10b83c49db4b2c167537a62b2ebdc6ee294d4ce09cf231e425cd"),
    "8T20": (32, 2, "c9c96f06c06b1e2d6e3a28644dfa4496638f378ba18c6936e2a5b9e1e46b0dea"),
    "8T21": (32, 3, "ed2dae5bd208715fc20615ef4683189a2d94b641984333b39c1e49fbc686817c"),
    "8T22": (32, 5, "663aadd12ab0322bb5fb4eb0057b9c4f508c31908a286ced4433da095fd69233"),
    "8T26": (64, 3, "dd25940fce3f2bdb486ce63b2df73a2b0966011ba221f61d546ed929980dd6ca"),
    "8T27": (64, 2, "4b7cff26997b94289d1820630fd3d16c464cbaff79aa829751c2151400d117d3"),
    "8T28": (64, 3, "de113f6563227e71cf66a0c82cef689626d4732286ef27b50f1c5b0eadfcb4cb"),
    "8T29": (64, 5, "f3dddab2331ab02382cca395a5b8743b8a1198e31907890a877a511eb673e9b4"),
    "8T30": (64, 3, "2898465e206e2c1c65667cda6e83c29784f3bb9dd5dedd6496686f33abb098a9"),
    "8T31": (64, 3, "b1a2218fb13310d15f056b17a053a0e10ce2becc92f95c78a02d8d862b69ca04"),
    "8T35": (128, 3, "76a5f90545ba67f4e69d7f81ad46418c85aa8d46e36b644fc1e544ab045d1d95"),
}
WIDTH = 8
# Assigned only from the literal allowlist after argument validation.
SOURCE_NAME = "8T35"
ROW_COUNT, GENERATOR_COUNT, SOURCE_SHA256 = SOURCES[SOURCE_NAME]
SOURCE = FORMAL / f"BinaryMenuCayley{SOURCE_NAME}.lean"
OUTPUT = FORMAL / f"GeneratedPrunedActions/ConjugacyCover{SOURCE_NAME}.lean"
MAX_REPRESENTATIVES = 25
MAX_EDGES = 384
MAX_OPERATIONS = 100000
MAX_SECONDS = 5.0
MAX_INPUT = 64 * 1024
MAX_OUTPUT = 64 * 1024
MAX_TOKENS = 4096
MAX_PARSE_DEPTH = 32
OWNERSHIP = b"Generated by export_lean_conjugacy_cover_selected.py"


class Refused(Exception):
    pass


def require(condition, message):
    if not condition:
        raise Refused(message)


def digest(data):
    return hashlib.sha256(data).hexdigest()


def read_small(path, limit=MAX_INPUT):
    require(path.is_file() and not path.is_symlink(), f"missing or redirected input: {path}")
    with path.open("rb") as handle:
        data = handle.read(limit + 1)
    require(len(data) <= limit, f"input byte ceiling reached: {path}")
    return data


class Budget:
    def __init__(self, operations, seconds):
        self.limit = operations
        self.seconds = seconds
        self.operations = 0
        self.edges = 0
        self.started = time.monotonic()

    def tick(self, amount=1):
        self.operations += amount
        require(self.operations <= self.limit, "charged operation ceiling reached")
        self.check_time()

    def check_time(self):
        require(time.monotonic() - self.started <= self.seconds,
                "cooperative time ceiling reached")

    def compose(self, a, b):
        self.tick(WIDTH)
        return tuple(a[b[x]] for x in range(WIDTH))

    def inverse(self, a):
        self.tick(WIDTH)
        result = [0] * WIDTH
        for x, y in enumerate(a):
            result[y] = x
        return tuple(result)

    def get_index(self, lookup, value):
        self.tick()
        require(value in lookup, "a conjugacy witness escaped the pinned original rows")
        return lookup[value]


class LiteralLookup:
    """Only parenthesized if/i.val/numeral expressions; no evaluation engine."""

    def __init__(self, text, budget):
        self.budget = budget
        self.tokens = re.findall(r"i\.val|if|then|else|[0-9]+|[()<]", text)
        require(re.sub(r"\s+", "", text) == "".join(self.tokens),
                "unrecognized original code lookup grammar")
        require(len(self.tokens) <= MAX_TOKENS, "lookup token ceiling reached")
        self.position = 0
        self.tree = self.expression(0)
        require(self.position == len(self.tokens), "trailing original lookup tokens")

    def pop(self, expected=None):
        self.budget.tick()
        require(self.position < len(self.tokens), "truncated original lookup")
        token = self.tokens[self.position]
        self.position += 1
        require(expected is None or token == expected, "malformed original lookup")
        return token

    def expression(self, depth):
        require(depth <= MAX_PARSE_DEPTH, "lookup recursion ceiling reached")
        token = self.pop()
        if token == "(":
            result = self.expression(depth + 1)
            self.pop(")")
            return result
        if token == "if":
            self.pop("i.val")
            self.pop("<")
            split = self.pop()
            require(split.isdecimal() and len(split) <= 3,
                    "invalid original lookup split")
            split = int(split)
            require(0 < split < ROW_COUNT, "original lookup split out of range")
            self.pop("then")
            left = self.expression(depth + 1)
            self.pop("else")
            right = self.expression(depth + 1)
            return (split, left, right)
        require(token.isdecimal() and len(token) <= 8, "invalid original code numeral")
        result = int(token)
        require(0 <= result < WIDTH ** WIDTH, "original code numeral out of range")
        return result

    def value(self, i):
        tree = self.tree
        while isinstance(tree, tuple):
            self.budget.tick()
            split, left, right = tree
            tree = left if i < split else right
        self.budget.tick()
        return tree


def validate_permutation(row, budget):
    budget.tick(WIDTH)
    require(len(row) == WIDTH and sorted(row) == list(range(WIDTH)),
            "a decoded original row is not an eight-point permutation")
    return tuple(row)


def inputs(data, budget):
    text = data.decode("utf-8")
    found = re.findall(
        rf"^private def codes \(i : Fin {ROW_COUNT}\) : Fin \(8\^8\) :=\n  ([^\n]+)$",
        text, re.MULTILINE)
    require(len(found) == 1, "missing or duplicated original row lookup")
    lookup = LiteralLookup(found[0], budget)
    codes = [lookup.value(i) for i in range(ROW_COUNT)]
    budget.tick(ROW_COUNT)
    require(len(set(codes)) == ROW_COUNT, "original row codes are not distinct")
    rows = []
    for code in codes:
        budget.tick(WIDTH)
        rows.append(validate_permutation(
            [(code // WIDTH ** x) % WIDTH for x in range(WIDTH)], budget))
    generators = []
    for j in range(GENERATOR_COUNT):
        found = re.findall(
            rf"^private def generator{j} : Equiv\.Perm \(Fin 8\) where\n"
            r"  toFun x := \(#\[([0-9,]+)\] : Array \(Fin 8\)\)\[x\.val\]!",
            text, re.MULTILINE)
        require(len(found) == 1, "missing or duplicated original generator")
        values = found[0].split(",")
        require(len(values) == WIDTH and all(len(x) == 1 for x in values),
                "original generator image list out of bounds")
        generators.append(validate_permutation([int(x) for x in values], budget))
    return rows, generators


def search(rows, generators, budget):
    budget.tick(ROW_COUNT)
    lookup = {row: i for i, row in enumerate(rows)}
    identity = budget.get_index(lookup, tuple(range(WIDTH)))
    for g in generators:
        budget.get_index(lookup, g)
    inverses = [budget.inverse(g) for g in generators]
    label = [-1] * ROW_COUNT
    conjugator = [-1] * ROW_COUNT
    representative = []
    for start in range(ROW_COUNT):
        budget.tick()
        if label[start] != -1:
            continue
        require(len(representative) < MAX_REPRESENTATIVES,
                "more than 25 representative labels are needed by this search")
        current = len(representative)
        representative.append(start)
        label[start] = current
        conjugator[start] = identity
        queue = deque([start])
        while queue:
            budget.tick()
            i = queue.popleft()
            for g, inverse in zip(generators, inverses):
                budget.tick()
                budget.edges += 1
                require(budget.edges <= MAX_EDGES, "conjugation edge ceiling reached")
                y = budget.compose(budget.compose(g, rows[i]), inverse)
                j = budget.get_index(lookup, y)
                if label[j] == -1:
                    witness = budget.compose(rows[conjugator[i]], inverse)
                    conjugator[j] = budget.get_index(lookup, witness)
                    label[j] = current
                    queue.append(j)
                    require(len(queue) <= ROW_COUNT, "conjugation queue ceiling reached")
                else:
                    require(label[j] == current, "inconsistent conjugation components")
    require(budget.edges == ROW_COUNT * GENERATOR_COUNT, "incomplete original-row traversal")
    for i in range(ROW_COUNT):
        budget.tick()
        require(0 <= label[i] < len(representative) and 0 <= conjugator[i] < ROW_COUNT,
                "an original row has no actual-group witness")
        a = rows[conjugator[i]]
        require(budget.compose(a, rows[i]) ==
                budget.compose(rows[representative[label[i]]], a),
                "independent final conjugacy witness check failed")
    return representative, label, conjugator


def balanced(values, variable="i.val", start=0):
    if len(values) == 1:
        return str(values[0])
    middle = len(values) // 2
    return (f"(if {variable} < {start + middle} then "
            f"{balanced(values[:middle], variable, start)} else "
            f"{balanced(values[middle:], variable, start + middle)})")


def emit(result, budget):
    representatives, labels, conjugators = result
    count = len(representatives)
    budget.tick(len(representatives) + 2 * ROW_COUNT)
    text = f'''import SymmetricSubgroupAsymptotics.BinaryMenuCayley{SOURCE_NAME}
import Mathlib.Order.Fin.Basic

/-! Generated by export_lean_conjugacy_cover_selected.py.
Selected original source SHA-256: {SOURCE_SHA256}.
Only row-index witnesses and original-point equations are supplied here.
The public BinaryConjugacyClass{SOURCE_NAME} module proves complete original coverage.
-/
set_option autoImplicit false
namespace SymmetricSubgroupAsymptotics.BinaryConjugacyData{SOURCE_NAME}

abbrev representativeCount : ℕ := {count}
def representative (i : Fin representativeCount) : Fin {ROW_COUNT} :=
  {balanced(representatives)}
def label (i : Fin {ROW_COUNT}) : Fin representativeCount :=
  {balanced(labels)}
def conjugator (i : Fin {ROW_COUNT}) : Fin {ROW_COUNT} :=
  {balanced(conjugators)}

def image (i : Fin {ROW_COUNT}) (x : Fin 8) : Fin 8 :=
  finFunctionFinEquiv.symm (BinaryMenuCayley{SOURCE_NAME}.certificate.rows i) x

private def RowChecked (i : Fin {ROW_COUNT}) : Prop := ∀ x : Fin 8,
  image (conjugator i) (image i x) =
    image (representative (label i)) (image (conjugator i) x)

'''
    for i in range(ROW_COUNT):
        budget.tick()
        name = f"row_checked_{i}"
        text += f"private theorem {name} : RowChecked {i} := by\n  unfold RowChecked\n  decide +kernel\n\n"
    # The expected forall type guides each finite eliminator. Each leaf sees
    # an arbitrary Fin 1 value, so explicitly eliminate that value before
    # applying its concrete named row theorem.
    def aggregate(start, length):
        if length == 1:
            return f"(by intro i; have hi : i = 0 := Subsingleton.elim _ _; subst i; exact row_checked_{start})"
        middle = length // 2
        return (f"(Fin.addCases (m := {middle}) (n := {length - middle}) "
                f"{aggregate(start, middle)} {aggregate(start + middle, length - middle)})")
    text += f'''private theorem row_checked : ∀ i : Fin {ROW_COUNT}, RowChecked i :=
  {aggregate(0, ROW_COUNT)}

theorem conjugates_pointwise (i : Fin {ROW_COUNT}) (x : Fin 8) :
    image (conjugator i) (image i x) =
      image (representative (label i)) (image (conjugator i) x) :=
  row_checked i x

theorem representativeCount_le_twenty_five : representativeCount ≤ 25 := by
  decide +kernel

end SymmetricSubgroupAsymptotics.BinaryConjugacyData{SOURCE_NAME}
'''
    budget.tick(len(text))
    return text.encode("utf-8")


def report_path(raw):
    path = Path(raw).expanduser().absolute()
    allowed = (ROOT.parent / "private_audits").resolve()
    require(path.parent.exists() and path.parent.resolve().is_relative_to(allowed),
            "report must stay in an existing private_audits directory")
    require(not path.is_symlink(), "refusing symbolic-link report")
    return path


def atomic_write(path, data):
    require(path.parent.is_dir() and not path.parent.is_symlink(), "unsafe output directory")
    require(not path.is_symlink(), "refusing symbolic-link output")
    temporary = None
    try:
        with tempfile.NamedTemporaryFile(prefix=f".{path.name}.", dir=path.parent,
                                         delete=False) as handle:
            temporary = Path(handle.name)
            handle.write(data)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
    finally:
        if temporary is not None and temporary.exists():
            temporary.unlink()


def main():
    global SOURCE_NAME, ROW_COUNT, GENERATOR_COUNT, SOURCE_SHA256, SOURCE, OUTPUT
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", required=True, choices=sorted(SOURCES))
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    parser.add_argument("--report")
    parser.add_argument("--max-operations", type=int, default=MAX_OPERATIONS)
    parser.add_argument("--seconds", type=float, default=MAX_SECONDS)
    parser.add_argument("--max-output-bytes", type=int, default=MAX_OUTPUT)
    args = parser.parse_args()
    SOURCE_NAME = args.source
    ROW_COUNT, GENERATOR_COUNT, SOURCE_SHA256 = SOURCES[SOURCE_NAME]
    SOURCE = FORMAL / f"BinaryMenuCayley{SOURCE_NAME}.lean"
    OUTPUT = FORMAL / f"GeneratedPrunedActions/ConjugacyCover{SOURCE_NAME}.lean"
    require(ROW_COUNT <= 128 and ROW_COUNT * GENERATOR_COUNT <= MAX_EDGES,
            "selected source exceeds fixed structural ceilings")
    require(0 < args.max_operations <= MAX_OPERATIONS, "operation limit may only lower ceiling")
    require(math.isfinite(args.seconds) and 0 < args.seconds <= MAX_SECONDS,
            "time limit may only lower ceiling")
    require(0 < args.max_output_bytes <= MAX_OUTPUT, "output limit may only lower ceiling")
    require(not (args.check and args.report), "--check is read-only and forbids --report")
    private_report = report_path(args.report) if args.report else None
    budget = Budget(args.max_operations, args.seconds)
    original = read_small(SOURCE)
    own = read_small(SELF)
    require(len(original) + len(own) <= MAX_INPUT, "combined input ceiling reached")
    require(digest(original) == SOURCE_SHA256, "pinned original Cayley source mismatch")
    rows, generators = inputs(original, budget)
    result = search(rows, generators, budget)
    output = emit(result, budget)
    report = {
        "schema": "selected-original-conjugacy-cover-v1", "source": SOURCE_NAME,
        "status": "candidate sparse cover; separate Lean checks required",
        "producer_sha256": digest(own), "original_source_sha256": SOURCE_SHA256,
        "source_rows": ROW_COUNT, "original_generators": GENERATOR_COUNT,
        "representative_count": len(result[0]), "conjugation_edges": budget.edges,
        "charged_operations": budget.operations, "generated_bytes": len(output),
        "generated_sha256": digest(output),
        "limits": {"input_bytes": MAX_INPUT, "output_bytes": args.max_output_bytes,
                   "operations": args.max_operations, "seconds": args.seconds,
                   "rows": ROW_COUNT, "edges": MAX_EDGES,
                   "representatives": MAX_REPRESENTATIVES},
        "scope": "one literal original class-count upper bound; no universal action coverage",
    }
    report_bytes = (json.dumps(report, sort_keys=True, indent=2) + "\n").encode()
    require(len(output) + (len(report_bytes) if private_report else 0) <= args.max_output_bytes,
            "combined output ceiling reached")
    require(read_small(SOURCE) == original and read_small(SELF) == own,
            "original source or producer changed during run")
    budget.check_time()
    if args.check:
        require(read_small(OUTPUT, args.max_output_bytes) == output,
                "generated data differs from deterministic replay")
    else:
        if OUTPUT.exists():
            require(OWNERSHIP in read_small(OUTPUT, args.max_output_bytes),
                    "refusing output not owned by this producer")
        atomic_write(OUTPUT, output)
        if private_report:
            atomic_write(private_report, report_bytes)
    print(json.dumps({"source": SOURCE_NAME, "mode": "check" if args.check else "write",
                      "representatives": len(result[0]), "edges": budget.edges,
                      "operations": budget.operations, "bytes": len(output),
                      "sha256": digest(output)}, sort_keys=True))


if __name__ == "__main__":
    try:
        main()
    except (Refused, OSError, ValueError, TypeError, KeyError) as exc:
        print(f"REFUSED: {exc}", file=sys.stderr)
        raise SystemExit(2)
