#!/usr/bin/env python3
"""Export untrusted literal carrier witnesses for checking by the Lean kernel.

Run from any directory. This reconstructs Cayley rows and generator words
from certificates/data/binary_menu.jsonl.gz; Lean proves their soundness.
No catalogue order or external checker verdict is used as a proof premise.
"""
from pathlib import Path
import argparse
import gzip, json
from collections import deque

ROOT = Path(__file__).resolve().parents[2]
OUT=ROOT/'formal/SymmetricSubgroupAsymptotics'

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--check', action='store_true',
                    help='Compare generated bytes without writing any Lean file.')
args = parser.parse_args()


def save_generated(path, content):
    data = content.encode('utf-8')
    if args.check:
        if not path.is_file() or path.read_bytes() != data:
            raise SystemExit(f'Generated witness differs: {path.relative_to(ROOT)}')
    else:
        path.write_bytes(data)

def mul(a,b): return tuple(a[x] for x in b)
def pairmul(a,b): return (mul(a[0],b[0]),mul(a[1],b[1]))
def bfs(gens,identity,op):
    rows=[identity]; words=[[]]; ix={identity:0}; nxt=[]
    for i,g in enumerate(rows):
        ns=[]
        for j,h in enumerate(gens):
            v=op(g,h)
            if v not in ix:
                ix[v]=len(rows);rows.append(v);words.append(words[i]+[j])
            ns.append(ix[v])
        nxt.append(ns)
    return {'rows':rows,'words':words,'next':nxt,'ix':ix,'generators':[ix[g] for g in gens]}
def row(a):return '#['+','.join(map(str,a))+']'
def array(a,fn=str):return '#[\n  '+',\n  '.join(fn(x) for x in a)+'\n]'
def rawperm(a):return tuple(x-1 for x in a)
def lookup(values, var='i.val', start=0):
    """Balanced kernel-reducible table lookup; avoid linear Array row scans."""
    if len(values)==1:return values[0]
    k=len(values)//2
    return f'(if {var} < {start+k} then {lookup(values[:k],var,start)} else {lookup(values[k:],var,start+k)})'

def checks(n):
    if n<=32:return '(by decide +kernel)'
    k=n//2
    return f'(Fin.addCases (m := {k}) (n := {n-k}) {checks(k)} {checks(n-k)})'

def emit_perms(name,rows,w):
    # Every literal permutation is checked locally. Large universal
    # bijectivity reductions repeat the whole lookup term in the kernel.
    unique=list(dict.fromkeys(rows)); ix={a:i for i,a in enumerate(unique)}
    out=''
    for i,a in enumerate(unique):
        inv=tuple(a.index(j)for j in range(w))
        out+=f"""private def {name}Literal{i} : Equiv.Perm (Fin {w}) where
  toFun x := ({row(a)} : Array (Fin {w}))[x.val]!
  invFun x := ({row(inv)} : Array (Fin {w}))[x.val]!
  left_inv := by decide +kernel
  right_inv := by decide +kernel

"""
    out+=f"""private def {name} (i : Fin {len(rows)}) : Equiv.Perm (Fin {w}) :=
  {lookup([name+'Literal'+str(ix[a])for a in rows])}

"""
    return out
def emit_table(name,data,dimensions):
    n=len(data['rows']);d=len(data['generators']);graph=len(dimensions)==2
    if graph:
        s=emit_perms(name+'Source',[x[0]for x in data['rows']],dimensions[0])
        s+=emit_perms(name+'Target',[x[1]for x in data['rows']],dimensions[1])
        s+=f'def {name}Generators (j : Fin {d}) := {name}Source ({row(data["generators"])}[j.val]!)\n'
        s+=f'def {name}Images (j : Fin {d}) := {name}Target ({row(data["generators"])}[j.val]!)\n'
        elems=f'(fun i => ({name}Source i, {name}Target i))'
        gens=f'(fun j => ({name}Generators j, {name}Images j))'
    else:
        s=emit_perms(name+'Element',data['rows'],dimensions[0])
        s+=f'def {name}Generators (j : Fin {d}) := {name}Element ({row(data["generators"])}[j.val]!)\n'
        elems=name+'Element';gens=name+'Generators'
    s+=f'''private def {name}NextTable (i : Fin {n}) : Array (Fin {n}) :=
  {lookup([row(a)for a in data['next']])}
private def {name}WordTable (i : Fin {n}) : List (Fin {d}) :=
  {lookup(['['+','.join(map(str,x))+']'for x in data['words']])}
private def {name}Cayley : FiniteCayleyCertificate {gens} {n} where
  elements := {elems}
  identity := 0
  identity_eq := by decide +kernel
  next i j := ({name}NextTable i)[j.val]!
  next_eq := {checks(n)}
  words i := {name}WordTable i
  words_eq := {checks(n)}

'''
    if graph:
        s+=f'''def {name}Certificate : FiniteHomCertificate {name}Generators {name}Images {n} where
  cayley := {name}Cayley
  first_kernel := {checks(n)}

'''
    else:
        s+=f'def {name}Certificate := {name}Cayley\n\n'
    return s

def mkdata(gs,w):return bfs([rawperm(g)for g in gs],tuple(range(w)),mul)
def mkgraph(gs,ims,w,q):return bfs(list(zip(map(rawperm,gs),map(rawperm,ims))),(tuple(range(w)),tuple(range(q))),pairmul)
with gzip.open(ROOT/'certificates/data/binary_menu.jsonl.gz','rt')as f:
    header=json.loads(next(f));nodes={x['id']:x for x in header['nodes']}; charts=[]
    for line in f:
        a=json.loads(line)
        if a.get('kind')=='action':
            for e in a['normals']:
                if e['kind']=='transport':charts.append((nodes[a['id']],e))
for node,e in charts:
    label=node['id'].replace('b','',1).replace('_','T');w=node['degree'];q=e['quotient_degree']
    ds={
        'alpha':mkgraph(node['generators'],e['alpha_images'],w,q),
        'beta':mkgraph(e['cover_generators'],e['beta_images'],w,q),
        'quotient':mkdata(e['quotient_generators'],q),
        'axis':mkdata(e['normal_generators'],w),
        'coverKernel':mkdata(e['cover_kernel_generators'],w)}
    s=f'''import SymmetricSubgroupAsymptotics.FiniteGroupCertificates

/-!
# Literal transport chart {label}

The permutation rows are the original rows from the committed binary menu,
converted to zero-based Lean notation. Cayley rows and words are untrusted
candidate witnesses; every certificate equation is checked by Lean's kernel.
No catalogue identification or external PASS output is used in a proof.
-/

set_option autoImplicit false
set_option maxRecDepth 100000
set_option maxHeartbeats 0
noncomputable section

namespace SymmetricSubgroupAsymptotics.BinaryChart{label}

'''
    for name in ['alpha','beta','quotient','axis','coverKernel']:
        s+=emit_table(name,ds[name],[w,q]if name in ['alpha','beta']else [q if name=='quotient'else w])
    # Checked maps between finite rows install the shared literal quotient.
    for name in ['alpha','beta']:
        data=ds[name];qdata=ds['quotient'];ni=len(data['rows']);nq=len(qdata['rows'])
        qix={v[1]:i for i,v in reversed(list(enumerate(data['rows'])))}
        forward=[qdata['ix'][v[1]]for v in data['rows']]
        backward=[qix[v]for v in qdata['rows']]
        s+=f'''theorem {name}_range : {name}Certificate.hom.range =
    Subgroup.closure (Set.range quotientGenerators) :=
  {name}Certificate.hom_range_eq_of_rows quotientCertificate
    (fun i => {lookup(list(map(str,forward)))})
    (fun j => {lookup(list(map(str,backward)),"j.val")})
    {checks(ni)} {checks(nq)}

'''
        kname='axis'if name=='alpha'else'coverKernel';kd=ds[kname];nk=len(kd['rows']);kid=tuple(range(q))
        sx={v[0]:i for i,v in enumerate(data['rows']) if v[1]==kid}
        assert set(sx)==set(kd['rows'])
        forward=[kd['ix'].get(v[0],0)if v[1]==kid else 0 for v in data['rows']]
        backward=[sx[v]for v in kd['rows']]
        s+=f'''theorem {name}_kernel : {name}Certificate.hom.ker.map
    (Subgroup.closure (Set.range {name}Generators)).subtype =
      Subgroup.closure (Set.range {kname}Generators) :=
  {name}Certificate.kernel_image_eq_of_rows {kname}Certificate
    (fun i => {lookup(list(map(str,forward)))})
    (fun j => {lookup(list(map(str,backward)),"j.val")})
    {checks(ni)} {checks(nk)}

'''
    s+=f'end SymmetricSubgroupAsymptotics.BinaryChart{label}\n'
    path=OUT/f'BinaryExceptional{label}.lean';save_generated(path,s)
    print(path.name,len(s),{k:len(v['rows'])for k,v in ds.items()})

# Use literal base-alphabet generator rows, with coordinate charts chosen
# by exhaustive search. The search is untrusted; Lean checks every output.
from itertools import permutations

s = ('import SymmetricSubgroupAsymptotics.BinaryPermutationBlocks\n' +
     ''.join(f'import SymmetricSubgroupAsymptotics.BinaryExceptional{node["id"].replace("b", "", 1).replace("_", "T")}\n'
             for node, _ in charts))
s += '''
/-!
# Physical orbit words of the four exceptional carriers

Every displayed block uses actual coordinates in the original point set.
Generator intertwiners and two-way generator words prove the whole block
projection is the literal base-alphabet action. The blocks cover exactly
the original physical set, with no auxiliary quotient points counted.
-/

set_option autoImplicit false
set_option maxRecDepth 100000
set_option maxHeartbeats 0
noncomputable section

namespace SymmetricSubgroupAsymptotics

'''
for node, e in charts:
    label=node['id'].replace('b','',1).replace('_','T'); w=node['degree']
    s += f'namespace BinaryChart{label}\n\n'
    gs=[rawperm(g) for g in e['cover_generators']]
    chosen=[]
    for bi,wd in enumerate(e['word']):
        base=header['base_alphabet'][wd['base_index']-1]
        bg=[rawperm(g)for g in base['generators']]; b=base['degree']
        bd=bfs(bg,tuple(range(b)),mul)
        for emb in permutations(x-1 for x in wd['block']):
            ix={x:i for i,x in enumerate(emb)}
            ims=[tuple(ix[g[x]]for x in emb)for g in gs]
            if all(im in bd['ix']for im in ims):
                md=bfs(ims,tuple(range(b)),mul)
                if all(g in md['ix']for g in bg):break
        else:raise ValueError('no literal base chart')
        chosen.append(emb)
        name=f'block{bi}'
        s += emit_perms(name+'Images',ims,b)
        s += emit_table(name+'Base',bd,[b])
        s += f'''def {name} : PermutationBlockChart (Y := Fin {b}) betaGenerators where
  embedding := ⟨(fun x => ({row(emb)} : Array (Fin {w}))[x.val]!), by decide +kernel⟩
  images := {name}Images
  intertwine := by decide +kernel

'''
        fw=[bd['words'][bd['ix'][im]]for im in ims]
        bw=[md['words'][md['ix'][g]]for g in bg]
        s += f'''theorem {name}_range : {name}.hom.range =
    Subgroup.closure (Set.range {name}BaseGenerators) := by
  rw [{name}.hom_range]
  exact subgroup_closure_eq_of_generator_words {name}.images {name}BaseGenerators
    (fun i => ({array(fw, lambda x:'['+','.join(map(str,x))+']')} : Array (List (Fin {len(bg)})))[i.val]!)
    (fun j => ({array(bw, lambda x:'['+','.join(map(str,x))+']')} : Array (List (Fin {len(gs)})))[j.val]!)
    (by decide +kernel) (by decide +kernel)

'''
        # An element sending each x to each y, expressed in checked rows.
        witnesses=[[next(i for i,g in enumerate(bd['rows'])if g[x]==y)for y in range(b)]for x in range(b)]
        s += f'''theorem {name}_base_transitive (x y : Fin {b}) :
    ∃ g : Subgroup.closure (Set.range {name}BaseGenerators), (g : Equiv.Perm (Fin {b})) x = y := by
  let i : Fin {len(bd['rows'])} := (({array(witnesses,row)} : Array (Array (Fin {len(bd['rows'])})))[x.val]!)[y.val]!
  refine ⟨⟨{name}BaseCertificate.elements i,
    ({name}BaseCertificate.mem_closure_iff _).mpr ⟨i,rfl⟩⟩, ?_⟩
  have h : ∀ x y : Fin {b},
      {name}BaseCertificate.elements ((({array(witnesses,row)} : Array (Array (Fin {len(bd['rows'])})))[x.val]!)[y.val]!) x = y := by decide +kernel
  exact h x y

'''
        # Small exact order witnesses are checked on original rows.
        s += f'''theorem {name}_base_card :
    Nat.card (Subgroup.closure (Set.range {name}BaseGenerators)) = {len(bd['rows'])} :=
  {name}BaseCertificate.card_closure (by decide +kernel)

'''
    # These finite statements record the exact partition of physical points.
    widths=[len(b) for b in chosen]
    s += f'''theorem physical_degree : {' + '.join(map(str,widths))} = {w} := by decide +kernel

'''
    for i,emb in enumerate(chosen):
        for j in range(i):
            s += f'''theorem blocks{i}_{j}_disjoint : ∀ x y,
    block{i}.embedding x ≠ block{j}.embedding y := by decide +kernel

'''
    cov=' ∨ '.join(f'∃ y, block{i}.embedding y = x'for i in range(len(chosen)))
    s += f'''theorem blocks_cover : ∀ x : Fin {w}, {cov} := by decide +kernel

'''
    # The actual first block suffices for positive physical support.
    # Its proved group invariants, not a role string, appear in the theorem.
    b0=len(chosen[0])
    if b0==4:
        proof='''Or.inl ⟨rfl,
    subgroup_closure_single_generator_isCyclic block0BaseGenerators,
    block0_base_card⟩'''
    else:
        proof='''Or.inr ⟨rfl, by rw [block0_base_card]; decide +kernel⟩'''
    s += f'''/-- A full literal block of positive physical size is either the
cyclic group of order four, or a degree-eight group of order above 32. -/
theorem quarter_cyclic_four_or_large_eight :
    {w} ≤ 4 * {b0} ∧
    (({b0} = 4 ∧ IsCyclic (Subgroup.closure (Set.range block0BaseGenerators)) ∧
      Nat.card (Subgroup.closure (Set.range block0BaseGenerators)) = 4) ∨
     ({b0} = 8 ∧ 32 < Nat.card (Subgroup.closure (Set.range block0BaseGenerators)))) :=
  ⟨by decide +kernel, {proof}⟩

end BinaryChart{label}

'''
s += 'end SymmetricSubgroupAsymptotics\n'
path=OUT/'BinaryExceptionalBlocks.lean';save_generated(path,s)
print(path.name,len(s))

# Exhibit the retained correlation in the nonabelian degree-sixteen core:
# the independent C4 block rotation belongs to the displayed product but
# does not belong to the literal carrier.
assert label == '16T1086'
perm=list(range(16)); emb=chosen[0]
cycle=rawperm(header['base_alphabet'][e['word'][0]['base_index']-1]['generators'][0])
for x in range(4):perm[emb[x]]=emb[cycle[x]]
assert tuple(perm) not in {v[0]for v in ds['beta']['rows']}
s = '''import SymmetricSubgroupAsymptotics.BinaryExceptionalBlocks

/-!
# The proper degree-sixteen carrier correlation

The independent rotation of the literal C4 block is an element of the
full displayed block product, but is absent from the actual carrier.
Thus the reversible chart retains a proper subdirect core.
-/

set_option autoImplicit false
set_option maxRecDepth 100000
set_option maxHeartbeats 0
noncomputable section

namespace SymmetricSubgroupAsymptotics.BinaryChart16T1086

'''
s += emit_perms('independentRotationPermutation',[tuple(perm)],16)
s += '''def independentRotation : Equiv.Perm (Fin 16) :=
  independentRotationPermutation 0

theorem independentRotation_on_cyclic_block : ∀ x,
    independentRotation (block0.embedding x) =
      block0.embedding (block0BaseGenerators 0 x) := by decide +kernel

'''
for i in range(1,4):
    s += f'''theorem independentRotation_on_block{i} : ∀ x,
    independentRotation (block{i}.embedding x) = block{i}.embedding x := by decide +kernel

'''
n=len(ds['beta']['rows'])
gs=[rawperm(g)for g in e['cover_generators']]
a,b=next((i,j)for i,g in enumerate(gs)for j,h in enumerate(gs)if mul(g,h)!=mul(h,g))
s += f'''theorem carrier_nonabelian :
    ∃ x y : Subgroup.closure (Set.range betaGenerators), x*y ≠ y*x := by
  refine ⟨⟨betaGenerators {a}, Subgroup.subset_closure (Set.mem_range_self _)⟩,
    ⟨betaGenerators {b}, Subgroup.subset_closure (Set.mem_range_self _)⟩, ?_⟩
  intro he
  have hne : betaGenerators {a} * betaGenerators {b} ≠
      betaGenerators {b} * betaGenerators {a} := by decide +kernel
  exact hne (congrArg Subtype.val he)

'''
s += f'''/-- The independent displayed C4 rotation is absent from the original
literal carrier. Full coordinate projections therefore do not license
replacement by the full displayed product. -/
theorem independentRotation_not_mem : independentRotation ∉
    Subgroup.closure (Set.range betaGenerators) := by
  intro h
  obtain ⟨i,hi⟩ := (betaCertificate.source_mem_iff _).mp h
  have hno : ∀ i, (betaCertificate.cayley.elements i).1 ≠ independentRotation :=
    {checks(n)}
  exact hno i hi

end SymmetricSubgroupAsymptotics.BinaryChart16T1086
'''
path=OUT/'BinaryExceptional16Proper.lean';save_generated(path,s)
print(path.name,len(s))
