#!/usr/bin/env python3
"""Export the bounded primitive socle-quotient arithmetic receipt to Lean.

The committed primitive stream contains every normal subgroup for every
primitive action of degree at most 33.  A primitive group has a unique
minimal normal subgroup in this range (the two-minimal-normal diagonal types
start far above it), so the smallest nontrivial normal order is the socle
order.  This exporter records only the resulting quotient order.  Lean
independently checks its 3-adic valuation and the strict 3/20 inequality.

Identification of an arbitrary primitive action with a published PrimGrp row
and with its actual socle remains a separate literature correspondence.
"""

from __future__ import annotations

import argparse
import gzip
import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
DATA = ROOT / "certificates/data/primitive_rank.jsonl.gz"
OUTPUT = ROOT / (
    "formal/SymmetricSubgroupAsymptotics/PrimitiveStrictHeadReceipt.lean"
)


def valuation_three(n: int) -> int:
    value = 0
    while n % 3 == 0:
        n //= 3
        value += 1
    return value


def selected_rows() -> list[tuple[int, int, int, int]]:
    rows: list[tuple[int, int, int, int]] = []
    with gzip.open(DATA, "rt", encoding="utf-8") as source:
        for line in source:
            record = json.loads(line)
            if not (
                record.get("kind") == "action"
                and record.get("catalogue") == "primitive"
                and 2 <= record["degree"] <= 33
            ):
                continue
            normal_orders = sorted(
                {normal["order"] for normal in record["normals"] if normal["order"] > 1}
            )
            if not normal_orders:
                raise RuntimeError(
                    f"missing nontrivial normal row at "
                    f"{record['degree']}P{record['index']}"
                )
            socle_order = normal_orders[0]
            if record["order"] % socle_order:
                raise RuntimeError("socle order does not divide group order")
            quotient_order = record["order"] // socle_order
            value = valuation_three(quotient_order)
            if record["degree"] not in (3, 4, 18):
                if not 20 * value < 3 * record["degree"]:
                    raise RuntimeError(
                        f"strict row failed at {record['degree']}P{record['index']}"
                    )
            rows.append(
                (record["degree"], record["index"], quotient_order, value)
            )
    if len(rows) != 253:
        raise RuntimeError(f"expected 253 primitive rows, got {len(rows)}")
    if len({(degree, index) for degree, index, _, _ in rows}) != len(rows):
        raise RuntimeError("duplicate primitive catalogue locator")
    return rows


def render(rows: list[tuple[int, int, int, int]]) -> str:
    digest = hashlib.sha256(DATA.read_bytes()).hexdigest()
    entries = "\n".join(
        "  { degree := %d, catalogueIndex := %d, quotientOrder := %d,\n"
        "    ternaryValuation := %d, valuation_eq := by decide +kernel,\n"
        "    eighteen_zero := by omega, strict_of_nonexceptional := by omega },"
        % (degree, index, quotient_order, value)
        for degree, index, quotient_order, value in rows
    )
    return f"""import Mathlib.Data.Nat.Factorization.Basic

/-!
# Kernel-checked bounded primitive strict-head receipt

Generated by `computations/python/export_lean_primitive_strict_head.py`
from `certificates/data/primitive_rank.jsonl.gz` (compressed SHA256
`{digest}`).  The 253 entries are all published PrimGrp rows in degrees
2 through 33.  Only the socle-quotient order is retained.

Lean checks the exact 3-adic valuation of every quotient and the strict
three-twentieths inequality outside degrees 3, 4 and 18.  The published
classification correspondence between an arbitrary primitive action and a
row, including its actual socle, is deliberately separate.
-/

set_option autoImplicit false

namespace SymmetricSubgroupAsymptotics

/-- One bounded primitive catalogue row with kernel-checked arithmetic. -/
structure PrimitiveStrictHeadRow where
  degree : ℕ
  catalogueIndex : ℕ
  quotientOrder : ℕ
  ternaryValuation : ℕ
  valuation_eq : quotientOrder.factorization 3 = ternaryValuation
  eighteen_zero : degree = 18 → ternaryValuation = 0
  strict_of_nonexceptional : degree ≠ 3 → degree ≠ 4 → degree ≠ 18 →
    20 * ternaryValuation < 3 * degree

/-- Every primitive catalogue row in degrees 2 through 33. -/
def primitiveStrictHeadRows : Array PrimitiveStrictHeadRow := #[
{entries}]

theorem primitiveStrictHeadRows_size :
    primitiveStrictHeadRows.size = 253 := by
  decide +kernel

/-- Typed access to the complete numerical receipt. -/
def primitiveStrictHeadRow (i : Fin 253) : PrimitiveStrictHeadRow :=
  primitiveStrictHeadRows[i.val]'(by
    rw [primitiveStrictHeadRows_size]
    exact i.isLt)

theorem primitiveStrictHeadRow_valuation (i : Fin 253) :
    (primitiveStrictHeadRow i).quotientOrder.factorization 3 =
      (primitiveStrictHeadRow i).ternaryValuation :=
  (primitiveStrictHeadRow i).valuation_eq

theorem primitiveStrictHeadRow_eighteen_zero (i : Fin 253)
    (h18 : (primitiveStrictHeadRow i).degree = 18) :
    (primitiveStrictHeadRow i).ternaryValuation = 0 :=
  (primitiveStrictHeadRow i).eighteen_zero h18

theorem primitiveStrictHeadRow_strict (i : Fin 253)
    (h3 : (primitiveStrictHeadRow i).degree ≠ 3)
    (h4 : (primitiveStrictHeadRow i).degree ≠ 4)
    (h18 : (primitiveStrictHeadRow i).degree ≠ 18) :
    20 * (primitiveStrictHeadRow i).ternaryValuation <
      3 * (primitiveStrictHeadRow i).degree :=
  (primitiveStrictHeadRow i).strict_of_nonexceptional h3 h4 h18

end SymmetricSubgroupAsymptotics
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render(selected_rows())
    if args.check:
        if OUTPUT.read_text(encoding="utf-8") != expected:
            raise SystemExit(f"stale generated receipt: {OUTPUT}")
        print(f"PASS {OUTPUT.relative_to(ROOT)}")
    else:
        OUTPUT.write_text(expected, encoding="utf-8")


if __name__ == "__main__":
    main()
