import SymmetricSubgroupAsymptotics.BinaryNormalGeneratorChecks
import SymmetricSubgroupAsymptotics.BinaryMenuCayley8T19

/-! Exact original normal states and quotient rows for 8T19.
Generated by export_lean_normal_registry.py; all finite facts are checked
in Lean's kernel. This file certifies normal-state coverage, not the later
pair/character/transport acceptance of those states. -/

set_option autoImplicit false
set_option maxRecDepth 100000
set_option maxHeartbeats 0
set_option linter.unusedVariables false
noncomputable section
namespace SymmetricSubgroupAsymptotics.BinaryNormal8T19

abbrev Source := FiniteGroupRow 32
local instance : Group Source := BinaryMenuCayley8T19.group

def generators (j : Fin 4) : Source :=
  ⟨BinaryMenuCayley8T19.certificate.next BinaryMenuCayley8T19.certificate.identity j⟩

theorem generators_full : Subgroup.closure (Set.range generators)=⊤ := by
  apply binaryNormal_full_generators_of_equiv BinaryMenuCayley8T19.generators
    generators BinaryMenuCayley8T19.originalEquiv
  intro j
  change BinaryMenuCayley8T19.certificate.toCayley.elements
    (BinaryMenuCayley8T19.certificate.toCayley.next
      BinaryMenuCayley8T19.certificate.toCayley.identity j)=_
  rw [FiniteCayleyCertificate.next_eq,FiniteCayleyCertificate.identity_eq,one_mul]

theorem source_card : Nat.card Source=32 := by
  rw [Nat.card_eq_fintype_card]
  rfl

namespace N0
def normalGenerators (j : Fin 0) : Source := Fin.elim0 j
def kernel : Subgroup Source := Subgroup.closure (Set.range normalGenerators)
private def rows (i : Fin 1) : Fin 32 := (31 : Fin 32)
private def next (i : Fin 1) (j : Fin 0) : Fin 1 := Fin.elim0 j
private def rank (i : Fin 1) : ℕ := 0
private def parents (i : Fin 1) : Fin 1 := (0 : Fin 1)

def normalCertificate : EncodedCayleyCertificate (binaryNormalRowEncoding normalGenerators) 1 where
  rows := rows
  identity := 0
  identity_eq := by decide +kernel
  next := next
  next_eq := (by decide +kernel)
  rank := rank
  parent i _ := parents i
  letter i hi := False.elim (hi (Subsingleton.elim i (0 : Fin 1)))
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

theorem normalRows_injective : Function.Injective normalCertificate.rows := by decide +kernel

theorem kernel_card : Nat.card kernel=1 := normalCertificate.card_closure normalRows_injective

theorem row_mem (i : Fin 1) : (⟨rows i⟩ : Source)∈kernel :=
  binaryNormalRow_mem normalCertificate i

instance normal : kernel.Normal := binaryNormal_of_generator_conjugates generators generators_full
  normalGenerators (fun _ j => Fin.elim0 j) (fun _ j => Fin.elim0 j)

private def representatives (i : Fin 32) : Source := ⟨((if i.val < 16 then (if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 31 else 2) else (if i.val < 3 then 5 else 14)) else (if i.val < 6 then (if i.val < 5 then 28 else 8) else (if i.val < 7 then 17 else 1))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 20 else 6) else (if i.val < 11 then 15 else 11)) else (if i.val < 14 then (if i.val < 13 then 16 else 29) else (if i.val < 15 then 27 else 0)))) else (if i.val < 24 then (if i.val < 20 then (if i.val < 18 then (if i.val < 17 then 21 else 26) else (if i.val < 19 then 7 else 12)) else (if i.val < 22 then (if i.val < 21 then 10 else 19) else (if i.val < 23 then 22 else 30))) else (if i.val < 28 then (if i.val < 26 then (if i.val < 25 then 25 else 3) else (if i.val < 27 then 4 else 13)) else (if i.val < 30 then (if i.val < 29 then 9 else 18) else (if i.val < 31 then 23 else 24))))) : Fin 32)⟩
private def quotientNext (i : Fin 32) (j : Fin 4) : Fin 32 := ((if i.val < 16 then (if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[1,2,3,4] else #[0,5,6,7]) else (if i.val < 3 then #[5,0,8,9] else #[6,8,0,10])) else (if i.val < 6 then (if i.val < 5 then #[11,9,12,13] else #[2,1,14,11]) else (if i.val < 7 then #[3,14,1,12] else #[9,11,10,15]))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then #[14,3,2,16] else #[7,4,17,18]) else (if i.val < 11 then #[17,16,7,19] else #[4,7,16,20])) else (if i.val < 14 then (if i.val < 13 then #[16,17,4,21] else #[15,18,22,23]) else (if i.val < 15 then #[8,6,5,17] else #[13,20,24,25])))) else (if i.val < 24 then (if i.val < 20 then (if i.val < 18 then (if i.val < 17 then #[12,10,11,22] else #[10,12,9,24]) else (if i.val < 19 then #[20,13,19,26] else #[21,22,18,27])) else (if i.val < 22 then (if i.val < 21 then #[18,15,21,28] else #[19,24,20,29]) else (if i.val < 23 then #[24,19,13,30] else #[28,26,31,0]))) else (if i.val < 28 then (if i.val < 26 then (if i.val < 25 then #[22,21,15,31] else #[26,28,30,1]) else (if i.val < 27 then #[25,23,29,2] else #[31,30,28,3])) else (if i.val < 30 then (if i.val < 29 then #[23,25,27,5] else #[30,31,26,6]) else (if i.val < 31 then #[29,27,25,8] else #[27,29,23,14]))))) : Array (Fin 32))[j.val]!
private def quotientPrev (i : Fin 32) (j : Fin 4) : Fin 32 := ((if i.val < 16 then (if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[1,2,3,23] else #[0,5,6,25]) else (if i.val < 3 then #[5,0,8,26] else #[6,8,0,27])) else (if i.val < 6 then (if i.val < 5 then #[11,9,12,0] else #[2,1,14,28]) else (if i.val < 7 then #[3,14,1,29] else #[9,11,10,1]))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then #[14,3,2,30] else #[7,4,17,2]) else (if i.val < 11 then #[17,16,7,3] else #[4,7,16,5])) else (if i.val < 14 then (if i.val < 13 then #[16,17,4,6] else #[15,18,22,4]) else (if i.val < 15 then #[8,6,5,31] else #[13,20,24,7])))) else (if i.val < 24 then (if i.val < 20 then (if i.val < 18 then (if i.val < 17 then #[12,10,11,8] else #[10,12,9,14]) else (if i.val < 19 then #[20,13,19,9] else #[21,22,18,10])) else (if i.val < 22 then (if i.val < 21 then #[18,15,21,11] else #[19,24,20,12]) else (if i.val < 23 then #[24,19,13,16] else #[28,26,31,13]))) else (if i.val < 28 then (if i.val < 26 then (if i.val < 25 then #[22,21,15,17] else #[26,28,30,15]) else (if i.val < 27 then #[25,23,29,18] else #[31,30,28,19])) else (if i.val < 30 then (if i.val < 29 then #[23,25,27,20] else #[30,31,26,21]) else (if i.val < 31 then #[29,27,25,22] else #[27,29,23,24]))))) : Array (Fin 32))[j.val]!
private def quotientParents (i : Fin 32) : Fin 32 := ((if i.val < 16 then (if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 0 else 0)) else (if i.val < 6 then (if i.val < 5 then 0 else 1) else (if i.val < 7 then 1 else 1))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 2 else 2) else (if i.val < 11 then 3 else 4)) else (if i.val < 14 then (if i.val < 13 then 4 else 4) else (if i.val < 15 then 5 else 7)))) else (if i.val < 24 then (if i.val < 20 then (if i.val < 18 then (if i.val < 17 then 8 else 9) else (if i.val < 19 then 9 else 10)) else (if i.val < 22 then (if i.val < 21 then 11 else 12) else (if i.val < 23 then 13 else 13))) else (if i.val < 28 then (if i.val < 26 then (if i.val < 25 then 15 else 15) else (if i.val < 27 then 18 else 19)) else (if i.val < 30 then (if i.val < 29 then 20 else 21) else (if i.val < 31 then 22 else 23))))) : Fin 32)
private def quotientLetters (i : Fin 32) : Fin 4 := ((if i.val < 16 then (if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 1 else 2)) else (if i.val < 6 then (if i.val < 5 then 3 else 1) else (if i.val < 7 then 2 else 3))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 2 else 3) else (if i.val < 11 then 3 else 0)) else (if i.val < 14 then (if i.val < 13 then 2 else 3) else (if i.val < 15 then 2 else 3)))) else (if i.val < 24 then (if i.val < 20 then (if i.val < 18 then (if i.val < 17 then 3 else 2) else (if i.val < 19 then 3 else 3)) else (if i.val < 22 then (if i.val < 21 then 3 else 3) else (if i.val < 23 then 2 else 3))) else (if i.val < 28 then (if i.val < 26 then (if i.val < 25 then 2 else 3) else (if i.val < 27 then 3 else 3)) else (if i.val < 30 then (if i.val < 29 then 3 else 3) else (if i.val < 31 then 3 else 2))))) : Fin 4)
private def stepWitness (i : Fin 32) (j : Fin 4) : Fin 1 := ((if i.val < 16 then (if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[0,0,0,0] else #[0,0,0,0]) else (if i.val < 3 then #[0,0,0,0] else #[0,0,0,0])) else (if i.val < 6 then (if i.val < 5 then #[0,0,0,0] else #[0,0,0,0]) else (if i.val < 7 then #[0,0,0,0] else #[0,0,0,0]))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then #[0,0,0,0] else #[0,0,0,0]) else (if i.val < 11 then #[0,0,0,0] else #[0,0,0,0])) else (if i.val < 14 then (if i.val < 13 then #[0,0,0,0] else #[0,0,0,0]) else (if i.val < 15 then #[0,0,0,0] else #[0,0,0,0])))) else (if i.val < 24 then (if i.val < 20 then (if i.val < 18 then (if i.val < 17 then #[0,0,0,0] else #[0,0,0,0]) else (if i.val < 19 then #[0,0,0,0] else #[0,0,0,0])) else (if i.val < 22 then (if i.val < 21 then #[0,0,0,0] else #[0,0,0,0]) else (if i.val < 23 then #[0,0,0,0] else #[0,0,0,0]))) else (if i.val < 28 then (if i.val < 26 then (if i.val < 25 then #[0,0,0,0] else #[0,0,0,0]) else (if i.val < 27 then #[0,0,0,0] else #[0,0,0,0])) else (if i.val < 30 then (if i.val < 29 then #[0,0,0,0] else #[0,0,0,0]) else (if i.val < 31 then #[0,0,0,0] else #[0,0,0,0]))))) : Array (Fin 1))[j.val]!
private theorem quotientStep_checked : ∀ i j,
    representatives (quotientNext i j)/(representatives i*generators j)=
      (⟨rows (stepWitness i j)⟩ : Source) := (Fin.addCases (m := 16) (n := 16) (by decide +kernel) (by decide +kernel))

def cosets : BinaryNormalCosetCertificate generators kernel 32 where
  representatives := representatives
  identity := 0
  identity_mem := by
    have he : representatives 0=(⟨rows 0⟩ : Source) := by decide +kernel
    exact he ▸ row_mem 0
  next := quotientNext
  step_mem := fun i j => (quotientStep_checked i j) ▸ row_mem (stepWitness i j)
  rank i := i.val
  parent i _ := quotientParents i
  letter i _ := quotientLetters i
  parent_lt := (Fin.addCases (m := 16) (n := 16) (by decide +kernel) (by decide +kernel))
  parent_next := (Fin.addCases (m := 16) (n := 16) (by decide +kernel) (by decide +kernel))

@[reducible] def state : BinaryNormalState generators where
  kernel := kernel
  normal := normal
  generatorCount := 0
  normalGenerators := normalGenerators
  generated := rfl
  quotientCount := 32
  cardinal := by rw [kernel_card,source_card]
  cosets := cosets
  prev := quotientPrev
  prev_next := (Fin.addCases (m := 16) (n := 16) (by decide +kernel) (by decide +kernel))

end N0

namespace N1
def normalGenerators (j : Fin 1) : Source := ⟨(5 : Fin 32)⟩
def kernel : Subgroup Source := Subgroup.closure (Set.range normalGenerators)
private def rows (i : Fin 2) : Fin 32 := ((if i.val < 1 then 5 else 31) : Fin 32)
private def next (i : Fin 2) (j : Fin 1) : Fin 2 := ((if i.val < 1 then #[1] else #[0]) : Array (Fin 2))[j.val]!
private def rank (i : Fin 2) : ℕ := (if i.val < 1 then 1 else 0)
private def parents (i : Fin 2) : Fin 2 := ((if i.val < 1 then 1 else 1) : Fin 2)
private def letters (i : Fin 2) : Fin 1 := ((if i.val < 1 then 0 else 0) : Fin 1)

def normalCertificate : EncodedCayleyCertificate (binaryNormalRowEncoding normalGenerators) 2 where
  rows := rows
  identity := 1
  identity_eq := by decide +kernel
  next := next
  next_eq := (by decide +kernel)
  rank := rank
  parent i _ := parents i
  letter i hi := letters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

theorem normalRows_injective : Function.Injective normalCertificate.rows := by decide +kernel

theorem kernel_card : Nat.card kernel=2 := normalCertificate.card_closure normalRows_injective

theorem row_mem (i : Fin 2) : (⟨rows i⟩ : Source)∈kernel :=
  binaryNormalRow_mem normalCertificate i

private def posWitness (i : Fin 4) (j : Fin 1) : Fin 2 := ((if i.val < 2 then (if i.val < 1 then #[0] else #[0]) else (if i.val < 3 then #[0] else #[0])) : Array (Fin 2))[j.val]!
private def negWitness (i : Fin 4) (j : Fin 1) : Fin 2 := ((if i.val < 2 then (if i.val < 1 then #[0] else #[0]) else (if i.val < 3 then #[0] else #[0])) : Array (Fin 2))[j.val]!
private theorem pos_checked : ∀ i j, generators i*normalGenerators j*(generators i)⁻¹=
    (⟨rows (posWitness i j)⟩ : Source) := by decide +kernel
private theorem neg_checked : ∀ i j, (generators i)⁻¹*normalGenerators j*generators i=
    (⟨rows (negWitness i j)⟩ : Source) := by decide +kernel

instance normal : kernel.Normal := binaryNormal_of_generator_conjugates generators generators_full
  normalGenerators (fun i j => (pos_checked i j) ▸ row_mem (posWitness i j))
  (fun i j => (neg_checked i j) ▸ row_mem (negWitness i j))

private def representatives (i : Fin 16) : Source := ⟨((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 31 else 2) else (if i.val < 3 then 14 else 28)) else (if i.val < 6 then (if i.val < 5 then 17 else 1) else (if i.val < 7 then 15 else 16))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 29 else 0) else (if i.val < 11 then 12 else 19)) else (if i.val < 14 then (if i.val < 13 then 30 else 3) else (if i.val < 15 then 13 else 18)))) : Fin 32)⟩
private def quotientNext (i : Fin 16) (j : Fin 4) : Fin 16 := ((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[1,0,2,3] else #[0,1,4,5]) else (if i.val < 3 then #[4,2,0,6] else #[5,3,7,8])) else (if i.val < 6 then (if i.val < 5 then #[2,4,1,7] else #[3,5,6,9]) else (if i.val < 7 then #[7,6,5,10] else #[6,7,3,11]))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then #[9,8,10,12] else #[8,9,11,13]) else (if i.val < 11 then #[11,10,8,14] else #[10,11,9,15])) else (if i.val < 14 then (if i.val < 13 then #[13,12,15,0] else #[12,13,14,1]) else (if i.val < 15 then #[15,14,13,2] else #[14,15,12,4])))) : Array (Fin 16))[j.val]!
private def quotientPrev (i : Fin 16) (j : Fin 4) : Fin 16 := ((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[1,0,2,12] else #[0,1,4,13]) else (if i.val < 3 then #[4,2,0,14] else #[5,3,7,0])) else (if i.val < 6 then (if i.val < 5 then #[2,4,1,15] else #[3,5,6,1]) else (if i.val < 7 then #[7,6,5,2] else #[6,7,3,4]))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then #[9,8,10,3] else #[8,9,11,5]) else (if i.val < 11 then #[11,10,8,6] else #[10,11,9,7])) else (if i.val < 14 then (if i.val < 13 then #[13,12,15,8] else #[12,13,14,9]) else (if i.val < 15 then #[15,14,13,10] else #[14,15,12,11])))) : Array (Fin 16))[j.val]!
private def quotientParents (i : Fin 16) : Fin 16 := ((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 0 else 0)) else (if i.val < 6 then (if i.val < 5 then 1 else 1) else (if i.val < 7 then 2 else 3))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 3 else 5) else (if i.val < 11 then 6 else 7)) else (if i.val < 14 then (if i.val < 13 then 8 else 9) else (if i.val < 15 then 10 else 11)))) : Fin 16)
private def quotientLetters (i : Fin 16) : Fin 4 := ((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 2 else 3)) else (if i.val < 6 then (if i.val < 5 then 2 else 3) else (if i.val < 7 then 3 else 2))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 3 else 3) else (if i.val < 11 then 3 else 3)) else (if i.val < 14 then (if i.val < 13 then 3 else 3) else (if i.val < 15 then 3 else 3)))) : Fin 4)
private def stepWitness (i : Fin 16) (j : Fin 4) : Fin 2 := ((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[1,0,1,1] else #[1,0,1,1]) else (if i.val < 3 then #[1,0,1,1] else #[0,0,1,1])) else (if i.val < 6 then (if i.val < 5 then #[1,0,1,1] else #[0,0,1,1]) else (if i.val < 7 then #[0,0,1,1] else #[0,0,1,1]))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then #[1,0,0,1] else #[1,0,0,1]) else (if i.val < 11 then #[1,0,0,1] else #[1,0,0,1])) else (if i.val < 14 then (if i.val < 13 then #[0,0,0,1] else #[0,0,0,1]) else (if i.val < 15 then #[0,0,0,1] else #[0,0,0,1])))) : Array (Fin 2))[j.val]!
private theorem quotientStep_checked : ∀ i j,
    representatives (quotientNext i j)/(representatives i*generators j)=
      (⟨rows (stepWitness i j)⟩ : Source) := (by decide +kernel)

def cosets : BinaryNormalCosetCertificate generators kernel 16 where
  representatives := representatives
  identity := 0
  identity_mem := by
    have he : representatives 0=(⟨rows 1⟩ : Source) := by decide +kernel
    exact he ▸ row_mem 1
  next := quotientNext
  step_mem := fun i j => (quotientStep_checked i j) ▸ row_mem (stepWitness i j)
  rank i := i.val
  parent i _ := quotientParents i
  letter i _ := quotientLetters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

@[reducible] def state : BinaryNormalState generators where
  kernel := kernel
  normal := normal
  generatorCount := 1
  normalGenerators := normalGenerators
  generated := rfl
  quotientCount := 16
  cardinal := by rw [kernel_card,source_card]
  cosets := cosets
  prev := quotientPrev
  prev_next := (by decide +kernel)

end N1

namespace N2
def normalGenerators (j : Fin 2) : Source := ⟨((if j.val < 1 then 10 else 5) : Fin 32)⟩
def kernel : Subgroup Source := Subgroup.closure (Set.range normalGenerators)
private def rows (i : Fin 4) : Fin 32 := ((if i.val < 2 then (if i.val < 1 then 0 else 5) else (if i.val < 3 then 10 else 31)) : Fin 32)
private def next (i : Fin 4) (j : Fin 2) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[1,2] else #[0,3]) else (if i.val < 3 then #[3,0] else #[2,1])) : Array (Fin 4))[j.val]!
private def rank (i : Fin 4) : ℕ := (if i.val < 2 then (if i.val < 1 then 3 else 2) else (if i.val < 3 then 1 else 0))
private def parents (i : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then 2 else 3) else (if i.val < 3 then 3 else 3)) : Fin 4)
private def letters (i : Fin 4) : Fin 2 := ((if i.val < 2 then (if i.val < 1 then 1 else 1) else (if i.val < 3 then 0 else 0)) : Fin 2)

def normalCertificate : EncodedCayleyCertificate (binaryNormalRowEncoding normalGenerators) 4 where
  rows := rows
  identity := 3
  identity_eq := by decide +kernel
  next := next
  next_eq := (by decide +kernel)
  rank := rank
  parent i _ := parents i
  letter i hi := letters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

theorem normalRows_injective : Function.Injective normalCertificate.rows := by decide +kernel

theorem kernel_card : Nat.card kernel=4 := normalCertificate.card_closure normalRows_injective

theorem row_mem (i : Fin 4) : (⟨rows i⟩ : Source)∈kernel :=
  binaryNormalRow_mem normalCertificate i

private def posWitness (i : Fin 4) (j : Fin 2) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[2,1] else #[2,1]) else (if i.val < 3 then #[0,1] else #[0,1])) : Array (Fin 4))[j.val]!
private def negWitness (i : Fin 4) (j : Fin 2) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[2,1] else #[2,1]) else (if i.val < 3 then #[0,1] else #[0,1])) : Array (Fin 4))[j.val]!
private theorem pos_checked : ∀ i j, generators i*normalGenerators j*(generators i)⁻¹=
    (⟨rows (posWitness i j)⟩ : Source) := by decide +kernel
private theorem neg_checked : ∀ i j, (generators i)⁻¹*normalGenerators j*generators i=
    (⟨rows (negWitness i j)⟩ : Source) := by decide +kernel

instance normal : kernel.Normal := binaryNormal_of_generator_conjugates generators generators_full
  normalGenerators (fun i j => (pos_checked i j) ▸ row_mem (posWitness i j))
  (fun i j => (neg_checked i j) ▸ row_mem (negWitness i j))

private def representatives (i : Fin 8) : Source := ⟨((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 31 else 2) else (if i.val < 3 then 14 else 28)) else (if i.val < 6 then (if i.val < 5 then 17 else 1) else (if i.val < 7 then 15 else 16))) : Fin 32)⟩
private def quotientNext (i : Fin 8) (j : Fin 4) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[1,0,2,3] else #[0,1,4,5]) else (if i.val < 3 then #[4,2,0,6] else #[5,3,7,1])) else (if i.val < 6 then (if i.val < 5 then #[2,4,1,7] else #[3,5,6,0]) else (if i.val < 7 then #[7,6,5,4] else #[6,7,3,2]))) : Array (Fin 8))[j.val]!
private def quotientPrev (i : Fin 8) (j : Fin 4) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[1,0,2,5] else #[0,1,4,3]) else (if i.val < 3 then #[4,2,0,7] else #[5,3,7,0])) else (if i.val < 6 then (if i.val < 5 then #[2,4,1,6] else #[3,5,6,1]) else (if i.val < 7 then #[7,6,5,2] else #[6,7,3,4]))) : Array (Fin 8))[j.val]!
private def quotientParents (i : Fin 8) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 0 else 0)) else (if i.val < 6 then (if i.val < 5 then 1 else 1) else (if i.val < 7 then 2 else 3))) : Fin 8)
private def quotientLetters (i : Fin 8) : Fin 4 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 2 else 3)) else (if i.val < 6 then (if i.val < 5 then 2 else 3) else (if i.val < 7 then 3 else 2))) : Fin 4)
private def stepWitness (i : Fin 8) (j : Fin 4) : Fin 4 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[3,1,3,3] else #[3,1,3,3]) else (if i.val < 3 then #[3,1,3,3] else #[1,1,3,0])) else (if i.val < 6 then (if i.val < 5 then #[3,1,3,3] else #[1,1,3,0]) else (if i.val < 7 then #[1,1,3,2] else #[1,1,3,2]))) : Array (Fin 4))[j.val]!
private theorem quotientStep_checked : ∀ i j,
    representatives (quotientNext i j)/(representatives i*generators j)=
      (⟨rows (stepWitness i j)⟩ : Source) := (by decide +kernel)

def cosets : BinaryNormalCosetCertificate generators kernel 8 where
  representatives := representatives
  identity := 0
  identity_mem := by
    have he : representatives 0=(⟨rows 3⟩ : Source) := by decide +kernel
    exact he ▸ row_mem 3
  next := quotientNext
  step_mem := fun i j => (quotientStep_checked i j) ▸ row_mem (stepWitness i j)
  rank i := i.val
  parent i _ := quotientParents i
  letter i _ := quotientLetters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

@[reducible] def state : BinaryNormalState generators where
  kernel := kernel
  normal := normal
  generatorCount := 2
  normalGenerators := normalGenerators
  generated := rfl
  quotientCount := 8
  cardinal := by rw [kernel_card,source_card]
  cosets := cosets
  prev := quotientPrev
  prev_next := (by decide +kernel)

end N2

namespace N3
def normalGenerators (j : Fin 2) : Source := ⟨((if j.val < 1 then 29 else 5) : Fin 32)⟩
def kernel : Subgroup Source := Subgroup.closure (Set.range normalGenerators)
private def rows (i : Fin 4) : Fin 32 := ((if i.val < 2 then (if i.val < 1 then 5 else 7) else (if i.val < 3 then 29 else 31)) : Fin 32)
private def next (i : Fin 4) (j : Fin 2) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[1,3] else #[0,2]) else (if i.val < 3 then #[3,1] else #[2,0])) : Array (Fin 4))[j.val]!
private def rank (i : Fin 4) : ℕ := (if i.val < 2 then (if i.val < 1 then 2 else 3) else (if i.val < 3 then 1 else 0))
private def parents (i : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then 3 else 2) else (if i.val < 3 then 3 else 3)) : Fin 4)
private def letters (i : Fin 4) : Fin 2 := ((if i.val < 2 then (if i.val < 1 then 1 else 1) else (if i.val < 3 then 0 else 0)) : Fin 2)

def normalCertificate : EncodedCayleyCertificate (binaryNormalRowEncoding normalGenerators) 4 where
  rows := rows
  identity := 3
  identity_eq := by decide +kernel
  next := next
  next_eq := (by decide +kernel)
  rank := rank
  parent i _ := parents i
  letter i hi := letters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

theorem normalRows_injective : Function.Injective normalCertificate.rows := by decide +kernel

theorem kernel_card : Nat.card kernel=4 := normalCertificate.card_closure normalRows_injective

theorem row_mem (i : Fin 4) : (⟨rows i⟩ : Source)∈kernel :=
  binaryNormalRow_mem normalCertificate i

private def posWitness (i : Fin 4) (j : Fin 2) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[2,0] else #[2,0]) else (if i.val < 3 then #[1,0] else #[2,0])) : Array (Fin 4))[j.val]!
private def negWitness (i : Fin 4) (j : Fin 2) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[2,0] else #[2,0]) else (if i.val < 3 then #[1,0] else #[2,0])) : Array (Fin 4))[j.val]!
private theorem pos_checked : ∀ i j, generators i*normalGenerators j*(generators i)⁻¹=
    (⟨rows (posWitness i j)⟩ : Source) := by decide +kernel
private theorem neg_checked : ∀ i j, (generators i)⁻¹*normalGenerators j*generators i=
    (⟨rows (negWitness i j)⟩ : Source) := by decide +kernel

instance normal : kernel.Normal := binaryNormal_of_generator_conjugates generators generators_full
  normalGenerators (fun i j => (pos_checked i j) ▸ row_mem (posWitness i j))
  (fun i j => (neg_checked i j) ▸ row_mem (negWitness i j))

private def representatives (i : Fin 8) : Source := ⟨((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 31 else 2) else (if i.val < 3 then 14 else 28)) else (if i.val < 6 then (if i.val < 5 then 17 else 1) else (if i.val < 7 then 15 else 16))) : Fin 32)⟩
private def quotientNext (i : Fin 8) (j : Fin 4) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[1,0,2,3] else #[0,1,4,5]) else (if i.val < 3 then #[4,2,0,6] else #[5,3,7,0])) else (if i.val < 6 then (if i.val < 5 then #[2,4,1,7] else #[3,5,6,1]) else (if i.val < 7 then #[7,6,5,2] else #[6,7,3,4]))) : Array (Fin 8))[j.val]!
private def quotientPrev (i : Fin 8) (j : Fin 4) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[1,0,2,3] else #[0,1,4,5]) else (if i.val < 3 then #[4,2,0,6] else #[5,3,7,0])) else (if i.val < 6 then (if i.val < 5 then #[2,4,1,7] else #[3,5,6,1]) else (if i.val < 7 then #[7,6,5,2] else #[6,7,3,4]))) : Array (Fin 8))[j.val]!
private def quotientParents (i : Fin 8) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 0 else 0)) else (if i.val < 6 then (if i.val < 5 then 1 else 1) else (if i.val < 7 then 2 else 3))) : Fin 8)
private def quotientLetters (i : Fin 8) : Fin 4 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 2 else 3)) else (if i.val < 6 then (if i.val < 5 then 2 else 3) else (if i.val < 7 then 3 else 2))) : Fin 4)
private def stepWitness (i : Fin 8) (j : Fin 4) : Fin 4 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[3,0,3,3] else #[3,0,3,3]) else (if i.val < 3 then #[3,0,3,3] else #[0,0,3,2])) else (if i.val < 6 then (if i.val < 5 then #[3,0,3,3] else #[0,0,3,2]) else (if i.val < 7 then #[0,0,3,1] else #[0,0,3,1]))) : Array (Fin 4))[j.val]!
private theorem quotientStep_checked : ∀ i j,
    representatives (quotientNext i j)/(representatives i*generators j)=
      (⟨rows (stepWitness i j)⟩ : Source) := (by decide +kernel)

def cosets : BinaryNormalCosetCertificate generators kernel 8 where
  representatives := representatives
  identity := 0
  identity_mem := by
    have he : representatives 0=(⟨rows 3⟩ : Source) := by decide +kernel
    exact he ▸ row_mem 3
  next := quotientNext
  step_mem := fun i j => (quotientStep_checked i j) ▸ row_mem (stepWitness i j)
  rank i := i.val
  parent i _ := quotientParents i
  letter i _ := quotientLetters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

@[reducible] def state : BinaryNormalState generators where
  kernel := kernel
  normal := normal
  generatorCount := 2
  normalGenerators := normalGenerators
  generated := rfl
  quotientCount := 8
  cardinal := by rw [kernel_card,source_card]
  cosets := cosets
  prev := quotientPrev
  prev_next := (by decide +kernel)

end N3

namespace N4
def normalGenerators (j : Fin 2) : Source := ⟨((if j.val < 1 then 8 else 2) : Fin 32)⟩
def kernel : Subgroup Source := Subgroup.closure (Set.range normalGenerators)
private def rows (i : Fin 4) : Fin 32 := ((if i.val < 2 then (if i.val < 1 then 2 else 5) else (if i.val < 3 then 8 else 31)) : Fin 32)
private def next (i : Fin 4) (j : Fin 2) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[1,3] else #[0,2]) else (if i.val < 3 then #[3,1] else #[2,0])) : Array (Fin 4))[j.val]!
private def rank (i : Fin 4) : ℕ := (if i.val < 2 then (if i.val < 1 then 2 else 3) else (if i.val < 3 then 1 else 0))
private def parents (i : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then 3 else 2) else (if i.val < 3 then 3 else 3)) : Fin 4)
private def letters (i : Fin 4) : Fin 2 := ((if i.val < 2 then (if i.val < 1 then 1 else 1) else (if i.val < 3 then 0 else 0)) : Fin 2)

def normalCertificate : EncodedCayleyCertificate (binaryNormalRowEncoding normalGenerators) 4 where
  rows := rows
  identity := 3
  identity_eq := by decide +kernel
  next := next
  next_eq := (by decide +kernel)
  rank := rank
  parent i _ := parents i
  letter i hi := letters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

theorem normalRows_injective : Function.Injective normalCertificate.rows := by decide +kernel

theorem kernel_card : Nat.card kernel=4 := normalCertificate.card_closure normalRows_injective

theorem row_mem (i : Fin 4) : (⟨rows i⟩ : Source)∈kernel :=
  binaryNormalRow_mem normalCertificate i

private def posWitness (i : Fin 4) (j : Fin 2) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[2,0] else #[2,0]) else (if i.val < 3 then #[2,0] else #[0,2])) : Array (Fin 4))[j.val]!
private def negWitness (i : Fin 4) (j : Fin 2) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[2,0] else #[2,0]) else (if i.val < 3 then #[2,0] else #[0,2])) : Array (Fin 4))[j.val]!
private theorem pos_checked : ∀ i j, generators i*normalGenerators j*(generators i)⁻¹=
    (⟨rows (posWitness i j)⟩ : Source) := by decide +kernel
private theorem neg_checked : ∀ i j, (generators i)⁻¹*normalGenerators j*generators i=
    (⟨rows (negWitness i j)⟩ : Source) := by decide +kernel

instance normal : kernel.Normal := binaryNormal_of_generator_conjugates generators generators_full
  normalGenerators (fun i j => (pos_checked i j) ▸ row_mem (posWitness i j))
  (fun i j => (neg_checked i j) ▸ row_mem (negWitness i j))

private def representatives (i : Fin 8) : Source := ⟨((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 31 else 14) else (if i.val < 3 then 28 else 15)) else (if i.val < 6 then (if i.val < 5 then 29 else 12) else (if i.val < 7 then 30 else 13))) : Fin 32)⟩
private def quotientNext (i : Fin 8) (j : Fin 4) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[0,0,1,2] else #[1,1,0,3]) else (if i.val < 3 then #[2,2,3,4] else #[3,3,2,5])) else (if i.val < 6 then (if i.val < 5 then #[4,4,5,6] else #[5,5,4,7]) else (if i.val < 7 then #[6,6,7,0] else #[7,7,6,1]))) : Array (Fin 8))[j.val]!
private def quotientPrev (i : Fin 8) (j : Fin 4) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[0,0,1,6] else #[1,1,0,7]) else (if i.val < 3 then #[2,2,3,0] else #[3,3,2,1])) else (if i.val < 6 then (if i.val < 5 then #[4,4,5,2] else #[5,5,4,3]) else (if i.val < 7 then #[6,6,7,4] else #[7,7,6,5]))) : Array (Fin 8))[j.val]!
private def quotientParents (i : Fin 8) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 0 else 1)) else (if i.val < 6 then (if i.val < 5 then 2 else 3) else (if i.val < 7 then 4 else 5))) : Fin 8)
private def quotientLetters (i : Fin 8) : Fin 4 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 2) else (if i.val < 3 then 3 else 3)) else (if i.val < 6 then (if i.val < 5 then 3 else 3) else (if i.val < 7 then 3 else 3))) : Fin 4)
private def stepWitness (i : Fin 8) (j : Fin 4) : Fin 4 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[0,1,3,3] else #[0,1,3,3]) else (if i.val < 3 then #[2,1,0,3] else #[2,1,0,3])) else (if i.val < 6 then (if i.val < 5 then #[0,1,1,3] else #[0,1,1,3]) else (if i.val < 7 then #[2,1,2,3] else #[2,1,2,3]))) : Array (Fin 4))[j.val]!
private theorem quotientStep_checked : ∀ i j,
    representatives (quotientNext i j)/(representatives i*generators j)=
      (⟨rows (stepWitness i j)⟩ : Source) := (by decide +kernel)

def cosets : BinaryNormalCosetCertificate generators kernel 8 where
  representatives := representatives
  identity := 0
  identity_mem := by
    have he : representatives 0=(⟨rows 3⟩ : Source) := by decide +kernel
    exact he ▸ row_mem 3
  next := quotientNext
  step_mem := fun i j => (quotientStep_checked i j) ▸ row_mem (stepWitness i j)
  rank i := i.val
  parent i _ := quotientParents i
  letter i _ := quotientLetters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

@[reducible] def state : BinaryNormalState generators where
  kernel := kernel
  normal := normal
  generatorCount := 2
  normalGenerators := normalGenerators
  generated := rfl
  quotientCount := 8
  cardinal := by rw [kernel_card,source_card]
  cosets := cosets
  prev := quotientPrev
  prev_next := (by decide +kernel)

end N4

namespace N5
def normalGenerators (j : Fin 3) : Source := ⟨((if j.val < 1 then 12 else (if j.val < 2 then 8 else 2)) : Fin 32)⟩
def kernel : Subgroup Source := Subgroup.closure (Set.range normalGenerators)
private def rows (i : Fin 8) : Fin 32 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 2 else 5) else (if i.val < 3 then 8 else 12)) else (if i.val < 6 then (if i.val < 5 then 19 else 22) else (if i.val < 7 then 25 else 31))) : Fin 32)
private def next (i : Fin 8) (j : Fin 3) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[4,1,7] else #[5,0,2]) else (if i.val < 3 then #[6,7,1] else #[1,6,4])) else (if i.val < 6 then (if i.val < 5 then #[2,5,3] else #[7,4,6]) else (if i.val < 7 then #[0,3,5] else #[3,2,0]))) : Array (Fin 8))[j.val]!
private def rank (i : Fin 8) : ℕ := (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 3 else 4) else (if i.val < 3 then 2 else 1)) else (if i.val < 6 then (if i.val < 5 then 6 else 7) else (if i.val < 7 then 5 else 0)))
private def parents (i : Fin 8) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 7 else 3) else (if i.val < 3 then 7 else 7)) else (if i.val < 6 then (if i.val < 5 then 3 else 1) else (if i.val < 7 then 3 else 7))) : Fin 8)
private def letters (i : Fin 8) : Fin 3 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 2 else 0) else (if i.val < 3 then 1 else 0)) else (if i.val < 6 then (if i.val < 5 then 2 else 0) else (if i.val < 7 then 1 else 0))) : Fin 3)

def normalCertificate : EncodedCayleyCertificate (binaryNormalRowEncoding normalGenerators) 8 where
  rows := rows
  identity := 7
  identity_eq := by decide +kernel
  next := next
  next_eq := (by decide +kernel)
  rank := rank
  parent i _ := parents i
  letter i hi := letters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

theorem normalRows_injective : Function.Injective normalCertificate.rows := by decide +kernel

theorem kernel_card : Nat.card kernel=8 := normalCertificate.card_closure normalRows_injective

theorem row_mem (i : Fin 8) : (⟨rows i⟩ : Source)∈kernel :=
  binaryNormalRow_mem normalCertificate i

private def posWitness (i : Fin 4) (j : Fin 3) : Fin 8 := ((if i.val < 2 then (if i.val < 1 then #[3,2,0] else #[3,2,0]) else (if i.val < 3 then #[5,2,0] else #[4,0,2])) : Array (Fin 8))[j.val]!
private def negWitness (i : Fin 4) (j : Fin 3) : Fin 8 := ((if i.val < 2 then (if i.val < 1 then #[3,2,0] else #[3,2,0]) else (if i.val < 3 then #[5,2,0] else #[6,0,2])) : Array (Fin 8))[j.val]!
private theorem pos_checked : ∀ i j, generators i*normalGenerators j*(generators i)⁻¹=
    (⟨rows (posWitness i j)⟩ : Source) := by decide +kernel
private theorem neg_checked : ∀ i j, (generators i)⁻¹*normalGenerators j*generators i=
    (⟨rows (negWitness i j)⟩ : Source) := by decide +kernel

instance normal : kernel.Normal := binaryNormal_of_generator_conjugates generators generators_full
  normalGenerators (fun i j => (pos_checked i j) ▸ row_mem (posWitness i j))
  (fun i j => (neg_checked i j) ▸ row_mem (negWitness i j))

private def representatives (i : Fin 4) : Source := ⟨((if i.val < 2 then (if i.val < 1 then 31 else 14) else (if i.val < 3 then 28 else 15)) : Fin 32)⟩
private def quotientNext (i : Fin 4) (j : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[0,0,1,2] else #[1,1,0,3]) else (if i.val < 3 then #[2,2,3,1] else #[3,3,2,0])) : Array (Fin 4))[j.val]!
private def quotientPrev (i : Fin 4) (j : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[0,0,1,3] else #[1,1,0,2]) else (if i.val < 3 then #[2,2,3,0] else #[3,3,2,1])) : Array (Fin 4))[j.val]!
private def quotientParents (i : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 0 else 1)) : Fin 4)
private def quotientLetters (i : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then 0 else 2) else (if i.val < 3 then 3 else 3)) : Fin 4)
private def stepWitness (i : Fin 4) (j : Fin 4) : Fin 8 := ((if i.val < 2 then (if i.val < 1 then #[0,1,7,7] else #[0,1,7,7]) else (if i.val < 3 then #[2,1,0,3] else #[2,1,0,5])) : Array (Fin 8))[j.val]!
private theorem quotientStep_checked : ∀ i j,
    representatives (quotientNext i j)/(representatives i*generators j)=
      (⟨rows (stepWitness i j)⟩ : Source) := (by decide +kernel)

def cosets : BinaryNormalCosetCertificate generators kernel 4 where
  representatives := representatives
  identity := 0
  identity_mem := by
    have he : representatives 0=(⟨rows 7⟩ : Source) := by decide +kernel
    exact he ▸ row_mem 7
  next := quotientNext
  step_mem := fun i j => (quotientStep_checked i j) ▸ row_mem (stepWitness i j)
  rank i := i.val
  parent i _ := quotientParents i
  letter i _ := quotientLetters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

@[reducible] def state : BinaryNormalState generators where
  kernel := kernel
  normal := normal
  generatorCount := 3
  normalGenerators := normalGenerators
  generated := rfl
  quotientCount := 4
  cardinal := by rw [kernel_card,source_card]
  cosets := cosets
  prev := quotientPrev
  prev_next := (by decide +kernel)

end N5

namespace N6
def normalGenerators (j : Fin 3) : Source := ⟨((if j.val < 1 then 29 else (if j.val < 2 then 8 else 2)) : Fin 32)⟩
def kernel : Subgroup Source := Subgroup.closure (Set.range normalGenerators)
private def rows (i : Fin 8) : Fin 32 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 2) else (if i.val < 3 then 5 else 7)) else (if i.val < 6 then (if i.val < 5 then 8 else 10) else (if i.val < 7 then 29 else 31))) : Fin 32)
private def next (i : Fin 8) (j : Fin 3) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[1,3,6] else #[0,2,7]) else (if i.val < 3 then #[3,1,4] else #[2,0,5])) else (if i.val < 6 then (if i.val < 5 then #[5,7,2] else #[4,6,3]) else (if i.val < 7 then #[7,5,0] else #[6,4,1]))) : Array (Fin 8))[j.val]!
private def rank (i : Fin 8) : ℕ := (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 5 else 3) else (if i.val < 3 then 6 else 7)) else (if i.val < 6 then (if i.val < 5 then 2 else 4) else (if i.val < 7 then 1 else 0)))
private def parents (i : Fin 8) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 6 else 7) else (if i.val < 3 then 4 else 5)) else (if i.val < 6 then (if i.val < 5 then 7 else 6) else (if i.val < 7 then 7 else 7))) : Fin 8)
private def letters (i : Fin 8) : Fin 3 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 2 else 2) else (if i.val < 3 then 2 else 2)) else (if i.val < 6 then (if i.val < 5 then 1 else 1) else (if i.val < 7 then 0 else 0))) : Fin 3)

def normalCertificate : EncodedCayleyCertificate (binaryNormalRowEncoding normalGenerators) 8 where
  rows := rows
  identity := 7
  identity_eq := by decide +kernel
  next := next
  next_eq := (by decide +kernel)
  rank := rank
  parent i _ := parents i
  letter i hi := letters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

theorem normalRows_injective : Function.Injective normalCertificate.rows := by decide +kernel

theorem kernel_card : Nat.card kernel=8 := normalCertificate.card_closure normalRows_injective

theorem row_mem (i : Fin 8) : (⟨rows i⟩ : Source)∈kernel :=
  binaryNormalRow_mem normalCertificate i

private def posWitness (i : Fin 4) (j : Fin 3) : Fin 8 := ((if i.val < 2 then (if i.val < 1 then #[6,4,1] else #[6,4,1]) else (if i.val < 3 then #[3,4,1] else #[6,1,4])) : Array (Fin 8))[j.val]!
private def negWitness (i : Fin 4) (j : Fin 3) : Fin 8 := ((if i.val < 2 then (if i.val < 1 then #[6,4,1] else #[6,4,1]) else (if i.val < 3 then #[3,4,1] else #[6,1,4])) : Array (Fin 8))[j.val]!
private theorem pos_checked : ∀ i j, generators i*normalGenerators j*(generators i)⁻¹=
    (⟨rows (posWitness i j)⟩ : Source) := by decide +kernel
private theorem neg_checked : ∀ i j, (generators i)⁻¹*normalGenerators j*generators i=
    (⟨rows (negWitness i j)⟩ : Source) := by decide +kernel

instance normal : kernel.Normal := binaryNormal_of_generator_conjugates generators generators_full
  normalGenerators (fun i j => (pos_checked i j) ▸ row_mem (posWitness i j))
  (fun i j => (neg_checked i j) ▸ row_mem (negWitness i j))

private def representatives (i : Fin 4) : Source := ⟨((if i.val < 2 then (if i.val < 1 then 31 else 14) else (if i.val < 3 then 28 else 15)) : Fin 32)⟩
private def quotientNext (i : Fin 4) (j : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[0,0,1,2] else #[1,1,0,3]) else (if i.val < 3 then #[2,2,3,0] else #[3,3,2,1])) : Array (Fin 4))[j.val]!
private def quotientPrev (i : Fin 4) (j : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[0,0,1,2] else #[1,1,0,3]) else (if i.val < 3 then #[2,2,3,0] else #[3,3,2,1])) : Array (Fin 4))[j.val]!
private def quotientParents (i : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 0 else 1)) : Fin 4)
private def quotientLetters (i : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then 0 else 2) else (if i.val < 3 then 3 else 3)) : Fin 4)
private def stepWitness (i : Fin 4) (j : Fin 4) : Fin 8 := ((if i.val < 2 then (if i.val < 1 then #[1,2,7,7] else #[1,2,7,7]) else (if i.val < 3 then #[4,2,1,6] else #[4,2,1,3])) : Array (Fin 8))[j.val]!
private theorem quotientStep_checked : ∀ i j,
    representatives (quotientNext i j)/(representatives i*generators j)=
      (⟨rows (stepWitness i j)⟩ : Source) := (by decide +kernel)

def cosets : BinaryNormalCosetCertificate generators kernel 4 where
  representatives := representatives
  identity := 0
  identity_mem := by
    have he : representatives 0=(⟨rows 7⟩ : Source) := by decide +kernel
    exact he ▸ row_mem 7
  next := quotientNext
  step_mem := fun i j => (quotientStep_checked i j) ▸ row_mem (stepWitness i j)
  rank i := i.val
  parent i _ := quotientParents i
  letter i _ := quotientLetters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

@[reducible] def state : BinaryNormalState generators where
  kernel := kernel
  normal := normal
  generatorCount := 3
  normalGenerators := normalGenerators
  generated := rfl
  quotientCount := 4
  cardinal := by rw [kernel_card,source_card]
  cosets := cosets
  prev := quotientPrev
  prev_next := (by decide +kernel)

end N6

namespace N7
def normalGenerators (j : Fin 3) : Source := ⟨((if j.val < 1 then 21 else (if j.val < 2 then 8 else 2)) : Fin 32)⟩
def kernel : Subgroup Source := Subgroup.closure (Set.range normalGenerators)
private def rows (i : Fin 16) : Fin 32 := ((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 2) else (if i.val < 3 then 5 else 7)) else (if i.val < 6 then (if i.val < 5 then 8 else 10) else (if i.val < 7 then 13 else 15))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 16 else 18) else (if i.val < 11 then 21 else 23)) else (if i.val < 14 then (if i.val < 13 then 24 else 26) else (if i.val < 15 then 29 else 31)))) : Fin 32)
private def next (i : Fin 16) (j : Fin 3) : Fin 16 := ((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[9,3,14] else #[13,2,15]) else (if i.val < 3 then #[7,1,4] else #[11,0,5])) else (if i.val < 6 then (if i.val < 5 then #[8,15,2] else #[12,14,3]) else (if i.val < 7 then #[1,9,12] else #[5,8,13]))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then #[3,7,10] else #[15,6,11]) else (if i.val < 11 then #[0,13,8] else #[4,12,9])) else (if i.val < 14 then (if i.val < 13 then #[2,11,6] else #[14,10,7]) else (if i.val < 15 then #[6,5,0] else #[10,4,1])))) : Array (Fin 16))[j.val]!
private def rank (i : Fin 16) : ℕ := (if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 4 else 3) else (if i.val < 3 then 7 else 9)) else (if i.val < 6 then (if i.val < 5 then 2 else 14) else (if i.val < 7 then 12 else 11))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 6 else 8) else (if i.val < 11 then 1 else 13)) else (if i.val < 14 then (if i.val < 13 then 15 else 5) else (if i.val < 15 then 10 else 0))))
private def parents (i : Fin 16) : Fin 16 := ((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 10 else 15) else (if i.val < 3 then 4 else 0)) else (if i.val < 6 then (if i.val < 5 then 15 else 3) else (if i.val < 7 then 9 else 13))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 10 else 0) else (if i.val < 11 then 15 else 9)) else (if i.val < 14 then (if i.val < 13 then 6 else 10) else (if i.val < 15 then 0 else 15)))) : Fin 16)
private def letters (i : Fin 16) : Fin 3 := ((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 2) else (if i.val < 3 then 2 else 1)) else (if i.val < 6 then (if i.val < 5 then 1 else 2) else (if i.val < 7 then 1 else 2))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 2 else 0) else (if i.val < 11 then 0 else 2)) else (if i.val < 14 then (if i.val < 13 then 2 else 1) else (if i.val < 15 then 2 else 0)))) : Fin 3)

def normalCertificate : EncodedCayleyCertificate (binaryNormalRowEncoding normalGenerators) 16 where
  rows := rows
  identity := 15
  identity_eq := by decide +kernel
  next := next
  next_eq := (by decide +kernel)
  rank := rank
  parent i _ := parents i
  letter i hi := letters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

theorem normalRows_injective : Function.Injective normalCertificate.rows := by decide +kernel

theorem kernel_card : Nat.card kernel=16 := normalCertificate.card_closure normalRows_injective

theorem row_mem (i : Fin 16) : (⟨rows i⟩ : Source)∈kernel :=
  binaryNormalRow_mem normalCertificate i

private def posWitness (i : Fin 4) (j : Fin 3) : Fin 16 := ((if i.val < 2 then (if i.val < 1 then #[7,4,1] else #[10,4,1]) else (if i.val < 3 then #[13,4,1] else #[13,1,4])) : Array (Fin 16))[j.val]!
private def negWitness (i : Fin 4) (j : Fin 3) : Fin 16 := ((if i.val < 2 then (if i.val < 1 then #[7,4,1] else #[10,4,1]) else (if i.val < 3 then #[13,4,1] else #[8,1,4])) : Array (Fin 16))[j.val]!
private theorem pos_checked : ∀ i j, generators i*normalGenerators j*(generators i)⁻¹=
    (⟨rows (posWitness i j)⟩ : Source) := by decide +kernel
private theorem neg_checked : ∀ i j, (generators i)⁻¹*normalGenerators j*generators i=
    (⟨rows (negWitness i j)⟩ : Source) := by decide +kernel

instance normal : kernel.Normal := binaryNormal_of_generator_conjugates generators generators_full
  normalGenerators (fun i j => (pos_checked i j) ▸ row_mem (posWitness i j))
  (fun i j => (neg_checked i j) ▸ row_mem (negWitness i j))

private def representatives (i : Fin 2) : Source := ⟨((if i.val < 1 then 31 else 14) : Fin 32)⟩
private def quotientNext (i : Fin 2) (j : Fin 4) : Fin 2 := ((if i.val < 1 then #[0,0,1,1] else #[1,1,0,0]) : Array (Fin 2))[j.val]!
private def quotientPrev (i : Fin 2) (j : Fin 4) : Fin 2 := ((if i.val < 1 then #[0,0,1,1] else #[1,1,0,0]) : Array (Fin 2))[j.val]!
private def quotientParents (i : Fin 2) : Fin 2 := ((if i.val < 1 then 0 else 0) : Fin 2)
private def quotientLetters (i : Fin 2) : Fin 4 := ((if i.val < 1 then 0 else 2) : Fin 4)
private def stepWitness (i : Fin 2) (j : Fin 4) : Fin 16 := ((if i.val < 1 then #[1,2,15,6] else #[1,2,15,12]) : Array (Fin 16))[j.val]!
private theorem quotientStep_checked : ∀ i j,
    representatives (quotientNext i j)/(representatives i*generators j)=
      (⟨rows (stepWitness i j)⟩ : Source) := (by decide +kernel)

def cosets : BinaryNormalCosetCertificate generators kernel 2 where
  representatives := representatives
  identity := 0
  identity_mem := by
    have he : representatives 0=(⟨rows 15⟩ : Source) := by decide +kernel
    exact he ▸ row_mem 15
  next := quotientNext
  step_mem := fun i j => (quotientStep_checked i j) ▸ row_mem (stepWitness i j)
  rank i := i.val
  parent i _ := quotientParents i
  letter i _ := quotientLetters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

@[reducible] def state : BinaryNormalState generators where
  kernel := kernel
  normal := normal
  generatorCount := 3
  normalGenerators := normalGenerators
  generated := rfl
  quotientCount := 2
  cardinal := by rw [kernel_card,source_card]
  cosets := cosets
  prev := quotientPrev
  prev_next := (by decide +kernel)

end N7

namespace N8
def normalGenerators (j : Fin 3) : Source := ⟨((if j.val < 1 then 6 else (if j.val < 2 then 8 else 2)) : Fin 32)⟩
def kernel : Subgroup Source := Subgroup.closure (Set.range normalGenerators)
private def rows (i : Fin 16) : Fin 32 := ((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 1) else (if i.val < 3 then 2 else 3)) else (if i.val < 6 then (if i.val < 5 then 4 else 5) else (if i.val < 7 then 6 else 7))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 8 else 9) else (if i.val < 11 then 10 else 11)) else (if i.val < 14 then (if i.val < 13 then 28 else 29) else (if i.val < 15 then 30 else 31)))) : Fin 32)
private def next (i : Fin 16) (j : Fin 3) : Fin 16 := ((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[9,7,13] else #[10,12,6]) else (if i.val < 3 then #[11,5,15] else #[8,14,4])) else (if i.val < 6 then (if i.val < 5 then #[15,9,3] else #[12,2,8]) else (if i.val < 7 then #[13,11,1] else #[14,0,10]))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then #[1,15,5] else #[2,4,14]) else (if i.val < 11 then #[3,13,7] else #[0,6,12])) else (if i.val < 14 then (if i.val < 13 then #[7,1,11] else #[4,10,0]) else (if i.val < 15 then #[5,3,9] else #[6,8,2])))) : Array (Fin 16))[j.val]!
private def rank (i : Fin 16) : ℕ := (if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 10 else 6) else (if i.val < 3 then 3 else 13)) else (if i.val < 6 then (if i.val < 5 then 8 else 7) else (if i.val < 7 then 1 else 14))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 2 else 12) else (if i.val < 11 then 9 else 5)) else (if i.val < 14 then (if i.val < 13 then 11 else 4) else (if i.val < 15 then 15 else 0))))
private def parents (i : Fin 16) : Fin 16 := ((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 13 else 6) else (if i.val < 3 then 15 else 4)) else (if i.val < 6 then (if i.val < 5 then 13 else 8) else (if i.val < 7 then 15 else 10))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 15 else 4) else (if i.val < 11 then 13 else 6)) else (if i.val < 14 then (if i.val < 13 then 11 else 6) else (if i.val < 15 then 9 else 15)))) : Fin 16)
private def letters (i : Fin 16) : Fin 3 := ((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 2 else 2) else (if i.val < 3 then 2 else 2)) else (if i.val < 6 then (if i.val < 5 then 0 else 2) else (if i.val < 7 then 0 else 2))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 1 else 1) else (if i.val < 11 then 1 else 1)) else (if i.val < 14 then (if i.val < 13 then 2 else 0) else (if i.val < 15 then 2 else 0)))) : Fin 3)

def normalCertificate : EncodedCayleyCertificate (binaryNormalRowEncoding normalGenerators) 16 where
  rows := rows
  identity := 15
  identity_eq := by decide +kernel
  next := next
  next_eq := (by decide +kernel)
  rank := rank
  parent i _ := parents i
  letter i hi := letters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

theorem normalRows_injective : Function.Injective normalCertificate.rows := by decide +kernel

theorem kernel_card : Nat.card kernel=16 := normalCertificate.card_closure normalRows_injective

theorem row_mem (i : Fin 16) : (⟨rows i⟩ : Source)∈kernel :=
  binaryNormalRow_mem normalCertificate i

private def posWitness (i : Fin 4) (j : Fin 3) : Fin 16 := ((if i.val < 2 then (if i.val < 1 then #[12,8,2] else #[6,8,2]) else (if i.val < 3 then #[11,8,2] else #[6,2,8])) : Array (Fin 16))[j.val]!
private def negWitness (i : Fin 4) (j : Fin 3) : Fin 16 := ((if i.val < 2 then (if i.val < 1 then #[12,8,2] else #[6,8,2]) else (if i.val < 3 then #[11,8,2] else #[6,2,8])) : Array (Fin 16))[j.val]!
private theorem pos_checked : ∀ i j, generators i*normalGenerators j*(generators i)⁻¹=
    (⟨rows (posWitness i j)⟩ : Source) := by decide +kernel
private theorem neg_checked : ∀ i j, (generators i)⁻¹*normalGenerators j*generators i=
    (⟨rows (negWitness i j)⟩ : Source) := by decide +kernel

instance normal : kernel.Normal := binaryNormal_of_generator_conjugates generators generators_full
  normalGenerators (fun i j => (pos_checked i j) ▸ row_mem (posWitness i j))
  (fun i j => (neg_checked i j) ▸ row_mem (negWitness i j))

private def representatives (i : Fin 2) : Source := ⟨((if i.val < 1 then 31 else 14) : Fin 32)⟩
private def quotientNext (i : Fin 2) (j : Fin 4) : Fin 2 := ((if i.val < 1 then #[0,0,1,0] else #[1,1,0,1]) : Array (Fin 2))[j.val]!
private def quotientPrev (i : Fin 2) (j : Fin 4) : Fin 2 := ((if i.val < 1 then #[0,0,1,0] else #[1,1,0,1]) : Array (Fin 2))[j.val]!
private def quotientParents (i : Fin 2) : Fin 2 := ((if i.val < 1 then 0 else 0) : Fin 2)
private def quotientLetters (i : Fin 2) : Fin 4 := ((if i.val < 1 then 0 else 2) : Fin 4)
private def stepWitness (i : Fin 2) (j : Fin 4) : Fin 16 := ((if i.val < 1 then #[2,5,15,14] else #[2,5,15,9]) : Array (Fin 16))[j.val]!
private theorem quotientStep_checked : ∀ i j,
    representatives (quotientNext i j)/(representatives i*generators j)=
      (⟨rows (stepWitness i j)⟩ : Source) := (by decide +kernel)

def cosets : BinaryNormalCosetCertificate generators kernel 2 where
  representatives := representatives
  identity := 0
  identity_mem := by
    have he : representatives 0=(⟨rows 15⟩ : Source) := by decide +kernel
    exact he ▸ row_mem 15
  next := quotientNext
  step_mem := fun i j => (quotientStep_checked i j) ▸ row_mem (stepWitness i j)
  rank i := i.val
  parent i _ := quotientParents i
  letter i _ := quotientLetters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

@[reducible] def state : BinaryNormalState generators where
  kernel := kernel
  normal := normal
  generatorCount := 3
  normalGenerators := normalGenerators
  generated := rfl
  quotientCount := 2
  cardinal := by rw [kernel_card,source_card]
  cosets := cosets
  prev := quotientPrev
  prev_next := (by decide +kernel)

end N8

namespace N9
def normalGenerators (j : Fin 3) : Source := ⟨((if j.val < 1 then 8 else (if j.val < 2 then 14 else 2)) : Fin 32)⟩
def kernel : Subgroup Source := Subgroup.closure (Set.range normalGenerators)
private def rows (i : Fin 8) : Fin 32 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 2 else 5) else (if i.val < 3 then 8 else 14)) else (if i.val < 6 then (if i.val < 5 then 17 else 20) else (if i.val < 7 then 27 else 31))) : Fin 32)
private def next (i : Fin 8) (j : Fin 3) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[1,4,7] else #[0,5,2]) else (if i.val < 3 then #[7,6,1] else #[6,7,4])) else (if i.val < 6 then (if i.val < 5 then #[5,0,3] else #[4,1,6]) else (if i.val < 7 then #[3,2,5] else #[2,3,0]))) : Array (Fin 8))[j.val]!
private def rank (i : Fin 8) : ℕ := (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 3 else 5) else (if i.val < 3 then 1 else 2)) else (if i.val < 6 then (if i.val < 5 then 6 else 7) else (if i.val < 7 then 4 else 0)))
private def parents (i : Fin 8) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 7 else 2) else (if i.val < 3 then 7 else 7)) else (if i.val < 6 then (if i.val < 5 then 3 else 6) else (if i.val < 7 then 2 else 7))) : Fin 8)
private def letters (i : Fin 8) : Fin 3 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 2 else 2) else (if i.val < 3 then 0 else 1)) else (if i.val < 6 then (if i.val < 5 then 2 else 2) else (if i.val < 7 then 1 else 0))) : Fin 3)

def normalCertificate : EncodedCayleyCertificate (binaryNormalRowEncoding normalGenerators) 8 where
  rows := rows
  identity := 7
  identity_eq := by decide +kernel
  next := next
  next_eq := (by decide +kernel)
  rank := rank
  parent i _ := parents i
  letter i hi := letters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

theorem normalRows_injective : Function.Injective normalCertificate.rows := by decide +kernel

theorem kernel_card : Nat.card kernel=8 := normalCertificate.card_closure normalRows_injective

theorem row_mem (i : Fin 8) : (⟨rows i⟩ : Source)∈kernel :=
  binaryNormalRow_mem normalCertificate i

private def posWitness (i : Fin 4) (j : Fin 3) : Fin 8 := ((if i.val < 2 then (if i.val < 1 then #[2,3,0] else #[2,3,0]) else (if i.val < 3 then #[2,3,0] else #[0,4,2])) : Array (Fin 8))[j.val]!
private def negWitness (i : Fin 4) (j : Fin 3) : Fin 8 := ((if i.val < 2 then (if i.val < 1 then #[2,3,0] else #[2,3,0]) else (if i.val < 3 then #[2,3,0] else #[0,6,2])) : Array (Fin 8))[j.val]!
private theorem pos_checked : ∀ i j, generators i*normalGenerators j*(generators i)⁻¹=
    (⟨rows (posWitness i j)⟩ : Source) := by decide +kernel
private theorem neg_checked : ∀ i j, (generators i)⁻¹*normalGenerators j*generators i=
    (⟨rows (negWitness i j)⟩ : Source) := by decide +kernel

instance normal : kernel.Normal := binaryNormal_of_generator_conjugates generators generators_full
  normalGenerators (fun i j => (pos_checked i j) ▸ row_mem (posWitness i j))
  (fun i j => (neg_checked i j) ▸ row_mem (negWitness i j))

private def representatives (i : Fin 4) : Source := ⟨((if i.val < 2 then (if i.val < 1 then 31 else 28) else (if i.val < 3 then 29 else 30)) : Fin 32)⟩
private def quotientNext (i : Fin 4) (j : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[0,0,0,1] else #[1,1,1,2]) else (if i.val < 3 then #[2,2,2,3] else #[3,3,3,0])) : Array (Fin 4))[j.val]!
private def quotientPrev (i : Fin 4) (j : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[0,0,0,3] else #[1,1,1,0]) else (if i.val < 3 then #[2,2,2,1] else #[3,3,3,2])) : Array (Fin 4))[j.val]!
private def quotientParents (i : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 1 else 2)) : Fin 4)
private def quotientLetters (i : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then 0 else 3) else (if i.val < 3 then 3 else 3)) : Fin 4)
private def stepWitness (i : Fin 4) (j : Fin 4) : Fin 8 := ((if i.val < 2 then (if i.val < 1 then #[0,1,3,7] else #[2,1,4,7]) else (if i.val < 3 then #[0,1,5,7] else #[2,1,6,7])) : Array (Fin 8))[j.val]!
private theorem quotientStep_checked : ∀ i j,
    representatives (quotientNext i j)/(representatives i*generators j)=
      (⟨rows (stepWitness i j)⟩ : Source) := (by decide +kernel)

def cosets : BinaryNormalCosetCertificate generators kernel 4 where
  representatives := representatives
  identity := 0
  identity_mem := by
    have he : representatives 0=(⟨rows 7⟩ : Source) := by decide +kernel
    exact he ▸ row_mem 7
  next := quotientNext
  step_mem := fun i j => (quotientStep_checked i j) ▸ row_mem (stepWitness i j)
  rank i := i.val
  parent i _ := quotientParents i
  letter i _ := quotientLetters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

@[reducible] def state : BinaryNormalState generators where
  kernel := kernel
  normal := normal
  generatorCount := 3
  normalGenerators := normalGenerators
  generated := rfl
  quotientCount := 4
  cardinal := by rw [kernel_card,source_card]
  cosets := cosets
  prev := quotientPrev
  prev_next := (by decide +kernel)

end N9

namespace N10
def normalGenerators (j : Fin 4) : Source := ⟨((if j.val < 2 then (if j.val < 1 then 29 else 8) else (if j.val < 3 then 14 else 2)) : Fin 32)⟩
def kernel : Subgroup Source := Subgroup.closure (Set.range normalGenerators)
private def rows (i : Fin 16) : Fin 32 := ((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 2) else (if i.val < 3 then 5 else 7)) else (if i.val < 6 then (if i.val < 5 then 8 else 10) else (if i.val < 7 then 12 else 14))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 17 else 19) else (if i.val < 11 then 20 else 22)) else (if i.val < 14 then (if i.val < 13 then 25 else 27) else (if i.val < 15 then 29 else 31)))) : Fin 32)
private def next (i : Fin 16) (j : Fin 4) : Fin 16 := ((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[1,3,12,14] else #[0,2,8,15]) else (if i.val < 3 then #[3,1,10,4] else #[2,0,6,5])) else (if i.val < 6 then (if i.val < 5 then #[5,15,13,2] else #[4,14,9,3]) else (if i.val < 7 then #[7,12,3,9] else #[6,13,15,8]))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then #[9,10,1,7] else #[8,11,5,6]) else (if i.val < 11 then #[11,8,2,13] else #[10,9,14,12])) else (if i.val < 14 then (if i.val < 13 then #[13,6,0,11] else #[12,7,4,10]) else (if i.val < 15 then #[15,5,11,0] else #[14,4,7,1])))) : Array (Fin 16))[j.val]!
private def rank (i : Fin 16) : ℕ := (if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 7 else 4) else (if i.val < 3 then 9 else 13)) else (if i.val < 6 then (if i.val < 5 then 2 else 5) else (if i.val < 7 then 10 else 3))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 11 else 12) else (if i.val < 11 then 14 else 6)) else (if i.val < 14 then (if i.val < 13 then 15 else 8) else (if i.val < 15 then 1 else 0))))
private def parents (i : Fin 16) : Fin 16 := ((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 14 else 15) else (if i.val < 3 then 4 else 5)) else (if i.val < 6 then (if i.val < 5 then 15 else 14) else (if i.val < 7 then 7 else 15))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 7 else 5) else (if i.val < 11 then 11 else 14)) else (if i.val < 14 then (if i.val < 13 then 11 else 4) else (if i.val < 15 then 15 else 15)))) : Fin 16)
private def letters (i : Fin 16) : Fin 4 := ((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 3 else 3) else (if i.val < 3 then 3 else 3)) else (if i.val < 6 then (if i.val < 5 then 1 else 1) else (if i.val < 7 then 0 else 2))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 3 else 2) else (if i.val < 11 then 0 else 2)) else (if i.val < 14 then (if i.val < 13 then 3 else 2) else (if i.val < 15 then 0 else 0)))) : Fin 4)

def normalCertificate : EncodedCayleyCertificate (binaryNormalRowEncoding normalGenerators) 16 where
  rows := rows
  identity := 15
  identity_eq := by decide +kernel
  next := next
  next_eq := (by decide +kernel)
  rank := rank
  parent i _ := parents i
  letter i hi := letters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

theorem normalRows_injective : Function.Injective normalCertificate.rows := by decide +kernel

theorem kernel_card : Nat.card kernel=16 := normalCertificate.card_closure normalRows_injective

theorem row_mem (i : Fin 16) : (⟨rows i⟩ : Source)∈kernel :=
  binaryNormalRow_mem normalCertificate i

private def posWitness (i : Fin 4) (j : Fin 4) : Fin 16 := ((if i.val < 2 then (if i.val < 1 then #[14,4,7,1] else #[14,4,7,1]) else (if i.val < 3 then #[3,4,7,1] else #[14,1,8,4])) : Array (Fin 16))[j.val]!
private def negWitness (i : Fin 4) (j : Fin 4) : Fin 16 := ((if i.val < 2 then (if i.val < 1 then #[14,4,7,1] else #[14,4,7,1]) else (if i.val < 3 then #[3,4,7,1] else #[14,1,13,4])) : Array (Fin 16))[j.val]!
private theorem pos_checked : ∀ i j, generators i*normalGenerators j*(generators i)⁻¹=
    (⟨rows (posWitness i j)⟩ : Source) := by decide +kernel
private theorem neg_checked : ∀ i j, (generators i)⁻¹*normalGenerators j*generators i=
    (⟨rows (negWitness i j)⟩ : Source) := by decide +kernel

instance normal : kernel.Normal := binaryNormal_of_generator_conjugates generators generators_full
  normalGenerators (fun i j => (pos_checked i j) ▸ row_mem (posWitness i j))
  (fun i j => (neg_checked i j) ▸ row_mem (negWitness i j))

private def representatives (i : Fin 2) : Source := ⟨((if i.val < 1 then 31 else 28) : Fin 32)⟩
private def quotientNext (i : Fin 2) (j : Fin 4) : Fin 2 := ((if i.val < 1 then #[0,0,0,1] else #[1,1,1,0]) : Array (Fin 2))[j.val]!
private def quotientPrev (i : Fin 2) (j : Fin 4) : Fin 2 := ((if i.val < 1 then #[0,0,0,1] else #[1,1,1,0]) : Array (Fin 2))[j.val]!
private def quotientParents (i : Fin 2) : Fin 2 := ((if i.val < 1 then 0 else 0) : Fin 2)
private def quotientLetters (i : Fin 2) : Fin 4 := ((if i.val < 1 then 0 else 3) : Fin 4)
private def stepWitness (i : Fin 2) (j : Fin 4) : Fin 16 := ((if i.val < 1 then #[1,2,7,15] else #[4,2,8,14]) : Array (Fin 16))[j.val]!
private theorem quotientStep_checked : ∀ i j,
    representatives (quotientNext i j)/(representatives i*generators j)=
      (⟨rows (stepWitness i j)⟩ : Source) := (by decide +kernel)

def cosets : BinaryNormalCosetCertificate generators kernel 2 where
  representatives := representatives
  identity := 0
  identity_mem := by
    have he : representatives 0=(⟨rows 15⟩ : Source) := by decide +kernel
    exact he ▸ row_mem 15
  next := quotientNext
  step_mem := fun i j => (quotientStep_checked i j) ▸ row_mem (stepWitness i j)
  rank i := i.val
  parent i _ := quotientParents i
  letter i _ := quotientLetters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

@[reducible] def state : BinaryNormalState generators where
  kernel := kernel
  normal := normal
  generatorCount := 4
  normalGenerators := normalGenerators
  generated := rfl
  quotientCount := 2
  cardinal := by rw [kernel_card,source_card]
  cosets := cosets
  prev := quotientPrev
  prev_next := (by decide +kernel)

end N10

namespace N11
def normalGenerators (j : Fin 4) : Source := ⟨((if j.val < 2 then (if j.val < 1 then 28 else 5) else (if j.val < 3 then 14 else 2)) : Fin 32)⟩
def kernel : Subgroup Source := Subgroup.closure (Set.range normalGenerators)
private def rows (i : Fin 32) : Fin 32 := ((if i.val < 16 then (if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 1) else (if i.val < 3 then 2 else 3)) else (if i.val < 6 then (if i.val < 5 then 4 else 5) else (if i.val < 7 then 6 else 7))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 8 else 9) else (if i.val < 11 then 10 else 11)) else (if i.val < 14 then (if i.val < 13 then 12 else 13) else (if i.val < 15 then 14 else 15)))) else (if i.val < 24 then (if i.val < 20 then (if i.val < 18 then (if i.val < 17 then 16 else 17) else (if i.val < 19 then 18 else 19)) else (if i.val < 22 then (if i.val < 21 then 20 else 21) else (if i.val < 23 then 22 else 23))) else (if i.val < 28 then (if i.val < 26 then (if i.val < 25 then 24 else 25) else (if i.val < 27 then 26 else 27)) else (if i.val < 30 then (if i.val < 29 then 28 else 29) else (if i.val < 31 then 30 else 31))))) : Fin 32)
private def next (i : Fin 32) (j : Fin 4) : Fin 32 := ((if i.val < 16 then (if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[3,10,25,29] else #[0,11,15,6]) else (if i.val < 3 then #[1,8,17,31] else #[2,9,23,4])) else (if i.val < 6 then (if i.val < 5 then #[5,30,18,3] else #[6,31,20,8]) else (if i.val < 7 then #[7,28,26,1] else #[4,29,12,10]))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then #[11,2,27,5] else #[8,3,13,30]) else (if i.val < 11 then #[9,0,19,7] else #[10,1,21,28])) else (if i.val < 14 then (if i.val < 13 then #[13,22,7,19] else #[14,23,9,24]) else (if i.val < 15 then #[15,20,31,17] else #[12,21,1,26])))) else (if i.val < 24 then (if i.val < 20 then (if i.val < 18 then (if i.val < 17 then #[19,26,28,21] else #[16,27,2,14]) else (if i.val < 19 then #[17,24,4,23] else #[18,25,10,12])) else (if i.val < 22 then (if i.val < 21 then #[21,14,5,27] else #[22,15,11,16]) else (if i.val < 23 then #[23,12,29,25] else #[20,13,3,18]))) else (if i.val < 28 then (if i.val < 26 then (if i.val < 25 then #[27,18,30,13] else #[24,19,0,22]) else (if i.val < 27 then #[25,16,6,15] else #[26,17,8,20])) else (if i.val < 30 then (if i.val < 29 then #[29,6,16,11] else #[30,7,22,0]) else (if i.val < 31 then #[31,4,24,9] else #[28,5,14,2]))))) : Array (Fin 32))[j.val]!
private def rank (i : Fin 32) : ℕ := (if i.val < 16 then (if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 17 else 13) else (if i.val < 3 then 4 else 29)) else (if i.val < 6 then (if i.val < 5 then 24 else 2) else (if i.val < 7 then 6 else 15))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 10 else 26) else (if i.val < 11 then 21 else 8)) else (if i.val < 14 then (if i.val < 13 then 23 else 31) else (if i.val < 15 then 3 else 11)))) else (if i.val < 24 then (if i.val < 20 then (if i.val < 18 then (if i.val < 17 then 7 else 12) else (if i.val < 19 then 30 else 19)) else (if i.val < 22 then (if i.val < 21 then 9 else 20) else (if i.val < 23 then 16 else 27))) else (if i.val < 28 then (if i.val < 26 then (if i.val < 25 then 25 else 28) else (if i.val < 27 then 18 else 22)) else (if i.val < 30 then (if i.val < 29 then 1 else 5) else (if i.val < 31 then 14 else 0)))))
private def parents (i : Fin 32) : Fin 32 := ((if i.val < 16 then (if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 29 else 2) else (if i.val < 3 then 31 else 0)) else (if i.val < 6 then (if i.val < 5 then 30 else 31) else (if i.val < 7 then 28 else 29))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 5 else 30) else (if i.val < 11 then 11 else 28)) else (if i.val < 14 then (if i.val < 13 then 15 else 12) else (if i.val < 15 then 31 else 14)))) else (if i.val < 24 then (if i.val < 20 then (if i.val < 18 then (if i.val < 17 then 28 else 14) else (if i.val < 19 then 19 else 16)) else (if i.val < 22 then (if i.val < 21 then 5 else 16) else (if i.val < 23 then 29 else 22))) else (if i.val < 28 then (if i.val < 26 then (if i.val < 25 then 30 else 22) else (if i.val < 27 then 6 else 20)) else (if i.val < 30 then (if i.val < 29 then 31 else 28) else (if i.val < 31 then 29 else 31))))) : Fin 32)
private def letters (i : Fin 32) : Fin 4 := ((if i.val < 16 then (if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 3 else 0) else (if i.val < 3 then 3 else 0)) else (if i.val < 6 then (if i.val < 5 then 1 else 1) else (if i.val < 7 then 1 else 1))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 3 else 3) else (if i.val < 11 then 0 else 3)) else (if i.val < 14 then (if i.val < 13 then 0 else 0) else (if i.val < 15 then 2 else 0)))) else (if i.val < 24 then (if i.val < 20 then (if i.val < 18 then (if i.val < 17 then 2 else 3) else (if i.val < 19 then 0 else 0)) else (if i.val < 22 then (if i.val < 21 then 2 else 3) else (if i.val < 23 then 2 else 0))) else (if i.val < 28 then (if i.val < 26 then (if i.val < 25 then 2 else 3) else (if i.val < 27 then 2 else 3)) else (if i.val < 30 then (if i.val < 29 then 0 else 0) else (if i.val < 31 then 0 else 0))))) : Fin 4)

def normalCertificate : EncodedCayleyCertificate (binaryNormalRowEncoding normalGenerators) 32 where
  rows := rows
  identity := 31
  identity_eq := by decide +kernel
  next := next
  next_eq := (Fin.addCases (m := 16) (n := 16) (by decide +kernel) (by decide +kernel))
  rank := rank
  parent i _ := parents i
  letter i hi := letters i
  parent_lt := (Fin.addCases (m := 16) (n := 16) (by decide +kernel) (by decide +kernel))
  parent_next := (Fin.addCases (m := 16) (n := 16) (by decide +kernel) (by decide +kernel))

theorem normalRows_injective : Function.Injective normalCertificate.rows := by decide +kernel

theorem kernel_card : Nat.card kernel=32 := normalCertificate.card_closure normalRows_injective

theorem row_mem (i : Fin 32) : (⟨rows i⟩ : Source)∈kernel :=
  binaryNormalRow_mem normalCertificate i

private def posWitness (i : Fin 4) (j : Fin 4) : Fin 32 := ((if i.val < 2 then (if i.val < 1 then #[6,5,14,2] else #[28,5,14,2]) else (if i.val < 3 then #[1,5,14,2] else #[28,5,17,8])) : Array (Fin 32))[j.val]!
private def negWitness (i : Fin 4) (j : Fin 4) : Fin 32 := ((if i.val < 2 then (if i.val < 1 then #[6,5,14,2] else #[28,5,14,2]) else (if i.val < 3 then #[1,5,14,2] else #[28,5,27,8])) : Array (Fin 32))[j.val]!
private theorem pos_checked : ∀ i j, generators i*normalGenerators j*(generators i)⁻¹=
    (⟨rows (posWitness i j)⟩ : Source) := by decide +kernel
private theorem neg_checked : ∀ i j, (generators i)⁻¹*normalGenerators j*generators i=
    (⟨rows (negWitness i j)⟩ : Source) := by decide +kernel

instance normal : kernel.Normal := binaryNormal_of_generator_conjugates generators generators_full
  normalGenerators (fun i j => (pos_checked i j) ▸ row_mem (posWitness i j))
  (fun i j => (neg_checked i j) ▸ row_mem (negWitness i j))

private def representatives (i : Fin 1) : Source := ⟨(31 : Fin 32)⟩
private def quotientNext (i : Fin 1) (j : Fin 4) : Fin 1 := (#[0,0,0,0] : Array (Fin 1))[j.val]!
private def quotientPrev (i : Fin 1) (j : Fin 4) : Fin 1 := (#[0,0,0,0] : Array (Fin 1))[j.val]!
private def quotientParents (i : Fin 1) : Fin 1 := (0 : Fin 1)
private def quotientLetters (i : Fin 1) : Fin 4 := (0 : Fin 4)
private def stepWitness (i : Fin 1) (j : Fin 4) : Fin 32 := (#[2,5,14,30] : Array (Fin 32))[j.val]!
private theorem quotientStep_checked : ∀ i j,
    representatives (quotientNext i j)/(representatives i*generators j)=
      (⟨rows (stepWitness i j)⟩ : Source) := (by decide +kernel)

def cosets : BinaryNormalCosetCertificate generators kernel 1 where
  representatives := representatives
  identity := 0
  identity_mem := by
    have he : representatives 0=(⟨rows 31⟩ : Source) := by decide +kernel
    exact he ▸ row_mem 31
  next := quotientNext
  step_mem := fun i j => (quotientStep_checked i j) ▸ row_mem (stepWitness i j)
  rank i := i.val
  parent i _ := quotientParents i
  letter i _ := quotientLetters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

@[reducible] def state : BinaryNormalState generators where
  kernel := kernel
  normal := normal
  generatorCount := 4
  normalGenerators := normalGenerators
  generated := rfl
  quotientCount := 1
  cardinal := by rw [kernel_card,source_card]
  cosets := cosets
  prev := quotientPrev
  prev_next := (by decide +kernel)

end N11

@[reducible] def states (i : Fin 12) : BinaryNormalState generators :=
  (if i.val < 6 then (if i.val < 3 then (if i.val < 1 then N0.state else (if i.val < 2 then N1.state else N2.state)) else (if i.val < 4 then N3.state else (if i.val < 5 then N4.state else N5.state))) else (if i.val < 9 then (if i.val < 7 then N6.state else (if i.val < 8 then N7.state else N8.state)) else (if i.val < 10 then N9.state else (if i.val < 11 then N10.state else N11.state))))

end SymmetricSubgroupAsymptotics.BinaryNormal8T19
