import SymmetricSubgroupAsymptotics.BinaryNormalGeneratorChecks
import SymmetricSubgroupAsymptotics.BinaryMenuCayley8T20

/-! Exact original normal states and quotient rows for 8T20.
Generated by export_lean_normal_registry.py; all finite facts are checked
in Lean's kernel. This file certifies normal-state coverage, not the later
pair/character/transport acceptance of those states. -/

set_option autoImplicit false
set_option maxRecDepth 100000
set_option maxHeartbeats 0
set_option linter.unusedVariables false
noncomputable section
namespace SymmetricSubgroupAsymptotics.BinaryNormal8T20

abbrev Source := FiniteGroupRow 32
local instance : Group Source := BinaryMenuCayley8T20.group

def generators (j : Fin 2) : Source :=
  ⟨BinaryMenuCayley8T20.certificate.next BinaryMenuCayley8T20.certificate.identity j⟩

theorem generators_full : Subgroup.closure (Set.range generators)=⊤ := by
  apply binaryNormal_full_generators_of_equiv BinaryMenuCayley8T20.generators
    generators BinaryMenuCayley8T20.originalEquiv
  intro j
  change BinaryMenuCayley8T20.certificate.toCayley.elements
    (BinaryMenuCayley8T20.certificate.toCayley.next
      BinaryMenuCayley8T20.certificate.toCayley.identity j)=_
  rw [FiniteCayleyCertificate.next_eq,FiniteCayleyCertificate.identity_eq,one_mul]

theorem source_card : Nat.card Source=32 := by
  rw [Nat.card_eq_fintype_card]
  rfl

namespace N0
def normalGenerators (j : Fin 0) : Source := Fin.elim0 j
def kernel : Subgroup Source := Subgroup.closure (Set.range normalGenerators)
private def rows (i : Fin 1) : Fin 32 := (31 : Fin 32)
private def next (i : Fin 1) (j : Fin 0) : Fin 1 := Fin.elim0 j
private def rank (i : Fin 1) : ℕ := 0
private def parents (i : Fin 1) : Fin 1 := (0 : Fin 1)

def normalCertificate : EncodedCayleyCertificate (binaryNormalRowEncoding normalGenerators) 1 where
  rows := rows
  identity := 0
  identity_eq := by decide +kernel
  next := next
  next_eq := (by decide +kernel)
  rank := rank
  parent i _ := parents i
  letter i hi := False.elim (hi (Subsingleton.elim i (0 : Fin 1)))
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

theorem normalRows_injective : Function.Injective normalCertificate.rows := by decide +kernel

theorem kernel_card : Nat.card kernel=1 := normalCertificate.card_closure normalRows_injective

theorem row_mem (i : Fin 1) : (⟨rows i⟩ : Source)∈kernel :=
  binaryNormalRow_mem normalCertificate i

instance normal : kernel.Normal := binaryNormal_of_generator_conjugates generators generators_full
  normalGenerators (fun _ j => Fin.elim0 j) (fun _ j => Fin.elim0 j)

private def representatives (i : Fin 32) : Source := ⟨((if i.val < 16 then (if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 31 else 28) else (if i.val < 3 then 1 else 0)) else (if i.val < 6 then (if i.val < 5 then 2 else 6) else (if i.val < 7 then 3 else 22))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 7 else 5) else (if i.val < 11 then 11 else 23)) else (if i.val < 14 then (if i.val < 13 then 21 else 25) else (if i.val < 15 then 4 else 27)))) else (if i.val < 24 then (if i.val < 20 then (if i.val < 18 then (if i.val < 17 then 10 else 8) else (if i.val < 19 then 20 else 9)) else (if i.val < 22 then (if i.val < 21 then 24 else 26) else (if i.val < 23 then 13 else 15))) else (if i.val < 28 then (if i.val < 26 then (if i.val < 25 then 30 else 14) else (if i.val < 27 then 12 else 29)) else (if i.val < 30 then (if i.val < 29 then 19 else 17) else (if i.val < 31 then 18 else 16))))) : Fin 32)⟩
private def quotientNext (i : Fin 32) (j : Fin 2) : Fin 32 := ((if i.val < 16 then (if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[1,2] else #[0,3]) else (if i.val < 3 then #[4,5] else #[6,7])) else (if i.val < 6 then (if i.val < 5 then #[2,8] else #[9,10]) else (if i.val < 7 then #[3,11] else #[12,13]))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then #[14,15] else #[5,16]) else (if i.val < 11 then #[17,0] else #[18,19])) else (if i.val < 14 then (if i.val < 13 then #[7,20] else #[21,1]) else (if i.val < 15 then #[8,21] else #[20,22])))) else (if i.val < 24 then (if i.val < 20 then (if i.val < 18 then (if i.val < 17 then #[19,23] else #[10,24]) else (if i.val < 19 then #[11,17] else #[16,25])) else (if i.val < 22 then (if i.val < 21 then #[15,26] else #[13,27]) else (if i.val < 23 then #[25,4] else #[26,28]))) else (if i.val < 28 then (if i.val < 26 then (if i.val < 25 then #[27,29] else #[22,6]) else (if i.val < 27 then #[23,30] else #[24,31])) else (if i.val < 30 then (if i.val < 29 then #[31,9] else #[30,18]) else (if i.val < 31 then #[29,12] else #[28,14]))))) : Array (Fin 32))[j.val]!
private def quotientPrev (i : Fin 32) (j : Fin 2) : Fin 32 := ((if i.val < 16 then (if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[1,10] else #[0,13]) else (if i.val < 3 then #[4,0] else #[6,1])) else (if i.val < 6 then (if i.val < 5 then #[2,22] else #[9,2]) else (if i.val < 7 then #[3,25] else #[12,3]))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then #[14,4] else #[5,28]) else (if i.val < 11 then #[17,5] else #[18,6])) else (if i.val < 14 then (if i.val < 13 then #[7,30] else #[21,7]) else (if i.val < 15 then #[8,31] else #[20,8])))) else (if i.val < 24 then (if i.val < 20 then (if i.val < 18 then (if i.val < 17 then #[19,9] else #[10,18]) else (if i.val < 19 then #[11,29] else #[16,11])) else (if i.val < 22 then (if i.val < 21 then #[15,12] else #[13,14]) else (if i.val < 23 then #[25,15] else #[26,16]))) else (if i.val < 28 then (if i.val < 26 then (if i.val < 25 then #[27,17] else #[22,19]) else (if i.val < 27 then #[23,20] else #[24,21])) else (if i.val < 30 then (if i.val < 29 then #[31,23] else #[30,24]) else (if i.val < 31 then #[29,26] else #[28,27]))))) : Array (Fin 32))[j.val]!
private def quotientParents (i : Fin 32) : Fin 32 := ((if i.val < 16 then (if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 0 else 1)) else (if i.val < 6 then (if i.val < 5 then 2 else 2) else (if i.val < 7 then 3 else 3))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 4 else 5) else (if i.val < 11 then 5 else 6)) else (if i.val < 14 then (if i.val < 13 then 7 else 7) else (if i.val < 15 then 8 else 8)))) else (if i.val < 24 then (if i.val < 20 then (if i.val < 18 then (if i.val < 17 then 9 else 10) else (if i.val < 19 then 11 else 11)) else (if i.val < 22 then (if i.val < 21 then 12 else 13) else (if i.val < 23 then 15 else 16))) else (if i.val < 28 then (if i.val < 26 then (if i.val < 25 then 17 else 19) else (if i.val < 27 then 20 else 21)) else (if i.val < 30 then (if i.val < 29 then 23 else 24) else (if i.val < 31 then 26 else 27))))) : Fin 32)
private def quotientLetters (i : Fin 32) : Fin 2 := ((if i.val < 16 then (if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 1 else 1)) else (if i.val < 6 then (if i.val < 5 then 0 else 1) else (if i.val < 7 then 0 else 1))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 1 else 0) else (if i.val < 11 then 1 else 1)) else (if i.val < 14 then (if i.val < 13 then 0 else 1) else (if i.val < 15 then 0 else 1)))) else (if i.val < 24 then (if i.val < 20 then (if i.val < 18 then (if i.val < 17 then 1 else 0) else (if i.val < 19 then 0 else 1)) else (if i.val < 22 then (if i.val < 21 then 1 else 0) else (if i.val < 23 then 1 else 1))) else (if i.val < 28 then (if i.val < 26 then (if i.val < 25 then 1 else 1) else (if i.val < 27 then 1 else 1)) else (if i.val < 30 then (if i.val < 29 then 1 else 1) else (if i.val < 31 then 1 else 1))))) : Fin 2)
private def stepWitness (i : Fin 32) (j : Fin 2) : Fin 1 := ((if i.val < 16 then (if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[0,0] else #[0,0]) else (if i.val < 3 then #[0,0] else #[0,0])) else (if i.val < 6 then (if i.val < 5 then #[0,0] else #[0,0]) else (if i.val < 7 then #[0,0] else #[0,0]))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then #[0,0] else #[0,0]) else (if i.val < 11 then #[0,0] else #[0,0])) else (if i.val < 14 then (if i.val < 13 then #[0,0] else #[0,0]) else (if i.val < 15 then #[0,0] else #[0,0])))) else (if i.val < 24 then (if i.val < 20 then (if i.val < 18 then (if i.val < 17 then #[0,0] else #[0,0]) else (if i.val < 19 then #[0,0] else #[0,0])) else (if i.val < 22 then (if i.val < 21 then #[0,0] else #[0,0]) else (if i.val < 23 then #[0,0] else #[0,0]))) else (if i.val < 28 then (if i.val < 26 then (if i.val < 25 then #[0,0] else #[0,0]) else (if i.val < 27 then #[0,0] else #[0,0])) else (if i.val < 30 then (if i.val < 29 then #[0,0] else #[0,0]) else (if i.val < 31 then #[0,0] else #[0,0]))))) : Array (Fin 1))[j.val]!
private theorem quotientStep_checked : ∀ i j,
    representatives (quotientNext i j)/(representatives i*generators j)=
      (⟨rows (stepWitness i j)⟩ : Source) := (Fin.addCases (m := 16) (n := 16) (by decide +kernel) (by decide +kernel))

def cosets : BinaryNormalCosetCertificate generators kernel 32 where
  representatives := representatives
  identity := 0
  identity_mem := by
    have he : representatives 0=(⟨rows 0⟩ : Source) := by decide +kernel
    exact he ▸ row_mem 0
  next := quotientNext
  step_mem := fun i j => (quotientStep_checked i j) ▸ row_mem (stepWitness i j)
  rank i := i.val
  parent i _ := quotientParents i
  letter i _ := quotientLetters i
  parent_lt := (Fin.addCases (m := 16) (n := 16) (by decide +kernel) (by decide +kernel))
  parent_next := (Fin.addCases (m := 16) (n := 16) (by decide +kernel) (by decide +kernel))

@[reducible] def state : BinaryNormalState generators where
  kernel := kernel
  normal := normal
  generatorCount := 0
  normalGenerators := normalGenerators
  generated := rfl
  quotientCount := 32
  cardinal := by rw [kernel_card,source_card]
  cosets := cosets
  prev := quotientPrev
  prev_next := (Fin.addCases (m := 16) (n := 16) (by decide +kernel) (by decide +kernel))

end N0

namespace N1
def normalGenerators (j : Fin 1) : Source := ⟨(12 : Fin 32)⟩
def kernel : Subgroup Source := Subgroup.closure (Set.range normalGenerators)
private def rows (i : Fin 2) : Fin 32 := ((if i.val < 1 then 12 else 31) : Fin 32)
private def next (i : Fin 2) (j : Fin 1) : Fin 2 := ((if i.val < 1 then #[1] else #[0]) : Array (Fin 2))[j.val]!
private def rank (i : Fin 2) : ℕ := (if i.val < 1 then 1 else 0)
private def parents (i : Fin 2) : Fin 2 := ((if i.val < 1 then 1 else 1) : Fin 2)
private def letters (i : Fin 2) : Fin 1 := ((if i.val < 1 then 0 else 0) : Fin 1)

def normalCertificate : EncodedCayleyCertificate (binaryNormalRowEncoding normalGenerators) 2 where
  rows := rows
  identity := 1
  identity_eq := by decide +kernel
  next := next
  next_eq := (by decide +kernel)
  rank := rank
  parent i _ := parents i
  letter i hi := letters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

theorem normalRows_injective : Function.Injective normalCertificate.rows := by decide +kernel

theorem kernel_card : Nat.card kernel=2 := normalCertificate.card_closure normalRows_injective

theorem row_mem (i : Fin 2) : (⟨rows i⟩ : Source)∈kernel :=
  binaryNormalRow_mem normalCertificate i

private def posWitness (i : Fin 2) (j : Fin 1) : Fin 2 := ((if i.val < 1 then #[0] else #[0]) : Array (Fin 2))[j.val]!
private def negWitness (i : Fin 2) (j : Fin 1) : Fin 2 := ((if i.val < 1 then #[0] else #[0]) : Array (Fin 2))[j.val]!
private theorem pos_checked : ∀ i j, generators i*normalGenerators j*(generators i)⁻¹=
    (⟨rows (posWitness i j)⟩ : Source) := by decide +kernel
private theorem neg_checked : ∀ i j, (generators i)⁻¹*normalGenerators j*generators i=
    (⟨rows (negWitness i j)⟩ : Source) := by decide +kernel

instance normal : kernel.Normal := binaryNormal_of_generator_conjugates generators generators_full
  normalGenerators (fun i j => (pos_checked i j) ▸ row_mem (posWitness i j))
  (fun i j => (neg_checked i j) ▸ row_mem (negWitness i j))

private def representatives (i : Fin 16) : Source := ⟨((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 31 else 28) else (if i.val < 3 then 1 else 0)) else (if i.val < 6 then (if i.val < 5 then 2 else 6) else (if i.val < 7 then 3 else 22))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 7 else 11) else (if i.val < 11 then 23 else 25)) else (if i.val < 14 then (if i.val < 13 then 27 else 9) else (if i.val < 15 then 13 else 14)))) : Fin 32)⟩
private def quotientNext (i : Fin 16) (j : Fin 2) : Fin 16 := ((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[1,2] else #[0,3]) else (if i.val < 3 then #[4,5] else #[6,7])) else (if i.val < 6 then (if i.val < 5 then #[2,8] else #[7,9]) else (if i.val < 7 then #[3,10] else #[5,11]))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then #[10,12] else #[12,0]) else (if i.val < 11 then #[8,13] else #[13,1])) else (if i.val < 14 then (if i.val < 13 then #[9,14] else #[11,15]) else (if i.val < 15 then #[15,4] else #[14,6])))) : Array (Fin 16))[j.val]!
private def quotientPrev (i : Fin 16) (j : Fin 2) : Fin 16 := ((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[1,9] else #[0,11]) else (if i.val < 3 then #[4,0] else #[6,1])) else (if i.val < 6 then (if i.val < 5 then #[2,14] else #[7,2]) else (if i.val < 7 then #[3,15] else #[5,3]))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then #[10,4] else #[12,5]) else (if i.val < 11 then #[8,6] else #[13,7])) else (if i.val < 14 then (if i.val < 13 then #[9,8] else #[11,10]) else (if i.val < 15 then #[15,12] else #[14,13])))) : Array (Fin 16))[j.val]!
private def quotientParents (i : Fin 16) : Fin 16 := ((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 0 else 1)) else (if i.val < 6 then (if i.val < 5 then 2 else 2) else (if i.val < 7 then 3 else 3))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 4 else 5) else (if i.val < 11 then 6 else 7)) else (if i.val < 14 then (if i.val < 13 then 8 else 10) else (if i.val < 15 then 12 else 13)))) : Fin 16)
private def quotientLetters (i : Fin 16) : Fin 2 := ((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 1 else 1)) else (if i.val < 6 then (if i.val < 5 then 0 else 1) else (if i.val < 7 then 0 else 1))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 1 else 1) else (if i.val < 11 then 1 else 1)) else (if i.val < 14 then (if i.val < 13 then 1 else 1) else (if i.val < 15 then 1 else 1)))) : Fin 2)
private def stepWitness (i : Fin 16) (j : Fin 2) : Fin 2 := ((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[1,1] else #[1,1]) else (if i.val < 3 then #[1,1] else #[1,1])) else (if i.val < 6 then (if i.val < 5 then #[1,1] else #[0,1]) else (if i.val < 7 then #[1,1] else #[0,1]))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then #[0,1] else #[0,1]) else (if i.val < 11 then #[0,1] else #[0,1])) else (if i.val < 14 then (if i.val < 13 then #[0,1] else #[0,1]) else (if i.val < 15 then #[1,1] else #[1,1])))) : Array (Fin 2))[j.val]!
private theorem quotientStep_checked : ∀ i j,
    representatives (quotientNext i j)/(representatives i*generators j)=
      (⟨rows (stepWitness i j)⟩ : Source) := (by decide +kernel)

def cosets : BinaryNormalCosetCertificate generators kernel 16 where
  representatives := representatives
  identity := 0
  identity_mem := by
    have he : representatives 0=(⟨rows 1⟩ : Source) := by decide +kernel
    exact he ▸ row_mem 1
  next := quotientNext
  step_mem := fun i j => (quotientStep_checked i j) ▸ row_mem (stepWitness i j)
  rank i := i.val
  parent i _ := quotientParents i
  letter i _ := quotientLetters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

@[reducible] def state : BinaryNormalState generators where
  kernel := kernel
  normal := normal
  generatorCount := 1
  normalGenerators := normalGenerators
  generated := rfl
  quotientCount := 16
  cardinal := by rw [kernel_card,source_card]
  cosets := cosets
  prev := quotientPrev
  prev_next := (by decide +kernel)

end N1

namespace N2
def normalGenerators (j : Fin 2) : Source := ⟨((if j.val < 1 then 23 else 12) : Fin 32)⟩
def kernel : Subgroup Source := Subgroup.closure (Set.range normalGenerators)
private def rows (i : Fin 4) : Fin 32 := ((if i.val < 2 then (if i.val < 1 then 4 else 12) else (if i.val < 3 then 23 else 31)) : Fin 32)
private def next (i : Fin 4) (j : Fin 2) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[1,2] else #[0,3]) else (if i.val < 3 then #[3,0] else #[2,1])) : Array (Fin 4))[j.val]!
private def rank (i : Fin 4) : ℕ := (if i.val < 2 then (if i.val < 1 then 3 else 2) else (if i.val < 3 then 1 else 0))
private def parents (i : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then 2 else 3) else (if i.val < 3 then 3 else 3)) : Fin 4)
private def letters (i : Fin 4) : Fin 2 := ((if i.val < 2 then (if i.val < 1 then 1 else 1) else (if i.val < 3 then 0 else 0)) : Fin 2)

def normalCertificate : EncodedCayleyCertificate (binaryNormalRowEncoding normalGenerators) 4 where
  rows := rows
  identity := 3
  identity_eq := by decide +kernel
  next := next
  next_eq := (by decide +kernel)
  rank := rank
  parent i _ := parents i
  letter i hi := letters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

theorem normalRows_injective : Function.Injective normalCertificate.rows := by decide +kernel

theorem kernel_card : Nat.card kernel=4 := normalCertificate.card_closure normalRows_injective

theorem row_mem (i : Fin 4) : (⟨rows i⟩ : Source)∈kernel :=
  binaryNormalRow_mem normalCertificate i

private def posWitness (i : Fin 2) (j : Fin 2) : Fin 4 := ((if i.val < 1 then #[0,1] else #[0,1]) : Array (Fin 4))[j.val]!
private def negWitness (i : Fin 2) (j : Fin 2) : Fin 4 := ((if i.val < 1 then #[0,1] else #[0,1]) : Array (Fin 4))[j.val]!
private theorem pos_checked : ∀ i j, generators i*normalGenerators j*(generators i)⁻¹=
    (⟨rows (posWitness i j)⟩ : Source) := by decide +kernel
private theorem neg_checked : ∀ i j, (generators i)⁻¹*normalGenerators j*generators i=
    (⟨rows (negWitness i j)⟩ : Source) := by decide +kernel

instance normal : kernel.Normal := binaryNormal_of_generator_conjugates generators generators_full
  normalGenerators (fun i j => (pos_checked i j) ▸ row_mem (posWitness i j))
  (fun i j => (neg_checked i j) ▸ row_mem (negWitness i j))

private def representatives (i : Fin 8) : Source := ⟨((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 31 else 28) else (if i.val < 3 then 1 else 0)) else (if i.val < 6 then (if i.val < 5 then 2 else 6) else (if i.val < 7 then 3 else 22))) : Fin 32)⟩
private def quotientNext (i : Fin 8) (j : Fin 2) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[1,2] else #[0,3]) else (if i.val < 3 then #[4,5] else #[6,7])) else (if i.val < 6 then (if i.val < 5 then #[2,1] else #[7,6]) else (if i.val < 7 then #[3,0] else #[5,4]))) : Array (Fin 8))[j.val]!
private def quotientPrev (i : Fin 8) (j : Fin 2) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[1,6] else #[0,4]) else (if i.val < 3 then #[4,0] else #[6,1])) else (if i.val < 6 then (if i.val < 5 then #[2,7] else #[7,2]) else (if i.val < 7 then #[3,5] else #[5,3]))) : Array (Fin 8))[j.val]!
private def quotientParents (i : Fin 8) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 0 else 1)) else (if i.val < 6 then (if i.val < 5 then 2 else 2) else (if i.val < 7 then 3 else 3))) : Fin 8)
private def quotientLetters (i : Fin 8) : Fin 2 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 1 else 1)) else (if i.val < 6 then (if i.val < 5 then 0 else 1) else (if i.val < 7 then 0 else 1))) : Fin 2)
private def stepWitness (i : Fin 8) (j : Fin 2) : Fin 4 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[3,3] else #[3,3]) else (if i.val < 3 then #[3,3] else #[3,3])) else (if i.val < 6 then (if i.val < 5 then #[3,0] else #[1,2]) else (if i.val < 7 then #[3,2] else #[1,0]))) : Array (Fin 4))[j.val]!
private theorem quotientStep_checked : ∀ i j,
    representatives (quotientNext i j)/(representatives i*generators j)=
      (⟨rows (stepWitness i j)⟩ : Source) := (by decide +kernel)

def cosets : BinaryNormalCosetCertificate generators kernel 8 where
  representatives := representatives
  identity := 0
  identity_mem := by
    have he : representatives 0=(⟨rows 3⟩ : Source) := by decide +kernel
    exact he ▸ row_mem 3
  next := quotientNext
  step_mem := fun i j => (quotientStep_checked i j) ▸ row_mem (stepWitness i j)
  rank i := i.val
  parent i _ := quotientParents i
  letter i _ := quotientLetters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

@[reducible] def state : BinaryNormalState generators where
  kernel := kernel
  normal := normal
  generatorCount := 2
  normalGenerators := normalGenerators
  generated := rfl
  quotientCount := 8
  cardinal := by rw [kernel_card,source_card]
  cosets := cosets
  prev := quotientPrev
  prev_next := (by decide +kernel)

end N2

namespace N3
def normalGenerators (j : Fin 2) : Source := ⟨((if j.val < 1 then 6 else 12) : Fin 32)⟩
def kernel : Subgroup Source := Subgroup.closure (Set.range normalGenerators)
private def rows (i : Fin 4) : Fin 32 := ((if i.val < 2 then (if i.val < 1 then 6 else 12) else (if i.val < 3 then 21 else 31)) : Fin 32)
private def next (i : Fin 4) (j : Fin 2) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[3,2] else #[2,3]) else (if i.val < 3 then #[1,0] else #[0,1])) : Array (Fin 4))[j.val]!
private def rank (i : Fin 4) : ℕ := (if i.val < 2 then (if i.val < 1 then 1 else 2) else (if i.val < 3 then 3 else 0))
private def parents (i : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then 3 else 3) else (if i.val < 3 then 0 else 3)) : Fin 4)
private def letters (i : Fin 4) : Fin 2 := ((if i.val < 2 then (if i.val < 1 then 0 else 1) else (if i.val < 3 then 1 else 0)) : Fin 2)

def normalCertificate : EncodedCayleyCertificate (binaryNormalRowEncoding normalGenerators) 4 where
  rows := rows
  identity := 3
  identity_eq := by decide +kernel
  next := next
  next_eq := (by decide +kernel)
  rank := rank
  parent i _ := parents i
  letter i hi := letters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

theorem normalRows_injective : Function.Injective normalCertificate.rows := by decide +kernel

theorem kernel_card : Nat.card kernel=4 := normalCertificate.card_closure normalRows_injective

theorem row_mem (i : Fin 4) : (⟨rows i⟩ : Source)∈kernel :=
  binaryNormalRow_mem normalCertificate i

private def posWitness (i : Fin 2) (j : Fin 2) : Fin 4 := ((if i.val < 1 then #[2,1] else #[0,1]) : Array (Fin 4))[j.val]!
private def negWitness (i : Fin 2) (j : Fin 2) : Fin 4 := ((if i.val < 1 then #[2,1] else #[0,1]) : Array (Fin 4))[j.val]!
private theorem pos_checked : ∀ i j, generators i*normalGenerators j*(generators i)⁻¹=
    (⟨rows (posWitness i j)⟩ : Source) := by decide +kernel
private theorem neg_checked : ∀ i j, (generators i)⁻¹*normalGenerators j*generators i=
    (⟨rows (negWitness i j)⟩ : Source) := by decide +kernel

instance normal : kernel.Normal := binaryNormal_of_generator_conjugates generators generators_full
  normalGenerators (fun i j => (pos_checked i j) ▸ row_mem (posWitness i j))
  (fun i j => (neg_checked i j) ▸ row_mem (negWitness i j))

private def representatives (i : Fin 8) : Source := ⟨((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 31 else 28) else (if i.val < 3 then 1 else 0)) else (if i.val < 6 then (if i.val < 5 then 2 else 3) else (if i.val < 7 then 7 else 23))) : Fin 32)⟩
private def quotientNext (i : Fin 8) (j : Fin 2) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[1,2] else #[0,3]) else (if i.val < 3 then #[4,0] else #[5,1])) else (if i.val < 6 then (if i.val < 5 then #[2,6] else #[3,7]) else (if i.val < 7 then #[7,4] else #[6,5]))) : Array (Fin 8))[j.val]!
private def quotientPrev (i : Fin 8) (j : Fin 2) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[1,2] else #[0,3]) else (if i.val < 3 then #[4,0] else #[5,1])) else (if i.val < 6 then (if i.val < 5 then #[2,6] else #[3,7]) else (if i.val < 7 then #[7,4] else #[6,5]))) : Array (Fin 8))[j.val]!
private def quotientParents (i : Fin 8) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 0 else 1)) else (if i.val < 6 then (if i.val < 5 then 2 else 3) else (if i.val < 7 then 4 else 5))) : Fin 8)
private def quotientLetters (i : Fin 8) : Fin 2 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 1 else 1)) else (if i.val < 6 then (if i.val < 5 then 0 else 0) else (if i.val < 7 then 1 else 1))) : Fin 2)
private def stepWitness (i : Fin 8) (j : Fin 2) : Fin 4 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[3,3] else #[3,3]) else (if i.val < 3 then #[3,0] else #[3,2])) else (if i.val < 6 then (if i.val < 5 then #[3,3] else #[3,3]) else (if i.val < 7 then #[1,2] else #[1,0]))) : Array (Fin 4))[j.val]!
private theorem quotientStep_checked : ∀ i j,
    representatives (quotientNext i j)/(representatives i*generators j)=
      (⟨rows (stepWitness i j)⟩ : Source) := (by decide +kernel)

def cosets : BinaryNormalCosetCertificate generators kernel 8 where
  representatives := representatives
  identity := 0
  identity_mem := by
    have he : representatives 0=(⟨rows 3⟩ : Source) := by decide +kernel
    exact he ▸ row_mem 3
  next := quotientNext
  step_mem := fun i j => (quotientStep_checked i j) ▸ row_mem (stepWitness i j)
  rank i := i.val
  parent i _ := quotientParents i
  letter i _ := quotientLetters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

@[reducible] def state : BinaryNormalState generators where
  kernel := kernel
  normal := normal
  generatorCount := 2
  normalGenerators := normalGenerators
  generated := rfl
  quotientCount := 8
  cardinal := by rw [kernel_card,source_card]
  cosets := cosets
  prev := quotientPrev
  prev_next := (by decide +kernel)

end N3

namespace N4
def normalGenerators (j : Fin 2) : Source := ⟨((if j.val < 1 then 14 else 12) : Fin 32)⟩
def kernel : Subgroup Source := Subgroup.closure (Set.range normalGenerators)
private def rows (i : Fin 4) : Fin 32 := ((if i.val < 2 then (if i.val < 1 then 12 else 14) else (if i.val < 3 then 29 else 31)) : Fin 32)
private def next (i : Fin 4) (j : Fin 2) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[2,3] else #[3,2]) else (if i.val < 3 then #[0,1] else #[1,0])) : Array (Fin 4))[j.val]!
private def rank (i : Fin 4) : ℕ := (if i.val < 2 then (if i.val < 1 then 2 else 1) else (if i.val < 3 then 3 else 0))
private def parents (i : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then 3 else 3) else (if i.val < 3 then 1 else 3)) : Fin 4)
private def letters (i : Fin 4) : Fin 2 := ((if i.val < 2 then (if i.val < 1 then 1 else 0) else (if i.val < 3 then 1 else 0)) : Fin 2)

def normalCertificate : EncodedCayleyCertificate (binaryNormalRowEncoding normalGenerators) 4 where
  rows := rows
  identity := 3
  identity_eq := by decide +kernel
  next := next
  next_eq := (by decide +kernel)
  rank := rank
  parent i _ := parents i
  letter i hi := letters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

theorem normalRows_injective : Function.Injective normalCertificate.rows := by decide +kernel

theorem kernel_card : Nat.card kernel=4 := normalCertificate.card_closure normalRows_injective

theorem row_mem (i : Fin 4) : (⟨rows i⟩ : Source)∈kernel :=
  binaryNormalRow_mem normalCertificate i

private def posWitness (i : Fin 2) (j : Fin 2) : Fin 4 := ((if i.val < 1 then #[1,0] else #[2,0]) : Array (Fin 4))[j.val]!
private def negWitness (i : Fin 2) (j : Fin 2) : Fin 4 := ((if i.val < 1 then #[1,0] else #[2,0]) : Array (Fin 4))[j.val]!
private theorem pos_checked : ∀ i j, generators i*normalGenerators j*(generators i)⁻¹=
    (⟨rows (posWitness i j)⟩ : Source) := by decide +kernel
private theorem neg_checked : ∀ i j, (generators i)⁻¹*normalGenerators j*generators i=
    (⟨rows (negWitness i j)⟩ : Source) := by decide +kernel

instance normal : kernel.Normal := binaryNormal_of_generator_conjugates generators generators_full
  normalGenerators (fun i j => (pos_checked i j) ▸ row_mem (posWitness i j))
  (fun i j => (neg_checked i j) ▸ row_mem (negWitness i j))

private def representatives (i : Fin 8) : Source := ⟨((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 31 else 28) else (if i.val < 3 then 1 else 0)) else (if i.val < 6 then (if i.val < 5 then 6 else 22) else (if i.val < 7 then 11 else 25))) : Fin 32)⟩
private def quotientNext (i : Fin 8) (j : Fin 2) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[1,2] else #[0,3]) else (if i.val < 3 then #[3,4] else #[2,5])) else (if i.val < 6 then (if i.val < 5 then #[5,6] else #[4,7]) else (if i.val < 7 then #[7,0] else #[6,1]))) : Array (Fin 8))[j.val]!
private def quotientPrev (i : Fin 8) (j : Fin 2) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[1,6] else #[0,7]) else (if i.val < 3 then #[3,0] else #[2,1])) else (if i.val < 6 then (if i.val < 5 then #[5,2] else #[4,3]) else (if i.val < 7 then #[7,4] else #[6,5]))) : Array (Fin 8))[j.val]!
private def quotientParents (i : Fin 8) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 0 else 1)) else (if i.val < 6 then (if i.val < 5 then 2 else 3) else (if i.val < 7 then 4 else 5))) : Fin 8)
private def quotientLetters (i : Fin 8) : Fin 2 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 1 else 1)) else (if i.val < 6 then (if i.val < 5 then 1 else 1) else (if i.val < 7 then 1 else 1))) : Fin 2)
private def stepWitness (i : Fin 8) (j : Fin 2) : Fin 4 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[3,3] else #[3,3]) else (if i.val < 3 then #[1,3] else #[1,3])) else (if i.val < 6 then (if i.val < 5 then #[0,3] else #[0,3]) else (if i.val < 7 then #[2,3] else #[2,3]))) : Array (Fin 4))[j.val]!
private theorem quotientStep_checked : ∀ i j,
    representatives (quotientNext i j)/(representatives i*generators j)=
      (⟨rows (stepWitness i j)⟩ : Source) := (by decide +kernel)

def cosets : BinaryNormalCosetCertificate generators kernel 8 where
  representatives := representatives
  identity := 0
  identity_mem := by
    have he : representatives 0=(⟨rows 3⟩ : Source) := by decide +kernel
    exact he ▸ row_mem 3
  next := quotientNext
  step_mem := fun i j => (quotientStep_checked i j) ▸ row_mem (stepWitness i j)
  rank i := i.val
  parent i _ := quotientParents i
  letter i _ := quotientLetters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

@[reducible] def state : BinaryNormalState generators where
  kernel := kernel
  normal := normal
  generatorCount := 2
  normalGenerators := normalGenerators
  generated := rfl
  quotientCount := 8
  cardinal := by rw [kernel_card,source_card]
  cosets := cosets
  prev := quotientPrev
  prev_next := (by decide +kernel)

end N4

namespace N5
def normalGenerators (j : Fin 2) : Source := ⟨((if j.val < 1 then 7 else 14) : Fin 32)⟩
def kernel : Subgroup Source := Subgroup.closure (Set.range normalGenerators)
private def rows (i : Fin 8) : Fin 32 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 5 else 7) else (if i.val < 3 then 12 else 14)) else (if i.val < 6 then (if i.val < 5 then 20 else 22) else (if i.val < 7 then 29 else 31))) : Fin 32)
private def next (i : Fin 8) (j : Fin 2) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[3,4] else #[2,5]) else (if i.val < 3 then #[4,6] else #[5,7])) else (if i.val < 6 then (if i.val < 5 then #[7,0] else #[6,1]) else (if i.val < 7 then #[0,2] else #[1,3]))) : Array (Fin 8))[j.val]!
private def rank (i : Fin 8) : ℕ := (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 7 else 1) else (if i.val < 3 then 3 else 2)) else (if i.val < 6 then (if i.val < 5 then 5 else 4) else (if i.val < 7 then 6 else 0)))
private def parents (i : Fin 8) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 4 else 7) else (if i.val < 3 then 1 else 7)) else (if i.val < 6 then (if i.val < 5 then 2 else 1) else (if i.val < 7 then 2 else 7))) : Fin 8)
private def letters (i : Fin 8) : Fin 2 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 1 else 0) else (if i.val < 3 then 0 else 1)) else (if i.val < 6 then (if i.val < 5 then 0 else 1) else (if i.val < 7 then 1 else 0))) : Fin 2)

def normalCertificate : EncodedCayleyCertificate (binaryNormalRowEncoding normalGenerators) 8 where
  rows := rows
  identity := 7
  identity_eq := by decide +kernel
  next := next
  next_eq := (by decide +kernel)
  rank := rank
  parent i _ := parents i
  letter i hi := letters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

theorem normalRows_injective : Function.Injective normalCertificate.rows := by decide +kernel

theorem kernel_card : Nat.card kernel=8 := normalCertificate.card_closure normalRows_injective

theorem row_mem (i : Fin 8) : (⟨rows i⟩ : Source)∈kernel :=
  binaryNormalRow_mem normalCertificate i

private def posWitness (i : Fin 2) (j : Fin 2) : Fin 8 := ((if i.val < 1 then #[4,3] else #[0,6]) : Array (Fin 8))[j.val]!
private def negWitness (i : Fin 2) (j : Fin 2) : Fin 8 := ((if i.val < 1 then #[4,3] else #[5,6]) : Array (Fin 8))[j.val]!
private theorem pos_checked : ∀ i j, generators i*normalGenerators j*(generators i)⁻¹=
    (⟨rows (posWitness i j)⟩ : Source) := by decide +kernel
private theorem neg_checked : ∀ i j, (generators i)⁻¹*normalGenerators j*generators i=
    (⟨rows (negWitness i j)⟩ : Source) := by decide +kernel

instance normal : kernel.Normal := binaryNormal_of_generator_conjugates generators generators_full
  normalGenerators (fun i j => (pos_checked i j) ▸ row_mem (posWitness i j))
  (fun i j => (neg_checked i j) ▸ row_mem (negWitness i j))

private def representatives (i : Fin 4) : Source := ⟨((if i.val < 2 then (if i.val < 1 then 31 else 28) else (if i.val < 3 then 1 else 0)) : Fin 32)⟩
private def quotientNext (i : Fin 4) (j : Fin 2) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[1,2] else #[0,3]) else (if i.val < 3 then #[3,1] else #[2,0])) : Array (Fin 4))[j.val]!
private def quotientPrev (i : Fin 4) (j : Fin 2) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[1,3] else #[0,2]) else (if i.val < 3 then #[3,0] else #[2,1])) : Array (Fin 4))[j.val]!
private def quotientParents (i : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 0 else 1)) : Fin 4)
private def quotientLetters (i : Fin 4) : Fin 2 := ((if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 1 else 1)) : Fin 2)
private def stepWitness (i : Fin 4) (j : Fin 2) : Fin 8 := ((if i.val < 2 then (if i.val < 1 then #[7,7] else #[7,7]) else (if i.val < 3 then #[3,5] else #[3,0])) : Array (Fin 8))[j.val]!
private theorem quotientStep_checked : ∀ i j,
    representatives (quotientNext i j)/(representatives i*generators j)=
      (⟨rows (stepWitness i j)⟩ : Source) := (by decide +kernel)

def cosets : BinaryNormalCosetCertificate generators kernel 4 where
  representatives := representatives
  identity := 0
  identity_mem := by
    have he : representatives 0=(⟨rows 7⟩ : Source) := by decide +kernel
    exact he ▸ row_mem 7
  next := quotientNext
  step_mem := fun i j => (quotientStep_checked i j) ▸ row_mem (stepWitness i j)
  rank i := i.val
  parent i _ := quotientParents i
  letter i _ := quotientLetters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

@[reducible] def state : BinaryNormalState generators where
  kernel := kernel
  normal := normal
  generatorCount := 2
  normalGenerators := normalGenerators
  generated := rfl
  quotientCount := 4
  cardinal := by rw [kernel_card,source_card]
  cosets := cosets
  prev := quotientPrev
  prev_next := (by decide +kernel)

end N5

namespace N6
def normalGenerators (j : Fin 3) : Source := ⟨((if j.val < 1 then 14 else (if j.val < 2 then 6 else 12)) : Fin 32)⟩
def kernel : Subgroup Source := Subgroup.closure (Set.range normalGenerators)
private def rows (i : Fin 8) : Fin 32 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 4 else 6) else (if i.val < 3 then 12 else 14)) else (if i.val < 6 then (if i.val < 5 then 21 else 23) else (if i.val < 7 then 29 else 31))) : Fin 32)
private def next (i : Fin 8) (j : Fin 3) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[4,6,5] else #[5,7,4]) else (if i.val < 3 then #[6,4,7] else #[7,5,6])) else (if i.val < 6 then (if i.val < 5 then #[0,2,1] else #[1,3,0]) else (if i.val < 7 then #[2,0,3] else #[3,1,2]))) : Array (Fin 8))[j.val]!
private def rank (i : Fin 8) : ℕ := (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 7 else 2) else (if i.val < 3 then 3 else 1)) else (if i.val < 6 then (if i.val < 5 then 6 else 4) else (if i.val < 7 then 5 else 0)))
private def parents (i : Fin 8) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 5 else 7) else (if i.val < 3 then 7 else 7)) else (if i.val < 6 then (if i.val < 5 then 1 else 3) else (if i.val < 7 then 3 else 7))) : Fin 8)
private def letters (i : Fin 8) : Fin 3 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 2 else 1) else (if i.val < 3 then 2 else 0)) else (if i.val < 6 then (if i.val < 5 then 2 else 1) else (if i.val < 7 then 2 else 0))) : Fin 3)

def normalCertificate : EncodedCayleyCertificate (binaryNormalRowEncoding normalGenerators) 8 where
  rows := rows
  identity := 7
  identity_eq := by decide +kernel
  next := next
  next_eq := (by decide +kernel)
  rank := rank
  parent i _ := parents i
  letter i hi := letters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

theorem normalRows_injective : Function.Injective normalCertificate.rows := by decide +kernel

theorem kernel_card : Nat.card kernel=8 := normalCertificate.card_closure normalRows_injective

theorem row_mem (i : Fin 8) : (⟨rows i⟩ : Source)∈kernel :=
  binaryNormalRow_mem normalCertificate i

private def posWitness (i : Fin 2) (j : Fin 3) : Fin 8 := ((if i.val < 1 then #[3,4,2] else #[6,1,2]) : Array (Fin 8))[j.val]!
private def negWitness (i : Fin 2) (j : Fin 3) : Fin 8 := ((if i.val < 1 then #[3,4,2] else #[6,1,2]) : Array (Fin 8))[j.val]!
private theorem pos_checked : ∀ i j, generators i*normalGenerators j*(generators i)⁻¹=
    (⟨rows (posWitness i j)⟩ : Source) := by decide +kernel
private theorem neg_checked : ∀ i j, (generators i)⁻¹*normalGenerators j*generators i=
    (⟨rows (negWitness i j)⟩ : Source) := by decide +kernel

instance normal : kernel.Normal := binaryNormal_of_generator_conjugates generators generators_full
  normalGenerators (fun i j => (pos_checked i j) ▸ row_mem (posWitness i j))
  (fun i j => (neg_checked i j) ▸ row_mem (negWitness i j))

private def representatives (i : Fin 4) : Source := ⟨((if i.val < 2 then (if i.val < 1 then 31 else 28) else (if i.val < 3 then 1 else 0)) : Fin 32)⟩
private def quotientNext (i : Fin 4) (j : Fin 2) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[1,2] else #[0,3]) else (if i.val < 3 then #[3,0] else #[2,1])) : Array (Fin 4))[j.val]!
private def quotientPrev (i : Fin 4) (j : Fin 2) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[1,2] else #[0,3]) else (if i.val < 3 then #[3,0] else #[2,1])) : Array (Fin 4))[j.val]!
private def quotientParents (i : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 0 else 1)) : Fin 4)
private def quotientLetters (i : Fin 4) : Fin 2 := ((if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 1 else 1)) : Fin 2)
private def stepWitness (i : Fin 4) (j : Fin 2) : Fin 8 := ((if i.val < 2 then (if i.val < 1 then #[7,7] else #[7,7]) else (if i.val < 3 then #[3,1] else #[3,4])) : Array (Fin 8))[j.val]!
private theorem quotientStep_checked : ∀ i j,
    representatives (quotientNext i j)/(representatives i*generators j)=
      (⟨rows (stepWitness i j)⟩ : Source) := (by decide +kernel)

def cosets : BinaryNormalCosetCertificate generators kernel 4 where
  representatives := representatives
  identity := 0
  identity_mem := by
    have he : representatives 0=(⟨rows 7⟩ : Source) := by decide +kernel
    exact he ▸ row_mem 7
  next := quotientNext
  step_mem := fun i j => (quotientStep_checked i j) ▸ row_mem (stepWitness i j)
  rank i := i.val
  parent i _ := quotientParents i
  letter i _ := quotientLetters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

@[reducible] def state : BinaryNormalState generators where
  kernel := kernel
  normal := normal
  generatorCount := 3
  normalGenerators := normalGenerators
  generated := rfl
  quotientCount := 4
  cardinal := by rw [kernel_card,source_card]
  cosets := cosets
  prev := quotientPrev
  prev_next := (by decide +kernel)

end N6

namespace N7
def normalGenerators (j : Fin 3) : Source := ⟨((if j.val < 1 then 2 else (if j.val < 2 then 14 else 12)) : Fin 32)⟩
def kernel : Subgroup Source := Subgroup.closure (Set.range normalGenerators)
private def rows (i : Fin 16) : Fin 32 := ((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 2) else (if i.val < 3 then 4 else 6)) else (if i.val < 6 then (if i.val < 5 then 8 else 10) else (if i.val < 7 then 12 else 14))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 17 else 19) else (if i.val < 11 then 21 else 23)) else (if i.val < 14 then (if i.val < 13 then 25 else 27) else (if i.val < 15 then 29 else 31)))) : Fin 32)
private def next (i : Fin 16) (j : Fin 3) : Fin 16 := ((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[10,8,9] else #[2,9,8]) else (if i.val < 3 then #[12,10,11] else #[4,11,10])) else (if i.val < 6 then (if i.val < 5 then #[14,12,13] else #[6,13,12]) else (if i.val < 7 then #[8,14,15] else #[0,15,14]))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then #[11,0,1] else #[3,1,0]) else (if i.val < 11 then #[13,2,3] else #[5,3,2])) else (if i.val < 14 then (if i.val < 13 then #[15,4,5] else #[7,5,4]) else (if i.val < 15 then #[9,6,7] else #[1,7,6])))) : Array (Fin 16))[j.val]!
private def rank (i : Fin 16) : ℕ := (if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 7 else 1) else (if i.val < 3 then 4 else 12)) else (if i.val < 6 then (if i.val < 5 then 13 else 14) else (if i.val < 7 then 3 else 2))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 6 else 5) else (if i.val < 11 then 10 else 11)) else (if i.val < 14 then (if i.val < 13 then 9 else 15) else (if i.val < 15 then 8 else 0))))
private def parents (i : Fin 16) : Fin 16 := ((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 7 else 15) else (if i.val < 3 then 1 else 9)) else (if i.val < 6 then (if i.val < 5 then 12 else 12) else (if i.val < 7 then 15 else 15))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 1 else 1) else (if i.val < 11 then 2 else 2)) else (if i.val < 14 then (if i.val < 13 then 2 else 10) else (if i.val < 15 then 7 else 15)))) : Fin 16)
private def letters (i : Fin 16) : Fin 3 := ((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 0 else 0)) else (if i.val < 6 then (if i.val < 5 then 1 else 2) else (if i.val < 7 then 2 else 1))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 2 else 1) else (if i.val < 11 then 1 else 2)) else (if i.val < 14 then (if i.val < 13 then 0 else 0) else (if i.val < 15 then 2 else 0)))) : Fin 3)

def normalCertificate : EncodedCayleyCertificate (binaryNormalRowEncoding normalGenerators) 16 where
  rows := rows
  identity := 15
  identity_eq := by decide +kernel
  next := next
  next_eq := (by decide +kernel)
  rank := rank
  parent i _ := parents i
  letter i hi := letters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

theorem normalRows_injective : Function.Injective normalCertificate.rows := by decide +kernel

theorem kernel_card : Nat.card kernel=16 := normalCertificate.card_closure normalRows_injective

theorem row_mem (i : Fin 16) : (⟨rows i⟩ : Source)∈kernel :=
  binaryNormalRow_mem normalCertificate i

private def posWitness (i : Fin 2) (j : Fin 3) : Fin 16 := ((if i.val < 1 then #[0,7,6] else #[9,14,6]) : Array (Fin 16))[j.val]!
private def negWitness (i : Fin 2) (j : Fin 3) : Fin 16 := ((if i.val < 1 then #[0,7,6] else #[0,14,6]) : Array (Fin 16))[j.val]!
private theorem pos_checked : ∀ i j, generators i*normalGenerators j*(generators i)⁻¹=
    (⟨rows (posWitness i j)⟩ : Source) := by decide +kernel
private theorem neg_checked : ∀ i j, (generators i)⁻¹*normalGenerators j*generators i=
    (⟨rows (negWitness i j)⟩ : Source) := by decide +kernel

instance normal : kernel.Normal := binaryNormal_of_generator_conjugates generators generators_full
  normalGenerators (fun i j => (pos_checked i j) ▸ row_mem (posWitness i j))
  (fun i j => (neg_checked i j) ▸ row_mem (negWitness i j))

private def representatives (i : Fin 2) : Source := ⟨((if i.val < 1 then 31 else 28) : Fin 32)⟩
private def quotientNext (i : Fin 2) (j : Fin 2) : Fin 2 := ((if i.val < 1 then #[1,1] else #[0,0]) : Array (Fin 2))[j.val]!
private def quotientPrev (i : Fin 2) (j : Fin 2) : Fin 2 := ((if i.val < 1 then #[1,1] else #[0,0]) : Array (Fin 2))[j.val]!
private def quotientParents (i : Fin 2) : Fin 2 := ((if i.val < 1 then 0 else 0) : Fin 2)
private def quotientLetters (i : Fin 2) : Fin 2 := ((if i.val < 1 then 0 else 0) : Fin 2)
private def stepWitness (i : Fin 2) (j : Fin 2) : Fin 16 := ((if i.val < 1 then #[15,12] else #[15,4]) : Array (Fin 16))[j.val]!
private theorem quotientStep_checked : ∀ i j,
    representatives (quotientNext i j)/(representatives i*generators j)=
      (⟨rows (stepWitness i j)⟩ : Source) := (by decide +kernel)

def cosets : BinaryNormalCosetCertificate generators kernel 2 where
  representatives := representatives
  identity := 0
  identity_mem := by
    have he : representatives 0=(⟨rows 15⟩ : Source) := by decide +kernel
    exact he ▸ row_mem 15
  next := quotientNext
  step_mem := fun i j => (quotientStep_checked i j) ▸ row_mem (stepWitness i j)
  rank i := i.val
  parent i _ := quotientParents i
  letter i _ := quotientLetters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

@[reducible] def state : BinaryNormalState generators where
  kernel := kernel
  normal := normal
  generatorCount := 3
  normalGenerators := normalGenerators
  generated := rfl
  quotientCount := 2
  cardinal := by rw [kernel_card,source_card]
  cosets := cosets
  prev := quotientPrev
  prev_next := (by decide +kernel)

end N7

namespace N8
def normalGenerators (j : Fin 3) : Source := ⟨((if j.val < 1 then 1 else (if j.val < 2 then 14 else 12)) : Fin 32)⟩
def kernel : Subgroup Source := Subgroup.closure (Set.range normalGenerators)
private def rows (i : Fin 16) : Fin 32 := ((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 1 else 3) else (if i.val < 3 then 4 else 6)) else (if i.val < 6 then (if i.val < 5 then 9 else 11) else (if i.val < 7 then 12 else 14))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 16 else 18) else (if i.val < 11 then 21 else 23)) else (if i.val < 14 then (if i.val < 13 then 24 else 26) else (if i.val < 15 then 29 else 31)))) : Fin 32)
private def next (i : Fin 16) (j : Fin 3) : Fin 16 := ((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[3,8,9] else #[11,9,8]) else (if i.val < 3 then #[13,10,11] else #[5,11,10])) else (if i.val < 6 then (if i.val < 5 then #[7,12,13] else #[15,13,12]) else (if i.val < 7 then #[9,14,15] else #[1,15,14]))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then #[2,0,1] else #[10,1,0]) else (if i.val < 11 then #[12,2,3] else #[4,3,2])) else (if i.val < 14 then (if i.val < 13 then #[6,4,5] else #[14,5,4]) else (if i.val < 15 then #[8,6,7] else #[0,7,6])))) : Array (Fin 16))[j.val]!
private def rank (i : Fin 16) : ℕ := (if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 1 else 7) else (if i.val < 3 then 12 else 4)) else (if i.val < 6 then (if i.val < 5 then 15 else 9) else (if i.val < 7 then 3 else 2))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 5 else 6) else (if i.val < 11 then 11 else 10)) else (if i.val < 14 then (if i.val < 13 then 14 else 13) else (if i.val < 15 then 8 else 0))))
private def parents (i : Fin 16) : Fin 16 := ((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 15 else 7) else (if i.val < 3 then 8 else 0)) else (if i.val < 6 then (if i.val < 5 then 11 else 3) else (if i.val < 7 then 15 else 15))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 0 else 0) else (if i.val < 11 then 3 else 3)) else (if i.val < 14 then (if i.val < 13 then 5 else 5) else (if i.val < 15 then 7 else 15)))) : Fin 16)
private def letters (i : Fin 16) : Fin 3 := ((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 0 else 0)) else (if i.val < 6 then (if i.val < 5 then 0 else 0) else (if i.val < 7 then 2 else 1))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 1 else 2) else (if i.val < 11 then 2 else 1)) else (if i.val < 14 then (if i.val < 13 then 2 else 1) else (if i.val < 15 then 2 else 0)))) : Fin 3)

def normalCertificate : EncodedCayleyCertificate (binaryNormalRowEncoding normalGenerators) 16 where
  rows := rows
  identity := 15
  identity_eq := by decide +kernel
  next := next
  next_eq := (by decide +kernel)
  rank := rank
  parent i _ := parents i
  letter i hi := letters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

theorem normalRows_injective : Function.Injective normalCertificate.rows := by decide +kernel

theorem kernel_card : Nat.card kernel=16 := normalCertificate.card_closure normalRows_injective

theorem row_mem (i : Fin 16) : (⟨rows i⟩ : Source)∈kernel :=
  binaryNormalRow_mem normalCertificate i

private def posWitness (i : Fin 2) (j : Fin 3) : Fin 16 := ((if i.val < 1 then #[1,7,6] else #[0,14,6]) : Array (Fin 16))[j.val]!
private def negWitness (i : Fin 2) (j : Fin 3) : Fin 16 := ((if i.val < 1 then #[1,7,6] else #[0,14,6]) : Array (Fin 16))[j.val]!
private theorem pos_checked : ∀ i j, generators i*normalGenerators j*(generators i)⁻¹=
    (⟨rows (posWitness i j)⟩ : Source) := by decide +kernel
private theorem neg_checked : ∀ i j, (generators i)⁻¹*normalGenerators j*generators i=
    (⟨rows (negWitness i j)⟩ : Source) := by decide +kernel

instance normal : kernel.Normal := binaryNormal_of_generator_conjugates generators generators_full
  normalGenerators (fun i j => (pos_checked i j) ▸ row_mem (posWitness i j))
  (fun i j => (neg_checked i j) ▸ row_mem (negWitness i j))

private def representatives (i : Fin 2) : Source := ⟨((if i.val < 1 then 31 else 28) : Fin 32)⟩
private def quotientNext (i : Fin 2) (j : Fin 2) : Fin 2 := ((if i.val < 1 then #[1,0] else #[0,1]) : Array (Fin 2))[j.val]!
private def quotientPrev (i : Fin 2) (j : Fin 2) : Fin 2 := ((if i.val < 1 then #[1,0] else #[0,1]) : Array (Fin 2))[j.val]!
private def quotientParents (i : Fin 2) : Fin 2 := ((if i.val < 1 then 0 else 0) : Fin 2)
private def quotientLetters (i : Fin 2) : Fin 2 := ((if i.val < 1 then 0 else 0) : Fin 2)
private def stepWitness (i : Fin 2) (j : Fin 2) : Fin 16 := ((if i.val < 1 then #[15,5] else #[15,13]) : Array (Fin 16))[j.val]!
private theorem quotientStep_checked : ∀ i j,
    representatives (quotientNext i j)/(representatives i*generators j)=
      (⟨rows (stepWitness i j)⟩ : Source) := (by decide +kernel)

def cosets : BinaryNormalCosetCertificate generators kernel 2 where
  representatives := representatives
  identity := 0
  identity_mem := by
    have he : representatives 0=(⟨rows 15⟩ : Source) := by decide +kernel
    exact he ▸ row_mem 15
  next := quotientNext
  step_mem := fun i j => (quotientStep_checked i j) ▸ row_mem (stepWitness i j)
  rank i := i.val
  parent i _ := quotientParents i
  letter i _ := quotientLetters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

@[reducible] def state : BinaryNormalState generators where
  kernel := kernel
  normal := normal
  generatorCount := 3
  normalGenerators := normalGenerators
  generated := rfl
  quotientCount := 2
  cardinal := by rw [kernel_card,source_card]
  cosets := cosets
  prev := quotientPrev
  prev_next := (by decide +kernel)

end N8

namespace N9
def normalGenerators (j : Fin 3) : Source := ⟨((if j.val < 1 then 13 else (if j.val < 2 then 28 else 15)) : Fin 32)⟩
def kernel : Subgroup Source := Subgroup.closure (Set.range normalGenerators)
private def rows (i : Fin 8) : Fin 32 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 12 else 13) else (if i.val < 3 then 14 else 15)) else (if i.val < 6 then (if i.val < 5 then 28 else 29) else (if i.val < 7 then 30 else 31))) : Fin 32)
private def next (i : Fin 8) (j : Fin 3) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[6,3,4] else #[7,2,5]) else (if i.val < 3 then #[4,1,6] else #[5,0,7])) else (if i.val < 6 then (if i.val < 5 then #[2,7,0] else #[3,6,1]) else (if i.val < 7 then #[0,5,2] else #[1,4,3]))) : Array (Fin 8))[j.val]!
private def rank (i : Fin 8) : ℕ := (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 6 else 1) else (if i.val < 3 then 4 else 3)) else (if i.val < 6 then (if i.val < 5 then 2 else 5) else (if i.val < 7 then 7 else 0)))
private def parents (i : Fin 8) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 4 else 7) else (if i.val < 3 then 1 else 7)) else (if i.val < 6 then (if i.val < 5 then 7 else 1) else (if i.val < 7 then 2 else 7))) : Fin 8)
private def letters (i : Fin 8) : Fin 3 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 2 else 0) else (if i.val < 3 then 1 else 2)) else (if i.val < 6 then (if i.val < 5 then 1 else 2) else (if i.val < 7 then 2 else 0))) : Fin 3)

def normalCertificate : EncodedCayleyCertificate (binaryNormalRowEncoding normalGenerators) 8 where
  rows := rows
  identity := 7
  identity_eq := by decide +kernel
  next := next
  next_eq := (by decide +kernel)
  rank := rank
  parent i _ := parents i
  letter i hi := letters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

theorem normalRows_injective : Function.Injective normalCertificate.rows := by decide +kernel

theorem kernel_card : Nat.card kernel=8 := normalCertificate.card_closure normalRows_injective

theorem row_mem (i : Fin 8) : (⟨rows i⟩ : Source)∈kernel :=
  binaryNormalRow_mem normalCertificate i

private def posWitness (i : Fin 2) (j : Fin 3) : Fin 8 := ((if i.val < 1 then #[1,4,3] else #[3,1,6]) : Array (Fin 8))[j.val]!
private def negWitness (i : Fin 2) (j : Fin 3) : Fin 8 := ((if i.val < 1 then #[1,4,3] else #[4,6,1]) : Array (Fin 8))[j.val]!
private theorem pos_checked : ∀ i j, generators i*normalGenerators j*(generators i)⁻¹=
    (⟨rows (posWitness i j)⟩ : Source) := by decide +kernel
private theorem neg_checked : ∀ i j, (generators i)⁻¹*normalGenerators j*generators i=
    (⟨rows (negWitness i j)⟩ : Source) := by decide +kernel

instance normal : kernel.Normal := binaryNormal_of_generator_conjugates generators generators_full
  normalGenerators (fun i j => (pos_checked i j) ▸ row_mem (posWitness i j))
  (fun i j => (neg_checked i j) ▸ row_mem (negWitness i j))

private def representatives (i : Fin 4) : Source := ⟨((if i.val < 2 then (if i.val < 1 then 31 else 1) else (if i.val < 3 then 6 else 11)) : Fin 32)⟩
private def quotientNext (i : Fin 4) (j : Fin 2) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[0,1] else #[1,2]) else (if i.val < 3 then #[2,3] else #[3,0])) : Array (Fin 4))[j.val]!
private def quotientPrev (i : Fin 4) (j : Fin 2) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[0,3] else #[1,0]) else (if i.val < 3 then #[2,1] else #[3,2])) : Array (Fin 4))[j.val]!
private def quotientParents (i : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 1 else 2)) : Fin 4)
private def quotientLetters (i : Fin 4) : Fin 2 := ((if i.val < 2 then (if i.val < 1 then 0 else 1) else (if i.val < 3 then 1 else 1)) : Fin 2)
private def stepWitness (i : Fin 4) (j : Fin 2) : Fin 8 := ((if i.val < 2 then (if i.val < 1 then #[4,7] else #[1,7]) else (if i.val < 3 then #[3,7] else #[6,7])) : Array (Fin 8))[j.val]!
private theorem quotientStep_checked : ∀ i j,
    representatives (quotientNext i j)/(representatives i*generators j)=
      (⟨rows (stepWitness i j)⟩ : Source) := (by decide +kernel)

def cosets : BinaryNormalCosetCertificate generators kernel 4 where
  representatives := representatives
  identity := 0
  identity_mem := by
    have he : representatives 0=(⟨rows 7⟩ : Source) := by decide +kernel
    exact he ▸ row_mem 7
  next := quotientNext
  step_mem := fun i j => (quotientStep_checked i j) ▸ row_mem (stepWitness i j)
  rank i := i.val
  parent i _ := quotientParents i
  letter i _ := quotientLetters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

@[reducible] def state : BinaryNormalState generators where
  kernel := kernel
  normal := normal
  generatorCount := 3
  normalGenerators := normalGenerators
  generated := rfl
  quotientCount := 4
  cardinal := by rw [kernel_card,source_card]
  cosets := cosets
  prev := quotientPrev
  prev_next := (by decide +kernel)

end N9

namespace N10
def normalGenerators (j : Fin 4) : Source := ⟨((if j.val < 2 then (if j.val < 1 then 13 else 28) else (if j.val < 3 then 6 else 15)) : Fin 32)⟩
def kernel : Subgroup Source := Subgroup.closure (Set.range normalGenerators)
private def rows (i : Fin 16) : Fin 32 := ((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 4 else 5) else (if i.val < 3 then 6 else 7)) else (if i.val < 6 then (if i.val < 5 then 12 else 13) else (if i.val < 7 then 14 else 15))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 20 else 21) else (if i.val < 11 then 22 else 23)) else (if i.val < 14 then (if i.val < 13 then 28 else 29) else (if i.val < 15 then 30 else 31)))) : Fin 32)
private def next (i : Fin 16) (j : Fin 4) : Fin 16 := ((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[10,3,13,8] else #[11,2,7,9]) else (if i.val < 3 then #[8,1,15,10] else #[9,0,5,11])) else (if i.val < 6 then (if i.val < 5 then #[14,7,9,12] else #[15,6,3,13]) else (if i.val < 7 then #[12,5,11,14] else #[13,4,1,15]))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then #[2,11,14,0] else #[3,10,4,1]) else (if i.val < 11 then #[0,9,12,2] else #[1,8,6,3])) else (if i.val < 14 then (if i.val < 13 then #[6,15,10,4] else #[7,14,0,5]) else (if i.val < 15 then #[4,13,8,6] else #[5,12,2,7])))) : Array (Fin 16))[j.val]!
private def rank (i : Fin 16) : ℕ := (if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 15 else 11) else (if i.val < 3 then 3 else 6)) else (if i.val < 6 then (if i.val < 5 then 9 else 1) else (if i.val < 7 then 5 else 4))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 10 else 14) else (if i.val < 11 then 8 else 12)) else (if i.val < 14 then (if i.val < 13 then 2 else 7) else (if i.val < 15 then 13 else 0))))
private def parents (i : Fin 16) : Fin 16 := ((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 3 else 2) else (if i.val < 3 then 15 else 5)) else (if i.val < 6 then (if i.val < 5 then 12 else 15) else (if i.val < 7 then 5 else 15))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 2 else 3) else (if i.val < 11 then 12 else 6)) else (if i.val < 14 then (if i.val < 13 then 15 else 5) else (if i.val < 15 then 6 else 15)))) : Fin 16)
private def letters (i : Fin 16) : Fin 4 := ((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 1 else 1) else (if i.val < 3 then 2 else 2)) else (if i.val < 6 then (if i.val < 5 then 3 else 0) else (if i.val < 7 then 1 else 3))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 0 else 0) else (if i.val < 11 then 2 else 2)) else (if i.val < 14 then (if i.val < 13 then 1 else 3) else (if i.val < 15 then 3 else 0)))) : Fin 4)

def normalCertificate : EncodedCayleyCertificate (binaryNormalRowEncoding normalGenerators) 16 where
  rows := rows
  identity := 15
  identity_eq := by decide +kernel
  next := next
  next_eq := (by decide +kernel)
  rank := rank
  parent i _ := parents i
  letter i hi := letters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

theorem normalRows_injective : Function.Injective normalCertificate.rows := by decide +kernel

theorem kernel_card : Nat.card kernel=16 := normalCertificate.card_closure normalRows_injective

theorem row_mem (i : Fin 16) : (⟨rows i⟩ : Source)∈kernel :=
  binaryNormalRow_mem normalCertificate i

private def posWitness (i : Fin 2) (j : Fin 4) : Fin 16 := ((if i.val < 1 then #[5,12,9,7] else #[7,5,2,14]) : Array (Fin 16))[j.val]!
private def negWitness (i : Fin 2) (j : Fin 4) : Fin 16 := ((if i.val < 1 then #[5,12,9,7] else #[12,14,2,5]) : Array (Fin 16))[j.val]!
private theorem pos_checked : ∀ i j, generators i*normalGenerators j*(generators i)⁻¹=
    (⟨rows (posWitness i j)⟩ : Source) := by decide +kernel
private theorem neg_checked : ∀ i j, (generators i)⁻¹*normalGenerators j*generators i=
    (⟨rows (negWitness i j)⟩ : Source) := by decide +kernel

instance normal : kernel.Normal := binaryNormal_of_generator_conjugates generators generators_full
  normalGenerators (fun i j => (pos_checked i j) ▸ row_mem (posWitness i j))
  (fun i j => (neg_checked i j) ▸ row_mem (negWitness i j))

private def representatives (i : Fin 2) : Source := ⟨((if i.val < 1 then 31 else 1) : Fin 32)⟩
private def quotientNext (i : Fin 2) (j : Fin 2) : Fin 2 := ((if i.val < 1 then #[0,1] else #[1,0]) : Array (Fin 2))[j.val]!
private def quotientPrev (i : Fin 2) (j : Fin 2) : Fin 2 := ((if i.val < 1 then #[0,1] else #[1,0]) : Array (Fin 2))[j.val]!
private def quotientParents (i : Fin 2) : Fin 2 := ((if i.val < 1 then 0 else 0) : Fin 2)
private def quotientLetters (i : Fin 2) : Fin 2 := ((if i.val < 1 then 0 else 1) : Fin 2)
private def stepWitness (i : Fin 2) (j : Fin 2) : Fin 16 := ((if i.val < 1 then #[12,15] else #[5,2]) : Array (Fin 16))[j.val]!
private theorem quotientStep_checked : ∀ i j,
    representatives (quotientNext i j)/(representatives i*generators j)=
      (⟨rows (stepWitness i j)⟩ : Source) := (by decide +kernel)

def cosets : BinaryNormalCosetCertificate generators kernel 2 where
  representatives := representatives
  identity := 0
  identity_mem := by
    have he : representatives 0=(⟨rows 15⟩ : Source) := by decide +kernel
    exact he ▸ row_mem 15
  next := quotientNext
  step_mem := fun i j => (quotientStep_checked i j) ▸ row_mem (stepWitness i j)
  rank i := i.val
  parent i _ := quotientParents i
  letter i _ := quotientLetters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

@[reducible] def state : BinaryNormalState generators where
  kernel := kernel
  normal := normal
  generatorCount := 4
  normalGenerators := normalGenerators
  generated := rfl
  quotientCount := 2
  cardinal := by rw [kernel_card,source_card]
  cosets := cosets
  prev := quotientPrev
  prev_next := (by decide +kernel)

end N10

namespace N11
def normalGenerators (j : Fin 2) : Source := ⟨((if j.val < 1 then 1 else 28) : Fin 32)⟩
def kernel : Subgroup Source := Subgroup.closure (Set.range normalGenerators)
private def rows (i : Fin 32) : Fin 32 := ((if i.val < 16 then (if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 1) else (if i.val < 3 then 2 else 3)) else (if i.val < 6 then (if i.val < 5 then 4 else 5) else (if i.val < 7 then 6 else 7))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 8 else 9) else (if i.val < 11 then 10 else 11)) else (if i.val < 14 then (if i.val < 13 then 12 else 13) else (if i.val < 15 then 14 else 15)))) else (if i.val < 24 then (if i.val < 20 then (if i.val < 18 then (if i.val < 17 then 16 else 17) else (if i.val < 19 then 18 else 19)) else (if i.val < 22 then (if i.val < 21 then 20 else 21) else (if i.val < 23 then 22 else 23))) else (if i.val < 28 then (if i.val < 26 then (if i.val < 25 then 24 else 25) else (if i.val < 27 then 26 else 27)) else (if i.val < 30 then (if i.val < 29 then 28 else 29) else (if i.val < 31 then 30 else 31))))) : Fin 32)
private def next (i : Fin 32) (j : Fin 2) : Fin 32 := ((if i.val < 16 then (if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[22,3] else #[6,2]) else (if i.val < 3 then #[7,1] else #[23,0])) else (if i.val < 6 then (if i.val < 5 then #[26,7] else #[10,6]) else (if i.val < 7 then #[11,5] else #[27,4]))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then #[30,11] else #[14,10]) else (if i.val < 11 then #[15,9] else #[31,8])) else (if i.val < 14 then (if i.val < 13 then #[18,15] else #[2,14]) else (if i.val < 15 then #[3,13] else #[19,12])))) else (if i.val < 24 then (if i.val < 20 then (if i.val < 18 then (if i.val < 17 then #[4,19] else #[20,18]) else (if i.val < 19 then #[21,17] else #[5,16])) else (if i.val < 22 then (if i.val < 21 then #[8,23] else #[24,22]) else (if i.val < 23 then #[25,21] else #[9,20]))) else (if i.val < 28 then (if i.val < 26 then (if i.val < 25 then #[12,27] else #[28,26]) else (if i.val < 27 then #[29,25] else #[13,24])) else (if i.val < 30 then (if i.val < 29 then #[0,31] else #[16,30]) else (if i.val < 31 then #[17,29] else #[1,28]))))) : Array (Fin 32))[j.val]!
private def rank (i : Fin 32) : ℕ := (if i.val < 16 then (if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 5 else 1) else (if i.val < 3 then 4 else 10)) else (if i.val < 6 then (if i.val < 5 then 14 else 7) else (if i.val < 7 then 3 else 8))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 11 else 20) else (if i.val < 11 then 12 else 6)) else (if i.val < 14 then (if i.val < 13 then 28 else 21) else (if i.val < 15 then 29 else 19)))) else (if i.val < 24 then (if i.val < 20 then (if i.val < 18 then (if i.val < 17 then 31 else 25) else (if i.val < 19 then 30 else 27)) else (if i.val < 22 then (if i.val < 21 then 24 else 16) else (if i.val < 23 then 9 else 17))) else (if i.val < 28 then (if i.val < 26 then (if i.val < 25 then 22 else 15) else (if i.val < 27 then 23 else 13)) else (if i.val < 30 then (if i.val < 29 then 2 else 26) else (if i.val < 31 then 18 else 0)))))
private def parents (i : Fin 32) : Fin 32 := ((if i.val < 16 then (if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 28 else 31) else (if i.val < 3 then 1 else 0)) else (if i.val < 6 then (if i.val < 5 then 7 else 6) else (if i.val < 7 then 1 else 2))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 11 else 10) else (if i.val < 11 then 5 else 6)) else (if i.val < 14 then (if i.val < 13 then 15 else 27) else (if i.val < 15 then 9 else 10)))) else (if i.val < 24 then (if i.val < 20 then (if i.val < 18 then (if i.val < 17 then 29 else 30) else (if i.val < 19 then 17 else 15)) else (if i.val < 22 then (if i.val < 21 then 23 else 22) else (if i.val < 23 then 0 else 3))) else (if i.val < 28 then (if i.val < 26 then (if i.val < 25 then 27 else 22) else (if i.val < 27 then 4 else 7)) else (if i.val < 30 then (if i.val < 29 then 31 else 30) else (if i.val < 31 then 8 else 31))))) : Fin 32)
private def letters (i : Fin 32) : Fin 2 := ((if i.val < 16 then (if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 1 else 1)) else (if i.val < 6 then (if i.val < 5 then 1 else 1) else (if i.val < 7 then 0 else 0))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 1 else 1) else (if i.val < 11 then 0 else 0)) else (if i.val < 14 then (if i.val < 13 then 1 else 0) else (if i.val < 15 then 0 else 0)))) else (if i.val < 24 then (if i.val < 20 then (if i.val < 18 then (if i.val < 17 then 0 else 0) else (if i.val < 19 then 1 else 0)) else (if i.val < 22 then (if i.val < 21 then 1 else 1) else (if i.val < 23 then 0 else 0))) else (if i.val < 28 then (if i.val < 26 then (if i.val < 25 then 1 else 0) else (if i.val < 27 then 0 else 0)) else (if i.val < 30 then (if i.val < 29 then 1 else 1) else (if i.val < 31 then 0 else 0))))) : Fin 2)

def normalCertificate : EncodedCayleyCertificate (binaryNormalRowEncoding normalGenerators) 32 where
  rows := rows
  identity := 31
  identity_eq := by decide +kernel
  next := next
  next_eq := (Fin.addCases (m := 16) (n := 16) (by decide +kernel) (by decide +kernel))
  rank := rank
  parent i _ := parents i
  letter i hi := letters i
  parent_lt := (Fin.addCases (m := 16) (n := 16) (by decide +kernel) (by decide +kernel))
  parent_next := (Fin.addCases (m := 16) (n := 16) (by decide +kernel) (by decide +kernel))

theorem normalRows_injective : Function.Injective normalCertificate.rows := by decide +kernel

theorem kernel_card : Nat.card kernel=32 := normalCertificate.card_closure normalRows_injective

theorem row_mem (i : Fin 32) : (⟨rows i⟩ : Source)∈kernel :=
  binaryNormalRow_mem normalCertificate i

private def posWitness (i : Fin 2) (j : Fin 2) : Fin 32 := ((if i.val < 1 then #[3,28] else #[1,13]) : Array (Fin 32))[j.val]!
private def negWitness (i : Fin 2) (j : Fin 2) : Fin 32 := ((if i.val < 1 then #[3,28] else #[1,30]) : Array (Fin 32))[j.val]!
private theorem pos_checked : ∀ i j, generators i*normalGenerators j*(generators i)⁻¹=
    (⟨rows (posWitness i j)⟩ : Source) := by decide +kernel
private theorem neg_checked : ∀ i j, (generators i)⁻¹*normalGenerators j*generators i=
    (⟨rows (negWitness i j)⟩ : Source) := by decide +kernel

instance normal : kernel.Normal := binaryNormal_of_generator_conjugates generators generators_full
  normalGenerators (fun i j => (pos_checked i j) ▸ row_mem (posWitness i j))
  (fun i j => (neg_checked i j) ▸ row_mem (negWitness i j))

private def representatives (i : Fin 1) : Source := ⟨(31 : Fin 32)⟩
private def quotientNext (i : Fin 1) (j : Fin 2) : Fin 1 := (#[0,0] : Array (Fin 1))[j.val]!
private def quotientPrev (i : Fin 1) (j : Fin 2) : Fin 1 := (#[0,0] : Array (Fin 1))[j.val]!
private def quotientParents (i : Fin 1) : Fin 1 := (0 : Fin 1)
private def quotientLetters (i : Fin 1) : Fin 2 := (0 : Fin 2)
private def stepWitness (i : Fin 1) (j : Fin 2) : Fin 32 := (#[28,11] : Array (Fin 32))[j.val]!
private theorem quotientStep_checked : ∀ i j,
    representatives (quotientNext i j)/(representatives i*generators j)=
      (⟨rows (stepWitness i j)⟩ : Source) := (by decide +kernel)

def cosets : BinaryNormalCosetCertificate generators kernel 1 where
  representatives := representatives
  identity := 0
  identity_mem := by
    have he : representatives 0=(⟨rows 31⟩ : Source) := by decide +kernel
    exact he ▸ row_mem 31
  next := quotientNext
  step_mem := fun i j => (quotientStep_checked i j) ▸ row_mem (stepWitness i j)
  rank i := i.val
  parent i _ := quotientParents i
  letter i _ := quotientLetters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

@[reducible] def state : BinaryNormalState generators where
  kernel := kernel
  normal := normal
  generatorCount := 2
  normalGenerators := normalGenerators
  generated := rfl
  quotientCount := 1
  cardinal := by rw [kernel_card,source_card]
  cosets := cosets
  prev := quotientPrev
  prev_next := (by decide +kernel)

end N11

@[reducible] def states (i : Fin 12) : BinaryNormalState generators :=
  (if i.val < 6 then (if i.val < 3 then (if i.val < 1 then N0.state else (if i.val < 2 then N1.state else N2.state)) else (if i.val < 4 then N3.state else (if i.val < 5 then N4.state else N5.state))) else (if i.val < 9 then (if i.val < 7 then N6.state else (if i.val < 8 then N7.state else N8.state)) else (if i.val < 10 then N9.state else (if i.val < 11 then N10.state else N11.state))))

end SymmetricSubgroupAsymptotics.BinaryNormal8T20
