import SymmetricSubgroupAsymptotics.BinaryNormalGeneratorChecks
import SymmetricSubgroupAsymptotics.BinaryMenuCayley8T16

/-! Exact original normal states and quotient rows for 8T16.
Generated by export_lean_normal_registry.py; all finite facts are checked
in Lean's kernel. This file certifies normal-state coverage, not the later
pair/character/transport acceptance of those states. -/

set_option autoImplicit false
set_option maxRecDepth 100000
set_option maxHeartbeats 0
set_option linter.unusedVariables false
noncomputable section
namespace SymmetricSubgroupAsymptotics.BinaryNormal8T16

abbrev Source := FiniteGroupRow 32
local instance : Group Source := BinaryMenuCayley8T16.group

def generators (j : Fin 2) : Source :=
  ⟨BinaryMenuCayley8T16.certificate.next BinaryMenuCayley8T16.certificate.identity j⟩

theorem generators_full : Subgroup.closure (Set.range generators)=⊤ := by
  apply binaryNormal_full_generators_of_equiv BinaryMenuCayley8T16.generators
    generators BinaryMenuCayley8T16.originalEquiv
  intro j
  change BinaryMenuCayley8T16.certificate.toCayley.elements
    (BinaryMenuCayley8T16.certificate.toCayley.next
      BinaryMenuCayley8T16.certificate.toCayley.identity j)=_
  rw [FiniteCayleyCertificate.next_eq,FiniteCayleyCertificate.identity_eq,one_mul]

theorem source_card : Nat.card Source=32 := by
  rw [Nat.card_eq_fintype_card]
  rfl

namespace N0
def normalGenerators (j : Fin 0) : Source := Fin.elim0 j
def kernel : Subgroup Source := Subgroup.closure (Set.range normalGenerators)
private def rows (i : Fin 1) : Fin 32 := (31 : Fin 32)
private def next (i : Fin 1) (j : Fin 0) : Fin 1 := Fin.elim0 j
private def rank (i : Fin 1) : ℕ := 0
private def parents (i : Fin 1) : Fin 1 := (0 : Fin 1)

def normalCertificate : EncodedCayleyCertificate (binaryNormalRowEncoding normalGenerators) 1 where
  rows := rows
  identity := 0
  identity_eq := by decide +kernel
  next := next
  next_eq := (by decide +kernel)
  rank := rank
  parent i _ := parents i
  letter i hi := False.elim (hi (Subsingleton.elim i (0 : Fin 1)))
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

theorem normalRows_injective : Function.Injective normalCertificate.rows := by decide +kernel

theorem kernel_card : Nat.card kernel=1 := normalCertificate.card_closure normalRows_injective

theorem row_mem (i : Fin 1) : (⟨rows i⟩ : Source)∈kernel :=
  binaryNormalRow_mem normalCertificate i

instance normal : kernel.Normal := binaryNormal_of_generator_conjugates generators generators_full
  normalGenerators (fun _ j => Fin.elim0 j) (fun _ j => Fin.elim0 j)

private def representatives (i : Fin 32) : Source := ⟨((if i.val < 16 then (if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 31 else 28) else (if i.val < 3 then 3 else 2)) else (if i.val < 6 then (if i.val < 5 then 0 else 5) else (if i.val < 7 then 1 else 21))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 4 else 6) else (if i.val < 11 then 8 else 20)) else (if i.val < 14 then (if i.val < 13 then 22 else 26) else (if i.val < 15 then 7 else 24)))) else (if i.val < 24 then (if i.val < 20 then (if i.val < 18 then (if i.val < 17 then 9 else 11) else (if i.val < 19 then 12 else 23)) else (if i.val < 22 then (if i.val < 21 then 10 else 27) else (if i.val < 23 then 25 else 15))) else (if i.val < 28 then (if i.val < 26 then (if i.val < 25 then 30 else 13) else (if i.val < 27 then 16 else 29)) else (if i.val < 30 then (if i.val < 29 then 14 else 17) else (if i.val < 31 then 19 else 18))))) : Fin 32)⟩
private def quotientNext (i : Fin 32) (j : Fin 2) : Fin 32 := ((if i.val < 16 then (if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[1,2] else #[0,3]) else (if i.val < 3 then #[4,5] else #[6,7])) else (if i.val < 6 then (if i.val < 5 then #[2,8] else #[9,10]) else (if i.val < 7 then #[3,11] else #[12,13]))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then #[14,15] else #[5,16]) else (if i.val < 11 then #[17,18] else #[19,20])) else (if i.val < 14 then (if i.val < 13 then #[7,21] else #[22,23]) else (if i.val < 15 then #[8,22] else #[21,24])))) else (if i.val < 24 then (if i.val < 20 then (if i.val < 18 then (if i.val < 17 then #[20,1] else #[10,25]) else (if i.val < 19 then #[23,26] else #[11,17])) else (if i.val < 22 then (if i.val < 21 then #[16,27] else #[15,0]) else (if i.val < 23 then #[13,28] else #[18,29]))) else (if i.val < 28 then (if i.val < 26 then (if i.val < 25 then #[27,30] else #[28,4]) else (if i.val < 27 then #[30,12] else #[24,31])) else (if i.val < 30 then (if i.val < 29 then #[25,6] else #[31,9]) else (if i.val < 31 then #[26,19] else #[29,14]))))) : Array (Fin 32))[j.val]!
private def quotientPrev (i : Fin 32) (j : Fin 2) : Fin 32 := ((if i.val < 16 then (if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[1,21] else #[0,16]) else (if i.val < 3 then #[4,0] else #[6,1])) else (if i.val < 6 then (if i.val < 5 then #[2,25] else #[9,2]) else (if i.val < 7 then #[3,28] else #[12,3]))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then #[14,4] else #[5,29]) else (if i.val < 11 then #[17,5] else #[19,6])) else (if i.val < 14 then (if i.val < 13 then #[7,26] else #[22,7]) else (if i.val < 15 then #[8,31] else #[21,8])))) else (if i.val < 24 then (if i.val < 20 then (if i.val < 18 then (if i.val < 17 then #[20,9] else #[10,19]) else (if i.val < 19 then #[23,10] else #[11,30])) else (if i.val < 22 then (if i.val < 21 then #[16,11] else #[15,12]) else (if i.val < 23 then #[13,14] else #[18,13]))) else (if i.val < 28 then (if i.val < 26 then (if i.val < 25 then #[27,15] else #[28,17]) else (if i.val < 27 then #[30,18] else #[24,20])) else (if i.val < 30 then (if i.val < 29 then #[25,22] else #[31,23]) else (if i.val < 31 then #[26,24] else #[29,27]))))) : Array (Fin 32))[j.val]!
private def quotientParents (i : Fin 32) : Fin 32 := ((if i.val < 16 then (if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 0 else 1)) else (if i.val < 6 then (if i.val < 5 then 2 else 2) else (if i.val < 7 then 3 else 3))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 4 else 5) else (if i.val < 11 then 5 else 6)) else (if i.val < 14 then (if i.val < 13 then 7 else 7) else (if i.val < 15 then 8 else 8)))) else (if i.val < 24 then (if i.val < 20 then (if i.val < 18 then (if i.val < 17 then 9 else 10) else (if i.val < 19 then 10 else 11)) else (if i.val < 22 then (if i.val < 21 then 11 else 12) else (if i.val < 23 then 13 else 13))) else (if i.val < 28 then (if i.val < 26 then (if i.val < 25 then 15 else 17) else (if i.val < 27 then 18 else 20)) else (if i.val < 30 then (if i.val < 29 then 22 else 23) else (if i.val < 31 then 24 else 27))))) : Fin 32)
private def quotientLetters (i : Fin 32) : Fin 2 := ((if i.val < 16 then (if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 1 else 1)) else (if i.val < 6 then (if i.val < 5 then 0 else 1) else (if i.val < 7 then 0 else 1))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 1 else 0) else (if i.val < 11 then 1 else 1)) else (if i.val < 14 then (if i.val < 13 then 0 else 1) else (if i.val < 15 then 0 else 1)))) else (if i.val < 24 then (if i.val < 20 then (if i.val < 18 then (if i.val < 17 then 1 else 0) else (if i.val < 19 then 1 else 0)) else (if i.val < 22 then (if i.val < 21 then 1 else 1) else (if i.val < 23 then 0 else 1))) else (if i.val < 28 then (if i.val < 26 then (if i.val < 25 then 1 else 1) else (if i.val < 27 then 1 else 1)) else (if i.val < 30 then (if i.val < 29 then 1 else 1) else (if i.val < 31 then 1 else 1))))) : Fin 2)
private def stepWitness (i : Fin 32) (j : Fin 2) : Fin 1 := ((if i.val < 16 then (if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[0,0] else #[0,0]) else (if i.val < 3 then #[0,0] else #[0,0])) else (if i.val < 6 then (if i.val < 5 then #[0,0] else #[0,0]) else (if i.val < 7 then #[0,0] else #[0,0]))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then #[0,0] else #[0,0]) else (if i.val < 11 then #[0,0] else #[0,0])) else (if i.val < 14 then (if i.val < 13 then #[0,0] else #[0,0]) else (if i.val < 15 then #[0,0] else #[0,0])))) else (if i.val < 24 then (if i.val < 20 then (if i.val < 18 then (if i.val < 17 then #[0,0] else #[0,0]) else (if i.val < 19 then #[0,0] else #[0,0])) else (if i.val < 22 then (if i.val < 21 then #[0,0] else #[0,0]) else (if i.val < 23 then #[0,0] else #[0,0]))) else (if i.val < 28 then (if i.val < 26 then (if i.val < 25 then #[0,0] else #[0,0]) else (if i.val < 27 then #[0,0] else #[0,0])) else (if i.val < 30 then (if i.val < 29 then #[0,0] else #[0,0]) else (if i.val < 31 then #[0,0] else #[0,0]))))) : Array (Fin 1))[j.val]!
private theorem quotientStep_checked : ∀ i j,
    representatives (quotientNext i j)/(representatives i*generators j)=
      (⟨rows (stepWitness i j)⟩ : Source) := (Fin.addCases (m := 16) (n := 16) (by decide +kernel) (by decide +kernel))

def cosets : BinaryNormalCosetCertificate generators kernel 32 where
  representatives := representatives
  identity := 0
  identity_mem := by
    have he : representatives 0=(⟨rows 0⟩ : Source) := by decide +kernel
    exact he ▸ row_mem 0
  next := quotientNext
  step_mem := fun i j => (quotientStep_checked i j) ▸ row_mem (stepWitness i j)
  rank i := i.val
  parent i _ := quotientParents i
  letter i _ := quotientLetters i
  parent_lt := (Fin.addCases (m := 16) (n := 16) (by decide +kernel) (by decide +kernel))
  parent_next := (Fin.addCases (m := 16) (n := 16) (by decide +kernel) (by decide +kernel))

@[reducible] def state : BinaryNormalState generators where
  kernel := kernel
  normal := normal
  generatorCount := 0
  normalGenerators := normalGenerators
  generated := rfl
  quotientCount := 32
  cardinal := by rw [kernel_card,source_card]
  cosets := cosets
  prev := quotientPrev
  prev_next := (Fin.addCases (m := 16) (n := 16) (by decide +kernel) (by decide +kernel))

end N0

namespace N1
def normalGenerators (j : Fin 1) : Source := ⟨(12 : Fin 32)⟩
def kernel : Subgroup Source := Subgroup.closure (Set.range normalGenerators)
private def rows (i : Fin 2) : Fin 32 := ((if i.val < 1 then 12 else 31) : Fin 32)
private def next (i : Fin 2) (j : Fin 1) : Fin 2 := ((if i.val < 1 then #[1] else #[0]) : Array (Fin 2))[j.val]!
private def rank (i : Fin 2) : ℕ := (if i.val < 1 then 1 else 0)
private def parents (i : Fin 2) : Fin 2 := ((if i.val < 1 then 1 else 1) : Fin 2)
private def letters (i : Fin 2) : Fin 1 := ((if i.val < 1 then 0 else 0) : Fin 1)

def normalCertificate : EncodedCayleyCertificate (binaryNormalRowEncoding normalGenerators) 2 where
  rows := rows
  identity := 1
  identity_eq := by decide +kernel
  next := next
  next_eq := (by decide +kernel)
  rank := rank
  parent i _ := parents i
  letter i hi := letters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

theorem normalRows_injective : Function.Injective normalCertificate.rows := by decide +kernel

theorem kernel_card : Nat.card kernel=2 := normalCertificate.card_closure normalRows_injective

theorem row_mem (i : Fin 2) : (⟨rows i⟩ : Source)∈kernel :=
  binaryNormalRow_mem normalCertificate i

private def posWitness (i : Fin 2) (j : Fin 1) : Fin 2 := ((if i.val < 1 then #[0] else #[0]) : Array (Fin 2))[j.val]!
private def negWitness (i : Fin 2) (j : Fin 1) : Fin 2 := ((if i.val < 1 then #[0] else #[0]) : Array (Fin 2))[j.val]!
private theorem pos_checked : ∀ i j, generators i*normalGenerators j*(generators i)⁻¹=
    (⟨rows (posWitness i j)⟩ : Source) := by decide +kernel
private theorem neg_checked : ∀ i j, (generators i)⁻¹*normalGenerators j*generators i=
    (⟨rows (negWitness i j)⟩ : Source) := by decide +kernel

instance normal : kernel.Normal := binaryNormal_of_generator_conjugates generators generators_full
  normalGenerators (fun i j => (pos_checked i j) ▸ row_mem (posWitness i j))
  (fun i j => (neg_checked i j) ▸ row_mem (negWitness i j))

private def representatives (i : Fin 16) : Source := ⟨((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 31 else 28) else (if i.val < 3 then 3 else 2)) else (if i.val < 6 then (if i.val < 5 then 0 else 5) else (if i.val < 7 then 1 else 21))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 4 else 8) else (if i.val < 11 then 20 else 26)) else (if i.val < 14 then (if i.val < 13 then 24 else 10) else (if i.val < 15 then 30 else 29)))) : Fin 32)⟩
private def quotientNext (i : Fin 16) (j : Fin 2) : Fin 16 := ((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[1,2] else #[0,3]) else (if i.val < 3 then #[4,5] else #[6,7])) else (if i.val < 6 then (if i.val < 5 then #[2,8] else #[7,9]) else (if i.val < 7 then #[3,10] else #[5,11]))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then #[10,12] else #[12,0]) else (if i.val < 11 then #[8,13] else #[13,1])) else (if i.val < 14 then (if i.val < 13 then #[9,14] else #[11,15]) else (if i.val < 15 then #[15,4] else #[14,6])))) : Array (Fin 16))[j.val]!
private def quotientPrev (i : Fin 16) (j : Fin 2) : Fin 16 := ((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[1,9] else #[0,11]) else (if i.val < 3 then #[4,0] else #[6,1])) else (if i.val < 6 then (if i.val < 5 then #[2,14] else #[7,2]) else (if i.val < 7 then #[3,15] else #[5,3]))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then #[10,4] else #[12,5]) else (if i.val < 11 then #[8,6] else #[13,7])) else (if i.val < 14 then (if i.val < 13 then #[9,8] else #[11,10]) else (if i.val < 15 then #[15,12] else #[14,13])))) : Array (Fin 16))[j.val]!
private def quotientParents (i : Fin 16) : Fin 16 := ((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 0 else 1)) else (if i.val < 6 then (if i.val < 5 then 2 else 2) else (if i.val < 7 then 3 else 3))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 4 else 5) else (if i.val < 11 then 6 else 7)) else (if i.val < 14 then (if i.val < 13 then 8 else 10) else (if i.val < 15 then 12 else 13)))) : Fin 16)
private def quotientLetters (i : Fin 16) : Fin 2 := ((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 1 else 1)) else (if i.val < 6 then (if i.val < 5 then 0 else 1) else (if i.val < 7 then 0 else 1))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 1 else 1) else (if i.val < 11 then 1 else 1)) else (if i.val < 14 then (if i.val < 13 then 1 else 1) else (if i.val < 15 then 1 else 1)))) : Fin 2)
private def stepWitness (i : Fin 16) (j : Fin 2) : Fin 2 := ((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[1,1] else #[1,1]) else (if i.val < 3 then #[1,1] else #[1,1])) else (if i.val < 6 then (if i.val < 5 then #[1,1] else #[0,1]) else (if i.val < 7 then #[1,1] else #[0,1]))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then #[0,1] else #[0,0]) else (if i.val < 11 then #[0,1] else #[0,0])) else (if i.val < 14 then (if i.val < 13 then #[0,1] else #[0,1]) else (if i.val < 15 then #[1,0] else #[1,0])))) : Array (Fin 2))[j.val]!
private theorem quotientStep_checked : ∀ i j,
    representatives (quotientNext i j)/(representatives i*generators j)=
      (⟨rows (stepWitness i j)⟩ : Source) := (by decide +kernel)

def cosets : BinaryNormalCosetCertificate generators kernel 16 where
  representatives := representatives
  identity := 0
  identity_mem := by
    have he : representatives 0=(⟨rows 1⟩ : Source) := by decide +kernel
    exact he ▸ row_mem 1
  next := quotientNext
  step_mem := fun i j => (quotientStep_checked i j) ▸ row_mem (stepWitness i j)
  rank i := i.val
  parent i _ := quotientParents i
  letter i _ := quotientLetters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

@[reducible] def state : BinaryNormalState generators where
  kernel := kernel
  normal := normal
  generatorCount := 1
  normalGenerators := normalGenerators
  generated := rfl
  quotientCount := 16
  cardinal := by rw [kernel_card,source_card]
  cosets := cosets
  prev := quotientPrev
  prev_next := (by decide +kernel)

end N1

namespace N2
def normalGenerators (j : Fin 1) : Source := ⟨(20 : Fin 32)⟩
def kernel : Subgroup Source := Subgroup.closure (Set.range normalGenerators)
private def rows (i : Fin 4) : Fin 32 := ((if i.val < 2 then (if i.val < 1 then 7 else 12) else (if i.val < 3 then 20 else 31)) : Fin 32)
private def next (i : Fin 4) (j : Fin 1) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[3] else #[0]) else (if i.val < 3 then #[1] else #[2])) : Array (Fin 4))[j.val]!
private def rank (i : Fin 4) : ℕ := (if i.val < 2 then (if i.val < 1 then 3 else 2) else (if i.val < 3 then 1 else 0))
private def parents (i : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then 1 else 2) else (if i.val < 3 then 3 else 3)) : Fin 4)
private def letters (i : Fin 4) : Fin 1 := ((if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 0 else 0)) : Fin 1)

def normalCertificate : EncodedCayleyCertificate (binaryNormalRowEncoding normalGenerators) 4 where
  rows := rows
  identity := 3
  identity_eq := by decide +kernel
  next := next
  next_eq := (by decide +kernel)
  rank := rank
  parent i _ := parents i
  letter i hi := letters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

theorem normalRows_injective : Function.Injective normalCertificate.rows := by decide +kernel

theorem kernel_card : Nat.card kernel=4 := normalCertificate.card_closure normalRows_injective

theorem row_mem (i : Fin 4) : (⟨rows i⟩ : Source)∈kernel :=
  binaryNormalRow_mem normalCertificate i

private def posWitness (i : Fin 2) (j : Fin 1) : Fin 4 := ((if i.val < 1 then #[0] else #[0]) : Array (Fin 4))[j.val]!
private def negWitness (i : Fin 2) (j : Fin 1) : Fin 4 := ((if i.val < 1 then #[0] else #[0]) : Array (Fin 4))[j.val]!
private theorem pos_checked : ∀ i j, generators i*normalGenerators j*(generators i)⁻¹=
    (⟨rows (posWitness i j)⟩ : Source) := by decide +kernel
private theorem neg_checked : ∀ i j, (generators i)⁻¹*normalGenerators j*generators i=
    (⟨rows (negWitness i j)⟩ : Source) := by decide +kernel

instance normal : kernel.Normal := binaryNormal_of_generator_conjugates generators generators_full
  normalGenerators (fun i j => (pos_checked i j) ▸ row_mem (posWitness i j))
  (fun i j => (neg_checked i j) ▸ row_mem (negWitness i j))

private def representatives (i : Fin 8) : Source := ⟨((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 31 else 28) else (if i.val < 3 then 3 else 2)) else (if i.val < 6 then (if i.val < 5 then 0 else 5) else (if i.val < 7 then 1 else 21))) : Fin 32)⟩
private def quotientNext (i : Fin 8) (j : Fin 2) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[1,2] else #[0,3]) else (if i.val < 3 then #[4,5] else #[6,7])) else (if i.val < 6 then (if i.val < 5 then #[2,1] else #[7,6]) else (if i.val < 7 then #[3,0] else #[5,4]))) : Array (Fin 8))[j.val]!
private def quotientPrev (i : Fin 8) (j : Fin 2) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[1,6] else #[0,4]) else (if i.val < 3 then #[4,0] else #[6,1])) else (if i.val < 6 then (if i.val < 5 then #[2,7] else #[7,2]) else (if i.val < 7 then #[3,5] else #[5,3]))) : Array (Fin 8))[j.val]!
private def quotientParents (i : Fin 8) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 0 else 1)) else (if i.val < 6 then (if i.val < 5 then 2 else 2) else (if i.val < 7 then 3 else 3))) : Fin 8)
private def quotientLetters (i : Fin 8) : Fin 2 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 1 else 1)) else (if i.val < 6 then (if i.val < 5 then 0 else 1) else (if i.val < 7 then 0 else 1))) : Fin 2)
private def stepWitness (i : Fin 8) (j : Fin 2) : Fin 4 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[3,3] else #[3,3]) else (if i.val < 3 then #[3,3] else #[3,3])) else (if i.val < 6 then (if i.val < 5 then #[3,2] else #[1,0]) else (if i.val < 7 then #[3,0] else #[1,2]))) : Array (Fin 4))[j.val]!
private theorem quotientStep_checked : ∀ i j,
    representatives (quotientNext i j)/(representatives i*generators j)=
      (⟨rows (stepWitness i j)⟩ : Source) := (by decide +kernel)

def cosets : BinaryNormalCosetCertificate generators kernel 8 where
  representatives := representatives
  identity := 0
  identity_mem := by
    have he : representatives 0=(⟨rows 3⟩ : Source) := by decide +kernel
    exact he ▸ row_mem 3
  next := quotientNext
  step_mem := fun i j => (quotientStep_checked i j) ▸ row_mem (stepWitness i j)
  rank i := i.val
  parent i _ := quotientParents i
  letter i _ := quotientLetters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

@[reducible] def state : BinaryNormalState generators where
  kernel := kernel
  normal := normal
  generatorCount := 1
  normalGenerators := normalGenerators
  generated := rfl
  quotientCount := 8
  cardinal := by rw [kernel_card,source_card]
  cosets := cosets
  prev := quotientPrev
  prev_next := (by decide +kernel)

end N2

namespace N3
def normalGenerators (j : Fin 1) : Source := ⟨(5 : Fin 32)⟩
def kernel : Subgroup Source := Subgroup.closure (Set.range normalGenerators)
private def rows (i : Fin 4) : Fin 32 := ((if i.val < 2 then (if i.val < 1 then 5 else 12) else (if i.val < 3 then 22 else 31)) : Fin 32)
private def next (i : Fin 4) (j : Fin 1) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[1] else #[2]) else (if i.val < 3 then #[3] else #[0])) : Array (Fin 4))[j.val]!
private def rank (i : Fin 4) : ℕ := (if i.val < 2 then (if i.val < 1 then 1 else 2) else (if i.val < 3 then 3 else 0))
private def parents (i : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then 3 else 0) else (if i.val < 3 then 1 else 3)) : Fin 4)
private def letters (i : Fin 4) : Fin 1 := ((if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 0 else 0)) : Fin 1)

def normalCertificate : EncodedCayleyCertificate (binaryNormalRowEncoding normalGenerators) 4 where
  rows := rows
  identity := 3
  identity_eq := by decide +kernel
  next := next
  next_eq := (by decide +kernel)
  rank := rank
  parent i _ := parents i
  letter i hi := letters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

theorem normalRows_injective : Function.Injective normalCertificate.rows := by decide +kernel

theorem kernel_card : Nat.card kernel=4 := normalCertificate.card_closure normalRows_injective

theorem row_mem (i : Fin 4) : (⟨rows i⟩ : Source)∈kernel :=
  binaryNormalRow_mem normalCertificate i

private def posWitness (i : Fin 2) (j : Fin 1) : Fin 4 := ((if i.val < 1 then #[2] else #[0]) : Array (Fin 4))[j.val]!
private def negWitness (i : Fin 2) (j : Fin 1) : Fin 4 := ((if i.val < 1 then #[2] else #[0]) : Array (Fin 4))[j.val]!
private theorem pos_checked : ∀ i j, generators i*normalGenerators j*(generators i)⁻¹=
    (⟨rows (posWitness i j)⟩ : Source) := by decide +kernel
private theorem neg_checked : ∀ i j, (generators i)⁻¹*normalGenerators j*generators i=
    (⟨rows (negWitness i j)⟩ : Source) := by decide +kernel

instance normal : kernel.Normal := binaryNormal_of_generator_conjugates generators generators_full
  normalGenerators (fun i j => (pos_checked i j) ▸ row_mem (posWitness i j))
  (fun i j => (neg_checked i j) ▸ row_mem (negWitness i j))

private def representatives (i : Fin 8) : Source := ⟨((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 31 else 28) else (if i.val < 3 then 3 else 2)) else (if i.val < 6 then (if i.val < 5 then 0 else 1) else (if i.val < 7 then 4 else 20))) : Fin 32)⟩
private def quotientNext (i : Fin 8) (j : Fin 2) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[1,2] else #[0,3]) else (if i.val < 3 then #[4,0] else #[5,1])) else (if i.val < 6 then (if i.val < 5 then #[2,6] else #[3,7]) else (if i.val < 7 then #[7,4] else #[6,5]))) : Array (Fin 8))[j.val]!
private def quotientPrev (i : Fin 8) (j : Fin 2) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[1,2] else #[0,3]) else (if i.val < 3 then #[4,0] else #[5,1])) else (if i.val < 6 then (if i.val < 5 then #[2,6] else #[3,7]) else (if i.val < 7 then #[7,4] else #[6,5]))) : Array (Fin 8))[j.val]!
private def quotientParents (i : Fin 8) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 0 else 1)) else (if i.val < 6 then (if i.val < 5 then 2 else 3) else (if i.val < 7 then 4 else 5))) : Fin 8)
private def quotientLetters (i : Fin 8) : Fin 2 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 1 else 1)) else (if i.val < 6 then (if i.val < 5 then 0 else 0) else (if i.val < 7 then 1 else 1))) : Fin 2)
private def stepWitness (i : Fin 8) (j : Fin 2) : Fin 4 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[3,3] else #[3,3]) else (if i.val < 3 then #[3,2] else #[3,0])) else (if i.val < 6 then (if i.val < 5 then #[3,3] else #[3,3]) else (if i.val < 7 then #[1,0] else #[1,2]))) : Array (Fin 4))[j.val]!
private theorem quotientStep_checked : ∀ i j,
    representatives (quotientNext i j)/(representatives i*generators j)=
      (⟨rows (stepWitness i j)⟩ : Source) := (by decide +kernel)

def cosets : BinaryNormalCosetCertificate generators kernel 8 where
  representatives := representatives
  identity := 0
  identity_mem := by
    have he : representatives 0=(⟨rows 3⟩ : Source) := by decide +kernel
    exact he ▸ row_mem 3
  next := quotientNext
  step_mem := fun i j => (quotientStep_checked i j) ▸ row_mem (stepWitness i j)
  rank i := i.val
  parent i _ := quotientParents i
  letter i _ := quotientLetters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

@[reducible] def state : BinaryNormalState generators where
  kernel := kernel
  normal := normal
  generatorCount := 1
  normalGenerators := normalGenerators
  generated := rfl
  quotientCount := 8
  cardinal := by rw [kernel_card,source_card]
  cosets := cosets
  prev := quotientPrev
  prev_next := (by decide +kernel)

end N3

namespace N4
def normalGenerators (j : Fin 2) : Source := ⟨((if j.val < 1 then 14 else 12) : Fin 32)⟩
def kernel : Subgroup Source := Subgroup.closure (Set.range normalGenerators)
private def rows (i : Fin 4) : Fin 32 := ((if i.val < 2 then (if i.val < 1 then 12 else 14) else (if i.val < 3 then 29 else 31)) : Fin 32)
private def next (i : Fin 4) (j : Fin 2) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[2,3] else #[3,2]) else (if i.val < 3 then #[0,1] else #[1,0])) : Array (Fin 4))[j.val]!
private def rank (i : Fin 4) : ℕ := (if i.val < 2 then (if i.val < 1 then 2 else 1) else (if i.val < 3 then 3 else 0))
private def parents (i : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then 3 else 3) else (if i.val < 3 then 1 else 3)) : Fin 4)
private def letters (i : Fin 4) : Fin 2 := ((if i.val < 2 then (if i.val < 1 then 1 else 0) else (if i.val < 3 then 1 else 0)) : Fin 2)

def normalCertificate : EncodedCayleyCertificate (binaryNormalRowEncoding normalGenerators) 4 where
  rows := rows
  identity := 3
  identity_eq := by decide +kernel
  next := next
  next_eq := (by decide +kernel)
  rank := rank
  parent i _ := parents i
  letter i hi := letters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

theorem normalRows_injective : Function.Injective normalCertificate.rows := by decide +kernel

theorem kernel_card : Nat.card kernel=4 := normalCertificate.card_closure normalRows_injective

theorem row_mem (i : Fin 4) : (⟨rows i⟩ : Source)∈kernel :=
  binaryNormalRow_mem normalCertificate i

private def posWitness (i : Fin 2) (j : Fin 2) : Fin 4 := ((if i.val < 1 then #[1,0] else #[2,0]) : Array (Fin 4))[j.val]!
private def negWitness (i : Fin 2) (j : Fin 2) : Fin 4 := ((if i.val < 1 then #[1,0] else #[2,0]) : Array (Fin 4))[j.val]!
private theorem pos_checked : ∀ i j, generators i*normalGenerators j*(generators i)⁻¹=
    (⟨rows (posWitness i j)⟩ : Source) := by decide +kernel
private theorem neg_checked : ∀ i j, (generators i)⁻¹*normalGenerators j*generators i=
    (⟨rows (negWitness i j)⟩ : Source) := by decide +kernel

instance normal : kernel.Normal := binaryNormal_of_generator_conjugates generators generators_full
  normalGenerators (fun i j => (pos_checked i j) ▸ row_mem (posWitness i j))
  (fun i j => (neg_checked i j) ▸ row_mem (negWitness i j))

private def representatives (i : Fin 8) : Source := ⟨((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 31 else 28) else (if i.val < 3 then 3 else 2)) else (if i.val < 6 then (if i.val < 5 then 5 else 21) else (if i.val < 7 then 8 else 26))) : Fin 32)⟩
private def quotientNext (i : Fin 8) (j : Fin 2) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[1,2] else #[0,3]) else (if i.val < 3 then #[3,4] else #[2,5])) else (if i.val < 6 then (if i.val < 5 then #[5,6] else #[4,7]) else (if i.val < 7 then #[7,0] else #[6,1]))) : Array (Fin 8))[j.val]!
private def quotientPrev (i : Fin 8) (j : Fin 2) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[1,6] else #[0,7]) else (if i.val < 3 then #[3,0] else #[2,1])) else (if i.val < 6 then (if i.val < 5 then #[5,2] else #[4,3]) else (if i.val < 7 then #[7,4] else #[6,5]))) : Array (Fin 8))[j.val]!
private def quotientParents (i : Fin 8) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 0 else 1)) else (if i.val < 6 then (if i.val < 5 then 2 else 3) else (if i.val < 7 then 4 else 5))) : Fin 8)
private def quotientLetters (i : Fin 8) : Fin 2 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 1 else 1)) else (if i.val < 6 then (if i.val < 5 then 1 else 1) else (if i.val < 7 then 1 else 1))) : Fin 2)
private def stepWitness (i : Fin 8) (j : Fin 2) : Fin 4 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[3,3] else #[3,3]) else (if i.val < 3 then #[1,3] else #[1,3])) else (if i.val < 6 then (if i.val < 5 then #[0,3] else #[0,3]) else (if i.val < 7 then #[2,0] else #[2,0]))) : Array (Fin 4))[j.val]!
private theorem quotientStep_checked : ∀ i j,
    representatives (quotientNext i j)/(representatives i*generators j)=
      (⟨rows (stepWitness i j)⟩ : Source) := (by decide +kernel)

def cosets : BinaryNormalCosetCertificate generators kernel 8 where
  representatives := representatives
  identity := 0
  identity_mem := by
    have he : representatives 0=(⟨rows 3⟩ : Source) := by decide +kernel
    exact he ▸ row_mem 3
  next := quotientNext
  step_mem := fun i j => (quotientStep_checked i j) ▸ row_mem (stepWitness i j)
  rank i := i.val
  parent i _ := quotientParents i
  letter i _ := quotientLetters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

@[reducible] def state : BinaryNormalState generators where
  kernel := kernel
  normal := normal
  generatorCount := 2
  normalGenerators := normalGenerators
  generated := rfl
  quotientCount := 8
  cardinal := by rw [kernel_card,source_card]
  cosets := cosets
  prev := quotientPrev
  prev_next := (by decide +kernel)

end N4

namespace N5
def normalGenerators (j : Fin 3) : Source := ⟨((if j.val < 1 then 14 else (if j.val < 2 then 12 else 4)) : Fin 32)⟩
def kernel : Subgroup Source := Subgroup.closure (Set.range normalGenerators)
private def rows (i : Fin 8) : Fin 32 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 4 else 6) else (if i.val < 3 then 12 else 14)) else (if i.val < 6 then (if i.val < 5 then 21 else 23) else (if i.val < 7 then 29 else 31))) : Fin 32)
private def next (i : Fin 8) (j : Fin 3) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[4,5,7] else #[5,4,6]) else (if i.val < 3 then #[6,7,5] else #[7,6,4])) else (if i.val < 6 then (if i.val < 5 then #[0,1,3] else #[1,0,2]) else (if i.val < 7 then #[2,3,1] else #[3,2,0]))) : Array (Fin 8))[j.val]!
private def rank (i : Fin 8) : ℕ := (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 3 else 7) else (if i.val < 3 then 2 else 1)) else (if i.val < 6 then (if i.val < 5 then 5 else 6) else (if i.val < 7 then 4 else 0)))
private def parents (i : Fin 8) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 7 else 6) else (if i.val < 3 then 7 else 7)) else (if i.val < 6 then (if i.val < 5 then 3 else 2) else (if i.val < 7 then 3 else 7))) : Fin 8)
private def letters (i : Fin 8) : Fin 3 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 2 else 2) else (if i.val < 3 then 1 else 0)) else (if i.val < 6 then (if i.val < 5 then 2 else 2) else (if i.val < 7 then 1 else 0))) : Fin 3)

def normalCertificate : EncodedCayleyCertificate (binaryNormalRowEncoding normalGenerators) 8 where
  rows := rows
  identity := 7
  identity_eq := by decide +kernel
  next := next
  next_eq := (by decide +kernel)
  rank := rank
  parent i _ := parents i
  letter i hi := letters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

theorem normalRows_injective : Function.Injective normalCertificate.rows := by decide +kernel

theorem kernel_card : Nat.card kernel=8 := normalCertificate.card_closure normalRows_injective

theorem row_mem (i : Fin 8) : (⟨rows i⟩ : Source)∈kernel :=
  binaryNormalRow_mem normalCertificate i

private def posWitness (i : Fin 2) (j : Fin 3) : Fin 8 := ((if i.val < 1 then #[3,2,5] else #[6,2,1]) : Array (Fin 8))[j.val]!
private def negWitness (i : Fin 2) (j : Fin 3) : Fin 8 := ((if i.val < 1 then #[3,2,5] else #[6,2,4]) : Array (Fin 8))[j.val]!
private theorem pos_checked : ∀ i j, generators i*normalGenerators j*(generators i)⁻¹=
    (⟨rows (posWitness i j)⟩ : Source) := by decide +kernel
private theorem neg_checked : ∀ i j, (generators i)⁻¹*normalGenerators j*generators i=
    (⟨rows (negWitness i j)⟩ : Source) := by decide +kernel

instance normal : kernel.Normal := binaryNormal_of_generator_conjugates generators generators_full
  normalGenerators (fun i j => (pos_checked i j) ▸ row_mem (posWitness i j))
  (fun i j => (neg_checked i j) ▸ row_mem (negWitness i j))

private def representatives (i : Fin 4) : Source := ⟨((if i.val < 2 then (if i.val < 1 then 31 else 28) else (if i.val < 3 then 3 else 2)) : Fin 32)⟩
private def quotientNext (i : Fin 4) (j : Fin 2) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[1,2] else #[0,3]) else (if i.val < 3 then #[3,1] else #[2,0])) : Array (Fin 4))[j.val]!
private def quotientPrev (i : Fin 4) (j : Fin 2) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[1,3] else #[0,2]) else (if i.val < 3 then #[3,0] else #[2,1])) : Array (Fin 4))[j.val]!
private def quotientParents (i : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 0 else 1)) : Fin 4)
private def quotientLetters (i : Fin 4) : Fin 2 := ((if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 1 else 1)) : Fin 2)
private def stepWitness (i : Fin 4) (j : Fin 2) : Fin 8 := ((if i.val < 2 then (if i.val < 1 then #[7,7] else #[7,7]) else (if i.val < 3 then #[3,1] else #[3,4])) : Array (Fin 8))[j.val]!
private theorem quotientStep_checked : ∀ i j,
    representatives (quotientNext i j)/(representatives i*generators j)=
      (⟨rows (stepWitness i j)⟩ : Source) := (by decide +kernel)

def cosets : BinaryNormalCosetCertificate generators kernel 4 where
  representatives := representatives
  identity := 0
  identity_mem := by
    have he : representatives 0=(⟨rows 7⟩ : Source) := by decide +kernel
    exact he ▸ row_mem 7
  next := quotientNext
  step_mem := fun i j => (quotientStep_checked i j) ▸ row_mem (stepWitness i j)
  rank i := i.val
  parent i _ := quotientParents i
  letter i _ := quotientLetters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

@[reducible] def state : BinaryNormalState generators where
  kernel := kernel
  normal := normal
  generatorCount := 3
  normalGenerators := normalGenerators
  generated := rfl
  quotientCount := 4
  cardinal := by rw [kernel_card,source_card]
  cosets := cosets
  prev := quotientPrev
  prev_next := (by decide +kernel)

end N5

namespace N6
def normalGenerators (j : Fin 2) : Source := ⟨((if j.val < 1 then 5 else 14) : Fin 32)⟩
def kernel : Subgroup Source := Subgroup.closure (Set.range normalGenerators)
private def rows (i : Fin 8) : Fin 32 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 5 else 7) else (if i.val < 3 then 12 else 14)) else (if i.val < 6 then (if i.val < 5 then 20 else 22) else (if i.val < 7 then 29 else 31))) : Fin 32)
private def next (i : Fin 8) (j : Fin 2) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[2,4] else #[3,5]) else (if i.val < 3 then #[5,6] else #[4,7])) else (if i.val < 6 then (if i.val < 5 then #[6,0] else #[7,1]) else (if i.val < 7 then #[1,2] else #[0,3]))) : Array (Fin 8))[j.val]!
private def rank (i : Fin 8) : ℕ := (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 1 else 7) else (if i.val < 3 then 3 else 2)) else (if i.val < 6 then (if i.val < 5 then 4 else 5) else (if i.val < 7 then 6 else 0)))
private def parents (i : Fin 8) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 7 else 5) else (if i.val < 3 then 0 else 7)) else (if i.val < 6 then (if i.val < 5 then 0 else 2) else (if i.val < 7 then 2 else 7))) : Fin 8)
private def letters (i : Fin 8) : Fin 2 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 1) else (if i.val < 3 then 0 else 1)) else (if i.val < 6 then (if i.val < 5 then 1 else 0) else (if i.val < 7 then 1 else 0))) : Fin 2)

def normalCertificate : EncodedCayleyCertificate (binaryNormalRowEncoding normalGenerators) 8 where
  rows := rows
  identity := 7
  identity_eq := by decide +kernel
  next := next
  next_eq := (by decide +kernel)
  rank := rank
  parent i _ := parents i
  letter i hi := letters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

theorem normalRows_injective : Function.Injective normalCertificate.rows := by decide +kernel

theorem kernel_card : Nat.card kernel=8 := normalCertificate.card_closure normalRows_injective

theorem row_mem (i : Fin 8) : (⟨rows i⟩ : Source)∈kernel :=
  binaryNormalRow_mem normalCertificate i

private def posWitness (i : Fin 2) (j : Fin 2) : Fin 8 := ((if i.val < 1 then #[5,3] else #[0,6]) : Array (Fin 8))[j.val]!
private def negWitness (i : Fin 2) (j : Fin 2) : Fin 8 := ((if i.val < 1 then #[5,3] else #[0,6]) : Array (Fin 8))[j.val]!
private theorem pos_checked : ∀ i j, generators i*normalGenerators j*(generators i)⁻¹=
    (⟨rows (posWitness i j)⟩ : Source) := by decide +kernel
private theorem neg_checked : ∀ i j, (generators i)⁻¹*normalGenerators j*generators i=
    (⟨rows (negWitness i j)⟩ : Source) := by decide +kernel

instance normal : kernel.Normal := binaryNormal_of_generator_conjugates generators generators_full
  normalGenerators (fun i j => (pos_checked i j) ▸ row_mem (posWitness i j))
  (fun i j => (neg_checked i j) ▸ row_mem (negWitness i j))

private def representatives (i : Fin 4) : Source := ⟨((if i.val < 2 then (if i.val < 1 then 31 else 28) else (if i.val < 3 then 3 else 2)) : Fin 32)⟩
private def quotientNext (i : Fin 4) (j : Fin 2) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[1,2] else #[0,3]) else (if i.val < 3 then #[3,0] else #[2,1])) : Array (Fin 4))[j.val]!
private def quotientPrev (i : Fin 4) (j : Fin 2) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[1,2] else #[0,3]) else (if i.val < 3 then #[3,0] else #[2,1])) : Array (Fin 4))[j.val]!
private def quotientParents (i : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 0 else 1)) : Fin 4)
private def quotientLetters (i : Fin 4) : Fin 2 := ((if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 1 else 1)) : Fin 2)
private def stepWitness (i : Fin 4) (j : Fin 2) : Fin 8 := ((if i.val < 2 then (if i.val < 1 then #[7,7] else #[7,7]) else (if i.val < 3 then #[3,5] else #[3,0])) : Array (Fin 8))[j.val]!
private theorem quotientStep_checked : ∀ i j,
    representatives (quotientNext i j)/(representatives i*generators j)=
      (⟨rows (stepWitness i j)⟩ : Source) := (by decide +kernel)

def cosets : BinaryNormalCosetCertificate generators kernel 4 where
  representatives := representatives
  identity := 0
  identity_mem := by
    have he : representatives 0=(⟨rows 7⟩ : Source) := by decide +kernel
    exact he ▸ row_mem 7
  next := quotientNext
  step_mem := fun i j => (quotientStep_checked i j) ▸ row_mem (stepWitness i j)
  rank i := i.val
  parent i _ := quotientParents i
  letter i _ := quotientLetters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

@[reducible] def state : BinaryNormalState generators where
  kernel := kernel
  normal := normal
  generatorCount := 2
  normalGenerators := normalGenerators
  generated := rfl
  quotientCount := 4
  cardinal := by rw [kernel_card,source_card]
  cosets := cosets
  prev := quotientPrev
  prev_next := (by decide +kernel)

end N6

namespace N7
def normalGenerators (j : Fin 2) : Source := ⟨((if j.val < 1 then 0 else 14) : Fin 32)⟩
def kernel : Subgroup Source := Subgroup.closure (Set.range normalGenerators)
private def rows (i : Fin 16) : Fin 32 := ((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 2) else (if i.val < 3 then 5 else 7)) else (if i.val < 6 then (if i.val < 5 then 9 else 11) else (if i.val < 7 then 12 else 14))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 17 else 19) else (if i.val < 11 then 20 else 22)) else (if i.val < 14 then (if i.val < 13 then 24 else 26) else (if i.val < 15 then 29 else 31)))) : Fin 32)
private def next (i : Fin 16) (j : Fin 2) : Fin 16 := ((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[3,8] else #[11,9]) else (if i.val < 3 then #[5,10] else #[13,11])) else (if i.val < 6 then (if i.val < 5 then #[15,12] else #[7,13]) else (if i.val < 7 then #[9,14] else #[1,15]))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then #[2,0] else #[10,1]) else (if i.val < 11 then #[4,2] else #[12,3])) else (if i.val < 14 then (if i.val < 13 then #[14,4] else #[6,5]) else (if i.val < 15 then #[8,6] else #[0,7])))) : Array (Fin 16))[j.val]!
private def rank (i : Fin 16) : ℕ := (if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 1 else 5) else (if i.val < 3 then 8 else 3)) else (if i.val < 6 then (if i.val < 5 then 15 else 11) else (if i.val < 7 then 10 else 2))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 4 else 9) else (if i.val < 11 then 13 else 7)) else (if i.val < 14 then (if i.val < 13 then 12 else 6) else (if i.val < 15 then 14 else 0))))
private def parents (i : Fin 16) : Fin 16 := ((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 15 else 7) else (if i.val < 3 then 8 else 0)) else (if i.val < 6 then (if i.val < 5 then 12 else 13) else (if i.val < 7 then 13 else 15))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 0 else 1) else (if i.val < 11 then 2 else 3)) else (if i.val < 14 then (if i.val < 13 then 11 else 3) else (if i.val < 15 then 6 else 15)))) : Fin 16)
private def letters (i : Fin 16) : Fin 2 := ((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 0 else 0)) else (if i.val < 6 then (if i.val < 5 then 1 else 1) else (if i.val < 7 then 0 else 1))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 1 else 1) else (if i.val < 11 then 1 else 1)) else (if i.val < 14 then (if i.val < 13 then 0 else 0) else (if i.val < 15 then 1 else 0)))) : Fin 2)

def normalCertificate : EncodedCayleyCertificate (binaryNormalRowEncoding normalGenerators) 16 where
  rows := rows
  identity := 15
  identity_eq := by decide +kernel
  next := next
  next_eq := (by decide +kernel)
  rank := rank
  parent i _ := parents i
  letter i hi := letters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

theorem normalRows_injective : Function.Injective normalCertificate.rows := by decide +kernel

theorem kernel_card : Nat.card kernel=16 := normalCertificate.card_closure normalRows_injective

theorem row_mem (i : Fin 16) : (⟨rows i⟩ : Source)∈kernel :=
  binaryNormalRow_mem normalCertificate i

private def posWitness (i : Fin 2) (j : Fin 2) : Fin 16 := ((if i.val < 1 then #[1,7] else #[8,14]) : Array (Fin 16))[j.val]!
private def negWitness (i : Fin 2) (j : Fin 2) : Fin 16 := ((if i.val < 1 then #[1,7] else #[1,14]) : Array (Fin 16))[j.val]!
private theorem pos_checked : ∀ i j, generators i*normalGenerators j*(generators i)⁻¹=
    (⟨rows (posWitness i j)⟩ : Source) := by decide +kernel
private theorem neg_checked : ∀ i j, (generators i)⁻¹*normalGenerators j*generators i=
    (⟨rows (negWitness i j)⟩ : Source) := by decide +kernel

instance normal : kernel.Normal := binaryNormal_of_generator_conjugates generators generators_full
  normalGenerators (fun i j => (pos_checked i j) ▸ row_mem (posWitness i j))
  (fun i j => (neg_checked i j) ▸ row_mem (negWitness i j))

private def representatives (i : Fin 2) : Source := ⟨((if i.val < 1 then 31 else 28) : Fin 32)⟩
private def quotientNext (i : Fin 2) (j : Fin 2) : Fin 2 := ((if i.val < 1 then #[1,1] else #[0,0]) : Array (Fin 2))[j.val]!
private def quotientPrev (i : Fin 2) (j : Fin 2) : Fin 2 := ((if i.val < 1 then #[1,1] else #[0,0]) : Array (Fin 2))[j.val]!
private def quotientParents (i : Fin 2) : Fin 2 := ((if i.val < 1 then 0 else 0) : Fin 2)
private def quotientLetters (i : Fin 2) : Fin 2 := ((if i.val < 1 then 0 else 0) : Fin 2)
private def stepWitness (i : Fin 2) (j : Fin 2) : Fin 16 := ((if i.val < 1 then #[15,4] else #[15,12]) : Array (Fin 16))[j.val]!
private theorem quotientStep_checked : ∀ i j,
    representatives (quotientNext i j)/(representatives i*generators j)=
      (⟨rows (stepWitness i j)⟩ : Source) := (by decide +kernel)

def cosets : BinaryNormalCosetCertificate generators kernel 2 where
  representatives := representatives
  identity := 0
  identity_mem := by
    have he : representatives 0=(⟨rows 15⟩ : Source) := by decide +kernel
    exact he ▸ row_mem 15
  next := quotientNext
  step_mem := fun i j => (quotientStep_checked i j) ▸ row_mem (stepWitness i j)
  rank i := i.val
  parent i _ := quotientParents i
  letter i _ := quotientLetters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

@[reducible] def state : BinaryNormalState generators where
  kernel := kernel
  normal := normal
  generatorCount := 2
  normalGenerators := normalGenerators
  generated := rfl
  quotientCount := 2
  cardinal := by rw [kernel_card,source_card]
  cosets := cosets
  prev := quotientPrev
  prev_next := (by decide +kernel)

end N7

namespace N8
def normalGenerators (j : Fin 2) : Source := ⟨((if j.val < 1 then 3 else 14) : Fin 32)⟩
def kernel : Subgroup Source := Subgroup.closure (Set.range normalGenerators)
private def rows (i : Fin 16) : Fin 32 := ((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 1 else 3) else (if i.val < 3 then 5 else 7)) else (if i.val < 6 then (if i.val < 5 then 8 else 10) else (if i.val < 7 then 12 else 14))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 16 else 18) else (if i.val < 11 then 20 else 22)) else (if i.val < 14 then (if i.val < 13 then 25 else 27) else (if i.val < 15 then 29 else 31)))) : Fin 32)
private def next (i : Fin 16) (j : Fin 2) : Fin 16 := ((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[10,8] else #[2,9]) else (if i.val < 3 then #[4,10] else #[12,11])) else (if i.val < 6 then (if i.val < 5 then #[6,12] else #[14,13]) else (if i.val < 7 then #[8,14] else #[0,15]))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then #[11,0] else #[3,1]) else (if i.val < 11 then #[5,2] else #[13,3])) else (if i.val < 14 then (if i.val < 13 then #[7,4] else #[15,5]) else (if i.val < 15 then #[9,6] else #[1,7])))) : Array (Fin 16))[j.val]!
private def rank (i : Fin 16) : ℕ := (if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 5 else 1) else (if i.val < 3 then 3 else 8)) else (if i.val < 6 then (if i.val < 5 then 6 else 12) else (if i.val < 7 then 10 else 2))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 9 else 4) else (if i.val < 11 then 7 else 13)) else (if i.val < 14 then (if i.val < 13 then 11 else 15) else (if i.val < 15 then 14 else 0))))
private def parents (i : Fin 16) : Fin 16 := ((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 7 else 15) else (if i.val < 3 then 1 else 9)) else (if i.val < 6 then (if i.val < 5 then 2 else 10) else (if i.val < 7 then 4 else 15))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 0 else 1) else (if i.val < 11 then 2 else 3)) else (if i.val < 14 then (if i.val < 13 then 4 else 5) else (if i.val < 15 then 6 else 15)))) : Fin 16)
private def letters (i : Fin 16) : Fin 2 := ((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 0 else 0)) else (if i.val < 6 then (if i.val < 5 then 0 else 0) else (if i.val < 7 then 0 else 1))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 1 else 1) else (if i.val < 11 then 1 else 1)) else (if i.val < 14 then (if i.val < 13 then 1 else 1) else (if i.val < 15 then 1 else 0)))) : Fin 2)

def normalCertificate : EncodedCayleyCertificate (binaryNormalRowEncoding normalGenerators) 16 where
  rows := rows
  identity := 15
  identity_eq := by decide +kernel
  next := next
  next_eq := (by decide +kernel)
  rank := rank
  parent i _ := parents i
  letter i hi := letters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

theorem normalRows_injective : Function.Injective normalCertificate.rows := by decide +kernel

theorem kernel_card : Nat.card kernel=16 := normalCertificate.card_closure normalRows_injective

theorem row_mem (i : Fin 16) : (⟨rows i⟩ : Source)∈kernel :=
  binaryNormalRow_mem normalCertificate i

private def posWitness (i : Fin 2) (j : Fin 2) : Fin 16 := ((if i.val < 1 then #[0,7] else #[1,14]) : Array (Fin 16))[j.val]!
private def negWitness (i : Fin 2) (j : Fin 2) : Fin 16 := ((if i.val < 1 then #[0,7] else #[1,14]) : Array (Fin 16))[j.val]!
private theorem pos_checked : ∀ i j, generators i*normalGenerators j*(generators i)⁻¹=
    (⟨rows (posWitness i j)⟩ : Source) := by decide +kernel
private theorem neg_checked : ∀ i j, (generators i)⁻¹*normalGenerators j*generators i=
    (⟨rows (negWitness i j)⟩ : Source) := by decide +kernel

instance normal : kernel.Normal := binaryNormal_of_generator_conjugates generators generators_full
  normalGenerators (fun i j => (pos_checked i j) ▸ row_mem (posWitness i j))
  (fun i j => (neg_checked i j) ▸ row_mem (negWitness i j))

private def representatives (i : Fin 2) : Source := ⟨((if i.val < 1 then 31 else 28) : Fin 32)⟩
private def quotientNext (i : Fin 2) (j : Fin 2) : Fin 2 := ((if i.val < 1 then #[1,0] else #[0,1]) : Array (Fin 2))[j.val]!
private def quotientPrev (i : Fin 2) (j : Fin 2) : Fin 2 := ((if i.val < 1 then #[1,0] else #[0,1]) : Array (Fin 2))[j.val]!
private def quotientParents (i : Fin 2) : Fin 2 := ((if i.val < 1 then 0 else 0) : Fin 2)
private def quotientLetters (i : Fin 2) : Fin 2 := ((if i.val < 1 then 0 else 0) : Fin 2)
private def stepWitness (i : Fin 2) (j : Fin 2) : Fin 16 := ((if i.val < 1 then #[15,13] else #[15,5]) : Array (Fin 16))[j.val]!
private theorem quotientStep_checked : ∀ i j,
    representatives (quotientNext i j)/(representatives i*generators j)=
      (⟨rows (stepWitness i j)⟩ : Source) := (by decide +kernel)

def cosets : BinaryNormalCosetCertificate generators kernel 2 where
  representatives := representatives
  identity := 0
  identity_mem := by
    have he : representatives 0=(⟨rows 15⟩ : Source) := by decide +kernel
    exact he ▸ row_mem 15
  next := quotientNext
  step_mem := fun i j => (quotientStep_checked i j) ▸ row_mem (stepWitness i j)
  rank i := i.val
  parent i _ := quotientParents i
  letter i _ := quotientLetters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

@[reducible] def state : BinaryNormalState generators where
  kernel := kernel
  normal := normal
  generatorCount := 2
  normalGenerators := normalGenerators
  generated := rfl
  quotientCount := 2
  cardinal := by rw [kernel_card,source_card]
  cosets := cosets
  prev := quotientPrev
  prev_next := (by decide +kernel)

end N8

namespace N9
def normalGenerators (j : Fin 3) : Source := ⟨((if j.val < 1 then 13 else (if j.val < 2 then 28 else 15)) : Fin 32)⟩
def kernel : Subgroup Source := Subgroup.closure (Set.range normalGenerators)
private def rows (i : Fin 8) : Fin 32 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 12 else 13) else (if i.val < 3 then 14 else 15)) else (if i.val < 6 then (if i.val < 5 then 28 else 29) else (if i.val < 7 then 30 else 31))) : Fin 32)
private def next (i : Fin 8) (j : Fin 3) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[6,3,4] else #[7,2,5]) else (if i.val < 3 then #[4,1,6] else #[5,0,7])) else (if i.val < 6 then (if i.val < 5 then #[2,7,0] else #[3,6,1]) else (if i.val < 7 then #[0,5,2] else #[1,4,3]))) : Array (Fin 8))[j.val]!
private def rank (i : Fin 8) : ℕ := (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 6 else 1) else (if i.val < 3 then 4 else 3)) else (if i.val < 6 then (if i.val < 5 then 2 else 5) else (if i.val < 7 then 7 else 0)))
private def parents (i : Fin 8) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 4 else 7) else (if i.val < 3 then 1 else 7)) else (if i.val < 6 then (if i.val < 5 then 7 else 1) else (if i.val < 7 then 2 else 7))) : Fin 8)
private def letters (i : Fin 8) : Fin 3 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 2 else 0) else (if i.val < 3 then 1 else 2)) else (if i.val < 6 then (if i.val < 5 then 1 else 2) else (if i.val < 7 then 2 else 0))) : Fin 3)

def normalCertificate : EncodedCayleyCertificate (binaryNormalRowEncoding normalGenerators) 8 where
  rows := rows
  identity := 7
  identity_eq := by decide +kernel
  next := next
  next_eq := (by decide +kernel)
  rank := rank
  parent i _ := parents i
  letter i hi := letters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

theorem normalRows_injective : Function.Injective normalCertificate.rows := by decide +kernel

theorem kernel_card : Nat.card kernel=8 := normalCertificate.card_closure normalRows_injective

theorem row_mem (i : Fin 8) : (⟨rows i⟩ : Source)∈kernel :=
  binaryNormalRow_mem normalCertificate i

private def posWitness (i : Fin 2) (j : Fin 3) : Fin 8 := ((if i.val < 1 then #[1,4,3] else #[3,1,6]) : Array (Fin 8))[j.val]!
private def negWitness (i : Fin 2) (j : Fin 3) : Fin 8 := ((if i.val < 1 then #[1,4,3] else #[4,6,1]) : Array (Fin 8))[j.val]!
private theorem pos_checked : ∀ i j, generators i*normalGenerators j*(generators i)⁻¹=
    (⟨rows (posWitness i j)⟩ : Source) := by decide +kernel
private theorem neg_checked : ∀ i j, (generators i)⁻¹*normalGenerators j*generators i=
    (⟨rows (negWitness i j)⟩ : Source) := by decide +kernel

instance normal : kernel.Normal := binaryNormal_of_generator_conjugates generators generators_full
  normalGenerators (fun i j => (pos_checked i j) ▸ row_mem (posWitness i j))
  (fun i j => (neg_checked i j) ▸ row_mem (negWitness i j))

private def representatives (i : Fin 4) : Source := ⟨((if i.val < 2 then (if i.val < 1 then 31 else 3) else (if i.val < 3 then 5 else 8)) : Fin 32)⟩
private def quotientNext (i : Fin 4) (j : Fin 2) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[0,1] else #[1,2]) else (if i.val < 3 then #[2,3] else #[3,0])) : Array (Fin 4))[j.val]!
private def quotientPrev (i : Fin 4) (j : Fin 2) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[0,3] else #[1,0]) else (if i.val < 3 then #[2,1] else #[3,2])) : Array (Fin 4))[j.val]!
private def quotientParents (i : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 1 else 2)) : Fin 4)
private def quotientLetters (i : Fin 4) : Fin 2 := ((if i.val < 2 then (if i.val < 1 then 0 else 1) else (if i.val < 3 then 1 else 1)) : Fin 2)
private def stepWitness (i : Fin 4) (j : Fin 2) : Fin 8 := ((if i.val < 2 then (if i.val < 1 then #[4,7] else #[1,7]) else (if i.val < 3 then #[3,7] else #[6,0])) : Array (Fin 8))[j.val]!
private theorem quotientStep_checked : ∀ i j,
    representatives (quotientNext i j)/(representatives i*generators j)=
      (⟨rows (stepWitness i j)⟩ : Source) := (by decide +kernel)

def cosets : BinaryNormalCosetCertificate generators kernel 4 where
  representatives := representatives
  identity := 0
  identity_mem := by
    have he : representatives 0=(⟨rows 7⟩ : Source) := by decide +kernel
    exact he ▸ row_mem 7
  next := quotientNext
  step_mem := fun i j => (quotientStep_checked i j) ▸ row_mem (stepWitness i j)
  rank i := i.val
  parent i _ := quotientParents i
  letter i _ := quotientLetters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

@[reducible] def state : BinaryNormalState generators where
  kernel := kernel
  normal := normal
  generatorCount := 3
  normalGenerators := normalGenerators
  generated := rfl
  quotientCount := 4
  cardinal := by rw [kernel_card,source_card]
  cosets := cosets
  prev := quotientPrev
  prev_next := (by decide +kernel)

end N9

namespace N10
def normalGenerators (j : Fin 4) : Source := ⟨((if j.val < 2 then (if j.val < 1 then 5 else 13) else (if j.val < 3 then 28 else 15)) : Fin 32)⟩
def kernel : Subgroup Source := Subgroup.closure (Set.range normalGenerators)
private def rows (i : Fin 16) : Fin 32 := ((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 4 else 5) else (if i.val < 3 then 6 else 7)) else (if i.val < 6 then (if i.val < 5 then 12 else 13) else (if i.val < 7 then 14 else 15))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 20 else 21) else (if i.val < 11 then 22 else 23)) else (if i.val < 14 then (if i.val < 13 then 28 else 29) else (if i.val < 15 then 30 else 31)))) : Fin 32)
private def next (i : Fin 16) (j : Fin 4) : Fin 16 := ((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[14,10,3,8] else #[4,11,2,9]) else (if i.val < 3 then #[12,8,1,10] else #[6,9,0,11])) else (if i.val < 6 then (if i.val < 5 then #[10,14,7,12] else #[0,15,6,13]) else (if i.val < 7 then #[8,12,5,14] else #[2,13,4,15]))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then #[13,2,11,0] else #[7,3,10,1]) else (if i.val < 11 then #[15,0,9,2] else #[5,1,8,3])) else (if i.val < 14 then (if i.val < 13 then #[9,6,15,4] else #[3,7,14,5]) else (if i.val < 15 then #[11,4,13,6] else #[1,5,12,7])))) : Array (Fin 16))[j.val]!
private def rank (i : Fin 16) : ℕ := (if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 9 else 1) else (if i.val < 3 then 7 else 15)) else (if i.val < 6 then (if i.val < 5 then 5 else 2) else (if i.val < 7 then 10 else 4))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 14 else 8) else (if i.val < 11 then 12 else 6)) else (if i.val < 14 then (if i.val < 13 then 3 else 11) else (if i.val < 15 then 13 else 0))))
private def parents (i : Fin 16) : Fin 16 := ((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 5 else 15) else (if i.val < 3 then 1 else 11)) else (if i.val < 6 then (if i.val < 5 then 1 else 15) else (if i.val < 7 then 5 else 15))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 11 else 1) else (if i.val < 11 then 4 else 1)) else (if i.val < 14 then (if i.val < 13 then 15 else 5) else (if i.val < 15 then 4 else 15)))) : Fin 16)
private def letters (i : Fin 16) : Fin 4 := ((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 2 else 3)) else (if i.val < 6 then (if i.val < 5 then 0 else 1) else (if i.val < 7 then 2 else 3))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 2 else 3) else (if i.val < 11 then 0 else 1)) else (if i.val < 14 then (if i.val < 13 then 2 else 3) else (if i.val < 15 then 1 else 0)))) : Fin 4)

def normalCertificate : EncodedCayleyCertificate (binaryNormalRowEncoding normalGenerators) 16 where
  rows := rows
  identity := 15
  identity_eq := by decide +kernel
  next := next
  next_eq := (by decide +kernel)
  rank := rank
  parent i _ := parents i
  letter i hi := letters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

theorem normalRows_injective : Function.Injective normalCertificate.rows := by decide +kernel

theorem kernel_card : Nat.card kernel=16 := normalCertificate.card_closure normalRows_injective

theorem row_mem (i : Fin 16) : (⟨rows i⟩ : Source)∈kernel :=
  binaryNormalRow_mem normalCertificate i

private def posWitness (i : Fin 2) (j : Fin 4) : Fin 16 := ((if i.val < 1 then #[10,5,12,7] else #[1,7,5,14]) : Array (Fin 16))[j.val]!
private def negWitness (i : Fin 2) (j : Fin 4) : Fin 16 := ((if i.val < 1 then #[10,5,12,7] else #[1,12,14,5]) : Array (Fin 16))[j.val]!
private theorem pos_checked : ∀ i j, generators i*normalGenerators j*(generators i)⁻¹=
    (⟨rows (posWitness i j)⟩ : Source) := by decide +kernel
private theorem neg_checked : ∀ i j, (generators i)⁻¹*normalGenerators j*generators i=
    (⟨rows (negWitness i j)⟩ : Source) := by decide +kernel

instance normal : kernel.Normal := binaryNormal_of_generator_conjugates generators generators_full
  normalGenerators (fun i j => (pos_checked i j) ▸ row_mem (posWitness i j))
  (fun i j => (neg_checked i j) ▸ row_mem (negWitness i j))

private def representatives (i : Fin 2) : Source := ⟨((if i.val < 1 then 31 else 3) : Fin 32)⟩
private def quotientNext (i : Fin 2) (j : Fin 2) : Fin 2 := ((if i.val < 1 then #[0,1] else #[1,0]) : Array (Fin 2))[j.val]!
private def quotientPrev (i : Fin 2) (j : Fin 2) : Fin 2 := ((if i.val < 1 then #[0,1] else #[1,0]) : Array (Fin 2))[j.val]!
private def quotientParents (i : Fin 2) : Fin 2 := ((if i.val < 1 then 0 else 0) : Fin 2)
private def quotientLetters (i : Fin 2) : Fin 2 := ((if i.val < 1 then 0 else 1) : Fin 2)
private def stepWitness (i : Fin 2) (j : Fin 2) : Fin 16 := ((if i.val < 1 then #[12,15] else #[5,10]) : Array (Fin 16))[j.val]!
private theorem quotientStep_checked : ∀ i j,
    representatives (quotientNext i j)/(representatives i*generators j)=
      (⟨rows (stepWitness i j)⟩ : Source) := (by decide +kernel)

def cosets : BinaryNormalCosetCertificate generators kernel 2 where
  representatives := representatives
  identity := 0
  identity_mem := by
    have he : representatives 0=(⟨rows 15⟩ : Source) := by decide +kernel
    exact he ▸ row_mem 15
  next := quotientNext
  step_mem := fun i j => (quotientStep_checked i j) ▸ row_mem (stepWitness i j)
  rank i := i.val
  parent i _ := quotientParents i
  letter i _ := quotientLetters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

@[reducible] def state : BinaryNormalState generators where
  kernel := kernel
  normal := normal
  generatorCount := 4
  normalGenerators := normalGenerators
  generated := rfl
  quotientCount := 2
  cardinal := by rw [kernel_card,source_card]
  cosets := cosets
  prev := quotientPrev
  prev_next := (by decide +kernel)

end N10

namespace N11
def normalGenerators (j : Fin 2) : Source := ⟨((if j.val < 1 then 3 else 28) : Fin 32)⟩
def kernel : Subgroup Source := Subgroup.closure (Set.range normalGenerators)
private def rows (i : Fin 32) : Fin 32 := ((if i.val < 16 then (if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 1) else (if i.val < 3 then 2 else 3)) else (if i.val < 6 then (if i.val < 5 then 4 else 5) else (if i.val < 7 then 6 else 7))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 8 else 9) else (if i.val < 11 then 10 else 11)) else (if i.val < 14 then (if i.val < 13 then 12 else 13) else (if i.val < 15 then 14 else 15)))) else (if i.val < 24 then (if i.val < 20 then (if i.val < 18 then (if i.val < 17 then 16 else 17) else (if i.val < 19 then 18 else 19)) else (if i.val < 22 then (if i.val < 21 then 20 else 21) else (if i.val < 23 then 22 else 23))) else (if i.val < 28 then (if i.val < 26 then (if i.val < 25 then 24 else 25) else (if i.val < 27 then 26 else 27)) else (if i.val < 30 then (if i.val < 29 then 28 else 29) else (if i.val < 31 then 30 else 31))))) : Fin 32)
private def next (i : Fin 32) (j : Fin 2) : Fin 32 := ((if i.val < 16 then (if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[4,3] else #[20,2]) else (if i.val < 3 then #[21,1] else #[5,0])) else (if i.val < 6 then (if i.val < 5 then #[24,7] else #[8,6]) else (if i.val < 7 then #[9,5] else #[25,4]))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then #[12,11] else #[28,10]) else (if i.val < 11 then #[29,9] else #[13,8])) else (if i.val < 14 then (if i.val < 13 then #[16,15] else #[0,14]) else (if i.val < 15 then #[1,13] else #[17,12])))) else (if i.val < 24 then (if i.val < 20 then (if i.val < 18 then (if i.val < 17 then #[22,19] else #[6,18]) else (if i.val < 19 then #[7,17] else #[23,16])) else (if i.val < 22 then (if i.val < 21 then #[10,23] else #[26,22]) else (if i.val < 23 then #[27,21] else #[11,20]))) else (if i.val < 28 then (if i.val < 26 then (if i.val < 25 then #[30,27] else #[14,26]) else (if i.val < 27 then #[15,25] else #[31,24])) else (if i.val < 30 then (if i.val < 29 then #[2,31] else #[18,30]) else (if i.val < 31 then #[19,29] else #[3,28]))))) : Array (Fin 32))[j.val]!
private def rank (i : Fin 32) : ℕ := (if i.val < 16 then (if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 4 else 10) else (if i.val < 3 then 5 else 1)) else (if i.val < 6 then (if i.val < 5 then 8 else 3) else (if i.val < 7 then 7 else 15))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 6 else 13) else (if i.val < 11 then 22 else 12)) else (if i.val < 14 then (if i.val < 13 then 11 else 21) else (if i.val < 15 then 29 else 20)))) else (if i.val < 24 then (if i.val < 20 then (if i.val < 18 then (if i.val < 17 then 19 else 28) else (if i.val < 19 then 31 else 27)) else (if i.val < 22 then (if i.val < 21 then 18 else 9) else (if i.val < 23 then 17 else 26))) else (if i.val < 28 then (if i.val < 26 then (if i.val < 25 then 14 else 25) else (if i.val < 27 then 16 else 24)) else (if i.val < 30 then (if i.val < 29 then 2 else 30) else (if i.val < 31 then 23 else 0)))))
private def parents (i : Fin 32) : Fin 32 := ((if i.val < 16 then (if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 3 else 2) else (if i.val < 3 then 28 else 31)) else (if i.val < 6 then (if i.val < 5 then 0 else 3) else (if i.val < 7 then 5 else 4))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 5 else 6) else (if i.val < 11 then 9 else 8)) else (if i.val < 14 then (if i.val < 13 then 8 else 11) else (if i.val < 15 then 13 else 12)))) else (if i.val < 24 then (if i.val < 20 then (if i.val < 18 then (if i.val < 17 then 12 else 15) else (if i.val < 19 then 17 else 16)) else (if i.val < 22 then (if i.val < 21 then 1 else 2) else (if i.val < 23 then 21 else 20))) else (if i.val < 28 then (if i.val < 26 then (if i.val < 25 then 4 else 7) else (if i.val < 27 then 21 else 24)) else (if i.val < 30 then (if i.val < 29 then 31 else 10) else (if i.val < 31 then 24 else 31))))) : Fin 32)
private def letters (i : Fin 32) : Fin 2 := ((if i.val < 16 then (if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 1 else 1) else (if i.val < 3 then 0 else 0)) else (if i.val < 6 then (if i.val < 5 then 0 else 0) else (if i.val < 7 then 1 else 1))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 0 else 0) else (if i.val < 11 then 1 else 1)) else (if i.val < 14 then (if i.val < 13 then 0 else 0) else (if i.val < 15 then 1 else 1)))) else (if i.val < 24 then (if i.val < 20 then (if i.val < 18 then (if i.val < 17 then 0 else 0) else (if i.val < 19 then 1 else 1)) else (if i.val < 22 then (if i.val < 21 then 0 else 0) else (if i.val < 23 then 1 else 1))) else (if i.val < 28 then (if i.val < 26 then (if i.val < 25 then 0 else 0) else (if i.val < 27 then 0 else 1)) else (if i.val < 30 then (if i.val < 29 then 1 else 0) else (if i.val < 31 then 0 else 0))))) : Fin 2)

def normalCertificate : EncodedCayleyCertificate (binaryNormalRowEncoding normalGenerators) 32 where
  rows := rows
  identity := 31
  identity_eq := by decide +kernel
  next := next
  next_eq := (Fin.addCases (m := 16) (n := 16) (by decide +kernel) (by decide +kernel))
  rank := rank
  parent i _ := parents i
  letter i hi := letters i
  parent_lt := (Fin.addCases (m := 16) (n := 16) (by decide +kernel) (by decide +kernel))
  parent_next := (Fin.addCases (m := 16) (n := 16) (by decide +kernel) (by decide +kernel))

theorem normalRows_injective : Function.Injective normalCertificate.rows := by decide +kernel

theorem kernel_card : Nat.card kernel=32 := normalCertificate.card_closure normalRows_injective

theorem row_mem (i : Fin 32) : (⟨rows i⟩ : Source)∈kernel :=
  binaryNormalRow_mem normalCertificate i

private def posWitness (i : Fin 2) (j : Fin 2) : Fin 32 := ((if i.val < 1 then #[1,28] else #[3,13]) : Array (Fin 32))[j.val]!
private def negWitness (i : Fin 2) (j : Fin 2) : Fin 32 := ((if i.val < 1 then #[1,28] else #[3,30]) : Array (Fin 32))[j.val]!
private theorem pos_checked : ∀ i j, generators i*normalGenerators j*(generators i)⁻¹=
    (⟨rows (posWitness i j)⟩ : Source) := by decide +kernel
private theorem neg_checked : ∀ i j, (generators i)⁻¹*normalGenerators j*generators i=
    (⟨rows (negWitness i j)⟩ : Source) := by decide +kernel

instance normal : kernel.Normal := binaryNormal_of_generator_conjugates generators generators_full
  normalGenerators (fun i j => (pos_checked i j) ▸ row_mem (posWitness i j))
  (fun i j => (neg_checked i j) ▸ row_mem (negWitness i j))

private def representatives (i : Fin 1) : Source := ⟨(31 : Fin 32)⟩
private def quotientNext (i : Fin 1) (j : Fin 2) : Fin 1 := (#[0,0] : Array (Fin 1))[j.val]!
private def quotientPrev (i : Fin 1) (j : Fin 2) : Fin 1 := (#[0,0] : Array (Fin 1))[j.val]!
private def quotientParents (i : Fin 1) : Fin 1 := (0 : Fin 1)
private def quotientLetters (i : Fin 1) : Fin 2 := (0 : Fin 2)
private def stepWitness (i : Fin 1) (j : Fin 2) : Fin 32 := (#[28,27] : Array (Fin 32))[j.val]!
private theorem quotientStep_checked : ∀ i j,
    representatives (quotientNext i j)/(representatives i*generators j)=
      (⟨rows (stepWitness i j)⟩ : Source) := (by decide +kernel)

def cosets : BinaryNormalCosetCertificate generators kernel 1 where
  representatives := representatives
  identity := 0
  identity_mem := by
    have he : representatives 0=(⟨rows 31⟩ : Source) := by decide +kernel
    exact he ▸ row_mem 31
  next := quotientNext
  step_mem := fun i j => (quotientStep_checked i j) ▸ row_mem (stepWitness i j)
  rank i := i.val
  parent i _ := quotientParents i
  letter i _ := quotientLetters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

@[reducible] def state : BinaryNormalState generators where
  kernel := kernel
  normal := normal
  generatorCount := 2
  normalGenerators := normalGenerators
  generated := rfl
  quotientCount := 1
  cardinal := by rw [kernel_card,source_card]
  cosets := cosets
  prev := quotientPrev
  prev_next := (by decide +kernel)

end N11

@[reducible] def states (i : Fin 12) : BinaryNormalState generators :=
  (if i.val < 6 then (if i.val < 3 then (if i.val < 1 then N0.state else (if i.val < 2 then N1.state else N2.state)) else (if i.val < 4 then N3.state else (if i.val < 5 then N4.state else N5.state))) else (if i.val < 9 then (if i.val < 7 then N6.state else (if i.val < 8 then N7.state else N8.state)) else (if i.val < 10 then N9.state else (if i.val < 11 then N10.state else N11.state))))

end SymmetricSubgroupAsymptotics.BinaryNormal8T16
