import SymmetricSubgroupAsymptotics.BinaryNormalGeneratorChecks
import SymmetricSubgroupAsymptotics.BinaryMenuCayley8T9

/-! Exact original normal states and quotient rows for 8T9.
Generated by export_lean_normal_registry.py; all finite facts are checked
in Lean's kernel. This file certifies normal-state coverage, not the later
pair/character/transport acceptance of those states. -/

set_option autoImplicit false
set_option maxRecDepth 100000
set_option maxHeartbeats 0
set_option linter.unusedVariables false
noncomputable section
namespace SymmetricSubgroupAsymptotics.BinaryNormal8T9

abbrev Source := FiniteGroupRow 16
local instance : Group Source := BinaryMenuCayley8T9.group

def generators (j : Fin 4) : Source :=
  ⟨BinaryMenuCayley8T9.certificate.next BinaryMenuCayley8T9.certificate.identity j⟩

theorem generators_full : Subgroup.closure (Set.range generators)=⊤ := by
  apply binaryNormal_full_generators_of_equiv BinaryMenuCayley8T9.generators
    generators BinaryMenuCayley8T9.originalEquiv
  intro j
  change BinaryMenuCayley8T9.certificate.toCayley.elements
    (BinaryMenuCayley8T9.certificate.toCayley.next
      BinaryMenuCayley8T9.certificate.toCayley.identity j)=_
  rw [FiniteCayleyCertificate.next_eq,FiniteCayleyCertificate.identity_eq,one_mul]

theorem source_card : Nat.card Source=16 := by
  rw [Nat.card_eq_fintype_card]
  rfl

namespace N0
def normalGenerators (j : Fin 0) : Source := Fin.elim0 j
def kernel : Subgroup Source := Subgroup.closure (Set.range normalGenerators)
private def rows (i : Fin 1) : Fin 16 := (15 : Fin 16)
private def next (i : Fin 1) (j : Fin 0) : Fin 1 := Fin.elim0 j
private def rank (i : Fin 1) : ℕ := 0
private def parents (i : Fin 1) : Fin 1 := (0 : Fin 1)

def normalCertificate : EncodedCayleyCertificate (binaryNormalRowEncoding normalGenerators) 1 where
  rows := rows
  identity := 0
  identity_eq := by decide +kernel
  next := next
  next_eq := (by decide +kernel)
  rank := rank
  parent i _ := parents i
  letter i hi := False.elim (hi (Subsingleton.elim i (0 : Fin 1)))
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

theorem normalRows_injective : Function.Injective normalCertificate.rows := by decide +kernel

theorem kernel_card : Nat.card kernel=1 := normalCertificate.card_closure normalRows_injective

theorem row_mem (i : Fin 1) : (⟨rows i⟩ : Source)∈kernel :=
  binaryNormalRow_mem normalCertificate i

instance normal : kernel.Normal := binaryNormal_of_generator_conjugates generators generators_full
  normalGenerators (fun _ j => Fin.elim0 j) (fun _ j => Fin.elim0 j)

private def representatives (i : Fin 16) : Source := ⟨((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 15 else 0) else (if i.val < 3 then 3 else 7)) else (if i.val < 6 then (if i.val < 5 then 14 else 4) else (if i.val < 7 then 8 else 1))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 10 else 2) else (if i.val < 11 then 6 else 9)) else (if i.val < 14 then (if i.val < 13 then 13 else 5) else (if i.val < 15 then 11 else 12)))) : Fin 16)⟩
private def quotientNext (i : Fin 16) (j : Fin 4) : Fin 16 := ((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[1,2,3,4] else #[0,5,6,7]) else (if i.val < 3 then #[5,0,8,9] else #[6,8,0,10])) else (if i.val < 6 then (if i.val < 5 then #[7,9,11,0] else #[2,1,12,13]) else (if i.val < 7 then #[3,12,1,11] else #[4,13,10,1]))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then #[12,3,2,14] else #[13,4,15,2]) else (if i.val < 11 then #[11,14,7,3] else #[10,15,4,6])) else (if i.val < 14 then (if i.val < 13 then #[8,6,5,15] else #[9,7,14,5]) else (if i.val < 15 then #[15,10,13,8] else #[14,11,9,12])))) : Array (Fin 16))[j.val]!
private def quotientPrev (i : Fin 16) (j : Fin 4) : Fin 16 := ((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[1,2,3,4] else #[0,5,6,7]) else (if i.val < 3 then #[5,0,8,9] else #[6,8,0,10])) else (if i.val < 6 then (if i.val < 5 then #[7,9,11,0] else #[2,1,12,13]) else (if i.val < 7 then #[3,12,1,11] else #[4,13,10,1]))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then #[12,3,2,14] else #[13,4,15,2]) else (if i.val < 11 then #[11,14,7,3] else #[10,15,4,6])) else (if i.val < 14 then (if i.val < 13 then #[8,6,5,15] else #[9,7,14,5]) else (if i.val < 15 then #[15,10,13,8] else #[14,11,9,12])))) : Array (Fin 16))[j.val]!
private def quotientParents (i : Fin 16) : Fin 16 := ((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 0 else 0)) else (if i.val < 6 then (if i.val < 5 then 0 else 1) else (if i.val < 7 then 1 else 1))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 2 else 2) else (if i.val < 11 then 3 else 4)) else (if i.val < 14 then (if i.val < 13 then 5 else 5) else (if i.val < 15 then 8 else 9)))) : Fin 16)
private def quotientLetters (i : Fin 16) : Fin 4 := ((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 1 else 2)) else (if i.val < 6 then (if i.val < 5 then 3 else 1) else (if i.val < 7 then 2 else 3))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 2 else 3) else (if i.val < 11 then 3 else 2)) else (if i.val < 14 then (if i.val < 13 then 2 else 3) else (if i.val < 15 then 3 else 2)))) : Fin 4)
private def stepWitness (i : Fin 16) (j : Fin 4) : Fin 1 := ((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[0,0,0,0] else #[0,0,0,0]) else (if i.val < 3 then #[0,0,0,0] else #[0,0,0,0])) else (if i.val < 6 then (if i.val < 5 then #[0,0,0,0] else #[0,0,0,0]) else (if i.val < 7 then #[0,0,0,0] else #[0,0,0,0]))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then #[0,0,0,0] else #[0,0,0,0]) else (if i.val < 11 then #[0,0,0,0] else #[0,0,0,0])) else (if i.val < 14 then (if i.val < 13 then #[0,0,0,0] else #[0,0,0,0]) else (if i.val < 15 then #[0,0,0,0] else #[0,0,0,0])))) : Array (Fin 1))[j.val]!
private theorem quotientStep_checked : ∀ i j,
    representatives (quotientNext i j)/(representatives i*generators j)=
      (⟨rows (stepWitness i j)⟩ : Source) := (by decide +kernel)

def cosets : BinaryNormalCosetCertificate generators kernel 16 where
  representatives := representatives
  identity := 0
  identity_mem := by
    have he : representatives 0=(⟨rows 0⟩ : Source) := by decide +kernel
    exact he ▸ row_mem 0
  next := quotientNext
  step_mem := fun i j => (quotientStep_checked i j) ▸ row_mem (stepWitness i j)
  rank i := i.val
  parent i _ := quotientParents i
  letter i _ := quotientLetters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

@[reducible] def state : BinaryNormalState generators where
  kernel := kernel
  normal := normal
  generatorCount := 0
  normalGenerators := normalGenerators
  generated := rfl
  quotientCount := 16
  cardinal := by rw [kernel_card,source_card]
  cosets := cosets
  prev := quotientPrev
  prev_next := (by decide +kernel)

end N0

namespace N1
def normalGenerators (j : Fin 1) : Source := ⟨(4 : Fin 16)⟩
def kernel : Subgroup Source := Subgroup.closure (Set.range normalGenerators)
private def rows (i : Fin 2) : Fin 16 := ((if i.val < 1 then 4 else 15) : Fin 16)
private def next (i : Fin 2) (j : Fin 1) : Fin 2 := ((if i.val < 1 then #[1] else #[0]) : Array (Fin 2))[j.val]!
private def rank (i : Fin 2) : ℕ := (if i.val < 1 then 1 else 0)
private def parents (i : Fin 2) : Fin 2 := ((if i.val < 1 then 1 else 1) : Fin 2)
private def letters (i : Fin 2) : Fin 1 := ((if i.val < 1 then 0 else 0) : Fin 1)

def normalCertificate : EncodedCayleyCertificate (binaryNormalRowEncoding normalGenerators) 2 where
  rows := rows
  identity := 1
  identity_eq := by decide +kernel
  next := next
  next_eq := (by decide +kernel)
  rank := rank
  parent i _ := parents i
  letter i hi := letters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

theorem normalRows_injective : Function.Injective normalCertificate.rows := by decide +kernel

theorem kernel_card : Nat.card kernel=2 := normalCertificate.card_closure normalRows_injective

theorem row_mem (i : Fin 2) : (⟨rows i⟩ : Source)∈kernel :=
  binaryNormalRow_mem normalCertificate i

private def posWitness (i : Fin 4) (j : Fin 1) : Fin 2 := ((if i.val < 2 then (if i.val < 1 then #[0] else #[0]) else (if i.val < 3 then #[0] else #[0])) : Array (Fin 2))[j.val]!
private def negWitness (i : Fin 4) (j : Fin 1) : Fin 2 := ((if i.val < 2 then (if i.val < 1 then #[0] else #[0]) else (if i.val < 3 then #[0] else #[0])) : Array (Fin 2))[j.val]!
private theorem pos_checked : ∀ i j, generators i*normalGenerators j*(generators i)⁻¹=
    (⟨rows (posWitness i j)⟩ : Source) := by decide +kernel
private theorem neg_checked : ∀ i j, (generators i)⁻¹*normalGenerators j*generators i=
    (⟨rows (negWitness i j)⟩ : Source) := by decide +kernel

instance normal : kernel.Normal := binaryNormal_of_generator_conjugates generators generators_full
  normalGenerators (fun i j => (pos_checked i j) ▸ row_mem (posWitness i j))
  (fun i j => (neg_checked i j) ▸ row_mem (negWitness i j))

private def representatives (i : Fin 8) : Source := ⟨((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 15 else 0) else (if i.val < 3 then 7 else 14)) else (if i.val < 6 then (if i.val < 5 then 8 else 1) else (if i.val < 7 then 6 else 9))) : Fin 16)⟩
private def quotientNext (i : Fin 8) (j : Fin 4) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[1,1,2,3] else #[0,0,4,5]) else (if i.val < 3 then #[4,4,0,6] else #[5,5,7,0])) else (if i.val < 6 then (if i.val < 5 then #[2,2,1,7] else #[3,3,6,1]) else (if i.val < 7 then #[7,7,5,2] else #[6,6,3,4]))) : Array (Fin 8))[j.val]!
private def quotientPrev (i : Fin 8) (j : Fin 4) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[1,1,2,3] else #[0,0,4,5]) else (if i.val < 3 then #[4,4,0,6] else #[5,5,7,0])) else (if i.val < 6 then (if i.val < 5 then #[2,2,1,7] else #[3,3,6,1]) else (if i.val < 7 then #[7,7,5,2] else #[6,6,3,4]))) : Array (Fin 8))[j.val]!
private def quotientParents (i : Fin 8) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 0 else 0)) else (if i.val < 6 then (if i.val < 5 then 1 else 1) else (if i.val < 7 then 2 else 3))) : Fin 8)
private def quotientLetters (i : Fin 8) : Fin 4 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 2 else 3)) else (if i.val < 6 then (if i.val < 5 then 2 else 3) else (if i.val < 7 then 3 else 2))) : Fin 4)
private def stepWitness (i : Fin 8) (j : Fin 4) : Fin 2 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[1,0,1,1] else #[1,0,1,1]) else (if i.val < 3 then #[1,0,1,1] else #[1,0,1,1])) else (if i.val < 6 then (if i.val < 5 then #[1,0,1,1] else #[1,0,1,1]) else (if i.val < 7 then #[1,0,1,1] else #[1,0,1,1]))) : Array (Fin 2))[j.val]!
private theorem quotientStep_checked : ∀ i j,
    representatives (quotientNext i j)/(representatives i*generators j)=
      (⟨rows (stepWitness i j)⟩ : Source) := (by decide +kernel)

def cosets : BinaryNormalCosetCertificate generators kernel 8 where
  representatives := representatives
  identity := 0
  identity_mem := by
    have he : representatives 0=(⟨rows 1⟩ : Source) := by decide +kernel
    exact he ▸ row_mem 1
  next := quotientNext
  step_mem := fun i j => (quotientStep_checked i j) ▸ row_mem (stepWitness i j)
  rank i := i.val
  parent i _ := quotientParents i
  letter i _ := quotientLetters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

@[reducible] def state : BinaryNormalState generators where
  kernel := kernel
  normal := normal
  generatorCount := 1
  normalGenerators := normalGenerators
  generated := rfl
  quotientCount := 8
  cardinal := by rw [kernel_card,source_card]
  cosets := cosets
  prev := quotientPrev
  prev_next := (by decide +kernel)

end N1

namespace N2
def normalGenerators (j : Fin 1) : Source := ⟨(3 : Fin 16)⟩
def kernel : Subgroup Source := Subgroup.closure (Set.range normalGenerators)
private def rows (i : Fin 2) : Fin 16 := ((if i.val < 1 then 3 else 15) : Fin 16)
private def next (i : Fin 2) (j : Fin 1) : Fin 2 := ((if i.val < 1 then #[1] else #[0]) : Array (Fin 2))[j.val]!
private def rank (i : Fin 2) : ℕ := (if i.val < 1 then 1 else 0)
private def parents (i : Fin 2) : Fin 2 := ((if i.val < 1 then 1 else 1) : Fin 2)
private def letters (i : Fin 2) : Fin 1 := ((if i.val < 1 then 0 else 0) : Fin 1)

def normalCertificate : EncodedCayleyCertificate (binaryNormalRowEncoding normalGenerators) 2 where
  rows := rows
  identity := 1
  identity_eq := by decide +kernel
  next := next
  next_eq := (by decide +kernel)
  rank := rank
  parent i _ := parents i
  letter i hi := letters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

theorem normalRows_injective : Function.Injective normalCertificate.rows := by decide +kernel

theorem kernel_card : Nat.card kernel=2 := normalCertificate.card_closure normalRows_injective

theorem row_mem (i : Fin 2) : (⟨rows i⟩ : Source)∈kernel :=
  binaryNormalRow_mem normalCertificate i

private def posWitness (i : Fin 4) (j : Fin 1) : Fin 2 := ((if i.val < 2 then (if i.val < 1 then #[0] else #[0]) else (if i.val < 3 then #[0] else #[0])) : Array (Fin 2))[j.val]!
private def negWitness (i : Fin 4) (j : Fin 1) : Fin 2 := ((if i.val < 2 then (if i.val < 1 then #[0] else #[0]) else (if i.val < 3 then #[0] else #[0])) : Array (Fin 2))[j.val]!
private theorem pos_checked : ∀ i j, generators i*normalGenerators j*(generators i)⁻¹=
    (⟨rows (posWitness i j)⟩ : Source) := by decide +kernel
private theorem neg_checked : ∀ i j, (generators i)⁻¹*normalGenerators j*generators i=
    (⟨rows (negWitness i j)⟩ : Source) := by decide +kernel

instance normal : kernel.Normal := binaryNormal_of_generator_conjugates generators generators_full
  normalGenerators (fun i j => (pos_checked i j) ▸ row_mem (posWitness i j))
  (fun i j => (neg_checked i j) ▸ row_mem (negWitness i j))

private def representatives (i : Fin 8) : Source := ⟨((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 15 else 0) else (if i.val < 3 then 7 else 14)) else (if i.val < 6 then (if i.val < 5 then 8 else 1) else (if i.val < 7 then 6 else 9))) : Fin 16)⟩
private def quotientNext (i : Fin 8) (j : Fin 4) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[1,0,2,3] else #[0,1,4,5]) else (if i.val < 3 then #[4,2,0,6] else #[5,3,7,0])) else (if i.val < 6 then (if i.val < 5 then #[2,4,1,7] else #[3,5,6,1]) else (if i.val < 7 then #[7,6,5,2] else #[6,7,3,4]))) : Array (Fin 8))[j.val]!
private def quotientPrev (i : Fin 8) (j : Fin 4) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[1,0,2,3] else #[0,1,4,5]) else (if i.val < 3 then #[4,2,0,6] else #[5,3,7,0])) else (if i.val < 6 then (if i.val < 5 then #[2,4,1,7] else #[3,5,6,1]) else (if i.val < 7 then #[7,6,5,2] else #[6,7,3,4]))) : Array (Fin 8))[j.val]!
private def quotientParents (i : Fin 8) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 0 else 0)) else (if i.val < 6 then (if i.val < 5 then 1 else 1) else (if i.val < 7 then 2 else 3))) : Fin 8)
private def quotientLetters (i : Fin 8) : Fin 4 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 2 else 3)) else (if i.val < 6 then (if i.val < 5 then 2 else 3) else (if i.val < 7 then 3 else 2))) : Fin 4)
private def stepWitness (i : Fin 8) (j : Fin 4) : Fin 2 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[1,0,1,1] else #[1,0,1,1]) else (if i.val < 3 then #[1,0,1,1] else #[1,0,1,1])) else (if i.val < 6 then (if i.val < 5 then #[1,0,1,1] else #[1,0,1,1]) else (if i.val < 7 then #[1,0,1,1] else #[1,0,1,1]))) : Array (Fin 2))[j.val]!
private theorem quotientStep_checked : ∀ i j,
    representatives (quotientNext i j)/(representatives i*generators j)=
      (⟨rows (stepWitness i j)⟩ : Source) := (by decide +kernel)

def cosets : BinaryNormalCosetCertificate generators kernel 8 where
  representatives := representatives
  identity := 0
  identity_mem := by
    have he : representatives 0=(⟨rows 1⟩ : Source) := by decide +kernel
    exact he ▸ row_mem 1
  next := quotientNext
  step_mem := fun i j => (quotientStep_checked i j) ▸ row_mem (stepWitness i j)
  rank i := i.val
  parent i _ := quotientParents i
  letter i _ := quotientLetters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

@[reducible] def state : BinaryNormalState generators where
  kernel := kernel
  normal := normal
  generatorCount := 1
  normalGenerators := normalGenerators
  generated := rfl
  quotientCount := 8
  cardinal := by rw [kernel_card,source_card]
  cosets := cosets
  prev := quotientPrev
  prev_next := (by decide +kernel)

end N2

namespace N3
def normalGenerators (j : Fin 1) : Source := ⟨(0 : Fin 16)⟩
def kernel : Subgroup Source := Subgroup.closure (Set.range normalGenerators)
private def rows (i : Fin 2) : Fin 16 := ((if i.val < 1 then 0 else 15) : Fin 16)
private def next (i : Fin 2) (j : Fin 1) : Fin 2 := ((if i.val < 1 then #[1] else #[0]) : Array (Fin 2))[j.val]!
private def rank (i : Fin 2) : ℕ := (if i.val < 1 then 1 else 0)
private def parents (i : Fin 2) : Fin 2 := ((if i.val < 1 then 1 else 1) : Fin 2)
private def letters (i : Fin 2) : Fin 1 := ((if i.val < 1 then 0 else 0) : Fin 1)

def normalCertificate : EncodedCayleyCertificate (binaryNormalRowEncoding normalGenerators) 2 where
  rows := rows
  identity := 1
  identity_eq := by decide +kernel
  next := next
  next_eq := (by decide +kernel)
  rank := rank
  parent i _ := parents i
  letter i hi := letters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

theorem normalRows_injective : Function.Injective normalCertificate.rows := by decide +kernel

theorem kernel_card : Nat.card kernel=2 := normalCertificate.card_closure normalRows_injective

theorem row_mem (i : Fin 2) : (⟨rows i⟩ : Source)∈kernel :=
  binaryNormalRow_mem normalCertificate i

private def posWitness (i : Fin 4) (j : Fin 1) : Fin 2 := ((if i.val < 2 then (if i.val < 1 then #[0] else #[0]) else (if i.val < 3 then #[0] else #[0])) : Array (Fin 2))[j.val]!
private def negWitness (i : Fin 4) (j : Fin 1) : Fin 2 := ((if i.val < 2 then (if i.val < 1 then #[0] else #[0]) else (if i.val < 3 then #[0] else #[0])) : Array (Fin 2))[j.val]!
private theorem pos_checked : ∀ i j, generators i*normalGenerators j*(generators i)⁻¹=
    (⟨rows (posWitness i j)⟩ : Source) := by decide +kernel
private theorem neg_checked : ∀ i j, (generators i)⁻¹*normalGenerators j*generators i=
    (⟨rows (negWitness i j)⟩ : Source) := by decide +kernel

instance normal : kernel.Normal := binaryNormal_of_generator_conjugates generators generators_full
  normalGenerators (fun i j => (pos_checked i j) ▸ row_mem (posWitness i j))
  (fun i j => (neg_checked i j) ▸ row_mem (negWitness i j))

private def representatives (i : Fin 8) : Source := ⟨((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 15 else 3) else (if i.val < 3 then 7 else 14)) else (if i.val < 6 then (if i.val < 5 then 10 else 2) else (if i.val < 7 then 6 else 11))) : Fin 16)⟩
private def quotientNext (i : Fin 8) (j : Fin 4) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[0,1,2,3] else #[1,0,4,5]) else (if i.val < 3 then #[2,4,0,6] else #[3,5,6,0])) else (if i.val < 6 then (if i.val < 5 then #[4,2,1,7] else #[5,3,7,1]) else (if i.val < 7 then #[6,7,3,2] else #[7,6,5,4]))) : Array (Fin 8))[j.val]!
private def quotientPrev (i : Fin 8) (j : Fin 4) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[0,1,2,3] else #[1,0,4,5]) else (if i.val < 3 then #[2,4,0,6] else #[3,5,6,0])) else (if i.val < 6 then (if i.val < 5 then #[4,2,1,7] else #[5,3,7,1]) else (if i.val < 7 then #[6,7,3,2] else #[7,6,5,4]))) : Array (Fin 8))[j.val]!
private def quotientParents (i : Fin 8) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 0 else 0)) else (if i.val < 6 then (if i.val < 5 then 1 else 1) else (if i.val < 7 then 2 else 4))) : Fin 8)
private def quotientLetters (i : Fin 8) : Fin 4 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 1) else (if i.val < 3 then 2 else 3)) else (if i.val < 6 then (if i.val < 5 then 2 else 3) else (if i.val < 7 then 3 else 3))) : Fin 4)
private def stepWitness (i : Fin 8) (j : Fin 4) : Fin 2 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[0,1,1,1] else #[0,1,1,1]) else (if i.val < 3 then #[0,1,1,1] else #[0,1,0,1])) else (if i.val < 6 then (if i.val < 5 then #[0,1,1,1] else #[0,1,0,1]) else (if i.val < 7 then #[0,1,0,1] else #[0,1,0,1]))) : Array (Fin 2))[j.val]!
private theorem quotientStep_checked : ∀ i j,
    representatives (quotientNext i j)/(representatives i*generators j)=
      (⟨rows (stepWitness i j)⟩ : Source) := (by decide +kernel)

def cosets : BinaryNormalCosetCertificate generators kernel 8 where
  representatives := representatives
  identity := 0
  identity_mem := by
    have he : representatives 0=(⟨rows 1⟩ : Source) := by decide +kernel
    exact he ▸ row_mem 1
  next := quotientNext
  step_mem := fun i j => (quotientStep_checked i j) ▸ row_mem (stepWitness i j)
  rank i := i.val
  parent i _ := quotientParents i
  letter i _ := quotientLetters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

@[reducible] def state : BinaryNormalState generators where
  kernel := kernel
  normal := normal
  generatorCount := 1
  normalGenerators := normalGenerators
  generated := rfl
  quotientCount := 8
  cardinal := by rw [kernel_card,source_card]
  cosets := cosets
  prev := quotientPrev
  prev_next := (by decide +kernel)

end N3

namespace N4
def normalGenerators (j : Fin 1) : Source := ⟨(11 : Fin 16)⟩
def kernel : Subgroup Source := Subgroup.closure (Set.range normalGenerators)
private def rows (i : Fin 4) : Fin 16 := ((if i.val < 2 then (if i.val < 1 then 0 else 11) else (if i.val < 3 then 12 else 15)) : Fin 16)
private def next (i : Fin 4) (j : Fin 1) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[2] else #[0]) else (if i.val < 3 then #[3] else #[1])) : Array (Fin 4))[j.val]!
private def rank (i : Fin 4) : ℕ := (if i.val < 2 then (if i.val < 1 then 2 else 1) else (if i.val < 3 then 3 else 0))
private def parents (i : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then 1 else 3) else (if i.val < 3 then 0 else 3)) : Fin 4)
private def letters (i : Fin 4) : Fin 1 := ((if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 0 else 0)) : Fin 1)

def normalCertificate : EncodedCayleyCertificate (binaryNormalRowEncoding normalGenerators) 4 where
  rows := rows
  identity := 3
  identity_eq := by decide +kernel
  next := next
  next_eq := (by decide +kernel)
  rank := rank
  parent i _ := parents i
  letter i hi := letters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

theorem normalRows_injective : Function.Injective normalCertificate.rows := by decide +kernel

theorem kernel_card : Nat.card kernel=4 := normalCertificate.card_closure normalRows_injective

theorem row_mem (i : Fin 4) : (⟨rows i⟩ : Source)∈kernel :=
  binaryNormalRow_mem normalCertificate i

private def posWitness (i : Fin 4) (j : Fin 1) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[1] else #[1]) else (if i.val < 3 then #[2] else #[2])) : Array (Fin 4))[j.val]!
private def negWitness (i : Fin 4) (j : Fin 1) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[1] else #[1]) else (if i.val < 3 then #[2] else #[2])) : Array (Fin 4))[j.val]!
private theorem pos_checked : ∀ i j, generators i*normalGenerators j*(generators i)⁻¹=
    (⟨rows (posWitness i j)⟩ : Source) := by decide +kernel
private theorem neg_checked : ∀ i j, (generators i)⁻¹*normalGenerators j*generators i=
    (⟨rows (negWitness i j)⟩ : Source) := by decide +kernel

instance normal : kernel.Normal := binaryNormal_of_generator_conjugates generators generators_full
  normalGenerators (fun i j => (pos_checked i j) ▸ row_mem (posWitness i j))
  (fun i j => (neg_checked i j) ▸ row_mem (negWitness i j))

private def representatives (i : Fin 4) : Source := ⟨((if i.val < 2 then (if i.val < 1 then 15 else 3) else (if i.val < 3 then 7 else 14)) : Fin 16)⟩
private def quotientNext (i : Fin 4) (j : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[0,1,2,3] else #[1,0,3,2]) else (if i.val < 3 then #[2,3,0,1] else #[3,2,1,0])) : Array (Fin 4))[j.val]!
private def quotientPrev (i : Fin 4) (j : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[0,1,2,3] else #[1,0,3,2]) else (if i.val < 3 then #[2,3,0,1] else #[3,2,1,0])) : Array (Fin 4))[j.val]!
private def quotientParents (i : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 0 else 0)) : Fin 4)
private def quotientLetters (i : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then 0 else 1) else (if i.val < 3 then 2 else 3)) : Fin 4)
private def stepWitness (i : Fin 4) (j : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[0,3,3,3] else #[0,3,2,1]) else (if i.val < 3 then #[0,2,3,2] else #[0,1,1,3])) : Array (Fin 4))[j.val]!
private theorem quotientStep_checked : ∀ i j,
    representatives (quotientNext i j)/(representatives i*generators j)=
      (⟨rows (stepWitness i j)⟩ : Source) := (by decide +kernel)

def cosets : BinaryNormalCosetCertificate generators kernel 4 where
  representatives := representatives
  identity := 0
  identity_mem := by
    have he : representatives 0=(⟨rows 3⟩ : Source) := by decide +kernel
    exact he ▸ row_mem 3
  next := quotientNext
  step_mem := fun i j => (quotientStep_checked i j) ▸ row_mem (stepWitness i j)
  rank i := i.val
  parent i _ := quotientParents i
  letter i _ := quotientLetters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

@[reducible] def state : BinaryNormalState generators where
  kernel := kernel
  normal := normal
  generatorCount := 1
  normalGenerators := normalGenerators
  generated := rfl
  quotientCount := 4
  cardinal := by rw [kernel_card,source_card]
  cosets := cosets
  prev := quotientPrev
  prev_next := (by decide +kernel)

end N4

namespace N5
def normalGenerators (j : Fin 1) : Source := ⟨(6 : Fin 16)⟩
def kernel : Subgroup Source := Subgroup.closure (Set.range normalGenerators)
private def rows (i : Fin 4) : Fin 16 := ((if i.val < 2 then (if i.val < 1 then 0 else 6) else (if i.val < 3 then 9 else 15)) : Fin 16)
private def next (i : Fin 4) (j : Fin 1) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[2] else #[0]) else (if i.val < 3 then #[3] else #[1])) : Array (Fin 4))[j.val]!
private def rank (i : Fin 4) : ℕ := (if i.val < 2 then (if i.val < 1 then 2 else 1) else (if i.val < 3 then 3 else 0))
private def parents (i : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then 1 else 3) else (if i.val < 3 then 0 else 3)) : Fin 4)
private def letters (i : Fin 4) : Fin 1 := ((if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 0 else 0)) : Fin 1)

def normalCertificate : EncodedCayleyCertificate (binaryNormalRowEncoding normalGenerators) 4 where
  rows := rows
  identity := 3
  identity_eq := by decide +kernel
  next := next
  next_eq := (by decide +kernel)
  rank := rank
  parent i _ := parents i
  letter i hi := letters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

theorem normalRows_injective : Function.Injective normalCertificate.rows := by decide +kernel

theorem kernel_card : Nat.card kernel=4 := normalCertificate.card_closure normalRows_injective

theorem row_mem (i : Fin 4) : (⟨rows i⟩ : Source)∈kernel :=
  binaryNormalRow_mem normalCertificate i

private def posWitness (i : Fin 4) (j : Fin 1) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[1] else #[1]) else (if i.val < 3 then #[2] else #[2])) : Array (Fin 4))[j.val]!
private def negWitness (i : Fin 4) (j : Fin 1) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[1] else #[1]) else (if i.val < 3 then #[2] else #[2])) : Array (Fin 4))[j.val]!
private theorem pos_checked : ∀ i j, generators i*normalGenerators j*(generators i)⁻¹=
    (⟨rows (posWitness i j)⟩ : Source) := by decide +kernel
private theorem neg_checked : ∀ i j, (generators i)⁻¹*normalGenerators j*generators i=
    (⟨rows (negWitness i j)⟩ : Source) := by decide +kernel

instance normal : kernel.Normal := binaryNormal_of_generator_conjugates generators generators_full
  normalGenerators (fun i j => (pos_checked i j) ▸ row_mem (posWitness i j))
  (fun i j => (neg_checked i j) ▸ row_mem (negWitness i j))

private def representatives (i : Fin 4) : Source := ⟨((if i.val < 2 then (if i.val < 1 then 15 else 3) else (if i.val < 3 then 7 else 10)) : Fin 16)⟩
private def quotientNext (i : Fin 4) (j : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[0,1,2,2] else #[1,0,3,3]) else (if i.val < 3 then #[2,3,0,0] else #[3,2,1,1])) : Array (Fin 4))[j.val]!
private def quotientPrev (i : Fin 4) (j : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[0,1,2,2] else #[1,0,3,3]) else (if i.val < 3 then #[2,3,0,0] else #[3,2,1,1])) : Array (Fin 4))[j.val]!
private def quotientParents (i : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 0 else 1)) : Fin 4)
private def quotientLetters (i : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then 0 else 1) else (if i.val < 3 then 2 else 2)) : Fin 4)
private def stepWitness (i : Fin 4) (j : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[0,3,3,1] else #[0,3,3,1]) else (if i.val < 3 then #[0,3,3,2] else #[0,3,3,2])) : Array (Fin 4))[j.val]!
private theorem quotientStep_checked : ∀ i j,
    representatives (quotientNext i j)/(representatives i*generators j)=
      (⟨rows (stepWitness i j)⟩ : Source) := (by decide +kernel)

def cosets : BinaryNormalCosetCertificate generators kernel 4 where
  representatives := representatives
  identity := 0
  identity_mem := by
    have he : representatives 0=(⟨rows 3⟩ : Source) := by decide +kernel
    exact he ▸ row_mem 3
  next := quotientNext
  step_mem := fun i j => (quotientStep_checked i j) ▸ row_mem (stepWitness i j)
  rank i := i.val
  parent i _ := quotientParents i
  letter i _ := quotientLetters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

@[reducible] def state : BinaryNormalState generators where
  kernel := kernel
  normal := normal
  generatorCount := 1
  normalGenerators := normalGenerators
  generated := rfl
  quotientCount := 4
  cardinal := by rw [kernel_card,source_card]
  cosets := cosets
  prev := quotientPrev
  prev_next := (by decide +kernel)

end N5

namespace N6
def normalGenerators (j : Fin 2) : Source := ⟨((if j.val < 1 then 2 else 0) : Fin 16)⟩
def kernel : Subgroup Source := Subgroup.closure (Set.range normalGenerators)
private def rows (i : Fin 4) : Fin 16 := ((if i.val < 2 then (if i.val < 1 then 0 else 2) else (if i.val < 3 then 5 else 15)) : Fin 16)
private def next (i : Fin 4) (j : Fin 2) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[2,3] else #[3,2]) else (if i.val < 3 then #[0,1] else #[1,0])) : Array (Fin 4))[j.val]!
private def rank (i : Fin 4) : ℕ := (if i.val < 2 then (if i.val < 1 then 2 else 1) else (if i.val < 3 then 3 else 0))
private def parents (i : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then 3 else 3) else (if i.val < 3 then 1 else 3)) : Fin 4)
private def letters (i : Fin 4) : Fin 2 := ((if i.val < 2 then (if i.val < 1 then 1 else 0) else (if i.val < 3 then 1 else 0)) : Fin 2)

def normalCertificate : EncodedCayleyCertificate (binaryNormalRowEncoding normalGenerators) 4 where
  rows := rows
  identity := 3
  identity_eq := by decide +kernel
  next := next
  next_eq := (by decide +kernel)
  rank := rank
  parent i _ := parents i
  letter i hi := letters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

theorem normalRows_injective : Function.Injective normalCertificate.rows := by decide +kernel

theorem kernel_card : Nat.card kernel=4 := normalCertificate.card_closure normalRows_injective

theorem row_mem (i : Fin 4) : (⟨rows i⟩ : Source)∈kernel :=
  binaryNormalRow_mem normalCertificate i

private def posWitness (i : Fin 4) (j : Fin 2) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[1,0] else #[1,0]) else (if i.val < 3 then #[2,0] else #[1,0])) : Array (Fin 4))[j.val]!
private def negWitness (i : Fin 4) (j : Fin 2) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[1,0] else #[1,0]) else (if i.val < 3 then #[2,0] else #[1,0])) : Array (Fin 4))[j.val]!
private theorem pos_checked : ∀ i j, generators i*normalGenerators j*(generators i)⁻¹=
    (⟨rows (posWitness i j)⟩ : Source) := by decide +kernel
private theorem neg_checked : ∀ i j, (generators i)⁻¹*normalGenerators j*generators i=
    (⟨rows (negWitness i j)⟩ : Source) := by decide +kernel

instance normal : kernel.Normal := binaryNormal_of_generator_conjugates generators generators_full
  normalGenerators (fun i j => (pos_checked i j) ▸ row_mem (posWitness i j))
  (fun i j => (neg_checked i j) ▸ row_mem (negWitness i j))

private def representatives (i : Fin 4) : Source := ⟨((if i.val < 2 then (if i.val < 1 then 15 else 3) else (if i.val < 3 then 7 else 10)) : Fin 16)⟩
private def quotientNext (i : Fin 4) (j : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[0,1,2,1] else #[1,0,3,0]) else (if i.val < 3 then #[2,3,0,3] else #[3,2,1,2])) : Array (Fin 4))[j.val]!
private def quotientPrev (i : Fin 4) (j : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[0,1,2,1] else #[1,0,3,0]) else (if i.val < 3 then #[2,3,0,3] else #[3,2,1,2])) : Array (Fin 4))[j.val]!
private def quotientParents (i : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 0 else 1)) : Fin 4)
private def quotientLetters (i : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then 0 else 1) else (if i.val < 3 then 2 else 2)) : Fin 4)
private def stepWitness (i : Fin 4) (j : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[0,3,3,1] else #[0,3,3,1]) else (if i.val < 3 then #[0,3,3,2] else #[0,3,3,2])) : Array (Fin 4))[j.val]!
private theorem quotientStep_checked : ∀ i j,
    representatives (quotientNext i j)/(representatives i*generators j)=
      (⟨rows (stepWitness i j)⟩ : Source) := (by decide +kernel)

def cosets : BinaryNormalCosetCertificate generators kernel 4 where
  representatives := representatives
  identity := 0
  identity_mem := by
    have he : representatives 0=(⟨rows 3⟩ : Source) := by decide +kernel
    exact he ▸ row_mem 3
  next := quotientNext
  step_mem := fun i j => (quotientStep_checked i j) ▸ row_mem (stepWitness i j)
  rank i := i.val
  parent i _ := quotientParents i
  letter i _ := quotientLetters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

@[reducible] def state : BinaryNormalState generators where
  kernel := kernel
  normal := normal
  generatorCount := 2
  normalGenerators := normalGenerators
  generated := rfl
  quotientCount := 4
  cardinal := by rw [kernel_card,source_card]
  cosets := cosets
  prev := quotientPrev
  prev_next := (by decide +kernel)

end N6

namespace N7
def normalGenerators (j : Fin 2) : Source := ⟨((if j.val < 1 then 14 else 0) : Fin 16)⟩
def kernel : Subgroup Source := Subgroup.closure (Set.range normalGenerators)
private def rows (i : Fin 4) : Fin 16 := ((if i.val < 2 then (if i.val < 1 then 0 else 1) else (if i.val < 3 then 14 else 15)) : Fin 16)
private def next (i : Fin 4) (j : Fin 2) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[1,3] else #[0,2]) else (if i.val < 3 then #[3,1] else #[2,0])) : Array (Fin 4))[j.val]!
private def rank (i : Fin 4) : ℕ := (if i.val < 2 then (if i.val < 1 then 2 else 3) else (if i.val < 3 then 1 else 0))
private def parents (i : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then 3 else 2) else (if i.val < 3 then 3 else 3)) : Fin 4)
private def letters (i : Fin 4) : Fin 2 := ((if i.val < 2 then (if i.val < 1 then 1 else 1) else (if i.val < 3 then 0 else 0)) : Fin 2)

def normalCertificate : EncodedCayleyCertificate (binaryNormalRowEncoding normalGenerators) 4 where
  rows := rows
  identity := 3
  identity_eq := by decide +kernel
  next := next
  next_eq := (by decide +kernel)
  rank := rank
  parent i _ := parents i
  letter i hi := letters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

theorem normalRows_injective : Function.Injective normalCertificate.rows := by decide +kernel

theorem kernel_card : Nat.card kernel=4 := normalCertificate.card_closure normalRows_injective

theorem row_mem (i : Fin 4) : (⟨rows i⟩ : Source)∈kernel :=
  binaryNormalRow_mem normalCertificate i

private def posWitness (i : Fin 4) (j : Fin 2) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[2,0] else #[2,0]) else (if i.val < 3 then #[1,0] else #[2,0])) : Array (Fin 4))[j.val]!
private def negWitness (i : Fin 4) (j : Fin 2) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[2,0] else #[2,0]) else (if i.val < 3 then #[1,0] else #[2,0])) : Array (Fin 4))[j.val]!
private theorem pos_checked : ∀ i j, generators i*normalGenerators j*(generators i)⁻¹=
    (⟨rows (posWitness i j)⟩ : Source) := by decide +kernel
private theorem neg_checked : ∀ i j, (generators i)⁻¹*normalGenerators j*generators i=
    (⟨rows (negWitness i j)⟩ : Source) := by decide +kernel

instance normal : kernel.Normal := binaryNormal_of_generator_conjugates generators generators_full
  normalGenerators (fun i j => (pos_checked i j) ▸ row_mem (posWitness i j))
  (fun i j => (neg_checked i j) ▸ row_mem (negWitness i j))

private def representatives (i : Fin 4) : Source := ⟨((if i.val < 2 then (if i.val < 1 then 15 else 3) else (if i.val < 3 then 7 else 10)) : Fin 16)⟩
private def quotientNext (i : Fin 4) (j : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[0,1,2,0] else #[1,0,3,1]) else (if i.val < 3 then #[2,3,0,2] else #[3,2,1,3])) : Array (Fin 4))[j.val]!
private def quotientPrev (i : Fin 4) (j : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[0,1,2,0] else #[1,0,3,1]) else (if i.val < 3 then #[2,3,0,2] else #[3,2,1,3])) : Array (Fin 4))[j.val]!
private def quotientParents (i : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 0 else 1)) : Fin 4)
private def quotientLetters (i : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then 0 else 1) else (if i.val < 3 then 2 else 2)) : Fin 4)
private def stepWitness (i : Fin 4) (j : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[0,3,3,2] else #[0,3,3,2]) else (if i.val < 3 then #[0,3,3,1] else #[0,3,3,1])) : Array (Fin 4))[j.val]!
private theorem quotientStep_checked : ∀ i j,
    representatives (quotientNext i j)/(representatives i*generators j)=
      (⟨rows (stepWitness i j)⟩ : Source) := (by decide +kernel)

def cosets : BinaryNormalCosetCertificate generators kernel 4 where
  representatives := representatives
  identity := 0
  identity_mem := by
    have he : representatives 0=(⟨rows 3⟩ : Source) := by decide +kernel
    exact he ▸ row_mem 3
  next := quotientNext
  step_mem := fun i j => (quotientStep_checked i j) ▸ row_mem (stepWitness i j)
  rank i := i.val
  parent i _ := quotientParents i
  letter i _ := quotientLetters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

@[reducible] def state : BinaryNormalState generators where
  kernel := kernel
  normal := normal
  generatorCount := 2
  normalGenerators := normalGenerators
  generated := rfl
  quotientCount := 4
  cardinal := by rw [kernel_card,source_card]
  cosets := cosets
  prev := quotientPrev
  prev_next := (by decide +kernel)

end N7

namespace N8
def normalGenerators (j : Fin 2) : Source := ⟨((if j.val < 1 then 10 else 0) : Fin 16)⟩
def kernel : Subgroup Source := Subgroup.closure (Set.range normalGenerators)
private def rows (i : Fin 4) : Fin 16 := ((if i.val < 2 then (if i.val < 1 then 0 else 10) else (if i.val < 3 then 13 else 15)) : Fin 16)
private def next (i : Fin 4) (j : Fin 2) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[2,3] else #[3,2]) else (if i.val < 3 then #[0,1] else #[1,0])) : Array (Fin 4))[j.val]!
private def rank (i : Fin 4) : ℕ := (if i.val < 2 then (if i.val < 1 then 2 else 1) else (if i.val < 3 then 3 else 0))
private def parents (i : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then 3 else 3) else (if i.val < 3 then 1 else 3)) : Fin 4)
private def letters (i : Fin 4) : Fin 2 := ((if i.val < 2 then (if i.val < 1 then 1 else 0) else (if i.val < 3 then 1 else 0)) : Fin 2)

def normalCertificate : EncodedCayleyCertificate (binaryNormalRowEncoding normalGenerators) 4 where
  rows := rows
  identity := 3
  identity_eq := by decide +kernel
  next := next
  next_eq := (by decide +kernel)
  rank := rank
  parent i _ := parents i
  letter i hi := letters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

theorem normalRows_injective : Function.Injective normalCertificate.rows := by decide +kernel

theorem kernel_card : Nat.card kernel=4 := normalCertificate.card_closure normalRows_injective

theorem row_mem (i : Fin 4) : (⟨rows i⟩ : Source)∈kernel :=
  binaryNormalRow_mem normalCertificate i

private def posWitness (i : Fin 4) (j : Fin 2) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[1,0] else #[1,0]) else (if i.val < 3 then #[1,0] else #[2,0])) : Array (Fin 4))[j.val]!
private def negWitness (i : Fin 4) (j : Fin 2) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[1,0] else #[1,0]) else (if i.val < 3 then #[1,0] else #[2,0])) : Array (Fin 4))[j.val]!
private theorem pos_checked : ∀ i j, generators i*normalGenerators j*(generators i)⁻¹=
    (⟨rows (posWitness i j)⟩ : Source) := by decide +kernel
private theorem neg_checked : ∀ i j, (generators i)⁻¹*normalGenerators j*generators i=
    (⟨rows (negWitness i j)⟩ : Source) := by decide +kernel

instance normal : kernel.Normal := binaryNormal_of_generator_conjugates generators generators_full
  normalGenerators (fun i j => (pos_checked i j) ▸ row_mem (posWitness i j))
  (fun i j => (neg_checked i j) ▸ row_mem (negWitness i j))

private def representatives (i : Fin 4) : Source := ⟨((if i.val < 2 then (if i.val < 1 then 15 else 3) else (if i.val < 3 then 14 else 2)) : Fin 16)⟩
private def quotientNext (i : Fin 4) (j : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[0,1,1,2] else #[1,0,0,3]) else (if i.val < 3 then #[2,3,3,0] else #[3,2,2,1])) : Array (Fin 4))[j.val]!
private def quotientPrev (i : Fin 4) (j : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[0,1,1,2] else #[1,0,0,3]) else (if i.val < 3 then #[2,3,3,0] else #[3,2,2,1])) : Array (Fin 4))[j.val]!
private def quotientParents (i : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 0 else 1)) : Fin 4)
private def quotientLetters (i : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then 0 else 1) else (if i.val < 3 then 3 else 3)) : Fin 4)
private def stepWitness (i : Fin 4) (j : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[0,3,1,3] else #[0,3,1,3]) else (if i.val < 3 then #[0,3,2,3] else #[0,3,2,3])) : Array (Fin 4))[j.val]!
private theorem quotientStep_checked : ∀ i j,
    representatives (quotientNext i j)/(representatives i*generators j)=
      (⟨rows (stepWitness i j)⟩ : Source) := (by decide +kernel)

def cosets : BinaryNormalCosetCertificate generators kernel 4 where
  representatives := representatives
  identity := 0
  identity_mem := by
    have he : representatives 0=(⟨rows 3⟩ : Source) := by decide +kernel
    exact he ▸ row_mem 3
  next := quotientNext
  step_mem := fun i j => (quotientStep_checked i j) ▸ row_mem (stepWitness i j)
  rank i := i.val
  parent i _ := quotientParents i
  letter i _ := quotientLetters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

@[reducible] def state : BinaryNormalState generators where
  kernel := kernel
  normal := normal
  generatorCount := 2
  normalGenerators := normalGenerators
  generated := rfl
  quotientCount := 4
  cardinal := by rw [kernel_card,source_card]
  cosets := cosets
  prev := quotientPrev
  prev_next := (by decide +kernel)

end N8

namespace N9
def normalGenerators (j : Fin 2) : Source := ⟨((if j.val < 1 then 7 else 0) : Fin 16)⟩
def kernel : Subgroup Source := Subgroup.closure (Set.range normalGenerators)
private def rows (i : Fin 4) : Fin 16 := ((if i.val < 2 then (if i.val < 1 then 0 else 7) else (if i.val < 3 then 8 else 15)) : Fin 16)
private def next (i : Fin 4) (j : Fin 2) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[2,3] else #[3,2]) else (if i.val < 3 then #[0,1] else #[1,0])) : Array (Fin 4))[j.val]!
private def rank (i : Fin 4) : ℕ := (if i.val < 2 then (if i.val < 1 then 2 else 1) else (if i.val < 3 then 3 else 0))
private def parents (i : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then 3 else 3) else (if i.val < 3 then 1 else 3)) : Fin 4)
private def letters (i : Fin 4) : Fin 2 := ((if i.val < 2 then (if i.val < 1 then 1 else 0) else (if i.val < 3 then 1 else 0)) : Fin 2)

def normalCertificate : EncodedCayleyCertificate (binaryNormalRowEncoding normalGenerators) 4 where
  rows := rows
  identity := 3
  identity_eq := by decide +kernel
  next := next
  next_eq := (by decide +kernel)
  rank := rank
  parent i _ := parents i
  letter i hi := letters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

theorem normalRows_injective : Function.Injective normalCertificate.rows := by decide +kernel

theorem kernel_card : Nat.card kernel=4 := normalCertificate.card_closure normalRows_injective

theorem row_mem (i : Fin 4) : (⟨rows i⟩ : Source)∈kernel :=
  binaryNormalRow_mem normalCertificate i

private def posWitness (i : Fin 4) (j : Fin 2) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[1,0] else #[1,0]) else (if i.val < 3 then #[1,0] else #[2,0])) : Array (Fin 4))[j.val]!
private def negWitness (i : Fin 4) (j : Fin 2) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[1,0] else #[1,0]) else (if i.val < 3 then #[1,0] else #[2,0])) : Array (Fin 4))[j.val]!
private theorem pos_checked : ∀ i j, generators i*normalGenerators j*(generators i)⁻¹=
    (⟨rows (posWitness i j)⟩ : Source) := by decide +kernel
private theorem neg_checked : ∀ i j, (generators i)⁻¹*normalGenerators j*generators i=
    (⟨rows (negWitness i j)⟩ : Source) := by decide +kernel

instance normal : kernel.Normal := binaryNormal_of_generator_conjugates generators generators_full
  normalGenerators (fun i j => (pos_checked i j) ▸ row_mem (posWitness i j))
  (fun i j => (neg_checked i j) ▸ row_mem (negWitness i j))

private def representatives (i : Fin 4) : Source := ⟨((if i.val < 2 then (if i.val < 1 then 15 else 3) else (if i.val < 3 then 14 else 2)) : Fin 16)⟩
private def quotientNext (i : Fin 4) (j : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[0,1,0,2] else #[1,0,1,3]) else (if i.val < 3 then #[2,3,2,0] else #[3,2,3,1])) : Array (Fin 4))[j.val]!
private def quotientPrev (i : Fin 4) (j : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[0,1,0,2] else #[1,0,1,3]) else (if i.val < 3 then #[2,3,2,0] else #[3,2,3,1])) : Array (Fin 4))[j.val]!
private def quotientParents (i : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 0 else 1)) : Fin 4)
private def quotientLetters (i : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then 0 else 1) else (if i.val < 3 then 3 else 3)) : Fin 4)
private def stepWitness (i : Fin 4) (j : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[0,3,1,3] else #[0,3,1,3]) else (if i.val < 3 then #[0,3,2,3] else #[0,3,2,3])) : Array (Fin 4))[j.val]!
private theorem quotientStep_checked : ∀ i j,
    representatives (quotientNext i j)/(representatives i*generators j)=
      (⟨rows (stepWitness i j)⟩ : Source) := (by decide +kernel)

def cosets : BinaryNormalCosetCertificate generators kernel 4 where
  representatives := representatives
  identity := 0
  identity_mem := by
    have he : representatives 0=(⟨rows 3⟩ : Source) := by decide +kernel
    exact he ▸ row_mem 3
  next := quotientNext
  step_mem := fun i j => (quotientStep_checked i j) ▸ row_mem (stepWitness i j)
  rank i := i.val
  parent i _ := quotientParents i
  letter i _ := quotientLetters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

@[reducible] def state : BinaryNormalState generators where
  kernel := kernel
  normal := normal
  generatorCount := 2
  normalGenerators := normalGenerators
  generated := rfl
  quotientCount := 4
  cardinal := by rw [kernel_card,source_card]
  cosets := cosets
  prev := quotientPrev
  prev_next := (by decide +kernel)

end N9

namespace N10
def normalGenerators (j : Fin 3) : Source := ⟨((if j.val < 1 then 2 else (if j.val < 2 then 10 else 0)) : Fin 16)⟩
def kernel : Subgroup Source := Subgroup.closure (Set.range normalGenerators)
private def rows (i : Fin 8) : Fin 16 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 2) else (if i.val < 3 then 5 else 6)) else (if i.val < 6 then (if i.val < 5 then 9 else 10) else (if i.val < 7 then 13 else 15))) : Fin 16)
private def next (i : Fin 8) (j : Fin 3) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[2,6,7] else #[7,4,2]) else (if i.val < 3 then #[0,3,1] else #[5,2,4])) else (if i.val < 6 then (if i.val < 5 then #[6,1,3] else #[3,7,6]) else (if i.val < 7 then #[4,0,5] else #[1,5,0]))) : Array (Fin 8))[j.val]!
private def rank (i : Fin 8) : ℕ := (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 3 else 1) else (if i.val < 3 then 5 else 6)) else (if i.val < 6 then (if i.val < 5 then 4 else 2) else (if i.val < 7 then 7 else 0)))
private def parents (i : Fin 8) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 7 else 7) else (if i.val < 3 then 1 else 5)) else (if i.val < 6 then (if i.val < 5 then 1 else 7) else (if i.val < 7 then 5 else 7))) : Fin 8)
private def letters (i : Fin 8) : Fin 3 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 2 else 0) else (if i.val < 3 then 2 else 0)) else (if i.val < 6 then (if i.val < 5 then 1 else 1) else (if i.val < 7 then 2 else 0))) : Fin 3)

def normalCertificate : EncodedCayleyCertificate (binaryNormalRowEncoding normalGenerators) 8 where
  rows := rows
  identity := 7
  identity_eq := by decide +kernel
  next := next
  next_eq := (by decide +kernel)
  rank := rank
  parent i _ := parents i
  letter i hi := letters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

theorem normalRows_injective : Function.Injective normalCertificate.rows := by decide +kernel

theorem kernel_card : Nat.card kernel=8 := normalCertificate.card_closure normalRows_injective

theorem row_mem (i : Fin 8) : (⟨rows i⟩ : Source)∈kernel :=
  binaryNormalRow_mem normalCertificate i

private def posWitness (i : Fin 4) (j : Fin 3) : Fin 8 := ((if i.val < 2 then (if i.val < 1 then #[1,5,0] else #[1,5,0]) else (if i.val < 3 then #[2,5,0] else #[1,6,0])) : Array (Fin 8))[j.val]!
private def negWitness (i : Fin 4) (j : Fin 3) : Fin 8 := ((if i.val < 2 then (if i.val < 1 then #[1,5,0] else #[1,5,0]) else (if i.val < 3 then #[2,5,0] else #[1,6,0])) : Array (Fin 8))[j.val]!
private theorem pos_checked : ∀ i j, generators i*normalGenerators j*(generators i)⁻¹=
    (⟨rows (posWitness i j)⟩ : Source) := by decide +kernel
private theorem neg_checked : ∀ i j, (generators i)⁻¹*normalGenerators j*generators i=
    (⟨rows (negWitness i j)⟩ : Source) := by decide +kernel

instance normal : kernel.Normal := binaryNormal_of_generator_conjugates generators generators_full
  normalGenerators (fun i j => (pos_checked i j) ▸ row_mem (posWitness i j))
  (fun i j => (neg_checked i j) ▸ row_mem (negWitness i j))

private def representatives (i : Fin 2) : Source := ⟨((if i.val < 1 then 15 else 3) : Fin 16)⟩
private def quotientNext (i : Fin 2) (j : Fin 4) : Fin 2 := ((if i.val < 1 then #[0,1,1,1] else #[1,0,0,0]) : Array (Fin 2))[j.val]!
private def quotientPrev (i : Fin 2) (j : Fin 4) : Fin 2 := ((if i.val < 1 then #[0,1,1,1] else #[1,0,0,0]) : Array (Fin 2))[j.val]!
private def quotientParents (i : Fin 2) : Fin 2 := ((if i.val < 1 then 0 else 0) : Fin 2)
private def quotientLetters (i : Fin 2) : Fin 4 := ((if i.val < 1 then 0 else 1) : Fin 4)
private def stepWitness (i : Fin 2) (j : Fin 4) : Fin 8 := ((if i.val < 1 then #[0,7,5,1] else #[0,7,5,1]) : Array (Fin 8))[j.val]!
private theorem quotientStep_checked : ∀ i j,
    representatives (quotientNext i j)/(representatives i*generators j)=
      (⟨rows (stepWitness i j)⟩ : Source) := (by decide +kernel)

def cosets : BinaryNormalCosetCertificate generators kernel 2 where
  representatives := representatives
  identity := 0
  identity_mem := by
    have he : representatives 0=(⟨rows 7⟩ : Source) := by decide +kernel
    exact he ▸ row_mem 7
  next := quotientNext
  step_mem := fun i j => (quotientStep_checked i j) ▸ row_mem (stepWitness i j)
  rank i := i.val
  parent i _ := quotientParents i
  letter i _ := quotientLetters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

@[reducible] def state : BinaryNormalState generators where
  kernel := kernel
  normal := normal
  generatorCount := 3
  normalGenerators := normalGenerators
  generated := rfl
  quotientCount := 2
  cardinal := by rw [kernel_card,source_card]
  cosets := cosets
  prev := quotientPrev
  prev_next := (by decide +kernel)

end N10

namespace N11
def normalGenerators (j : Fin 3) : Source := ⟨((if j.val < 1 then 2 else (if j.val < 2 then 7 else 0)) : Fin 16)⟩
def kernel : Subgroup Source := Subgroup.closure (Set.range normalGenerators)
private def rows (i : Fin 8) : Fin 16 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 2) else (if i.val < 3 then 5 else 7)) else (if i.val < 6 then (if i.val < 5 then 8 else 11) else (if i.val < 7 then 12 else 15))) : Fin 16)
private def next (i : Fin 8) (j : Fin 3) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[2,4,7] else #[7,6,2]) else (if i.val < 3 then #[0,5,1] else #[5,7,4])) else (if i.val < 6 then (if i.val < 5 then #[6,0,3] else #[3,2,6]) else (if i.val < 7 then #[4,1,5] else #[1,3,0]))) : Array (Fin 8))[j.val]!
private def rank (i : Fin 8) : ℕ := (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 3 else 1) else (if i.val < 3 then 5 else 2)) else (if i.val < 6 then (if i.val < 5 then 7 else 6) else (if i.val < 7 then 4 else 0)))
private def parents (i : Fin 8) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 7 else 7) else (if i.val < 3 then 1 else 7)) else (if i.val < 6 then (if i.val < 5 then 3 else 3) else (if i.val < 7 then 1 else 7))) : Fin 8)
private def letters (i : Fin 8) : Fin 3 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 2 else 0) else (if i.val < 3 then 2 else 1)) else (if i.val < 6 then (if i.val < 5 then 2 else 0) else (if i.val < 7 then 1 else 0))) : Fin 3)

def normalCertificate : EncodedCayleyCertificate (binaryNormalRowEncoding normalGenerators) 8 where
  rows := rows
  identity := 7
  identity_eq := by decide +kernel
  next := next
  next_eq := (by decide +kernel)
  rank := rank
  parent i _ := parents i
  letter i hi := letters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

theorem normalRows_injective : Function.Injective normalCertificate.rows := by decide +kernel

theorem kernel_card : Nat.card kernel=8 := normalCertificate.card_closure normalRows_injective

theorem row_mem (i : Fin 8) : (⟨rows i⟩ : Source)∈kernel :=
  binaryNormalRow_mem normalCertificate i

private def posWitness (i : Fin 4) (j : Fin 3) : Fin 8 := ((if i.val < 2 then (if i.val < 1 then #[1,3,0] else #[1,3,0]) else (if i.val < 3 then #[2,3,0] else #[1,4,0])) : Array (Fin 8))[j.val]!
private def negWitness (i : Fin 4) (j : Fin 3) : Fin 8 := ((if i.val < 2 then (if i.val < 1 then #[1,3,0] else #[1,3,0]) else (if i.val < 3 then #[2,3,0] else #[1,4,0])) : Array (Fin 8))[j.val]!
private theorem pos_checked : ∀ i j, generators i*normalGenerators j*(generators i)⁻¹=
    (⟨rows (posWitness i j)⟩ : Source) := by decide +kernel
private theorem neg_checked : ∀ i j, (generators i)⁻¹*normalGenerators j*generators i=
    (⟨rows (negWitness i j)⟩ : Source) := by decide +kernel

instance normal : kernel.Normal := binaryNormal_of_generator_conjugates generators generators_full
  normalGenerators (fun i j => (pos_checked i j) ▸ row_mem (posWitness i j))
  (fun i j => (neg_checked i j) ▸ row_mem (negWitness i j))

private def representatives (i : Fin 2) : Source := ⟨((if i.val < 1 then 15 else 3) : Fin 16)⟩
private def quotientNext (i : Fin 2) (j : Fin 4) : Fin 2 := ((if i.val < 1 then #[0,1,0,1] else #[1,0,1,0]) : Array (Fin 2))[j.val]!
private def quotientPrev (i : Fin 2) (j : Fin 4) : Fin 2 := ((if i.val < 1 then #[0,1,0,1] else #[1,0,1,0]) : Array (Fin 2))[j.val]!
private def quotientParents (i : Fin 2) : Fin 2 := ((if i.val < 1 then 0 else 0) : Fin 2)
private def quotientLetters (i : Fin 2) : Fin 4 := ((if i.val < 1 then 0 else 1) : Fin 4)
private def stepWitness (i : Fin 2) (j : Fin 4) : Fin 8 := ((if i.val < 1 then #[0,7,3,1] else #[0,7,3,1]) : Array (Fin 8))[j.val]!
private theorem quotientStep_checked : ∀ i j,
    representatives (quotientNext i j)/(representatives i*generators j)=
      (⟨rows (stepWitness i j)⟩ : Source) := (by decide +kernel)

def cosets : BinaryNormalCosetCertificate generators kernel 2 where
  representatives := representatives
  identity := 0
  identity_mem := by
    have he : representatives 0=(⟨rows 7⟩ : Source) := by decide +kernel
    exact he ▸ row_mem 7
  next := quotientNext
  step_mem := fun i j => (quotientStep_checked i j) ▸ row_mem (stepWitness i j)
  rank i := i.val
  parent i _ := quotientParents i
  letter i _ := quotientLetters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

@[reducible] def state : BinaryNormalState generators where
  kernel := kernel
  normal := normal
  generatorCount := 3
  normalGenerators := normalGenerators
  generated := rfl
  quotientCount := 2
  cardinal := by rw [kernel_card,source_card]
  cosets := cosets
  prev := quotientPrev
  prev_next := (by decide +kernel)

end N11

namespace N12
def normalGenerators (j : Fin 3) : Source := ⟨((if j.val < 1 then 14 else (if j.val < 2 then 10 else 0)) : Fin 16)⟩
def kernel : Subgroup Source := Subgroup.closure (Set.range normalGenerators)
private def rows (i : Fin 8) : Fin 16 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 1) else (if i.val < 3 then 10 else 11)) else (if i.val < 6 then (if i.val < 5 then 12 else 13) else (if i.val < 7 then 14 else 15))) : Fin 16)
private def next (i : Fin 8) (j : Fin 3) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[1,5,7] else #[0,3,6]) else (if i.val < 3 then #[3,7,5] else #[2,1,4])) else (if i.val < 6 then (if i.val < 5 then #[5,6,3] else #[4,0,2]) else (if i.val < 7 then #[7,4,1] else #[6,2,0]))) : Array (Fin 8))[j.val]!
private def rank (i : Fin 8) : ℕ := (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 3 else 5) else (if i.val < 3 then 2 else 6)) else (if i.val < 6 then (if i.val < 5 then 4 else 7) else (if i.val < 7 then 1 else 0)))
private def parents (i : Fin 8) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 7 else 6) else (if i.val < 3 then 7 else 2)) else (if i.val < 6 then (if i.val < 5 then 6 else 2) else (if i.val < 7 then 7 else 7))) : Fin 8)
private def letters (i : Fin 8) : Fin 3 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 2 else 2) else (if i.val < 3 then 1 else 0)) else (if i.val < 6 then (if i.val < 5 then 1 else 2) else (if i.val < 7 then 0 else 0))) : Fin 3)

def normalCertificate : EncodedCayleyCertificate (binaryNormalRowEncoding normalGenerators) 8 where
  rows := rows
  identity := 7
  identity_eq := by decide +kernel
  next := next
  next_eq := (by decide +kernel)
  rank := rank
  parent i _ := parents i
  letter i hi := letters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

theorem normalRows_injective : Function.Injective normalCertificate.rows := by decide +kernel

theorem kernel_card : Nat.card kernel=8 := normalCertificate.card_closure normalRows_injective

theorem row_mem (i : Fin 8) : (⟨rows i⟩ : Source)∈kernel :=
  binaryNormalRow_mem normalCertificate i

private def posWitness (i : Fin 4) (j : Fin 3) : Fin 8 := ((if i.val < 2 then (if i.val < 1 then #[6,2,0] else #[6,2,0]) else (if i.val < 3 then #[1,2,0] else #[6,5,0])) : Array (Fin 8))[j.val]!
private def negWitness (i : Fin 4) (j : Fin 3) : Fin 8 := ((if i.val < 2 then (if i.val < 1 then #[6,2,0] else #[6,2,0]) else (if i.val < 3 then #[1,2,0] else #[6,5,0])) : Array (Fin 8))[j.val]!
private theorem pos_checked : ∀ i j, generators i*normalGenerators j*(generators i)⁻¹=
    (⟨rows (posWitness i j)⟩ : Source) := by decide +kernel
private theorem neg_checked : ∀ i j, (generators i)⁻¹*normalGenerators j*generators i=
    (⟨rows (negWitness i j)⟩ : Source) := by decide +kernel

instance normal : kernel.Normal := binaryNormal_of_generator_conjugates generators generators_full
  normalGenerators (fun i j => (pos_checked i j) ▸ row_mem (posWitness i j))
  (fun i j => (neg_checked i j) ▸ row_mem (negWitness i j))

private def representatives (i : Fin 2) : Source := ⟨((if i.val < 1 then 15 else 3) : Fin 16)⟩
private def quotientNext (i : Fin 2) (j : Fin 4) : Fin 2 := ((if i.val < 1 then #[0,1,1,0] else #[1,0,0,1]) : Array (Fin 2))[j.val]!
private def quotientPrev (i : Fin 2) (j : Fin 4) : Fin 2 := ((if i.val < 1 then #[0,1,1,0] else #[1,0,0,1]) : Array (Fin 2))[j.val]!
private def quotientParents (i : Fin 2) : Fin 2 := ((if i.val < 1 then 0 else 0) : Fin 2)
private def quotientLetters (i : Fin 2) : Fin 4 := ((if i.val < 1 then 0 else 1) : Fin 4)
private def stepWitness (i : Fin 2) (j : Fin 4) : Fin 8 := ((if i.val < 1 then #[0,7,2,6] else #[0,7,2,6]) : Array (Fin 8))[j.val]!
private theorem quotientStep_checked : ∀ i j,
    representatives (quotientNext i j)/(representatives i*generators j)=
      (⟨rows (stepWitness i j)⟩ : Source) := (by decide +kernel)

def cosets : BinaryNormalCosetCertificate generators kernel 2 where
  representatives := representatives
  identity := 0
  identity_mem := by
    have he : representatives 0=(⟨rows 7⟩ : Source) := by decide +kernel
    exact he ▸ row_mem 7
  next := quotientNext
  step_mem := fun i j => (quotientStep_checked i j) ▸ row_mem (stepWitness i j)
  rank i := i.val
  parent i _ := quotientParents i
  letter i _ := quotientLetters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

@[reducible] def state : BinaryNormalState generators where
  kernel := kernel
  normal := normal
  generatorCount := 3
  normalGenerators := normalGenerators
  generated := rfl
  quotientCount := 2
  cardinal := by rw [kernel_card,source_card]
  cosets := cosets
  prev := quotientPrev
  prev_next := (by decide +kernel)

end N12

namespace N13
def normalGenerators (j : Fin 3) : Source := ⟨((if j.val < 1 then 14 else (if j.val < 2 then 7 else 0)) : Fin 16)⟩
def kernel : Subgroup Source := Subgroup.closure (Set.range normalGenerators)
private def rows (i : Fin 8) : Fin 16 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 1) else (if i.val < 3 then 6 else 7)) else (if i.val < 6 then (if i.val < 5 then 8 else 9) else (if i.val < 7 then 14 else 15))) : Fin 16)
private def next (i : Fin 8) (j : Fin 3) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[1,4,7] else #[0,2,6]) else (if i.val < 3 then #[3,1,5] else #[2,7,4])) else (if i.val < 6 then (if i.val < 5 then #[5,0,3] else #[4,6,2]) else (if i.val < 7 then #[7,5,1] else #[6,3,0]))) : Array (Fin 8))[j.val]!
private def rank (i : Fin 8) : ℕ := (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 3 else 5) else (if i.val < 3 then 6 else 2)) else (if i.val < 6 then (if i.val < 5 then 7 else 4) else (if i.val < 7 then 1 else 0)))
private def parents (i : Fin 8) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 7 else 6) else (if i.val < 3 then 3 else 7)) else (if i.val < 6 then (if i.val < 5 then 3 else 6) else (if i.val < 7 then 7 else 7))) : Fin 8)
private def letters (i : Fin 8) : Fin 3 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 2 else 2) else (if i.val < 3 then 0 else 1)) else (if i.val < 6 then (if i.val < 5 then 2 else 1) else (if i.val < 7 then 0 else 0))) : Fin 3)

def normalCertificate : EncodedCayleyCertificate (binaryNormalRowEncoding normalGenerators) 8 where
  rows := rows
  identity := 7
  identity_eq := by decide +kernel
  next := next
  next_eq := (by decide +kernel)
  rank := rank
  parent i _ := parents i
  letter i hi := letters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

theorem normalRows_injective : Function.Injective normalCertificate.rows := by decide +kernel

theorem kernel_card : Nat.card kernel=8 := normalCertificate.card_closure normalRows_injective

theorem row_mem (i : Fin 8) : (⟨rows i⟩ : Source)∈kernel :=
  binaryNormalRow_mem normalCertificate i

private def posWitness (i : Fin 4) (j : Fin 3) : Fin 8 := ((if i.val < 2 then (if i.val < 1 then #[6,3,0] else #[6,3,0]) else (if i.val < 3 then #[1,3,0] else #[6,4,0])) : Array (Fin 8))[j.val]!
private def negWitness (i : Fin 4) (j : Fin 3) : Fin 8 := ((if i.val < 2 then (if i.val < 1 then #[6,3,0] else #[6,3,0]) else (if i.val < 3 then #[1,3,0] else #[6,4,0])) : Array (Fin 8))[j.val]!
private theorem pos_checked : ∀ i j, generators i*normalGenerators j*(generators i)⁻¹=
    (⟨rows (posWitness i j)⟩ : Source) := by decide +kernel
private theorem neg_checked : ∀ i j, (generators i)⁻¹*normalGenerators j*generators i=
    (⟨rows (negWitness i j)⟩ : Source) := by decide +kernel

instance normal : kernel.Normal := binaryNormal_of_generator_conjugates generators generators_full
  normalGenerators (fun i j => (pos_checked i j) ▸ row_mem (posWitness i j))
  (fun i j => (neg_checked i j) ▸ row_mem (negWitness i j))

private def representatives (i : Fin 2) : Source := ⟨((if i.val < 1 then 15 else 3) : Fin 16)⟩
private def quotientNext (i : Fin 2) (j : Fin 4) : Fin 2 := ((if i.val < 1 then #[0,1,0,0] else #[1,0,1,1]) : Array (Fin 2))[j.val]!
private def quotientPrev (i : Fin 2) (j : Fin 4) : Fin 2 := ((if i.val < 1 then #[0,1,0,0] else #[1,0,1,1]) : Array (Fin 2))[j.val]!
private def quotientParents (i : Fin 2) : Fin 2 := ((if i.val < 1 then 0 else 0) : Fin 2)
private def quotientLetters (i : Fin 2) : Fin 4 := ((if i.val < 1 then 0 else 1) : Fin 4)
private def stepWitness (i : Fin 2) (j : Fin 4) : Fin 8 := ((if i.val < 1 then #[0,7,3,6] else #[0,7,3,6]) : Array (Fin 8))[j.val]!
private theorem quotientStep_checked : ∀ i j,
    representatives (quotientNext i j)/(representatives i*generators j)=
      (⟨rows (stepWitness i j)⟩ : Source) := (by decide +kernel)

def cosets : BinaryNormalCosetCertificate generators kernel 2 where
  representatives := representatives
  identity := 0
  identity_mem := by
    have he : representatives 0=(⟨rows 7⟩ : Source) := by decide +kernel
    exact he ▸ row_mem 7
  next := quotientNext
  step_mem := fun i j => (quotientStep_checked i j) ▸ row_mem (stepWitness i j)
  rank i := i.val
  parent i _ := quotientParents i
  letter i _ := quotientLetters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

@[reducible] def state : BinaryNormalState generators where
  kernel := kernel
  normal := normal
  generatorCount := 3
  normalGenerators := normalGenerators
  generated := rfl
  quotientCount := 2
  cardinal := by rw [kernel_card,source_card]
  cosets := cosets
  prev := quotientPrev
  prev_next := (by decide +kernel)

end N13

namespace N14
def normalGenerators (j : Fin 2) : Source := ⟨((if j.val < 1 then 3 else 0) : Fin 16)⟩
def kernel : Subgroup Source := Subgroup.closure (Set.range normalGenerators)
private def rows (i : Fin 4) : Fin 16 := ((if i.val < 2 then (if i.val < 1 then 0 else 3) else (if i.val < 3 then 4 else 15)) : Fin 16)
private def next (i : Fin 4) (j : Fin 2) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[2,3] else #[3,2]) else (if i.val < 3 then #[0,1] else #[1,0])) : Array (Fin 4))[j.val]!
private def rank (i : Fin 4) : ℕ := (if i.val < 2 then (if i.val < 1 then 2 else 1) else (if i.val < 3 then 3 else 0))
private def parents (i : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then 3 else 3) else (if i.val < 3 then 1 else 3)) : Fin 4)
private def letters (i : Fin 4) : Fin 2 := ((if i.val < 2 then (if i.val < 1 then 1 else 0) else (if i.val < 3 then 1 else 0)) : Fin 2)

def normalCertificate : EncodedCayleyCertificate (binaryNormalRowEncoding normalGenerators) 4 where
  rows := rows
  identity := 3
  identity_eq := by decide +kernel
  next := next
  next_eq := (by decide +kernel)
  rank := rank
  parent i _ := parents i
  letter i hi := letters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

theorem normalRows_injective : Function.Injective normalCertificate.rows := by decide +kernel

theorem kernel_card : Nat.card kernel=4 := normalCertificate.card_closure normalRows_injective

theorem row_mem (i : Fin 4) : (⟨rows i⟩ : Source)∈kernel :=
  binaryNormalRow_mem normalCertificate i

private def posWitness (i : Fin 4) (j : Fin 2) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[1,0] else #[1,0]) else (if i.val < 3 then #[1,0] else #[1,0])) : Array (Fin 4))[j.val]!
private def negWitness (i : Fin 4) (j : Fin 2) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[1,0] else #[1,0]) else (if i.val < 3 then #[1,0] else #[1,0])) : Array (Fin 4))[j.val]!
private theorem pos_checked : ∀ i j, generators i*normalGenerators j*(generators i)⁻¹=
    (⟨rows (posWitness i j)⟩ : Source) := by decide +kernel
private theorem neg_checked : ∀ i j, (generators i)⁻¹*normalGenerators j*generators i=
    (⟨rows (negWitness i j)⟩ : Source) := by decide +kernel

instance normal : kernel.Normal := binaryNormal_of_generator_conjugates generators generators_full
  normalGenerators (fun i j => (pos_checked i j) ▸ row_mem (posWitness i j))
  (fun i j => (neg_checked i j) ▸ row_mem (negWitness i j))

private def representatives (i : Fin 4) : Source := ⟨((if i.val < 2 then (if i.val < 1 then 15 else 7) else (if i.val < 3 then 14 else 6)) : Fin 16)⟩
private def quotientNext (i : Fin 4) (j : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[0,0,1,2] else #[1,1,0,3]) else (if i.val < 3 then #[2,2,3,0] else #[3,3,2,1])) : Array (Fin 4))[j.val]!
private def quotientPrev (i : Fin 4) (j : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[0,0,1,2] else #[1,1,0,3]) else (if i.val < 3 then #[2,2,3,0] else #[3,3,2,1])) : Array (Fin 4))[j.val]!
private def quotientParents (i : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then 0 else 0) else (if i.val < 3 then 0 else 1)) : Fin 4)
private def quotientLetters (i : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then 0 else 2) else (if i.val < 3 then 3 else 3)) : Fin 4)
private def stepWitness (i : Fin 4) (j : Fin 4) : Fin 4 := ((if i.val < 2 then (if i.val < 1 then #[0,1,3,3] else #[0,1,3,3]) else (if i.val < 3 then #[0,1,0,3] else #[0,1,0,3])) : Array (Fin 4))[j.val]!
private theorem quotientStep_checked : ∀ i j,
    representatives (quotientNext i j)/(representatives i*generators j)=
      (⟨rows (stepWitness i j)⟩ : Source) := (by decide +kernel)

def cosets : BinaryNormalCosetCertificate generators kernel 4 where
  representatives := representatives
  identity := 0
  identity_mem := by
    have he : representatives 0=(⟨rows 3⟩ : Source) := by decide +kernel
    exact he ▸ row_mem 3
  next := quotientNext
  step_mem := fun i j => (quotientStep_checked i j) ▸ row_mem (stepWitness i j)
  rank i := i.val
  parent i _ := quotientParents i
  letter i _ := quotientLetters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

@[reducible] def state : BinaryNormalState generators where
  kernel := kernel
  normal := normal
  generatorCount := 2
  normalGenerators := normalGenerators
  generated := rfl
  quotientCount := 4
  cardinal := by rw [kernel_card,source_card]
  cosets := cosets
  prev := quotientPrev
  prev_next := (by decide +kernel)

end N14

namespace N15
def normalGenerators (j : Fin 2) : Source := ⟨((if j.val < 1 then 6 else 3) : Fin 16)⟩
def kernel : Subgroup Source := Subgroup.closure (Set.range normalGenerators)
private def rows (i : Fin 8) : Fin 16 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 3) else (if i.val < 3 then 4 else 6)) else (if i.val < 6 then (if i.val < 5 then 9 else 11) else (if i.val < 7 then 12 else 15))) : Fin 16)
private def next (i : Fin 8) (j : Fin 2) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[4,2] else #[5,7]) else (if i.val < 3 then #[6,0] else #[0,5])) else (if i.val < 6 then (if i.val < 5 then #[7,6] else #[2,3]) else (if i.val < 7 then #[1,4] else #[3,1]))) : Array (Fin 8))[j.val]!
private def rank (i : Fin 8) : ℕ := (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 3 else 2) else (if i.val < 3 then 6 else 1)) else (if i.val < 6 then (if i.val < 5 then 5 else 4) else (if i.val < 7 then 7 else 0)))
private def parents (i : Fin 8) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 3 else 7) else (if i.val < 3 then 0 else 7)) else (if i.val < 6 then (if i.val < 5 then 0 else 3) else (if i.val < 7 then 4 else 7))) : Fin 8)
private def letters (i : Fin 8) : Fin 2 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 1) else (if i.val < 3 then 1 else 0)) else (if i.val < 6 then (if i.val < 5 then 0 else 1) else (if i.val < 7 then 1 else 0))) : Fin 2)

def normalCertificate : EncodedCayleyCertificate (binaryNormalRowEncoding normalGenerators) 8 where
  rows := rows
  identity := 7
  identity_eq := by decide +kernel
  next := next
  next_eq := (by decide +kernel)
  rank := rank
  parent i _ := parents i
  letter i hi := letters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

theorem normalRows_injective : Function.Injective normalCertificate.rows := by decide +kernel

theorem kernel_card : Nat.card kernel=8 := normalCertificate.card_closure normalRows_injective

theorem row_mem (i : Fin 8) : (⟨rows i⟩ : Source)∈kernel :=
  binaryNormalRow_mem normalCertificate i

private def posWitness (i : Fin 4) (j : Fin 2) : Fin 8 := ((if i.val < 2 then (if i.val < 1 then #[3,1] else #[3,1]) else (if i.val < 3 then #[4,1] else #[4,1])) : Array (Fin 8))[j.val]!
private def negWitness (i : Fin 4) (j : Fin 2) : Fin 8 := ((if i.val < 2 then (if i.val < 1 then #[3,1] else #[3,1]) else (if i.val < 3 then #[4,1] else #[4,1])) : Array (Fin 8))[j.val]!
private theorem pos_checked : ∀ i j, generators i*normalGenerators j*(generators i)⁻¹=
    (⟨rows (posWitness i j)⟩ : Source) := by decide +kernel
private theorem neg_checked : ∀ i j, (generators i)⁻¹*normalGenerators j*generators i=
    (⟨rows (negWitness i j)⟩ : Source) := by decide +kernel

instance normal : kernel.Normal := binaryNormal_of_generator_conjugates generators generators_full
  normalGenerators (fun i j => (pos_checked i j) ▸ row_mem (posWitness i j))
  (fun i j => (neg_checked i j) ▸ row_mem (negWitness i j))

private def representatives (i : Fin 2) : Source := ⟨((if i.val < 1 then 15 else 7) : Fin 16)⟩
private def quotientNext (i : Fin 2) (j : Fin 4) : Fin 2 := ((if i.val < 1 then #[0,0,1,1] else #[1,1,0,0]) : Array (Fin 2))[j.val]!
private def quotientPrev (i : Fin 2) (j : Fin 4) : Fin 2 := ((if i.val < 1 then #[0,0,1,1] else #[1,1,0,0]) : Array (Fin 2))[j.val]!
private def quotientParents (i : Fin 2) : Fin 2 := ((if i.val < 1 then 0 else 0) : Fin 2)
private def quotientLetters (i : Fin 2) : Fin 4 := ((if i.val < 1 then 0 else 2) : Fin 4)
private def stepWitness (i : Fin 2) (j : Fin 4) : Fin 8 := ((if i.val < 1 then #[0,1,7,3] else #[0,1,7,4]) : Array (Fin 8))[j.val]!
private theorem quotientStep_checked : ∀ i j,
    representatives (quotientNext i j)/(representatives i*generators j)=
      (⟨rows (stepWitness i j)⟩ : Source) := (by decide +kernel)

def cosets : BinaryNormalCosetCertificate generators kernel 2 where
  representatives := representatives
  identity := 0
  identity_mem := by
    have he : representatives 0=(⟨rows 7⟩ : Source) := by decide +kernel
    exact he ▸ row_mem 7
  next := quotientNext
  step_mem := fun i j => (quotientStep_checked i j) ▸ row_mem (stepWitness i j)
  rank i := i.val
  parent i _ := quotientParents i
  letter i _ := quotientLetters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

@[reducible] def state : BinaryNormalState generators where
  kernel := kernel
  normal := normal
  generatorCount := 2
  normalGenerators := normalGenerators
  generated := rfl
  quotientCount := 2
  cardinal := by rw [kernel_card,source_card]
  cosets := cosets
  prev := quotientPrev
  prev_next := (by decide +kernel)

end N15

namespace N16
def normalGenerators (j : Fin 3) : Source := ⟨((if j.val < 1 then 14 else (if j.val < 2 then 3 else 0)) : Fin 16)⟩
def kernel : Subgroup Source := Subgroup.closure (Set.range normalGenerators)
private def rows (i : Fin 8) : Fin 16 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 1) else (if i.val < 3 then 2 else 3)) else (if i.val < 6 then (if i.val < 5 then 4 else 5) else (if i.val < 7 then 14 else 15))) : Fin 16)
private def next (i : Fin 8) (j : Fin 3) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[1,4,7] else #[0,5,6]) else (if i.val < 3 then #[3,6,5] else #[2,7,4])) else (if i.val < 6 then (if i.val < 5 then #[5,0,3] else #[4,1,2]) else (if i.val < 7 then #[7,2,1] else #[6,3,0]))) : Array (Fin 8))[j.val]!
private def rank (i : Fin 8) : ℕ := (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 3 else 5) else (if i.val < 3 then 4 else 2)) else (if i.val < 6 then (if i.val < 5 then 6 else 7) else (if i.val < 7 then 1 else 0)))
private def parents (i : Fin 8) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 7 else 6) else (if i.val < 3 then 6 else 7)) else (if i.val < 6 then (if i.val < 5 then 3 else 2) else (if i.val < 7 then 7 else 7))) : Fin 8)
private def letters (i : Fin 8) : Fin 3 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 2 else 2) else (if i.val < 3 then 1 else 1)) else (if i.val < 6 then (if i.val < 5 then 2 else 2) else (if i.val < 7 then 0 else 0))) : Fin 3)

def normalCertificate : EncodedCayleyCertificate (binaryNormalRowEncoding normalGenerators) 8 where
  rows := rows
  identity := 7
  identity_eq := by decide +kernel
  next := next
  next_eq := (by decide +kernel)
  rank := rank
  parent i _ := parents i
  letter i hi := letters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

theorem normalRows_injective : Function.Injective normalCertificate.rows := by decide +kernel

theorem kernel_card : Nat.card kernel=8 := normalCertificate.card_closure normalRows_injective

theorem row_mem (i : Fin 8) : (⟨rows i⟩ : Source)∈kernel :=
  binaryNormalRow_mem normalCertificate i

private def posWitness (i : Fin 4) (j : Fin 3) : Fin 8 := ((if i.val < 2 then (if i.val < 1 then #[6,3,0] else #[6,3,0]) else (if i.val < 3 then #[1,3,0] else #[6,3,0])) : Array (Fin 8))[j.val]!
private def negWitness (i : Fin 4) (j : Fin 3) : Fin 8 := ((if i.val < 2 then (if i.val < 1 then #[6,3,0] else #[6,3,0]) else (if i.val < 3 then #[1,3,0] else #[6,3,0])) : Array (Fin 8))[j.val]!
private theorem pos_checked : ∀ i j, generators i*normalGenerators j*(generators i)⁻¹=
    (⟨rows (posWitness i j)⟩ : Source) := by decide +kernel
private theorem neg_checked : ∀ i j, (generators i)⁻¹*normalGenerators j*generators i=
    (⟨rows (negWitness i j)⟩ : Source) := by decide +kernel

instance normal : kernel.Normal := binaryNormal_of_generator_conjugates generators generators_full
  normalGenerators (fun i j => (pos_checked i j) ▸ row_mem (posWitness i j))
  (fun i j => (neg_checked i j) ▸ row_mem (negWitness i j))

private def representatives (i : Fin 2) : Source := ⟨((if i.val < 1 then 15 else 7) : Fin 16)⟩
private def quotientNext (i : Fin 2) (j : Fin 4) : Fin 2 := ((if i.val < 1 then #[0,0,1,0] else #[1,1,0,1]) : Array (Fin 2))[j.val]!
private def quotientPrev (i : Fin 2) (j : Fin 4) : Fin 2 := ((if i.val < 1 then #[0,0,1,0] else #[1,1,0,1]) : Array (Fin 2))[j.val]!
private def quotientParents (i : Fin 2) : Fin 2 := ((if i.val < 1 then 0 else 0) : Fin 2)
private def quotientLetters (i : Fin 2) : Fin 4 := ((if i.val < 1 then 0 else 2) : Fin 4)
private def stepWitness (i : Fin 2) (j : Fin 4) : Fin 8 := ((if i.val < 1 then #[0,3,7,6] else #[0,3,7,1]) : Array (Fin 8))[j.val]!
private theorem quotientStep_checked : ∀ i j,
    representatives (quotientNext i j)/(representatives i*generators j)=
      (⟨rows (stepWitness i j)⟩ : Source) := (by decide +kernel)

def cosets : BinaryNormalCosetCertificate generators kernel 2 where
  representatives := representatives
  identity := 0
  identity_mem := by
    have he : representatives 0=(⟨rows 7⟩ : Source) := by decide +kernel
    exact he ▸ row_mem 7
  next := quotientNext
  step_mem := fun i j => (quotientStep_checked i j) ▸ row_mem (stepWitness i j)
  rank i := i.val
  parent i _ := quotientParents i
  letter i _ := quotientLetters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

@[reducible] def state : BinaryNormalState generators where
  kernel := kernel
  normal := normal
  generatorCount := 3
  normalGenerators := normalGenerators
  generated := rfl
  quotientCount := 2
  cardinal := by rw [kernel_card,source_card]
  cosets := cosets
  prev := quotientPrev
  prev_next := (by decide +kernel)

end N16

namespace N17
def normalGenerators (j : Fin 3) : Source := ⟨((if j.val < 1 then 3 else (if j.val < 2 then 7 else 0)) : Fin 16)⟩
def kernel : Subgroup Source := Subgroup.closure (Set.range normalGenerators)
private def rows (i : Fin 8) : Fin 16 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 3) else (if i.val < 3 then 4 else 7)) else (if i.val < 6 then (if i.val < 5 then 8 else 10) else (if i.val < 7 then 13 else 15))) : Fin 16)
private def next (i : Fin 8) (j : Fin 3) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[2,4,7] else #[7,5,2]) else (if i.val < 3 then #[0,6,1] else #[5,7,4])) else (if i.val < 6 then (if i.val < 5 then #[6,0,3] else #[3,1,6]) else (if i.val < 7 then #[4,2,5] else #[1,3,0]))) : Array (Fin 8))[j.val]!
private def rank (i : Fin 8) : ℕ := (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 3 else 1) else (if i.val < 3 then 5 else 2)) else (if i.val < 6 then (if i.val < 5 then 6 else 4) else (if i.val < 7 then 7 else 0)))
private def parents (i : Fin 8) : Fin 8 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 7 else 7) else (if i.val < 3 then 1 else 7)) else (if i.val < 6 then (if i.val < 5 then 3 else 1) else (if i.val < 7 then 5 else 7))) : Fin 8)
private def letters (i : Fin 8) : Fin 3 := ((if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 2 else 0) else (if i.val < 3 then 2 else 1)) else (if i.val < 6 then (if i.val < 5 then 2 else 1) else (if i.val < 7 then 2 else 0))) : Fin 3)

def normalCertificate : EncodedCayleyCertificate (binaryNormalRowEncoding normalGenerators) 8 where
  rows := rows
  identity := 7
  identity_eq := by decide +kernel
  next := next
  next_eq := (by decide +kernel)
  rank := rank
  parent i _ := parents i
  letter i hi := letters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

theorem normalRows_injective : Function.Injective normalCertificate.rows := by decide +kernel

theorem kernel_card : Nat.card kernel=8 := normalCertificate.card_closure normalRows_injective

theorem row_mem (i : Fin 8) : (⟨rows i⟩ : Source)∈kernel :=
  binaryNormalRow_mem normalCertificate i

private def posWitness (i : Fin 4) (j : Fin 3) : Fin 8 := ((if i.val < 2 then (if i.val < 1 then #[1,3,0] else #[1,3,0]) else (if i.val < 3 then #[1,3,0] else #[1,4,0])) : Array (Fin 8))[j.val]!
private def negWitness (i : Fin 4) (j : Fin 3) : Fin 8 := ((if i.val < 2 then (if i.val < 1 then #[1,3,0] else #[1,3,0]) else (if i.val < 3 then #[1,3,0] else #[1,4,0])) : Array (Fin 8))[j.val]!
private theorem pos_checked : ∀ i j, generators i*normalGenerators j*(generators i)⁻¹=
    (⟨rows (posWitness i j)⟩ : Source) := by decide +kernel
private theorem neg_checked : ∀ i j, (generators i)⁻¹*normalGenerators j*generators i=
    (⟨rows (negWitness i j)⟩ : Source) := by decide +kernel

instance normal : kernel.Normal := binaryNormal_of_generator_conjugates generators generators_full
  normalGenerators (fun i j => (pos_checked i j) ▸ row_mem (posWitness i j))
  (fun i j => (neg_checked i j) ▸ row_mem (negWitness i j))

private def representatives (i : Fin 2) : Source := ⟨((if i.val < 1 then 15 else 14) : Fin 16)⟩
private def quotientNext (i : Fin 2) (j : Fin 4) : Fin 2 := ((if i.val < 1 then #[0,0,0,1] else #[1,1,1,0]) : Array (Fin 2))[j.val]!
private def quotientPrev (i : Fin 2) (j : Fin 4) : Fin 2 := ((if i.val < 1 then #[0,0,0,1] else #[1,1,1,0]) : Array (Fin 2))[j.val]!
private def quotientParents (i : Fin 2) : Fin 2 := ((if i.val < 1 then 0 else 0) : Fin 2)
private def quotientLetters (i : Fin 2) : Fin 4 := ((if i.val < 1 then 0 else 3) : Fin 4)
private def stepWitness (i : Fin 2) (j : Fin 4) : Fin 8 := ((if i.val < 1 then #[0,1,3,7] else #[0,1,4,7]) : Array (Fin 8))[j.val]!
private theorem quotientStep_checked : ∀ i j,
    representatives (quotientNext i j)/(representatives i*generators j)=
      (⟨rows (stepWitness i j)⟩ : Source) := (by decide +kernel)

def cosets : BinaryNormalCosetCertificate generators kernel 2 where
  representatives := representatives
  identity := 0
  identity_mem := by
    have he : representatives 0=(⟨rows 7⟩ : Source) := by decide +kernel
    exact he ▸ row_mem 7
  next := quotientNext
  step_mem := fun i j => (quotientStep_checked i j) ▸ row_mem (stepWitness i j)
  rank i := i.val
  parent i _ := quotientParents i
  letter i _ := quotientLetters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

@[reducible] def state : BinaryNormalState generators where
  kernel := kernel
  normal := normal
  generatorCount := 3
  normalGenerators := normalGenerators
  generated := rfl
  quotientCount := 2
  cardinal := by rw [kernel_card,source_card]
  cosets := cosets
  prev := quotientPrev
  prev_next := (by decide +kernel)

end N17

namespace N18
def normalGenerators (j : Fin 4) : Source := ⟨((if j.val < 2 then (if j.val < 1 then 14 else 3) else (if j.val < 3 then 7 else 0)) : Fin 16)⟩
def kernel : Subgroup Source := Subgroup.closure (Set.range normalGenerators)
private def rows (i : Fin 16) : Fin 16 := ((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 0 else 1) else (if i.val < 3 then 2 else 3)) else (if i.val < 6 then (if i.val < 5 then 4 else 5) else (if i.val < 7 then 6 else 7))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 8 else 9) else (if i.val < 11 then 10 else 11)) else (if i.val < 14 then (if i.val < 13 then 12 else 13) else (if i.val < 15 then 14 else 15)))) : Fin 16)
private def next (i : Fin 16) (j : Fin 4) : Fin 16 := ((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then #[1,4,8,15] else #[0,5,6,14]) else (if i.val < 3 then #[3,14,12,5] else #[2,15,10,4])) else (if i.val < 6 then (if i.val < 5 then #[5,0,13,3] else #[4,1,11,2]) else (if i.val < 7 then #[7,11,1,9] else #[6,10,15,8]))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then #[9,13,0,7] else #[8,12,14,6]) else (if i.val < 11 then #[11,7,3,13] else #[10,6,5,12])) else (if i.val < 14 then (if i.val < 13 then #[13,9,2,11] else #[12,8,4,10]) else (if i.val < 15 then #[15,2,9,1] else #[14,3,7,0])))) : Array (Fin 16))[j.val]!
private def rank (i : Fin 16) : ℕ := (if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 4 else 7) else (if i.val < 3 then 5 else 2)) else (if i.val < 6 then (if i.val < 5 then 9 else 13) else (if i.val < 7 then 10 else 3))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 11 else 6) else (if i.val < 11 then 8 else 14)) else (if i.val < 14 then (if i.val < 13 then 12 else 15) else (if i.val < 15 then 1 else 0))))
private def parents (i : Fin 16) : Fin 16 := ((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 15 else 14) else (if i.val < 3 then 14 else 15)) else (if i.val < 6 then (if i.val < 5 then 3 else 2) else (if i.val < 7 then 7 else 15))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 7 else 14) else (if i.val < 11 then 3 else 10)) else (if i.val < 14 then (if i.val < 13 then 2 else 10) else (if i.val < 15 then 15 else 15)))) : Fin 16)
private def letters (i : Fin 16) : Fin 4 := ((if i.val < 8 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then 3 else 3) else (if i.val < 3 then 1 else 1)) else (if i.val < 6 then (if i.val < 5 then 3 else 3) else (if i.val < 7 then 0 else 2))) else (if i.val < 12 then (if i.val < 10 then (if i.val < 9 then 3 else 2) else (if i.val < 11 then 2 else 0)) else (if i.val < 14 then (if i.val < 13 then 2 else 3) else (if i.val < 15 then 0 else 0)))) : Fin 4)

def normalCertificate : EncodedCayleyCertificate (binaryNormalRowEncoding normalGenerators) 16 where
  rows := rows
  identity := 15
  identity_eq := by decide +kernel
  next := next
  next_eq := (by decide +kernel)
  rank := rank
  parent i _ := parents i
  letter i hi := letters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

theorem normalRows_injective : Function.Injective normalCertificate.rows := by decide +kernel

theorem kernel_card : Nat.card kernel=16 := normalCertificate.card_closure normalRows_injective

theorem row_mem (i : Fin 16) : (⟨rows i⟩ : Source)∈kernel :=
  binaryNormalRow_mem normalCertificate i

private def posWitness (i : Fin 4) (j : Fin 4) : Fin 16 := ((if i.val < 2 then (if i.val < 1 then #[14,3,7,0] else #[14,3,7,0]) else (if i.val < 3 then #[1,3,7,0] else #[14,3,8,0])) : Array (Fin 16))[j.val]!
private def negWitness (i : Fin 4) (j : Fin 4) : Fin 16 := ((if i.val < 2 then (if i.val < 1 then #[14,3,7,0] else #[14,3,7,0]) else (if i.val < 3 then #[1,3,7,0] else #[14,3,8,0])) : Array (Fin 16))[j.val]!
private theorem pos_checked : ∀ i j, generators i*normalGenerators j*(generators i)⁻¹=
    (⟨rows (posWitness i j)⟩ : Source) := by decide +kernel
private theorem neg_checked : ∀ i j, (generators i)⁻¹*normalGenerators j*generators i=
    (⟨rows (negWitness i j)⟩ : Source) := by decide +kernel

instance normal : kernel.Normal := binaryNormal_of_generator_conjugates generators generators_full
  normalGenerators (fun i j => (pos_checked i j) ▸ row_mem (posWitness i j))
  (fun i j => (neg_checked i j) ▸ row_mem (negWitness i j))

private def representatives (i : Fin 1) : Source := ⟨(15 : Fin 16)⟩
private def quotientNext (i : Fin 1) (j : Fin 4) : Fin 1 := (#[0,0,0,0] : Array (Fin 1))[j.val]!
private def quotientPrev (i : Fin 1) (j : Fin 4) : Fin 1 := (#[0,0,0,0] : Array (Fin 1))[j.val]!
private def quotientParents (i : Fin 1) : Fin 1 := (0 : Fin 1)
private def quotientLetters (i : Fin 1) : Fin 4 := (0 : Fin 4)
private def stepWitness (i : Fin 1) (j : Fin 4) : Fin 16 := (#[0,3,7,14] : Array (Fin 16))[j.val]!
private theorem quotientStep_checked : ∀ i j,
    representatives (quotientNext i j)/(representatives i*generators j)=
      (⟨rows (stepWitness i j)⟩ : Source) := (by decide +kernel)

def cosets : BinaryNormalCosetCertificate generators kernel 1 where
  representatives := representatives
  identity := 0
  identity_mem := by
    have he : representatives 0=(⟨rows 15⟩ : Source) := by decide +kernel
    exact he ▸ row_mem 15
  next := quotientNext
  step_mem := fun i j => (quotientStep_checked i j) ▸ row_mem (stepWitness i j)
  rank i := i.val
  parent i _ := quotientParents i
  letter i _ := quotientLetters i
  parent_lt := (by decide +kernel)
  parent_next := (by decide +kernel)

@[reducible] def state : BinaryNormalState generators where
  kernel := kernel
  normal := normal
  generatorCount := 4
  normalGenerators := normalGenerators
  generated := rfl
  quotientCount := 1
  cardinal := by rw [kernel_card,source_card]
  cosets := cosets
  prev := quotientPrev
  prev_next := (by decide +kernel)

end N18

@[reducible] def states (i : Fin 19) : BinaryNormalState generators :=
  (if i.val < 9 then (if i.val < 4 then (if i.val < 2 then (if i.val < 1 then N0.state else N1.state) else (if i.val < 3 then N2.state else N3.state)) else (if i.val < 6 then (if i.val < 5 then N4.state else N5.state) else (if i.val < 7 then N6.state else (if i.val < 8 then N7.state else N8.state)))) else (if i.val < 14 then (if i.val < 11 then (if i.val < 10 then N9.state else N10.state) else (if i.val < 12 then N11.state else (if i.val < 13 then N12.state else N13.state))) else (if i.val < 16 then (if i.val < 15 then N14.state else N15.state) else (if i.val < 17 then N16.state else (if i.val < 18 then N17.state else N18.state)))))

end SymmetricSubgroupAsymptotics.BinaryNormal8T9
